In [3]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from src.tuning import *
from src.modeling import *
from src.data_split import *
from src.preprocessing import *

c:\Users\sokol\Desktop\Проект Регрессия\real-estate-price-prediction\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\sokol\Desktop\Проект Регрессия\real-estate-price-prediction\src\tuning.py:20: DtypeWarning: Columns (0: old_education_build_share, 1: provision_doctors) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv('../data/train_test/holdout/train_full.csv', index_col='id', parse_dates=['timestamp'])

In [5]:
best_params_cat, best_rmsle_cat = tune_busting('catboost')
best_params_lgb, best_rmsle_lgb = tune_busting('lightgbm')
best_params_xgb, best_rmsle_xgb = tune_busting('xgboost')

[I 2026-06-12 20:35:12,066] A new study created in memory with name: no-name-9a330f7a-ee90-42ab-9fc5-cd8e10ebf5e3
Best trial: 0. Best value: 0.460977:   2%|▏         | 1/50 [00:54<44:11, 54.12s/it]

[I 2026-06-12 20:36:06,182] Trial 0 finished with value: 0.46097740961493266 and parameters: {'iterations': 648, 'depth': 4, 'learning_rate': 0.09003544422500852, 'l2_leaf_reg': 0.1891082603929302, 'bagging_temperature': 0.6256284278232959, 'random_strength': 6.041136332754239, 'border_count': 230}. Best is trial 0 with value: 0.46097740961493266.

Best trial: 0. Best value: 0.460977:   4%|▍         | 2/50 [03:44<1:38:13, 122.77s/it]

[I 2026-06-12 20:38:57,014] Trial 1 finished with value: 0.46183959535628477 and parameters: {'iterations': 1567, 'depth': 4, 'learning_rate': 0.00870062113023314, 'l2_leaf_reg': 8.339007036475363e-05, 'bagging_temperature': 0.38527255265008964, 'random_strength': 5.757098698077493, 'border_count': 64}. Best is trial 0 with value: 0.46097740961493266.

Best trial: 2. Best value: 0.459455:   6%|▌         | 3/50 [05:24<1:27:57, 112.28s/it]

[I 2026-06-12 20:40:36,813] Trial 2 finished with value: 0.45945512349576006 and parameters: {'iterations': 1436, 'depth': 6, 'learning_rate': 0.04093952824652868, 'l2_leaf_reg': 0.0064760341946747775, 'bagging_temperature': 0.7233406440863501, 'random_strength': 6.806707599795607, 'border_count': 72}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:   8%|▊         | 4/50 [06:14<1:07:10, 87.63s/it]

[I 2026-06-12 20:41:26,640] Trial 3 finished with value: 0.4968685988499891 and parameters: {'iterations': 412, 'depth': 4, 'learning_rate': 0.005153239510218607, 'l2_leaf_reg': 1.7402693821999938e-05, 'bagging_temperature': 0.1460417453061661, 'random_strength': 5.427230570313438, 'border_count': 223}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:  10%|█         | 5/50 [07:19<59:34, 79.44s/it]

[I 2026-06-12 20:42:31,576] Trial 4 finished with value: 0.47423197563069924 and parameters: {'iterations': 560, 'depth': 4, 'learning_rate': 0.010994100490055864, 'l2_leaf_reg': 5.733250064217131, 'bagging_temperature': 0.8583297869224262, 'random_strength': 5.337853219096339, 'border_count': 129}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:  12%|█▏        | 6/50 [08:35<57:26, 78.32s/it]

[I 2026-06-12 20:43:47,717] Trial 5 finished with value: 0.4611471111394085 and parameters: {'iterations': 537, 'depth': 5, 'learning_rate': 0.05055099326243649, 'l2_leaf_reg': 1.5898378918183813e-05, 'bagging_temperature': 0.7294554143716817, 'random_strength': 5.569882332680919, 'border_count': 243}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:  14%|█▍        | 7/50 [12:11<1:28:25, 123.37s/it]

[I 2026-06-12 20:47:23,849] Trial 6 finished with value: 0.46772239603420557 and parameters: {'iterations': 476, 'depth': 10, 'learning_rate': 0.009642557287689427, 'l2_leaf_reg': 0.002230296798117602, 'bagging_temperature': 0.04262962777106849, 'random_strength': 6.5339054738973825, 'border_count': 114}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:  16%|█▌        | 8/50 [13:38<1:18:07, 111.61s/it]

[I 2026-06-12 20:48:50,273] Trial 7 finished with value: 0.46155689507175524 and parameters: {'iterations': 1632, 'depth': 3, 'learning_rate': 0.029403744013436848, 'l2_leaf_reg': 7.435174672552585e-08, 'bagging_temperature': 0.12807294440036732, 'random_strength': 8.192242079392031, 'border_count': 167}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:  18%|█▊        | 9/50 [14:45<1:06:42, 97.61s/it]

[I 2026-06-12 20:49:57,097] Trial 8 finished with value: 0.46478831498845136 and parameters: {'iterations': 1939, 'depth': 8, 'learning_rate': 0.18268899674127792, 'l2_leaf_reg': 0.00045255424599847303, 'bagging_temperature': 0.52487465588629, 'random_strength': 1.1794287378154333, 'border_count': 106}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:  20%|██        | 10/50 [26:13<3:06:45, 280.15s/it]

[I 2026-06-12 21:01:25,980] Trial 9 finished with value: 0.46682686950905977 and parameters: {'iterations': 690, 'depth': 9, 'learning_rate': 0.0068894800879573444, 'l2_leaf_reg': 0.00020262546920446012, 'bagging_temperature': 0.8377898351745696, 'random_strength': 5.097879964582102, 'border_count': 42}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:  22%|██▏       | 11/50 [29:28<2:45:07, 254.05s/it]

[I 2026-06-12 21:04:40,842] Trial 10 finished with value: 0.4596378044135437 and parameters: {'iterations': 1069, 'depth': 7, 'learning_rate': 0.021520134701379954, 'l2_leaf_reg': 3.226045351431449e-08, 'bagging_temperature': 0.9821365770658135, 'random_strength': 0.5311827349230489, 'border_count': 180}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 2. Best value: 0.459455:  24%|██▍       | 12/50 [32:08<2:22:42, 225.33s/it]

[I 2026-06-12 21:07:20,507] Trial 11 finished with value: 0.46029895885327105 and parameters: {'iterations': 973, 'depth': 7, 'learning_rate': 0.02407715612524724, 'l2_leaf_reg': 1.584038807613369e-08, 'bagging_temperature': 0.9985457081590959, 'random_strength': 0.024051695088903036, 'border_count': 175}. Best is trial 2 with value: 0.45945512349576006.

Best trial: 12. Best value: 0.458522:  26%|██▌       | 13/50 [34:58<2:08:41, 208.70s/it]

[I 2026-06-12 21:10:10,936] Trial 12 finished with value: 0.45852188230614743 and parameters: {'iterations': 1152, 'depth': 6, 'learning_rate': 0.02270430684556757, 'l2_leaf_reg': 4.6178459141011665e-07, 'bagging_temperature': 0.9477455504414958, 'random_strength': 2.662209811036215, 'border_count': 182}. Best is trial 12 with value: 0.45852188230614743.

Best trial: 12. Best value: 0.458522:  28%|██▊       | 14/50 [36:20<1:42:06, 170.19s/it]

[I 2026-06-12 21:11:32,127] Trial 13 finished with value: 0.4594711250728514 and parameters: {'iterations': 1229, 'depth': 6, 'learning_rate': 0.051388267155775304, 'l2_leaf_reg': 6.038931652810558e-07, 'bagging_temperature': 0.7663461662284077, 'random_strength': 2.7282458482601015, 'border_count': 75}. Best is trial 12 with value: 0.45852188230614743.

Best trial: 12. Best value: 0.458522:  30%|███       | 15/50 [1:06:48<6:30:53, 670.11s/it]

[I 2026-06-12 21:42:00,821] Trial 14 finished with value: 0.4586587079089346 and parameters: {'iterations': 1362, 'depth': 6, 'learning_rate': 0.016046311951786244, 'l2_leaf_reg': 0.01981654614212097, 'bagging_temperature': 0.48914811121893675, 'random_strength': 9.840483161311948, 'border_count': 151}. Best is trial 12 with value: 0.45852188230614743.

Best trial: 12. Best value: 0.458522:  32%|███▏      | 16/50 [1:09:35<4:53:48, 518.50s/it]

[I 2026-06-12 21:44:47,223] Trial 15 finished with value: 0.45958755583204974 and parameters: {'iterations': 929, 'depth': 6, 'learning_rate': 0.015622058303235818, 'l2_leaf_reg': 0.03470727195859928, 'bagging_temperature': 0.33972951755426656, 'random_strength': 9.169864431153421, 'border_count': 144}. Best is trial 12 with value: 0.45852188230614743.

Best trial: 16. Best value: 0.458365:  34%|███▍      | 17/50 [1:15:17<4:16:03, 465.57s/it]

[I 2026-06-12 21:50:29,699] Trial 16 finished with value: 0.4583654374424109 and parameters: {'iterations': 1287, 'depth': 8, 'learning_rate': 0.013406540620384334, 'l2_leaf_reg': 9.728494805293534e-07, 'bagging_temperature': 0.44500746571043903, 'random_strength': 3.527811264567295, 'border_count': 204}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  36%|███▌      | 18/50 [1:50:44<8:34:30, 964.70s/it]

[I 2026-06-12 22:25:56,341] Trial 17 finished with value: 0.45858543100416765 and parameters: {'iterations': 1825, 'depth': 8, 'learning_rate': 0.016033679814881165, 'l2_leaf_reg': 8.404095567359777e-07, 'bagging_temperature': 0.34029449915302346, 'random_strength': 3.3864348708296284, 'border_count': 198}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  38%|███▊      | 19/50 [1:55:36<6:34:03, 762.70s/it]

[I 2026-06-12 22:30:48,484] Trial 18 finished with value: 0.46134355431084845 and parameters: {'iterations': 1181, 'depth': 10, 'learning_rate': 0.034060168335621845, 'l2_leaf_reg': 9.07998056658657e-07, 'bagging_temperature': 0.5798786873492505, 'random_strength': 3.195789650434838, 'border_count': 199}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  40%|████      | 20/50 [1:57:24<4:43:02, 566.08s/it]

[I 2026-06-12 22:32:36,300] Trial 19 finished with value: 0.46134977731578847 and parameters: {'iterations': 1681, 'depth': 8, 'learning_rate': 0.06710246141230983, 'l2_leaf_reg': 4.386984008262909e-06, 'bagging_temperature': 0.21101449797096017, 'random_strength': 1.9003356853335733, 'border_count': 211}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  42%|████▏     | 21/50 [1:59:46<3:32:05, 438.80s/it]

[I 2026-06-12 22:34:58,346] Trial 20 finished with value: 0.4642012090587224 and parameters: {'iterations': 825, 'depth': 9, 'learning_rate': 0.09960306871199757, 'l2_leaf_reg': 2.1984018326338483e-07, 'bagging_temperature': 0.41346973726198477, 'random_strength': 4.155129853414004, 'border_count': 251}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  44%|████▍     | 22/50 [2:01:07<2:34:42, 331.53s/it]

[I 2026-06-12 22:36:19,712] Trial 21 finished with value: 0.472127871823315 and parameters: {'iterations': 214, 'depth': 8, 'learning_rate': 0.015382393552410062, 'l2_leaf_reg': 2.296341314014735e-06, 'bagging_temperature': 0.2965776135787451, 'random_strength': 3.6384770077112583, 'border_count': 194}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  46%|████▌     | 23/50 [2:04:29<2:11:42, 292.68s/it]

[I 2026-06-12 22:39:41,772] Trial 22 finished with value: 0.45888363880898003 and parameters: {'iterations': 1972, 'depth': 7, 'learning_rate': 0.020736120814267813, 'l2_leaf_reg': 8.988687286199372e-08, 'bagging_temperature': 0.47404849768348256, 'random_strength': 2.140268580200563, 'border_count': 206}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  48%|████▊     | 24/50 [3:40:27<13:57:28, 1932.64s/it]

[I 2026-06-13 00:15:39,947] Trial 23 finished with value: 0.4593043442846246 and parameters: {'iterations': 1790, 'depth': 9, 'learning_rate': 0.01283348111864591, 'l2_leaf_reg': 7.645087395917003e-06, 'bagging_temperature': 0.26542502981317495, 'random_strength': 3.9758187700189858, 'border_count': 186}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  50%|█████     | 25/50 [13:09:44<80:33:50, 11601.24s/it]

[I 2026-06-13 09:44:56,917] Trial 24 finished with value: 0.45907799456722104 and parameters: {'iterations': 1432, 'depth': 8, 'learning_rate': 0.026627812582145572, 'l2_leaf_reg': 3.88117765786406e-07, 'bagging_temperature': 0.009877750468176127, 'random_strength': 4.572459251516351, 'border_count': 162}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  52%|█████▏    | 26/50 [13:14:53<54:45:12, 8213.02s/it]

[I 2026-06-13 09:50:05,161] Trial 25 finished with value: 0.46102009889739365 and parameters: {'iterations': 1265, 'depth': 7, 'learning_rate': 0.007294500889141577, 'l2_leaf_reg': 1.0808033721628719e-08, 'bagging_temperature': 0.6229088538867268, 'random_strength': 3.0050944752598316, 'border_count': 219}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  54%|█████▍    | 27/50 [13:17:38<37:02:46, 5798.55s/it]

[I 2026-06-13 09:52:50,467] Trial 26 finished with value: 0.45998406176924855 and parameters: {'iterations': 1833, 'depth': 5, 'learning_rate': 0.018494136009602966, 'l2_leaf_reg': 3.772450559329982e-05, 'bagging_temperature': 0.9089445424498446, 'random_strength': 2.004650602831358, 'border_count': 235}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  56%|█████▌    | 28/50 [13:35:30<26:46:13, 4380.60s/it]

[I 2026-06-13 10:10:42,728] Trial 27 finished with value: 0.45933373704277014 and parameters: {'iterations': 1540, 'depth': 9, 'learning_rate': 0.011730490067798145, 'l2_leaf_reg': 1.6093792871040361e-06, 'bagging_temperature': 0.43171218821405594, 'random_strength': 2.287335368782368, 'border_count': 191}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  58%|█████▊    | 29/50 [13:40:43<18:26:01, 3160.09s/it]

[I 2026-06-13 10:15:55,113] Trial 28 finished with value: 0.4602333257664828 and parameters: {'iterations': 1097, 'depth': 5, 'learning_rate': 0.03812460379415775, 'l2_leaf_reg': 1.5984828193950285e-07, 'bagging_temperature': 0.2198241563717439, 'random_strength': 1.0466820209881673, 'border_count': 141}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  60%|██████    | 30/50 [13:47:28<12:57:55, 2333.79s/it]

[I 2026-06-13 10:22:40,927] Trial 29 finished with value: 0.45846990743503474 and parameters: {'iterations': 1311, 'depth': 8, 'learning_rate': 0.013537278315120731, 'l2_leaf_reg': 3.052678387457974e-06, 'bagging_temperature': 0.646573541843748, 'random_strength': 4.590842618506949, 'border_count': 232}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 16. Best value: 0.458365:  62%|██████▏   | 31/50 [13:50:42<8:55:42, 1691.71s/it]

[I 2026-06-13 10:25:54,474] Trial 30 finished with value: 0.469719198762433 and parameters: {'iterations': 799, 'depth': 7, 'learning_rate': 0.0056117348689725625, 'l2_leaf_reg': 0.0007251917633459784, 'bagging_temperature': 0.6485200062525525, 'random_strength': 4.523069426444912, 'border_count': 223}. Best is trial 16 with value: 0.4583654374424109.

Best trial: 31. Best value: 0.458186:  64%|██████▍   | 32/50 [13:57:02<6:29:28, 1298.25s/it]

[I 2026-06-13 10:32:14,675] Trial 31 finished with value: 0.45818608874712674 and parameters: {'iterations': 1312, 'depth': 8, 'learning_rate': 0.015017092532527218, 'l2_leaf_reg': 3.455501005045953e-06, 'bagging_temperature': 0.5708563287223052, 'random_strength': 3.4893013333133185, 'border_count': 233}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  66%|██████▌   | 33/50 [14:16:38<5:57:26, 1261.54s/it]

[I 2026-06-13 10:51:50,568] Trial 32 finished with value: 0.4596047316076403 and parameters: {'iterations': 1313, 'depth': 9, 'learning_rate': 0.008339982148937435, 'l2_leaf_reg': 5.882018087199349e-05, 'bagging_temperature': 0.567266867723907, 'random_strength': 4.684948135152156, 'border_count': 239}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  68%|██████▊   | 34/50 [14:23:24<4:27:57, 1004.84s/it]

[I 2026-06-13 10:58:36,420] Trial 33 finished with value: 0.45870664796386773 and parameters: {'iterations': 1495, 'depth': 8, 'learning_rate': 0.01297276744169696, 'l2_leaf_reg': 6.330682118189666e-06, 'bagging_temperature': 0.6713779324345344, 'random_strength': 3.8840364796414866, 'border_count': 229}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  70%|███████   | 35/50 [15:44:27<9:00:33, 2162.21s/it]

[I 2026-06-13 12:19:39,173] Trial 34 finished with value: 0.4600740565153873 and parameters: {'iterations': 1152, 'depth': 10, 'learning_rate': 0.010197536943733486, 'l2_leaf_reg': 3.3678476223143283e-06, 'bagging_temperature': 0.5522100365920879, 'random_strength': 6.178779404922581, 'border_count': 253}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  72%|███████▏  | 36/50 [15:46:42<6:02:39, 1554.26s/it]

[I 2026-06-13 12:21:54,889] Trial 35 finished with value: 0.4607291456666902 and parameters: {'iterations': 1370, 'depth': 6, 'learning_rate': 0.02881877199258661, 'l2_leaf_reg': 2.007317179433601e-05, 'bagging_temperature': 0.8015494474783805, 'random_strength': 7.237125267323584, 'border_count': 212}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  74%|███████▍  | 37/50 [15:50:24<4:10:09, 1154.59s/it]

[I 2026-06-13 12:25:36,914] Trial 36 finished with value: 0.4587591868304865 and parameters: {'iterations': 1023, 'depth': 7, 'learning_rate': 0.02005642505380801, 'l2_leaf_reg': 4.951391257474608e-08, 'bagging_temperature': 0.9109100503142641, 'random_strength': 2.526428170302343, 'border_count': 228}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  76%|███████▌  | 38/50 [16:02:40<3:25:48, 1029.05s/it]

[I 2026-06-13 12:37:53,035] Trial 37 finished with value: 0.4592595190001467 and parameters: {'iterations': 1437, 'depth': 8, 'learning_rate': 0.012922065229506325, 'l2_leaf_reg': 0.00020747947645357798, 'bagging_temperature': 0.6971436712372615, 'random_strength': 1.4854368319013078, 'border_count': 242}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  78%|███████▊  | 39/50 [16:11:50<2:42:16, 885.15s/it]

[I 2026-06-13 12:47:02,413] Trial 38 finished with value: 0.45931056478854043 and parameters: {'iterations': 1271, 'depth': 9, 'learning_rate': 0.009110411695170375, 'l2_leaf_reg': 2.458401744513704e-07, 'bagging_temperature': 0.6080232112844336, 'random_strength': 4.987371637343213, 'border_count': 213}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  80%|████████  | 40/50 [16:15:09<1:53:14, 679.45s/it]

[I 2026-06-13 12:50:21,891] Trial 39 finished with value: 0.4646462379171605 and parameters: {'iterations': 1632, 'depth': 4, 'learning_rate': 0.006480016426117001, 'l2_leaf_reg': 1.4444854751936897, 'bagging_temperature': 0.7493600804665107, 'random_strength': 2.997602257392992, 'border_count': 169}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  82%|████████▏ | 41/50 [16:59:24<3:10:47, 1271.93s/it]

[I 2026-06-13 13:34:36,278] Trial 40 finished with value: 0.4611866083635934 and parameters: {'iterations': 892, 'depth': 5, 'learning_rate': 0.04772309672320301, 'l2_leaf_reg': 1.2888826946977315e-05, 'bagging_temperature': 0.5206242482633314, 'random_strength': 5.823427778844925, 'border_count': 201}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  84%|████████▍ | 42/50 [17:11:06<2:26:48, 1101.00s/it]

[I 2026-06-13 13:46:18,455] Trial 41 finished with value: 0.4584062235197062 and parameters: {'iterations': 1154, 'depth': 8, 'learning_rate': 0.01725632851551831, 'l2_leaf_reg': 1.2341600349065673e-06, 'bagging_temperature': 0.3863392734263384, 'random_strength': 3.4922254433991955, 'border_count': 182}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  86%|████████▌ | 43/50 [17:12:56<1:33:45, 803.70s/it]

[I 2026-06-13 13:48:08,442] Trial 42 finished with value: 0.462095819693894 and parameters: {'iterations': 1149, 'depth': 3, 'learning_rate': 0.017715697118890178, 'l2_leaf_reg': 1.6295809871751459e-06, 'bagging_temperature': 0.44954431345559387, 'random_strength': 3.487363171912356, 'border_count': 183}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  88%|████████▊ | 44/50 [17:16:51<1:03:19, 633.20s/it]

[I 2026-06-13 13:52:03,828] Trial 43 finished with value: 0.45915873898090703 and parameters: {'iterations': 1029, 'depth': 8, 'learning_rate': 0.025481557720453754, 'l2_leaf_reg': 5.03384695669085e-07, 'bagging_temperature': 0.37646820736230735, 'random_strength': 4.14712489100706, 'border_count': 160}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  90%|█████████ | 45/50 [17:22:26<45:17, 543.55s/it]

[I 2026-06-13 13:57:38,170] Trial 44 finished with value: 0.45843525560153847 and parameters: {'iterations': 1344, 'depth': 7, 'learning_rate': 0.011087259452843745, 'l2_leaf_reg': 2.2920235012688354e-05, 'bagging_temperature': 0.38252522677767165, 'random_strength': 5.3303531781893625, 'border_count': 176}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  92%|█████████▏| 46/50 [17:27:20<31:15, 468.90s/it]

[I 2026-06-13 14:02:32,902] Trial 45 finished with value: 0.45874978808767986 and parameters: {'iterations': 1342, 'depth': 7, 'learning_rate': 0.011021624076619352, 'l2_leaf_reg': 0.00013239175139966735, 'bagging_temperature': 0.38699344403044245, 'random_strength': 7.082556597816071, 'border_count': 127}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  94%|█████████▍| 47/50 [17:33:15<21:43, 434.56s/it]

[I 2026-06-13 14:08:27,320] Trial 46 finished with value: 0.4590253013200077 and parameters: {'iterations': 1427, 'depth': 8, 'learning_rate': 0.014345421448332901, 'l2_leaf_reg': 3.080243106242481e-05, 'bagging_temperature': 0.511393397117843, 'random_strength': 5.430201609244769, 'border_count': 246}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  96%|█████████▌| 48/50 [18:46:17<53:57, 1618.84s/it]

[I 2026-06-13 15:21:29,494] Trial 47 finished with value: 0.4604276174966084 and parameters: {'iterations': 1242, 'depth': 9, 'learning_rate': 0.007946567987267302, 'l2_leaf_reg': 1.1507865581725523e-05, 'bagging_temperature': 0.33912483989659387, 'random_strength': 4.84393575262083, 'border_count': 172}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186:  98%|█████████▊| 49/50 [18:52:07<20:38, 1238.34s/it]

[I 2026-06-13 15:27:19,999] Trial 48 finished with value: 0.45889089613469475 and parameters: {'iterations': 1527, 'depth': 7, 'learning_rate': 0.010344501906044572, 'l2_leaf_reg': 7.168988100893694e-05, 'bagging_temperature': 0.09878594290707743, 'random_strength': 5.975755916313863, 'border_count': 221}. Best is trial 31 with value: 0.45818608874712674.

Best trial: 31. Best value: 0.458186: 100%|██████████| 50/50 [18:56:59<00:00, 1364.40s/it]
[I 2026-06-13 15:32:12,068] A new study created in memory with name: no-name-df06e95a-eea1-4285-977f-00f1ca162e4c

[I 2026-06-13 15:32:12,049] Trial 49 finished with value: 0.4594885914762783 and parameters: {'iterations': 1602, 'depth': 8, 'learning_rate': 0.01772824231402709, 'l2_leaf_reg': 0.0013688138144606569, 'bagging_temperature': 0.47471666928687334, 'random_strength': 7.785832707938904, 'border_count': 153}. Best is trial 31 with value: 0.45818608874712674.

  0%|          | 0/50 [00:00<?, ?it/s]

Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.487614	valid_0's l2: 0.237767
Early stopping, best iteration is:
[52]	valid_0's rmse: 0.477489	valid_0's l2: 0.227996
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.483445	valid_0's l2: 0.233719
Early stopping, best iteration is:
[67]	valid_0's rmse: 0.479961	valid_0's l2: 0.230363
Training until validation scores don't improve for 200 rounds

Best trial: 0. Best value: 0.467197:   2%|▏         | 1/50 [00:06<05:06,  6.26s/it]

[200]	valid_0's rmse: 0.446631	valid_0's l2: 0.19948
Early stopping, best iteration is:
[95]	valid_0's rmse: 0.44414	valid_0's l2: 0.197261
[I 2026-06-13 15:32:18,327] Trial 0 finished with value: 0.4671969506539224 and parameters: {'n_estimators': 648, 'num_leaves': 33, 'max_depth': 10, 'learning_rate': 0.09868996106858782, 'subsample': 0.8128142139116479, 'colsample_bytree': 0.7624681799652544, 'min_child_weight': 18, 'reg_alpha': 0.06792931113888691, 'reg_lambda': 4.265259954948051e-07, 'min_split_gain': 0.1501693161428389}. Best is trial 0 with value: 0.4671969506539224.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.482902	valid_0's l2: 0.233195
[400]	valid_0's rmse: 0.474143	valid_0's l2: 0.224811
[600]	valid_0's rmse: 0.473803	valid_0's l2: 0.224489
Early stopping, best iteration is:
[545]	valid_0's rmse: 0.473716	valid_0's l2: 0.224407
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.491543	valid_0's l2: 0.241615
[400]	valid_0's rmse: 0.481225	valid_0's l2: 0.231577
[600]	valid_0's rmse: 0.478382	valid_0's l2: 0.228849
[800]	valid_0's rmse: 0.47838	valid_0's l2: 0.228848
Early stopping, best iteration is:
[602]	valid_0's rmse: 0.47838	valid_0's l2: 0.228848
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.462352	valid_0's l2: 0.21377
[400]	valid_0's rmse: 0.445968	valid_0's l2: 0.198888
[600]	valid_0's rmse: 0.44174	valid_0's l2: 0.195134
[800]	valid_0's rmse: 0.441082	valid_0's l2: 0.194553
Early stopping, best iteration is:
[653]	valid_0's rmse: 0.441082	valid_0's l2: 0.194553

Best trial: 1. Best value: 0.464393:   4%|▍         | 2/50 [00:20<08:41, 10.86s/it]

[I 2026-06-13 15:32:32,408] Trial 1 finished with value: 0.4643926540909811 and parameters: {'n_estimators': 984, 'num_leaves': 58, 'max_depth': 8, 'learning_rate': 0.008570695406948778, 'subsample': 0.8432965093525775, 'colsample_bytree': 0.6812824030367373, 'min_child_weight': 12, 'reg_alpha': 0.0064760341946747775, 'reg_lambda': 0.03236426859492333, 'min_split_gain': 0.6806707599795607}. Best is trial 1 with value: 0.4643926540909811.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.505385	valid_0's l2: 0.255414
[400]	valid_0's rmse: 0.482194	valid_0's l2: 0.232511
Did not meet early stopping. Best iteration is:
[525]	valid_0's rmse: 0.476623	valid_0's l2: 0.22717
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.515744	valid_0's l2: 0.265992
[400]	valid_0's rmse: 0.490669	valid_0's l2: 0.240756
Did not meet early stopping. Best iteration is:
[525]	valid_0's rmse: 0.485525	valid_0's l2: 0.235735
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.495862	valid_0's l2: 0.245879
[400]	valid_0's rmse: 0.46267	valid_0's l2: 0.214064

Best trial: 1. Best value: 0.464393:   6%|▌         | 3/50 [00:29<07:48,  9.96s/it]

Did not meet early stopping. Best iteration is:
[525]	valid_0's rmse: 0.454154	valid_0's l2: 0.206256
[I 2026-06-13 15:32:41,294] Trial 2 finished with value: 0.4721009089699497 and parameters: {'n_estimators': 525, 'num_leaves': 28, 'max_depth': 5, 'learning_rate': 0.005153239510218607, 'subsample': 0.6800342488556674, 'colsample_bytree': 0.4876250471836997, 'min_child_weight': 11, 'reg_alpha': 0.5175245301347682, 'reg_lambda': 6.337376094032935e-07, 'min_split_gain': 0.13463345870123333}. Best is trial 1 with value: 0.4643926540909811.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474268	valid_0's l2: 0.22493
Early stopping, best iteration is:
[175]	valid_0's rmse: 0.474255	valid_0's l2: 0.224918
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.478949	valid_0's l2: 0.229392
Early stopping, best iteration is:
[187]	valid_0's rmse: 0.478949	valid_0's l2: 0.229392
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.439702	valid_0's l2: 0.193338
Early stopping, best iteration is:
[184]	valid_0's rmse: 0.439702	valid_0's l2: 0.193338

Best trial: 3. Best value: 0.464306:   8%|▊         | 4/50 [00:35<06:34,  8.57s/it]

[I 2026-06-13 15:32:47,732] Trial 3 finished with value: 0.4643062381674598 and parameters: {'n_estimators': 584, 'num_leaves': 124, 'max_depth': 11, 'learning_rate': 0.035820043797197255, 'subsample': 0.7172292954945612, 'colsample_bytree': 0.5123155399025462, 'min_child_weight': 6, 'reg_alpha': 0.004410684361566336, 'reg_lambda': 1.5898378918183813e-05, 'min_split_gain': 0.7294554143716817}. Best is trial 3 with value: 0.4643062381674598.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.473657	valid_0's l2: 0.224351
Early stopping, best iteration is:
[63]	valid_0's rmse: 0.473645	valid_0's l2: 0.224339
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.478414	valid_0's l2: 0.22888
Early stopping, best iteration is:
[77]	valid_0's rmse: 0.478414	valid_0's l2: 0.22888
Training until validation scores don't improve for 200 rounds

Best trial: 3. Best value: 0.464306:  10%|█         | 5/50 [00:40<05:23,  7.18s/it]

[200]	valid_0's rmse: 0.441901	valid_0's l2: 0.195276
Early stopping, best iteration is:
[81]	valid_0's rmse: 0.441869	valid_0's l2: 0.195249
[I 2026-06-13 15:32:52,459] Trial 4 finished with value: 0.46464280996891577 and parameters: {'n_estimators': 1203, 'num_leaves': 121, 'max_depth': 4, 'learning_rate': 0.13638831686825714, 'subsample': 0.5890173354786217, 'colsample_bytree': 0.7565575107266116, 'min_child_weight': 1, 'reg_alpha': 0.00759477525123107, 'reg_lambda': 1.9974501698690318e-05, 'min_split_gain': 0.7955697723224631}. Best is trial 3 with value: 0.4643062381674598.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.496721	valid_0's l2: 0.246732
Did not meet early stopping. Best iteration is:
[219]	valid_0's rmse: 0.494059	valid_0's l2: 0.244094
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.508182	valid_0's l2: 0.258249
Did not meet early stopping. Best iteration is:
[219]	valid_0's rmse: 0.505152	valid_0's l2: 0.255178
Training until validation scores don't improve for 200 rounds

Best trial: 3. Best value: 0.464306:  12%|█▏        | 6/50 [00:44<04:36,  6.29s/it]

[200]	valid_0's rmse: 0.485831	valid_0's l2: 0.236032
Did not meet early stopping. Best iteration is:
[219]	valid_0's rmse: 0.481728	valid_0's l2: 0.232061
[I 2026-06-13 15:32:57,026] Trial 5 finished with value: 0.4936461504894783 and parameters: {'n_estimators': 219, 'num_leaves': 69, 'max_depth': 3, 'learning_rate': 0.008019560065198885, 'subsample': 0.9096121039696016, 'colsample_bytree': 0.7620314705557336, 'min_child_weight': 20, 'reg_alpha': 0.01733033648305316, 'reg_lambda': 6.013438183301075, 'min_split_gain': 0.5172967382144137}. Best is trial 3 with value: 0.4643062381674598.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.477682	valid_0's l2: 0.22818
[400]	valid_0's rmse: 0.473582	valid_0's l2: 0.22428
Early stopping, best iteration is:
[347]	valid_0's rmse: 0.473315	valid_0's l2: 0.224027
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.486685	valid_0's l2: 0.236862
[400]	valid_0's rmse: 0.480153	valid_0's l2: 0.230547
[600]	valid_0's rmse: 0.477804	valid_0's l2: 0.228296
[800]	valid_0's rmse: 0.477166	valid_0's l2: 0.227687
Early stopping, best iteration is:
[773]	valid_0's rmse: 0.47702	valid_0's l2: 0.227548
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.4531	valid_0's l2: 0.2053
[400]	valid_0's rmse: 0.442416	valid_0's l2: 0.195732
[600]	valid_0's rmse: 0.441036	valid_0's l2: 0.194513
[800]	valid_0's rmse: 0.440517	valid_0's l2: 0.194055

Best trial: 6. Best value: 0.463563:  14%|█▍        | 7/50 [00:56<05:44,  8.02s/it]

Early stopping, best iteration is:
[753]	valid_0's rmse: 0.440354	valid_0's l2: 0.193912
[I 2026-06-13 15:33:08,609] Trial 6 finished with value: 0.46356308292968923 and parameters: {'n_estimators': 1145, 'num_leaves': 28, 'max_depth': 6, 'learning_rate': 0.013658325975935614, 'subsample': 0.9349304188521758, 'colsample_bytree': 0.45213903812247913, 'min_child_weight': 10, 'reg_alpha': 0.34682349994249695, 'reg_lambda': 0.0003873396610002218, 'min_split_gain': 0.0483459820917963}. Best is trial 6 with value: 0.46356308292968923.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.491305	valid_0's l2: 0.241381
[400]	valid_0's rmse: 0.47503	valid_0's l2: 0.225654
[600]	valid_0's rmse: 0.472381	valid_0's l2: 0.223144
[800]	valid_0's rmse: 0.472175	valid_0's l2: 0.222949
Early stopping, best iteration is:
[658]	valid_0's rmse: 0.472058	valid_0's l2: 0.222838
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.501079	valid_0's l2: 0.25108
[400]	valid_0's rmse: 0.484032	valid_0's l2: 0.234287
[600]	valid_0's rmse: 0.480062	valid_0's l2: 0.230459
[800]	valid_0's rmse: 0.479215	valid_0's l2: 0.229647
[1000]	valid_0's rmse: 0.479077	valid_0's l2: 0.229515
[1200]	valid_0's rmse: 0.479059	valid_0's l2: 0.229498
Early stopping, best iteration is:
[1053]	valid_0's rmse: 0.479058	valid_0's l2: 0.229497
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474483	valid_0's l2: 0.225134
[400]	valid_0's rmse: 0.449118	valid_0's l2: 0.201707
[600]	valid_0's rmse: 0.442159	valid_0's l2: 0.195504
[800]	valid_0's rmse: 0.440312	valid_0's l2: 0.193875
[1000]	valid_0's rmse: 0.439753	valid_0's l2: 0.193383
[1200]	valid_0's rmse: 0.439669	valid_0's l2: 0.193309
Early stopping, best iteration is:
[1062]	valid_0's rmse: 0.439669	valid_0's l2: 0.193309

Best trial: 6. Best value: 0.463563:  16%|█▌        | 8/50 [01:10<07:02, 10.06s/it]

[I 2026-06-13 15:33:23,028] Trial 7 finished with value: 0.4635952064076257 and parameters: {'n_estimators': 1304, 'num_leaves': 61, 'max_depth': 10, 'learning_rate': 0.006932440901114855, 'subsample': 0.6909220768095793, 'colsample_bytree': 0.4143368956812655, 'min_child_weight': 8, 'reg_alpha': 1.900989755132965e-07, 'reg_lambda': 1.0072861435661662e-06, 'min_split_gain': 0.7938129264940265}. Best is trial 6 with value: 0.46356308292968923.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.478241	valid_0's l2: 0.228714
Early stopping, best iteration is:
[58]	valid_0's rmse: 0.478241	valid_0's l2: 0.228714
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.480846	valid_0's l2: 0.231212
Early stopping, best iteration is:
[62]	valid_0's rmse: 0.48083	valid_0's l2: 0.231197
Training until validation scores don't improve for 200 rounds

Best trial: 6. Best value: 0.463563:  18%|█▊        | 9/50 [01:16<05:54,  8.64s/it]

[200]	valid_0's rmse: 0.445101	valid_0's l2: 0.198115
Early stopping, best iteration is:
[64]	valid_0's rmse: 0.445101	valid_0's l2: 0.198115
[I 2026-06-13 15:33:28,536] Trial 8 finished with value: 0.468057134649493 and parameters: {'n_estimators': 1493, 'num_leaves': 69, 'max_depth': 12, 'learning_rate': 0.08291665513773347, 'subsample': 0.5454054113547102, 'colsample_bytree': 0.7223781637631188, 'min_child_weight': 14, 'reg_alpha': 0.04588020805366937, 'reg_lambda': 0.004446407546354058, 'min_split_gain': 0.8832838023788622}. Best is trial 6 with value: 0.46356308292968923.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474467	valid_0's l2: 0.225119
[400]	valid_0's rmse: 0.47432	valid_0's l2: 0.224979
Early stopping, best iteration is:
[208]	valid_0's rmse: 0.474237	valid_0's l2: 0.2249
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479664	valid_0's l2: 0.230077
[400]	valid_0's rmse: 0.478836	valid_0's l2: 0.229284
Early stopping, best iteration is:
[274]	valid_0's rmse: 0.478836	valid_0's l2: 0.229284
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.441781	valid_0's l2: 0.195171

Best trial: 6. Best value: 0.463563:  20%|██        | 10/50 [01:24<05:36,  8.42s/it]

[400]	valid_0's rmse: 0.440548	valid_0's l2: 0.194083
Early stopping, best iteration is:
[276]	valid_0's rmse: 0.440548	valid_0's l2: 0.194083
[I 2026-06-13 15:33:36,469] Trial 9 finished with value: 0.4645404569828499 and parameters: {'n_estimators': 1640, 'num_leaves': 77, 'max_depth': 11, 'learning_rate': 0.022622492535654317, 'subsample': 0.5336085426932707, 'colsample_bytree': 0.4846891420693052, 'min_child_weight': 20, 'reg_alpha': 5.916398047912201e-07, 'reg_lambda': 0.9794034214488329, 'min_split_gain': 0.6478467554049107}. Best is trial 6 with value: 0.46356308292968923.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.478033	valid_0's l2: 0.228515
[400]	valid_0's rmse: 0.477742	valid_0's l2: 0.228237
Early stopping, best iteration is:
[269]	valid_0's rmse: 0.477726	valid_0's l2: 0.228223
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.481461	valid_0's l2: 0.231805
[400]	valid_0's rmse: 0.479876	valid_0's l2: 0.230281
Early stopping, best iteration is:
[291]	valid_0's rmse: 0.479869	valid_0's l2: 0.230275
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.444766	valid_0's l2: 0.197817
[400]	valid_0's rmse: 0.441208	valid_0's l2: 0.194665
Early stopping, best iteration is:
[323]	valid_0's rmse: 0.441208	valid_0's l2: 0.194665

Best trial: 6. Best value: 0.463563:  22%|██▏       | 11/50 [01:34<05:43,  8.82s/it]

[I 2026-06-13 15:33:46,192] Trial 10 finished with value: 0.46626802954185714 and parameters: {'n_estimators': 1948, 'num_leaves': 99, 'max_depth': 7, 'learning_rate': 0.023259533515926564, 'subsample': 0.991719894481221, 'colsample_bytree': 0.9711422909390367, 'min_child_weight': 3, 'reg_alpha': 2.745804302771729e-05, 'reg_lambda': 0.0011516277441905296, 'min_split_gain': 0.3655369041465087}. Best is trial 6 with value: 0.46356308292968923.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.477512	valid_0's l2: 0.228017
[400]	valid_0's rmse: 0.472121	valid_0's l2: 0.222898
[600]	valid_0's rmse: 0.471724	valid_0's l2: 0.222524
Early stopping, best iteration is:
[568]	valid_0's rmse: 0.471722	valid_0's l2: 0.222522
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.486673	valid_0's l2: 0.23685
[400]	valid_0's rmse: 0.480212	valid_0's l2: 0.230604
[600]	valid_0's rmse: 0.479745	valid_0's l2: 0.230155
Early stopping, best iteration is:
[585]	valid_0's rmse: 0.479741	valid_0's l2: 0.230152
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.453178	valid_0's l2: 0.20537
[400]	valid_0's rmse: 0.441524	valid_0's l2: 0.194944
[600]	valid_0's rmse: 0.440444	valid_0's l2: 0.193991

Best trial: 6. Best value: 0.463563:  24%|██▍       | 12/50 [01:42<05:35,  8.83s/it]

Early stopping, best iteration is:
[586]	valid_0's rmse: 0.440443	valid_0's l2: 0.19399
[I 2026-06-13 15:33:55,062] Trial 11 finished with value: 0.4639712623783577 and parameters: {'n_estimators': 1141, 'num_leaves': 45, 'max_depth': 8, 'learning_rate': 0.012428923473922094, 'subsample': 0.7013241533841847, 'colsample_bytree': 0.4047834976849438, 'min_child_weight': 7, 'reg_alpha': 1.0271676431398732e-08, 'reg_lambda': 1.0731083602525381e-08, 'min_split_gain': 0.9907761401025786}. Best is trial 6 with value: 0.46356308292968923.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.47519	valid_0's l2: 0.225806
[400]	valid_0's rmse: 0.473345	valid_0's l2: 0.224056
[600]	valid_0's rmse: 0.474021	valid_0's l2: 0.224696
Early stopping, best iteration is:
[431]	valid_0's rmse: 0.473183	valid_0's l2: 0.223902
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.484875	valid_0's l2: 0.235104
[400]	valid_0's rmse: 0.478796	valid_0's l2: 0.229246
[600]	valid_0's rmse: 0.476472	valid_0's l2: 0.227025
[800]	valid_0's rmse: 0.476067	valid_0's l2: 0.22664
Early stopping, best iteration is:
[707]	valid_0's rmse: 0.476067	valid_0's l2: 0.22664
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.451585	valid_0's l2: 0.203929
[400]	valid_0's rmse: 0.443428	valid_0's l2: 0.196628
[600]	valid_0's rmse: 0.442433	valid_0's l2: 0.195747
[800]	valid_0's rmse: 0.441118	valid_0's l2: 0.194585
Early stopping, best iteration is:
[783]	valid_0's rmse: 0.441077	valid_0's l2: 0.194549

Best trial: 12. Best value: 0.463442:  26%|██▌       | 13/50 [01:53<05:43,  9.28s/it]

[I 2026-06-13 15:34:05,353] Trial 12 finished with value: 0.4634423915635979 and parameters: {'n_estimators': 1409, 'num_leaves': 24, 'max_depth': 6, 'learning_rate': 0.015345265990569474, 'subsample': 0.9884637852312946, 'colsample_bytree': 0.5933713953332046, 'min_child_weight': 9, 'reg_alpha': 2.1742167559136653e-05, 'reg_lambda': 8.738886423645245e-05, 'min_split_gain': 0.3422798180283436}. Best is trial 12 with value: 0.4634423915635979.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.475505	valid_0's l2: 0.226105
[400]	valid_0's rmse: 0.472009	valid_0's l2: 0.222792
[600]	valid_0's rmse: 0.472278	valid_0's l2: 0.223047
Early stopping, best iteration is:
[488]	valid_0's rmse: 0.471682	valid_0's l2: 0.222484
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.485157	valid_0's l2: 0.235378
[400]	valid_0's rmse: 0.478501	valid_0's l2: 0.228964
[600]	valid_0's rmse: 0.476261	valid_0's l2: 0.226825
[800]	valid_0's rmse: 0.475821	valid_0's l2: 0.226405
Did not meet early stopping. Best iteration is:
[765]	valid_0's rmse: 0.475693	valid_0's l2: 0.226284
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.452537	valid_0's l2: 0.20479
[400]	valid_0's rmse: 0.442994	valid_0's l2: 0.196244
[600]	valid_0's rmse: 0.44175	valid_0's l2: 0.195143

Best trial: 13. Best value: 0.463019:  28%|██▊       | 14/50 [02:04<05:49,  9.71s/it]

[800]	valid_0's rmse: 0.442322	valid_0's l2: 0.195649
Early stopping, best iteration is:
[604]	valid_0's rmse: 0.441682	valid_0's l2: 0.195083
[I 2026-06-13 15:34:16,075] Trial 13 finished with value: 0.4630192113922562 and parameters: {'n_estimators': 946, 'num_leaves': 18, 'max_depth': 6, 'learning_rate': 0.015811489867069362, 'subsample': 0.985000776477052, 'colsample_bytree': 0.607006788316522, 'min_child_weight': 10, 'reg_alpha': 8.676229263135003e-05, 'reg_lambda': 0.00023741860737730935, 'min_split_gain': 0.01732621665846263}. Best is trial 13 with value: 0.4630192113922562.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.472127	valid_0's l2: 0.222904
Early stopping, best iteration is:
[161]	valid_0's rmse: 0.471732	valid_0's l2: 0.222531
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.478236	valid_0's l2: 0.228709
[400]	valid_0's rmse: 0.478351	valid_0's l2: 0.228819
Early stopping, best iteration is:
[216]	valid_0's rmse: 0.477983	valid_0's l2: 0.228468
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.445482	valid_0's l2: 0.198454

Best trial: 13. Best value: 0.463019:  30%|███       | 15/50 [02:10<05:02,  8.63s/it]

[400]	valid_0's rmse: 0.443441	valid_0's l2: 0.19664
Early stopping, best iteration is:
[310]	valid_0's rmse: 0.443406	valid_0's l2: 0.196609
[I 2026-06-13 15:34:22,202] Trial 14 finished with value: 0.4643738978482004 and parameters: {'n_estimators': 1761, 'num_leaves': 19, 'max_depth': 6, 'learning_rate': 0.04814415549733444, 'subsample': 0.9976421563177846, 'colsample_bytree': 0.6100178645389046, 'min_child_weight': 14, 'reg_alpha': 0.00011229333068250452, 'reg_lambda': 7.257716186032676e-05, 'min_split_gain': 0.33303659273596925}. Best is trial 13 with value: 0.4630192113922562.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.475105	valid_0's l2: 0.225725
[400]	valid_0's rmse: 0.471797	valid_0's l2: 0.222593
[600]	valid_0's rmse: 0.471717	valid_0's l2: 0.222516
Early stopping, best iteration is:
[525]	valid_0's rmse: 0.471102	valid_0's l2: 0.221937
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.485154	valid_0's l2: 0.235374
[400]	valid_0's rmse: 0.478746	valid_0's l2: 0.229197
[600]	valid_0's rmse: 0.476035	valid_0's l2: 0.226609
[800]	valid_0's rmse: 0.475467	valid_0's l2: 0.226069
Did not meet early stopping. Best iteration is:
[871]	valid_0's rmse: 0.475339	valid_0's l2: 0.225947
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.451893	valid_0's l2: 0.204207
[400]	valid_0's rmse: 0.443185	valid_0's l2: 0.196413
[600]	valid_0's rmse: 0.442782	valid_0's l2: 0.196056

Best trial: 15. Best value: 0.462968:  32%|███▏      | 16/50 [02:19<05:01,  8.88s/it]

Early stopping, best iteration is:
[562]	valid_0's rmse: 0.442464	valid_0's l2: 0.195774
[I 2026-06-13 15:34:31,666] Trial 15 finished with value: 0.4629683637735737 and parameters: {'n_estimators': 887, 'num_leaves': 15, 'max_depth': 5, 'learning_rate': 0.017544548918102813, 'subsample': 0.8936196070721474, 'colsample_bytree': 0.5882810431302585, 'min_child_weight': 5, 'reg_alpha': 0.00018357916528686347, 'reg_lambda': 0.07486847762333562, 'min_split_gain': 0.2896140661711059}. Best is trial 15 with value: 0.4629683637735737.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474056	valid_0's l2: 0.224729
[400]	valid_0's rmse: 0.4737	valid_0's l2: 0.224391
Early stopping, best iteration is:
[299]	valid_0's rmse: 0.472759	valid_0's l2: 0.223501
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.481424	valid_0's l2: 0.231769
[400]	valid_0's rmse: 0.476184	valid_0's l2: 0.226751
[600]	valid_0's rmse: 0.475294	valid_0's l2: 0.225904
Early stopping, best iteration is:
[498]	valid_0's rmse: 0.475224	valid_0's l2: 0.225838
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.446718	valid_0's l2: 0.199557
[400]	valid_0's rmse: 0.441112	valid_0's l2: 0.19458
[600]	valid_0's rmse: 0.440924	valid_0's l2: 0.194414

Best trial: 16. Best value: 0.4629:  34%|███▍      | 17/50 [02:25<04:28,  8.12s/it]

Early stopping, best iteration is:
[571]	valid_0's rmse: 0.440718	valid_0's l2: 0.194233
[I 2026-06-13 15:34:38,029] Trial 16 finished with value: 0.4629002602778219 and parameters: {'n_estimators': 869, 'num_leaves': 43, 'max_depth': 3, 'learning_rate': 0.03631243331985874, 'subsample': 0.871440346337854, 'colsample_bytree': 0.5846149168369102, 'min_child_weight': 4, 'reg_alpha': 0.00044991069363274963, 'reg_lambda': 0.06485530238800677, 'min_split_gain': 0.01598590761620252}. Best is trial 16 with value: 0.4629002602778219.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.47523	valid_0's l2: 0.225844
[400]	valid_0's rmse: 0.475704	valid_0's l2: 0.226294
Early stopping, best iteration is:
[277]	valid_0's rmse: 0.474584	valid_0's l2: 0.22523
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.480324	valid_0's l2: 0.230711
[400]	valid_0's rmse: 0.476866	valid_0's l2: 0.227402
[600]	valid_0's rmse: 0.476504	valid_0's l2: 0.227056
[800]	valid_0's rmse: 0.477005	valid_0's l2: 0.227533
Early stopping, best iteration is:
[600]	valid_0's rmse: 0.476504	valid_0's l2: 0.227056
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.446762	valid_0's l2: 0.199596
[400]	valid_0's rmse: 0.443252	valid_0's l2: 0.196473
[600]	valid_0's rmse: 0.442075	valid_0's l2: 0.19543

Best trial: 16. Best value: 0.4629:  36%|███▌      | 18/50 [02:33<04:10,  7.82s/it]

[800]	valid_0's rmse: 0.443814	valid_0's l2: 0.196971
Early stopping, best iteration is:
[610]	valid_0's rmse: 0.442008	valid_0's l2: 0.195371
[I 2026-06-13 15:34:45,155] Trial 17 finished with value: 0.46436559678419514 and parameters: {'n_estimators': 825, 'num_leaves': 41, 'max_depth': 3, 'learning_rate': 0.04261456001725194, 'subsample': 0.8159473897366376, 'colsample_bytree': 0.8899796759742924, 'min_child_weight': 4, 'reg_alpha': 0.0003992278636768371, 'reg_lambda': 0.10106834143223481, 'min_split_gain': 0.21118659472669765}. Best is trial 16 with value: 0.4629002602778219.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474077	valid_0's l2: 0.224749
Did not meet early stopping. Best iteration is:
[238]	valid_0's rmse: 0.473322	valid_0's l2: 0.224034
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.481796	valid_0's l2: 0.232128
Did not meet early stopping. Best iteration is:
[252]	valid_0's rmse: 0.48014	valid_0's l2: 0.230534
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.446084	valid_0's l2: 0.198991
Did not meet early stopping. Best iteration is:
[252]	valid_0's rmse: 0.442884	valid_0's l2: 0.196147

Best trial: 16. Best value: 0.4629:  38%|███▊      | 19/50 [02:38<03:36,  6.98s/it]

[I 2026-06-13 15:34:50,164] Trial 18 finished with value: 0.46544872127247716 and parameters: {'n_estimators': 252, 'num_leaves': 42, 'max_depth': 4, 'learning_rate': 0.026000589984772452, 'subsample': 0.8767015103798115, 'colsample_bytree': 0.5435363580684844, 'min_child_weight': 5, 'reg_alpha': 2.7814164319119256e-06, 'reg_lambda': 0.11518088031592481, 'min_split_gain': 0.4804793384144004}. Best is trial 16 with value: 0.4629002602778219.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474614	valid_0's l2: 0.225259
Early stopping, best iteration is:
[141]	valid_0's rmse: 0.473423	valid_0's l2: 0.22413
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.477323	valid_0's l2: 0.227837
[400]	valid_0's rmse: 0.479545	valid_0's l2: 0.229964
Early stopping, best iteration is:
[207]	valid_0's rmse: 0.477051	valid_0's l2: 0.227577
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.441375	valid_0's l2: 0.194812

Best trial: 16. Best value: 0.4629:  40%|████      | 20/50 [02:43<03:17,  6.59s/it]

[400]	valid_0's rmse: 0.442667	valid_0's l2: 0.195954
Early stopping, best iteration is:
[225]	valid_0's rmse: 0.440804	valid_0's l2: 0.194308
[I 2026-06-13 15:34:55,859] Trial 19 finished with value: 0.46375933416356047 and parameters: {'n_estimators': 778, 'num_leaves': 52, 'max_depth': 4, 'learning_rate': 0.06015137434530425, 'subsample': 0.7671205422949231, 'colsample_bytree': 0.6558846315050082, 'min_child_weight': 1, 'reg_alpha': 0.0005102478735824108, 'reg_lambda': 0.010679468329442497, 'min_split_gain': 0.21062606926057437}. Best is trial 16 with value: 0.4629002602778219.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.475797	valid_0's l2: 0.226383
Early stopping, best iteration is:
[66]	valid_0's rmse: 0.475522	valid_0's l2: 0.226121
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.48051	valid_0's l2: 0.23089
Early stopping, best iteration is:
[81]	valid_0's rmse: 0.480469	valid_0's l2: 0.23085
Training until validation scores don't improve for 200 rounds

Best trial: 16. Best value: 0.4629:  42%|████▏     | 21/50 [02:47<02:49,  5.85s/it]

[200]	valid_0's rmse: 0.442078	valid_0's l2: 0.195433
Early stopping, best iteration is:
[97]	valid_0's rmse: 0.442053	valid_0's l2: 0.195411
[I 2026-06-13 15:34:59,982] Trial 20 finished with value: 0.466014665234276 and parameters: {'n_estimators': 489, 'num_leaves': 86, 'max_depth': 3, 'learning_rate': 0.17036965771018472, 'subsample': 0.9230811833144508, 'colsample_bytree': 0.8178774690642359, 'min_child_weight': 3, 'reg_alpha': 6.3495495850332695, 'reg_lambda': 1.4659190084375693, 'min_split_gain': 0.49993591098908013}. Best is trial 16 with value: 0.4629002602778219.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474159	valid_0's l2: 0.224826
[400]	valid_0's rmse: 0.472536	valid_0's l2: 0.22329
Early stopping, best iteration is:
[383]	valid_0's rmse: 0.472406	valid_0's l2: 0.223167
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.48266	valid_0's l2: 0.232961
[400]	valid_0's rmse: 0.478048	valid_0's l2: 0.22853
[600]	valid_0's rmse: 0.476387	valid_0's l2: 0.226944
[800]	valid_0's rmse: 0.476377	valid_0's l2: 0.226935
Early stopping, best iteration is:
[622]	valid_0's rmse: 0.476147	valid_0's l2: 0.226716
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.448188	valid_0's l2: 0.200872
[400]	valid_0's rmse: 0.44073	valid_0's l2: 0.194243
[600]	valid_0's rmse: 0.439242	valid_0's l2: 0.192934
[800]	valid_0's rmse: 0.439924	valid_0's l2: 0.193533
Early stopping, best iteration is:
[629]	valid_0's rmse: 0.439112	valid_0's l2: 0.192819

Best trial: 21. Best value: 0.462555:  44%|████▍     | 22/50 [02:58<03:20,  7.18s/it]

[I 2026-06-13 15:35:10,249] Trial 21 finished with value: 0.4625550575492252 and parameters: {'n_estimators': 969, 'num_leaves': 33, 'max_depth': 5, 'learning_rate': 0.017438172904390245, 'subsample': 0.8795956736673556, 'colsample_bytree': 0.5767256716744723, 'min_child_weight': 6, 'reg_alpha': 0.0008606226519235526, 'reg_lambda': 0.2698530840888031, 'min_split_gain': 0.00658056553892665}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.47269	valid_0's l2: 0.223436
[400]	valid_0's rmse: 0.473457	valid_0's l2: 0.224162
Early stopping, best iteration is:
[251]	valid_0's rmse: 0.471901	valid_0's l2: 0.22269
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479847	valid_0's l2: 0.230254
[400]	valid_0's rmse: 0.47781	valid_0's l2: 0.228302
Early stopping, best iteration is:
[353]	valid_0's rmse: 0.477589	valid_0's l2: 0.228091
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.443397	valid_0's l2: 0.196601
[400]	valid_0's rmse: 0.440173	valid_0's l2: 0.193752
[600]	valid_0's rmse: 0.440566	valid_0's l2: 0.194098
Early stopping, best iteration is:
[446]	valid_0's rmse: 0.439737	valid_0's l2: 0.193369

Best trial: 21. Best value: 0.462555:  46%|████▌     | 23/50 [03:08<03:35,  7.98s/it]

[I 2026-06-13 15:35:20,110] Trial 22 finished with value: 0.4630756080504872 and parameters: {'n_estimators': 1010, 'num_leaves': 35, 'max_depth': 5, 'learning_rate': 0.026637779813941408, 'subsample': 0.8769773890783237, 'colsample_bytree': 0.5667391259550336, 'min_child_weight': 5, 'reg_alpha': 0.0014314807038873323, 'reg_lambda': 0.35694123073261314, 'min_split_gain': 0.007688063582114038}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.472117	valid_0's l2: 0.222894
[400]	valid_0's rmse: 0.474795	valid_0's l2: 0.22543
Early stopping, best iteration is:
[234]	valid_0's rmse: 0.472008	valid_0's l2: 0.222791
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479917	valid_0's l2: 0.23032
[400]	valid_0's rmse: 0.477631	valid_0's l2: 0.228131
[600]	valid_0's rmse: 0.478093	valid_0's l2: 0.228572
Early stopping, best iteration is:
[420]	valid_0's rmse: 0.477224	valid_0's l2: 0.227743
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.444401	valid_0's l2: 0.197492
[400]	valid_0's rmse: 0.44221	valid_0's l2: 0.19555
[600]	valid_0's rmse: 0.442627	valid_0's l2: 0.195919
Early stopping, best iteration is:
[449]	valid_0's rmse: 0.441955	valid_0's l2: 0.195325

Best trial: 21. Best value: 0.462555:  48%|████▊     | 24/50 [03:15<03:25,  7.91s/it]

[I 2026-06-13 15:35:27,859] Trial 23 finished with value: 0.46372916431749145 and parameters: {'n_estimators': 786, 'num_leaves': 15, 'max_depth': 5, 'learning_rate': 0.03352525245123668, 'subsample': 0.7702474612793009, 'colsample_bytree': 0.6634121064105555, 'min_child_weight': 7, 'reg_alpha': 8.676237381689483e-06, 'reg_lambda': 0.008690692477693607, 'min_split_gain': 0.10270923075014425}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.475009	valid_0's l2: 0.225634
[400]	valid_0's rmse: 0.472194	valid_0's l2: 0.222967
[600]	valid_0's rmse: 0.472653	valid_0's l2: 0.223401
Early stopping, best iteration is:
[449]	valid_0's rmse: 0.471876	valid_0's l2: 0.222667
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.48467	valid_0's l2: 0.234905
[400]	valid_0's rmse: 0.479013	valid_0's l2: 0.229453
[600]	valid_0's rmse: 0.476457	valid_0's l2: 0.227011
[800]	valid_0's rmse: 0.475998	valid_0's l2: 0.226574
Did not meet early stopping. Best iteration is:
[873]	valid_0's rmse: 0.475768	valid_0's l2: 0.226355
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.450787	valid_0's l2: 0.203209
[400]	valid_0's rmse: 0.442706	valid_0's l2: 0.195989
[600]	valid_0's rmse: 0.441385	valid_0's l2: 0.194821
[800]	valid_0's rmse: 0.440842	valid_0's l2: 0.194342

Best trial: 21. Best value: 0.462555:  50%|█████     | 25/50 [03:24<03:23,  8.15s/it]

Did not meet early stopping. Best iteration is:
[845]	valid_0's rmse: 0.440628	valid_0's l2: 0.194153
[I 2026-06-13 15:35:36,555] Trial 24 finished with value: 0.46275715764181086 and parameters: {'n_estimators': 935, 'num_leaves': 48, 'max_depth': 4, 'learning_rate': 0.01940217624214081, 'subsample': 0.8656685875995435, 'colsample_bytree': 0.5395629657621732, 'min_child_weight': 2, 'reg_alpha': 0.0006569669757428542, 'reg_lambda': 0.052428801959121224, 'min_split_gain': 0.2626987685524113}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.485892	valid_0's l2: 0.236091
[400]	valid_0's rmse: 0.474238	valid_0's l2: 0.224902
[600]	valid_0's rmse: 0.47254	valid_0's l2: 0.223294
Did not meet early stopping. Best iteration is:
[695]	valid_0's rmse: 0.472188	valid_0's l2: 0.222961
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.495614	valid_0's l2: 0.245634
[400]	valid_0's rmse: 0.484311	valid_0's l2: 0.234557
[600]	valid_0's rmse: 0.480335	valid_0's l2: 0.230721
Did not meet early stopping. Best iteration is:
[695]	valid_0's rmse: 0.479119	valid_0's l2: 0.229555
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.468395	valid_0's l2: 0.219394
[400]	valid_0's rmse: 0.449565	valid_0's l2: 0.202109
[600]	valid_0's rmse: 0.4442	valid_0's l2: 0.197314
Did not meet early stopping. Best iteration is:
[698]	valid_0's rmse: 0.442629	valid_0's l2: 0.19592

Best trial: 21. Best value: 0.462555:  52%|█████▏    | 26/50 [03:32<03:15,  8.13s/it]

[I 2026-06-13 15:35:44,644] Trial 25 finished with value: 0.4646451755198469 and parameters: {'n_estimators': 698, 'num_leaves': 52, 'max_depth': 4, 'learning_rate': 0.010116511605034424, 'subsample': 0.8424780391327984, 'colsample_bytree': 0.5297410460732275, 'min_child_weight': 2, 'reg_alpha': 0.001317349897793665, 'reg_lambda': 3.482455922047791, 'min_split_gain': 0.222408392494168}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479111	valid_0's l2: 0.229547
[400]	valid_0's rmse: 0.473139	valid_0's l2: 0.223861
Did not meet early stopping. Best iteration is:
[429]	valid_0's rmse: 0.472856	valid_0's l2: 0.223593
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.487692	valid_0's l2: 0.237843
[400]	valid_0's rmse: 0.480632	valid_0's l2: 0.231007
Did not meet early stopping. Best iteration is:
[429]	valid_0's rmse: 0.480084	valid_0's l2: 0.23048
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.456761	valid_0's l2: 0.208631

Best trial: 21. Best value: 0.462555:  54%|█████▍    | 27/50 [03:37<02:46,  7.26s/it]

[400]	valid_0's rmse: 0.445439	valid_0's l2: 0.198416
Did not meet early stopping. Best iteration is:
[428]	valid_0's rmse: 0.444377	valid_0's l2: 0.197471
[I 2026-06-13 15:35:49,868] Trial 26 finished with value: 0.4657721570252264 and parameters: {'n_estimators': 430, 'num_leaves': 47, 'max_depth': 3, 'learning_rate': 0.018710505318249363, 'subsample': 0.9418504378855468, 'colsample_bytree': 0.4587426163276424, 'min_child_weight': 3, 'reg_alpha': 0.001389030788728729, 'reg_lambda': 0.3368025549734173, 'min_split_gain': 0.083172028101544}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.47434	valid_0's l2: 0.224998
Early stopping, best iteration is:
[149]	valid_0's rmse: 0.47306	valid_0's l2: 0.223786
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.477077	valid_0's l2: 0.227603
[400]	valid_0's rmse: 0.477312	valid_0's l2: 0.227827
Early stopping, best iteration is:
[260]	valid_0's rmse: 0.476472	valid_0's l2: 0.227025
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.441245	valid_0's l2: 0.194697

Best trial: 21. Best value: 0.462555:  56%|█████▌    | 28/50 [03:43<02:31,  6.89s/it]

[400]	valid_0's rmse: 0.442576	valid_0's l2: 0.195873
Early stopping, best iteration is:
[253]	valid_0's rmse: 0.439607	valid_0's l2: 0.193255
[I 2026-06-13 15:35:55,894] Trial 27 finished with value: 0.46304646536248945 and parameters: {'n_estimators': 1059, 'num_leaves': 35, 'max_depth': 4, 'learning_rate': 0.06329103949789443, 'subsample': 0.7656118274493503, 'colsample_bytree': 0.6287828697369047, 'min_child_weight': 7, 'reg_alpha': 3.1804366066238106e-06, 'reg_lambda': 0.004163317567735938, 'min_split_gain': 0.17412135007034057}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.475999	valid_0's l2: 0.226575
Early stopping, best iteration is:
[122]	valid_0's rmse: 0.474874	valid_0's l2: 0.225505
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479017	valid_0's l2: 0.229458
[400]	valid_0's rmse: 0.478653	valid_0's l2: 0.229109
Early stopping, best iteration is:
[267]	valid_0's rmse: 0.478618	valid_0's l2: 0.229075
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.441984	valid_0's l2: 0.19535

Best trial: 21. Best value: 0.462555:  58%|█████▊    | 29/50 [03:51<02:28,  7.09s/it]

[400]	valid_0's rmse: 0.440984	valid_0's l2: 0.194467
Early stopping, best iteration is:
[297]	valid_0's rmse: 0.440902	valid_0's l2: 0.194395
[I 2026-06-13 15:36:03,456] Trial 28 finished with value: 0.4647979030196466 and parameters: {'n_estimators': 1346, 'num_leaves': 61, 'max_depth': 7, 'learning_rate': 0.031931144361644626, 'subsample': 0.8395393854010434, 'colsample_bytree': 0.5684369789990552, 'min_child_weight': 1, 'reg_alpha': 4.089461189320735e-05, 'reg_lambda': 0.027210331478751598, 'min_split_gain': 0.27321613421703006}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.489276	valid_0's l2: 0.239391
[400]	valid_0's rmse: 0.476449	valid_0's l2: 0.227003
[600]	valid_0's rmse: 0.473923	valid_0's l2: 0.224603
Did not meet early stopping. Best iteration is:
[638]	valid_0's rmse: 0.473567	valid_0's l2: 0.224265
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.499956	valid_0's l2: 0.249956
[400]	valid_0's rmse: 0.487769	valid_0's l2: 0.237919
[600]	valid_0's rmse: 0.482895	valid_0's l2: 0.233187
Did not meet early stopping. Best iteration is:
[638]	valid_0's rmse: 0.482285	valid_0's l2: 0.232599
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474371	valid_0's l2: 0.225027
[400]	valid_0's rmse: 0.455537	valid_0's l2: 0.207514

Best trial: 21. Best value: 0.462555:  60%|██████    | 30/50 [03:58<02:19,  6.97s/it]

[600]	valid_0's rmse: 0.449299	valid_0's l2: 0.201869
Did not meet early stopping. Best iteration is:
[638]	valid_0's rmse: 0.448557	valid_0's l2: 0.201203
[I 2026-06-13 15:36:10,141] Trial 29 finished with value: 0.46813613053389397 and parameters: {'n_estimators': 638, 'num_leaves': 37, 'max_depth': 3, 'learning_rate': 0.010558891667844102, 'subsample': 0.8091969545342491, 'colsample_bytree': 0.697197995890713, 'min_child_weight': 4, 'reg_alpha': 0.08549877386218216, 'reg_lambda': 9.64834709610372, 'min_split_gain': 0.11277664729406575}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474837	valid_0's l2: 0.22547
[400]	valid_0's rmse: 0.474397	valid_0's l2: 0.225052
Early stopping, best iteration is:
[287]	valid_0's rmse: 0.474393	valid_0's l2: 0.225048
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.481926	valid_0's l2: 0.232252
[400]	valid_0's rmse: 0.478752	valid_0's l2: 0.229204
Early stopping, best iteration is:
[317]	valid_0's rmse: 0.478752	valid_0's l2: 0.229204
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.445203	valid_0's l2: 0.198206
[400]	valid_0's rmse: 0.441063	valid_0's l2: 0.194537
Early stopping, best iteration is:
[358]	valid_0's rmse: 0.441063	valid_0's l2: 0.194537

Best trial: 21. Best value: 0.462555:  62%|██████▏   | 31/50 [04:07<02:24,  7.60s/it]

[I 2026-06-13 15:36:19,215] Trial 30 finished with value: 0.4647360294535996 and parameters: {'n_estimators': 724, 'num_leaves': 52, 'max_depth': 7, 'learning_rate': 0.02086722311749288, 'subsample': 0.9523302415946533, 'colsample_bytree': 0.8281020965974191, 'min_child_weight': 6, 'reg_alpha': 0.0004215980274260818, 'reg_lambda': 0.610525696880368, 'min_split_gain': 0.43260868423609994}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.471779	valid_0's l2: 0.222575
[400]	valid_0's rmse: 0.472996	valid_0's l2: 0.223725
Early stopping, best iteration is:
[248]	valid_0's rmse: 0.471035	valid_0's l2: 0.221874
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479787	valid_0's l2: 0.230196
[400]	valid_0's rmse: 0.477341	valid_0's l2: 0.227855
[600]	valid_0's rmse: 0.477244	valid_0's l2: 0.227762
Early stopping, best iteration is:
[431]	valid_0's rmse: 0.477181	valid_0's l2: 0.227702
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.443893	valid_0's l2: 0.197041
[400]	valid_0's rmse: 0.440818	valid_0's l2: 0.19432

Best trial: 21. Best value: 0.462555:  64%|██████▍   | 32/50 [04:14<02:15,  7.53s/it]

[600]	valid_0's rmse: 0.441153	valid_0's l2: 0.194616
Early stopping, best iteration is:
[416]	valid_0's rmse: 0.440569	valid_0's l2: 0.194101
[I 2026-06-13 15:36:26,586] Trial 31 finished with value: 0.46292854427453217 and parameters: {'n_estimators': 889, 'num_leaves': 29, 'max_depth': 5, 'learning_rate': 0.02898961934043975, 'subsample': 0.8873806731374788, 'colsample_bytree': 0.5684499307711928, 'min_child_weight': 5, 'reg_alpha': 0.0002283364749132561, 'reg_lambda': 0.08745872582347279, 'min_split_gain': 0.28721867639178295}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.47244	valid_0's l2: 0.223199
Early stopping, best iteration is:
[148]	valid_0's rmse: 0.471985	valid_0's l2: 0.22277
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.477543	valid_0's l2: 0.228047
[400]	valid_0's rmse: 0.476785	valid_0's l2: 0.227323
Early stopping, best iteration is:
[244]	valid_0's rmse: 0.476783	valid_0's l2: 0.227322
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.441491	valid_0's l2: 0.194914

Best trial: 21. Best value: 0.462555:  66%|██████▌   | 33/50 [04:20<02:02,  7.20s/it]

[400]	valid_0's rmse: 0.440476	valid_0's l2: 0.194019
Early stopping, best iteration is:
[266]	valid_0's rmse: 0.440464	valid_0's l2: 0.194009
[I 2026-06-13 15:36:33,017] Trial 32 finished with value: 0.46307727782484737 and parameters: {'n_estimators': 918, 'num_leaves': 29, 'max_depth': 5, 'learning_rate': 0.04419917505619423, 'subsample': 0.8597226178770854, 'colsample_bytree': 0.6436474811791653, 'min_child_weight': 4, 'reg_alpha': 0.0038913178174585484, 'reg_lambda': 0.026180011711800732, 'min_split_gain': 0.403863819671386}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.473196	valid_0's l2: 0.223915
[400]	valid_0's rmse: 0.472623	valid_0's l2: 0.223372
Early stopping, best iteration is:
[286]	valid_0's rmse: 0.472149	valid_0's l2: 0.222925
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.480992	valid_0's l2: 0.231354
[400]	valid_0's rmse: 0.476111	valid_0's l2: 0.226681
Early stopping, best iteration is:
[392]	valid_0's rmse: 0.476102	valid_0's l2: 0.226674
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.44545	valid_0's l2: 0.198426
[400]	valid_0's rmse: 0.440357	valid_0's l2: 0.193914
[600]	valid_0's rmse: 0.440207	valid_0's l2: 0.193782

Best trial: 21. Best value: 0.462555:  68%|██████▊   | 34/50 [04:27<01:50,  6.92s/it]

Early stopping, best iteration is:
[434]	valid_0's rmse: 0.440207	valid_0's l2: 0.193782
[I 2026-06-13 15:36:39,268] Trial 33 finished with value: 0.46282233223145725 and parameters: {'n_estimators': 1066, 'num_leaves': 25, 'max_depth': 4, 'learning_rate': 0.02839437117600477, 'subsample': 0.7984802679260791, 'colsample_bytree': 0.5390553763818453, 'min_child_weight': 2, 'reg_alpha': 0.00022355883339162996, 'reg_lambda': 0.1590198372291734, 'min_split_gain': 0.5918813473893257}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.473687	valid_0's l2: 0.224379
Early stopping, best iteration is:
[160]	valid_0's rmse: 0.473494	valid_0's l2: 0.224197
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.478173	valid_0's l2: 0.22865
[400]	valid_0's rmse: 0.478162	valid_0's l2: 0.228639
Early stopping, best iteration is:
[203]	valid_0's rmse: 0.478162	valid_0's l2: 0.228639
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.441035	valid_0's l2: 0.194512
[400]	valid_0's rmse: 0.441044	valid_0's l2: 0.19452
Early stopping, best iteration is:
[209]	valid_0's rmse: 0.440909	valid_0's l2: 0.194401

Best trial: 21. Best value: 0.462555:  70%|███████   | 35/50 [04:32<01:34,  6.28s/it]

[I 2026-06-13 15:36:44,072] Trial 34 finished with value: 0.4641884763513942 and parameters: {'n_estimators': 1051, 'num_leaves': 24, 'max_depth': 4, 'learning_rate': 0.05666020465992497, 'subsample': 0.8046556552568629, 'colsample_bytree': 0.4943121723845811, 'min_child_weight': 2, 'reg_alpha': 0.02510804314755256, 'reg_lambda': 0.0014735495343140466, 'min_split_gain': 0.6016762325304776}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.473044	valid_0's l2: 0.223771
Early stopping, best iteration is:
[194]	valid_0's rmse: 0.472643	valid_0's l2: 0.223391
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479021	valid_0's l2: 0.229462
[400]	valid_0's rmse: 0.476404	valid_0's l2: 0.226961
Early stopping, best iteration is:
[352]	valid_0's rmse: 0.476196	valid_0's l2: 0.226763
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.44202	valid_0's l2: 0.195382
[400]	valid_0's rmse: 0.441025	valid_0's l2: 0.194503

Best trial: 21. Best value: 0.462555:  72%|███████▏  | 36/50 [04:38<01:28,  6.29s/it]

Early stopping, best iteration is:
[376]	valid_0's rmse: 0.440558	valid_0's l2: 0.194092
[I 2026-06-13 15:36:50,383] Trial 35 finished with value: 0.4631323210999763 and parameters: {'n_estimators': 1200, 'num_leaves': 38, 'max_depth': 4, 'learning_rate': 0.040675613048973956, 'subsample': 0.800936552791692, 'colsample_bytree': 0.5334834143147705, 'min_child_weight': 2, 'reg_alpha': 0.002202468909523901, 'reg_lambda': 0.18866379016727164, 'min_split_gain': 0.15323987374696663}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.474407	valid_0's l2: 0.225062
Early stopping, best iteration is:
[151]	valid_0's rmse: 0.472585	valid_0's l2: 0.223337
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.476534	valid_0's l2: 0.227084
[400]	valid_0's rmse: 0.475863	valid_0's l2: 0.226446
Early stopping, best iteration is:
[219]	valid_0's rmse: 0.475863	valid_0's l2: 0.226446
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.440276	valid_0's l2: 0.193843
[400]	valid_0's rmse: 0.439895	valid_0's l2: 0.193507
Early stopping, best iteration is:
[242]	valid_0's rmse: 0.439875	valid_0's l2: 0.19349

Best trial: 21. Best value: 0.462555:  74%|███████▍  | 37/50 [04:42<01:15,  5.79s/it]

[I 2026-06-13 15:36:55,006] Trial 36 finished with value: 0.4627746545362406 and parameters: {'n_estimators': 1257, 'num_leaves': 46, 'max_depth': 3, 'learning_rate': 0.0830790079475774, 'subsample': 0.7325965126149548, 'colsample_bytree': 0.45000945942083737, 'min_child_weight': 3, 'reg_alpha': 0.007101780549878456, 'reg_lambda': 2.332146552421762, 'min_split_gain': 0.5780926846736018}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.473394	valid_0's l2: 0.224102
Early stopping, best iteration is:
[78]	valid_0's rmse: 0.47233	valid_0's l2: 0.223096
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.477951	valid_0's l2: 0.228437
Early stopping, best iteration is:
[123]	valid_0's rmse: 0.477951	valid_0's l2: 0.228437
Training until validation scores don't improve for 200 rounds

Best trial: 21. Best value: 0.462555:  76%|███████▌  | 38/50 [04:47<01:04,  5.40s/it]

[200]	valid_0's rmse: 0.441045	valid_0's l2: 0.194521
Early stopping, best iteration is:
[110]	valid_0's rmse: 0.440972	valid_0's l2: 0.194456
[I 2026-06-13 15:36:59,494] Trial 37 finished with value: 0.4637509337761847 and parameters: {'n_estimators': 1269, 'num_leaves': 56, 'max_depth': 5, 'learning_rate': 0.08369097989435349, 'subsample': 0.6567781677808173, 'colsample_bytree': 0.4796803961414799, 'min_child_weight': 1, 'reg_alpha': 0.0131885912038104, 'reg_lambda': 2.53900485949267, 'min_split_gain': 0.5403980500387305}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.475337	valid_0's l2: 0.225945
Early stopping, best iteration is:
[77]	valid_0's rmse: 0.473749	valid_0's l2: 0.224438
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.478851	valid_0's l2: 0.229299
Early stopping, best iteration is:
[117]	valid_0's rmse: 0.478851	valid_0's l2: 0.229299
Training until validation scores don't improve for 200 rounds

Best trial: 21. Best value: 0.462555:  78%|███████▊  | 39/50 [04:51<00:55,  5.04s/it]

[200]	valid_0's rmse: 0.440105	valid_0's l2: 0.193692
Early stopping, best iteration is:
[119]	valid_0's rmse: 0.439845	valid_0's l2: 0.193464
[I 2026-06-13 15:37:03,707] Trial 38 finished with value: 0.4641484914604616 and parameters: {'n_estimators': 1508, 'num_leaves': 66, 'max_depth': 4, 'learning_rate': 0.10673289108040254, 'subsample': 0.7344827879240563, 'colsample_bytree': 0.4305885428834355, 'min_child_weight': 6, 'reg_alpha': 0.35251586711220817, 'reg_lambda': 1.0601717314186394, 'min_split_gain': 0.5826843022607606}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.50447	valid_0's l2: 0.25449
[400]	valid_0's rmse: 0.483372	valid_0's l2: 0.233648
[600]	valid_0's rmse: 0.476646	valid_0's l2: 0.227192
[800]	valid_0's rmse: 0.474558	valid_0's l2: 0.225205
[1000]	valid_0's rmse: 0.473246	valid_0's l2: 0.223962
Did not meet early stopping. Best iteration is:
[1123]	valid_0's rmse: 0.47269	valid_0's l2: 0.223435
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.514534	valid_0's l2: 0.264745
[400]	valid_0's rmse: 0.492506	valid_0's l2: 0.242562
[600]	valid_0's rmse: 0.486273	valid_0's l2: 0.236461
[800]	valid_0's rmse: 0.483108	valid_0's l2: 0.233394
[1000]	valid_0's rmse: 0.481165	valid_0's l2: 0.23152
Did not meet early stopping. Best iteration is:
[1123]	valid_0's rmse: 0.48034	valid_0's l2: 0.230727
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.494958	valid_0's l2: 0.244984
[400]	valid_0's rmse: 0.464341	valid_0's l2: 0.215613
[600]	valid_0's rmse: 0.453926	valid_0's l2: 0.206049
[800]	valid_0's rmse: 0.448988	valid_0's l2: 0.20159
[1000]	valid_0's rmse: 0.446634	valid_0's l2: 0.199482
Did not meet early stopping. Best iteration is:
[1123]	valid_0's rmse: 0.444992	valid_0's l2: 0.198018

Best trial: 21. Best value: 0.462555:  80%|████████  | 40/50 [05:00<01:01,  6.11s/it]

[I 2026-06-13 15:37:12,289] Trial 39 finished with value: 0.46600718403689506 and parameters: {'n_estimators': 1123, 'num_leaves': 48, 'max_depth': 3, 'learning_rate': 0.007015670859744059, 'subsample': 0.6437355280512231, 'colsample_bytree': 0.5123250917612286, 'min_child_weight': 3, 'reg_alpha': 0.010323789568646675, 'reg_lambda': 0.01708723217333258, 'min_split_gain': 0.6958572073239749}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.47366	valid_0's l2: 0.224354
Early stopping, best iteration is:
[32]	valid_0's rmse: 0.472771	valid_0's l2: 0.223512
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.481954	valid_0's l2: 0.23228
Early stopping, best iteration is:
[55]	valid_0's rmse: 0.481954	valid_0's l2: 0.23228
Training until validation scores don't improve for 200 rounds

Best trial: 21. Best value: 0.462555:  82%|████████▏ | 41/50 [05:04<00:49,  5.47s/it]

[200]	valid_0's rmse: 0.442331	valid_0's l2: 0.195657
Early stopping, best iteration is:
[49]	valid_0's rmse: 0.442331	valid_0's l2: 0.195657
[I 2026-06-13 15:37:16,292] Trial 40 finished with value: 0.4656852300670886 and parameters: {'n_estimators': 1239, 'num_leaves': 113, 'max_depth': 6, 'learning_rate': 0.16900470220389005, 'subsample': 0.7276048036469281, 'colsample_bytree': 0.4454491832741783, 'min_child_weight': 12, 'reg_alpha': 1.896669949528837, 'reg_lambda': 3.560610526981402, 'min_split_gain': 0.8684498462021999}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479431	valid_0's l2: 0.229854
Early stopping, best iteration is:
[79]	valid_0's rmse: 0.474016	valid_0's l2: 0.224691
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.47667	valid_0's l2: 0.227214
[400]	valid_0's rmse: 0.478249	valid_0's l2: 0.228722
Early stopping, best iteration is:
[227]	valid_0's rmse: 0.475893	valid_0's l2: 0.226474
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.442793	valid_0's l2: 0.196065
Early stopping, best iteration is:
[120]	valid_0's rmse: 0.440451	valid_0's l2: 0.193997

Best trial: 21. Best value: 0.462555:  84%|████████▍ | 42/50 [05:09<00:42,  5.29s/it]

[I 2026-06-13 15:37:21,143] Trial 41 finished with value: 0.4634532446623267 and parameters: {'n_estimators': 1090, 'num_leaves': 31, 'max_depth': 3, 'learning_rate': 0.12127801168790071, 'subsample': 0.8301804755450111, 'colsample_bytree': 0.5480082744519077, 'min_child_weight': 4, 'reg_alpha': 0.000797815339664385, 'reg_lambda': 0.03790964845129985, 'min_split_gain': 0.06513339955781072}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.48702	valid_0's l2: 0.237189
[400]	valid_0's rmse: 0.475354	valid_0's l2: 0.225962
[600]	valid_0's rmse: 0.47299	valid_0's l2: 0.22372
[800]	valid_0's rmse: 0.471716	valid_0's l2: 0.222516
Did not meet early stopping. Best iteration is:
[958]	valid_0's rmse: 0.471021	valid_0's l2: 0.221861
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.495471	valid_0's l2: 0.245492
[400]	valid_0's rmse: 0.484484	valid_0's l2: 0.234725
[600]	valid_0's rmse: 0.480288	valid_0's l2: 0.230676
[800]	valid_0's rmse: 0.477943	valid_0's l2: 0.228429
Did not meet early stopping. Best iteration is:
[966]	valid_0's rmse: 0.476453	valid_0's l2: 0.227007
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.468927	valid_0's l2: 0.219893
[400]	valid_0's rmse: 0.451577	valid_0's l2: 0.203922
[600]	valid_0's rmse: 0.446054	valid_0's l2: 0.198964
[800]	valid_0's rmse: 0.442669	valid_0's l2: 0.195955

Best trial: 21. Best value: 0.462555:  86%|████████▌ | 43/50 [05:16<00:42,  6.02s/it]

Did not meet early stopping. Best iteration is:
[966]	valid_0's rmse: 0.441267	valid_0's l2: 0.194716
[I 2026-06-13 15:37:28,860] Trial 42 finished with value: 0.46291344319253985 and parameters: {'n_estimators': 967, 'num_leaves': 42, 'max_depth': 3, 'learning_rate': 0.012344116894530998, 'subsample': 0.7873922948362825, 'colsample_bytree': 0.5120650697924692, 'min_child_weight': 2, 'reg_alpha': 0.0789730922469341, 'reg_lambda': 0.3089432463950538, 'min_split_gain': 0.6381929497548124}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.472907	valid_0's l2: 0.223641
Early stopping, best iteration is:
[120]	valid_0's rmse: 0.472891	valid_0's l2: 0.223626
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.479207	valid_0's l2: 0.22964
Early stopping, best iteration is:
[131]	valid_0's rmse: 0.479145	valid_0's l2: 0.22958
Training until validation scores don't improve for 200 rounds

Best trial: 21. Best value: 0.462555:  88%|████████▊ | 44/50 [05:21<00:33,  5.57s/it]

[200]	valid_0's rmse: 0.441383	valid_0's l2: 0.194819
Early stopping, best iteration is:
[138]	valid_0's rmse: 0.441267	valid_0's l2: 0.194717
[I 2026-06-13 15:37:33,396] Trial 43 finished with value: 0.46443454537839807 and parameters: {'n_estimators': 1396, 'num_leaves': 75, 'max_depth': 4, 'learning_rate': 0.07652085689601898, 'subsample': 0.8603078395721605, 'colsample_bytree': 0.46745968142879024, 'min_child_weight': 8, 'reg_alpha': 0.005345115594544078, 'reg_lambda': 0.763381582652142, 'min_split_gain': 0.7352417752774636}. Best is trial 21 with value: 0.4625550575492252.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.476229	valid_0's l2: 0.226794
[400]	valid_0's rmse: 0.473312	valid_0's l2: 0.224024
[600]	valid_0's rmse: 0.471989	valid_0's l2: 0.222774
[800]	valid_0's rmse: 0.472847	valid_0's l2: 0.223584
Early stopping, best iteration is:
[614]	valid_0's rmse: 0.471839	valid_0's l2: 0.222632
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.486926	valid_0's l2: 0.237097
[400]	valid_0's rmse: 0.480083	valid_0's l2: 0.23048
[600]	valid_0's rmse: 0.476844	valid_0's l2: 0.22738
[800]	valid_0's rmse: 0.475333	valid_0's l2: 0.225941
[1000]	valid_0's rmse: 0.475166	valid_0's l2: 0.225782
Early stopping, best iteration is:
[913]	valid_0's rmse: 0.475074	valid_0's l2: 0.225695
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.454451	valid_0's l2: 0.206525
[400]	valid_0's rmse: 0.445316	valid_0's l2: 0.198307
[600]	valid_0's rmse: 0.44177	valid_0's l2: 0.195161
[800]	valid_0's rmse: 0.440491	valid_0's l2: 0.194032
[1000]	valid_0's rmse: 0.439548	valid_0's l2: 0.193202
Did not meet early stopping. Best iteration is:
[1054]	valid_0's rmse: 0.439324	valid_0's l2: 0.193006

Best trial: 44. Best value: 0.462079:  90%|█████████ | 45/50 [05:29<00:31,  6.39s/it]

[I 2026-06-13 15:37:41,706] Trial 44 finished with value: 0.46207905090500206 and parameters: {'n_estimators': 1180, 'num_leaves': 22, 'max_depth': 3, 'learning_rate': 0.021228238945123736, 'subsample': 0.9084471776934789, 'colsample_bytree': 0.7199410703600272, 'min_child_weight': 3, 'reg_alpha': 5.7063482163442614e-05, 'reg_lambda': 0.003918181090381991, 'min_split_gain': 0.44584003876817246}. Best is trial 44 with value: 0.46207905090500206.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.475561	valid_0's l2: 0.226159
[400]	valid_0's rmse: 0.472926	valid_0's l2: 0.223659
[600]	valid_0's rmse: 0.473186	valid_0's l2: 0.223905
Early stopping, best iteration is:
[499]	valid_0's rmse: 0.47262	valid_0's l2: 0.22337
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.484066	valid_0's l2: 0.23432
[400]	valid_0's rmse: 0.478712	valid_0's l2: 0.229166
[600]	valid_0's rmse: 0.476634	valid_0's l2: 0.22718
[800]	valid_0's rmse: 0.476481	valid_0's l2: 0.227034
Early stopping, best iteration is:
[642]	valid_0's rmse: 0.476481	valid_0's l2: 0.227034
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.45025	valid_0's l2: 0.202725
[400]	valid_0's rmse: 0.442069	valid_0's l2: 0.195425
[600]	valid_0's rmse: 0.440868	valid_0's l2: 0.194364
[800]	valid_0's rmse: 0.440232	valid_0's l2: 0.193804
Early stopping, best iteration is:
[721]	valid_0's rmse: 0.44021	valid_0's l2: 0.193785

Best trial: 44. Best value: 0.462079:  92%|█████████▏| 46/50 [05:37<00:27,  6.88s/it]

[I 2026-06-13 15:37:49,704] Trial 45 finished with value: 0.46310383764112517 and parameters: {'n_estimators': 1171, 'num_leaves': 23, 'max_depth': 4, 'learning_rate': 0.020727383559836304, 'subsample': 0.9012550333490108, 'colsample_bytree': 0.7276877729500918, 'min_child_weight': 17, 'reg_alpha': 6.232195621885201e-05, 'reg_lambda': 0.0018305070775154007, 'min_split_gain': 0.4459476718149996}. Best is trial 44 with value: 0.46207905090500206.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.500987	valid_0's l2: 0.250988
[400]	valid_0's rmse: 0.480807	valid_0's l2: 0.231176
[600]	valid_0's rmse: 0.47607	valid_0's l2: 0.226643
[800]	valid_0's rmse: 0.475037	valid_0's l2: 0.22566
[1000]	valid_0's rmse: 0.474397	valid_0's l2: 0.225052
[1200]	valid_0's rmse: 0.474067	valid_0's l2: 0.22474
Did not meet early stopping. Best iteration is:
[1170]	valid_0's rmse: 0.473984	valid_0's l2: 0.224661
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.511898	valid_0's l2: 0.26204
[400]	valid_0's rmse: 0.490368	valid_0's l2: 0.240461
[600]	valid_0's rmse: 0.484838	valid_0's l2: 0.235068
[800]	valid_0's rmse: 0.48197	valid_0's l2: 0.232295
[1000]	valid_0's rmse: 0.480432	valid_0's l2: 0.230815
[1200]	valid_0's rmse: 0.479332	valid_0's l2: 0.229759
Did not meet early stopping. Best iteration is:
[1309]	valid_0's rmse: 0.478748	valid_0's l2: 0.2292
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.48916	valid_0's l2: 0.239277
[400]	valid_0's rmse: 0.460191	valid_0's l2: 0.211775
[600]	valid_0's rmse: 0.450916	valid_0's l2: 0.203325
[800]	valid_0's rmse: 0.446953	valid_0's l2: 0.199767
[1000]	valid_0's rmse: 0.444543	valid_0's l2: 0.197619
[1200]	valid_0's rmse: 0.442636	valid_0's l2: 0.195927
Did not meet early stopping. Best iteration is:
[1306]	valid_0's rmse: 0.441804	valid_0's l2: 0.195191

Best trial: 44. Best value: 0.462079:  94%|█████████▍| 47/50 [05:57<00:31, 10.66s/it]

[I 2026-06-13 15:38:09,203] Trial 46 finished with value: 0.4648455135298368 and parameters: {'n_estimators': 1310, 'num_leaves': 33, 'max_depth': 5, 'learning_rate': 0.005283019215489318, 'subsample': 0.7467535760969232, 'colsample_bytree': 0.7923682104261276, 'min_child_weight': 3, 'reg_alpha': 1.1275413892370375e-05, 'reg_lambda': 0.0027665481504762193, 'min_split_gain': 0.5536756579836252}. Best is trial 44 with value: 0.46207905090500206.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.482926	valid_0's l2: 0.233217
[400]	valid_0's rmse: 0.473978	valid_0's l2: 0.224655
[600]	valid_0's rmse: 0.472137	valid_0's l2: 0.222914
[800]	valid_0's rmse: 0.471268	valid_0's l2: 0.222094
Early stopping, best iteration is:
[778]	valid_0's rmse: 0.471182	valid_0's l2: 0.222013
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.490864	valid_0's l2: 0.240948
[400]	valid_0's rmse: 0.482168	valid_0's l2: 0.232486
[600]	valid_0's rmse: 0.478472	valid_0's l2: 0.228936
[800]	valid_0's rmse: 0.476362	valid_0's l2: 0.226921
[1000]	valid_0's rmse: 0.475372	valid_0's l2: 0.225978
[1200]	valid_0's rmse: 0.474782	valid_0's l2: 0.225418
[1400]	valid_0's rmse: 0.474538	valid_0's l2: 0.225186
Did not meet early stopping. Best iteration is:
[1462]	valid_0's rmse: 0.474479	valid_0's l2: 0.22513
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.462541	valid_0's l2: 0.213944
[400]	valid_0's rmse: 0.447519	valid_0's l2: 0.200274
[600]	valid_0's rmse: 0.442162	valid_0's l2: 0.195508
[800]	valid_0's rmse: 0.440091	valid_0's l2: 0.19368
[1000]	valid_0's rmse: 0.43962	valid_0's l2: 0.193266
[1200]	valid_0's rmse: 0.439294	valid_0's l2: 0.19298
[1400]	valid_0's rmse: 0.438669	valid_0's l2: 0.19243
Did not meet early stopping. Best iteration is:
[1444]	valid_0's rmse: 0.438546	valid_0's l2: 0.192322

Best trial: 47. Best value: 0.461402:  96%|█████████▌| 48/50 [06:07<00:21, 10.50s/it]

[I 2026-06-13 15:38:19,327] Trial 47 finished with value: 0.4614022927615053 and parameters: {'n_estimators': 1504, 'num_leaves': 22, 'max_depth': 3, 'learning_rate': 0.015445827808585411, 'subsample': 0.959810550737529, 'colsample_bytree': 0.4008077170758463, 'min_child_weight': 1, 'reg_alpha': 0.00015851767615267367, 'reg_lambda': 0.0006241354370674286, 'min_split_gain': 0.39191613263070235}. Best is trial 47 with value: 0.4614022927615053.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.484025	valid_0's l2: 0.23428
[400]	valid_0's rmse: 0.47418	valid_0's l2: 0.224847
[600]	valid_0's rmse: 0.472548	valid_0's l2: 0.223302
[800]	valid_0's rmse: 0.471476	valid_0's l2: 0.22229
[1000]	valid_0's rmse: 0.471392	valid_0's l2: 0.22221
Early stopping, best iteration is:
[911]	valid_0's rmse: 0.471153	valid_0's l2: 0.221986
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.492512	valid_0's l2: 0.242568
[400]	valid_0's rmse: 0.482636	valid_0's l2: 0.232938
[600]	valid_0's rmse: 0.479231	valid_0's l2: 0.229662
[800]	valid_0's rmse: 0.476985	valid_0's l2: 0.227515
[1000]	valid_0's rmse: 0.475494	valid_0's l2: 0.226094
[1200]	valid_0's rmse: 0.474998	valid_0's l2: 0.225623
[1400]	valid_0's rmse: 0.474796	valid_0's l2: 0.225431
Did not meet early stopping. Best iteration is:
[1563]	valid_0's rmse: 0.47467	valid_0's l2: 0.225312
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.464423	valid_0's l2: 0.215689
[400]	valid_0's rmse: 0.448425	valid_0's l2: 0.201085
[600]	valid_0's rmse: 0.442946	valid_0's l2: 0.196201
[800]	valid_0's rmse: 0.440338	valid_0's l2: 0.193897
[1000]	valid_0's rmse: 0.43963	valid_0's l2: 0.193275
[1200]	valid_0's rmse: 0.439051	valid_0's l2: 0.192766
[1400]	valid_0's rmse: 0.438806	valid_0's l2: 0.192551
Did not meet early stopping. Best iteration is:
[1579]	valid_0's rmse: 0.43838	valid_0's l2: 0.192177

Best trial: 48. Best value: 0.461401:  98%|█████████▊| 49/50 [06:18<00:10, 10.62s/it]

[I 2026-06-13 15:38:30,240] Trial 48 finished with value: 0.4614012533415255 and parameters: {'n_estimators': 1580, 'num_leaves': 19, 'max_depth': 3, 'learning_rate': 0.014624076339413969, 'subsample': 0.9678262105904213, 'colsample_bytree': 0.40153594539246124, 'min_child_weight': 1, 'reg_alpha': 3.743259100901015e-07, 'reg_lambda': 3.4602628028485467e-06, 'min_split_gain': 0.364877203684999}. Best is trial 48 with value: 0.4614012533415255.
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.477894	valid_0's l2: 0.228383
[400]	valid_0's rmse: 0.47245	valid_0's l2: 0.223209
[600]	valid_0's rmse: 0.471406	valid_0's l2: 0.222223
Early stopping, best iteration is:
[569]	valid_0's rmse: 0.471167	valid_0's l2: 0.221999
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.487963	valid_0's l2: 0.238108
[400]	valid_0's rmse: 0.480465	valid_0's l2: 0.230847
[600]	valid_0's rmse: 0.477997	valid_0's l2: 0.228481
[800]	valid_0's rmse: 0.476674	valid_0's l2: 0.227218
[1000]	valid_0's rmse: 0.476559	valid_0's l2: 0.227109
Early stopping, best iteration is:
[884]	valid_0's rmse: 0.476417	valid_0's l2: 0.226973
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.455211	valid_0's l2: 0.207217
[400]	valid_0's rmse: 0.443149	valid_0's l2: 0.196381
[600]	valid_0's rmse: 0.441097	valid_0's l2: 0.194566
[800]	valid_0's rmse: 0.440813	valid_0's l2: 0.194316
[1000]	valid_0's rmse: 0.440102	valid_0's l2: 0.19369
[1200]	valid_0's rmse: 0.439957	valid_0's l2: 0.193562
Early stopping, best iteration is:
[1048]	valid_0's rmse: 0.43992	valid_0's l2: 0.19353

Best trial: 48. Best value: 0.461401: 100%|██████████| 50/50 [06:33<00:00,  7.87s/it]
[I 2026-06-13 15:38:45,522] A new study created in memory with name: no-name-dc30431a-53bf-4026-8af7-923889b87bfc

[I 2026-06-13 15:38:45,509] Trial 49 finished with value: 0.4625013879848156 and parameters: {'n_estimators': 1701, 'num_leaves': 19, 'max_depth': 10, 'learning_rate': 0.01405027114089448, 'subsample': 0.9627945907592511, 'colsample_bytree': 0.4141274621746731, 'min_child_weight': 1, 'reg_alpha': 2.6695120576914855e-08, 'reg_lambda': 6.608413091645109e-08, 'min_split_gain': 0.37888435175610036}. Best is trial 48 with value: 0.4614012533415255.

  0%|          | 0/50 [00:00<?, ?it/s]

[0]	validation_0-rmse:0.57510
[200]	validation_0-rmse:0.47956
[262]	validation_0-rmse:0.48088
[0]	validation_0-rmse:0.59496
[200]	validation_0-rmse:0.48011
[353]	validation_0-rmse:0.48268
[0]	validation_0-rmse:0.59045
[200]	validation_0-rmse:0.44485
[332]	validation_0-rmse:0.45156

Best trial: 0. Best value: 0.465192:   2%|▏         | 1/50 [00:16<13:16, 16.25s/it]

[I 2026-06-13 15:39:01,764] Trial 0 finished with value: 0.4651917051352084 and parameters: {'n_estimators': 648, 'max_depth': 4, 'learning_rate': 0.09003544422500852, 'subsample': 0.9042616944207393, 'colsample_bytree': 0.7753770566939775, 'min_child_weight': 10, 'gamma': 0.8857019031149136, 'reg_alpha': 0.06792931113888691, 'reg_lambda': 4.265259954948051e-07}. Best is trial 0 with value: 0.4651917051352084.
[0]	validation_0-rmse:0.58768
[200]	validation_0-rmse:0.47331
[400]	validation_0-rmse:0.47526
[414]	validation_0-rmse:0.47542
[0]	validation_0-rmse:0.60692
[200]	validation_0-rmse:0.47813
[400]	validation_0-rmse:0.47664
[469]	validation_0-rmse:0.47686
[0]	validation_0-rmse:0.60444
[200]	validation_0-rmse:0.44544
[400]	validation_0-rmse:0.44416
[469]	validation_0-rmse:0.44477

Best trial: 1. Best value: 0.46419:   4%|▍         | 2/50 [42:10<19:48:40, 1485.84s/it]

[I 2026-06-13 16:20:56,315] Trial 1 finished with value: 0.464189850588739 and parameters: {'n_estimators': 470, 'max_depth': 6, 'learning_rate': 0.020710936956744613, 'subsample': 0.7878549349038746, 'colsample_bytree': 0.48765441667397996, 'min_child_weight': 11, 'gamma': 0.46880400506122877, 'reg_alpha': 0.0013489390558753562, 'reg_lambda': 0.0064760341946747775}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.58896
[200]	validation_0-rmse:0.48622
[400]	validation_0-rmse:0.48669
[497]	validation_0-rmse:0.48937
[0]	validation_0-rmse:0.60890
[200]	validation_0-rmse:0.49063
[400]	validation_0-rmse:0.48385
[596]	validation_0-rmse:0.48453
[0]	validation_0-rmse:0.60670
[200]	validation_0-rmse:0.47012
[400]	validation_0-rmse:0.46260
[600]	validation_0-rmse:0.46641
[681]	validation_0-rmse:0.46839

Best trial: 1. Best value: 0.46419:   6%|▌         | 3/50 [42:40<10:43:05, 820.97s/it]

[I 2026-06-13 16:21:26,106] Trial 2 finished with value: 0.47669163112315055 and parameters: {'n_estimators': 1502, 'max_depth': 7, 'learning_rate': 0.009745634399862603, 'subsample': 0.5590792417482318, 'colsample_bytree': 0.5456406373206208, 'min_child_weight': 1, 'gamma': 0.36006849771133487, 'reg_alpha': 2.0624133336126844e-07, 'reg_lambda': 0.000766491800334076}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.58894
[200]	validation_0-rmse:0.48790
[400]	validation_0-rmse:0.47494
[600]	validation_0-rmse:0.47300
[800]	validation_0-rmse:0.47262
[1000]	validation_0-rmse:0.47238
[1153]	validation_0-rmse:0.47249
[0]	validation_0-rmse:0.60915
[200]	validation_0-rmse:0.49861
[400]	validation_0-rmse:0.48619
[600]	validation_0-rmse:0.48263
[800]	validation_0-rmse:0.48078
[1000]	validation_0-rmse:0.47934
[1200]	validation_0-rmse:0.47888
[1400]	validation_0-rmse:0.47844
[1600]	validation_0-rmse:0.47854
[1607]	validation_0-rmse:0.47856
[0]	validation_0-rmse:0.60695
[200]	validation_0-rmse:0.47316
[400]	validation_0-rmse:0.45434
[600]	validation_0-rmse:0.44780
[800]	validation_0-rmse:0.44562
[1000]	validation_0-rmse:0.44476
[1200]	validation_0-rmse:0.44543
[1228]	validation_0-rmse:0.44541

Best trial: 1. Best value: 0.46419:   8%|▊         | 4/50 [43:13<6:30:53, 509.85s/it]

[I 2026-06-13 16:21:59,004] Trial 3 finished with value: 0.4650138188361284 and parameters: {'n_estimators': 1743, 'max_depth': 4, 'learning_rate': 0.008216008540101983, 'subsample': 0.6067967803243348, 'colsample_bytree': 0.9838933923057781, 'min_child_weight': 13, 'gamma': 0.5337853219096339, 'reg_alpha': 8.130688426089733e-05, 'reg_lambda': 4.838749044172499e-07}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.58691
[200]	validation_0-rmse:0.47325
[400]	validation_0-rmse:0.47474
[432]	validation_0-rmse:0.47550
[0]	validation_0-rmse:0.60682
[200]	validation_0-rmse:0.48044
[400]	validation_0-rmse:0.47915
[600]	validation_0-rmse:0.48022
[631]	validation_0-rmse:0.48049
[0]	validation_0-rmse:0.60438
[200]	validation_0-rmse:0.44686
[400]	validation_0-rmse:0.44549
[495]	validation_0-rmse:0.44724

Best trial: 1. Best value: 0.46419:  10%|█         | 5/50 [43:39<4:11:30, 335.34s/it]

[I 2026-06-13 16:22:24,914] Trial 4 finished with value: 0.4654162162468862 and parameters: {'n_estimators': 719, 'max_depth': 7, 'learning_rate': 0.01857086572037467, 'subsample': 0.8647277071858408, 'colsample_bytree': 0.7341929399608551, 'min_child_weight': 15, 'gamma': 0.15354563302164526, 'reg_alpha': 1.1642073478060009, 'reg_lambda': 4.002322115071736e-07}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.58192
[200]	validation_0-rmse:0.47704
[324]	validation_0-rmse:0.48198
[0]	validation_0-rmse:0.60141
[200]	validation_0-rmse:0.48012
[400]	validation_0-rmse:0.48002
[474]	validation_0-rmse:0.48056
[0]	validation_0-rmse:0.59876
[200]	validation_0-rmse:0.44756
[400]	validation_0-rmse:0.45231
[423]	validation_0-rmse:0.45252

Best trial: 1. Best value: 0.46419:  12%|█▏        | 6/50 [43:53<2:45:44, 226.01s/it]

[I 2026-06-13 16:22:38,696] Trial 5 finished with value: 0.4675647366501991 and parameters: {'n_estimators': 1270, 'max_depth': 3, 'learning_rate': 0.055685337862373084, 'subsample': 0.6833597752129397, 'colsample_bytree': 0.8773418633934779, 'min_child_weight': 1, 'gamma': 0.48027703893184315, 'reg_alpha': 7.435174672552585e-08, 'reg_lambda': 1.4212042567426725e-07}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.56058
[200]	validation_0-rmse:0.50808
[213]	validation_0-rmse:0.50796
[0]	validation_0-rmse:0.57566
[200]	validation_0-rmse:0.50648
[227]	validation_0-rmse:0.50663
[0]	validation_0-rmse:0.56771
[200]	validation_0-rmse:0.49937
[221]	validation_0-rmse:0.49924

Best trial: 1. Best value: 0.46419:  14%|█▍        | 7/50 [44:05<1:51:47, 155.99s/it]

[I 2026-06-13 16:22:50,542] Trial 6 finished with value: 0.48053980965609977 and parameters: {'n_estimators': 1675, 'max_depth': 7, 'learning_rate': 0.17634438432758487, 'subsample': 0.8466003886104596, 'colsample_bytree': 0.9852748567257518, 'min_child_weight': 8, 'gamma': 0.52487465588629, 'reg_alpha': 1.1520885595798619e-07, 'reg_lambda': 9.68751745033328e-06}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.58893
[200]	validation_0-rmse:0.48702
[400]	validation_0-rmse:0.47875
[600]	validation_0-rmse:0.47993
[656]	validation_0-rmse:0.48051
[0]	validation_0-rmse:0.60909
[200]	validation_0-rmse:0.49407
[400]	validation_0-rmse:0.48385
[600]	validation_0-rmse:0.48298
[689]	validation_0-rmse:0.48278
[0]	validation_0-rmse:0.60699
[200]	validation_0-rmse:0.46906
[400]	validation_0-rmse:0.45525
[600]	validation_0-rmse:0.45622
[672]	validation_0-rmse:0.45663

Best trial: 1. Best value: 0.46419:  16%|█▌        | 8/50 [45:21<1:31:24, 130.58s/it]

[I 2026-06-13 16:24:06,721] Trial 7 finished with value: 0.47210833909396327 and parameters: {'n_estimators': 690, 'max_depth': 9, 'learning_rate': 0.0068894800879573444, 'subsample': 0.7392607796400328, 'colsample_bytree': 0.9026739011047418, 'min_child_weight': 8, 'gamma': 0.0483459820917963, 'reg_alpha': 0.003306088688020413, 'reg_lambda': 4.7303254685446273e-05}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.58821
[200]	validation_0-rmse:0.47681
[400]	validation_0-rmse:0.47429
[600]	validation_0-rmse:0.47402
[693]	validation_0-rmse:0.47510
[0]	validation_0-rmse:0.60821
[200]	validation_0-rmse:0.48688
[400]	validation_0-rmse:0.48073
[600]	validation_0-rmse:0.47855
[800]	validation_0-rmse:0.47735
[1000]	validation_0-rmse:0.47691
[1200]	validation_0-rmse:0.47760
[1212]	validation_0-rmse:0.47750
[0]	validation_0-rmse:0.60580
[200]	validation_0-rmse:0.45536
[400]	validation_0-rmse:0.44604
[600]	validation_0-rmse:0.44463
[735]	validation_0-rmse:0.44472

Best trial: 1. Best value: 0.46419:  18%|█▊        | 9/50 [45:45<1:06:35, 97.46s/it]

[I 2026-06-13 16:24:31,342] Trial 8 finished with value: 0.4647583743373138 and parameters: {'n_estimators': 1483, 'max_depth': 3, 'learning_rate': 0.02045065610592247, 'subsample': 0.5119474130677213, 'colsample_bytree': 0.6311828259689949, 'min_child_weight': 3, 'gamma': 0.22257253997204407, 'reg_alpha': 0.13941719427206353, 'reg_lambda': 0.02902389969877879}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.57521
[200]	validation_0-rmse:0.49674
[234]	validation_0-rmse:0.49677
[0]	validation_0-rmse:0.59406
[200]	validation_0-rmse:0.49560
[242]	validation_0-rmse:0.49636
[0]	validation_0-rmse:0.58904
[200]	validation_0-rmse:0.46927
[234]	validation_0-rmse:0.47305

Best trial: 1. Best value: 0.46419:  20%|██        | 10/50 [46:00<47:54, 71.86s/it]

[I 2026-06-13 16:24:45,895] Trial 9 finished with value: 0.4756524894874434 and parameters: {'n_estimators': 1071, 'max_depth': 9, 'learning_rate': 0.08291665513773347, 'subsample': 0.5454054113547102, 'colsample_bytree': 0.7223781637631188, 'min_child_weight': 11, 'gamma': 0.740180597626157, 'reg_alpha': 0.004446407546354058, 'reg_lambda': 0.8903365890691939}. Best is trial 1 with value: 0.464189850588739.
[0]	validation_0-rmse:0.58669
[200]	validation_0-rmse:0.47046
[267]	validation_0-rmse:0.47076
[0]	validation_0-rmse:0.60610
[200]	validation_0-rmse:0.47791
[267]	validation_0-rmse:0.47732
[0]	validation_0-rmse:0.60331
[200]	validation_0-rmse:0.44266
[267]	validation_0-rmse:0.44146

Best trial: 10. Best value: 0.463019:  22%|██▏       | 11/50 [46:12<34:43, 53.43s/it]

[I 2026-06-13 16:24:57,530] Trial 10 finished with value: 0.46301945288052276 and parameters: {'n_estimators': 268, 'max_depth': 5, 'learning_rate': 0.03023089392435322, 'subsample': 0.9742888060117842, 'colsample_bytree': 0.40073597364330305, 'min_child_weight': 5, 'gamma': 0.9576358604009154, 'reg_alpha': 9.052966263995141e-06, 'reg_lambda': 7.860572882253776}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58700
[200]	validation_0-rmse:0.47075
[204]	validation_0-rmse:0.47070
[0]	validation_0-rmse:0.60653
[200]	validation_0-rmse:0.47847
[204]	validation_0-rmse:0.47845
[0]	validation_0-rmse:0.60383
[200]	validation_0-rmse:0.44306
[204]	validation_0-rmse:0.44295

Best trial: 10. Best value: 0.463019:  24%|██▍       | 12/50 [46:22<25:29, 40.24s/it]

[I 2026-06-13 16:25:07,599] Trial 11 finished with value: 0.46401476498253663 and parameters: {'n_estimators': 205, 'max_depth': 5, 'learning_rate': 0.027714384439143425, 'subsample': 0.9895482844971181, 'colsample_bytree': 0.40463953704825734, 'min_child_weight': 5, 'gamma': 0.947644358960497, 'reg_alpha': 2.0756093042788608e-05, 'reg_lambda': 7.342813405745883}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58592
[200]	validation_0-rmse:0.47151
[205]	validation_0-rmse:0.47151
[0]	validation_0-rmse:0.60520
[200]	validation_0-rmse:0.47937
[205]	validation_0-rmse:0.47926
[0]	validation_0-rmse:0.60204
[200]	validation_0-rmse:0.44026
[205]	validation_0-rmse:0.44024

Best trial: 10. Best value: 0.463019:  26%|██▌       | 13/50 [46:31<19:08, 31.04s/it]

[I 2026-06-13 16:25:17,464] Trial 12 finished with value: 0.46352021891817946 and parameters: {'n_estimators': 206, 'max_depth': 5, 'learning_rate': 0.037579392099930366, 'subsample': 0.9916272221371264, 'colsample_bytree': 0.41418032824585344, 'min_child_weight': 5, 'gamma': 0.9769275704625893, 'reg_alpha': 9.647020738527246e-06, 'reg_lambda': 8.505695884066505}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58527
[200]	validation_0-rmse:0.47247
[207]	validation_0-rmse:0.47243
[0]	validation_0-rmse:0.60414
[200]	validation_0-rmse:0.47781
[207]	validation_0-rmse:0.47781
[0]	validation_0-rmse:0.60127
[200]	validation_0-rmse:0.44244
[207]	validation_0-rmse:0.44260

Best trial: 10. Best value: 0.463019:  28%|██▊       | 14/50 [46:41<14:48, 24.68s/it]

[I 2026-06-13 16:25:27,457] Trial 13 finished with value: 0.4639404031612517 and parameters: {'n_estimators': 208, 'max_depth': 5, 'learning_rate': 0.04073427739756223, 'subsample': 0.9979482416105043, 'colsample_bytree': 0.4132106112370803, 'min_child_weight': 5, 'gamma': 0.790627502636056, 'reg_alpha': 1.0208092910645763e-05, 'reg_lambda': 0.5287549212582002}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58520
[200]	validation_0-rmse:0.47423
[306]	validation_0-rmse:0.47483
[0]	validation_0-rmse:0.60367
[200]	validation_0-rmse:0.47695
[400]	validation_0-rmse:0.47658
[425]	validation_0-rmse:0.47665
[0]	validation_0-rmse:0.60017
[200]	validation_0-rmse:0.44245
[390]	validation_0-rmse:0.44484

Best trial: 10. Best value: 0.463019:  30%|███       | 15/50 [46:55<12:27, 21.35s/it]

[I 2026-06-13 16:25:41,099] Trial 14 finished with value: 0.46377825292457403 and parameters: {'n_estimators': 426, 'max_depth': 5, 'learning_rate': 0.04707428722732004, 'subsample': 0.9289562414986202, 'colsample_bytree': 0.5196823669759082, 'min_child_weight': 5, 'gamma': 0.9888720755336271, 'reg_alpha': 1.8799948266058237e-06, 'reg_lambda': 9.131131858855074}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58855
[200]	validation_0-rmse:0.47498
[400]	validation_0-rmse:0.47158
[600]	validation_0-rmse:0.47208
[620]	validation_0-rmse:0.47224
[0]	validation_0-rmse:0.60843
[200]	validation_0-rmse:0.48472
[400]	validation_0-rmse:0.47923
[600]	validation_0-rmse:0.47840
[800]	validation_0-rmse:0.47824
[936]	validation_0-rmse:0.47826
[0]	validation_0-rmse:0.60600
[200]	validation_0-rmse:0.45171
[400]	validation_0-rmse:0.44222
[600]	validation_0-rmse:0.44288
[691]	validation_0-rmse:0.44374

Best trial: 10. Best value: 0.463019:  32%|███▏      | 16/50 [47:26<13:43, 24.22s/it]

[I 2026-06-13 16:26:11,983] Trial 15 finished with value: 0.46374937113970677 and parameters: {'n_estimators': 937, 'max_depth': 6, 'learning_rate': 0.012814930690515211, 'subsample': 0.9505856310274072, 'colsample_bytree': 0.46776792416346646, 'min_child_weight': 7, 'gamma': 0.7234758069955727, 'reg_alpha': 0.00017082162537046834, 'reg_lambda': 0.15073712853394974}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58639
[200]	validation_0-rmse:0.47315
[400]	validation_0-rmse:0.47550
[405]	validation_0-rmse:0.47526
[0]	validation_0-rmse:0.60571
[200]	validation_0-rmse:0.47891
[400]	validation_0-rmse:0.47572
[405]	validation_0-rmse:0.47584
[0]	validation_0-rmse:0.60313
[200]	validation_0-rmse:0.44453
[400]	validation_0-rmse:0.44281
[405]	validation_0-rmse:0.44269

Best trial: 10. Best value: 0.463019:  34%|███▍      | 17/50 [47:41<11:50, 21.53s/it]

[I 2026-06-13 16:26:27,237] Trial 16 finished with value: 0.4635112769368797 and parameters: {'n_estimators': 406, 'max_depth': 4, 'learning_rate': 0.032726495180451155, 'subsample': 0.8568118211324517, 'colsample_bytree': 0.595871610017062, 'min_child_weight': 3, 'gamma': 0.8428954702255083, 'reg_alpha': 1.6278744461780158e-06, 'reg_lambda': 1.4768594586812338}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58034
[200]	validation_0-rmse:0.48348
[265]	validation_0-rmse:0.48758
[0]	validation_0-rmse:0.59830
[200]	validation_0-rmse:0.47937
[318]	validation_0-rmse:0.48139
[0]	validation_0-rmse:0.59463
[200]	validation_0-rmse:0.45244
[323]	validation_0-rmse:0.46240

Best trial: 10. Best value: 0.463019:  36%|███▌      | 18/50 [47:53<09:54, 18.58s/it]

[I 2026-06-13 16:26:38,974] Trial 17 finished with value: 0.4664582291923332 and parameters: {'n_estimators': 483, 'max_depth': 4, 'learning_rate': 0.0833118160025319, 'subsample': 0.8186045282160783, 'colsample_bytree': 0.6134854056692967, 'min_child_weight': 3, 'gamma': 0.6588741309369464, 'reg_alpha': 1.126636600863562e-08, 'reg_lambda': 0.038627680713996575}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58976
[200]	validation_0-rmse:0.51147
[400]	validation_0-rmse:0.48852
[600]	validation_0-rmse:0.47985
[800]	validation_0-rmse:0.47670
[938]	validation_0-rmse:0.47562
[0]	validation_0-rmse:0.61000
[200]	validation_0-rmse:0.52294
[400]	validation_0-rmse:0.49800
[600]	validation_0-rmse:0.48948
[800]	validation_0-rmse:0.48608
[938]	validation_0-rmse:0.48455
[0]	validation_0-rmse:0.60791
[200]	validation_0-rmse:0.50605
[400]	validation_0-rmse:0.47370
[600]	validation_0-rmse:0.46125
[800]	validation_0-rmse:0.45500
[938]	validation_0-rmse:0.45221

Best trial: 10. Best value: 0.463019:  38%|███▊      | 19/50 [48:20<10:57, 21.22s/it]

[I 2026-06-13 16:27:06,347] Trial 18 finished with value: 0.4707783214994618 and parameters: {'n_estimators': 939, 'max_depth': 3, 'learning_rate': 0.005146518939023304, 'subsample': 0.8907237463247298, 'colsample_bytree': 0.6043358651156072, 'min_child_weight': 3, 'gamma': 0.8480654291903034, 'reg_alpha': 1.2537063920458104e-06, 'reg_lambda': 0.003388876533460397}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58537
[200]	validation_0-rmse:0.47618
[366]	validation_0-rmse:0.48148
[0]	validation_0-rmse:0.60489
[200]	validation_0-rmse:0.48003
[400]	validation_0-rmse:0.48199
[428]	validation_0-rmse:0.48231
[0]	validation_0-rmse:0.60212
[200]	validation_0-rmse:0.44822
[395]	validation_0-rmse:0.45352

Best trial: 10. Best value: 0.463019:  40%|████      | 20/50 [48:40<10:23, 20.77s/it]

[I 2026-06-13 16:27:26,061] Trial 19 finished with value: 0.46758330926662195 and parameters: {'n_estimators': 429, 'max_depth': 6, 'learning_rate': 0.028118823594449303, 'subsample': 0.771672496127108, 'colsample_bytree': 0.6712438280509891, 'min_child_weight': 7, 'gamma': 0.6889039828026524, 'reg_alpha': 0.0003941928258194319, 'reg_lambda': 0.8091667015160509}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58873
[200]	validation_0-rmse:0.47725
[400]	validation_0-rmse:0.47331
[568]	validation_0-rmse:0.47376
[0]	validation_0-rmse:0.60851
[200]	validation_0-rmse:0.48740
[400]	validation_0-rmse:0.48057
[589]	validation_0-rmse:0.47785
[0]	validation_0-rmse:0.60630
[200]	validation_0-rmse:0.45850
[400]	validation_0-rmse:0.44828
[589]	validation_0-rmse:0.44488

Best trial: 10. Best value: 0.463019:  42%|████▏     | 21/50 [48:59<09:50, 20.36s/it]

[I 2026-06-13 16:27:45,463] Trial 20 finished with value: 0.46524121766692367 and parameters: {'n_estimators': 590, 'max_depth': 4, 'learning_rate': 0.013770544982620989, 'subsample': 0.7076078827216512, 'colsample_bytree': 0.562230412728791, 'min_child_weight': 2, 'gamma': 0.616989883547037, 'reg_alpha': 1.1092958297293647e-06, 'reg_lambda': 0.14667833152446175}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58619
[200]	validation_0-rmse:0.47140
[246]	validation_0-rmse:0.47137
[0]	validation_0-rmse:0.60535
[200]	validation_0-rmse:0.47791
[246]	validation_0-rmse:0.47665
[0]	validation_0-rmse:0.60254
[200]	validation_0-rmse:0.44191
[246]	validation_0-rmse:0.44222

Best trial: 10. Best value: 0.463019:  44%|████▍     | 22/50 [49:11<08:12, 17.59s/it]

[I 2026-06-13 16:27:56,581] Trial 21 finished with value: 0.4631530574908557 and parameters: {'n_estimators': 247, 'max_depth': 5, 'learning_rate': 0.03504800612411759, 'subsample': 0.9520272153207356, 'colsample_bytree': 0.4441086016452526, 'min_child_weight': 5, 'gamma': 0.8977502859281252, 'reg_alpha': 9.829538145180551e-06, 'reg_lambda': 9.037178556284493}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58284
[200]	validation_0-rmse:0.47571
[266]	validation_0-rmse:0.47606
[0]	validation_0-rmse:0.60115
[200]	validation_0-rmse:0.47751
[353]	validation_0-rmse:0.47807
[0]	validation_0-rmse:0.59716
[200]	validation_0-rmse:0.44439
[305]	validation_0-rmse:0.45109

Best trial: 10. Best value: 0.463019:  46%|████▌     | 23/50 [49:23<07:10, 15.93s/it]

[I 2026-06-13 16:28:08,663] Trial 22 finished with value: 0.4639302350662153 and parameters: {'n_estimators': 375, 'max_depth': 5, 'learning_rate': 0.06041533333037384, 'subsample': 0.9407414997008489, 'colsample_bytree': 0.468533593360545, 'min_child_weight': 4, 'gamma': 0.8528054460171522, 'reg_alpha': 3.550263294419561e-05, 'reg_lambda': 1.5607893861123636}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58651
[200]	validation_0-rmse:0.47537
[339]	validation_0-rmse:0.47815
[0]	validation_0-rmse:0.60562
[200]	validation_0-rmse:0.48058
[339]	validation_0-rmse:0.48071
[0]	validation_0-rmse:0.60259
[200]	validation_0-rmse:0.44527
[339]	validation_0-rmse:0.44773

Best trial: 10. Best value: 0.463019:  48%|████▊     | 24/50 [49:38<06:52, 15.86s/it]

[I 2026-06-13 16:28:24,342] Trial 23 finished with value: 0.46667562503073334 and parameters: {'n_estimators': 340, 'max_depth': 6, 'learning_rate': 0.030282955779161652, 'subsample': 0.8684475152501945, 'colsample_bytree': 0.4841663806699875, 'min_child_weight': 6, 'gamma': 0.9051039532992402, 'reg_alpha': 4.305825916700336e-06, 'reg_lambda': 2.280681528444465}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.57605
[200]	validation_0-rmse:0.48399
[237]	validation_0-rmse:0.48557
[0]	validation_0-rmse:0.59289
[200]	validation_0-rmse:0.48129
[305]	validation_0-rmse:0.48266
[0]	validation_0-rmse:0.58773
[200]	validation_0-rmse:0.46495
[258]	validation_0-rmse:0.46746

Best trial: 10. Best value: 0.463019:  50%|█████     | 25/50 [49:48<05:49, 14.00s/it]

[I 2026-06-13 16:28:33,996] Trial 24 finished with value: 0.4664314448978309 and parameters: {'n_estimators': 781, 'max_depth': 4, 'learning_rate': 0.12334429524828679, 'subsample': 0.9495338902966468, 'colsample_bytree': 0.5720053588080224, 'min_child_weight': 3, 'gamma': 0.7960961504733696, 'reg_alpha': 4.7513558318434176e-07, 'reg_lambda': 0.19310991160005206}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58591
[200]	validation_0-rmse:0.47286
[356]	validation_0-rmse:0.47463
[0]	validation_0-rmse:0.60508
[200]	validation_0-rmse:0.47869
[400]	validation_0-rmse:0.47740
[560]	validation_0-rmse:0.47785
[0]	validation_0-rmse:0.60210
[200]	validation_0-rmse:0.44314
[400]	validation_0-rmse:0.44564
[432]	validation_0-rmse:0.44620

Best trial: 10. Best value: 0.463019:  52%|█████▏    | 26/50 [50:04<05:52, 14.67s/it]

[I 2026-06-13 16:28:50,230] Trial 25 finished with value: 0.4637654216103049 and parameters: {'n_estimators': 561, 'max_depth': 5, 'learning_rate': 0.03384975348140355, 'subsample': 0.8137353505256127, 'colsample_bytree': 0.43553098113690314, 'min_child_weight': 7, 'gamma': 0.9986918787319805, 'reg_alpha': 1.9125050920837737e-08, 'reg_lambda': 0.04901157404527904}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58713
[200]	validation_0-rmse:0.47559
[305]	validation_0-rmse:0.47609
[0]	validation_0-rmse:0.60674
[200]	validation_0-rmse:0.48150
[305]	validation_0-rmse:0.48137
[0]	validation_0-rmse:0.60386
[200]	validation_0-rmse:0.44708
[305]	validation_0-rmse:0.44833

Best trial: 10. Best value: 0.463019:  54%|█████▍    | 27/50 [50:24<06:11, 16.14s/it]

[I 2026-06-13 16:29:09,814] Trial 26 finished with value: 0.46786158097016245 and parameters: {'n_estimators': 306, 'max_depth': 8, 'learning_rate': 0.022826047645338774, 'subsample': 0.9069035993887089, 'colsample_bytree': 0.5321545696720615, 'min_child_weight': 9, 'gamma': 0.8237503435539892, 'reg_alpha': 0.0005176785161542291, 'reg_lambda': 2.4224025478354605}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58865
[200]	validation_0-rmse:0.47748
[400]	validation_0-rmse:0.47253
[600]	validation_0-rmse:0.47305
[639]	validation_0-rmse:0.47324
[0]	validation_0-rmse:0.60843
[200]	validation_0-rmse:0.48526
[400]	validation_0-rmse:0.47977
[600]	validation_0-rmse:0.47710
[800]	validation_0-rmse:0.47615
[858]	validation_0-rmse:0.47611
[0]	validation_0-rmse:0.60610
[200]	validation_0-rmse:0.45458
[400]	validation_0-rmse:0.44378
[600]	validation_0-rmse:0.44155
[766]	validation_0-rmse:0.44241

Best trial: 10. Best value: 0.463019:  56%|█████▌    | 28/50 [50:46<06:37, 18.08s/it]

[I 2026-06-13 16:29:32,425] Trial 27 finished with value: 0.46307658879706476 and parameters: {'n_estimators': 859, 'max_depth': 4, 'learning_rate': 0.01523339761370321, 'subsample': 0.9571330732956677, 'colsample_bytree': 0.4513706057664139, 'min_child_weight': 4, 'gamma': 0.9150899573432086, 'reg_alpha': 5.691031789629787e-05, 'reg_lambda': 0.33227760126778577}. Best is trial 10 with value: 0.46301945288052276.
[0]	validation_0-rmse:0.58892
[200]	validation_0-rmse:0.48189
[400]	validation_0-rmse:0.47397
[600]	validation_0-rmse:0.47246
[800]	validation_0-rmse:0.47248
[925]	validation_0-rmse:0.47282
[0]	validation_0-rmse:0.60884
[200]	validation_0-rmse:0.49065
[400]	validation_0-rmse:0.48225
[600]	validation_0-rmse:0.47891
[800]	validation_0-rmse:0.47687
[1000]	validation_0-rmse:0.47568
[1200]	validation_0-rmse:0.47524
[1400]	validation_0-rmse:0.47514
[1600]	validation_0-rmse:0.47514
[1634]	validation_0-rmse:0.47514
[0]	validation_0-rmse:0.60646
[200]	validation_0-rmse:0.46251
[400]	validation_0-rmse:0.44799
[600]	validation_0-rmse:0.44310
[800]	validation_0-rmse:0.44118
[1000]	validation_0-rmse:0.44081
[1177]	validation_0-rmse:0.44109

Best trial: 28. Best value: 0.462607:  58%|█████▊    | 29/50 [51:16<07:33, 21.58s/it]

[I 2026-06-13 16:30:02,162] Trial 28 finished with value: 0.46260731461123844 and parameters: {'n_estimators': 1941, 'max_depth': 3, 'learning_rate': 0.01436408993532436, 'subsample': 0.9747064106791504, 'colsample_bytree': 0.4532900805007842, 'min_child_weight': 6, 'gamma': 0.9142919312795572, 'reg_alpha': 7.056048422798025e-05, 'reg_lambda': 0.004275681268576378}. Best is trial 28 with value: 0.46260731461123844.
[0]	validation_0-rmse:0.58881
[200]	validation_0-rmse:0.48129
[400]	validation_0-rmse:0.47390
[600]	validation_0-rmse:0.47340
[800]	validation_0-rmse:0.47313
[980]	validation_0-rmse:0.47340
[0]	validation_0-rmse:0.60883
[200]	validation_0-rmse:0.49037
[400]	validation_0-rmse:0.48276
[600]	validation_0-rmse:0.47964
[800]	validation_0-rmse:0.47770
[1000]	validation_0-rmse:0.47650
[1200]	validation_0-rmse:0.47622
[1400]	validation_0-rmse:0.47608
[1600]	validation_0-rmse:0.47600
[1800]	validation_0-rmse:0.47574
[1958]	validation_0-rmse:0.47568
[0]	validation_0-rmse:0.60654
[200]	validation_0-rmse:0.46227
[400]	validation_0-rmse:0.44828
[600]	validation_0-rmse:0.44363
[800]	validation_0-rmse:0.44153
[1000]	validation_0-rmse:0.44140
[1127]	validation_0-rmse:0.44160

Best trial: 28. Best value: 0.462607:  60%|██████    | 30/50 [51:50<08:25, 25.27s/it]

[I 2026-06-13 16:30:36,059] Trial 29 finished with value: 0.4631890079880346 and parameters: {'n_estimators': 1959, 'max_depth': 3, 'learning_rate': 0.014513408008826577, 'subsample': 0.9090630285591699, 'colsample_bytree': 0.5103414406239587, 'min_child_weight': 6, 'gamma': 0.9115125156326296, 'reg_alpha': 0.011567917975946801, 'reg_lambda': 0.0002105975906360864}. Best is trial 28 with value: 0.46260731461123844.
[0]	validation_0-rmse:0.58868
[200]	validation_0-rmse:0.47943
[400]	validation_0-rmse:0.47311
[600]	validation_0-rmse:0.47175
[800]	validation_0-rmse:0.47173
[930]	validation_0-rmse:0.47177
[0]	validation_0-rmse:0.60857
[200]	validation_0-rmse:0.48828
[400]	validation_0-rmse:0.48094
[600]	validation_0-rmse:0.47791
[800]	validation_0-rmse:0.47620
[1000]	validation_0-rmse:0.47518
[1200]	validation_0-rmse:0.47495
[1218]	validation_0-rmse:0.47494
[0]	validation_0-rmse:0.60613
[200]	validation_0-rmse:0.45832
[400]	validation_0-rmse:0.44583
[600]	validation_0-rmse:0.44128
[800]	validation_0-rmse:0.43958
[1000]	validation_0-rmse:0.43899
[1200]	validation_0-rmse:0.43883
[1218]	validation_0-rmse:0.43887

Best trial: 30. Best value: 0.461736:  62%|██████▏   | 31/50 [52:18<08:15, 26.10s/it]

[I 2026-06-13 16:31:04,100] Trial 30 finished with value: 0.46173577628959334 and parameters: {'n_estimators': 1219, 'max_depth': 3, 'learning_rate': 0.016545562093751534, 'subsample': 0.9777030555768058, 'colsample_bytree': 0.4507074373363352, 'min_child_weight': 9, 'gamma': 0.7626123309789703, 'reg_alpha': 5.8967365238741696e-05, 'reg_lambda': 0.004056596211651745}. Best is trial 30 with value: 0.46173577628959334.
[0]	validation_0-rmse:0.58925
[200]	validation_0-rmse:0.48968
[400]	validation_0-rmse:0.47668
[600]	validation_0-rmse:0.47383
[800]	validation_0-rmse:0.47257
[1000]	validation_0-rmse:0.47220
[1200]	validation_0-rmse:0.47203
[1241]	validation_0-rmse:0.47211
[0]	validation_0-rmse:0.60934
[200]	validation_0-rmse:0.49800
[400]	validation_0-rmse:0.48526
[600]	validation_0-rmse:0.48144
[800]	validation_0-rmse:0.47916
[1000]	validation_0-rmse:0.47748
[1200]	validation_0-rmse:0.47602
[1241]	validation_0-rmse:0.47582
[0]	validation_0-rmse:0.60715
[200]	validation_0-rmse:0.47315
[400]	validation_0-rmse:0.45333
[600]	validation_0-rmse:0.44651
[800]	validation_0-rmse:0.44301
[1000]	validation_0-rmse:0.44085
[1200]	validation_0-rmse:0.44018
[1241]	validation_0-rmse:0.44016

Best trial: 30. Best value: 0.461736:  64%|██████▍   | 32/50 [52:49<08:15, 27.51s/it]

[I 2026-06-13 16:31:34,903] Trial 31 finished with value: 0.4626410608746287 and parameters: {'n_estimators': 1242, 'max_depth': 3, 'learning_rate': 0.010586397787783258, 'subsample': 0.9716273651444571, 'colsample_bytree': 0.46225856848124625, 'min_child_weight': 10, 'gamma': 0.7666526064372234, 'reg_alpha': 8.858712057028428e-05, 'reg_lambda': 0.0038887772793419597}. Best is trial 30 with value: 0.46173577628959334.
[0]	validation_0-rmse:0.58925
[200]	validation_0-rmse:0.48956
[400]	validation_0-rmse:0.47663
[600]	validation_0-rmse:0.47374
[800]	validation_0-rmse:0.47271
[1000]	validation_0-rmse:0.47247
[1200]	validation_0-rmse:0.47238
[1217]	validation_0-rmse:0.47239
[0]	validation_0-rmse:0.60935
[200]	validation_0-rmse:0.49782
[400]	validation_0-rmse:0.48536
[600]	validation_0-rmse:0.48147
[800]	validation_0-rmse:0.47914
[1000]	validation_0-rmse:0.47744
[1200]	validation_0-rmse:0.47603
[1217]	validation_0-rmse:0.47596
[0]	validation_0-rmse:0.60715
[200]	validation_0-rmse:0.47283
[400]	validation_0-rmse:0.45327
[600]	validation_0-rmse:0.44647
[800]	validation_0-rmse:0.44315
[1000]	validation_0-rmse:0.44108
[1200]	validation_0-rmse:0.44032
[1217]	validation_0-rmse:0.44030

Best trial: 30. Best value: 0.461736:  66%|██████▌   | 33/50 [53:19<08:02, 28.41s/it]

[I 2026-06-13 16:32:05,402] Trial 32 finished with value: 0.4628435996366398 and parameters: {'n_estimators': 1218, 'max_depth': 3, 'learning_rate': 0.0105895856431747, 'subsample': 0.9746285857238923, 'colsample_bytree': 0.49921897665818993, 'min_child_weight': 10, 'gamma': 0.6111180695064686, 'reg_alpha': 0.00018741890675812221, 'reg_lambda': 0.005811573277009018}. Best is trial 30 with value: 0.46173577628959334.
[0]	validation_0-rmse:0.58913
[200]	validation_0-rmse:0.48781
[400]	validation_0-rmse:0.47569
[600]	validation_0-rmse:0.47360
[800]	validation_0-rmse:0.47313
[1000]	validation_0-rmse:0.47313
[1013]	validation_0-rmse:0.47311
[0]	validation_0-rmse:0.60927
[200]	validation_0-rmse:0.49620
[400]	validation_0-rmse:0.48485
[600]	validation_0-rmse:0.48122
[800]	validation_0-rmse:0.47923
[1000]	validation_0-rmse:0.47788
[1200]	validation_0-rmse:0.47701
[1213]	validation_0-rmse:0.47698
[0]	validation_0-rmse:0.60701
[200]	validation_0-rmse:0.47062
[400]	validation_0-rmse:0.45241
[600]	validation_0-rmse:0.44624
[800]	validation_0-rmse:0.44335
[1000]	validation_0-rmse:0.44134
[1200]	validation_0-rmse:0.44018
[1213]	validation_0-rmse:0.44017

Best trial: 30. Best value: 0.461736:  68%|██████▊   | 34/50 [53:49<07:39, 28.72s/it]

[I 2026-06-13 16:32:34,832] Trial 33 finished with value: 0.4633736179698846 and parameters: {'n_estimators': 1214, 'max_depth': 3, 'learning_rate': 0.011176427137014385, 'subsample': 0.9171352914840727, 'colsample_bytree': 0.5224267802208145, 'min_child_weight': 11, 'gamma': 0.6118295217273937, 'reg_alpha': 0.0008050839713721134, 'reg_lambda': 0.0037168765140891398}. Best is trial 30 with value: 0.46173577628959334.
[0]	validation_0-rmse:0.58947
[200]	validation_0-rmse:0.49667
[400]	validation_0-rmse:0.47953
[600]	validation_0-rmse:0.47500
[800]	validation_0-rmse:0.47331
[1000]	validation_0-rmse:0.47266
[1200]	validation_0-rmse:0.47247
[1313]	validation_0-rmse:0.47252
[0]	validation_0-rmse:0.60962
[200]	validation_0-rmse:0.50546
[400]	validation_0-rmse:0.48840
[600]	validation_0-rmse:0.48358
[800]	validation_0-rmse:0.48081
[1000]	validation_0-rmse:0.47903
[1200]	validation_0-rmse:0.47760
[1313]	validation_0-rmse:0.47689
[0]	validation_0-rmse:0.60747
[200]	validation_0-rmse:0.48296
[400]	validation_0-rmse:0.45869
[600]	validation_0-rmse:0.45008
[800]	validation_0-rmse:0.44642
[1000]	validation_0-rmse:0.44368
[1200]	validation_0-rmse:0.44187
[1313]	validation_0-rmse:0.44146

Best trial: 30. Best value: 0.461736:  70%|███████   | 35/50 [54:22<07:28, 29.91s/it]

[I 2026-06-13 16:33:07,526] Trial 34 finished with value: 0.46357746792018 and parameters: {'n_estimators': 1314, 'max_depth': 3, 'learning_rate': 0.008386531248699125, 'subsample': 0.9762795162032928, 'colsample_bytree': 0.49390646179397246, 'min_child_weight': 10, 'gamma': 0.3672611806088033, 'reg_alpha': 0.00013829908841267615, 'reg_lambda': 0.0006878930718195823}. Best is trial 30 with value: 0.46173577628959334.
[0]	validation_0-rmse:0.58919
[200]	validation_0-rmse:0.48860
[400]	validation_0-rmse:0.47581
[600]	validation_0-rmse:0.47412
[800]	validation_0-rmse:0.47329
[1000]	validation_0-rmse:0.47300
[1200]	validation_0-rmse:0.47285
[1400]	validation_0-rmse:0.47278
[1432]	validation_0-rmse:0.47283
[0]	validation_0-rmse:0.60935
[200]	validation_0-rmse:0.49729
[400]	validation_0-rmse:0.48528
[600]	validation_0-rmse:0.48181
[800]	validation_0-rmse:0.47998
[1000]	validation_0-rmse:0.47844
[1200]	validation_0-rmse:0.47739
[1400]	validation_0-rmse:0.47678
[1432]	validation_0-rmse:0.47661
[0]	validation_0-rmse:0.60713
[200]	validation_0-rmse:0.47200
[400]	validation_0-rmse:0.45344
[600]	validation_0-rmse:0.44732
[800]	validation_0-rmse:0.44392
[1000]	validation_0-rmse:0.44182
[1200]	validation_0-rmse:0.44047
[1400]	validation_0-rmse:0.44053
[1432]	validation_0-rmse:0.44052

Best trial: 30. Best value: 0.461736:  72%|███████▏  | 36/50 [54:57<07:22, 31.64s/it]

[I 2026-06-13 16:33:43,209] Trial 35 finished with value: 0.4631810763743663 and parameters: {'n_estimators': 1433, 'max_depth': 3, 'learning_rate': 0.01062512954890816, 'subsample': 0.8908135956270175, 'colsample_bytree': 0.5575295223855932, 'min_child_weight': 12, 'gamma': 0.7582109499789171, 'reg_alpha': 0.002006393312672543, 'reg_lambda': 0.01056446635113806}. Best is trial 30 with value: 0.46173577628959334.
[0]	validation_0-rmse:0.58960
[200]	validation_0-rmse:0.50501
[400]	validation_0-rmse:0.48428
[600]	validation_0-rmse:0.47747
[800]	validation_0-rmse:0.47531
[1000]	validation_0-rmse:0.47406
[1123]	validation_0-rmse:0.47363
[0]	validation_0-rmse:0.60984
[200]	validation_0-rmse:0.51529
[400]	validation_0-rmse:0.49304
[600]	validation_0-rmse:0.48639
[800]	validation_0-rmse:0.48344
[1000]	validation_0-rmse:0.48127
[1123]	validation_0-rmse:0.48044
[0]	validation_0-rmse:0.60769
[200]	validation_0-rmse:0.49481
[400]	validation_0-rmse:0.46554
[600]	validation_0-rmse:0.45453
[800]	validation_0-rmse:0.44940
[1000]	validation_0-rmse:0.44638
[1123]	validation_0-rmse:0.44485

Best trial: 30. Best value: 0.461736:  74%|███████▍  | 37/50 [55:26<06:40, 30.78s/it]

[I 2026-06-13 16:34:11,987] Trial 36 finished with value: 0.4662968232486067 and parameters: {'n_estimators': 1124, 'max_depth': 3, 'learning_rate': 0.006624331431190191, 'subsample': 0.9992585615428751, 'colsample_bytree': 0.4891518055379865, 'min_child_weight': 9, 'gamma': 0.600803013351453, 'reg_alpha': 0.015905099785698686, 'reg_lambda': 0.0009964757812860679}. Best is trial 30 with value: 0.46173577628959334.
[0]	validation_0-rmse:0.58843
[200]	validation_0-rmse:0.47489
[400]	validation_0-rmse:0.46883
[600]	validation_0-rmse:0.46808
[800]	validation_0-rmse:0.46794
[1000]	validation_0-rmse:0.46795
[1092]	validation_0-rmse:0.46797
[0]	validation_0-rmse:0.60827
[200]	validation_0-rmse:0.48506
[400]	validation_0-rmse:0.47832
[600]	validation_0-rmse:0.47605
[800]	validation_0-rmse:0.47568
[1000]	validation_0-rmse:0.47555
[1200]	validation_0-rmse:0.47553
[1377]	validation_0-rmse:0.47558
[0]	validation_0-rmse:0.60571
[200]	validation_0-rmse:0.45063
[400]	validation_0-rmse:0.43942
[600]	validation_0-rmse:0.43638
[800]	validation_0-rmse:0.43605
[1000]	validation_0-rmse:0.43590
[1200]	validation_0-rmse:0.43564
[1400]	validation_0-rmse:0.43554
[1600]	validation_0-rmse:0.43555
[1608]	validation_0-rmse:0.43555

Best trial: 37. Best value: 0.459661:  76%|███████▌  | 38/50 [55:57<06:11, 30.93s/it]

[I 2026-06-13 16:34:43,273] Trial 37 finished with value: 0.4596612782468972 and parameters: {'n_estimators': 1669, 'max_depth': 4, 'learning_rate': 0.018207360826567247, 'subsample': 0.9660296827625481, 'colsample_bytree': 0.45211670022866246, 'min_child_weight': 14, 'gamma': 0.6751829893073908, 'reg_alpha': 7.601669381793715, 'reg_lambda': 8.253838798164384e-05}. Best is trial 37 with value: 0.4596612782468972.
[0]	validation_0-rmse:0.58847
[200]	validation_0-rmse:0.47617
[400]	validation_0-rmse:0.47038
[600]	validation_0-rmse:0.46989
[680]	validation_0-rmse:0.47010
[0]	validation_0-rmse:0.60840
[200]	validation_0-rmse:0.48552
[400]	validation_0-rmse:0.47928
[600]	validation_0-rmse:0.47682
[800]	validation_0-rmse:0.47533
[1000]	validation_0-rmse:0.47524
[1200]	validation_0-rmse:0.47505
[1400]	validation_0-rmse:0.47503
[1600]	validation_0-rmse:0.47499
[1800]	validation_0-rmse:0.47494
[1915]	validation_0-rmse:0.47495
[0]	validation_0-rmse:0.60603
[200]	validation_0-rmse:0.45378
[400]	validation_0-rmse:0.44311
[600]	validation_0-rmse:0.44004
[800]	validation_0-rmse:0.43929
[1000]	validation_0-rmse:0.43915
[1173]	validation_0-rmse:0.43929

Best trial: 37. Best value: 0.459661:  78%|███████▊  | 39/50 [56:30<05:45, 31.38s/it]

[I 2026-06-13 16:35:15,684] Trial 38 finished with value: 0.46126207592459423 and parameters: {'n_estimators': 1916, 'max_depth': 4, 'learning_rate': 0.015954125787517738, 'subsample': 0.9319214862477623, 'colsample_bytree': 0.4411101077600971, 'min_child_weight': 15, 'gamma': 0.69553747546598, 'reg_alpha': 2.271397655079786, 'reg_lambda': 6.2370703723001525e-06}. Best is trial 37 with value: 0.4596612782468972.
[0]	validation_0-rmse:0.58855
[200]	validation_0-rmse:0.47641
[400]	validation_0-rmse:0.46947
[600]	validation_0-rmse:0.46845
[800]	validation_0-rmse:0.46809
[1000]	validation_0-rmse:0.46792
[1200]	validation_0-rmse:0.46780
[1375]	validation_0-rmse:0.46788
[0]	validation_0-rmse:0.60839
[200]	validation_0-rmse:0.48697
[400]	validation_0-rmse:0.47985
[600]	validation_0-rmse:0.47741
[800]	validation_0-rmse:0.47628
[1000]	validation_0-rmse:0.47588
[1200]	validation_0-rmse:0.47585
[1400]	validation_0-rmse:0.47570
[1590]	validation_0-rmse:0.47575
[0]	validation_0-rmse:0.60580
[200]	validation_0-rmse:0.45293
[400]	validation_0-rmse:0.44077
[600]	validation_0-rmse:0.43700
[800]	validation_0-rmse:0.43574
[1000]	validation_0-rmse:0.43546
[1200]	validation_0-rmse:0.43548
[1225]	validation_0-rmse:0.43538

Best trial: 39. Best value: 0.459611:  80%|████████  | 40/50 [57:04<05:22, 32.28s/it]

[I 2026-06-13 16:35:50,063] Trial 39 finished with value: 0.4596111821260566 and parameters: {'n_estimators': 1985, 'max_depth': 4, 'learning_rate': 0.01753249565904956, 'subsample': 0.8813610567113981, 'colsample_bytree': 0.4296737040472227, 'min_child_weight': 15, 'gamma': 0.5364303927125997, 'reg_alpha': 9.357733047533824, 'reg_lambda': 1.0907494668815432e-05}. Best is trial 39 with value: 0.4596111821260566.
[0]	validation_0-rmse:0.58850
[200]	validation_0-rmse:0.47520
[400]	validation_0-rmse:0.46882
[600]	validation_0-rmse:0.46785
[800]	validation_0-rmse:0.46766
[909]	validation_0-rmse:0.46776
[0]	validation_0-rmse:0.60833
[200]	validation_0-rmse:0.48600
[400]	validation_0-rmse:0.47930
[600]	validation_0-rmse:0.47700
[800]	validation_0-rmse:0.47601
[1000]	validation_0-rmse:0.47546
[1200]	validation_0-rmse:0.47519
[1400]	validation_0-rmse:0.47509
[1494]	validation_0-rmse:0.47510
[0]	validation_0-rmse:0.60568
[200]	validation_0-rmse:0.45229
[400]	validation_0-rmse:0.44064
[600]	validation_0-rmse:0.43673
[800]	validation_0-rmse:0.43594
[1000]	validation_0-rmse:0.43586
[1200]	validation_0-rmse:0.43586
[1322]	validation_0-rmse:0.43582

Best trial: 40. Best value: 0.45942:  82%|████████▏ | 41/50 [57:43<05:07, 34.17s/it]

[I 2026-06-13 16:36:28,651] Trial 40 finished with value: 0.45942012428149087 and parameters: {'n_estimators': 1798, 'max_depth': 4, 'learning_rate': 0.017967835910497824, 'subsample': 0.8372254280887725, 'colsample_bytree': 0.43008443005229, 'min_child_weight': 15, 'gamma': 0.4406240081385506, 'reg_alpha': 9.09248720327136, 'reg_lambda': 3.7689845929035388e-06}. Best is trial 40 with value: 0.45942012428149087.
[0]	validation_0-rmse:0.58847
[200]	validation_0-rmse:0.47576
[400]	validation_0-rmse:0.46934
[600]	validation_0-rmse:0.46864
[800]	validation_0-rmse:0.46845
[880]	validation_0-rmse:0.46851
[0]	validation_0-rmse:0.60830
[200]	validation_0-rmse:0.48541
[400]	validation_0-rmse:0.47854
[600]	validation_0-rmse:0.47637
[800]	validation_0-rmse:0.47534
[1000]	validation_0-rmse:0.47517
[1200]	validation_0-rmse:0.47518
[1341]	validation_0-rmse:0.47521
[0]	validation_0-rmse:0.60569
[200]	validation_0-rmse:0.45151
[400]	validation_0-rmse:0.43974
[600]	validation_0-rmse:0.43641
[800]	validation_0-rmse:0.43537
[1000]	validation_0-rmse:0.43524
[1135]	validation_0-rmse:0.43535

Best trial: 40. Best value: 0.45942:  84%|████████▍ | 42/50 [58:19<04:37, 34.70s/it]

[I 2026-06-13 16:37:04,573] Trial 41 finished with value: 0.4595094797152814 and parameters: {'n_estimators': 1793, 'max_depth': 4, 'learning_rate': 0.01809550647037045, 'subsample': 0.8327488877251407, 'colsample_bytree': 0.42226475230713356, 'min_child_weight': 15, 'gamma': 0.4051295765928448, 'reg_alpha': 7.548938457326822, 'reg_lambda': 3.598068199031937e-06}. Best is trial 40 with value: 0.45942012428149087.
[0]	validation_0-rmse:0.58782
[200]	validation_0-rmse:0.47186
[400]	validation_0-rmse:0.46762
[600]	validation_0-rmse:0.46751
[773]	validation_0-rmse:0.46794
[0]	validation_0-rmse:0.60757
[200]	validation_0-rmse:0.48181
[400]	validation_0-rmse:0.47674
[600]	validation_0-rmse:0.47507
[800]	validation_0-rmse:0.47470
[930]	validation_0-rmse:0.47482
[0]	validation_0-rmse:0.60486
[200]	validation_0-rmse:0.44611
[400]	validation_0-rmse:0.43738
[600]	validation_0-rmse:0.43565
[800]	validation_0-rmse:0.43615
[837]	validation_0-rmse:0.43621

Best trial: 42. Best value: 0.459209:  86%|████████▌ | 43/50 [58:47<03:49, 32.76s/it]

[I 2026-06-13 16:37:32,801] Trial 42 finished with value: 0.4592087820773397 and parameters: {'n_estimators': 1821, 'max_depth': 4, 'learning_rate': 0.02314105620216985, 'subsample': 0.8074175189516672, 'colsample_bytree': 0.42742090916152475, 'min_child_weight': 15, 'gamma': 0.4357164831273537, 'reg_alpha': 6.532528949599308, 'reg_lambda': 3.0521332595540163e-06}. Best is trial 42 with value: 0.4592087820773397.
[0]	validation_0-rmse:0.58791
[200]	validation_0-rmse:0.47269
[400]	validation_0-rmse:0.46823
[600]	validation_0-rmse:0.46762
[754]	validation_0-rmse:0.46814
[0]	validation_0-rmse:0.60766
[200]	validation_0-rmse:0.48321
[400]	validation_0-rmse:0.47798
[600]	validation_0-rmse:0.47618
[800]	validation_0-rmse:0.47597
[1000]	validation_0-rmse:0.47592
[1200]	validation_0-rmse:0.47567
[1267]	validation_0-rmse:0.47574
[0]	validation_0-rmse:0.60501
[200]	validation_0-rmse:0.44714
[400]	validation_0-rmse:0.43812
[600]	validation_0-rmse:0.43616
[800]	validation_0-rmse:0.43594
[1000]	validation_0-rmse:0.43619
[1055]	validation_0-rmse:0.43621

Best trial: 42. Best value: 0.459209:  88%|████████▊ | 44/50 [59:16<03:09, 31.66s/it]

[I 2026-06-13 16:38:01,917] Trial 43 finished with value: 0.45961006595128334 and parameters: {'n_estimators': 1733, 'max_depth': 4, 'learning_rate': 0.022893901340338554, 'subsample': 0.7697335596157601, 'colsample_bytree': 0.4307985475936392, 'min_child_weight': 14, 'gamma': 0.37902415684176544, 'reg_alpha': 9.580800664367763, 'reg_lambda': 2.2574047841088405e-06}. Best is trial 42 with value: 0.4592087820773397.
[0]	validation_0-rmse:0.58757
[200]	validation_0-rmse:0.47229
[400]	validation_0-rmse:0.47122
[501]	validation_0-rmse:0.47170
[0]	validation_0-rmse:0.60744
[200]	validation_0-rmse:0.48042
[400]	validation_0-rmse:0.47714
[600]	validation_0-rmse:0.47582
[800]	validation_0-rmse:0.47617
[808]	validation_0-rmse:0.47611
[0]	validation_0-rmse:0.60465
[200]	validation_0-rmse:0.44628
[400]	validation_0-rmse:0.43983
[600]	validation_0-rmse:0.43976
[677]	validation_0-rmse:0.44074

Best trial: 42. Best value: 0.459209:  90%|█████████ | 45/50 [59:37<02:22, 28.42s/it]

[I 2026-06-13 16:38:22,752] Trial 44 finished with value: 0.4620473802869931 and parameters: {'n_estimators': 1826, 'max_depth': 4, 'learning_rate': 0.02361137190795795, 'subsample': 0.7735047785766962, 'colsample_bytree': 0.4166287021705602, 'min_child_weight': 14, 'gamma': 0.3934338115637855, 'reg_alpha': 0.4495028521923381, 'reg_lambda': 2.011369055892172e-06}. Best is trial 42 with value: 0.4592087820773397.
[0]	validation_0-rmse:0.58793
[200]	validation_0-rmse:0.47237
[400]	validation_0-rmse:0.46838
[600]	validation_0-rmse:0.46831
[696]	validation_0-rmse:0.46860
[0]	validation_0-rmse:0.60761
[200]	validation_0-rmse:0.48333
[400]	validation_0-rmse:0.47842
[600]	validation_0-rmse:0.47668
[800]	validation_0-rmse:0.47658
[1000]	validation_0-rmse:0.47667
[1034]	validation_0-rmse:0.47661
[0]	validation_0-rmse:0.60486
[200]	validation_0-rmse:0.44693
[400]	validation_0-rmse:0.43764
[600]	validation_0-rmse:0.43524
[800]	validation_0-rmse:0.43532
[828]	validation_0-rmse:0.43538

Best trial: 42. Best value: 0.459209:  92%|█████████▏| 46/50 [1:00:02<01:49, 27.35s/it]

[I 2026-06-13 16:38:47,618] Trial 45 finished with value: 0.4598602097118271 and parameters: {'n_estimators': 1615, 'max_depth': 4, 'learning_rate': 0.02347818533899894, 'subsample': 0.8256655085591355, 'colsample_bytree': 0.40372600564570776, 'min_child_weight': 14, 'gamma': 0.27491244395353326, 'reg_alpha': 9.523733349967419, 'reg_lambda': 3.74975164326987e-08}. Best is trial 42 with value: 0.4592087820773397.
[0]	validation_0-rmse:0.58722
[200]	validation_0-rmse:0.47424
[400]	validation_0-rmse:0.47208
[600]	validation_0-rmse:0.47166
[718]	validation_0-rmse:0.47269
[0]	validation_0-rmse:0.60745
[200]	validation_0-rmse:0.48485
[400]	validation_0-rmse:0.47923
[600]	validation_0-rmse:0.47685
[800]	validation_0-rmse:0.47620
[1000]	validation_0-rmse:0.47678
[1050]	validation_0-rmse:0.47698
[0]	validation_0-rmse:0.60499
[200]	validation_0-rmse:0.45221
[400]	validation_0-rmse:0.44383
[600]	validation_0-rmse:0.44175
[786]	validation_0-rmse:0.44243

Best trial: 42. Best value: 0.459209:  94%|█████████▍| 47/50 [1:00:30<01:22, 27.55s/it]

[I 2026-06-13 16:39:15,650] Trial 46 finished with value: 0.46303541543033 and parameters: {'n_estimators': 1794, 'max_depth': 4, 'learning_rate': 0.018170187370289442, 'subsample': 0.7476785331602464, 'colsample_bytree': 0.7967625625436783, 'min_child_weight': 13, 'gamma': 0.4388352111749589, 'reg_alpha': 1.4489136563495653, 'reg_lambda': 6.160700344536788e-07}. Best is trial 42 with value: 0.4592087820773397.
[0]	validation_0-rmse:0.58789
[200]	validation_0-rmse:0.47218
[400]	validation_0-rmse:0.47039
[561]	validation_0-rmse:0.47068
[0]	validation_0-rmse:0.60785
[200]	validation_0-rmse:0.48171
[400]	validation_0-rmse:0.47761
[600]	validation_0-rmse:0.47672
[800]	validation_0-rmse:0.47639
[916]	validation_0-rmse:0.47692
[0]	validation_0-rmse:0.60539
[200]	validation_0-rmse:0.44930
[400]	validation_0-rmse:0.44195
[600]	validation_0-rmse:0.44102
[708]	validation_0-rmse:0.44203

Best trial: 42. Best value: 0.459209:  96%|█████████▌| 48/50 [1:00:52<00:52, 26.11s/it]

[I 2026-06-13 16:39:38,376] Trial 47 finished with value: 0.46239888560499137 and parameters: {'n_estimators': 1586, 'max_depth': 4, 'learning_rate': 0.02027042721641669, 'subsample': 0.6787368282961312, 'colsample_bytree': 0.43556525124800516, 'min_child_weight': 15, 'gamma': 0.5137138277868026, 'reg_alpha': 0.34799603893031356, 'reg_lambda': 1.501232747323586e-05}. Best is trial 42 with value: 0.4592087820773397.
[0]	validation_0-rmse:0.58722
[200]	validation_0-rmse:0.46932
[400]	validation_0-rmse:0.46792
[515]	validation_0-rmse:0.46894
[0]	validation_0-rmse:0.60685
[200]	validation_0-rmse:0.47873
[400]	validation_0-rmse:0.47522
[600]	validation_0-rmse:0.47557
[695]	validation_0-rmse:0.47576
[0]	validation_0-rmse:0.60388
[200]	validation_0-rmse:0.44196
[400]	validation_0-rmse:0.43731
[600]	validation_0-rmse:0.43776
[650]	validation_0-rmse:0.43808

Best trial: 42. Best value: 0.459209:  98%|█████████▊| 49/50 [1:01:17<00:25, 25.74s/it]

[I 2026-06-13 16:40:03,265] Trial 48 finished with value: 0.4598911953242247 and parameters: {'n_estimators': 1850, 'max_depth': 5, 'learning_rate': 0.02537715207560886, 'subsample': 0.8377213422818547, 'colsample_bytree': 0.42250117943863125, 'min_child_weight': 13, 'gamma': 0.28206555416911105, 'reg_alpha': 4.054932942550896, 'reg_lambda': 1.782999599220166e-06}. Best is trial 42 with value: 0.4592087820773397.
[0]	validation_0-rmse:0.58795
[200]	validation_0-rmse:0.47304
[400]	validation_0-rmse:0.47201
[600]	validation_0-rmse:0.47195
[719]	validation_0-rmse:0.47202
[0]	validation_0-rmse:0.60755
[200]	validation_0-rmse:0.48213
[400]	validation_0-rmse:0.47741
[600]	validation_0-rmse:0.47594
[800]	validation_0-rmse:0.47585
[914]	validation_0-rmse:0.47603
[0]	validation_0-rmse:0.60528
[200]	validation_0-rmse:0.44845
[400]	validation_0-rmse:0.44199
[600]	validation_0-rmse:0.44086
[800]	validation_0-rmse:0.44165
[845]	validation_0-rmse:0.44178

Best trial: 42. Best value: 0.459209: 100%|██████████| 50/50 [1:01:48<00:00, 74.17s/it]

[I 2026-06-13 16:40:34,205] Trial 49 finished with value: 0.4625099734000248 and parameters: {'n_estimators': 1728, 'max_depth': 4, 'learning_rate': 0.020588669753349394, 'subsample': 0.8755339132146279, 'colsample_bytree': 0.5380321042970182, 'min_child_weight': 14, 'gamma': 0.4324811370829304, 'reg_alpha': 0.6107979881213862, 'reg_lambda': 1.388696782170521e-07}. Best is trial 42 with value: 0.4592087820773397.

In [5]:
train_df = pd.read_csv('../data/train_test/holdout/train_full.csv', index_col='id', parse_dates=['timestamp'])
test_df = pd.read_csv('../data/train_test/holdout/holdout.csv', index_col='id', parse_dates=['timestamp'])
time_folds = get_time_folds()
with open("../data/features/features_100.json", "r", encoding="utf-8") as f:
    selected_features = json.load(f)

C:\Users\sokol\AppData\Local\Temp\ipykernel_23332\3628407794.py:1: DtypeWarning: Columns (0: old_education_build_share, 1: provision_doctors) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv('../data/train_test/holdout/train_full.csv', index_col='id', parse_dates=['timestamp'])
C:\Users\sokol\AppData\Local\Temp\ipykernel_23332\3628407794.py:2: DtypeWarning: Columns (0: load_of_teachers_school_per_teacher) have mixed types. Specify dtype option on import or set low_memory=False.
  test_df = pd.read_csv('../data/train_test/holdout/holdout.csv', index_col='id', parse_dates=['timestamp'])

In [10]:
model = XGBRegressor(**best_params_xgb,
                    eval_metric =  "rmse",
                    tree_method = "hist",
                    objective = 'reg:squarederror',
                    enable_categorical = True,
                    early_stopping_rounds = 200,
                    random_state = 42,
                    n_jobs = -1,)

xgboost_quality, oof_pred_xgb, xgb_models, features_import_xgb, xgb_features = run_boosting_cv(
    train_df=train_df,
    time_folds=time_folds,
    split_fold=split_fold,
    model_factory=model,
    model_name="xgboost_100_tuned",
    booster="xgboost",
    preprocessing_func=prep_with_features_eng,
    selected_features=selected_features,
    )

[0]	validation_0-rmse:0.58782
[200]	validation_0-rmse:0.47186
[400]	validation_0-rmse:0.46762
[600]	validation_0-rmse:0.46751
[773]	validation_0-rmse:0.46794
[0]	validation_0-rmse:0.60757
[200]	validation_0-rmse:0.48181
[400]	validation_0-rmse:0.47674
[600]	validation_0-rmse:0.47507
[800]	validation_0-rmse:0.47470
[930]	validation_0-rmse:0.47482
[0]	validation_0-rmse:0.60486
[200]	validation_0-rmse:0.44611
[400]	validation_0-rmse:0.43738
[600]	validation_0-rmse:0.43565
[800]	validation_0-rmse:0.43615
[837]	validation_0-rmse:0.43621

In [12]:
model = LGBMRegressor(**best_params_lgb,
                    objective = 'regression',
                    min_child_samples = 20,
                    random_state = 42,
                    n_jobs = -1,
                    verbose = -1)

lightgbm_quality, oof_pred_lightgbm, lightgbm_models, features_import_light, lgb_features = run_boosting_cv(
    train_df=train_df,
    time_folds=time_folds,
    split_fold=split_fold,
    model_factory=model,
    model_name="lightgbm_100_tuned",
    booster="lightgbm",
    preprocessing_func=prep_with_features_eng,
    selected_features=selected_features,
    )

Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.484025	valid_0's l2: 0.23428
[400]	valid_0's rmse: 0.47418	valid_0's l2: 0.224847
[600]	valid_0's rmse: 0.472548	valid_0's l2: 0.223302
[800]	valid_0's rmse: 0.471476	valid_0's l2: 0.22229
[1000]	valid_0's rmse: 0.471392	valid_0's l2: 0.22221
Early stopping, best iteration is:
[911]	valid_0's rmse: 0.471153	valid_0's l2: 0.221986
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.492512	valid_0's l2: 0.242568
[400]	valid_0's rmse: 0.482636	valid_0's l2: 0.232938
[600]	valid_0's rmse: 0.479231	valid_0's l2: 0.229662
[800]	valid_0's rmse: 0.476985	valid_0's l2: 0.227515
[1000]	valid_0's rmse: 0.475494	valid_0's l2: 0.226094
[1200]	valid_0's rmse: 0.474998	valid_0's l2: 0.225623
[1400]	valid_0's rmse: 0.474796	valid_0's l2: 0.225431
Did not meet early stopping. Best iteration is:
[1563]	valid_0's rmse: 0.47467	valid_0's l2: 0.225312
Training until validation scores don't improve for 200 rounds
[200]	valid_0's rmse: 0.464423	valid_0's l2: 0.215689
[400]	valid_0's rmse: 0.448425	valid_0's l2: 0.201085
[600]	valid_0's rmse: 0.442946	valid_0's l2: 0.196201
[800]	valid_0's rmse: 0.440338	valid_0's l2: 0.193897
[1000]	valid_0's rmse: 0.43963	valid_0's l2: 0.193275
[1200]	valid_0's rmse: 0.439051	valid_0's l2: 0.192766
[1400]	valid_0's rmse: 0.438806	valid_0's l2: 0.192551
Did not meet early stopping. Best iteration is:
[1579]	valid_0's rmse: 0.43838	valid_0's l2: 0.192177

In [14]:
model = CatBoostRegressor(**best_params_cat,
                        early_stopping_rounds = 200,
                        eval_metric = "RMSE",
                        loss_function = 'RMSE',
                        random_seed = 42,
                        verbose = 200)

cat_quality, oof_pred_cat, cat_models, features_import_cat, cat_features = run_boosting_cv(
        train_df=train_df,
        time_folds=time_folds,
        split_fold=split_fold,
        model_factory=model,
        model_name="catboost_100_tuned",
        booster="catboost",
        preprocessing_func=prep_with_features_eng,
        selected_features=selected_features,
    )

0:	learn: 0.6104409	test: 0.5879778	best: 0.5879778 (0)	total: 137ms	remaining: 2m 59s
200:	learn: 0.4827012	test: 0.4754434	best: 0.4754434 (200)	total: 20.5s	remaining: 1m 53s
400:	learn: 0.4510455	test: 0.4674385	best: 0.4674385 (400)	total: 41.6s	remaining: 1m 34s
600:	learn: 0.4242737	test: 0.4653667	best: 0.4653667 (600)	total: 1m 1s	remaining: 1m 12s
800:	learn: 0.3933273	test: 0.4647084	best: 0.4647084 (800)	total: 1m 21s	remaining: 51.8s
1000:	learn: 0.3624206	test: 0.4650116	best: 0.4645466 (947)	total: 1m 40s	remaining: 31.3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.4645465529
bestIteration = 947

Shrink model to first 948 iterations.
0:	learn: 0.6020638	test: 0.6084658	best: 0.6084658 (0)	total: 179ms	remaining: 3m 54s
200:	learn: 0.4796614	test: 0.4887677	best: 0.4887677 (200)	total: 20.6s	remaining: 1m 54s
400:	learn: 0.4552183	test: 0.4795923	best: 0.4795923 (400)	total: 41.2s	remaining: 1m 33s
600:	learn: 0.4371234	test: 0.4761328	best: 0.4761328 (600)	total: 1m 1s	remaining: 1m 12s
800:	learn: 0.4150885	test: 0.4747067	best: 0.4746986 (787)	total: 1m 22s	remaining: 52.4s
1000:	learn: 0.3930144	test: 0.4745631	best: 0.4744090 (960)	total: 1m 42s	remaining: 31.8s
1200:	learn: 0.3717092	test: 0.4747768	best: 0.4742778 (1061)	total: 2m 2s	remaining: 11.3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.474277781
bestIteration = 1061

Shrink model to first 1062 iterations.
0:	learn: 0.6027308	test: 0.6059722	best: 0.6059722 (0)	total: 177ms	remaining: 3m 52s
200:	learn: 0.4798698	test: 0.4565481	best: 0.4565481 (200)	total: 20.8s	remaining: 1m 55s
400:	learn: 0.4596089	test: 0.4432662	best: 0.4432662 (400)	total: 41.5s	remaining: 1m 34s
600:	learn: 0.4447848	test: 0.4390330	best: 0.4390330 (600)	total: 1m 1s	remaining: 1m 13s
800:	learn: 0.4287121	test: 0.4364457	best: 0.4364457 (800)	total: 1m 22s	remaining: 52.7s
1000:	learn: 0.4093871	test: 0.4354338	best: 0.4353942 (987)	total: 1m 43s	remaining: 32s
1200:	learn: 0.3911895	test: 0.4360027	best: 0.4353730 (1037)	total: 2m 3s	remaining: 11.4s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.4353729943
bestIteration = 1037

Shrink model to first 1038 iterations.

In [18]:
journal_quality = pd.read_csv('../data/journals/models_quality.csv')
journal_quality = pd.concat([journal_quality, xgboost_quality, lightgbm_quality, cat_quality])
journal_quality.sort_values('mean_rmsle').drop(['Unnamed: 0.1', 'Unnamed: 0'] , axis=1)

,model_name,fold_1,fold_2,fold_3,mean_rmsle,rmsle_std
0,catboost_100_tuned,0.464547,0.474639,0.435373,0.458186,0.020391
10,catboost_feature_set_4_100,0.464042,0.474308,0.436642,0.458331,0.019472
9,catboost_feature_set_3_150,0.465633,0.474431,0.435585,0.458550,0.020368
8,catboost_feature_set_2_200,0.466029,0.476668,0.434861,0.459186,0.021727
0,xgboost_100_tuned,0.467434,0.474607,0.435586,0.459209,0.020770
3,catboost_eng,0.466676,0.475195,0.436673,0.459514,0.020235
7,catboost_feature_set_1_250,0.465576,0.477364,0.437078,0.460006,0.020712
6,catboost_feature_set_0_300,0.466059,0.475702,0.439242,0.460334,0.018892
0,lightgbm_100_tuned,0.471153,0.474670,0.438380,0.461401,0.020014
0,catboost_baseline,0.469224,0.477262,0.439019,0.461835,0.020164
15,lightgbm_feature_set_4_100,0.475325,0.480109,0.445949,0.467128,0.018497
4,lightgbm_eng,0.475595,0.482197,0.444557,0.467450,0.020099
14,lightgbm_feature_set_3_150,0.474275,0.483879,0.444778,0.467644,0.020376
12,lightgbm_feature_set_1_250,0.475364,0.481824,0.445756,0.467648,0.019232
11,lightgbm_feature_set_0_300,0.475619,0.483207,0.444582,0.467803,0.020465
13,lightgbm_feature_set_2_200,0.475977,0.482522,0.445855,0.468118,0.019556
1,lightgbm_baseline,0.474571,0.484132,0.446759,0.468487,0.019415
20,xgboost_feature_set_4_100,0.480532,0.480349,0.448662,0.469848,0.018348
19,xgboost_feature_set_3_150,0.480055,0.486229,0.452197,0.472827,0.018130
18,xgboost_feature_set_2_200,0.480081,0.486958,0.452052,0.473030,0.018490
17,xgboost_feature_set_1_250,0.481422,0.485829,0.452636,0.473296,0.018027
16,xgboost_feature_set_0_300,0.481879,0.490196,0.450918,0.474331,0.020698
5,xgboost_eng,0.481180,0.487939,0.455003,0.474707,0.017396
2,xgboost_baseline,0.482901,0.491692,0.455477,0.476690,0.018889

In [6]:
X_train = prep_with_features_eng(train_df)
cat_categories = fit_cat_categories(X_train)
X_test = prep_with_features_eng(test_df, cat_categories=cat_categories)
y_train, y_test = X_train['price_doc'], X_test['price_doc']
X_train, X_test = X_train[selected_features], X_test[selected_features]

In [22]:
model_xgb = XGBRegressor(**best_params_xgb,
                    eval_metric =  "rmse",
                    tree_method = "hist",
                    objective = 'reg:squarederror',
                    enable_categorical = True,
                    random_state = 42,
                    n_jobs = -1,)
model_xgb.fit(X_train,
              y_train,
              verbose=200)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.42742090916152475, device=None,
             early_stopping_rounds=None, enable_categorical=True,
             eval_metric='rmse', feature_types=None, feature_weights=None,
             gamma=0.4357164831273537, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.02314105620216985,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=4, max_leaves=None,
             min_child_weight=15, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1821, n_jobs=-1,
             num_parallel_tree=None, ...)

In [32]:
xgb_pred_log = model_xgb.predict(X_test)
xgb_pred = np.expm1(xgb_pred_log)

score_xgb = rmsle(np.expm1(y_test), xgb_pred)
score_xgb

np.float64(0.40783964329591044)

In [24]:
cat_features = X_train.select_dtypes(
            include="category"
            ).columns.to_list()

model_cat = CatBoostRegressor(**best_params_cat,
                        eval_metric = "RMSE",
                        loss_function = 'RMSE',
                        random_seed = 42,
                        verbose = 200)

model_cat.fit(X_train,
            y_train,
            cat_features=cat_features,
            use_best_model=True)

You should provide test set for use best model. use_best_model parameter has been switched to false value.

0:	learn: 0.6030013	total: 199ms	remaining: 4m 21s
200:	learn: 0.4735970	total: 24.2s	remaining: 2m 13s
400:	learn: 0.4558999	total: 47.9s	remaining: 1m 48s
600:	learn: 0.4428760	total: 1m 11s	remaining: 1m 24s
800:	learn: 0.4289288	total: 1m 35s	remaining: 1m 1s
1000:	learn: 0.4132130	total: 1m 59s	remaining: 37.1s
1200:	learn: 0.3979429	total: 2m 23s	remaining: 13.2s
1311:	learn: 0.3898307	total: 2m 36s	remaining: 0us

CatBoostRegressor(bagging_temperature=0.5708563287223052, border_count=233, depth=8, eval_metric='RMSE', iterations=1312, l2_leaf_reg=3.455501005045953e-06, learning_rate=0.015017092532527218, loss_function='RMSE', random_seed=42, random_strength=3.4893013333133185, verbose=200)

In [33]:
cat_pred_log = model_cat.predict(X_test)
cat_pred = np.expm1(cat_pred_log)

score_cat = rmsle(np.expm1(y_test), cat_pred)
score_cat

np.float64(0.40745072608227706)

In [26]:
model_lgb = LGBMRegressor(**best_params_lgb,
                    objective = 'regression',
                    min_child_samples = 20,
                    random_state = 42,
                    n_jobs = -1,
                    verbose = 200)

model_lgb.fit(X_train,
              y_train,
              eval_metric="rmse",
              categorical_feature=cat_features)

[LightGBM] [Debug] Dataset::GetMultiBinFromSparseFeatures: sparse rate 0.822706
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.074941
[LightGBM] [Debug] init for col-wise cost 0.002541 seconds, init for row-wise cost 0.013957 seconds
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016158 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 20039
[LightGBM] [Info] Number of data points in the train set: 25438, number of used features: 100
[LightGBM] [Info] Start training from score 15.585158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 8 and depth = 3
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMRegressor(colsample_bytree=0.40153594539246124,
              learning_rate=0.014624076339413969, max_depth=3,
              min_child_weight=1, min_split_gain=0.364877203684999,
              n_estimators=1580, n_jobs=-1, num_leaves=19,
              objective='regression', random_state=42,
              reg_alpha=3.743259100901015e-07,
              reg_lambda=3.4602628028485467e-06, subsample=0.9678262105904213,
              verbose=200)

In [34]:
lgb_pred_log = model_lgb.predict(X_test)
lgb_pred = np.expm1(lgb_pred_log)

score_lgb = rmsle(np.expm1(y_test), lgb_pred)
score_lgb

np.float64(0.4112224611232791)

In [43]:
oof_pred_xgb = oof_pred_xgb.reset_index(drop=True)
oof_pred_lightgbm = oof_pred_lightgbm.reset_index(drop=True)
oof_pred_cat = oof_pred_cat.reset_index(drop=True)


pred_journal = oof_pred_xgb.merge(
        oof_pred_lightgbm[["id", "fold", "val_block", "lightgbm_100_tuned_pred", "lightgbm_100_tuned_error"]],
        on=["id", "fold", "val_block"],
        how="left"
        ).merge(
        oof_pred_cat[["id", "fold", "val_block", "catboost_100_tuned_pred", "catboost_100_tuned_error"]],
        on=["id", "fold", "val_block"],
        how="left"
        )
pred_journal

,id,fold,val_block,y_true,xgboost_100_tuned_pred,xgboost_100_tuned_error,lightgbm_100_tuned_pred,lightgbm_100_tuned_error,catboost_100_tuned_pred,catboost_100_tuned_error
0,10165,1,B3,8552548.0,8127559.50,-424988.50,8.071173e+06,-4.813754e+05,8.233219e+06,-3.193292e+05
1,10166,1,B3,11400000.0,9097011.00,-2302989.00,8.907268e+06,-2.492732e+06,9.716959e+06,-1.683041e+06
2,10167,1,B3,14021000.0,19285576.00,5264576.00,1.628893e+07,2.267930e+06,1.844919e+07,4.428188e+06
3,10168,1,B3,5395417.0,5266733.50,-128683.50,5.189082e+06,-2.063349e+05,5.323641e+06,-7.177640e+04
4,10169,1,B3,4462000.0,4108963.25,-353036.75,4.105858e+06,-3.561421e+05,4.189419e+06,-2.725806e+05
...,...,...,...,...,...,...,...,...,...,...
15273,25440,3,B5,4082035.0,3923343.50,-158691.50,3.788801e+06,-2.932343e+05,4.092554e+06,1.051950e+04
15274,25441,3,B5,3827681.0,4067790.50,240109.50,4.075600e+06,2.479190e+05,4.034544e+06,2.068632e+05
15275,25442,3,B5,7250000.0,5521263.50,-1728736.50,5.514738e+06,-1.735262e+06,4.262188e+06,-2.987812e+06
15276,25443,3,B5,8550000.0,6915198.00,-1634802.00,7.157160e+06,-1.392840e+06,7.528870e+06,-1.021130e+06
15277,25444,3,B5,4816350.0,4220420.00,-595930.00,4.399533e+06,-4.168172e+05,4.060205e+06,-7.561453e+05

In [44]:
stack_df = pred_journal[['catboost_100_tuned_pred', 'xgboost_100_tuned_pred', 'lightgbm_100_tuned_pred', 'y_true']]

In [ ]:
from sklearn.linear_model import RidgeCV

pred_cols = ['catboost_100_tuned_pred', 'xgboost_100_tuned_pred', 'lightgbm_100_tuned_pred']

X_meta = np.log1p(stack_df[pred_cols])
y_meta = np.log1p(stack_df["y_true"])

RidgeCV(alphas=[0.01, 0.1, 1.0, 10.0, 100.0])

In [56]:
def alpha_objective(trial):
    meta_model = RidgeCV(
        alphas=trial.suggest_float("alpha", 1e-8, 1e5, log=True)
    )

    meta_model.fit(X_meta, y_meta)
    holdout_stack = pd.DataFrame({'y_true': y_test, 'catboost_100_tuned_pred': cat_pred_log, 'xgboost_100_tuned_pred': xgb_pred_log, 'lightgbm_100_tuned_pred': lgb_pred_log})
    X_meta_test = holdout_stack[pred_cols]
    y_meta_test = holdout_stack["y_true"]

    stack_pred_log = meta_model.predict(X_meta_test)
    stack_pred = np.expm1(stack_pred_log)

    ridge_stack_score = rmsle(
        np.expm1(y_meta_test),
        stack_pred
    )

    return ridge_stack_score

In [ ]:
study_ridge = optuna.create_study(direction='minimize',
        sampler=optuna.samplers.TPESampler(seed=456))
study_ridge.optimize(alpha_objective, n_trials=500, show_progress_bar=True)

[I 2026-06-14 00:48:32,639] A new study created in memory with name: no-name-c5728530-1a9d-4027-879a-de1a0cbbaba6
Best trial: 1. Best value: 0.403745:   0%|          | 9/5000 [00:00<01:55, 43.07it/s]

[I 2026-06-14 00:48:32,663] Trial 0 finished with value: 0.4037454058723199 and parameters: {'alpha': 1.7132739897317752e-05}. Best is trial 0 with value: 0.4037454058723199.
[I 2026-06-14 00:48:32,689] Trial 1 finished with value: 0.40374539989537966 and parameters: {'alpha': 1.3178566773858449e-06}. Best is trial 1 with value: 0.40374539989537966.
[I 2026-06-14 00:48:32,725] Trial 2 finished with value: 0.4041867626806314 and parameters: {'alpha': 153.94384278814903}. Best is trial 1 with value: 0.40374539989537966.
[I 2026-06-14 00:48:32,748] Trial 3 finished with value: 0.40472391891844506 and parameters: {'alpha': 324.1933147506116}. Best is trial 1 with value: 0.40374539989537966.
[I 2026-06-14 00:48:32,774] Trial 4 finished with value: 0.4037466129246403 and parameters: {'alpha': 1.3588438767860131}. Best is trial 1 with value: 0.40374539989537966.
[I 2026-06-14 00:48:32,796] Trial 5 finished with value: 0.4037459671946611 and parameters: {'alpha': 0.7136367925031899}. Best is trial 1 with value: 0.40374539989537966.
[I 2026-06-14 00:48:32,812] Trial 6 finished with value: 0.4310755787944497 and parameters: {'alpha': 3266.816500317378}. Best is trial 1 with value: 0.40374539989537966.
[I 2026-06-14 00:48:32,837] Trial 7 finished with value: 0.4039685174907399 and parameters: {'alpha': 73.88003318273499}. Best is trial 1 with value: 0.40374539989537966.
[I 2026-06-14 00:48:32,854] Trial 8 finished with value: 0.4037454022857137 and parameters: {'alpha': 2.261339296855368e-06}. Best is trial 1 with value: 0.40374539989537966.

Best trial: 14. Best value: 0.403744:   0%|          | 18/5000 [00:00<01:52, 44.38it/s]

[I 2026-06-14 00:48:32,874] Trial 9 finished with value: 0.40374539854469726 and parameters: {'alpha': 8.957794804165514e-07}. Best is trial 9 with value: 0.40374539854469726.
[I 2026-06-14 00:48:32,897] Trial 10 finished with value: 0.40374540717282975 and parameters: {'alpha': 0.0009974366936248145}. Best is trial 9 with value: 0.40374539854469726.
[I 2026-06-14 00:48:32,920] Trial 11 finished with value: 0.40374474882312456 and parameters: {'alpha': 1.4677758782016897e-08}. Best is trial 11 with value: 0.40374474882312456.
[I 2026-06-14 00:48:32,940] Trial 12 finished with value: 0.40374461152300983 and parameters: {'alpha': 1.1341346455389126e-08}. Best is trial 12 with value: 0.40374461152300983.
[I 2026-06-14 00:48:32,963] Trial 13 finished with value: 0.4037448960679729 and parameters: {'alpha': 1.650074601613777e-08}. Best is trial 12 with value: 0.40374461152300983.
[I 2026-06-14 00:48:32,984] Trial 14 finished with value: 0.40374448277676533 and parameters: {'alpha': 1.0132046539761005e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,003] Trial 15 finished with value: 0.40374540662188674 and parameters: {'alpha': 0.0002182003923279994}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,022] Trial 16 finished with value: 0.4037452662152023 and parameters: {'alpha': 4.7032840497893944e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,040] Trial 17 finished with value: 0.4037454088696764 and parameters: {'alpha': 0.003530754304931379}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,060] Trial 18 finished with value: 0.4037452909447612 and parameters: {'alpha': 8.55874963620182e-08}. Best is trial 14 with value: 0.40374448277676533.

Best trial: 14. Best value: 0.403744:   1%|          | 29/5000 [00:00<01:41, 49.04it/s]

[I 2026-06-14 00:48:33,077] Trial 19 finished with value: 0.4037454061523273 and parameters: {'alpha': 2.9880616600260025e-05}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,097] Trial 20 finished with value: 0.4037453753792712 and parameters: {'alpha': 3.6691832448119234e-07}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,116] Trial 21 finished with value: 0.4037450059031943 and parameters: {'alpha': 2.1616012949235986e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,137] Trial 22 finished with value: 0.403744597301388 and parameters: {'alpha': 1.0247714159695309e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,156] Trial 23 finished with value: 0.403745404531089 and parameters: {'alpha': 4.437844190455998e-06}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,175] Trial 24 finished with value: 0.4037453667958331 and parameters: {'alpha': 2.431147711428858e-07}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,194] Trial 25 finished with value: 0.40374458926353823 and parameters: {'alpha': 1.155453383269039e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,213] Trial 26 finished with value: 0.40374536219966395 and parameters: {'alpha': 2.4837973770154297e-07}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,233] Trial 27 finished with value: 0.40374540633842776 and parameters: {'alpha': 3.529599516418042e-05}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,252] Trial 28 finished with value: 0.4037454217863546 and parameters: {'alpha': 0.022766825748805935}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,272] Trial 29 finished with value: 0.40374540527436703 and parameters: {'alpha': 5.58511833553637e-06}. Best is trial 14 with value: 0.40374448277676533.

[I 2026-06-14 00:48:33,292] Trial 30 finished with value: 0.4037453515365079 and parameters: {'alpha': 1.397370361447517e-07}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,312] Trial 31 finished with value: 0.40374470558327064 and parameters: {'alpha': 1.530071597139786e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,333] Trial 32 finished with value: 0.40374539285671107 and parameters: {'alpha': 6.44038566419952e-07}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,354] Trial 33 finished with value: 0.40374455747237104 and parameters: {'alpha': 1.047325022265651e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,373] Trial 34 finished with value: 0.40374531572462397 and parameters: {'alpha': 8.054353047975692e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,392] Trial 35 finished with value: 0.40374540548330723 and parameters: {'alpha': 7.64637478490776e-06}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,413] Trial 36 finished with value: 0.403745397048265 and parameters: {'alpha': 8.557942638176522e-07}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,435] Trial 37 finished with value: 0.4037453235976114 and parameters: {'alpha': 1.0882661368948018e-07}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,455] Trial 38 finished with value: 0.5627071606722717 and parameters: {'alpha': 59053.29186071767}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,473] Trial 39 finished with value: 0.40374540649283924 and parameters: {'alpha': 0.00010763875908427901}. Best is trial 14 with value: 0.40374448277676533.

Best trial: 45. Best value: 0.403744:   1%|          | 49/5000 [00:01<01:40, 49.30it/s]

[I 2026-06-14 00:48:33,494] Trial 40 finished with value: 0.4037454005627953 and parameters: {'alpha': 1.5577723221239977e-06}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,515] Trial 41 finished with value: 0.4037446320690152 and parameters: {'alpha': 1.2933915525323497e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,538] Trial 42 finished with value: 0.40374528674585486 and parameters: {'alpha': 5.32437001692061e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,558] Trial 43 finished with value: 0.40374456375431556 and parameters: {'alpha': 1.0337253406750338e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,578] Trial 44 finished with value: 0.40374531659611146 and parameters: {'alpha': 5.9365928256177016e-08}. Best is trial 14 with value: 0.40374448277676533.
[I 2026-06-14 00:48:33,597] Trial 45 finished with value: 0.4037443722108452 and parameters: {'alpha': 1.0250128476019141e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,617] Trial 46 finished with value: 0.4037453906752498 and parameters: {'alpha': 5.101582288912184e-07}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,640] Trial 47 finished with value: 0.40374526917418024 and parameters: {'alpha': 4.4512548318315357e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,662] Trial 48 finished with value: 0.40374533809989077 and parameters: {'alpha': 1.4675272963795537e-07}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,681] Trial 49 finished with value: 0.40374540353993305 and parameters: {'alpha': 2.721484534994148e-06}. Best is trial 45 with value: 0.4037443722108452.

Best trial: 45. Best value: 0.403744:   1%|          | 60/5000 [00:01<01:39, 49.75it/s]

[I 2026-06-14 00:48:33,703] Trial 50 finished with value: 0.40380067953781 and parameters: {'alpha': 21.66538612327267}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,723] Trial 51 finished with value: 0.4037447765991722 and parameters: {'alpha': 1.5887212779300054e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,743] Trial 52 finished with value: 0.4037446652625066 and parameters: {'alpha': 1.1153251375863037e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,765] Trial 53 finished with value: 0.40374521010537334 and parameters: {'alpha': 3.7011856133895065e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,783] Trial 54 finished with value: 0.4037453760141122 and parameters: {'alpha': 3.1408631041666973e-07}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,803] Trial 55 finished with value: 0.40374446748468673 and parameters: {'alpha': 1.054351086066625e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,821] Trial 56 finished with value: 0.4037451527993659 and parameters: {'alpha': 3.494838346635761e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,840] Trial 57 finished with value: 0.40374539877918336 and parameters: {'alpha': 1.100941769998208e-06}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,859] Trial 58 finished with value: 0.40374534449047406 and parameters: {'alpha': 1.475771000186572e-07}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,878] Trial 59 finished with value: 0.40374503729343353 and parameters: {'alpha': 2.4965258156785962e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,898] Trial 60 finished with value: 0.40374456278898885 and parameters: {'alpha': 1.0213216528406039e-08}. Best is trial 45 with value: 0.4037443722108452.

Best trial: 45. Best value: 0.403744:   1%|▏         | 70/5000 [00:01<01:40, 49.23it/s]

[I 2026-06-14 00:48:33,919] Trial 61 finished with value: 0.4037447377826138 and parameters: {'alpha': 1.046581543237985e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,939] Trial 62 finished with value: 0.4037452826321209 and parameters: {'alpha': 5.0099250739887665e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,961] Trial 63 finished with value: 0.4037453744626804 and parameters: {'alpha': 2.830430355243731e-07}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:33,982] Trial 64 finished with value: 0.40374531304390077 and parameters: {'alpha': 9.298983111965036e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:34,005] Trial 65 finished with value: 0.4037451926534048 and parameters: {'alpha': 3.73942504938556e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:34,024] Trial 66 finished with value: 0.4037449808925411 and parameters: {'alpha': 2.2806489970037285e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:34,043] Trial 67 finished with value: 0.40374536142751877 and parameters: {'alpha': 2.0936802045377005e-07}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:34,066] Trial 68 finished with value: 0.4037453958473712 and parameters: {'alpha': 8.070549704593019e-07}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:34,088] Trial 69 finished with value: 0.4037453243173717 and parameters: {'alpha': 9.775931713910915e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:34,106] Trial 70 finished with value: 0.4037446410487699 and parameters: {'alpha': 1.0002075257501475e-08}. Best is trial 45 with value: 0.4037443722108452.

Best trial: 72. Best value: 0.403744:   2%|▏         | 80/5000 [00:01<01:41, 48.55it/s]

[I 2026-06-14 00:48:34,126] Trial 71 finished with value: 0.4037449903000168 and parameters: {'alpha': 2.5716291598272298e-08}. Best is trial 45 with value: 0.4037443722108452.
[I 2026-06-14 00:48:34,147] Trial 72 finished with value: 0.403744353228764 and parameters: {'alpha': 1.0205345333612556e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,170] Trial 73 finished with value: 0.4037450662633028 and parameters: {'alpha': 2.5155850683539924e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,191] Trial 74 finished with value: 0.4037452881774133 and parameters: {'alpha': 7.999588543762093e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,211] Trial 75 finished with value: 0.40374535767321956 and parameters: {'alpha': 2.4144555540995776e-07}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,231] Trial 76 finished with value: 0.4037453897530194 and parameters: {'alpha': 5.14367986133646e-07}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,252] Trial 77 finished with value: 0.403744563187175 and parameters: {'alpha': 1.0368968405945579e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,273] Trial 78 finished with value: 0.40374507236502744 and parameters: {'alpha': 2.870460596647458e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,291] Trial 79 finished with value: 0.40374529372978246 and parameters: {'alpha': 7.901016352146142e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,311] Trial 80 finished with value: 0.4037454797172572 and parameters: {'alpha': 0.10685730170279456}. Best is trial 72 with value: 0.403744353228764.

[I 2026-06-14 00:48:34,331] Trial 81 finished with value: 0.40374454036276675 and parameters: {'alpha': 1.0129002878821847e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,351] Trial 82 finished with value: 0.40374494955455675 and parameters: {'alpha': 2.190990653413151e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,372] Trial 83 finished with value: 0.40374529759496525 and parameters: {'alpha': 5.2131269561935245e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,392] Trial 84 finished with value: 0.4037447542766865 and parameters: {'alpha': 1.2641117434245946e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,412] Trial 85 finished with value: 0.4037453583044891 and parameters: {'alpha': 1.6904548248134375e-07}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,432] Trial 86 finished with value: 0.4037452592007585 and parameters: {'alpha': 5.009398448282451e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,451] Trial 87 finished with value: 0.4037443879197519 and parameters: {'alpha': 1.0056716008338021e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,472] Trial 88 finished with value: 0.4037449813885935 and parameters: {'alpha': 2.270007986716518e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,492] Trial 89 finished with value: 0.40374537833598945 and parameters: {'alpha': 3.9046703730216066e-07}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,513] Trial 90 finished with value: 0.4037453281613598 and parameters: {'alpha': 1.1199932908562371e-07}. Best is trial 72 with value: 0.403744353228764.

[I 2026-06-14 00:48:34,533] Trial 91 finished with value: 0.4037447208222627 and parameters: {'alpha': 1.1719366624630957e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,553] Trial 92 finished with value: 0.4037450394605376 and parameters: {'alpha': 2.0368356976096378e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,572] Trial 93 finished with value: 0.40374529911680235 and parameters: {'alpha': 4.214757162478543e-08}. Best is trial 72 with value: 0.403744353228764.
[I 2026-06-14 00:48:34,595] Trial 94 finished with value: 0.4037443194743698 and parameters: {'alpha': 1.0604551983785416e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,614] Trial 95 finished with value: 0.40374531729549185 and parameters: {'alpha': 7.924393657397877e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,633] Trial 96 finished with value: 0.40374497616507743 and parameters: {'alpha': 2.0013581489998444e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,654] Trial 97 finished with value: 0.40374536474508865 and parameters: {'alpha': 1.6441480032040733e-07}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,675] Trial 98 finished with value: 0.4037454027435978 and parameters: {'alpha': 2.393933338589146e-06}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,696] Trial 99 finished with value: 0.40374443964773077 and parameters: {'alpha': 1.0377993232943963e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,715] Trial 100 finished with value: 0.40374522053517115 and parameters: {'alpha': 3.60651554627594e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,735] Trial 101 finished with value: 0.40374472504238035 and parameters: {'alpha': 1.0685047959780247e-08}. Best is trial 94 with value: 0.4037443194743698.

Best trial: 94. Best value: 0.403744:   2%|▏         | 112/5000 [00:02<01:37, 50.20it/s]

[I 2026-06-14 00:48:34,755] Trial 102 finished with value: 0.40374501188643463 and parameters: {'alpha': 1.933853113503265e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,775] Trial 103 finished with value: 0.4037453220849105 and parameters: {'alpha': 5.669439638381685e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,794] Trial 104 finished with value: 0.4037451552534228 and parameters: {'alpha': 3.233838186613999e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,815] Trial 105 finished with value: 0.40374468878445674 and parameters: {'alpha': 1.0178409602345145e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,835] Trial 106 finished with value: 0.40374531686436244 and parameters: {'alpha': 1.2097356240743688e-07}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,854] Trial 107 finished with value: 0.403744942160199 and parameters: {'alpha': 1.8362070467163114e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,872] Trial 108 finished with value: 0.403745264462009 and parameters: {'alpha': 6.11520348457225e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,891] Trial 109 finished with value: 0.40374512074977154 and parameters: {'alpha': 3.184810658922484e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,911] Trial 110 finished with value: 0.40374536683109047 and parameters: {'alpha': 3.129353078896794e-07}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,931] Trial 111 finished with value: 0.4037449161348771 and parameters: {'alpha': 1.6600290181915936e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,950] Trial 112 finished with value: 0.4037446999003949 and parameters: {'alpha': 1.0138356502812415e-08}. Best is trial 94 with value: 0.4037443194743698.

Best trial: 94. Best value: 0.403744:   2%|▏         | 122/5000 [00:02<01:39, 49.01it/s]

[I 2026-06-14 00:48:34,971] Trial 113 finished with value: 0.40631527440775567 and parameters: {'alpha': 651.651991957932}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:34,993] Trial 114 finished with value: 0.4037451580012407 and parameters: {'alpha': 3.5836615563600376e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,013] Trial 115 finished with value: 0.40374446568882005 and parameters: {'alpha': 1.001107676626611e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,040] Trial 116 finished with value: 0.40374529726164377 and parameters: {'alpha': 6.89031658699696e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,066] Trial 117 finished with value: 0.4037447858547797 and parameters: {'alpha': 1.8036217618392573e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,087] Trial 118 finished with value: 0.4037453153809239 and parameters: {'alpha': 1.2316606186675229e-07}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,104] Trial 119 finished with value: 0.40374519409264586 and parameters: {'alpha': 3.37792527799558e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,123] Trial 120 finished with value: 0.4037444429873221 and parameters: {'alpha': 1.033905357482103e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,141] Trial 121 finished with value: 0.40374481906329657 and parameters: {'alpha': 1.4801781229999689e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,163] Trial 122 finished with value: 0.4037444335589574 and parameters: {'alpha': 1.0106308561742972e-08}. Best is trial 94 with value: 0.4037443194743698.

Best trial: 94. Best value: 0.403744:   3%|▎         | 132/5000 [00:02<01:39, 48.91it/s]

[I 2026-06-14 00:48:35,182] Trial 123 finished with value: 0.4037450506799012 and parameters: {'alpha': 2.5799160470112523e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,203] Trial 124 finished with value: 0.40374529044953716 and parameters: {'alpha': 5.373424819984963e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,224] Trial 125 finished with value: 0.40374442266784744 and parameters: {'alpha': 1.0055249931170379e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,245] Trial 126 finished with value: 0.40374507207281235 and parameters: {'alpha': 2.7152002784355204e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,267] Trial 127 finished with value: 0.40374530248324647 and parameters: {'alpha': 8.174265254374714e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,286] Trial 128 finished with value: 0.4037448188659096 and parameters: {'alpha': 1.7730593432116185e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,307] Trial 129 finished with value: 0.403745228839966 and parameters: {'alpha': 4.5579196434414754e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,327] Trial 130 finished with value: 0.4037453615055844 and parameters: {'alpha': 1.7948214378924845e-07}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,347] Trial 131 finished with value: 0.4037445119341549 and parameters: {'alpha': 1.0728562140584691e-08}. Best is trial 94 with value: 0.4037443194743698.
[I 2026-06-14 00:48:35,368] Trial 132 finished with value: 0.4037443392502177 and parameters: {'alpha': 1.0102795190361493e-08}. Best is trial 94 with value: 0.4037443194743698.

Best trial: 133. Best value: 0.403744:   3%|▎         | 143/5000 [00:02<01:38, 49.27it/s]

[I 2026-06-14 00:48:35,387] Trial 133 finished with value: 0.40374429462837746 and parameters: {'alpha': 1.0141789702241557e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,408] Trial 134 finished with value: 0.4037449580231836 and parameters: {'alpha': 1.8643233992351414e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,430] Trial 135 finished with value: 0.4037451210734443 and parameters: {'alpha': 2.9696466667865673e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,450] Trial 136 finished with value: 0.40374490017772363 and parameters: {'alpha': 1.8618750542653814e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,471] Trial 137 finished with value: 0.4037452917897507 and parameters: {'alpha': 5.817571341953955e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,490] Trial 138 finished with value: 0.40374531014765586 and parameters: {'alpha': 9.813256107125801e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,509] Trial 139 finished with value: 0.4037446736333861 and parameters: {'alpha': 1.0523082316542397e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,528] Trial 140 finished with value: 0.40374517107228064 and parameters: {'alpha': 3.74093961107737e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,548] Trial 141 finished with value: 0.40374460401585943 and parameters: {'alpha': 1.070308652260404e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,569] Trial 142 finished with value: 0.40375059325323454 and parameters: {'alpha': 4.08448122407018}. Best is trial 133 with value: 0.40374429462837746.

Best trial: 144. Best value: 0.403744:   3%|▎         | 153/5000 [00:03<01:38, 49.15it/s]

[I 2026-06-14 00:48:35,590] Trial 143 finished with value: 0.40374500259005275 and parameters: {'alpha': 2.008268463436849e-08}. Best is trial 133 with value: 0.40374429462837746.
[I 2026-06-14 00:48:35,612] Trial 144 finished with value: 0.4037442500382929 and parameters: {'alpha': 1.012158676651819e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,632] Trial 145 finished with value: 0.4037450313709444 and parameters: {'alpha': 2.2855763625988675e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,652] Trial 146 finished with value: 0.4037452792849435 and parameters: {'alpha': 3.897016273348746e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,671] Trial 147 finished with value: 0.4037443255082728 and parameters: {'alpha': 1.0453891397920869e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,695] Trial 148 finished with value: 0.4037449397171128 and parameters: {'alpha': 1.982405891326261e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,714] Trial 149 finished with value: 0.40374527626833895 and parameters: {'alpha': 6.53845187852529e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,733] Trial 150 finished with value: 0.4037451608919535 and parameters: {'alpha': 3.502106327425609e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,755] Trial 151 finished with value: 0.40374445290714867 and parameters: {'alpha': 1.0410237413133586e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,775] Trial 152 finished with value: 0.40374476693480654 and parameters: {'alpha': 1.8057962745935396e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   3%|▎         | 163/5000 [00:03<01:38, 49.16it/s]

[I 2026-06-14 00:48:35,794] Trial 153 finished with value: 0.40374491204305274 and parameters: {'alpha': 1.730355787306581e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,815] Trial 154 finished with value: 0.40374435905505074 and parameters: {'alpha': 1.027305156886622e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,835] Trial 155 finished with value: 0.4037445023907848 and parameters: {'alpha': 1.0805524541048555e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,856] Trial 156 finished with value: 0.4037452070878034 and parameters: {'alpha': 3.2996902828586366e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,876] Trial 157 finished with value: 0.40374529552151267 and parameters: {'alpha': 4.9020282466263575e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,896] Trial 158 finished with value: 0.4037454089502162 and parameters: {'alpha': 0.003650244532758251}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,915] Trial 159 finished with value: 0.4037445277660744 and parameters: {'alpha': 1.0539831763700583e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,934] Trial 160 finished with value: 0.40374530655133206 and parameters: {'alpha': 8.981523900625854e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,954] Trial 161 finished with value: 0.40374495774800157 and parameters: {'alpha': 1.8124394995886822e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,974] Trial 162 finished with value: 0.4037450303884639 and parameters: {'alpha': 2.5894556192154383e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:35,993] Trial 163 finished with value: 0.4037444961914123 and parameters: {'alpha': 1.001339308441452e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   3%|▎         | 174/5000 [00:03<01:37, 49.59it/s]

[I 2026-06-14 00:48:36,014] Trial 164 finished with value: 0.403744953543452 and parameters: {'alpha': 1.8598122718999544e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,036] Trial 165 finished with value: 0.40374455080458943 and parameters: {'alpha': 1.009208203650802e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,056] Trial 166 finished with value: 0.40374513485611746 and parameters: {'alpha': 3.199564352905092e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,075] Trial 167 finished with value: 0.5688776127719019 and parameters: {'alpha': 76979.03292606483}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,094] Trial 168 finished with value: 0.4037452630649052 and parameters: {'alpha': 6.270462513168118e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,114] Trial 169 finished with value: 0.4037449809033632 and parameters: {'alpha': 1.844684985703126e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,134] Trial 170 finished with value: 0.40374521080613357 and parameters: {'alpha': 3.301110793742245e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,153] Trial 171 finished with value: 0.40374436334874375 and parameters: {'alpha': 1.0695514272171397e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,172] Trial 172 finished with value: 0.40374467512985257 and parameters: {'alpha': 1.0413851429688532e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,192] Trial 173 finished with value: 0.4037449406995494 and parameters: {'alpha': 1.9617923308457238e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,213] Trial 174 finished with value: 0.403744836278386 and parameters: {'alpha': 1.9245430527169192e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   4%|▎         | 185/5000 [00:03<01:36, 49.80it/s]

[I 2026-06-14 00:48:36,234] Trial 175 finished with value: 0.40374526241164693 and parameters: {'alpha': 3.845575618908859e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,257] Trial 176 finished with value: 0.4037447390943769 and parameters: {'alpha': 1.642169831315821e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,277] Trial 177 finished with value: 0.403744481560384 and parameters: {'alpha': 1.0048129978480159e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,296] Trial 178 finished with value: 0.4037452719883262 and parameters: {'alpha': 5.6320052181395554e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,314] Trial 179 finished with value: 0.4037445429385027 and parameters: {'alpha': 1.0387453922385509e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,336] Trial 180 finished with value: 0.40374505076984596 and parameters: {'alpha': 2.9342807577353643e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,356] Trial 181 finished with value: 0.40374469035101923 and parameters: {'alpha': 1.0486232067329304e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,375] Trial 182 finished with value: 0.40374499365672284 and parameters: {'alpha': 1.9065521159260517e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,393] Trial 183 finished with value: 0.40374503570640224 and parameters: {'alpha': 2.9220899195473107e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,413] Trial 184 finished with value: 0.40374491625631276 and parameters: {'alpha': 1.7123230781061456e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,433] Trial 185 finished with value: 0.40374461595304845 and parameters: {'alpha': 1.0131104008836155e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   4%|▍         | 196/5000 [00:04<01:37, 49.41it/s]

[I 2026-06-14 00:48:36,454] Trial 186 finished with value: 0.4037452776502398 and parameters: {'alpha': 4.976873705347984e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,475] Trial 187 finished with value: 0.40374468321158796 and parameters: {'alpha': 1.0081174097029985e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,497] Trial 188 finished with value: 0.40374505699574104 and parameters: {'alpha': 2.5085700618783066e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,518] Trial 189 finished with value: 0.5049041251500844 and parameters: {'alpha': 14378.256732204565}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,538] Trial 190 finished with value: 0.4037453236583007 and parameters: {'alpha': 1.3417134048564365e-07}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,559] Trial 191 finished with value: 0.403744390534812 and parameters: {'alpha': 1.0251592508406511e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,577] Trial 192 finished with value: 0.40374481608662216 and parameters: {'alpha': 1.8130967103618465e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,595] Trial 193 finished with value: 0.40374484554910695 and parameters: {'alpha': 1.7350437511483764e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,615] Trial 194 finished with value: 0.4037451760616462 and parameters: {'alpha': 3.229703787313909e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,634] Trial 195 finished with value: 0.40374459121826006 and parameters: {'alpha': 1.0345297139378257e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,653] Trial 196 finished with value: 0.4037452033958381 and parameters: {'alpha': 3.028067116835657e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   4%|▍         | 206/5000 [00:04<01:37, 49.15it/s]

[I 2026-06-14 00:48:36,674] Trial 197 finished with value: 0.4037453236238695 and parameters: {'alpha': 5.7685702601493715e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,697] Trial 198 finished with value: 0.40374490688436976 and parameters: {'alpha': 1.7143020894180697e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,720] Trial 199 finished with value: 0.40374441752584883 and parameters: {'alpha': 1.0424563176894905e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,740] Trial 200 finished with value: 0.40374483882978557 and parameters: {'alpha': 1.7488881339193805e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,761] Trial 201 finished with value: 0.40374458051707496 and parameters: {'alpha': 1.0194404784307371e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,781] Trial 202 finished with value: 0.4037450679393211 and parameters: {'alpha': 2.8338523478723705e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,801] Trial 203 finished with value: 0.40374482748333423 and parameters: {'alpha': 1.6523281750567305e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,822] Trial 204 finished with value: 0.4037445156393236 and parameters: {'alpha': 1.0476906343594698e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,842] Trial 205 finished with value: 0.4037452164353504 and parameters: {'alpha': 3.680763341950101e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,861] Trial 206 finished with value: 0.40374494348127515 and parameters: {'alpha': 1.7581875507376022e-08}. Best is trial 144 with value: 0.4037442500382929.

[I 2026-06-14 00:48:36,881] Trial 207 finished with value: 0.4037450290595149 and parameters: {'alpha': 2.6778087481909183e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,904] Trial 208 finished with value: 0.40374525830735264 and parameters: {'alpha': 5.195930060796878e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,926] Trial 209 finished with value: 0.40374447214028997 and parameters: {'alpha': 1.0042128292137965e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,947] Trial 210 finished with value: 0.40374489347056264 and parameters: {'alpha': 1.7652815005557367e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,967] Trial 211 finished with value: 0.40374438960885817 and parameters: {'alpha': 1.0697146348426741e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:36,985] Trial 212 finished with value: 0.40374444641635615 and parameters: {'alpha': 1.001470882987175e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,005] Trial 213 finished with value: 0.4037443965012361 and parameters: {'alpha': 1.0400956631185484e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,026] Trial 214 finished with value: 0.40374476639596624 and parameters: {'alpha': 1.8845808443832632e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,045] Trial 215 finished with value: 0.4037443426309288 and parameters: {'alpha': 1.0144438440294931e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,064] Trial 216 finished with value: 0.40374503710471726 and parameters: {'alpha': 2.6517141613117818e-08}. Best is trial 144 with value: 0.4037442500382929.

[I 2026-06-14 00:48:37,085] Trial 217 finished with value: 0.4037447565721186 and parameters: {'alpha': 1.759228370857063e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,107] Trial 218 finished with value: 0.4037446811850471 and parameters: {'alpha': 1.0024841225154479e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,127] Trial 219 finished with value: 0.4037452352961402 and parameters: {'alpha': 3.869921473764374e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,148] Trial 220 finished with value: 0.40374499411189957 and parameters: {'alpha': 1.8950690715620877e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,168] Trial 221 finished with value: 0.40374442164003044 and parameters: {'alpha': 1.070701788326731e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,189] Trial 222 finished with value: 0.4037448694602031 and parameters: {'alpha': 1.6088610330794044e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,209] Trial 223 finished with value: 0.4037450098350673 and parameters: {'alpha': 2.8486790405331376e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,229] Trial 224 finished with value: 0.40374453899001084 and parameters: {'alpha': 1.015364689107067e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,249] Trial 225 finished with value: 0.4037449281841827 and parameters: {'alpha': 1.7091933869554124e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,269] Trial 226 finished with value: 0.40374507611860105 and parameters: {'alpha': 2.946841969698199e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   5%|▍         | 237/5000 [00:04<01:35, 49.73it/s]

[I 2026-06-14 00:48:37,287] Trial 227 finished with value: 0.40374467430160904 and parameters: {'alpha': 1.0118723433096696e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,306] Trial 228 finished with value: 0.4037452876919563 and parameters: {'alpha': 5.182317713294735e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,329] Trial 229 finished with value: 0.4037448842452988 and parameters: {'alpha': 1.7608134302922187e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,347] Trial 230 finished with value: 0.40374426753058007 and parameters: {'alpha': 1.0288225564266633e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,367] Trial 231 finished with value: 0.4037448868647572 and parameters: {'alpha': 1.6943247026477334e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,389] Trial 232 finished with value: 0.4037444486741778 and parameters: {'alpha': 1.0314881181128404e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,408] Trial 233 finished with value: 0.40374507395575754 and parameters: {'alpha': 2.8900557081168934e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,427] Trial 234 finished with value: 0.403744551828359 and parameters: {'alpha': 1.0495467611591126e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,446] Trial 235 finished with value: 0.4037443001536579 and parameters: {'alpha': 1.0068087325682386e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,466] Trial 236 finished with value: 0.40374481534080964 and parameters: {'alpha': 1.8839959005778613e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,484] Trial 237 finished with value: 0.4037450106311794 and parameters: {'alpha': 2.8243186670747653e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   5%|▍         | 247/5000 [00:05<01:36, 49.05it/s]

[I 2026-06-14 00:48:37,506] Trial 238 finished with value: 0.40374485802821475 and parameters: {'alpha': 1.6507695779219807e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,530] Trial 239 finished with value: 0.40374434507704743 and parameters: {'alpha': 1.0524150050579463e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,553] Trial 240 finished with value: 0.40374526421806295 and parameters: {'alpha': 4.4703985910208377e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,574] Trial 241 finished with value: 0.40374457784690704 and parameters: {'alpha': 1.0494896339142033e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,593] Trial 242 finished with value: 0.4037447692150754 and parameters: {'alpha': 1.75267082889715e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,613] Trial 243 finished with value: 0.40374463759374635 and parameters: {'alpha': 1.0372870134047503e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,633] Trial 244 finished with value: 0.40374506579227937 and parameters: {'alpha': 2.6040877628428287e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,654] Trial 245 finished with value: 0.4037446571389962 and parameters: {'alpha': 1.0210706009460455e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,673] Trial 246 finished with value: 0.4037447762040512 and parameters: {'alpha': 1.851452198727744e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,693] Trial 247 finished with value: 0.40374455492553896 and parameters: {'alpha': 1.0017357570093104e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   5%|▌         | 257/5000 [00:05<01:37, 48.79it/s]

[I 2026-06-14 00:48:37,715] Trial 248 finished with value: 0.4037450362386927 and parameters: {'alpha': 2.8679447874943664e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,737] Trial 249 finished with value: 0.4037447362029288 and parameters: {'alpha': 1.000329445454342e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,759] Trial 250 finished with value: 0.4037448096758713 and parameters: {'alpha': 1.9449607163700604e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,780] Trial 251 finished with value: 0.40374481580520616 and parameters: {'alpha': 1.8380477827735392e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,799] Trial 252 finished with value: 0.4037452334088683 and parameters: {'alpha': 3.938047832253976e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,820] Trial 253 finished with value: 0.40374437794252044 and parameters: {'alpha': 1.0044604157830411e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,841] Trial 254 finished with value: 0.4037450793305812 and parameters: {'alpha': 2.5993698477977606e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,862] Trial 255 finished with value: 0.4037448981873293 and parameters: {'alpha': 1.705561866643171e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,882] Trial 256 finished with value: 0.4037452475331535 and parameters: {'alpha': 6.260557947416969e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,903] Trial 257 finished with value: 0.40374522573373395 and parameters: {'alpha': 3.433057334984458e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   5%|▌         | 267/5000 [00:05<01:38, 47.82it/s]

[I 2026-06-14 00:48:37,924] Trial 258 finished with value: 0.40374459216466646 and parameters: {'alpha': 1.0144478139918333e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,944] Trial 259 finished with value: 0.40374476474116733 and parameters: {'alpha': 1.7559937336788098e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,967] Trial 260 finished with value: 0.40374496607143245 and parameters: {'alpha': 1.8019610703718936e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:37,991] Trial 261 finished with value: 0.4037452627079493 and parameters: {'alpha': 4.205485422733514e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,011] Trial 262 finished with value: 0.4037452745264809 and parameters: {'alpha': 8.473625108165453e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,031] Trial 263 finished with value: 0.40374457675918585 and parameters: {'alpha': 1.0147571460820704e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,052] Trial 264 finished with value: 0.4037449773072113 and parameters: {'alpha': 2.695810957047732e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,074] Trial 265 finished with value: 0.40374483899316194 and parameters: {'alpha': 1.889313539790406e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,094] Trial 266 finished with value: 0.4037448657495104 and parameters: {'alpha': 1.7046390975969217e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,114] Trial 267 finished with value: 0.4037446355693808 and parameters: {'alpha': 1.0119021813257174e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   6%|▌         | 277/5000 [00:05<01:38, 48.10it/s]

[I 2026-06-14 00:48:38,133] Trial 268 finished with value: 0.4037452694943845 and parameters: {'alpha': 3.930648978979592e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,154] Trial 269 finished with value: 0.4037450086116518 and parameters: {'alpha': 2.7341098406658233e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,177] Trial 270 finished with value: 0.40374486043648855 and parameters: {'alpha': 1.7586826438750657e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,196] Trial 271 finished with value: 0.403744626566457 and parameters: {'alpha': 1.014005714850521e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,216] Trial 272 finished with value: 0.4037453007990667 and parameters: {'alpha': 5.8364360403498294e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,238] Trial 273 finished with value: 0.4037450211384371 and parameters: {'alpha': 2.547141393863917e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,258] Trial 274 finished with value: 0.40374488380490503 and parameters: {'alpha': 1.7321112894738828e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,279] Trial 275 finished with value: 0.40374559218933803 and parameters: {'alpha': 0.26112485909417454}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,298] Trial 276 finished with value: 0.4037444447580366 and parameters: {'alpha': 1.0150624742238142e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,318] Trial 277 finished with value: 0.40374523570506987 and parameters: {'alpha': 3.9111379765443674e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   6%|▌         | 287/5000 [00:05<01:37, 48.19it/s]

[I 2026-06-14 00:48:38,339] Trial 278 finished with value: 0.4037443908761887 and parameters: {'alpha': 1.0026509808502704e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,359] Trial 279 finished with value: 0.40374492598759343 and parameters: {'alpha': 1.8964426528274968e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,382] Trial 280 finished with value: 0.40374526604291683 and parameters: {'alpha': 8.037241539726673e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,404] Trial 281 finished with value: 0.40374503965161107 and parameters: {'alpha': 2.8456696796594415e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,424] Trial 282 finished with value: 0.4037447875576281 and parameters: {'alpha': 1.7237205699792045e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,444] Trial 283 finished with value: 0.4037448673982019 and parameters: {'alpha': 1.6505218385996783e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,463] Trial 284 finished with value: 0.40374431546093115 and parameters: {'alpha': 1.0090127189362862e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,486] Trial 285 finished with value: 0.40374516547207023 and parameters: {'alpha': 3.982875243127715e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,509] Trial 286 finished with value: 0.4037450641550038 and parameters: {'alpha': 2.6073009104898444e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,529] Trial 287 finished with value: 0.4037450013998129 and parameters: {'alpha': 1.8535801164925816e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   6%|▌         | 297/5000 [00:06<01:37, 48.01it/s]

[I 2026-06-14 00:48:38,549] Trial 288 finished with value: 0.40412860185015154 and parameters: {'alpha': 132.30690805629365}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,569] Trial 289 finished with value: 0.4037452639312359 and parameters: {'alpha': 5.221171280766249e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,589] Trial 290 finished with value: 0.4037448906830363 and parameters: {'alpha': 1.5740213404072345e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,612] Trial 291 finished with value: 0.40374460143332325 and parameters: {'alpha': 1.068595837923089e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,635] Trial 292 finished with value: 0.4037450347448939 and parameters: {'alpha': 2.4746095488141096e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,656] Trial 293 finished with value: 0.4037451710328851 and parameters: {'alpha': 3.1372350813415934e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,675] Trial 294 finished with value: 0.40374472987372745 and parameters: {'alpha': 1.0345627721462676e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,695] Trial 295 finished with value: 0.40374477004579523 and parameters: {'alpha': 1.7198275739490148e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,716] Trial 296 finished with value: 0.4037446270639915 and parameters: {'alpha': 1.00747611690776e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,736] Trial 297 finished with value: 0.4037453201408059 and parameters: {'alpha': 8.403206015151766e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   6%|▌         | 307/5000 [00:06<01:38, 47.56it/s]

[I 2026-06-14 00:48:38,755] Trial 298 finished with value: 0.40374444964150435 and parameters: {'alpha': 1.0133946429637416e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,777] Trial 299 finished with value: 0.40374525769029124 and parameters: {'alpha': 4.537192374501734e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,798] Trial 300 finished with value: 0.403745035452365 and parameters: {'alpha': 2.7274234001194904e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,822] Trial 301 finished with value: 0.40374540655861135 and parameters: {'alpha': 0.00014516685556669612}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,844] Trial 302 finished with value: 0.40374481461592765 and parameters: {'alpha': 1.7973355596472047e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,864] Trial 303 finished with value: 0.4037445663321162 and parameters: {'alpha': 1.0141472301775882e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,885] Trial 304 finished with value: 0.4037454056822105 and parameters: {'alpha': 1.2077585636932142e-05}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,908] Trial 305 finished with value: 0.4037450418877414 and parameters: {'alpha': 2.739392095258621e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,929] Trial 306 finished with value: 0.403744801026713 and parameters: {'alpha': 1.693403380109078e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,949] Trial 307 finished with value: 0.4037452654811056 and parameters: {'alpha': 5.359608088250449e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   6%|▋         | 317/5000 [00:06<01:39, 47.28it/s]

[I 2026-06-14 00:48:38,971] Trial 308 finished with value: 0.4037454067967567 and parameters: {'alpha': 0.00044913136844313746}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:38,993] Trial 309 finished with value: 0.4037447695532153 and parameters: {'alpha': 1.7202003915812904e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,016] Trial 310 finished with value: 0.4037443892605136 and parameters: {'alpha': 1.0037339133153951e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,039] Trial 311 finished with value: 0.4037451901761985 and parameters: {'alpha': 3.1781373724862965e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,060] Trial 312 finished with value: 0.4037447819695762 and parameters: {'alpha': 1.7184269356298066e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,079] Trial 313 finished with value: 0.4037451227853378 and parameters: {'alpha': 3.0047929679046514e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,099] Trial 314 finished with value: 0.4037446283253961 and parameters: {'alpha': 1.0359764849398536e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,119] Trial 315 finished with value: 0.4037444097871713 and parameters: {'alpha': 1.0099939443435234e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,142] Trial 316 finished with value: 0.4037449174519967 and parameters: {'alpha': 1.7638491877174108e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,161] Trial 317 finished with value: 0.4037452541513648 and parameters: {'alpha': 5.241518476018904e-08}. Best is trial 144 with value: 0.4037442500382929.

Best trial: 144. Best value: 0.403744:   7%|▋         | 327/5000 [00:06<01:37, 47.75it/s]

[I 2026-06-14 00:48:39,181] Trial 318 finished with value: 0.4037442810133765 and parameters: {'alpha': 1.0064596748988736e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,203] Trial 319 finished with value: 0.40374453834983176 and parameters: {'alpha': 1.0156976781559157e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,226] Trial 320 finished with value: 0.40374513237166004 and parameters: {'alpha': 2.989125998704561e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,247] Trial 321 finished with value: 0.40374530003160286 and parameters: {'alpha': 1.0396724488407988e-07}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,269] Trial 322 finished with value: 0.40374495523291526 and parameters: {'alpha': 1.744166195976223e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,288] Trial 323 finished with value: 0.4037442973432835 and parameters: {'alpha': 1.0119819046203306e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,308] Trial 324 finished with value: 0.40374502009949276 and parameters: {'alpha': 2.599027437400513e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,329] Trial 325 finished with value: 0.40374528523494524 and parameters: {'alpha': 4.794880925204e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,351] Trial 326 finished with value: 0.4037443216106441 and parameters: {'alpha': 1.0035369743907507e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,372] Trial 327 finished with value: 0.40374491378261534 and parameters: {'alpha': 1.7646531921312974e-08}. Best is trial 144 with value: 0.4037442500382929.

[I 2026-06-14 00:48:39,394] Trial 328 finished with value: 0.4037449773932063 and parameters: {'alpha': 1.9469069630236015e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,416] Trial 329 finished with value: 0.40374473160395197 and parameters: {'alpha': 1.0162590979909886e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,439] Trial 330 finished with value: 0.4037543400558558 and parameters: {'alpha': 5.978301795934872}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,462] Trial 331 finished with value: 0.40374540978414425 and parameters: {'alpha': 0.004896834891003783}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,482] Trial 332 finished with value: 0.4133769465877577 and parameters: {'alpha': 1540.4393220278246}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,501] Trial 333 finished with value: 0.4037451882385974 and parameters: {'alpha': 3.8249905746571115e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,519] Trial 334 finished with value: 0.4037449431164225 and parameters: {'alpha': 1.8919224995354465e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,538] Trial 335 finished with value: 0.40374458764180315 and parameters: {'alpha': 1.0094350389969183e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,557] Trial 336 finished with value: 0.40374526444264214 and parameters: {'alpha': 7.94983980821927e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,577] Trial 337 finished with value: 0.40374518006231536 and parameters: {'alpha': 3.0708500495298896e-08}. Best is trial 144 with value: 0.4037442500382929.

[I 2026-06-14 00:48:39,595] Trial 338 finished with value: 0.40374481908029497 and parameters: {'alpha': 1.9460384042734682e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,616] Trial 339 finished with value: 0.403744778127222 and parameters: {'alpha': 1.678093791397545e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,637] Trial 340 finished with value: 0.40374435220850113 and parameters: {'alpha': 1.0050458440556773e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,658] Trial 341 finished with value: 0.40374526886501716 and parameters: {'alpha': 4.419869240055685e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,680] Trial 342 finished with value: 0.40374506315267655 and parameters: {'alpha': 2.6566534874764557e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,701] Trial 343 finished with value: 0.40374502757919206 and parameters: {'alpha': 1.975237687497085e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,721] Trial 344 finished with value: 0.4037445731383165 and parameters: {'alpha': 1.0092807318326088e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,740] Trial 345 finished with value: 0.4037452967442105 and parameters: {'alpha': 4.28092829421883e-08}. Best is trial 144 with value: 0.4037442500382929.
[I 2026-06-14 00:48:39,763] Trial 346 finished with value: 0.4037442459980544 and parameters: {'alpha': 1.0049366635043204e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   7%|▋         | 354/5000 [00:07<01:55, 40.35it/s]

[I 2026-06-14 00:48:39,788] Trial 347 finished with value: 0.4037449731538733 and parameters: {'alpha': 1.7478533780257744e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:39,845] Trial 348 finished with value: 0.40374501188440676 and parameters: {'alpha': 2.8548540478709626e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:39,881] Trial 349 finished with value: 0.4037452820621407 and parameters: {'alpha': 7.436799889474839e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:39,911] Trial 350 finished with value: 0.4037448707927258 and parameters: {'alpha': 1.8783467725983777e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:39,931] Trial 351 finished with value: 0.4037445271685209 and parameters: {'alpha': 1.0269190942040484e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:39,962] Trial 352 finished with value: 0.40374503386779703 and parameters: {'alpha': 2.886912300287504e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:39,985] Trial 353 finished with value: 0.40374479144717007 and parameters: {'alpha': 1.84088381515939e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,006] Trial 354 finished with value: 0.40374489736303953 and parameters: {'alpha': 1.6799120903329846e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   7%|▋         | 364/5000 [00:07<01:47, 43.19it/s]

[I 2026-06-14 00:48:40,026] Trial 355 finished with value: 0.40374533097018084 and parameters: {'alpha': 1.5181285266714483e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,048] Trial 356 finished with value: 0.4037445818895985 and parameters: {'alpha': 1.002442722223718e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,072] Trial 357 finished with value: 0.40374527102236 and parameters: {'alpha': 4.981517234281116e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,092] Trial 358 finished with value: 0.40374519496587874 and parameters: {'alpha': 3.3741776901505206e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,112] Trial 359 finished with value: 0.403744868655982 and parameters: {'alpha': 1.707693532796913e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,132] Trial 360 finished with value: 0.4037445709534164 and parameters: {'alpha': 1.0297738209502636e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,153] Trial 361 finished with value: 0.4037450815589254 and parameters: {'alpha': 2.7700860917369504e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,175] Trial 362 finished with value: 0.40374478557371557 and parameters: {'alpha': 1.7617085899108525e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,194] Trial 363 finished with value: 0.4037452787264718 and parameters: {'alpha': 5.0653296514030486e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,214] Trial 364 finished with value: 0.40374432114034614 and parameters: {'alpha': 1.001850656019946e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   7%|▋         | 374/5000 [00:07<01:42, 45.30it/s]

[I 2026-06-14 00:48:40,237] Trial 365 finished with value: 0.40374496526983644 and parameters: {'alpha': 2.737377920200155e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,261] Trial 366 finished with value: 0.4037454063482504 and parameters: {'alpha': 5.275039852600456e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,283] Trial 367 finished with value: 0.4037449785293185 and parameters: {'alpha': 1.7370763345393293e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,304] Trial 368 finished with value: 0.4037452968400374 and parameters: {'alpha': 7.116330959075675e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,324] Trial 369 finished with value: 0.40374471030509157 and parameters: {'alpha': 1.6497731741409676e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,345] Trial 370 finished with value: 0.4037446448102921 and parameters: {'alpha': 1.0113885321203741e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,364] Trial 371 finished with value: 0.4037451439414587 and parameters: {'alpha': 3.012718012875829e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,386] Trial 372 finished with value: 0.403745084587409 and parameters: {'alpha': 2.7859229063728147e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,406] Trial 373 finished with value: 0.40374434542139087 and parameters: {'alpha': 1.0024843079514907e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,426] Trial 374 finished with value: 0.4037449083372728 and parameters: {'alpha': 1.7143813205005142e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   8%|▊         | 384/5000 [00:08<01:41, 45.56it/s]

[I 2026-06-14 00:48:40,447] Trial 375 finished with value: 0.40374521640132754 and parameters: {'alpha': 4.2843171201641196e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,469] Trial 376 finished with value: 0.40374476935770803 and parameters: {'alpha': 1.6592369630137177e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,494] Trial 377 finished with value: 0.40374493766935926 and parameters: {'alpha': 1.6118163379509745e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,517] Trial 378 finished with value: 0.4037444510481611 and parameters: {'alpha': 1.0117332483241834e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,540] Trial 379 finished with value: 0.4037453178292382 and parameters: {'alpha': 1.0429138318322981e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,559] Trial 380 finished with value: 0.40374498454411006 and parameters: {'alpha': 2.7925652976496483e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,581] Trial 381 finished with value: 0.4037446723070067 and parameters: {'alpha': 1.029115730487395e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,602] Trial 382 finished with value: 0.40374531236264016 and parameters: {'alpha': 5.651689662261197e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,623] Trial 383 finished with value: 0.4037450461224143 and parameters: {'alpha': 2.5079408963924318e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,643] Trial 384 finished with value: 0.40374429911249865 and parameters: {'alpha': 1.028825510596558e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   8%|▊         | 393/5000 [00:08<01:37, 47.08it/s]

[I 2026-06-14 00:48:40,663] Trial 385 finished with value: 0.4037443370109785 and parameters: {'alpha': 1.0017199131527968e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,683] Trial 386 finished with value: 0.40374489063652674 and parameters: {'alpha': 1.8198369269305887e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,706] Trial 387 finished with value: 0.403745230085927 and parameters: {'alpha': 3.9434073745835295e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,725] Trial 388 finished with value: 0.40374487944861887 and parameters: {'alpha': 1.764145121620518e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,745] Trial 389 finished with value: 0.4037450391395305 and parameters: {'alpha': 2.8114614610851326e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,767] Trial 390 finished with value: 0.4037449517174235 and parameters: {'alpha': 1.9611979679611645e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,787] Trial 391 finished with value: 0.40374527564369606 and parameters: {'alpha': 5.965582521613032e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,823] Trial 392 finished with value: 0.4037447370166874 and parameters: {'alpha': 1.5547041049784087e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,843] Trial 393 finished with value: 0.4037444818980803 and parameters: {'alpha': 1.029200260133153e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   8%|▊         | 403/5000 [00:08<01:42, 44.81it/s]

[I 2026-06-14 00:48:40,865] Trial 394 finished with value: 0.40374471845469995 and parameters: {'alpha': 1.0175522207789798e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,886] Trial 395 finished with value: 0.4037451829909251 and parameters: {'alpha': 3.3093621146242104e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,909] Trial 396 finished with value: 0.4037449450342169 and parameters: {'alpha': 1.8286292265417208e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,933] Trial 397 finished with value: 0.40374447279303216 and parameters: {'alpha': 1.0063088159481185e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,956] Trial 398 finished with value: 0.40374524296905484 and parameters: {'alpha': 4.1827122330471586e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,977] Trial 399 finished with value: 0.40374501498348053 and parameters: {'alpha': 2.5531730827724745e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:40,998] Trial 400 finished with value: 0.40374483320131316 and parameters: {'alpha': 1.7098065711269632e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,022] Trial 401 finished with value: 0.4037445287808101 and parameters: {'alpha': 1.0041667507628403e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,044] Trial 402 finished with value: 0.40374526438239633 and parameters: {'alpha': 7.16205714659486e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,063] Trial 403 finished with value: 0.4037451755707236 and parameters: {'alpha': 3.004856769938877e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   8%|▊         | 413/5000 [00:08<01:40, 45.85it/s]

[I 2026-06-14 00:48:41,085] Trial 404 finished with value: 0.40374444936148046 and parameters: {'alpha': 1.0056852797725774e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,108] Trial 405 finished with value: 0.403744758628801 and parameters: {'alpha': 1.7991589119026226e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,131] Trial 406 finished with value: 0.40374525400196654 and parameters: {'alpha': 4.021967255032889e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,155] Trial 407 finished with value: 0.40374488349179694 and parameters: {'alpha': 2.1644373521087107e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,175] Trial 408 finished with value: 0.40374480480360114 and parameters: {'alpha': 1.6959337089556504e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,195] Trial 409 finished with value: 0.40374509287582905 and parameters: {'alpha': 2.882965431687945e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,215] Trial 410 finished with value: 0.40374533078530406 and parameters: {'alpha': 1.1307205617133814e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,236] Trial 411 finished with value: 0.4037449117826941 and parameters: {'alpha': 1.659086634777558e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,258] Trial 412 finished with value: 0.40374440666253725 and parameters: {'alpha': 1.0080582523755374e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,278] Trial 413 finished with value: 0.40374528150807876 and parameters: {'alpha': 5.528619919469187e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   8%|▊         | 423/5000 [00:08<01:38, 46.27it/s]

[I 2026-06-14 00:48:41,300] Trial 414 finished with value: 0.4037449868006281 and parameters: {'alpha': 2.7359092417097506e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,321] Trial 415 finished with value: 0.4037444273466796 and parameters: {'alpha': 1.0057823294470273e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,345] Trial 416 finished with value: 0.4037449738962522 and parameters: {'alpha': 1.917005775565612e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,368] Trial 417 finished with value: 0.4908432799269636 and parameters: {'alpha': 11160.382471424518}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,387] Trial 418 finished with value: 0.4037452471861081 and parameters: {'alpha': 4.382137313986517e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,408] Trial 419 finished with value: 0.4037448417253419 and parameters: {'alpha': 1.7351349787486484e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,429] Trial 420 finished with value: 0.4037449569311844 and parameters: {'alpha': 1.6784765310671587e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,449] Trial 421 finished with value: 0.40374524205291706 and parameters: {'alpha': 3.3128608181772204e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,472] Trial 422 finished with value: 0.4037444940091267 and parameters: {'alpha': 1.0107120867643227e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,493] Trial 423 finished with value: 0.4037443492196256 and parameters: {'alpha': 1.0237928683261083e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   9%|▊         | 433/5000 [00:09<01:38, 46.51it/s]

[I 2026-06-14 00:48:41,513] Trial 424 finished with value: 0.40374502917555966 and parameters: {'alpha': 2.5883016646799678e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,534] Trial 425 finished with value: 0.4037452844989523 and parameters: {'alpha': 6.373971209278056e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,558] Trial 426 finished with value: 0.40374433027059525 and parameters: {'alpha': 1.0142990678010564e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,581] Trial 427 finished with value: 0.40384573155259434 and parameters: {'alpha': 34.87869627691754}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,602] Trial 428 finished with value: 0.4037445725113086 and parameters: {'alpha': 1.0065703143176006e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,624] Trial 429 finished with value: 0.40374493294934444 and parameters: {'alpha': 1.8178898432399742e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,645] Trial 430 finished with value: 0.40374511691179454 and parameters: {'alpha': 3.1123648014801836e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,664] Trial 431 finished with value: 0.4037453630496898 and parameters: {'alpha': 2.2122645806439975e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,685] Trial 432 finished with value: 0.40374470022337294 and parameters: {'alpha': 1.0011923957279456e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,707] Trial 433 finished with value: 0.4037447829095126 and parameters: {'alpha': 1.823999209553073e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   9%|▉         | 443/5000 [00:09<01:37, 46.57it/s]

[I 2026-06-14 00:48:41,729] Trial 434 finished with value: 0.40374524850113835 and parameters: {'alpha': 3.844658981788314e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,750] Trial 435 finished with value: 0.4037448332699005 and parameters: {'alpha': 1.679799568225633e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,774] Trial 436 finished with value: 0.40374542908083444 and parameters: {'alpha': 0.033550237985698825}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,797] Trial 437 finished with value: 0.4037452988900764 and parameters: {'alpha': 8.834476862172009e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,819] Trial 438 finished with value: 0.40374502313148825 and parameters: {'alpha': 2.6489382735937766e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,840] Trial 439 finished with value: 0.4037447213000715 and parameters: {'alpha': 1.5671320514068817e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,859] Trial 440 finished with value: 0.40374527489641876 and parameters: {'alpha': 4.931730659069138e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,880] Trial 441 finished with value: 0.4037447952118146 and parameters: {'alpha': 1.7163136853436536e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,902] Trial 442 finished with value: 0.40374504569669334 and parameters: {'alpha': 2.9373072319932296e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,922] Trial 443 finished with value: 0.40374485066425014 and parameters: {'alpha': 1.658688365241271e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   9%|▉         | 453/5000 [00:09<01:37, 46.86it/s]

[I 2026-06-14 00:48:41,943] Trial 444 finished with value: 0.4037448103551318 and parameters: {'alpha': 1.648795933664955e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,964] Trial 445 finished with value: 0.4037446329241305 and parameters: {'alpha': 1.045202153251967e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:41,987] Trial 446 finished with value: 0.4037444922484502 and parameters: {'alpha': 1.0105414047608671e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,010] Trial 447 finished with value: 0.40374523840956916 and parameters: {'alpha': 4.546432232199834e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,030] Trial 448 finished with value: 0.40374502246105576 and parameters: {'alpha': 2.675372004120036e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,052] Trial 449 finished with value: 0.40374438963522646 and parameters: {'alpha': 1.0228275119695275e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,073] Trial 450 finished with value: 0.403745094265118 and parameters: {'alpha': 2.7018678254658767e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,093] Trial 451 finished with value: 0.40374528139324634 and parameters: {'alpha': 8.341190627933326e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,115] Trial 452 finished with value: 0.403744805997614 and parameters: {'alpha': 1.982674037262527e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,136] Trial 453 finished with value: 0.4037444664104938 and parameters: {'alpha': 1.0258679878856342e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   9%|▉         | 463/5000 [00:09<01:37, 46.66it/s]

[I 2026-06-14 00:48:42,159] Trial 454 finished with value: 0.40374464650957753 and parameters: {'alpha': 1.0049080587527703e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,181] Trial 455 finished with value: 0.40374529060291703 and parameters: {'alpha': 4.889197411601876e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,204] Trial 456 finished with value: 0.40374501908608085 and parameters: {'alpha': 2.5946828832613752e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,226] Trial 457 finished with value: 0.40374492814568747 and parameters: {'alpha': 1.7692023304761708e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,249] Trial 458 finished with value: 0.4037449309842185 and parameters: {'alpha': 1.6737858769862487e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,268] Trial 459 finished with value: 0.4037446538574663 and parameters: {'alpha': 1.0029490364977288e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,289] Trial 460 finished with value: 0.40374526478113604 and parameters: {'alpha': 3.939264746014326e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,310] Trial 461 finished with value: 0.40374504142418316 and parameters: {'alpha': 2.629246869746093e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,330] Trial 462 finished with value: 0.4037453332928202 and parameters: {'alpha': 1.298643758321756e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,350] Trial 463 finished with value: 0.4037447743684712 and parameters: {'alpha': 1.7355225136576924e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:   9%|▉         | 472/5000 [00:09<01:40, 45.14it/s]

[I 2026-06-14 00:48:42,372] Trial 464 finished with value: 0.4037452899142268 and parameters: {'alpha': 5.902736713529513e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,393] Trial 465 finished with value: 0.4037443871336541 and parameters: {'alpha': 1.0104599489771543e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,415] Trial 466 finished with value: 0.40374506220729695 and parameters: {'alpha': 2.7319561365885048e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,439] Trial 467 finished with value: 0.40374430996951083 and parameters: {'alpha': 1.0060588222229008e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,462] Trial 468 finished with value: 0.40374492271800483 and parameters: {'alpha': 1.752401139846e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,495] Trial 469 finished with value: 0.4037445860391003 and parameters: {'alpha': 1.0069829575732354e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,516] Trial 470 finished with value: 0.40374518172651697 and parameters: {'alpha': 4.140952806445084e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,536] Trial 471 finished with value: 0.40374494089662205 and parameters: {'alpha': 1.6814041475920143e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,556] Trial 472 finished with value: 0.403745021635827 and parameters: {'alpha': 2.8402073187141284e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  10%|▉         | 482/5000 [00:10<01:36, 46.97it/s]

[I 2026-06-14 00:48:42,575] Trial 473 finished with value: 0.40374482736262607 and parameters: {'alpha': 1.7602245613294304e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,596] Trial 474 finished with value: 0.4037445536198222 and parameters: {'alpha': 1.0109427039278189e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,616] Trial 475 finished with value: 0.4037450979035876 and parameters: {'alpha': 2.831757862476605e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,636] Trial 476 finished with value: 0.4037452671224729 and parameters: {'alpha': 5.638912667936016e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,658] Trial 477 finished with value: 0.4037449099069994 and parameters: {'alpha': 1.6350086268178494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,679] Trial 478 finished with value: 0.4037445231036191 and parameters: {'alpha': 1.019758300691821e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,699] Trial 479 finished with value: 0.40374511316603345 and parameters: {'alpha': 2.9303249649553096e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,719] Trial 480 finished with value: 0.403744768534988 and parameters: {'alpha': 1.8016167777345218e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,740] Trial 481 finished with value: 0.4037447905515027 and parameters: {'alpha': 1.7632492670068746e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,762] Trial 482 finished with value: 0.4037452871822328 and parameters: {'alpha': 6.943739325226238e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  10%|▉         | 492/5000 [00:10<01:36, 46.82it/s]

[I 2026-06-14 00:48:42,784] Trial 483 finished with value: 0.4037452519767971 and parameters: {'alpha': 3.9606996915416045e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,809] Trial 484 finished with value: 0.4037448528391006 and parameters: {'alpha': 1.6214381167003614e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,830] Trial 485 finished with value: 0.40374500538471175 and parameters: {'alpha': 2.6359320523974162e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,851] Trial 486 finished with value: 0.4037444863234636 and parameters: {'alpha': 1.0497473808687959e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,873] Trial 487 finished with value: 0.4037443215511604 and parameters: {'alpha': 1.0292397238190626e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,893] Trial 488 finished with value: 0.4037448487252259 and parameters: {'alpha': 1.7406464890951797e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,914] Trial 489 finished with value: 0.4037452654854675 and parameters: {'alpha': 4.116420277076694e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,935] Trial 490 finished with value: 0.40374447397655255 and parameters: {'alpha': 1.0292919751108013e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,956] Trial 491 finished with value: 0.40374502929441575 and parameters: {'alpha': 2.561427854108612e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:42,977] Trial 492 finished with value: 0.4037447994539693 and parameters: {'alpha': 1.730091699103785e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  10%|█         | 502/5000 [00:10<01:36, 46.72it/s]

[I 2026-06-14 00:48:42,999] Trial 493 finished with value: 0.40374444883331356 and parameters: {'alpha': 1.024163668834435e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,019] Trial 494 finished with value: 0.4037452030262704 and parameters: {'alpha': 3.758402157391869e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,039] Trial 495 finished with value: 0.40374540752889465 and parameters: {'alpha': 0.0015281872615437002}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,059] Trial 496 finished with value: 0.40374532669457047 and parameters: {'alpha': 1.0848173358672057e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,081] Trial 497 finished with value: 0.40374434882374605 and parameters: {'alpha': 1.0109207152824604e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,102] Trial 498 finished with value: 0.4037449481677892 and parameters: {'alpha': 2.530957420412202e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,123] Trial 499 finished with value: 0.4037449748436029 and parameters: {'alpha': 1.753676766561398e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,145] Trial 500 finished with value: 0.40374528445724417 and parameters: {'alpha': 7.715689231058442e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,168] Trial 501 finished with value: 0.40374475427442424 and parameters: {'alpha': 1.677430962804036e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,190] Trial 502 finished with value: 0.40374518291555717 and parameters: {'alpha': 3.9525945139291364e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  10%|█         | 512/5000 [00:10<01:35, 46.82it/s]

[I 2026-06-14 00:48:43,210] Trial 503 finished with value: 0.4037445801699482 and parameters: {'alpha': 1.0096626883914946e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,233] Trial 504 finished with value: 0.4037446650531556 and parameters: {'alpha': 1.0147223828247647e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,254] Trial 505 finished with value: 0.40374506289181405 and parameters: {'alpha': 2.557629890536593e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,276] Trial 506 finished with value: 0.4037449858075192 and parameters: {'alpha': 1.811592248129112e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,298] Trial 507 finished with value: 0.4037452896036174 and parameters: {'alpha': 5.249224975019438e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,319] Trial 508 finished with value: 0.4037458073594072 and parameters: {'alpha': 0.5303909296441581}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,340] Trial 509 finished with value: 0.4037443881443065 and parameters: {'alpha': 1.0004775721191782e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,360] Trial 510 finished with value: 0.40374509563730104 and parameters: {'alpha': 2.819351176206946e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,381] Trial 511 finished with value: 0.4037448071315275 and parameters: {'alpha': 1.8192809846884758e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,404] Trial 512 finished with value: 0.4037449706040693 and parameters: {'alpha': 1.7703767574096008e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  10%|█         | 522/5000 [00:10<01:36, 46.20it/s]

[I 2026-06-14 00:48:43,426] Trial 513 finished with value: 0.40374514241356974 and parameters: {'alpha': 3.50113036281959e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,448] Trial 514 finished with value: 0.40374490369740684 and parameters: {'alpha': 1.737833584083489e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,470] Trial 515 finished with value: 0.4037445245410533 and parameters: {'alpha': 1.0275655506629407e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,491] Trial 516 finished with value: 0.40374437640309585 and parameters: {'alpha': 1.0048443493006751e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,513] Trial 517 finished with value: 0.40374530117522256 and parameters: {'alpha': 7.284622209017907e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,535] Trial 518 finished with value: 0.4037451928125333 and parameters: {'alpha': 3.081015756261779e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,557] Trial 519 finished with value: 0.40374482549031254 and parameters: {'alpha': 1.8683828619580912e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,578] Trial 520 finished with value: 0.4037446930002561 and parameters: {'alpha': 1.0115906245932715e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,600] Trial 521 finished with value: 0.40374527458513165 and parameters: {'alpha': 4.770684846675557e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,624] Trial 522 finished with value: 0.4037450094963187 and parameters: {'alpha': 2.57143926583887e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  11%|█         | 532/5000 [00:11<01:36, 46.29it/s]

[I 2026-06-14 00:48:43,644] Trial 523 finished with value: 0.40374495955016226 and parameters: {'alpha': 1.769355822423592e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,665] Trial 524 finished with value: 0.40374532841049904 and parameters: {'alpha': 1.4797351949900516e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,688] Trial 525 finished with value: 0.40374439322611316 and parameters: {'alpha': 1.0015902499472044e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,709] Trial 526 finished with value: 0.4037450492263122 and parameters: {'alpha': 2.7799716720291854e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,730] Trial 527 finished with value: 0.40374490679342917 and parameters: {'alpha': 1.7586198912042415e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,751] Trial 528 finished with value: 0.4037452619183557 and parameters: {'alpha': 4.951523378772248e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,772] Trial 529 finished with value: 0.40523291029850933 and parameters: {'alpha': 446.6859961362875}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,794] Trial 530 finished with value: 0.40374447477395375 and parameters: {'alpha': 1.0105934959489652e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,816] Trial 531 finished with value: 0.40374503635687564 and parameters: {'alpha': 2.776339098873052e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,839] Trial 532 finished with value: 0.4037445410032227 and parameters: {'alpha': 1.0026580255914011e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  11%|█         | 542/5000 [00:11<01:35, 46.53it/s]

[I 2026-06-14 00:48:43,860] Trial 533 finished with value: 0.40374478225916527 and parameters: {'alpha': 1.8010873107028007e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,880] Trial 534 finished with value: 0.4037447798687669 and parameters: {'alpha': 1.804142008167409e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,901] Trial 535 finished with value: 0.4037452512090918 and parameters: {'alpha': 4.788520708896128e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,923] Trial 536 finished with value: 0.40374508526404124 and parameters: {'alpha': 2.8474237488535464e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,945] Trial 537 finished with value: 0.4037443998751899 and parameters: {'alpha': 1.0073671437788209e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,968] Trial 538 finished with value: 0.40374480537323987 and parameters: {'alpha': 1.8131808225938738e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:43,988] Trial 539 finished with value: 0.40374527324429604 and parameters: {'alpha': 3.927204740260757e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,009] Trial 540 finished with value: 0.4037449634018772 and parameters: {'alpha': 1.6963610065938614e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,030] Trial 541 finished with value: 0.4037452680365877 and parameters: {'alpha': 6.940594976324345e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,053] Trial 542 finished with value: 0.40374455363348827 and parameters: {'alpha': 1.0068033987663541e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  11%|█         | 552/5000 [00:11<01:39, 44.91it/s]

[I 2026-06-14 00:48:44,073] Trial 543 finished with value: 0.403745020881301 and parameters: {'alpha': 2.9426468737399308e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,096] Trial 544 finished with value: 0.40374488490948857 and parameters: {'alpha': 1.7093274917843235e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,117] Trial 545 finished with value: 0.40374479357883025 and parameters: {'alpha': 1.7090351725292295e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,139] Trial 546 finished with value: 0.4037452238240823 and parameters: {'alpha': 3.553455224596828e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,164] Trial 547 finished with value: 0.40374451796993027 and parameters: {'alpha': 1.0063776355206813e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,189] Trial 548 finished with value: 0.4037449866338944 and parameters: {'alpha': 2.5502622544146362e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,211] Trial 549 finished with value: 0.4037453200872843 and parameters: {'alpha': 1.0212156957538831e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,233] Trial 550 finished with value: 0.40374483115386095 and parameters: {'alpha': 1.7082680692661496e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,255] Trial 551 finished with value: 0.4037452463860324 and parameters: {'alpha': 5.077803769530018e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  11%|█         | 562/5000 [00:11<01:37, 45.51it/s]

[I 2026-06-14 00:48:44,281] Trial 552 finished with value: 0.40374468204882524 and parameters: {'alpha': 1.0092205956585518e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,303] Trial 553 finished with value: 0.4037447362147303 and parameters: {'alpha': 1.0062008982101195e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,323] Trial 554 finished with value: 0.40374494299891744 and parameters: {'alpha': 2.4268936805528733e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,345] Trial 555 finished with value: 0.40374499582942824 and parameters: {'alpha': 1.8707638074097918e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,371] Trial 556 finished with value: 0.4037451207690028 and parameters: {'alpha': 3.144879011219963e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,395] Trial 557 finished with value: 0.40374500558927806 and parameters: {'alpha': 1.7533181683816617e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,414] Trial 558 finished with value: 0.40374450086536523 and parameters: {'alpha': 1.0133404981979762e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,435] Trial 559 finished with value: 0.403745238982459 and parameters: {'alpha': 6.407348929451174e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,456] Trial 560 finished with value: 0.4037450896378243 and parameters: {'alpha': 2.8079656553598444e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,477] Trial 561 finished with value: 0.4037447637492619 and parameters: {'alpha': 1.7227628349093023e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  11%|█▏        | 572/5000 [00:12<01:36, 46.09it/s]

[I 2026-06-14 00:48:44,499] Trial 562 finished with value: 0.40374517620515843 and parameters: {'alpha': 4.089140859394166e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,521] Trial 563 finished with value: 0.40374430338886497 and parameters: {'alpha': 1.0058233065607453e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,543] Trial 564 finished with value: 0.40374486934562437 and parameters: {'alpha': 1.7721210364663623e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,563] Trial 565 finished with value: 0.40374488523656443 and parameters: {'alpha': 1.6597648730235354e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,585] Trial 566 finished with value: 0.40374458290547244 and parameters: {'alpha': 1.0036197538208443e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,608] Trial 567 finished with value: 0.40374523650953276 and parameters: {'alpha': 3.244961523177894e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,630] Trial 568 finished with value: 0.4037448658921925 and parameters: {'alpha': 1.7142929202818255e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,650] Trial 569 finished with value: 0.4037443994027806 and parameters: {'alpha': 1.0133913368676036e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,671] Trial 570 finished with value: 0.4037452672386193 and parameters: {'alpha': 7.933038685813681e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,692] Trial 571 finished with value: 0.40374501900878246 and parameters: {'alpha': 2.9035139327005162e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  12%|█▏        | 582/5000 [00:12<01:36, 45.82it/s]

[I 2026-06-14 00:48:44,712] Trial 572 finished with value: 0.40374485043096553 and parameters: {'alpha': 1.7167835414051958e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,735] Trial 573 finished with value: 0.4037443166857173 and parameters: {'alpha': 1.0077582332432179e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,757] Trial 574 finished with value: 0.4037450411631181 and parameters: {'alpha': 2.9553786234711717e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,779] Trial 575 finished with value: 0.40374536318619997 and parameters: {'alpha': 1.9306925536599213e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,800] Trial 576 finished with value: 0.4037452755615598 and parameters: {'alpha': 5.366849570366529e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,823] Trial 577 finished with value: 0.4037448916217155 and parameters: {'alpha': 1.711784688356376e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,846] Trial 578 finished with value: 0.4037448731565854 and parameters: {'alpha': 1.7884467988400086e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,867] Trial 579 finished with value: 0.4037447021556403 and parameters: {'alpha': 1.0170533576250558e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,889] Trial 580 finished with value: 0.40374530196096803 and parameters: {'alpha': 4.3077212347942147e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,910] Trial 581 finished with value: 0.4037443540735933 and parameters: {'alpha': 1.0061876554891472e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  12%|█▏        | 592/5000 [00:12<01:35, 46.16it/s]

[I 2026-06-14 00:48:44,933] Trial 582 finished with value: 0.40374504038094305 and parameters: {'alpha': 2.6510440137107448e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,955] Trial 583 finished with value: 0.40374474598862314 and parameters: {'alpha': 1.781409003767507e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,977] Trial 584 finished with value: 0.40374452546856626 and parameters: {'alpha': 1.0155431984224318e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:44,998] Trial 585 finished with value: 0.40374499160192173 and parameters: {'alpha': 2.873415897914039e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,020] Trial 586 finished with value: 0.40374531656264406 and parameters: {'alpha': 8.224513244801692e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,043] Trial 587 finished with value: 0.40374477323136065 and parameters: {'alpha': 1.0025478124099509e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,065] Trial 588 finished with value: 0.40374508020131855 and parameters: {'alpha': 2.593074781748151e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,086] Trial 589 finished with value: 0.4037447681439065 and parameters: {'alpha': 1.7365941867756187e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,106] Trial 590 finished with value: 0.40374527365230317 and parameters: {'alpha': 4.848995447871732e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,127] Trial 591 finished with value: 0.4037454051759871 and parameters: {'alpha': 5.629430010128303e-06}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  12%|█▏        | 602/5000 [00:12<01:35, 46.29it/s]

[I 2026-06-14 00:48:45,149] Trial 592 finished with value: 0.4037447379676903 and parameters: {'alpha': 1.6950585202946206e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,172] Trial 593 finished with value: 0.4037452020793556 and parameters: {'alpha': 3.8148794098558147e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,193] Trial 594 finished with value: 0.4037546462578658 and parameters: {'alpha': 6.119520495354087}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,214] Trial 595 finished with value: 0.4037448224199656 and parameters: {'alpha': 1.6945079082775857e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,235] Trial 596 finished with value: 0.40374500563102533 and parameters: {'alpha': 2.519998286031881e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,258] Trial 597 finished with value: 0.4037448375146161 and parameters: {'alpha': 1.5896377353163032e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,277] Trial 598 finished with value: 0.40374442768121094 and parameters: {'alpha': 1.0190381255976663e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,298] Trial 599 finished with value: 0.4037452612229413 and parameters: {'alpha': 4.642983815519405e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,321] Trial 600 finished with value: 0.4037444250391479 and parameters: {'alpha': 1.0094243060556853e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,342] Trial 601 finished with value: 0.40374505326526194 and parameters: {'alpha': 2.631714877111352e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  12%|█▏        | 612/5000 [00:12<01:35, 45.79it/s]

[I 2026-06-14 00:48:45,365] Trial 602 finished with value: 0.4037448766120644 and parameters: {'alpha': 1.7096123814258323e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,388] Trial 603 finished with value: 0.4037452926935783 and parameters: {'alpha': 8.865625642098241e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,411] Trial 604 finished with value: 0.40374515495462276 and parameters: {'alpha': 3.129481269752793e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,432] Trial 605 finished with value: 0.40374443118986875 and parameters: {'alpha': 1.008683425836112e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,453] Trial 606 finished with value: 0.40374499353283594 and parameters: {'alpha': 1.9911976338687635e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,477] Trial 607 finished with value: 0.4037452813843039 and parameters: {'alpha': 4.546009455649941e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,497] Trial 608 finished with value: 0.4037444510021821 and parameters: {'alpha': 1.0044254929103695e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,520] Trial 609 finished with value: 0.40374501479959835 and parameters: {'alpha': 2.4928406987634898e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,541] Trial 610 finished with value: 0.4037447394442378 and parameters: {'alpha': 1.7208155452058785e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,562] Trial 611 finished with value: 0.4037448140500794 and parameters: {'alpha': 1.67972787323478e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  12%|█▏        | 622/5000 [00:13<01:35, 46.02it/s]

[I 2026-06-14 00:48:45,587] Trial 612 finished with value: 0.4037452589751606 and parameters: {'alpha': 5.474749508246431e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,608] Trial 613 finished with value: 0.4037443897867029 and parameters: {'alpha': 1.0243918614310524e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,629] Trial 614 finished with value: 0.4037444155367571 and parameters: {'alpha': 1.0040024763049632e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,649] Trial 615 finished with value: 0.40374507333102433 and parameters: {'alpha': 2.7836022553627146e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,670] Trial 616 finished with value: 0.5499340532960928 and parameters: {'alpha': 38670.441981728654}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,692] Trial 617 finished with value: 0.4037447406824767 and parameters: {'alpha': 1.752480859866345e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,712] Trial 618 finished with value: 0.40374533080103175 and parameters: {'alpha': 1.2278089122961467e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,734] Trial 619 finished with value: 0.40374526934273586 and parameters: {'alpha': 3.6867804015673637e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,756] Trial 620 finished with value: 0.40374494457043364 and parameters: {'alpha': 1.723561161552523e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,778] Trial 621 finished with value: 0.40374506862042386 and parameters: {'alpha': 2.602123753411038e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  13%|█▎        | 632/5000 [00:13<01:35, 45.76it/s]

[I 2026-06-14 00:48:45,802] Trial 622 finished with value: 0.4037452804077584 and parameters: {'alpha': 6.401183117599189e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,826] Trial 623 finished with value: 0.40374493378088044 and parameters: {'alpha': 1.7102592356903675e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,847] Trial 624 finished with value: 0.4037451288563546 and parameters: {'alpha': 3.2393561860421614e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,868] Trial 625 finished with value: 0.4037447794245304 and parameters: {'alpha': 1.618496420635972e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,889] Trial 626 finished with value: 0.4037443802543348 and parameters: {'alpha': 1.0044451513151376e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,912] Trial 627 finished with value: 0.4037450666903505 and parameters: {'alpha': 2.7152911621422214e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,934] Trial 628 finished with value: 0.4037449218066132 and parameters: {'alpha': 1.6574791328620624e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,956] Trial 629 finished with value: 0.4037452882726938 and parameters: {'alpha': 4.775547799239069e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,977] Trial 630 finished with value: 0.4037446017627913 and parameters: {'alpha': 1.0248484015500578e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:45,999] Trial 631 finished with value: 0.40374437529713136 and parameters: {'alpha': 1.011348829449592e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  13%|█▎        | 642/5000 [00:13<01:35, 45.84it/s]

[I 2026-06-14 00:48:46,024] Trial 632 finished with value: 0.40374505112681364 and parameters: {'alpha': 2.7560683585612513e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,045] Trial 633 finished with value: 0.4037447679815987 and parameters: {'alpha': 1.7706719546922567e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,068] Trial 634 finished with value: 0.4037444817306282 and parameters: {'alpha': 1.0096653900946741e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,090] Trial 635 finished with value: 0.4037451805482077 and parameters: {'alpha': 4.187444597594305e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,110] Trial 636 finished with value: 0.403744861593835 and parameters: {'alpha': 1.823222115130544e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,133] Trial 637 finished with value: 0.40374528438516205 and parameters: {'alpha': 7.088848997217375e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,154] Trial 638 finished with value: 0.4037449764368286 and parameters: {'alpha': 2.4617853836162658e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,175] Trial 639 finished with value: 0.4037448274290488 and parameters: {'alpha': 1.7133450814732368e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,197] Trial 640 finished with value: 0.4037446196584674 and parameters: {'alpha': 1.0186713146621428e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,217] Trial 641 finished with value: 0.40374511508714195 and parameters: {'alpha': 3.099547346177186e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  13%|█▎        | 651/5000 [00:13<01:35, 45.69it/s]

[I 2026-06-14 00:48:46,241] Trial 642 finished with value: 0.4037447776987962 and parameters: {'alpha': 1.626818004525629e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,263] Trial 643 finished with value: 0.40374472445126663 and parameters: {'alpha': 1.017560981747416e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,285] Trial 644 finished with value: 0.4037452276316794 and parameters: {'alpha': 4.231545254957561e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,306] Trial 645 finished with value: 0.4037449888985131 and parameters: {'alpha': 2.6123907196950952e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,328] Trial 646 finished with value: 0.4037453425907078 and parameters: {'alpha': 1.2058412089078702e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,350] Trial 647 finished with value: 0.4037446012768931 and parameters: {'alpha': 1.0101403038170579e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,373] Trial 648 finished with value: 0.40374449933209977 and parameters: {'alpha': 1.0018377552625467e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,396] Trial 649 finished with value: 0.40374495149205136 and parameters: {'alpha': 2.351003649875933e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,418] Trial 650 finished with value: 0.403744834489058 and parameters: {'alpha': 1.7270771782847162e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,439] Trial 651 finished with value: 0.40374528340899574 and parameters: {'alpha': 5.127713633312689e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  13%|█▎        | 662/5000 [00:14<01:35, 45.45it/s]

[I 2026-06-14 00:48:46,463] Trial 652 finished with value: 0.40374478699830957 and parameters: {'alpha': 1.76530111691602e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,484] Trial 653 finished with value: 0.40374437363505683 and parameters: {'alpha': 1.0046513983909293e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,507] Trial 654 finished with value: 0.403745202227872 and parameters: {'alpha': 3.800529963920437e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,528] Trial 655 finished with value: 0.4037449719594204 and parameters: {'alpha': 2.595953243368464e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,549] Trial 656 finished with value: 0.4037454214795923 and parameters: {'alpha': 0.022312389812912323}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,572] Trial 657 finished with value: 0.4037448916121649 and parameters: {'alpha': 1.70003580460192e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,595] Trial 658 finished with value: 0.40374527761831747 and parameters: {'alpha': 6.733854004552862e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,616] Trial 659 finished with value: 0.4037448502328692 and parameters: {'alpha': 1.7083660055560795e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,638] Trial 660 finished with value: 0.40374518032026496 and parameters: {'alpha': 3.414451981889262e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,659] Trial 661 finished with value: 0.4037446107157243 and parameters: {'alpha': 1.0078822275037696e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  13%|█▎        | 672/5000 [00:14<01:35, 45.22it/s]

[I 2026-06-14 00:48:46,683] Trial 662 finished with value: 0.40374482450464183 and parameters: {'alpha': 1.6877019672918594e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,705] Trial 663 finished with value: 0.4037450281571532 and parameters: {'alpha': 2.8801077756738466e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,726] Trial 664 finished with value: 0.4037447686628702 and parameters: {'alpha': 1.7632142412357788e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,746] Trial 665 finished with value: 0.40374527293897194 and parameters: {'alpha': 8.30746566670263e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,768] Trial 666 finished with value: 0.40374454875391136 and parameters: {'alpha': 1.0209955926654468e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,790] Trial 667 finished with value: 0.4037449608287878 and parameters: {'alpha': 2.6199659712233964e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,813] Trial 668 finished with value: 0.40374458769111154 and parameters: {'alpha': 1.0057147653302125e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,833] Trial 669 finished with value: 0.4037453103026084 and parameters: {'alpha': 5.258921010692822e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,858] Trial 670 finished with value: 0.40374489515627443 and parameters: {'alpha': 1.844259540757706e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,880] Trial 671 finished with value: 0.40374517355439554 and parameters: {'alpha': 2.995814195884053e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  14%|█▎        | 682/5000 [00:14<01:34, 45.49it/s]

[I 2026-06-14 00:48:46,903] Trial 672 finished with value: 0.40374477085069294 and parameters: {'alpha': 1.6613386079150638e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,925] Trial 673 finished with value: 0.40374540631478767 and parameters: {'alpha': 3.2341309738733476e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,947] Trial 674 finished with value: 0.40374463113590153 and parameters: {'alpha': 1.0029198974563959e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,969] Trial 675 finished with value: 0.4037451764902307 and parameters: {'alpha': 3.562854141674776e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:46,991] Trial 676 finished with value: 0.40374481822464964 and parameters: {'alpha': 1.907092741294767e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,013] Trial 677 finished with value: 0.4037449317863783 and parameters: {'alpha': 1.787648107935688e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,035] Trial 678 finished with value: 0.4037451911094006 and parameters: {'alpha': 4.0648207282749905e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,056] Trial 679 finished with value: 0.40374535777232096 and parameters: {'alpha': 1.7404621681972806e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,078] Trial 680 finished with value: 0.40374464571435464 and parameters: {'alpha': 1.0122486307855654e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,099] Trial 681 finished with value: 0.42818000287368485 and parameters: {'alpha': 2989.528677526536}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  14%|█▍        | 690/5000 [00:14<01:36, 44.55it/s]

[I 2026-06-14 00:48:47,124] Trial 682 finished with value: 0.4037449773376742 and parameters: {'alpha': 2.4001674047972857e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,146] Trial 683 finished with value: 0.4037453936940646 and parameters: {'alpha': 6.27593914208767e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,169] Trial 684 finished with value: 0.4037442632432125 and parameters: {'alpha': 1.004597246467003e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,192] Trial 685 finished with value: 0.4037452944804687 and parameters: {'alpha': 7.392668993829892e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,216] Trial 686 finished with value: 0.40374492478561047 and parameters: {'alpha': 1.658245428668528e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,243] Trial 687 finished with value: 0.40374510911487965 and parameters: {'alpha': 2.800969526571239e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,267] Trial 688 finished with value: 0.40374490651156647 and parameters: {'alpha': 1.6990018502476085e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,291] Trial 689 finished with value: 0.40374523950437996 and parameters: {'alpha': 4.6817824808044186e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,316] Trial 690 finished with value: 0.4037449042962452 and parameters: {'alpha': 1.708371751875987e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  14%|█▍        | 699/5000 [00:14<01:41, 42.45it/s]

[I 2026-06-14 00:48:47,340] Trial 691 finished with value: 0.4037446862993947 and parameters: {'alpha': 1.0079114778106446e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,366] Trial 692 finished with value: 0.40374451870252215 and parameters: {'alpha': 1.00988040558006e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,391] Trial 693 finished with value: 0.40374507339558785 and parameters: {'alpha': 2.9095075742763613e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,414] Trial 694 finished with value: 0.403744907605754 and parameters: {'alpha': 1.704097298287426e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,437] Trial 695 finished with value: 0.403745271593979 and parameters: {'alpha': 4.86798493125859e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,462] Trial 696 finished with value: 0.40374508476969523 and parameters: {'alpha': 2.6846477985231284e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,487] Trial 697 finished with value: 0.40374493288414265 and parameters: {'alpha': 1.68167749290941e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,514] Trial 698 finished with value: 0.4037448996600318 and parameters: {'alpha': 1.716964545143788e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,539] Trial 699 finished with value: 0.40374523450806377 and parameters: {'alpha': 3.6997453283802895e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  14%|█▍        | 708/5000 [00:15<01:43, 41.66it/s]

[I 2026-06-14 00:48:47,562] Trial 700 finished with value: 0.4037454026551324 and parameters: {'alpha': 1.8552472112954632e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,586] Trial 701 finished with value: 0.40374536631990154 and parameters: {'alpha': 2.885541422602781e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,611] Trial 702 finished with value: 0.4037443773731901 and parameters: {'alpha': 1.0032612579131515e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,634] Trial 703 finished with value: 0.40374497288465094 and parameters: {'alpha': 2.7888183262968916e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,660] Trial 704 finished with value: 0.4037453161203678 and parameters: {'alpha': 8.690697299019608e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,683] Trial 705 finished with value: 0.40374495627331175 and parameters: {'alpha': 1.699317565314603e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,708] Trial 706 finished with value: 0.40374466384700325 and parameters: {'alpha': 1.0293882352338344e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,734] Trial 707 finished with value: 0.4037452629090422 and parameters: {'alpha': 4.8037007690236595e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,761] Trial 708 finished with value: 0.4041549295021206 and parameters: {'alpha': 142.137240457585}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  14%|█▍        | 717/5000 [00:15<01:46, 40.11it/s]

[I 2026-06-14 00:48:47,784] Trial 709 finished with value: 0.4037446102088421 and parameters: {'alpha': 1.0015889741265604e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,809] Trial 710 finished with value: 0.40374493651023874 and parameters: {'alpha': 2.4776860806764914e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,832] Trial 711 finished with value: 0.40374470061536905 and parameters: {'alpha': 1.0070008062680725e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,860] Trial 712 finished with value: 0.4037447919771232 and parameters: {'alpha': 1.7617009976453392e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,884] Trial 713 finished with value: 0.40374504401698375 and parameters: {'alpha': 2.8982754088128047e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,909] Trial 714 finished with value: 0.40374491693757286 and parameters: {'alpha': 1.7064534483055582e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,935] Trial 715 finished with value: 0.40374528392492665 and parameters: {'alpha': 6.182186511589274e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:47,965] Trial 716 finished with value: 0.4037450248022028 and parameters: {'alpha': 2.7847408463112063e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  14%|█▍        | 724/5000 [00:15<01:48, 39.26it/s]

[I 2026-06-14 00:48:47,993] Trial 717 finished with value: 0.4037448114529493 and parameters: {'alpha': 1.707682544410924e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,020] Trial 718 finished with value: 0.4037452074921775 and parameters: {'alpha': 4.217639686261613e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,047] Trial 719 finished with value: 0.40374435906388667 and parameters: {'alpha': 1.0052655579892533e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,073] Trial 720 finished with value: 0.4037446969473181 and parameters: {'alpha': 1.6406042474277165e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,098] Trial 721 finished with value: 0.4037450404845183 and parameters: {'alpha': 2.7048362985474187e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,125] Trial 722 finished with value: 0.40374486669857734 and parameters: {'alpha': 1.67719809450869e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,149] Trial 723 finished with value: 0.40374532238064725 and parameters: {'alpha': 1.06898791573269e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,179] Trial 724 finished with value: 0.4037454066773731 and parameters: {'alpha': 0.00029522922404827547}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  15%|█▍        | 732/5000 [00:15<01:50, 38.53it/s]

[I 2026-06-14 00:48:48,206] Trial 725 finished with value: 0.4037452202587924 and parameters: {'alpha': 4.0405757147535415e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,235] Trial 726 finished with value: 0.40374472619555435 and parameters: {'alpha': 1.613877657568328e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,262] Trial 727 finished with value: 0.40374497257251485 and parameters: {'alpha': 2.5053168766046453e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,285] Trial 728 finished with value: 0.40374473930370647 and parameters: {'alpha': 1.6875965031517196e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,306] Trial 729 finished with value: 0.4037452878998785 and parameters: {'alpha': 5.944593002575466e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,327] Trial 730 finished with value: 0.40374429429286224 and parameters: {'alpha': 1.0186482159808096e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,374] Trial 731 finished with value: 0.40374438033449994 and parameters: {'alpha': 1.0073322328927592e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,405] Trial 732 finished with value: 0.40374430940347356 and parameters: {'alpha': 1.009399206648589e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  15%|█▍        | 741/5000 [00:15<01:48, 39.07it/s]

[I 2026-06-14 00:48:48,435] Trial 733 finished with value: 0.403745035284091 and parameters: {'alpha': 2.7157009681785517e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,460] Trial 734 finished with value: 0.40374506513134795 and parameters: {'alpha': 2.7433321307493144e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,487] Trial 735 finished with value: 0.40374486249914526 and parameters: {'alpha': 1.693160513015088e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,509] Trial 736 finished with value: 0.40374449509066146 and parameters: {'alpha': 1.0249062867789474e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,530] Trial 737 finished with value: 0.403745290652091 and parameters: {'alpha': 4.4435987442189197e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,551] Trial 738 finished with value: 0.40374493404919976 and parameters: {'alpha': 1.6883878513543624e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,573] Trial 739 finished with value: 0.4037451890357117 and parameters: {'alpha': 3.1980536677660244e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,595] Trial 740 finished with value: 0.40374490821248366 and parameters: {'alpha': 1.6430177863987422e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,616] Trial 741 finished with value: 0.4037452685615281 and parameters: {'alpha': 5.831281329413665e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  15%|█▌        | 750/5000 [00:16<01:44, 40.65it/s]

[I 2026-06-14 00:48:48,639] Trial 742 finished with value: 0.4037447793350845 and parameters: {'alpha': 1.7524015153050023e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,662] Trial 743 finished with value: 0.40374503345306756 and parameters: {'alpha': 2.6469373257552696e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,688] Trial 744 finished with value: 0.40374481236710713 and parameters: {'alpha': 1.6273359491776657e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,714] Trial 745 finished with value: 0.403745304193323 and parameters: {'alpha': 8.802698067994905e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,737] Trial 746 finished with value: 0.40374441993094096 and parameters: {'alpha': 1.030369331378973e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,762] Trial 747 finished with value: 0.40374519103161416 and parameters: {'alpha': 3.8702020618231744e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,784] Trial 748 finished with value: 0.4037445889260164 and parameters: {'alpha': 1.0374538857077627e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,808] Trial 749 finished with value: 0.40374444662549414 and parameters: {'alpha': 1.0011459228847777e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,831] Trial 750 finished with value: 0.40374506407311234 and parameters: {'alpha': 2.6727435774552998e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  15%|█▌        | 760/5000 [00:16<01:42, 41.45it/s]

[I 2026-06-14 00:48:48,854] Trial 751 finished with value: 0.40374490207095437 and parameters: {'alpha': 1.7711849416374902e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,881] Trial 752 finished with value: 0.4037443095034747 and parameters: {'alpha': 1.0177494651125767e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,904] Trial 753 finished with value: 0.40374508157982303 and parameters: {'alpha': 2.80460081481514e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,927] Trial 754 finished with value: 0.4037448890776163 and parameters: {'alpha': 1.7314298915475963e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,951] Trial 755 finished with value: 0.4037445169476008 and parameters: {'alpha': 1.0159751693660625e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,976] Trial 756 finished with value: 0.403746595771061 and parameters: {'alpha': 1.3431869041701054}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:48,998] Trial 757 finished with value: 0.40374524635915343 and parameters: {'alpha': 4.643191034259028e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,022] Trial 758 finished with value: 0.40374483526678634 and parameters: {'alpha': 1.7480070165792814e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,046] Trial 759 finished with value: 0.40374503975139836 and parameters: {'alpha': 2.8824859215837372e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  15%|█▌        | 768/5000 [00:16<01:42, 41.19it/s]

[I 2026-06-14 00:48:49,071] Trial 760 finished with value: 0.40374494332266936 and parameters: {'alpha': 1.7220598093678565e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,096] Trial 761 finished with value: 0.4037444733293349 and parameters: {'alpha': 1.0107430649171938e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,120] Trial 762 finished with value: 0.4037452871349326 and parameters: {'alpha': 6.05527871192941e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,145] Trial 763 finished with value: 0.4037450422833808 and parameters: {'alpha': 2.6464736862372698e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,168] Trial 764 finished with value: 0.4037446981691053 and parameters: {'alpha': 1.0049325556659284e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,193] Trial 765 finished with value: 0.40374441545722456 and parameters: {'alpha': 1.0078882223050507e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,216] Trial 766 finished with value: 0.4037453467468754 and parameters: {'alpha': 1.4230529034130192e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,239] Trial 767 finished with value: 0.4037450599439247 and parameters: {'alpha': 2.6629057815089017e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,260] Trial 768 finished with value: 0.40374483912100173 and parameters: {'alpha': 1.7219313205734506e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  16%|█▌        | 778/5000 [00:16<01:37, 43.24it/s]

[I 2026-06-14 00:48:49,284] Trial 769 finished with value: 0.40374444176320595 and parameters: {'alpha': 1.0025897252309031e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,306] Trial 770 finished with value: 0.40374525032471975 and parameters: {'alpha': 6.343115341188502e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,327] Trial 771 finished with value: 0.4037455124876059 and parameters: {'alpha': 0.1529521008524681}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,348] Trial 772 finished with value: 0.40374520974030315 and parameters: {'alpha': 3.5254678286709916e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,369] Trial 773 finished with value: 0.4037447556201113 and parameters: {'alpha': 1.82104103203893e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,391] Trial 774 finished with value: 0.4037454124624074 and parameters: {'alpha': 0.008897739676685838}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,414] Trial 775 finished with value: 0.4037445361494548 and parameters: {'alpha': 1.0094331565746715e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,436] Trial 776 finished with value: 0.403745201359202 and parameters: {'alpha': 3.6910937073658384e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,457] Trial 777 finished with value: 0.4037448380909328 and parameters: {'alpha': 1.7756454435282055e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,478] Trial 778 finished with value: 0.40374470052106626 and parameters: {'alpha': 1.0068213733484278e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  16%|█▌        | 788/5000 [00:17<01:34, 44.69it/s]

[I 2026-06-14 00:48:49,501] Trial 779 finished with value: 0.4037449643111002 and parameters: {'alpha': 2.3952520722885656e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,523] Trial 780 finished with value: 0.40374523972375 and parameters: {'alpha': 4.442534357170501e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,544] Trial 781 finished with value: 0.4037450220074987 and parameters: {'alpha': 1.868782381545384e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,566] Trial 782 finished with value: 0.403744558461211 and parameters: {'alpha': 1.0017236840525839e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,587] Trial 783 finished with value: 0.403745277992287 and parameters: {'alpha': 8.382144273044157e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,608] Trial 784 finished with value: 0.40374500798871976 and parameters: {'alpha': 2.4364139312164408e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,631] Trial 785 finished with value: 0.40374475401945853 and parameters: {'alpha': 1.8076988189373396e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,655] Trial 786 finished with value: 0.4037451788906587 and parameters: {'alpha': 3.8249315471728985e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,677] Trial 787 finished with value: 0.40374478227016447 and parameters: {'alpha': 1.634877149644558e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,698] Trial 788 finished with value: 0.4037447318319056 and parameters: {'alpha': 1.7179674833764313e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  16%|█▌        | 797/5000 [00:17<01:36, 43.74it/s]

[I 2026-06-14 00:48:49,721] Trial 789 finished with value: 0.403744489882183 and parameters: {'alpha': 1.0273753524076752e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,744] Trial 790 finished with value: 0.40374520983056644 and parameters: {'alpha': 3.873317132760005e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,768] Trial 791 finished with value: 0.4037454064388314 and parameters: {'alpha': 7.291955998541024e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,791] Trial 792 finished with value: 0.4037449817084737 and parameters: {'alpha': 2.3960735328208853e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,814] Trial 793 finished with value: 0.4037443068552196 and parameters: {'alpha': 1.0226930105013673e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,839] Trial 794 finished with value: 0.4037444873428616 and parameters: {'alpha': 1.0217444241575878e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,865] Trial 795 finished with value: 0.4037452619812839 and parameters: {'alpha': 6.738478874908902e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,894] Trial 796 finished with value: 0.4037449648895454 and parameters: {'alpha': 2.4422725578066212e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,917] Trial 797 finished with value: 0.40374497070159426 and parameters: {'alpha': 1.7729457722163648e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  16%|█▌        | 806/5000 [00:17<01:37, 43.04it/s]

[I 2026-06-14 00:48:49,942] Trial 798 finished with value: 0.4037444955965976 and parameters: {'alpha': 1.0057945411241546e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,965] Trial 799 finished with value: 0.4037452716866344 and parameters: {'alpha': 4.415654203865932e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:49,990] Trial 800 finished with value: 0.4037443849468771 and parameters: {'alpha': 1.0036836690467375e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,012] Trial 801 finished with value: 0.40374504930207045 and parameters: {'alpha': 2.8220043732613008e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,035] Trial 802 finished with value: 0.4037453417990332 and parameters: {'alpha': 1.3118306617102815e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,056] Trial 803 finished with value: 0.403744797629701 and parameters: {'alpha': 1.8252830795487545e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,078] Trial 804 finished with value: 0.4037448329039356 and parameters: {'alpha': 1.804393427766395e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,102] Trial 805 finished with value: 0.40374469612102926 and parameters: {'alpha': 1.0080596828858801e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,123] Trial 806 finished with value: 0.40374527849872816 and parameters: {'alpha': 3.998697584530733e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  16%|█▋        | 816/5000 [00:17<01:34, 44.46it/s]

[I 2026-06-14 00:48:50,144] Trial 807 finished with value: 0.40374473937927774 and parameters: {'alpha': 1.748826123125589e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,165] Trial 808 finished with value: 0.4037451952611858 and parameters: {'alpha': 3.0190779737259034e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,188] Trial 809 finished with value: 0.4037449772820988 and parameters: {'alpha': 1.7382807629477424e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,210] Trial 810 finished with value: 0.4037447172400684 and parameters: {'alpha': 1.0076540335393001e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,231] Trial 811 finished with value: 0.4037452923069598 and parameters: {'alpha': 7.560591821549397e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,253] Trial 812 finished with value: 0.4038814883813767 and parameters: {'alpha': 45.60134492006288}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,274] Trial 813 finished with value: 0.40374459384483263 and parameters: {'alpha': 1.0083848088050832e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,296] Trial 814 finished with value: 0.403745239102715 and parameters: {'alpha': 3.400885639896589e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,319] Trial 815 finished with value: 0.4037450129885049 and parameters: {'alpha': 2.5407119895139133e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,340] Trial 816 finished with value: 0.4037443629091491 and parameters: {'alpha': 1.0023682250511877e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  17%|█▋        | 826/5000 [00:17<01:33, 44.79it/s]

[I 2026-06-14 00:48:50,364] Trial 817 finished with value: 0.4037449120872834 and parameters: {'alpha': 1.842926154088877e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,385] Trial 818 finished with value: 0.4037452621137255 and parameters: {'alpha': 5.285217424100122e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,408] Trial 819 finished with value: 0.40374488923598806 and parameters: {'alpha': 1.77447294883634e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,431] Trial 820 finished with value: 0.40374446866062985 and parameters: {'alpha': 1.0060386562305468e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,454] Trial 821 finished with value: 0.4037450098238083 and parameters: {'alpha': 2.846170649282402e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,474] Trial 822 finished with value: 0.40374480899789117 and parameters: {'alpha': 1.8578089992087437e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,496] Trial 823 finished with value: 0.40374525610352713 and parameters: {'alpha': 4.4905291509862166e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,518] Trial 824 finished with value: 0.4037454058000934 and parameters: {'alpha': 1.4313761529082652e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,540] Trial 825 finished with value: 0.4037449372377568 and parameters: {'alpha': 1.74421626869601e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,562] Trial 826 finished with value: 0.4037450546419623 and parameters: {'alpha': 2.8846636748017257e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  17%|█▋        | 836/5000 [00:18<01:31, 45.35it/s]

[I 2026-06-14 00:48:50,584] Trial 827 finished with value: 0.4037447407078916 and parameters: {'alpha': 1.6778978552304833e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,605] Trial 828 finished with value: 0.40374522651439787 and parameters: {'alpha': 6.108227007108167e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,627] Trial 829 finished with value: 0.40374475568303814 and parameters: {'alpha': 1.7331543958611488e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,650] Trial 830 finished with value: 0.40374431604834404 and parameters: {'alpha': 1.0133885601871918e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,672] Trial 831 finished with value: 0.4037445169628529 and parameters: {'alpha': 1.0051219839203127e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,693] Trial 832 finished with value: 0.40374519059021724 and parameters: {'alpha': 3.221790356505124e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,714] Trial 833 finished with value: 0.4037447684013709 and parameters: {'alpha': 1.6627185649743575e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,737] Trial 834 finished with value: 0.4037450729812672 and parameters: {'alpha': 2.7972783700437414e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,760] Trial 835 finished with value: 0.40374540723135594 and parameters: {'alpha': 0.0010859471718563914}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,781] Trial 836 finished with value: 0.4037446844606876 and parameters: {'alpha': 1.013352502806878e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  17%|█▋        | 845/5000 [00:18<01:33, 44.33it/s]

[I 2026-06-14 00:48:50,803] Trial 837 finished with value: 0.40374529562871897 and parameters: {'alpha': 7.664176410773657e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,825] Trial 838 finished with value: 0.40377718255127826 and parameters: {'alpha': 14.438829981983414}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,847] Trial 839 finished with value: 0.4037446297802792 and parameters: {'alpha': 1.0004105597420408e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,870] Trial 840 finished with value: 0.4037446932897364 and parameters: {'alpha': 1.0005721709902089e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,892] Trial 841 finished with value: 0.4037450745608971 and parameters: {'alpha': 2.6438492083588996e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,917] Trial 842 finished with value: 0.4037452895724423 and parameters: {'alpha': 4.354971864461882e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,943] Trial 843 finished with value: 0.40374480819677055 and parameters: {'alpha': 1.8036961837423903e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,965] Trial 844 finished with value: 0.4037448303613779 and parameters: {'alpha': 1.8406209954997236e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:50,990] Trial 845 finished with value: 0.40374506259304405 and parameters: {'alpha': 2.8762303243759112e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  17%|█▋        | 855/5000 [00:18<01:36, 43.01it/s]

[I 2026-06-14 00:48:51,014] Trial 846 finished with value: 0.4037453351019884 and parameters: {'alpha': 1.289944133746536e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,039] Trial 847 finished with value: 0.4037448985271667 and parameters: {'alpha': 1.7436750260969397e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,061] Trial 848 finished with value: 0.4037452770031471 and parameters: {'alpha': 4.6551894966687976e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,084] Trial 849 finished with value: 0.40374475101818025 and parameters: {'alpha': 1.6692949279346555e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,110] Trial 850 finished with value: 0.40374450690365965 and parameters: {'alpha': 1.0006708488658672e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,133] Trial 851 finished with value: 0.4037450520473411 and parameters: {'alpha': 2.5829719288937626e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,158] Trial 852 finished with value: 0.4037452581031782 and parameters: {'alpha': 3.969511630519653e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,180] Trial 853 finished with value: 0.4037447257346329 and parameters: {'alpha': 1.7080525693420716e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,204] Trial 854 finished with value: 0.4037446298484708 and parameters: {'alpha': 1.0104563387174924e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  17%|█▋        | 863/5000 [00:18<01:36, 42.83it/s]

[I 2026-06-14 00:48:51,228] Trial 855 finished with value: 0.40374490169627025 and parameters: {'alpha': 1.7351412728162008e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,252] Trial 856 finished with value: 0.40374527420412526 and parameters: {'alpha': 7.249453545068585e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,276] Trial 857 finished with value: 0.4037443707807715 and parameters: {'alpha': 1.0094203370110526e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,298] Trial 858 finished with value: 0.40374463426225665 and parameters: {'alpha': 1.0012986184813198e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,322] Trial 859 finished with value: 0.40374510085827847 and parameters: {'alpha': 2.8533921401508616e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,347] Trial 860 finished with value: 0.4037451043377302 and parameters: {'alpha': 2.832942642134807e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,370] Trial 861 finished with value: 0.40374479669062563 and parameters: {'alpha': 1.7826889264885082e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,393] Trial 862 finished with value: 0.4037453133182532 and parameters: {'alpha': 5.643943204027663e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,415] Trial 863 finished with value: 0.4037448797075245 and parameters: {'alpha': 1.727480215967429e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  17%|█▋        | 872/5000 [00:18<01:35, 43.18it/s]

[I 2026-06-14 00:48:51,439] Trial 864 finished with value: 0.40374519501047307 and parameters: {'alpha': 3.804459798542982e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,463] Trial 865 finished with value: 0.4037448604136072 and parameters: {'alpha': 1.8619554277548845e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,486] Trial 866 finished with value: 0.4037450291972319 and parameters: {'alpha': 2.7159807088782107e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,508] Trial 867 finished with value: 0.4037448867422152 and parameters: {'alpha': 1.655459325273956e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,531] Trial 868 finished with value: 0.4098394881357815 and parameters: {'alpha': 1141.630085421002}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,553] Trial 869 finished with value: 0.4037448507523985 and parameters: {'alpha': 1.6003346826884643e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,576] Trial 870 finished with value: 0.403745302607484 and parameters: {'alpha': 5.0702076020595445e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,599] Trial 871 finished with value: 0.4037453576636626 and parameters: {'alpha': 2.1538904893700228e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,621] Trial 872 finished with value: 0.40374533417104336 and parameters: {'alpha': 1.0848611691424882e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  18%|█▊        | 881/5000 [00:19<01:34, 43.72it/s]

[I 2026-06-14 00:48:51,644] Trial 873 finished with value: 0.40374479356859905 and parameters: {'alpha': 1.7822194705937112e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,666] Trial 874 finished with value: 0.40374500093970933 and parameters: {'alpha': 2.907394975777203e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,690] Trial 875 finished with value: 0.4037448251362025 and parameters: {'alpha': 1.6105213650888422e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,712] Trial 876 finished with value: 0.4037444470126835 and parameters: {'alpha': 1.0037944231438995e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,734] Trial 877 finished with value: 0.40374469364492005 and parameters: {'alpha': 1.0167790196280068e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,757] Trial 878 finished with value: 0.4037452440003582 and parameters: {'alpha': 3.917628111449201e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,779] Trial 879 finished with value: 0.4037445950410629 and parameters: {'alpha': 1.023541517495071e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,802] Trial 880 finished with value: 0.4037449770998156 and parameters: {'alpha': 2.5721892372411306e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,825] Trial 881 finished with value: 0.403745035143824 and parameters: {'alpha': 2.7922154096159183e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  18%|█▊        | 890/5000 [00:19<01:35, 43.00it/s]

[I 2026-06-14 00:48:51,848] Trial 882 finished with value: 0.4037443018982986 and parameters: {'alpha': 1.0048453742318984e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,870] Trial 883 finished with value: 0.40374478849105616 and parameters: {'alpha': 1.698408385886001e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,894] Trial 884 finished with value: 0.4037452747000471 and parameters: {'alpha': 6.932875296625199e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,920] Trial 885 finished with value: 0.40374483627333774 and parameters: {'alpha': 1.674027391236805e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,943] Trial 886 finished with value: 0.4037452254540508 and parameters: {'alpha': 4.389879378579017e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,965] Trial 887 finished with value: 0.40374458526438584 and parameters: {'alpha': 1.0324757252993056e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:51,990] Trial 888 finished with value: 0.4037444061605573 and parameters: {'alpha': 1.0163234661242952e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,014] Trial 889 finished with value: 0.4037450039123064 and parameters: {'alpha': 2.6110017557695988e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,038] Trial 890 finished with value: 0.40374495443271763 and parameters: {'alpha': 1.7336254203690098e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  18%|█▊        | 900/5000 [00:19<01:35, 42.88it/s]

[I 2026-06-14 00:48:52,060] Trial 891 finished with value: 0.4037445117159366 and parameters: {'alpha': 1.0141584631830812e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,085] Trial 892 finished with value: 0.4037450480223227 and parameters: {'alpha': 2.7266375116726065e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,107] Trial 893 finished with value: 0.4037452675037053 and parameters: {'alpha': 4.0667145530174643e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,130] Trial 894 finished with value: 0.4037447834529999 and parameters: {'alpha': 1.726515260319286e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,154] Trial 895 finished with value: 0.40374530981933193 and parameters: {'alpha': 9.759595645900847e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,177] Trial 896 finished with value: 0.4037450108014355 and parameters: {'alpha': 2.7190415854090625e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,200] Trial 897 finished with value: 0.4037448508651528 and parameters: {'alpha': 1.8664733188905324e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,225] Trial 898 finished with value: 0.40374527475557437 and parameters: {'alpha': 5.0868159467436525e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,247] Trial 899 finished with value: 0.40374457931382224 and parameters: {'alpha': 1.007708549324981e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  18%|█▊        | 908/5000 [00:19<01:35, 42.86it/s]

[I 2026-06-14 00:48:52,273] Trial 900 finished with value: 0.40374477019932253 and parameters: {'alpha': 1.844448193766707e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,297] Trial 901 finished with value: 0.40374506440766855 and parameters: {'alpha': 2.8242548001616263e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,321] Trial 902 finished with value: 0.4037442980787611 and parameters: {'alpha': 1.0273659376213635e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,342] Trial 903 finished with value: 0.40374478850586193 and parameters: {'alpha': 1.700125214895163e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,365] Trial 904 finished with value: 0.4037452368747909 and parameters: {'alpha': 4.684696114040395e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,389] Trial 905 finished with value: 0.40374471973367465 and parameters: {'alpha': 1.6589546516280944e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,411] Trial 906 finished with value: 0.4037447147055409 and parameters: {'alpha': 1.0085271153671044e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,433] Trial 907 finished with value: 0.403744519091095 and parameters: {'alpha': 1.020376131608551e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,457] Trial 908 finished with value: 0.40374501066063184 and parameters: {'alpha': 2.8271066454758506e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  18%|█▊        | 917/5000 [00:20<01:34, 43.41it/s]

[I 2026-06-14 00:48:52,480] Trial 909 finished with value: 0.4037450221966619 and parameters: {'alpha': 2.6535044732328417e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,505] Trial 910 finished with value: 0.40374530177546036 and parameters: {'alpha': 8.25472189572299e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,526] Trial 911 finished with value: 0.4037447173188402 and parameters: {'alpha': 1.6888773056973382e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,549] Trial 912 finished with value: 0.4037452484538188 and parameters: {'alpha': 4.4627263594099116e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,571] Trial 913 finished with value: 0.40374425166415373 and parameters: {'alpha': 1.0065343097140491e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,593] Trial 914 finished with value: 0.4037443787867802 and parameters: {'alpha': 1.0133820054981066e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,616] Trial 915 finished with value: 0.4037449438612864 and parameters: {'alpha': 1.770572519189202e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,639] Trial 916 finished with value: 0.4037450686368647 and parameters: {'alpha': 2.7467041712209562e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,661] Trial 917 finished with value: 0.4037449240864533 and parameters: {'alpha': 1.69939325886006e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  19%|█▊        | 926/5000 [00:20<01:35, 42.67it/s]

[I 2026-06-14 00:48:52,683] Trial 918 finished with value: 0.40374521059748275 and parameters: {'alpha': 3.758234007043361e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,710] Trial 919 finished with value: 0.4037449532574467 and parameters: {'alpha': 1.7164705207195102e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,733] Trial 920 finished with value: 0.40374472766694713 and parameters: {'alpha': 1.65902979856291e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,757] Trial 921 finished with value: 0.40374440038606124 and parameters: {'alpha': 1.0312636281719185e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,783] Trial 922 finished with value: 0.4037452757395174 and parameters: {'alpha': 6.777569803119188e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,807] Trial 923 finished with value: 0.40374471332375406 and parameters: {'alpha': 1.013899624319342e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,830] Trial 924 finished with value: 0.40374514521743377 and parameters: {'alpha': 3.010765861105806e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,855] Trial 925 finished with value: 0.40374499876364184 and parameters: {'alpha': 2.8450708018993494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,879] Trial 926 finished with value: 0.40374430168424275 and parameters: {'alpha': 1.0167262025771667e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  19%|█▊        | 935/5000 [00:20<01:35, 42.51it/s]

[I 2026-06-14 00:48:52,905] Trial 927 finished with value: 0.4037448772746004 and parameters: {'alpha': 1.7946266115730865e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,929] Trial 928 finished with value: 0.40374528599853887 and parameters: {'alpha': 5.1376335174547974e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,952] Trial 929 finished with value: 0.47994935378847775 and parameters: {'alpha': 9194.593338947649}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,976] Trial 930 finished with value: 0.4037443825891857 and parameters: {'alpha': 1.0231585467424074e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:52,999] Trial 931 finished with value: 0.4037449808027906 and parameters: {'alpha': 2.5532920383102856e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,022] Trial 932 finished with value: 0.40374472660840416 and parameters: {'alpha': 1.6084412910117734e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,044] Trial 933 finished with value: 0.40374455632402834 and parameters: {'alpha': 1.0103102655462587e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,067] Trial 934 finished with value: 0.4037451885343922 and parameters: {'alpha': 4.0875383790476776e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,091] Trial 935 finished with value: 0.4037449304697737 and parameters: {'alpha': 1.7624657233106588e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  19%|█▉        | 945/5000 [00:20<01:33, 43.28it/s]

[I 2026-06-14 00:48:53,113] Trial 936 finished with value: 0.40374494714168185 and parameters: {'alpha': 2.5551104828882535e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,135] Trial 937 finished with value: 0.40374531108301115 and parameters: {'alpha': 1.1759361567463986e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,159] Trial 938 finished with value: 0.4037454039799068 and parameters: {'alpha': 3.4526242859502868e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,180] Trial 939 finished with value: 0.40374474044266556 and parameters: {'alpha': 1.0248089618586696e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,204] Trial 940 finished with value: 0.4037449312567542 and parameters: {'alpha': 1.7548506816789198e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,226] Trial 941 finished with value: 0.4037445079947981 and parameters: {'alpha': 1.0075249537885204e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,248] Trial 942 finished with value: 0.4037452599768487 and parameters: {'alpha': 4.619495836425746e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,272] Trial 943 finished with value: 0.40374500783802136 and parameters: {'alpha': 2.5922025692030302e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,294] Trial 944 finished with value: 0.4037448535392677 and parameters: {'alpha': 1.6895366829380616e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  19%|█▉        | 953/5000 [00:20<01:33, 43.19it/s]

[I 2026-06-14 00:48:53,318] Trial 945 finished with value: 0.40374517863703635 and parameters: {'alpha': 3.0349129632461146e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,340] Trial 946 finished with value: 0.4037452707321769 and parameters: {'alpha': 6.071861803956183e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,363] Trial 947 finished with value: 0.40374475021051665 and parameters: {'alpha': 1.7001953901929388e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,388] Trial 948 finished with value: 0.4037442928249426 and parameters: {'alpha': 1.0041928634000854e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,410] Trial 949 finished with value: 0.4037448655448641 and parameters: {'alpha': 1.7639673024457106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,433] Trial 950 finished with value: 0.40447156989894467 and parameters: {'alpha': 251.20416327868045}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,457] Trial 951 finished with value: 0.40374501119687106 and parameters: {'alpha': 2.9350279176455602e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,479] Trial 952 finished with value: 0.40374538110211705 and parameters: {'alpha': 3.927037278003649e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,502] Trial 953 finished with value: 0.4037448566542458 and parameters: {'alpha': 1.6652146458431098e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  19%|█▉        | 962/5000 [00:21<01:33, 43.19it/s]

[I 2026-06-14 00:48:53,526] Trial 954 finished with value: 0.4037452490970271 and parameters: {'alpha': 4.613946692358105e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,552] Trial 955 finished with value: 0.40374489100786676 and parameters: {'alpha': 1.6963478618013977e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,574] Trial 956 finished with value: 0.40374507735518506 and parameters: {'alpha': 2.7969550950848763e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,598] Trial 957 finished with value: 0.4037446105366088 and parameters: {'alpha': 1.0090767139276365e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,620] Trial 958 finished with value: 0.4037449506017495 and parameters: {'alpha': 1.741389809432891e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,643] Trial 959 finished with value: 0.4037444747267524 and parameters: {'alpha': 1.0047420245509931e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,666] Trial 960 finished with value: 0.40374459258647916 and parameters: {'alpha': 1.0184517625966035e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,690] Trial 961 finished with value: 0.40374531800527097 and parameters: {'alpha': 8.542720770599244e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,713] Trial 962 finished with value: 0.403745229425095 and parameters: {'alpha': 4.113097388702084e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  19%|█▉        | 971/5000 [00:21<01:33, 43.27it/s]

[I 2026-06-14 00:48:53,736] Trial 963 finished with value: 0.40374508706129236 and parameters: {'alpha': 2.7344790162287688e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,759] Trial 964 finished with value: 0.4037447836684903 and parameters: {'alpha': 1.7131543499717378e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,783] Trial 965 finished with value: 0.40374441213829687 and parameters: {'alpha': 1.0093611210129436e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,806] Trial 966 finished with value: 0.403744676213889 and parameters: {'alpha': 1.0085017647529657e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,828] Trial 967 finished with value: 0.40374510290893867 and parameters: {'alpha': 2.695595700481973e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,850] Trial 968 finished with value: 0.4037453035046945 and parameters: {'alpha': 5.9564432260605444e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,874] Trial 969 finished with value: 0.4037449927183976 and parameters: {'alpha': 2.606905625300563e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,897] Trial 970 finished with value: 0.4037454423466088 and parameters: {'alpha': 0.0530127296928313}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,919] Trial 971 finished with value: 0.40374493078033735 and parameters: {'alpha': 1.7905459005463516e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  20%|█▉        | 980/5000 [00:21<01:32, 43.48it/s]

[I 2026-06-14 00:48:53,943] Trial 972 finished with value: 0.403745271948027 and parameters: {'alpha': 4.247590253928392e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,967] Trial 973 finished with value: 0.403744786950022 and parameters: {'alpha': 1.7929388456147643e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:53,990] Trial 974 finished with value: 0.4037447491112865 and parameters: {'alpha': 1.71268352901169e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,015] Trial 975 finished with value: 0.4037445826805079 and parameters: {'alpha': 1.0201727471862624e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,037] Trial 976 finished with value: 0.4037453523884022 and parameters: {'alpha': 1.4550021213493812e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,059] Trial 977 finished with value: 0.4037450813013329 and parameters: {'alpha': 2.979297899095867e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,082] Trial 978 finished with value: 0.403744861013366 and parameters: {'alpha': 1.6865429177739372e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,104] Trial 979 finished with value: 0.403745247954431 and parameters: {'alpha': 4.118287816287553e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,127] Trial 980 finished with value: 0.40374530727525093 and parameters: {'alpha': 8.304023602844554e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  20%|█▉        | 990/5000 [00:21<01:32, 43.46it/s]

[I 2026-06-14 00:48:54,149] Trial 981 finished with value: 0.40374489447212836 and parameters: {'alpha': 1.7425033902249496e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,173] Trial 982 finished with value: 0.4037447265496953 and parameters: {'alpha': 1.00081265193636e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,196] Trial 983 finished with value: 0.40374447903859845 and parameters: {'alpha': 1.0186725935756215e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,219] Trial 984 finished with value: 0.4037450782233884 and parameters: {'alpha': 2.761552477144887e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,242] Trial 985 finished with value: 0.4037445540579897 and parameters: {'alpha': 1.0213795253488445e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,265] Trial 986 finished with value: 0.4037443508323041 and parameters: {'alpha': 1.0018000594351924e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,289] Trial 987 finished with value: 0.40374502420533126 and parameters: {'alpha': 2.5667989721105203e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,312] Trial 988 finished with value: 0.4037452312065668 and parameters: {'alpha': 6.05146315131406e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,333] Trial 989 finished with value: 0.40374451934468314 and parameters: {'alpha': 1.003080534068545e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  20%|█▉        | 998/5000 [00:21<01:31, 43.57it/s]

[I 2026-06-14 00:48:54,358] Trial 990 finished with value: 0.40374500646971545 and parameters: {'alpha': 2.5188886881292947e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,380] Trial 991 finished with value: 0.4037447773733016 and parameters: {'alpha': 1.7585048481802538e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,403] Trial 992 finished with value: 0.4037444930655847 and parameters: {'alpha': 1.0030920906959416e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,425] Trial 993 finished with value: 0.40374526658905063 and parameters: {'alpha': 4.921416946974454e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,448] Trial 994 finished with value: 0.40374506507831287 and parameters: {'alpha': 2.582722511423789e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,471] Trial 995 finished with value: 0.4037447712661276 and parameters: {'alpha': 1.6989306701343428e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,495] Trial 996 finished with value: 0.4037452067023298 and parameters: {'alpha': 4.25673936964414e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,517] Trial 997 finished with value: 0.4037448528001947 and parameters: {'alpha': 1.836324420035779e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,539] Trial 998 finished with value: 0.40374471355098746 and parameters: {'alpha': 1.006891944337466e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  20%|██        | 1007/5000 [00:22<01:31, 43.68it/s]

[I 2026-06-14 00:48:54,561] Trial 999 finished with value: 0.40374507940627663 and parameters: {'alpha': 2.738739935472364e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,585] Trial 1000 finished with value: 0.4037449447660796 and parameters: {'alpha': 1.8016829240924126e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,608] Trial 1001 finished with value: 0.4037452289120307 and parameters: {'alpha': 3.8671083406093495e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,631] Trial 1002 finished with value: 0.4037449868240533 and parameters: {'alpha': 1.8022461556960885e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,654] Trial 1003 finished with value: 0.40374483942118244 and parameters: {'alpha': 1.683036779732088e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,676] Trial 1004 finished with value: 0.40374426243837186 and parameters: {'alpha': 1.0111254536921675e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,700] Trial 1005 finished with value: 0.4037443582994797 and parameters: {'alpha': 1.0066542524507776e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,723] Trial 1006 finished with value: 0.40374529816192967 and parameters: {'alpha': 8.439737391282617e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,746] Trial 1007 finished with value: 0.40374511569446886 and parameters: {'alpha': 3.320013506130486e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  20%|██        | 1016/5000 [00:22<01:31, 43.74it/s]

[I 2026-06-14 00:48:54,768] Trial 1008 finished with value: 0.40374483418487883 and parameters: {'alpha': 1.7569876146910266e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,791] Trial 1009 finished with value: 0.40374508845768453 and parameters: {'alpha': 2.8227647018603474e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,814] Trial 1010 finished with value: 0.40374526924691395 and parameters: {'alpha': 5.0674850709370056e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,836] Trial 1011 finished with value: 0.4037448259191262 and parameters: {'alpha': 1.7192492955220896e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,860] Trial 1012 finished with value: 0.4037449630094457 and parameters: {'alpha': 1.6817537274916163e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,881] Trial 1013 finished with value: 0.40374519271497133 and parameters: {'alpha': 3.1903537284125966e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,904] Trial 1014 finished with value: 0.4037446904604934 and parameters: {'alpha': 1.0272947727349814e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,927] Trial 1015 finished with value: 0.4037443108420247 and parameters: {'alpha': 1.0033346214402415e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,950] Trial 1016 finished with value: 0.40374492775779386 and parameters: {'alpha': 1.7975238293727058e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  20%|██        | 1025/5000 [00:22<01:32, 43.20it/s]

[I 2026-06-14 00:48:54,974] Trial 1017 finished with value: 0.4037452947105783 and parameters: {'alpha': 7.738051178967515e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:54,998] Trial 1018 finished with value: 0.40374504207289696 and parameters: {'alpha': 2.900300122171562e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,021] Trial 1019 finished with value: 0.4037449666287609 and parameters: {'alpha': 1.851772499893504e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,045] Trial 1020 finished with value: 0.403745240518862 and parameters: {'alpha': 4.0484775415252826e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,068] Trial 1021 finished with value: 0.4037446555637161 and parameters: {'alpha': 1.0341823440396362e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,091] Trial 1022 finished with value: 0.4037453698028754 and parameters: {'alpha': 2.3204295867702175e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,114] Trial 1023 finished with value: 0.40374475548493555 and parameters: {'alpha': 1.752288860180934e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,138] Trial 1024 finished with value: 0.40374476310284374 and parameters: {'alpha': 1.7484209608526945e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,162] Trial 1025 finished with value: 0.4037450192189757 and parameters: {'alpha': 2.8583446471481463e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  21%|██        | 1035/5000 [00:22<01:31, 43.20it/s]

[I 2026-06-14 00:48:55,186] Trial 1026 finished with value: 0.40374429702696235 and parameters: {'alpha': 1.0227201232758347e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,209] Trial 1027 finished with value: 0.40374526848279285 and parameters: {'alpha': 5.739874804150106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,231] Trial 1028 finished with value: 0.40374472624947305 and parameters: {'alpha': 1.6454476493470416e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,254] Trial 1029 finished with value: 0.40374448838884147 and parameters: {'alpha': 1.0167133257789981e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,278] Trial 1030 finished with value: 0.40374433655935477 and parameters: {'alpha': 1.0048124547293056e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,301] Trial 1031 finished with value: 0.40374436250043905 and parameters: {'alpha': 1.0070750165270729e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,323] Trial 1032 finished with value: 0.40374509310299483 and parameters: {'alpha': 2.705762736594459e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,345] Trial 1033 finished with value: 0.4037444473776204 and parameters: {'alpha': 1.0045249044066616e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,369] Trial 1034 finished with value: 0.4037452826221421 and parameters: {'alpha': 4.72363788154989e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  21%|██        | 1043/5000 [00:22<01:31, 43.46it/s]

[I 2026-06-14 00:48:55,393] Trial 1035 finished with value: 0.40374494808222183 and parameters: {'alpha': 2.5708059953571494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,416] Trial 1036 finished with value: 0.4037449638253493 and parameters: {'alpha': 1.8925811146362197e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,439] Trial 1037 finished with value: 0.4037459002078621 and parameters: {'alpha': 0.638323967425297}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,461] Trial 1038 finished with value: 0.4037453111785867 and parameters: {'alpha': 1.1380206508611772e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,483] Trial 1039 finished with value: 0.40374522729740403 and parameters: {'alpha': 3.872602207239038e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,508] Trial 1040 finished with value: 0.40374495327016036 and parameters: {'alpha': 1.7305402042865334e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,531] Trial 1041 finished with value: 0.40374500389389884 and parameters: {'alpha': 2.7103982861334496e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,553] Trial 1042 finished with value: 0.40374476901652806 and parameters: {'alpha': 1.744919946128902e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,576] Trial 1043 finished with value: 0.4037453161274579 and parameters: {'alpha': 5.441244843754985e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  21%|██        | 1052/5000 [00:23<01:31, 43.16it/s]

[I 2026-06-14 00:48:55,599] Trial 1044 finished with value: 0.4037448738299737 and parameters: {'alpha': 1.7870870439442834e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,623] Trial 1045 finished with value: 0.4037450385932077 and parameters: {'alpha': 2.6841701644216004e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,645] Trial 1046 finished with value: 0.40374476404946724 and parameters: {'alpha': 1.8024774849552693e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,670] Trial 1047 finished with value: 0.4037445875860273 and parameters: {'alpha': 1.0021570544293246e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,692] Trial 1048 finished with value: 0.40374521194262186 and parameters: {'alpha': 3.922529981309719e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,716] Trial 1049 finished with value: 0.4037448735332062 and parameters: {'alpha': 1.6818316893346744e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,741] Trial 1050 finished with value: 0.4037452750546826 and parameters: {'alpha': 8.265947537332289e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,763] Trial 1051 finished with value: 0.4037447146025195 and parameters: {'alpha': 1.005221956540293e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,786] Trial 1052 finished with value: 0.40374467251683027 and parameters: {'alpha': 1.0252377114575234e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  21%|██        | 1061/5000 [00:23<01:31, 42.95it/s]

[I 2026-06-14 00:48:55,810] Trial 1053 finished with value: 0.40374499217658605 and parameters: {'alpha': 2.649420813761261e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,835] Trial 1054 finished with value: 0.4037449410321258 and parameters: {'alpha': 1.6851429146199942e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,858] Trial 1055 finished with value: 0.40374520606826236 and parameters: {'alpha': 3.041418354593624e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,881] Trial 1056 finished with value: 0.4037452580242908 and parameters: {'alpha': 5.3573996228938956e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,905] Trial 1057 finished with value: 0.40374483672851447 and parameters: {'alpha': 1.713314759080525e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,929] Trial 1058 finished with value: 0.40374471047205923 and parameters: {'alpha': 1.0283370665204966e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,952] Trial 1059 finished with value: 0.4037447583883615 and parameters: {'alpha': 1.0139476346310521e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:55,977] Trial 1060 finished with value: 0.403747809861634 and parameters: {'alpha': 2.3278756722303697}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,001] Trial 1061 finished with value: 0.4037450678373283 and parameters: {'alpha': 2.854499240680274e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  21%|██▏       | 1070/5000 [00:23<01:32, 42.53it/s]

[I 2026-06-14 00:48:56,025] Trial 1062 finished with value: 0.40374439371821236 and parameters: {'alpha': 1.0034533696183058e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,047] Trial 1063 finished with value: 0.40374526058979004 and parameters: {'alpha': 3.8431504279203e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,072] Trial 1064 finished with value: 0.40374498372088496 and parameters: {'alpha': 1.7881398481804832e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,096] Trial 1065 finished with value: 0.403745060599626 and parameters: {'alpha': 2.6045867232468753e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,120] Trial 1066 finished with value: 0.4037448229184667 and parameters: {'alpha': 1.6498363945905382e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,143] Trial 1067 finished with value: 0.40374532880499814 and parameters: {'alpha': 8.59206228167183e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,166] Trial 1068 finished with value: 0.40374467298948036 and parameters: {'alpha': 1.0085379111835313e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,188] Trial 1069 finished with value: 0.40374528610483007 and parameters: {'alpha': 4.071801212155059e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,212] Trial 1070 finished with value: 0.40374486296708034 and parameters: {'alpha': 1.7029727671215063e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  22%|██▏       | 1080/5000 [00:23<01:31, 42.87it/s]

[I 2026-06-14 00:48:56,235] Trial 1071 finished with value: 0.40374495802448485 and parameters: {'alpha': 2.6674010787156877e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,258] Trial 1072 finished with value: 0.4037446513319912 and parameters: {'alpha': 1.0023932823260068e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,281] Trial 1073 finished with value: 0.40374441006527556 and parameters: {'alpha': 1.0107879511925246e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,304] Trial 1074 finished with value: 0.40374503659256594 and parameters: {'alpha': 2.5483159393167887e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,329] Trial 1075 finished with value: 0.40374525265954675 and parameters: {'alpha': 6.877323637498767e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,352] Trial 1076 finished with value: 0.40374477862959307 and parameters: {'alpha': 1.758742255355202e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,375] Trial 1077 finished with value: 0.403745264844752 and parameters: {'alpha': 4.383936613759832e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,397] Trial 1078 finished with value: 0.40374431970731106 and parameters: {'alpha': 1.0174868539331185e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,420] Trial 1079 finished with value: 0.4037453367156252 and parameters: {'alpha': 1.3925547417530425e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  22%|██▏       | 1088/5000 [00:23<01:30, 43.05it/s]

[I 2026-06-14 00:48:56,444] Trial 1080 finished with value: 0.4037449862146451 and parameters: {'alpha': 1.8259197979640185e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,466] Trial 1081 finished with value: 0.4037450249624608 and parameters: {'alpha': 2.7498516369369596e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,489] Trial 1082 finished with value: 0.4037448583241004 and parameters: {'alpha': 1.791501800530641e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,512] Trial 1083 finished with value: 0.4037447628551856 and parameters: {'alpha': 1.0100459876181677e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,534] Trial 1084 finished with value: 0.4037442824171986 and parameters: {'alpha': 1.0022511688892458e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,559] Trial 1085 finished with value: 0.4037452321669418 and parameters: {'alpha': 4.4285559909715416e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,581] Trial 1086 finished with value: 0.40374493507300985 and parameters: {'alpha': 1.928332777340978e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,604] Trial 1087 finished with value: 0.4037450090069395 and parameters: {'alpha': 2.819983884602741e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,627] Trial 1088 finished with value: 0.4037449378559194 and parameters: {'alpha': 1.636514860230272e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  22%|██▏       | 1097/5000 [00:24<01:31, 42.81it/s]

[I 2026-06-14 00:48:56,651] Trial 1089 finished with value: 0.40374463449788733 and parameters: {'alpha': 1.001258504778794e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,676] Trial 1090 finished with value: 0.4037453196646312 and parameters: {'alpha': 5.812520378037483e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,701] Trial 1091 finished with value: 0.40374465193221154 and parameters: {'alpha': 1.0046340101781325e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,724] Trial 1092 finished with value: 0.40374499764876937 and parameters: {'alpha': 2.7100639090557864e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,746] Trial 1093 finished with value: 0.4037447932808972 and parameters: {'alpha': 1.7274069494159913e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,769] Trial 1094 finished with value: 0.4037452560009398 and parameters: {'alpha': 4.1416844938279184e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,794] Trial 1095 finished with value: 0.4037449775702224 and parameters: {'alpha': 1.7519704770965444e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,817] Trial 1096 finished with value: 0.4037442916605441 and parameters: {'alpha': 1.0034969965593003e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,839] Trial 1097 finished with value: 0.5449085347004997 and parameters: {'alpha': 33678.84295289634}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  22%|██▏       | 1106/5000 [00:24<01:31, 42.57it/s]

[I 2026-06-14 00:48:56,861] Trial 1098 finished with value: 0.4037451180868794 and parameters: {'alpha': 2.9394182820042742e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,885] Trial 1099 finished with value: 0.4037446568477907 and parameters: {'alpha': 1.0020567323370437e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,909] Trial 1100 finished with value: 0.4037449516529675 and parameters: {'alpha': 1.939555136978219e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,932] Trial 1101 finished with value: 0.40374528955240424 and parameters: {'alpha': 6.70063463288542e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,956] Trial 1102 finished with value: 0.40374479494576687 and parameters: {'alpha': 1.7209568273639514e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:56,981] Trial 1103 finished with value: 0.4037451759328228 and parameters: {'alpha': 3.582402924409613e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,005] Trial 1104 finished with value: 0.40374476223083616 and parameters: {'alpha': 1.7002605718973156e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,030] Trial 1105 finished with value: 0.4037452019636243 and parameters: {'alpha': 3.024449448098014e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,054] Trial 1106 finished with value: 0.4037449148981258 and parameters: {'alpha': 1.8077305743491767e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  22%|██▏       | 1113/5000 [00:24<01:38, 39.64it/s]

[I 2026-06-14 00:48:57,079] Trial 1107 finished with value: 0.4037444555106794 and parameters: {'alpha': 1.0082461588698988e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,102] Trial 1108 finished with value: 0.403745198794864 and parameters: {'alpha': 4.2507831036466557e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,149] Trial 1109 finished with value: 0.4037442771121361 and parameters: {'alpha': 1.0114951673426324e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,184] Trial 1110 finished with value: 0.40374501166063853 and parameters: {'alpha': 2.605061018744519e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,215] Trial 1111 finished with value: 0.4037453233235336 and parameters: {'alpha': 1.1523546606764888e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,246] Trial 1112 finished with value: 0.4037447459419999 and parameters: {'alpha': 1.751230973917673e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,271] Trial 1113 finished with value: 0.403744754224021 and parameters: {'alpha': 1.7288765956589292e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  22%|██▏       | 1122/5000 [00:24<01:39, 38.83it/s]

[I 2026-06-14 00:48:57,295] Trial 1114 finished with value: 0.4037446943886499 and parameters: {'alpha': 1.0084558086299151e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,319] Trial 1115 finished with value: 0.40374528156106954 and parameters: {'alpha': 6.034200980063674e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,342] Trial 1116 finished with value: 0.4037451593786568 and parameters: {'alpha': 3.571231047715537e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,367] Trial 1117 finished with value: 0.4037449487558933 and parameters: {'alpha': 1.682803235524148e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,392] Trial 1118 finished with value: 0.4037443685793882 and parameters: {'alpha': 1.0012639903371692e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,418] Trial 1119 finished with value: 0.40374539902289186 and parameters: {'alpha': 1.294230926334471e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,442] Trial 1120 finished with value: 0.4037449722900223 and parameters: {'alpha': 2.669249094317988e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,467] Trial 1121 finished with value: 0.4037447833068722 and parameters: {'alpha': 1.7170627535068548e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,491] Trial 1122 finished with value: 0.4037450182266503 and parameters: {'alpha': 2.894168171072729e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  23%|██▎       | 1131/5000 [00:25<01:37, 39.53it/s]

[I 2026-06-14 00:48:57,515] Trial 1123 finished with value: 0.4037454079992533 and parameters: {'alpha': 0.0022300740193640363}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,540] Trial 1124 finished with value: 0.4037447384599301 and parameters: {'alpha': 1.6953056949026243e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,565] Trial 1125 finished with value: 0.4037452679084877 and parameters: {'alpha': 5.8522947863189816e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,590] Trial 1126 finished with value: 0.4037443133657685 and parameters: {'alpha': 1.0085861696257764e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,613] Trial 1127 finished with value: 0.4037450755955542 and parameters: {'alpha': 2.7161886498780422e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,638] Trial 1128 finished with value: 0.40374478548882214 and parameters: {'alpha': 1.6929532654051743e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,663] Trial 1129 finished with value: 0.40374525873360273 and parameters: {'alpha': 4.106321653614689e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,690] Trial 1130 finished with value: 0.40374486455054104 and parameters: {'alpha': 1.7530278386381558e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,715] Trial 1131 finished with value: 0.4037450018296849 and parameters: {'alpha': 2.839599575434469e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  23%|██▎       | 1140/5000 [00:25<01:34, 40.76it/s]

[I 2026-06-14 00:48:57,740] Trial 1132 finished with value: 0.40374472451323895 and parameters: {'alpha': 1.0221106719733259e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,763] Trial 1133 finished with value: 0.4037449267973853 and parameters: {'alpha': 1.763285876565718e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,787] Trial 1134 finished with value: 0.4037452944123009 and parameters: {'alpha': 7.015761733688635e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,811] Trial 1135 finished with value: 0.4037450485184762 and parameters: {'alpha': 2.544729988826578e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,834] Trial 1136 finished with value: 0.5724552792277107 and parameters: {'alpha': 92575.91600304043}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,857] Trial 1137 finished with value: 0.403744792429571 and parameters: {'alpha': 1.659400616136929e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,881] Trial 1138 finished with value: 0.40374471417623997 and parameters: {'alpha': 1.0231875689911449e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,904] Trial 1139 finished with value: 0.40374518838498236 and parameters: {'alpha': 3.8304345881594007e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,929] Trial 1140 finished with value: 0.40374479613477954 and parameters: {'alpha': 1.592311767650912e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  23%|██▎       | 1150/5000 [00:25<01:34, 40.62it/s]

[I 2026-06-14 00:48:57,953] Trial 1141 finished with value: 0.4037450216153851 and parameters: {'alpha': 2.6446523447692993e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:57,977] Trial 1142 finished with value: 0.4037447615002128 and parameters: {'alpha': 1.6824290120176408e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,003] Trial 1143 finished with value: 0.40374533765121706 and parameters: {'alpha': 1.2918597325901877e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,026] Trial 1144 finished with value: 0.40374527425288464 and parameters: {'alpha': 4.812468853629407e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,053] Trial 1145 finished with value: 0.4037446947876141 and parameters: {'alpha': 1.0159155929575373e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,077] Trial 1146 finished with value: 0.40374463866532956 and parameters: {'alpha': 1.0239780768735689e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,103] Trial 1147 finished with value: 0.4037445087999897 and parameters: {'alpha': 1.0031187276125763e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,127] Trial 1148 finished with value: 0.40374429081160335 and parameters: {'alpha': 1.0070337935981163e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,151] Trial 1149 finished with value: 0.4037449605497309 and parameters: {'alpha': 2.5706568229112914e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  23%|██▎       | 1158/5000 [00:25<01:34, 40.46it/s]

[I 2026-06-14 00:48:58,176] Trial 1150 finished with value: 0.40374530445007967 and parameters: {'alpha': 7.419828018756704e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,200] Trial 1151 finished with value: 0.40374450908756343 and parameters: {'alpha': 1.0092621309284167e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,225] Trial 1152 finished with value: 0.4037450495051443 and parameters: {'alpha': 2.6127443049901634e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,250] Trial 1153 finished with value: 0.40374491283955327 and parameters: {'alpha': 1.731550220807183e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,276] Trial 1154 finished with value: 0.4037452729242739 and parameters: {'alpha': 4.2742848750466287e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,300] Trial 1155 finished with value: 0.4037447476969593 and parameters: {'alpha': 1.7476387521594076e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,324] Trial 1156 finished with value: 0.4037452587134802 and parameters: {'alpha': 3.9593558986147906e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,348] Trial 1157 finished with value: 0.4037446948267864 and parameters: {'alpha': 1.0072220292508536e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,373] Trial 1158 finished with value: 0.4037446648258706 and parameters: {'alpha': 1.0054970860436203e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:48:58,399] Trial 1159 finished with value: 0.4037449531031358 and parameters: {'alpha': 2.4684320292187288e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,425] Trial 1160 finished with value: 0.4037447762464166 and parameters: {'alpha': 1.7736148593252802e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,450] Trial 1161 finished with value: 0.40374499997393215 and parameters: {'alpha': 2.7755602056479078e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,476] Trial 1162 finished with value: 0.4037449338756982 and parameters: {'alpha': 1.7213093332875686e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,499] Trial 1163 finished with value: 0.4037452640875042 and parameters: {'alpha': 6.819739994750867e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,525] Trial 1164 finished with value: 0.40374501542435043 and parameters: {'alpha': 2.755690411227822e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,550] Trial 1165 finished with value: 0.4037447792864194 and parameters: {'alpha': 1.6653109222469804e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,575] Trial 1166 finished with value: 0.4037452767924694 and parameters: {'alpha': 4.502232034344007e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  24%|██▎       | 1175/5000 [00:26<01:35, 40.21it/s]

[I 2026-06-14 00:48:58,599] Trial 1167 finished with value: 0.40374480860613443 and parameters: {'alpha': 1.7348738738515964e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,625] Trial 1168 finished with value: 0.40374536229451463 and parameters: {'alpha': 1.8710049604575087e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,652] Trial 1169 finished with value: 0.40374488129504255 and parameters: {'alpha': 1.694249299466815e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,679] Trial 1170 finished with value: 0.40374522064966345 and parameters: {'alpha': 3.989152986219409e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,702] Trial 1171 finished with value: 0.4037447468820797 and parameters: {'alpha': 1.6879116366749843e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,726] Trial 1172 finished with value: 0.40374452063211164 and parameters: {'alpha': 1.0055480290437275e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,749] Trial 1173 finished with value: 0.4037450563806848 and parameters: {'alpha': 2.6986628954812933e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,774] Trial 1174 finished with value: 0.40374532053218093 and parameters: {'alpha': 9.286368055721346e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,799] Trial 1175 finished with value: 0.4037445185370839 and parameters: {'alpha': 1.010198700115909e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:48:58,824] Trial 1176 finished with value: 0.4037451540964556 and parameters: {'alpha': 3.12169165394046e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,850] Trial 1177 finished with value: 0.4037454136149646 and parameters: {'alpha': 0.010617849016686168}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,874] Trial 1178 finished with value: 0.40374460565865056 and parameters: {'alpha': 1.0033466862081964e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,899] Trial 1179 finished with value: 0.4037448524402106 and parameters: {'alpha': 1.9095895089701273e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,924] Trial 1180 finished with value: 0.4037452754730488 and parameters: {'alpha': 4.834980471570472e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,950] Trial 1181 finished with value: 0.40374483035758385 and parameters: {'alpha': 1.8103662819068475e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:58,976] Trial 1182 finished with value: 0.40374447227765725 and parameters: {'alpha': 1.017258015961388e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,000] Trial 1183 finished with value: 0.4037442906157659 and parameters: {'alpha': 1.0115730705877239e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,026] Trial 1184 finished with value: 0.4037450951566372 and parameters: {'alpha': 2.8717602759645688e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  24%|██▍       | 1193/5000 [00:26<01:34, 40.21it/s]

[I 2026-06-14 00:48:59,051] Trial 1185 finished with value: 0.40374468198351554 and parameters: {'alpha': 1.0034475240483432e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,075] Trial 1186 finished with value: 0.4037454066105664 and parameters: {'alpha': 0.00020613695268918762}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,100] Trial 1187 finished with value: 0.40374442647955955 and parameters: {'alpha': 1.0070308446544916e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,124] Trial 1188 finished with value: 0.40374501047816325 and parameters: {'alpha': 2.843999377044705e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,148] Trial 1189 finished with value: 0.4037452450364382 and parameters: {'alpha': 6.391997691815386e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,173] Trial 1190 finished with value: 0.4037449296121615 and parameters: {'alpha': 1.740905211540062e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,197] Trial 1191 finished with value: 0.40374500230736526 and parameters: {'alpha': 2.5651523533442584e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,221] Trial 1192 finished with value: 0.40374490374483213 and parameters: {'alpha': 1.7855149025639692e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,244] Trial 1193 finished with value: 0.40374531438690325 and parameters: {'alpha': 5.3633504192234686e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  24%|██▍       | 1201/5000 [00:26<01:33, 40.61it/s]

[I 2026-06-14 00:48:59,270] Trial 1194 finished with value: 0.403745406936066 and parameters: {'alpha': 0.0006508932210641982}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,295] Trial 1195 finished with value: 0.403744964566866 and parameters: {'alpha': 1.750521272930735e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,319] Trial 1196 finished with value: 0.40374473091714436 and parameters: {'alpha': 1.0020394716577813e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,344] Trial 1197 finished with value: 0.40374529681075416 and parameters: {'alpha': 4.043068582837199e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,367] Trial 1198 finished with value: 0.4037449336257092 and parameters: {'alpha': 1.6549451906550468e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,392] Trial 1199 finished with value: 0.403745021596116 and parameters: {'alpha': 2.9240498200211516e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,426] Trial 1200 finished with value: 0.4037448058399462 and parameters: {'alpha': 1.7203515225132792e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,461] Trial 1201 finished with value: 0.4037447490248083 and parameters: {'alpha': 1.7318190851322346e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  24%|██▍       | 1210/5000 [00:27<01:38, 38.60it/s]

[I 2026-06-14 00:48:59,491] Trial 1202 finished with value: 0.40374525456649263 and parameters: {'alpha': 4.007241898433801e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,523] Trial 1203 finished with value: 0.40374461701383973 and parameters: {'alpha': 1.0007421112705863e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,548] Trial 1204 finished with value: 0.4037453106793415 and parameters: {'alpha': 1.0648853024673432e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,573] Trial 1205 finished with value: 0.4037449786040334 and parameters: {'alpha': 2.71852614930998e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,596] Trial 1206 finished with value: 0.4037446895369765 and parameters: {'alpha': 1.608605273609639e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,620] Trial 1207 finished with value: 0.40374482280498775 and parameters: {'alpha': 1.6971278149050548e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,645] Trial 1208 finished with value: 0.4037452363577305 and parameters: {'alpha': 4.048043600992605e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,670] Trial 1209 finished with value: 0.403745000302481 and parameters: {'alpha': 2.63122153120304e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,694] Trial 1210 finished with value: 0.40374490040096817 and parameters: {'alpha': 1.70880824825272e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  24%|██▍       | 1219/5000 [00:27<01:36, 39.35it/s]

[I 2026-06-14 00:48:59,718] Trial 1211 finished with value: 0.40374474817204753 and parameters: {'alpha': 1.6461762908836487e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,742] Trial 1212 finished with value: 0.4037446146468648 and parameters: {'alpha': 1.0261782569134773e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,767] Trial 1213 finished with value: 0.40377105764903637 and parameters: {'alpha': 12.409794694760558}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,791] Trial 1214 finished with value: 0.40374527444520036 and parameters: {'alpha': 7.397825476228443e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,816] Trial 1215 finished with value: 0.40374471021726316 and parameters: {'alpha': 1.006607118748555e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,843] Trial 1216 finished with value: 0.4037452502987114 and parameters: {'alpha': 3.785140507166888e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,871] Trial 1217 finished with value: 0.4037446205692855 and parameters: {'alpha': 1.0102516083325532e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,893] Trial 1218 finished with value: 0.40374508541218695 and parameters: {'alpha': 2.699239165239936e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,918] Trial 1219 finished with value: 0.40374497321851954 and parameters: {'alpha': 2.692369205961464e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  25%|██▍       | 1228/5000 [00:27<01:36, 39.08it/s]

[I 2026-06-14 00:48:59,942] Trial 1220 finished with value: 0.4037445844152588 and parameters: {'alpha': 1.0065590419134104e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,965] Trial 1221 finished with value: 0.4037453259547077 and parameters: {'alpha': 5.8134471250691296e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:48:59,989] Trial 1222 finished with value: 0.40374478794420304 and parameters: {'alpha': 1.7441824811163102e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,016] Trial 1223 finished with value: 0.40374496220044526 and parameters: {'alpha': 2.5118393137917438e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,046] Trial 1224 finished with value: 0.40374488793293317 and parameters: {'alpha': 1.708860037039349e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,071] Trial 1225 finished with value: 0.40374450360178643 and parameters: {'alpha': 1.0006815558277307e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,096] Trial 1226 finished with value: 0.45403163579064587 and parameters: {'alpha': 5652.02202403864}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,123] Trial 1227 finished with value: 0.4037443674311658 and parameters: {'alpha': 1.0115036333365283e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  25%|██▍       | 1236/5000 [00:27<01:35, 39.57it/s]

[I 2026-06-14 00:49:00,149] Trial 1228 finished with value: 0.4037452378083686 and parameters: {'alpha': 4.4420545333928136e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,175] Trial 1229 finished with value: 0.40374498184652513 and parameters: {'alpha': 2.5538698515561838e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,199] Trial 1230 finished with value: 0.4037448602566487 and parameters: {'alpha': 1.7690723641020873e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,223] Trial 1231 finished with value: 0.4037446695944677 and parameters: {'alpha': 1.0005529774394369e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,246] Trial 1232 finished with value: 0.4037452660651438 and parameters: {'alpha': 7.653356380275427e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,271] Trial 1233 finished with value: 0.4037444165059529 and parameters: {'alpha': 1.0040226485473534e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,295] Trial 1234 finished with value: 0.40374507150511235 and parameters: {'alpha': 2.9363997268901266e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,319] Trial 1235 finished with value: 0.4037448994996359 and parameters: {'alpha': 1.7136003469057977e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,342] Trial 1236 finished with value: 0.40374528222896466 and parameters: {'alpha': 4.275795870716007e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  25%|██▍       | 1245/5000 [00:27<01:32, 40.58it/s]

[I 2026-06-14 00:49:00,365] Trial 1237 finished with value: 0.40374477912718576 and parameters: {'alpha': 1.8550080275198777e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,391] Trial 1238 finished with value: 0.4037450729228395 and parameters: {'alpha': 2.653654691849884e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,414] Trial 1239 finished with value: 0.40374495618456707 and parameters: {'alpha': 1.757945013225356e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,438] Trial 1240 finished with value: 0.4037444855317135 and parameters: {'alpha': 1.0070067011019973e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,463] Trial 1241 finished with value: 0.4037453609504861 and parameters: {'alpha': 2.0288281649589652e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,487] Trial 1242 finished with value: 0.4037452359774254 and parameters: {'alpha': 3.912152652829571e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,513] Trial 1243 finished with value: 0.40374491890985514 and parameters: {'alpha': 1.745963227148377e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,537] Trial 1244 finished with value: 0.4037446568496355 and parameters: {'alpha': 1.0121907173580586e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,561] Trial 1245 finished with value: 0.4037452750489275 and parameters: {'alpha': 8.272849152366729e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  25%|██▌       | 1254/5000 [00:28<01:32, 40.49it/s]

[I 2026-06-14 00:49:00,585] Trial 1246 finished with value: 0.4037450046194763 and parameters: {'alpha': 2.7075263898568252e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,609] Trial 1247 finished with value: 0.40374494458271504 and parameters: {'alpha': 1.746677500231954e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,635] Trial 1248 finished with value: 0.40374461107579934 and parameters: {'alpha': 1.0007028886501146e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,659] Trial 1249 finished with value: 0.4037452647691484 and parameters: {'alpha': 4.513655655054339e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,682] Trial 1250 finished with value: 0.403745047507179 and parameters: {'alpha': 2.664124168452376e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,708] Trial 1251 finished with value: 0.4037446966207517 and parameters: {'alpha': 1.000350735010106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,733] Trial 1252 finished with value: 0.4037449646241717 and parameters: {'alpha': 1.7480807073425925e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,759] Trial 1253 finished with value: 0.4037452466403007 and parameters: {'alpha': 4.672242612520622e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,783] Trial 1254 finished with value: 0.4037447884488203 and parameters: {'alpha': 1.7967169127395203e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  25%|██▌       | 1263/5000 [00:28<01:32, 40.33it/s]

[I 2026-06-14 00:49:00,810] Trial 1255 finished with value: 0.4037446309682526 and parameters: {'alpha': 1.0034866673682417e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,836] Trial 1256 finished with value: 0.40374561739178433 and parameters: {'alpha': 0.29427154628519026}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,861] Trial 1257 finished with value: 0.4037450964630161 and parameters: {'alpha': 2.894502087655038e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,886] Trial 1258 finished with value: 0.403744747639817 and parameters: {'alpha': 1.7617773445911965e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,910] Trial 1259 finished with value: 0.4037453146945667 and parameters: {'alpha': 7.263588248205046e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,936] Trial 1260 finished with value: 0.40374503518562044 and parameters: {'alpha': 2.6675369844991437e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,959] Trial 1261 finished with value: 0.40374486501959467 and parameters: {'alpha': 1.7770599781348194e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:00,984] Trial 1262 finished with value: 0.4037452657172168 and parameters: {'alpha': 4.256094978711763e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,010] Trial 1263 finished with value: 0.40374488483268994 and parameters: {'alpha': 1.8429782875548507e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  25%|██▌       | 1272/5000 [00:28<01:32, 40.27it/s]

[I 2026-06-14 00:49:01,036] Trial 1264 finished with value: 0.40374430993211036 and parameters: {'alpha': 1.0051494159361371e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,060] Trial 1265 finished with value: 0.4037450173106706 and parameters: {'alpha': 2.8443439827509886e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,084] Trial 1266 finished with value: 0.4037449472467253 and parameters: {'alpha': 1.716216471247145e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,108] Trial 1267 finished with value: 0.40374483181841686 and parameters: {'alpha': 1.6729005522982857e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,134] Trial 1268 finished with value: 0.40374534353513597 and parameters: {'alpha': 1.3638290450886778e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,159] Trial 1269 finished with value: 0.40374443936688054 and parameters: {'alpha': 1.016079460225333e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,184] Trial 1270 finished with value: 0.4037452633416452 and parameters: {'alpha': 4.7001553474064514e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,208] Trial 1271 finished with value: 0.4037450460080231 and parameters: {'alpha': 2.939949108386845e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,235] Trial 1272 finished with value: 0.40374454317249336 and parameters: {'alpha': 1.0046716553741552e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  26%|██▌       | 1280/5000 [00:28<01:32, 40.18it/s]

[I 2026-06-14 00:49:01,262] Trial 1273 finished with value: 0.4037449178929191 and parameters: {'alpha': 1.7479140164149773e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,286] Trial 1274 finished with value: 0.4037451154511533 and parameters: {'alpha': 3.0997290639074596e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,311] Trial 1275 finished with value: 0.40374530378318674 and parameters: {'alpha': 5.5469835638323536e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,334] Trial 1276 finished with value: 0.4037443985381853 and parameters: {'alpha': 1.0066696623040813e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,359] Trial 1277 finished with value: 0.40374497867143777 and parameters: {'alpha': 1.7575282043614753e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,384] Trial 1278 finished with value: 0.4037445306219302 and parameters: {'alpha': 1.006614306727741e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,411] Trial 1279 finished with value: 0.40374501464881135 and parameters: {'alpha': 2.6694719715003038e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,439] Trial 1280 finished with value: 0.40374492784202953 and parameters: {'alpha': 1.858040328847489e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  26%|██▌       | 1288/5000 [00:29<01:35, 38.95it/s]

[I 2026-06-14 00:49:01,468] Trial 1281 finished with value: 0.4037453169747755 and parameters: {'alpha': 9.82196260276891e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,496] Trial 1282 finished with value: 0.40374434056665753 and parameters: {'alpha': 1.0000032006751179e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,523] Trial 1283 finished with value: 0.40374521148796133 and parameters: {'alpha': 3.956197405168747e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,550] Trial 1284 finished with value: 0.4037447893114967 and parameters: {'alpha': 1.885721643156396e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,575] Trial 1285 finished with value: 0.40374504147616347 and parameters: {'alpha': 2.92544464173243e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,599] Trial 1286 finished with value: 0.4037447572408158 and parameters: {'alpha': 1.7274536789964736e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,626] Trial 1287 finished with value: 0.4037453001099444 and parameters: {'alpha': 6.760769063998859e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,652] Trial 1288 finished with value: 0.40374478895778754 and parameters: {'alpha': 1.7455736116531255e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  26%|██▌       | 1296/5000 [00:29<01:37, 38.08it/s]

[I 2026-06-14 00:49:01,679] Trial 1289 finished with value: 0.403744512484406 and parameters: {'alpha': 1.0046127450507619e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,707] Trial 1290 finished with value: 0.4037443863154802 and parameters: {'alpha': 1.0021415824015867e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,738] Trial 1291 finished with value: 0.40374475261708237 and parameters: {'alpha': 1.0014631698845657e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,764] Trial 1292 finished with value: 0.4037454060695457 and parameters: {'alpha': 2.283955408616586e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,790] Trial 1293 finished with value: 0.40374499036747036 and parameters: {'alpha': 2.803782096118487e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,815] Trial 1294 finished with value: 0.40374525956818635 and parameters: {'alpha': 4.6212506556927015e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,840] Trial 1295 finished with value: 0.4037449211435875 and parameters: {'alpha': 1.7788148671745618e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,864] Trial 1296 finished with value: 0.4037449732424382 and parameters: {'alpha': 2.6999235395756823e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  26%|██▌       | 1304/5000 [00:29<01:36, 38.49it/s]

[I 2026-06-14 00:49:01,892] Trial 1297 finished with value: 0.4037445304601602 and parameters: {'alpha': 1.0007149553468365e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,918] Trial 1298 finished with value: 0.4037448279712075 and parameters: {'alpha': 1.780818120610562e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,945] Trial 1299 finished with value: 0.40374526460923366 and parameters: {'alpha': 3.994977813919295e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,971] Trial 1300 finished with value: 0.40374496094656376 and parameters: {'alpha': 1.6916819143941395e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:01,996] Trial 1301 finished with value: 0.4037450255728631 and parameters: {'alpha': 2.7642322344559974e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,021] Trial 1302 finished with value: 0.40374530387597185 and parameters: {'alpha': 6.953826278996639e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,048] Trial 1303 finished with value: 0.40374492077807156 and parameters: {'alpha': 1.6321386195204654e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,073] Trial 1304 finished with value: 0.40374514467465683 and parameters: {'alpha': 3.00466080191027e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  26%|██▌       | 1312/5000 [00:29<01:35, 38.69it/s]

[I 2026-06-14 00:49:02,097] Trial 1305 finished with value: 0.40374480170515276 and parameters: {'alpha': 1.7450145539599504e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,122] Trial 1306 finished with value: 0.40374435673428677 and parameters: {'alpha': 1.005962472407185e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,147] Trial 1307 finished with value: 0.40374525323457794 and parameters: {'alpha': 4.6588610796828566e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,173] Trial 1308 finished with value: 0.40374428641824045 and parameters: {'alpha': 1.0038760298955391e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,199] Trial 1309 finished with value: 0.4039247864208544 and parameters: {'alpha': 59.253170707500225}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,225] Trial 1310 finished with value: 0.4037447705900638 and parameters: {'alpha': 1.795071042663744e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,253] Trial 1311 finished with value: 0.40374506340717187 and parameters: {'alpha': 2.570404216300171e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,280] Trial 1312 finished with value: 0.40374488545338755 and parameters: {'alpha': 1.654847904625985e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  26%|██▋       | 1320/5000 [00:29<01:36, 37.98it/s]

[I 2026-06-14 00:49:02,308] Trial 1313 finished with value: 0.40374527962028556 and parameters: {'alpha': 4.137818430048795e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,334] Trial 1314 finished with value: 0.4037443916751957 and parameters: {'alpha': 1.0056185733684178e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,360] Trial 1315 finished with value: 0.40374532943487285 and parameters: {'alpha': 1.0886405519829104e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,391] Trial 1316 finished with value: 0.4037450605404235 and parameters: {'alpha': 2.8928454257328757e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,419] Trial 1317 finished with value: 0.4037447252872857 and parameters: {'alpha': 1.689233076755936e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,442] Trial 1318 finished with value: 0.4037449402599888 and parameters: {'alpha': 1.706956902901177e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,468] Trial 1319 finished with value: 0.4037449805801471 and parameters: {'alpha': 2.7843312109180175e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,491] Trial 1320 finished with value: 0.40374540553092186 and parameters: {'alpha': 8.440142188105573e-06}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  27%|██▋       | 1328/5000 [00:30<01:35, 38.46it/s]

[I 2026-06-14 00:49:02,516] Trial 1321 finished with value: 0.40374452435871633 and parameters: {'alpha': 1.0050292046767491e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,540] Trial 1322 finished with value: 0.4037452551440288 and parameters: {'alpha': 6.172496616504871e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,564] Trial 1323 finished with value: 0.4037449567894625 and parameters: {'alpha': 1.8187984921836838e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,593] Trial 1324 finished with value: 0.4037451549888008 and parameters: {'alpha': 3.202877080789733e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,619] Trial 1325 finished with value: 0.403744798475185 and parameters: {'alpha': 1.7079646052407918e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,645] Trial 1326 finished with value: 0.40374528045064334 and parameters: {'alpha': 4.659068187157664e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,671] Trial 1327 finished with value: 0.4037450549783501 and parameters: {'alpha': 2.696601243855946e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,698] Trial 1328 finished with value: 0.40374474815021505 and parameters: {'alpha': 1.6357402111081245e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  27%|██▋       | 1336/5000 [00:30<01:34, 38.63it/s]

[I 2026-06-14 00:49:02,724] Trial 1329 finished with value: 0.4037448486895046 and parameters: {'alpha': 1.636516414170671e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,749] Trial 1330 finished with value: 0.40374466268812426 and parameters: {'alpha': 1.0149558524112012e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,776] Trial 1331 finished with value: 0.40374544966884524 and parameters: {'alpha': 0.0636752580028139}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,801] Trial 1332 finished with value: 0.40374463536821126 and parameters: {'alpha': 1.0120250503568589e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,827] Trial 1333 finished with value: 0.4037452814368017 and parameters: {'alpha': 5.1907713226265716e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,851] Trial 1334 finished with value: 0.40374503876161827 and parameters: {'alpha': 2.8916407061734898e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,877] Trial 1335 finished with value: 0.4037448867591337 and parameters: {'alpha': 1.7211266955019172e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,903] Trial 1336 finished with value: 0.4037453056575635 and parameters: {'alpha': 8.753467248596989e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:49:02,928] Trial 1337 finished with value: 0.4037450289003224 and parameters: {'alpha': 2.7657827187933476e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,952] Trial 1338 finished with value: 0.4037449177130079 and parameters: {'alpha': 1.6860285543065494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:02,977] Trial 1339 finished with value: 0.4037445140748856 and parameters: {'alpha': 1.0308326216708352e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,004] Trial 1340 finished with value: 0.4037448001439474 and parameters: {'alpha': 1.704405498204287e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,028] Trial 1341 finished with value: 0.40374529411852367 and parameters: {'alpha': 4.0147290860009606e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,051] Trial 1342 finished with value: 0.4037446789242391 and parameters: {'alpha': 1.0084771456999281e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,078] Trial 1343 finished with value: 0.40374441334476685 and parameters: {'alpha': 1.000484940097664e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,104] Trial 1344 finished with value: 0.40374509125692715 and parameters: {'alpha': 2.7550387900831503e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,129] Trial 1345 finished with value: 0.40374454471120697 and parameters: {'alpha': 1.0010747824286073e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  27%|██▋       | 1353/5000 [00:30<01:32, 39.51it/s]

[I 2026-06-14 00:49:03,154] Trial 1346 finished with value: 0.4037446778086558 and parameters: {'alpha': 1.0084666103376553e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,179] Trial 1347 finished with value: 0.4037453075465699 and parameters: {'alpha': 5.4144641908865844e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,205] Trial 1348 finished with value: 0.40374501428208487 and parameters: {'alpha': 2.388928441942153e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,230] Trial 1349 finished with value: 0.40374490608498054 and parameters: {'alpha': 1.74937057484075e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,255] Trial 1350 finished with value: 0.40374464014940464 and parameters: {'alpha': 1.0056647710441755e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,280] Trial 1351 finished with value: 0.40374504181134574 and parameters: {'alpha': 2.9049917506212775e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,305] Trial 1352 finished with value: 0.4037453595736461 and parameters: {'alpha': 1.8212099558505122e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,331] Trial 1353 finished with value: 0.403744914974504 and parameters: {'alpha': 1.7197213904862683e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  27%|██▋       | 1361/5000 [00:30<01:33, 39.07it/s]

[I 2026-06-14 00:49:03,357] Trial 1354 finished with value: 0.4037452374100646 and parameters: {'alpha': 4.504784896455857e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,381] Trial 1355 finished with value: 0.40374506106492225 and parameters: {'alpha': 2.6422275583834553e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,407] Trial 1356 finished with value: 0.40374480206234936 and parameters: {'alpha': 1.7301089707183085e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,434] Trial 1357 finished with value: 0.40374527671871846 and parameters: {'alpha': 6.701809510813825e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,458] Trial 1358 finished with value: 0.4037442997405718 and parameters: {'alpha': 1.0154779578100916e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,484] Trial 1359 finished with value: 0.40374490535380386 and parameters: {'alpha': 1.666425099331035e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,511] Trial 1360 finished with value: 0.4037450274039403 and parameters: {'alpha': 2.85948257017308e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,538] Trial 1361 finished with value: 0.4037442673051452 and parameters: {'alpha': 1.0134853447722229e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  27%|██▋       | 1369/5000 [00:31<01:36, 37.54it/s]

[I 2026-06-14 00:49:03,565] Trial 1362 finished with value: 0.4037446313562596 and parameters: {'alpha': 1.0111354803461621e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,596] Trial 1363 finished with value: 0.4037452480233369 and parameters: {'alpha': 4.100533771404912e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,625] Trial 1364 finished with value: 0.4037454064983349 and parameters: {'alpha': 0.00010368650442594186}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,653] Trial 1365 finished with value: 0.4037447427159719 and parameters: {'alpha': 1.81879272844086e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,679] Trial 1366 finished with value: 0.40374448450968564 and parameters: {'alpha': 1.0017652776589385e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,708] Trial 1367 finished with value: 0.4037453243743069 and parameters: {'alpha': 1.0628577484938856e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,734] Trial 1368 finished with value: 0.40374511804329805 and parameters: {'alpha': 2.9880209909135534e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,760] Trial 1369 finished with value: 0.4037449324029668 and parameters: {'alpha': 1.8161152432636145e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  28%|██▊       | 1377/5000 [00:31<01:35, 37.94it/s]

[I 2026-06-14 00:49:03,787] Trial 1370 finished with value: 0.4037449868413748 and parameters: {'alpha': 2.5917278964973298e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,813] Trial 1371 finished with value: 0.40374489608384784 and parameters: {'alpha': 1.712099284659726e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,839] Trial 1372 finished with value: 0.40374528867247855 and parameters: {'alpha': 5.8346815825325726e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,865] Trial 1373 finished with value: 0.4037449196760347 and parameters: {'alpha': 1.7189478287499185e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,892] Trial 1374 finished with value: 0.40374519082263083 and parameters: {'alpha': 4.3399680792376434e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,917] Trial 1375 finished with value: 0.40374474948486505 and parameters: {'alpha': 1.6030261577307656e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,943] Trial 1376 finished with value: 0.40374498802401987 and parameters: {'alpha': 2.7184429811875096e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:03,969] Trial 1377 finished with value: 0.40374483882281975 and parameters: {'alpha': 1.6242617831343868e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  28%|██▊       | 1385/5000 [00:31<01:33, 38.68it/s]

[I 2026-06-14 00:49:03,996] Trial 1378 finished with value: 0.403745081719702 and parameters: {'alpha': 2.833943191577847e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,020] Trial 1379 finished with value: 0.4037452951916116 and parameters: {'alpha': 7.396045452440622e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,045] Trial 1380 finished with value: 0.4037445076394466 and parameters: {'alpha': 1.0244093148566519e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,071] Trial 1381 finished with value: 0.4037453860265281 and parameters: {'alpha': 5.058190981816676e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,097] Trial 1382 finished with value: 0.4037447966536403 and parameters: {'alpha': 1.642230909853929e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,122] Trial 1383 finished with value: 0.4037452369804501 and parameters: {'alpha': 4.277545458491387e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,146] Trial 1384 finished with value: 0.417094855291229 and parameters: {'alpha': 1921.9310141466376}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,173] Trial 1385 finished with value: 0.40374460433268045 and parameters: {'alpha': 1.0032143634942931e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  28%|██▊       | 1393/5000 [00:31<01:33, 38.61it/s]

[I 2026-06-14 00:49:04,199] Trial 1386 finished with value: 0.40374426626551857 and parameters: {'alpha': 1.0000110235856522e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,223] Trial 1387 finished with value: 0.4037446984947958 and parameters: {'alpha': 1.0079849169073189e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,248] Trial 1388 finished with value: 0.403745036402994 and parameters: {'alpha': 2.7444667118820956e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,276] Trial 1389 finished with value: 0.40374478479198317 and parameters: {'alpha': 1.8151116002065237e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,301] Trial 1390 finished with value: 0.40374510457426804 and parameters: {'alpha': 3.0325370239034e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,326] Trial 1391 finished with value: 0.40374490600874674 and parameters: {'alpha': 1.700262154365518e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,350] Trial 1392 finished with value: 0.403744380938472 and parameters: {'alpha': 1.00578708581244e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,378] Trial 1393 finished with value: 0.4037452823891957 and parameters: {'alpha': 5.134619099160565e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  28%|██▊       | 1401/5000 [00:31<01:36, 37.39it/s]

[I 2026-06-14 00:49:04,403] Trial 1394 finished with value: 0.40374475700804724 and parameters: {'alpha': 1.7789040964589365e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,429] Trial 1395 finished with value: 0.403745078925282 and parameters: {'alpha': 2.7806060027735965e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,455] Trial 1396 finished with value: 0.4037453385531541 and parameters: {'alpha': 1.1692113469003024e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,482] Trial 1397 finished with value: 0.40374457787781615 and parameters: {'alpha': 1.0086587134207246e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,511] Trial 1398 finished with value: 0.40374490963099074 and parameters: {'alpha': 1.7451870702966124e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,538] Trial 1399 finished with value: 0.4037452299887671 and parameters: {'alpha': 4.180545017534345e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,570] Trial 1400 finished with value: 0.4037444090967092 and parameters: {'alpha': 1.003192749003646e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  28%|██▊       | 1405/5000 [00:32<01:59, 30.04it/s]

[I 2026-06-14 00:49:04,604] Trial 1401 finished with value: 0.40374505567694086 and parameters: {'alpha': 2.5287929368655518e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,675] Trial 1402 finished with value: 0.4037449254020862 and parameters: {'alpha': 1.6893270162356517e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,727] Trial 1403 finished with value: 0.4037449952861552 and parameters: {'alpha': 2.622064592388096e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,765] Trial 1404 finished with value: 0.40374483855273113 and parameters: {'alpha': 1.8365730631238708e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,803] Trial 1405 finished with value: 0.4037452549743454 and parameters: {'alpha': 6.887891229847303e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  28%|██▊       | 1411/5000 [00:32<02:02, 29.34it/s]

[I 2026-06-14 00:49:04,841] Trial 1406 finished with value: 0.4037444619674248 and parameters: {'alpha': 1.000862776995637e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,876] Trial 1407 finished with value: 0.4037443522308181 and parameters: {'alpha': 1.0026085469747855e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,907] Trial 1408 finished with value: 0.40374521219027293 and parameters: {'alpha': 4.1654343706275696e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,941] Trial 1409 finished with value: 0.4037448643934309 and parameters: {'alpha': 1.6835009489193024e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:04,973] Trial 1410 finished with value: 0.40374496774799556 and parameters: {'alpha': 2.738580251650099e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,008] Trial 1411 finished with value: 0.4037447583882694 and parameters: {'alpha': 1.7964106213548886e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  28%|██▊       | 1417/5000 [00:32<02:13, 26.84it/s]

[I 2026-06-14 00:49:05,045] Trial 1412 finished with value: 0.4037452646552782 and parameters: {'alpha': 3.7476837096244e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,087] Trial 1413 finished with value: 0.40374469603218743 and parameters: {'alpha': 1.6380399791816054e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,124] Trial 1414 finished with value: 0.4037450007137601 and parameters: {'alpha': 2.7695188990954944e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,182] Trial 1415 finished with value: 0.403744822471169 and parameters: {'alpha': 1.810938336390352e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,223] Trial 1416 finished with value: 0.40374460049074096 and parameters: {'alpha': 1.0024379732093537e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  28%|██▊       | 1423/5000 [00:32<02:15, 26.49it/s]

[I 2026-06-14 00:49:05,262] Trial 1417 finished with value: 0.4037452758096899 and parameters: {'alpha': 6.339160334878799e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,303] Trial 1418 finished with value: 0.4037449397390559 and parameters: {'alpha': 1.687676729865611e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,342] Trial 1419 finished with value: 0.40374433042577107 and parameters: {'alpha': 1.0211585812784304e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,378] Trial 1420 finished with value: 0.4037452051682858 and parameters: {'alpha': 3.981982144963634e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,415] Trial 1421 finished with value: 0.4037449693931365 and parameters: {'alpha': 2.6077114410115925e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,456] Trial 1422 finished with value: 0.40374502755523084 and parameters: {'alpha': 2.474560390991101e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  29%|██▊       | 1428/5000 [00:33<02:14, 26.55it/s]

[I 2026-06-14 00:49:05,494] Trial 1423 finished with value: 0.4037452999295603 and parameters: {'alpha': 9.500860408265573e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,532] Trial 1424 finished with value: 0.40374440969122405 and parameters: {'alpha': 1.0217665903542818e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,565] Trial 1425 finished with value: 0.4037449316806176 and parameters: {'alpha': 1.73640404495325e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,602] Trial 1426 finished with value: 0.4037445760088381 and parameters: {'alpha': 1.0176334641845564e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,634] Trial 1427 finished with value: 0.4037452001333481 and parameters: {'alpha': 4.084388593484109e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,668] Trial 1428 finished with value: 0.4037444870428976 and parameters: {'alpha': 1.0000419097754156e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  29%|██▊       | 1435/5000 [00:33<02:07, 27.94it/s]

[I 2026-06-14 00:49:05,701] Trial 1429 finished with value: 0.4037449618953431 and parameters: {'alpha': 1.7331685746900287e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,738] Trial 1430 finished with value: 0.4037450776058679 and parameters: {'alpha': 2.8634614762123507e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,771] Trial 1431 finished with value: 0.40374527098140156 and parameters: {'alpha': 5.553999741654761e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,806] Trial 1432 finished with value: 0.40374491499713744 and parameters: {'alpha': 1.6174970222526148e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,836] Trial 1433 finished with value: 0.40374479574904454 and parameters: {'alpha': 1.7007725929651073e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,869] Trial 1434 finished with value: 0.4037450008791799 and parameters: {'alpha': 2.8284789075678715e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,900] Trial 1435 finished with value: 0.4037446232971745 and parameters: {'alpha': 1.0201204965303864e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  29%|██▉       | 1442/5000 [00:33<01:58, 29.95it/s]

[I 2026-06-14 00:49:05,930] Trial 1436 finished with value: 0.4037446824463369 and parameters: {'alpha': 1.0101184513405823e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:05,975] Trial 1437 finished with value: 0.4037450543663165 and parameters: {'alpha': 2.5985831803938132e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,002] Trial 1438 finished with value: 0.403744560666872 and parameters: {'alpha': 1.0072283819480842e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,032] Trial 1439 finished with value: 0.4037452801453556 and parameters: {'alpha': 5.308187240559926e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,059] Trial 1440 finished with value: 0.4037449118038272 and parameters: {'alpha': 1.781082578199888e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,088] Trial 1441 finished with value: 0.4037452146853135 and parameters: {'alpha': 3.908319410555026e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,120] Trial 1442 finished with value: 0.40374481754696023 and parameters: {'alpha': 1.754097188457559e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  29%|██▉       | 1449/5000 [00:33<01:52, 31.48it/s]

[I 2026-06-14 00:49:06,149] Trial 1443 finished with value: 0.4037446666711887 and parameters: {'alpha': 1.0075098911254023e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,185] Trial 1444 finished with value: 0.4037453772755446 and parameters: {'alpha': 2.981025042932746e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,217] Trial 1445 finished with value: 0.4037453118728136 and parameters: {'alpha': 8.193849235227507e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,248] Trial 1446 finished with value: 0.4037450311236867 and parameters: {'alpha': 2.6068869285333178e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,278] Trial 1447 finished with value: 0.40374479822892534 and parameters: {'alpha': 1.7628179770482756e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,302] Trial 1448 finished with value: 0.4037444986636178 and parameters: {'alpha': 1.005765885367444e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,330] Trial 1449 finished with value: 0.4037452442216472 and parameters: {'alpha': 3.93706359960724e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  29%|██▉       | 1457/5000 [00:33<01:44, 33.87it/s]

[I 2026-06-14 00:49:06,358] Trial 1450 finished with value: 0.4037447444363727 and parameters: {'alpha': 1.7027744708344064e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,387] Trial 1451 finished with value: 0.40374504558123525 and parameters: {'alpha': 2.7134210158882255e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,416] Trial 1452 finished with value: 0.4037453516646752 and parameters: {'alpha': 1.4943937681061512e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,445] Trial 1453 finished with value: 0.4037446910234931 and parameters: {'alpha': 1.0067946181728206e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,471] Trial 1454 finished with value: 0.5349832544101921 and parameters: {'alpha': 26395.452623041587}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,498] Trial 1455 finished with value: 0.4037445911266688 and parameters: {'alpha': 1.0043259630875674e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,524] Trial 1456 finished with value: 0.40374507061546916 and parameters: {'alpha': 2.7397692561120942e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,555] Trial 1457 finished with value: 0.40374491002294327 and parameters: {'alpha': 1.739195309213621e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  29%|██▉       | 1465/5000 [00:34<01:49, 32.42it/s]

[I 2026-06-14 00:49:06,588] Trial 1458 finished with value: 0.4037452807286305 and parameters: {'alpha': 5.533545031959614e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,623] Trial 1459 finished with value: 0.40374470608946045 and parameters: {'alpha': 1.0060776666797157e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,653] Trial 1460 finished with value: 0.4037450235053477 and parameters: {'alpha': 2.6372565328165916e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,687] Trial 1461 finished with value: 0.40374482976204307 and parameters: {'alpha': 1.9061926655273994e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,721] Trial 1462 finished with value: 0.4037452398886627 and parameters: {'alpha': 4.2082829142299896e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,751] Trial 1463 finished with value: 0.4037446597049395 and parameters: {'alpha': 1.0020656955417949e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,781] Trial 1464 finished with value: 0.4037447193649512 and parameters: {'alpha': 1.7428079083305887e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  29%|██▉       | 1471/5000 [00:34<01:49, 32.25it/s]

[I 2026-06-14 00:49:06,812] Trial 1465 finished with value: 0.40374487772877343 and parameters: {'alpha': 1.7489805914113838e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,842] Trial 1466 finished with value: 0.4077982198898802 and parameters: {'alpha': 877.5411573528628}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,876] Trial 1467 finished with value: 0.4037451771903083 and parameters: {'alpha': 3.926140491107238e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,905] Trial 1468 finished with value: 0.4037452692957492 and parameters: {'alpha': 8.578250079066316e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,938] Trial 1469 finished with value: 0.40374489659464763 and parameters: {'alpha': 1.7098462904624064e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,966] Trial 1470 finished with value: 0.40381329117806014 and parameters: {'alpha': 25.382625057395657}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:06,994] Trial 1471 finished with value: 0.40374503053172933 and parameters: {'alpha': 2.9301825703931856e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  30%|██▉       | 1479/5000 [00:34<01:45, 33.35it/s]

[I 2026-06-14 00:49:07,023] Trial 1472 finished with value: 0.4037446356933622 and parameters: {'alpha': 1.0051958880951082e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,055] Trial 1473 finished with value: 0.40374503524004646 and parameters: {'alpha': 2.5264660199997465e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,084] Trial 1474 finished with value: 0.4037449394363875 and parameters: {'alpha': 1.6878322184106893e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,110] Trial 1475 finished with value: 0.4037454100923074 and parameters: {'alpha': 0.005358884435399502}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,139] Trial 1476 finished with value: 0.4037452597825679 and parameters: {'alpha': 6.202584089209281e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,166] Trial 1477 finished with value: 0.4037447433233213 and parameters: {'alpha': 1.6841464660487974e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,193] Trial 1478 finished with value: 0.40374517306235835 and parameters: {'alpha': 3.62587886959083e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,219] Trial 1479 finished with value: 0.40374495951009565 and parameters: {'alpha': 1.8400454367280552e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  30%|██▉       | 1487/5000 [00:34<01:39, 35.36it/s]

[I 2026-06-14 00:49:07,244] Trial 1480 finished with value: 0.4037448951853567 and parameters: {'alpha': 1.7286289684405586e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,273] Trial 1481 finished with value: 0.403745227800266 and parameters: {'alpha': 3.535135613518029e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,300] Trial 1482 finished with value: 0.4037449676216008 and parameters: {'alpha': 1.771622754757102e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,326] Trial 1483 finished with value: 0.4037450855260825 and parameters: {'alpha': 2.7960281639286765e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,351] Trial 1484 finished with value: 0.403744310299149 and parameters: {'alpha': 1.0112562932726872e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,380] Trial 1485 finished with value: 0.4037446369192105 and parameters: {'alpha': 1.0023148204423134e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,406] Trial 1486 finished with value: 0.4037452650095459 and parameters: {'alpha': 6.321671247574227e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,432] Trial 1487 finished with value: 0.4046597158013616 and parameters: {'alpha': 306.611352147157}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  30%|██▉       | 1494/5000 [00:35<01:42, 34.30it/s]

[I 2026-06-14 00:49:07,459] Trial 1488 finished with value: 0.40374506015582784 and parameters: {'alpha': 2.6841480056862076e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,487] Trial 1489 finished with value: 0.40374487169567447 and parameters: {'alpha': 1.8039330124690323e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,520] Trial 1490 finished with value: 0.4037446636343808 and parameters: {'alpha': 1.0093953638872939e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,555] Trial 1491 finished with value: 0.4037445881352536 and parameters: {'alpha': 1.0118941055950782e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,587] Trial 1492 finished with value: 0.4037452667759445 and parameters: {'alpha': 4.6494892868751295e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,618] Trial 1493 finished with value: 0.4037453339992827 and parameters: {'alpha': 1.1965077312623127e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,647] Trial 1494 finished with value: 0.4037449132087493 and parameters: {'alpha': 1.698453532174168e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  30%|███       | 1501/5000 [00:35<01:43, 33.85it/s]

[I 2026-06-14 00:49:07,675] Trial 1495 finished with value: 0.40374498086084826 and parameters: {'alpha': 2.765332444695104e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,705] Trial 1496 finished with value: 0.40374458075031927 and parameters: {'alpha': 1.0062906399153775e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,740] Trial 1497 finished with value: 0.40374493200426437 and parameters: {'alpha': 1.81993954938449e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,770] Trial 1498 finished with value: 0.40374526343271927 and parameters: {'alpha': 3.9307094579129184e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,800] Trial 1499 finished with value: 0.403744832031446 and parameters: {'alpha': 1.9241770196185064e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,828] Trial 1500 finished with value: 0.4037444935218607 and parameters: {'alpha': 1.0078612202103736e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,853] Trial 1501 finished with value: 0.40374502730739636 and parameters: {'alpha': 2.673901875831899e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  30%|███       | 1509/5000 [00:35<01:37, 35.80it/s]

[I 2026-06-14 00:49:07,878] Trial 1502 finished with value: 0.40374525362337027 and parameters: {'alpha': 4.928805711803823e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,905] Trial 1503 finished with value: 0.40374497080305943 and parameters: {'alpha': 2.6039787451121746e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,930] Trial 1504 finished with value: 0.40374477282081983 and parameters: {'alpha': 1.6499282567718832e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,960] Trial 1505 finished with value: 0.40374464226895623 and parameters: {'alpha': 1.0085814055925336e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:07,988] Trial 1506 finished with value: 0.40374479805683294 and parameters: {'alpha': 1.7010646170606593e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,013] Trial 1507 finished with value: 0.40374527322822 and parameters: {'alpha': 7.547508753807272e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,038] Trial 1508 finished with value: 0.40374525496249697 and parameters: {'alpha': 3.715709853637493e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,066] Trial 1509 finished with value: 0.4037450297897829 and parameters: {'alpha': 2.6708919349663167e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  30%|███       | 1517/5000 [00:35<01:37, 35.79it/s]

[I 2026-06-14 00:49:08,094] Trial 1510 finished with value: 0.40374485271452865 and parameters: {'alpha': 1.6057590079308875e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,122] Trial 1511 finished with value: 0.4037449482352379 and parameters: {'alpha': 1.7730111316446526e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,152] Trial 1512 finished with value: 0.4037452845892565 and parameters: {'alpha': 4.249751649663716e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,181] Trial 1513 finished with value: 0.4037448838141971 and parameters: {'alpha': 1.6968717429193964e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,211] Trial 1514 finished with value: 0.4037444371915641 and parameters: {'alpha': 1.0077328940127305e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,236] Trial 1515 finished with value: 0.40374501373742955 and parameters: {'alpha': 2.72599507457684e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,263] Trial 1516 finished with value: 0.40374446610913006 and parameters: {'alpha': 1.007749040394395e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,291] Trial 1517 finished with value: 0.4037452596948277 and parameters: {'alpha': 7.061903719953909e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  30%|███       | 1525/5000 [00:35<01:40, 34.71it/s]

[I 2026-06-14 00:49:08,321] Trial 1518 finished with value: 0.4037448194226401 and parameters: {'alpha': 1.8117970474307813e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,356] Trial 1519 finished with value: 0.40374523751226576 and parameters: {'alpha': 3.821400716489235e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,388] Trial 1520 finished with value: 0.4037470368403929 and parameters: {'alpha': 1.7270722753373777}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,418] Trial 1521 finished with value: 0.40374485288866685 and parameters: {'alpha': 1.6591836813445912e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,449] Trial 1522 finished with value: 0.4037448002085037 and parameters: {'alpha': 1.6672659432387132e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,476] Trial 1523 finished with value: 0.4037451271494562 and parameters: {'alpha': 3.2670662006349716e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,502] Trial 1524 finished with value: 0.4037449363267304 and parameters: {'alpha': 1.717463313740694e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:49:08,533] Trial 1525 finished with value: 0.4037444946108008 and parameters: {'alpha': 1.0094544074787868e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,558] Trial 1526 finished with value: 0.403745418771685 and parameters: {'alpha': 0.018293525309495337}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,588] Trial 1527 finished with value: 0.40374532811997493 and parameters: {'alpha': 1.2416841741178243e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,621] Trial 1528 finished with value: 0.40374503287080354 and parameters: {'alpha': 2.7852491344250404e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,650] Trial 1529 finished with value: 0.4037452768496633 and parameters: {'alpha': 6.597216119437616e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,678] Trial 1530 finished with value: 0.403744905701212 and parameters: {'alpha': 1.6693476884298445e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,706] Trial 1531 finished with value: 0.40374496761433026 and parameters: {'alpha': 2.7482879435410444e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  31%|███       | 1539/5000 [00:36<01:37, 35.54it/s]

[I 2026-06-14 00:49:08,734] Trial 1532 finished with value: 0.40374441105921854 and parameters: {'alpha': 1.0252487149547248e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,764] Trial 1533 finished with value: 0.4037452483657647 and parameters: {'alpha': 4.881178378260404e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,789] Trial 1534 finished with value: 0.4037444665474947 and parameters: {'alpha': 1.0147751900745324e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,816] Trial 1535 finished with value: 0.40374502913125243 and parameters: {'alpha': 2.5328466961412663e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,841] Trial 1536 finished with value: 0.4037447859431217 and parameters: {'alpha': 1.6233960095191497e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,867] Trial 1537 finished with value: 0.40374476567887474 and parameters: {'alpha': 1.7421099803027236e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,893] Trial 1538 finished with value: 0.4037452184935025 and parameters: {'alpha': 4.1858700482018546e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,920] Trial 1539 finished with value: 0.40374451050624294 and parameters: {'alpha': 1.0132932265019982e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  31%|███       | 1547/5000 [00:36<01:35, 36.25it/s]

[I 2026-06-14 00:49:08,945] Trial 1540 finished with value: 0.4037442935858372 and parameters: {'alpha': 1.0017236376663348e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:08,976] Trial 1541 finished with value: 0.4037450226059226 and parameters: {'alpha': 2.819730654742776e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,003] Trial 1542 finished with value: 0.40374457213464926 and parameters: {'alpha': 1.0041818073409928e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,030] Trial 1543 finished with value: 0.4037444312216152 and parameters: {'alpha': 1.0028745709095503e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,056] Trial 1544 finished with value: 0.4037449517433547 and parameters: {'alpha': 2.4836842127249355e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,085] Trial 1545 finished with value: 0.4037449643095168 and parameters: {'alpha': 1.7796434168720988e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,111] Trial 1546 finished with value: 0.4037452361426342 and parameters: {'alpha': 4.6048731095878394e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,139] Trial 1547 finished with value: 0.40374468168994637 and parameters: {'alpha': 1.0024439122019217e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  31%|███       | 1555/5000 [00:36<01:35, 36.26it/s]

[I 2026-06-14 00:49:09,168] Trial 1548 finished with value: 0.4037452671701044 and parameters: {'alpha': 8.633996687060182e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,195] Trial 1549 finished with value: 0.40374438864489076 and parameters: {'alpha': 1.0071846047362851e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,223] Trial 1550 finished with value: 0.4037447033230646 and parameters: {'alpha': 1.0017563737010683e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,251] Trial 1551 finished with value: 0.40374499265451397 and parameters: {'alpha': 2.7251549504743664e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,277] Trial 1552 finished with value: 0.4037447381687782 and parameters: {'alpha': 1.7531322787449368e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,306] Trial 1553 finished with value: 0.4037450586312212 and parameters: {'alpha': 2.607545616071615e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,335] Trial 1554 finished with value: 0.40374488718115353 and parameters: {'alpha': 1.8039445764401985e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,364] Trial 1555 finished with value: 0.4037452621820836 and parameters: {'alpha': 5.5230244924653753e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  31%|███▏      | 1563/5000 [00:36<01:35, 35.91it/s]

[I 2026-06-14 00:49:09,392] Trial 1556 finished with value: 0.4037448731608623 and parameters: {'alpha': 1.703819669201597e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,422] Trial 1557 finished with value: 0.40374536389647797 and parameters: {'alpha': 2.0570455012462894e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,448] Trial 1558 finished with value: 0.40374526250348214 and parameters: {'alpha': 3.9448352195407884e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,476] Trial 1559 finished with value: 0.4037443809911525 and parameters: {'alpha': 1.0082330061178063e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,503] Trial 1560 finished with value: 0.4037448629666299 and parameters: {'alpha': 1.7684490058764607e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,530] Trial 1561 finished with value: 0.4037450829648072 and parameters: {'alpha': 2.9351793859438463e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,557] Trial 1562 finished with value: 0.4037447359145554 and parameters: {'alpha': 1.7483603175053522e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,587] Trial 1563 finished with value: 0.40374507651303804 and parameters: {'alpha': 2.800900208248132e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  31%|███▏      | 1570/5000 [00:37<01:41, 33.83it/s]

[I 2026-06-14 00:49:09,616] Trial 1564 finished with value: 0.4037445223551252 and parameters: {'alpha': 1.0053878988506967e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,646] Trial 1565 finished with value: 0.40374442340922156 and parameters: {'alpha': 1.0051308122439556e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,689] Trial 1566 finished with value: 0.4037452783922906 and parameters: {'alpha': 5.652196333006933e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,719] Trial 1567 finished with value: 0.403744920348331 and parameters: {'alpha': 1.734777876165747e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,749] Trial 1568 finished with value: 0.40374510984257456 and parameters: {'alpha': 2.828969574398103e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,780] Trial 1569 finished with value: 0.40374531685691695 and parameters: {'alpha': 9.658577255490494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,806] Trial 1570 finished with value: 0.4037448469755619 and parameters: {'alpha': 1.839138822647785e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  32%|███▏      | 1578/5000 [00:37<01:37, 35.06it/s]

[I 2026-06-14 00:49:09,835] Trial 1571 finished with value: 0.4037497416503916 and parameters: {'alpha': 3.5932218828324056}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,862] Trial 1572 finished with value: 0.4037452752909722 and parameters: {'alpha': 4.462223646987092e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,891] Trial 1573 finished with value: 0.4037448453561124 and parameters: {'alpha': 1.6286319873255082e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,917] Trial 1574 finished with value: 0.4037450072013673 and parameters: {'alpha': 2.8852892316944094e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,943] Trial 1575 finished with value: 0.40374487571443834 and parameters: {'alpha': 1.7373099501764214e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,970] Trial 1576 finished with value: 0.40374476249511726 and parameters: {'alpha': 1.7206614077602044e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:09,998] Trial 1577 finished with value: 0.4037452606463171 and parameters: {'alpha': 4.3787412171178674e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,026] Trial 1578 finished with value: 0.40374487480091764 and parameters: {'alpha': 1.6929645100248304e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  32%|███▏      | 1586/5000 [00:37<01:34, 36.15it/s]

[I 2026-06-14 00:49:10,053] Trial 1579 finished with value: 0.40374508270551857 and parameters: {'alpha': 2.805484809808195e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,078] Trial 1580 finished with value: 0.40374492148700075 and parameters: {'alpha': 1.6892487676665e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,105] Trial 1581 finished with value: 0.4037452515236457 and parameters: {'alpha': 7.108489461257432e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,130] Trial 1582 finished with value: 0.4037444218178257 and parameters: {'alpha': 1.0226511551732436e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,157] Trial 1583 finished with value: 0.40374506239195745 and parameters: {'alpha': 2.682041090511604e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,186] Trial 1584 finished with value: 0.4037452659252899 and parameters: {'alpha': 4.165538277363554e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,212] Trial 1585 finished with value: 0.40402266434054374 and parameters: {'alpha': 93.02687363189787}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,238] Trial 1586 finished with value: 0.4037449299487221 and parameters: {'alpha': 1.685376337315274e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  32%|███▏      | 1594/5000 [00:37<01:31, 37.19it/s]

[I 2026-06-14 00:49:10,264] Trial 1587 finished with value: 0.40374452656171467 and parameters: {'alpha': 1.017723048895291e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,291] Trial 1588 finished with value: 0.4037450559604826 and parameters: {'alpha': 2.752362943731072e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,317] Trial 1589 finished with value: 0.4037444491861153 and parameters: {'alpha': 1.0108282155030618e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,344] Trial 1590 finished with value: 0.4037446334629799 and parameters: {'alpha': 1.0081895203844349e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,370] Trial 1591 finished with value: 0.4037445181522196 and parameters: {'alpha': 1.012050239104666e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,395] Trial 1592 finished with value: 0.4037450787225346 and parameters: {'alpha': 2.677778491462661e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,423] Trial 1593 finished with value: 0.4037452615736223 and parameters: {'alpha': 5.452181520017333e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,449] Trial 1594 finished with value: 0.40374479771446264 and parameters: {'alpha': 1.6880320387073486e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  32%|███▏      | 1602/5000 [00:38<01:31, 37.19it/s]

[I 2026-06-14 00:49:10,475] Trial 1595 finished with value: 0.4037443725407081 and parameters: {'alpha': 1.0123510091532272e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,502] Trial 1596 finished with value: 0.40374498568766237 and parameters: {'alpha': 2.7196524325399478e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,530] Trial 1597 finished with value: 0.40374490667957746 and parameters: {'alpha': 1.7182188952610818e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,556] Trial 1598 finished with value: 0.4037453058527212 and parameters: {'alpha': 1.0307137133784009e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,584] Trial 1599 finished with value: 0.4037452273461943 and parameters: {'alpha': 4.130190769934003e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,610] Trial 1600 finished with value: 0.40374488009357873 and parameters: {'alpha': 1.713424338328188e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,637] Trial 1601 finished with value: 0.40374502599449374 and parameters: {'alpha': 2.704724962392605e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,663] Trial 1602 finished with value: 0.4037454062626027 and parameters: {'alpha': 4.421812825292214e-05}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  32%|███▏      | 1610/5000 [00:38<01:31, 36.86it/s]

[I 2026-06-14 00:49:10,690] Trial 1603 finished with value: 0.40374499793409635 and parameters: {'alpha': 1.8392387249308906e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,716] Trial 1604 finished with value: 0.40374430680444784 and parameters: {'alpha': 1.0051216412720357e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,744] Trial 1605 finished with value: 0.40374528816215 and parameters: {'alpha': 6.169512058205201e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,772] Trial 1606 finished with value: 0.40374457938568414 and parameters: {'alpha': 1.0033713370424108e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,798] Trial 1607 finished with value: 0.4037451740256368 and parameters: {'alpha': 3.836868261386204e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,828] Trial 1608 finished with value: 0.40374475270697746 and parameters: {'alpha': 1.7393537784851016e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,857] Trial 1609 finished with value: 0.4037450338607367 and parameters: {'alpha': 2.6653588384134235e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,887] Trial 1610 finished with value: 0.40374484128938926 and parameters: {'alpha': 1.6882249925989347e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  32%|███▏      | 1617/5000 [00:38<01:44, 32.22it/s]

[I 2026-06-14 00:49:10,920] Trial 1611 finished with value: 0.4037452718112173 and parameters: {'alpha': 4.214725449562305e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,953] Trial 1612 finished with value: 0.4037448693729542 and parameters: {'alpha': 1.6860272449459313e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:10,995] Trial 1613 finished with value: 0.4037449222154444 and parameters: {'alpha': 1.712805170321259e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,029] Trial 1614 finished with value: 0.4037449857192343 and parameters: {'alpha': 2.802447046111776e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,064] Trial 1615 finished with value: 0.4037443152977951 and parameters: {'alpha': 1.0100251336642586e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,097] Trial 1616 finished with value: 0.40374530651092505 and parameters: {'alpha': 7.107922074582895e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  32%|███▏      | 1621/5000 [00:38<01:56, 29.06it/s]

[I 2026-06-14 00:49:11,142] Trial 1617 finished with value: 0.4037450230872309 and parameters: {'alpha': 2.903380616733363e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,173] Trial 1618 finished with value: 0.40374470768944054 and parameters: {'alpha': 1.0131492649934809e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,209] Trial 1619 finished with value: 0.4037448751445314 and parameters: {'alpha': 1.6835427999977374e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,267] Trial 1620 finished with value: 0.403744906149168 and parameters: {'alpha': 1.7918873968086203e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,315] Trial 1621 finished with value: 0.4037446513313868 and parameters: {'alpha': 1.0114221943355117e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  33%|███▎      | 1628/5000 [00:38<02:01, 27.66it/s]

[I 2026-06-14 00:49:11,359] Trial 1622 finished with value: 0.403745344688438 and parameters: {'alpha': 1.401430727474027e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,397] Trial 1623 finished with value: 0.4037452795383134 and parameters: {'alpha': 3.98912829959335e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,441] Trial 1624 finished with value: 0.40374506629005524 and parameters: {'alpha': 2.6438827823477067e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,480] Trial 1625 finished with value: 0.40374476546788446 and parameters: {'alpha': 1.65357307771723e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,509] Trial 1626 finished with value: 0.40374524619028807 and parameters: {'alpha': 4.1109165582978854e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,543] Trial 1627 finished with value: 0.4037455218033299 and parameters: {'alpha': 0.16587507666133525}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  33%|███▎      | 1634/5000 [00:39<01:59, 28.13it/s]

[I 2026-06-14 00:49:11,578] Trial 1628 finished with value: 0.40374491620098035 and parameters: {'alpha': 1.673440701573323e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,610] Trial 1629 finished with value: 0.4037446032939371 and parameters: {'alpha': 1.0112975881115913e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,650] Trial 1630 finished with value: 0.40374500598612645 and parameters: {'alpha': 2.7649016090842904e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,689] Trial 1631 finished with value: 0.40374526687661244 and parameters: {'alpha': 5.06291341513953e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,725] Trial 1632 finished with value: 0.4037442814316999 and parameters: {'alpha': 1.0042600196191685e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,756] Trial 1633 finished with value: 0.4037445054394891 and parameters: {'alpha': 1.0026101439410852e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  33%|███▎      | 1640/5000 [00:39<02:00, 27.93it/s]

[I 2026-06-14 00:49:11,793] Trial 1634 finished with value: 0.4037446663585583 and parameters: {'alpha': 1.0014073296124839e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,826] Trial 1635 finished with value: 0.4037450122292348 and parameters: {'alpha': 2.5146220519363095e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,861] Trial 1636 finished with value: 0.40374485991569653 and parameters: {'alpha': 1.6783288600120608e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,900] Trial 1637 finished with value: 0.4037453170846714 and parameters: {'alpha': 8.138888226017837e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,933] Trial 1638 finished with value: 0.4037449865732101 and parameters: {'alpha': 2.6663895011379874e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:11,970] Trial 1639 finished with value: 0.4037447537874396 and parameters: {'alpha': 1.012726350035443e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  33%|███▎      | 1646/5000 [00:39<01:57, 28.51it/s]

[I 2026-06-14 00:49:12,002] Trial 1640 finished with value: 0.40374497777226215 and parameters: {'alpha': 1.8345980608236272e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,033] Trial 1641 finished with value: 0.40374528863190423 and parameters: {'alpha': 4.204190407831559e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,067] Trial 1642 finished with value: 0.4037448251344387 and parameters: {'alpha': 1.752761803757314e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,104] Trial 1643 finished with value: 0.40374482460109934 and parameters: {'alpha': 1.743066699308378e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,137] Trial 1644 finished with value: 0.4037443358408031 and parameters: {'alpha': 1.0108088626098417e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,165] Trial 1645 finished with value: 0.4037450991315887 and parameters: {'alpha': 2.80251530189247e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,197] Trial 1646 finished with value: 0.40374527889807404 and parameters: {'alpha': 5.412174785028838e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  33%|███▎      | 1652/5000 [00:39<01:55, 29.03it/s]

[I 2026-06-14 00:49:12,228] Trial 1647 finished with value: 0.4037449576075361 and parameters: {'alpha': 1.7331970157436806e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,265] Trial 1648 finished with value: 0.4037450910417741 and parameters: {'alpha': 2.8974362859549634e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,299] Trial 1649 finished with value: 0.4037447422776967 and parameters: {'alpha': 1.7481627268202088e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,337] Trial 1650 finished with value: 0.4037448101229838 and parameters: {'alpha': 1.6754505302949286e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,371] Trial 1651 finished with value: 0.4037444033419539 and parameters: {'alpha': 1.0087723236550094e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,400] Trial 1652 finished with value: 0.4037452906956606 and parameters: {'alpha': 8.962252564475923e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  33%|███▎      | 1659/5000 [00:39<01:50, 30.37it/s]

[I 2026-06-14 00:49:12,430] Trial 1653 finished with value: 0.4037451573408313 and parameters: {'alpha': 3.855635471513345e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,464] Trial 1654 finished with value: 0.4037449666857152 and parameters: {'alpha': 2.6815212768361566e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,500] Trial 1655 finished with value: 0.40374488114899637 and parameters: {'alpha': 1.7045219339594076e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,531] Trial 1656 finished with value: 0.40374488634394196 and parameters: {'alpha': 1.7007282409770087e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,562] Trial 1657 finished with value: 0.4037452877060586 and parameters: {'alpha': 5.8356996442425746e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,592] Trial 1658 finished with value: 0.40374509396747127 and parameters: {'alpha': 2.8136060414844104e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  33%|███▎      | 1665/5000 [00:40<01:54, 29.07it/s]

[I 2026-06-14 00:49:12,637] Trial 1659 finished with value: 0.4037447588570657 and parameters: {'alpha': 1.6441750078521098e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,675] Trial 1660 finished with value: 0.4037451363594963 and parameters: {'alpha': 3.1224192873666426e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,708] Trial 1661 finished with value: 0.4037447483128972 and parameters: {'alpha': 1.7285792856636716e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,741] Trial 1662 finished with value: 0.4037449172895879 and parameters: {'alpha': 1.6781741306708484e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,776] Trial 1663 finished with value: 0.4037452404898917 and parameters: {'alpha': 4.694007254830804e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,808] Trial 1664 finished with value: 0.40374472516104 and parameters: {'alpha': 1.657989343156599e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,837] Trial 1665 finished with value: 0.4037450104903926 and parameters: {'alpha': 2.9018596992712483e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  33%|███▎      | 1672/5000 [00:40<01:53, 29.25it/s]

[I 2026-06-14 00:49:12,870] Trial 1666 finished with value: 0.40374432497900775 and parameters: {'alpha': 1.0012669918094572e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,907] Trial 1667 finished with value: 0.40374535682458856 and parameters: {'alpha': 1.4899593099427271e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,945] Trial 1668 finished with value: 0.40374466713820667 and parameters: {'alpha': 1.0105944311989689e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:12,976] Trial 1669 finished with value: 0.4037450661646507 and parameters: {'alpha': 2.732239326278e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,011] Trial 1670 finished with value: 0.4037444970608563 and parameters: {'alpha': 1.0167616531311429e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,041] Trial 1671 finished with value: 0.40374524251915095 and parameters: {'alpha': 6.244071047998348e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,069] Trial 1672 finished with value: 0.40374540685745197 and parameters: {'alpha': 0.0005269083465094855}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  34%|███▎      | 1679/5000 [00:40<01:48, 30.64it/s]

[I 2026-06-14 00:49:13,100] Trial 1673 finished with value: 0.4037448452560889 and parameters: {'alpha': 1.6868663002451663e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,135] Trial 1674 finished with value: 0.4037450246983129 and parameters: {'alpha': 2.7072586970893024e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,165] Trial 1675 finished with value: 0.40374428347988417 and parameters: {'alpha': 1.0289943849986654e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,194] Trial 1676 finished with value: 0.4037447243107587 and parameters: {'alpha': 1.0118644257822451e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,228] Trial 1677 finished with value: 0.4037451914674882 and parameters: {'alpha': 4.180755733409268e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,262] Trial 1678 finished with value: 0.4037448342026008 and parameters: {'alpha': 1.7379932419445437e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,299] Trial 1679 finished with value: 0.4037449844500273 and parameters: {'alpha': 2.5783268663948767e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  34%|███▎      | 1686/5000 [00:40<01:46, 31.06it/s]

[I 2026-06-14 00:49:13,330] Trial 1680 finished with value: 0.4037452795688787 and parameters: {'alpha': 6.77002472778623e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,361] Trial 1681 finished with value: 0.4037448792566513 and parameters: {'alpha': 1.6719297691350215e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,393] Trial 1682 finished with value: 0.4037452604132728 and parameters: {'alpha': 3.734562703955328e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,424] Trial 1683 finished with value: 0.40374484404083083 and parameters: {'alpha': 1.6423796853576895e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,453] Trial 1684 finished with value: 0.40374470460502415 and parameters: {'alpha': 1.0301068870631792e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,484] Trial 1685 finished with value: 0.4037450384802752 and parameters: {'alpha': 2.611454735602163e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,515] Trial 1686 finished with value: 0.4037447800951407 and parameters: {'alpha': 1.0233547060715299e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  34%|███▍      | 1694/5000 [00:41<01:39, 33.36it/s]

[I 2026-06-14 00:49:13,541] Trial 1687 finished with value: 0.40374522399910856 and parameters: {'alpha': 4.411667599034739e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,568] Trial 1688 finished with value: 0.4037447211017396 and parameters: {'alpha': 1.0263439189392884e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,596] Trial 1689 finished with value: 0.40374505751144946 and parameters: {'alpha': 2.5617345648719328e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,625] Trial 1690 finished with value: 0.4037447907656988 and parameters: {'alpha': 1.8224918169895526e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,655] Trial 1691 finished with value: 0.40374484281149614 and parameters: {'alpha': 1.8145875113298593e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,682] Trial 1692 finished with value: 0.4037452080284923 and parameters: {'alpha': 4.354654565978753e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,709] Trial 1693 finished with value: 0.4037449650887582 and parameters: {'alpha': 1.6949794708015005e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,737] Trial 1694 finished with value: 0.4037445699942605 and parameters: {'alpha': 1.0166361533565053e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  34%|███▍      | 1702/5000 [00:41<01:34, 34.75it/s]

[I 2026-06-14 00:49:13,765] Trial 1695 finished with value: 0.4037453022721803 and parameters: {'alpha': 1.012940573122177e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,793] Trial 1696 finished with value: 0.40374441862724475 and parameters: {'alpha': 1.0083105920603351e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,821] Trial 1697 finished with value: 0.4037450871599233 and parameters: {'alpha': 2.7485320359867983e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,848] Trial 1698 finished with value: 0.4037445117394818 and parameters: {'alpha': 1.021027476511626e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,875] Trial 1699 finished with value: 0.40374472758193714 and parameters: {'alpha': 1.000349122501148e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,901] Trial 1700 finished with value: 0.4037450043667059 and parameters: {'alpha': 2.8363047405997886e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,929] Trial 1701 finished with value: 0.4037452902759238 and parameters: {'alpha': 6.745662971470227e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:13,957] Trial 1702 finished with value: 0.40374475055198306 and parameters: {'alpha': 1.8441557004059205e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  34%|███▍      | 1710/5000 [00:41<01:32, 35.66it/s]

[I 2026-06-14 00:49:13,986] Trial 1703 finished with value: 0.4037451825148111 and parameters: {'alpha': 4.129765522353211e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,015] Trial 1704 finished with value: 0.40374440482347607 and parameters: {'alpha': 1.0097595315659871e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,043] Trial 1705 finished with value: 0.40374429931352146 and parameters: {'alpha': 1.0098109192774019e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,071] Trial 1706 finished with value: 0.40374507731289566 and parameters: {'alpha': 2.744281531024377e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,097] Trial 1707 finished with value: 0.40374473076353273 and parameters: {'alpha': 1.731517644792461e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,122] Trial 1708 finished with value: 0.40374499608506287 and parameters: {'alpha': 2.5170661717540878e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,150] Trial 1709 finished with value: 0.40374475129242204 and parameters: {'alpha': 1.8229073560498517e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,178] Trial 1710 finished with value: 0.4037444419063743 and parameters: {'alpha': 1.0005356307760443e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  34%|███▍      | 1718/5000 [00:41<01:32, 35.61it/s]

[I 2026-06-14 00:49:14,205] Trial 1711 finished with value: 0.4037452279504968 and parameters: {'alpha': 4.6072192663283204e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,235] Trial 1712 finished with value: 0.4037447962666204 and parameters: {'alpha': 1.6614430137423407e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,262] Trial 1713 finished with value: 0.4037450051887133 and parameters: {'alpha': 2.857208861515603e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,290] Trial 1714 finished with value: 0.4037452853177473 and parameters: {'alpha': 8.190754214258276e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,317] Trial 1715 finished with value: 0.40374430933213146 and parameters: {'alpha': 1.004255247860193e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,345] Trial 1716 finished with value: 0.40374474709463815 and parameters: {'alpha': 1.7295204429849143e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,373] Trial 1717 finished with value: 0.4037443548175828 and parameters: {'alpha': 1.0047161328429929e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,404] Trial 1718 finished with value: 0.40374520634882033 and parameters: {'alpha': 4.1847726083633046e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  35%|███▍      | 1726/5000 [00:41<01:35, 34.23it/s]

[I 2026-06-14 00:49:14,432] Trial 1719 finished with value: 0.4037450189779993 and parameters: {'alpha': 2.4752250744018914e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,467] Trial 1720 finished with value: 0.4037450042814351 and parameters: {'alpha': 1.8639949015102595e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,499] Trial 1721 finished with value: 0.40374536579455406 and parameters: {'alpha': 2.2610481071335847e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,530] Trial 1722 finished with value: 0.40374491712634053 and parameters: {'alpha': 1.7085423076868696e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,559] Trial 1723 finished with value: 0.40374528423055117 and parameters: {'alpha': 4.3191700925706774e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,593] Trial 1724 finished with value: 0.4037449851108797 and parameters: {'alpha': 2.6152693939814697e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,619] Trial 1725 finished with value: 0.40374494241630005 and parameters: {'alpha': 1.681236785219315e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  35%|███▍      | 1734/5000 [00:42<01:33, 35.06it/s]

[I 2026-06-14 00:49:14,647] Trial 1726 finished with value: 0.4037443426968856 and parameters: {'alpha': 1.0189619713533156e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,675] Trial 1727 finished with value: 0.40374520159670174 and parameters: {'alpha': 3.969052822583639e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,706] Trial 1728 finished with value: 0.40374479023053367 and parameters: {'alpha': 1.8336551487966287e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,734] Trial 1729 finished with value: 0.4037453225775044 and parameters: {'alpha': 1.0165813728838283e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,762] Trial 1730 finished with value: 0.4037450589948208 and parameters: {'alpha': 2.7097217846744606e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,788] Trial 1731 finished with value: 0.40374479936163377 and parameters: {'alpha': 1.699442739679167e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,815] Trial 1732 finished with value: 0.4037452474086651 and parameters: {'alpha': 6.682429343897232e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,842] Trial 1733 finished with value: 0.403744314441513 and parameters: {'alpha': 1.0177072998760864e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  35%|███▍      | 1742/5000 [00:42<01:32, 35.36it/s]

[I 2026-06-14 00:49:14,871] Trial 1734 finished with value: 0.4037449395472369 and parameters: {'alpha': 1.7443713289456518e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,899] Trial 1735 finished with value: 0.40374475112400626 and parameters: {'alpha': 1.021213412530142e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,928] Trial 1736 finished with value: 0.4037452457020113 and parameters: {'alpha': 3.7920973845572173e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,956] Trial 1737 finished with value: 0.4037450823406011 and parameters: {'alpha': 2.726205017639815e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:14,984] Trial 1738 finished with value: 0.4037444346918992 and parameters: {'alpha': 1.0066550958520263e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,011] Trial 1739 finished with value: 0.403744758399104 and parameters: {'alpha': 1.748873831380271e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,039] Trial 1740 finished with value: 0.4037452732114191 and parameters: {'alpha': 6.074476091496858e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,066] Trial 1741 finished with value: 0.40374507734792714 and parameters: {'alpha': 2.6571539823906754e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  35%|███▍      | 1748/5000 [00:42<01:31, 35.52it/s]

[I 2026-06-14 00:49:15,096] Trial 1742 finished with value: 0.4037449064803619 and parameters: {'alpha': 1.7686680553130016e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,123] Trial 1743 finished with value: 0.4037448870026896 and parameters: {'alpha': 1.7216533238144678e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,151] Trial 1744 finished with value: 0.4037452975954739 and parameters: {'alpha': 4.959261972794353e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,179] Trial 1745 finished with value: 0.4037445100934384 and parameters: {'alpha': 1.0056681710433929e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,213] Trial 1746 finished with value: 0.4037631162963464 and parameters: {'alpha': 9.588281091137564}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,244] Trial 1747 finished with value: 0.40374502009613306 and parameters: {'alpha': 2.850899727906662e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,274] Trial 1748 finished with value: 0.40374475990798336 and parameters: {'alpha': 1.692190132219699e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:49:15,299] Trial 1749 finished with value: 0.40374539834696843 and parameters: {'alpha': 8.122505615963826e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,328] Trial 1750 finished with value: 0.40374467791151936 and parameters: {'alpha': 1.0023540107567521e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,358] Trial 1751 finished with value: 0.40374512083122155 and parameters: {'alpha': 3.154719857989345e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,386] Trial 1752 finished with value: 0.4037443055815719 and parameters: {'alpha': 1.0026550207360859e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,415] Trial 1753 finished with value: 0.4037445296005755 and parameters: {'alpha': 1.0014673383913454e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,448] Trial 1754 finished with value: 0.4037449799087154 and parameters: {'alpha': 2.6411630333396734e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,476] Trial 1755 finished with value: 0.4037453491284785 and parameters: {'alpha': 1.3439845937287977e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  35%|███▌      | 1763/5000 [00:43<01:32, 34.88it/s]

[I 2026-06-14 00:49:15,501] Trial 1756 finished with value: 0.4037444597133803 and parameters: {'alpha': 1.003472768033404e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,528] Trial 1757 finished with value: 0.40374526117769755 and parameters: {'alpha': 4.3944278121619e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,556] Trial 1758 finished with value: 0.4037442936561021 and parameters: {'alpha': 1.0035039769636822e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,588] Trial 1759 finished with value: 0.4037449608839047 and parameters: {'alpha': 1.7804689355161778e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,614] Trial 1760 finished with value: 0.4037448690646232 and parameters: {'alpha': 1.8661904066896284e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,643] Trial 1761 finished with value: 0.4037450026357053 and parameters: {'alpha': 2.669254839780379e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,671] Trial 1762 finished with value: 0.4037447586323169 and parameters: {'alpha': 1.7355535859489855e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,698] Trial 1763 finished with value: 0.403745224431212 and parameters: {'alpha': 6.012779002172663e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  35%|███▌      | 1771/5000 [00:43<01:31, 35.16it/s]

[I 2026-06-14 00:49:15,726] Trial 1764 finished with value: 0.40374439290713326 and parameters: {'alpha': 1.0090915823839344e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,753] Trial 1765 finished with value: 0.4037452655983062 and parameters: {'alpha': 3.59597517115473e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,784] Trial 1766 finished with value: 0.40374495487841516 and parameters: {'alpha': 1.7780601905156438e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,811] Trial 1767 finished with value: 0.403744814413412 and parameters: {'alpha': 1.7075367065279125e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,839] Trial 1768 finished with value: 0.40374505358254237 and parameters: {'alpha': 2.7918636412901228e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,867] Trial 1769 finished with value: 0.4037452352827604 and parameters: {'alpha': 6.120717321303737e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,897] Trial 1770 finished with value: 0.403744443022644 and parameters: {'alpha': 1.005648086870064e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,924] Trial 1771 finished with value: 0.40374484708902053 and parameters: {'alpha': 1.7655088067919453e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:49:15,952] Trial 1772 finished with value: 0.403745078322106 and parameters: {'alpha': 2.6765876346198045e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:15,981] Trial 1773 finished with value: 0.45449162980154223 and parameters: {'alpha': 5705.113344980305}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,010] Trial 1774 finished with value: 0.4037448800964498 and parameters: {'alpha': 1.7244359223399743e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,039] Trial 1775 finished with value: 0.4037452369463723 and parameters: {'alpha': 4.0227033353257176e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,066] Trial 1776 finished with value: 0.40374480466532814 and parameters: {'alpha': 1.877537093062722e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,094] Trial 1777 finished with value: 0.40374482794037897 and parameters: {'alpha': 1.7463188373800463e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,123] Trial 1778 finished with value: 0.4037453056420322 and parameters: {'alpha': 9.234314717099909e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,151] Trial 1779 finished with value: 0.40374523538227847 and parameters: {'alpha': 3.885310250819882e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  36%|███▌      | 1787/5000 [00:43<01:30, 35.58it/s]

[I 2026-06-14 00:49:16,178] Trial 1780 finished with value: 0.4037448865414648 and parameters: {'alpha': 1.731978781339284e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,207] Trial 1781 finished with value: 0.40374474579458675 and parameters: {'alpha': 1.0183619484068167e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,236] Trial 1782 finished with value: 0.40374513751700464 and parameters: {'alpha': 3.0779342116433e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,264] Trial 1783 finished with value: 0.40374483602195477 and parameters: {'alpha': 1.8153114045673072e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,292] Trial 1784 finished with value: 0.40374529183465585 and parameters: {'alpha': 6.649809329201646e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,318] Trial 1785 finished with value: 0.40374485466367754 and parameters: {'alpha': 1.7022328698790793e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,346] Trial 1786 finished with value: 0.4037444037721324 and parameters: {'alpha': 1.0092234909682406e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,374] Trial 1787 finished with value: 0.40374433526322945 and parameters: {'alpha': 1.0048209414803127e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  36%|███▌      | 1795/5000 [00:43<01:30, 35.44it/s]

[I 2026-06-14 00:49:16,403] Trial 1788 finished with value: 0.4037450822063062 and parameters: {'alpha': 2.9742675310470304e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,431] Trial 1789 finished with value: 0.40374524707003384 and parameters: {'alpha': 3.943261176280409e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,462] Trial 1790 finished with value: 0.4037447758720259 and parameters: {'alpha': 1.7047155771557534e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,489] Trial 1791 finished with value: 0.40374495294871016 and parameters: {'alpha': 2.5178072977474372e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,518] Trial 1792 finished with value: 0.4037443899915549 and parameters: {'alpha': 1.0301788047474938e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,545] Trial 1793 finished with value: 0.40374528403693244 and parameters: {'alpha': 3.977400907030757e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,574] Trial 1794 finished with value: 0.40374485576513075 and parameters: {'alpha': 1.6252527931271242e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,601] Trial 1795 finished with value: 0.4037450823436192 and parameters: {'alpha': 2.7432786630362445e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  36%|███▌      | 1803/5000 [00:44<01:29, 35.77it/s]

[I 2026-06-14 00:49:16,628] Trial 1796 finished with value: 0.40374478883822273 and parameters: {'alpha': 1.7300947682433978e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,656] Trial 1797 finished with value: 0.4058144220525268 and parameters: {'alpha': 563.1722074576865}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,685] Trial 1798 finished with value: 0.403745255464049 and parameters: {'alpha': 6.174165571746106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,713] Trial 1799 finished with value: 0.4037448903058932 and parameters: {'alpha': 1.8257498484894393e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,740] Trial 1800 finished with value: 0.40374500015644865 and parameters: {'alpha': 2.8849951754459232e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,767] Trial 1801 finished with value: 0.40374531949164644 and parameters: {'alpha': 1.1458114824003453e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,794] Trial 1802 finished with value: 0.4037446958940106 and parameters: {'alpha': 1.6005120327464018e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,822] Trial 1803 finished with value: 0.4037446743887237 and parameters: {'alpha': 1.6200177255374597e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  36%|███▌      | 1811/5000 [00:44<01:29, 35.52it/s]

[I 2026-06-14 00:49:16,850] Trial 1804 finished with value: 0.40374433795369064 and parameters: {'alpha': 1.032439798116928e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,878] Trial 1805 finished with value: 0.403744462724618 and parameters: {'alpha': 1.0198401143201375e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,908] Trial 1806 finished with value: 0.40374442314600695 and parameters: {'alpha': 1.0190940525298627e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,937] Trial 1807 finished with value: 0.40374525767828867 and parameters: {'alpha': 4.52685876870852e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,963] Trial 1808 finished with value: 0.4037451545816531 and parameters: {'alpha': 3.0395063341758225e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:16,991] Trial 1809 finished with value: 0.40374460090905934 and parameters: {'alpha': 1.0230337132761017e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,020] Trial 1810 finished with value: 0.40374540765464734 and parameters: {'alpha': 0.0017141083946868997}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,046] Trial 1811 finished with value: 0.4037450208268107 and parameters: {'alpha': 2.6089326526009294e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  36%|███▋      | 1819/5000 [00:44<01:29, 35.39it/s]

[I 2026-06-14 00:49:17,073] Trial 1812 finished with value: 0.4037452619655662 and parameters: {'alpha': 7.234130962076728e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,103] Trial 1813 finished with value: 0.4037449804990143 and parameters: {'alpha': 2.6654906060746148e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,134] Trial 1814 finished with value: 0.4037446180938362 and parameters: {'alpha': 1.000630470915232e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,162] Trial 1815 finished with value: 0.40374481593778316 and parameters: {'alpha': 1.716941776866773e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,191] Trial 1816 finished with value: 0.40374519945504167 and parameters: {'alpha': 4.345198766855616e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,219] Trial 1817 finished with value: 0.40374494241618486 and parameters: {'alpha': 1.706959738346582e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,247] Trial 1818 finished with value: 0.4037450279368076 and parameters: {'alpha': 2.760948530846519e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,275] Trial 1819 finished with value: 0.4037443706679081 and parameters: {'alpha': 1.0136771619793322e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  37%|███▋      | 1826/5000 [00:44<01:30, 35.10it/s]

[I 2026-06-14 00:49:17,302] Trial 1820 finished with value: 0.4037442715497278 and parameters: {'alpha': 1.0016463439256775e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,332] Trial 1821 finished with value: 0.4037447125201706 and parameters: {'alpha': 1.0100051181273131e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,362] Trial 1822 finished with value: 0.40374498387368374 and parameters: {'alpha': 1.8006093065204658e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,391] Trial 1823 finished with value: 0.40374438743354885 and parameters: {'alpha': 1.0147251762386232e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,418] Trial 1824 finished with value: 0.40374526250444254 and parameters: {'alpha': 5.0343602651918725e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,447] Trial 1825 finished with value: 0.4037450007734296 and parameters: {'alpha': 2.5302258381273763e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,477] Trial 1826 finished with value: 0.40374478457029056 and parameters: {'alpha': 1.656036445344211e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  37%|███▋      | 1834/5000 [00:45<01:29, 35.36it/s]

[I 2026-06-14 00:49:17,505] Trial 1827 finished with value: 0.40374505849544723 and parameters: {'alpha': 2.7801237359122205e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,533] Trial 1828 finished with value: 0.40374428066768664 and parameters: {'alpha': 1.0053793151790624e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,562] Trial 1829 finished with value: 0.5108631840427078 and parameters: {'alpha': 16064.451222289803}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,589] Trial 1830 finished with value: 0.40374492465282824 and parameters: {'alpha': 1.7343907843549104e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,617] Trial 1831 finished with value: 0.4037445894948316 and parameters: {'alpha': 1.0198856128396558e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,644] Trial 1832 finished with value: 0.403745214228502 and parameters: {'alpha': 4.2610549161113775e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,674] Trial 1833 finished with value: 0.4037452864479547 and parameters: {'alpha': 7.277973714583405e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,703] Trial 1834 finished with value: 0.4037444478259966 and parameters: {'alpha': 1.0095131024298137e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  37%|███▋      | 1842/5000 [00:45<01:28, 35.49it/s]

[I 2026-06-14 00:49:17,731] Trial 1835 finished with value: 0.4037450191573453 and parameters: {'alpha': 2.8640035223085157e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,759] Trial 1836 finished with value: 0.4037453572552959 and parameters: {'alpha': 1.801920642681896e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,788] Trial 1837 finished with value: 0.4037447842523718 and parameters: {'alpha': 1.8009787761711728e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,816] Trial 1838 finished with value: 0.40374438571568 and parameters: {'alpha': 1.003320180578355e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,844] Trial 1839 finished with value: 0.40374507599961895 and parameters: {'alpha': 2.5784087315770553e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,870] Trial 1840 finished with value: 0.40374497323723574 and parameters: {'alpha': 1.8960588541592365e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,897] Trial 1841 finished with value: 0.4037445917142453 and parameters: {'alpha': 1.0000879868237837e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,926] Trial 1842 finished with value: 0.4037452334227513 and parameters: {'alpha': 4.511215086597168e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  37%|███▋      | 1850/5000 [00:45<01:29, 35.13it/s]

[I 2026-06-14 00:49:17,956] Trial 1843 finished with value: 0.40374483631734986 and parameters: {'alpha': 1.765179397725995e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:17,984] Trial 1844 finished with value: 0.4037449933692131 and parameters: {'alpha': 2.6757980042858955e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,013] Trial 1845 finished with value: 0.40374529420430194 and parameters: {'alpha': 7.729385221517257e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,043] Trial 1846 finished with value: 0.4037443711390658 and parameters: {'alpha': 1.0142342994870548e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,070] Trial 1847 finished with value: 0.40374520127828084 and parameters: {'alpha': 4.020216700228447e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,098] Trial 1848 finished with value: 0.40374479967943205 and parameters: {'alpha': 1.7214927410351513e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,127] Trial 1849 finished with value: 0.40374497924360053 and parameters: {'alpha': 1.743067867792192e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,156] Trial 1850 finished with value: 0.4037450750538546 and parameters: {'alpha': 2.6734920418431528e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  37%|███▋      | 1858/5000 [00:45<01:31, 34.32it/s]

[I 2026-06-14 00:49:18,185] Trial 1851 finished with value: 0.40374575099020693 and parameters: {'alpha': 0.462637598814299}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,215] Trial 1852 finished with value: 0.4037449075826257 and parameters: {'alpha': 1.7115559298562187e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,244] Trial 1853 finished with value: 0.4037447467942027 and parameters: {'alpha': 1.013647159301702e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,274] Trial 1854 finished with value: 0.4037452341515259 and parameters: {'alpha': 4.107281472098391e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,306] Trial 1855 finished with value: 0.40374427020934806 and parameters: {'alpha': 1.0096611710915874e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,335] Trial 1856 finished with value: 0.4037447465732044 and parameters: {'alpha': 1.0117469088634879e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,365] Trial 1857 finished with value: 0.4037450275688636 and parameters: {'alpha': 2.7491307560986754e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  37%|███▋      | 1865/5000 [00:45<01:31, 34.27it/s]

[I 2026-06-14 00:49:18,394] Trial 1858 finished with value: 0.4037448566959632 and parameters: {'alpha': 1.756422379754937e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,424] Trial 1859 finished with value: 0.4037453080206545 and parameters: {'alpha': 5.3378350637365104e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,453] Trial 1860 finished with value: 0.40374433394579234 and parameters: {'alpha': 1.0134444814955089e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,483] Trial 1861 finished with value: 0.40374495983270264 and parameters: {'alpha': 1.7514055640454977e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,514] Trial 1862 finished with value: 0.4037450325926842 and parameters: {'alpha': 2.779701800652749e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,541] Trial 1863 finished with value: 0.4037453039596841 and parameters: {'alpha': 9.476360930684622e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,568] Trial 1864 finished with value: 0.4037450005763611 and parameters: {'alpha': 2.7703200466252863e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,595] Trial 1865 finished with value: 0.4037447671874842 and parameters: {'alpha': 1.791050460347516e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  37%|███▋      | 1872/5000 [00:46<01:30, 34.40it/s]

[I 2026-06-14 00:49:18,625] Trial 1866 finished with value: 0.4037448098008905 and parameters: {'alpha': 1.672946904746702e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,655] Trial 1867 finished with value: 0.40374529447788904 and parameters: {'alpha': 5.469416603583833e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,684] Trial 1868 finished with value: 0.4037448776813886 and parameters: {'alpha': 1.679868654846792e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,714] Trial 1869 finished with value: 0.40374518016572924 and parameters: {'alpha': 3.771650948180229e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,743] Trial 1870 finished with value: 0.40374435645365714 and parameters: {'alpha': 1.0060681847313453e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,772] Trial 1871 finished with value: 0.4037454052162739 and parameters: {'alpha': 5.45418514565448e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,801] Trial 1872 finished with value: 0.40374508360653644 and parameters: {'alpha': 2.9195454047750103e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  38%|███▊      | 1878/5000 [00:46<01:30, 34.56it/s]

[I 2026-06-14 00:49:18,829] Trial 1873 finished with value: 0.4037447397641253 and parameters: {'alpha': 1.649121540580034e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,858] Trial 1874 finished with value: 0.4037453712165417 and parameters: {'alpha': 3.2316033231732906e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,888] Trial 1875 finished with value: 0.4037450467415555 and parameters: {'alpha': 2.6041065080557723e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,917] Trial 1876 finished with value: 0.4037449625590887 and parameters: {'alpha': 1.660115808083956e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,944] Trial 1877 finished with value: 0.40374432183669884 and parameters: {'alpha': 1.0059104796453269e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:18,979] Trial 1878 finished with value: 0.4037443298106905 and parameters: {'alpha': 1.0037587390238597e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  38%|███▊      | 1886/5000 [00:46<01:41, 30.62it/s]

[I 2026-06-14 00:49:19,050] Trial 1879 finished with value: 0.40374530163301875 and parameters: {'alpha': 4.291720274697954e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,090] Trial 1880 finished with value: 0.40374492986617466 and parameters: {'alpha': 1.827760103849458e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,128] Trial 1881 finished with value: 0.4037445419885537 and parameters: {'alpha': 1.0088822364673908e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,160] Trial 1882 finished with value: 0.40374532702257115 and parameters: {'alpha': 1.2154328359894498e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,190] Trial 1883 finished with value: 0.40374500341776215 and parameters: {'alpha': 2.751295552211846e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,217] Trial 1884 finished with value: 0.4037452745086833 and parameters: {'alpha': 5.9424128108224444e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,244] Trial 1885 finished with value: 0.4037448663824061 and parameters: {'alpha': 1.8845098285642376e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  38%|███▊      | 1892/5000 [00:46<01:38, 31.43it/s]

[I 2026-06-14 00:49:19,275] Trial 1886 finished with value: 0.4037449506278089 and parameters: {'alpha': 1.7079240339981443e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,310] Trial 1887 finished with value: 0.4037444389265546 and parameters: {'alpha': 1.007209664568616e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,338] Trial 1888 finished with value: 0.4037451936365708 and parameters: {'alpha': 3.747769180887406e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,365] Trial 1889 finished with value: 0.403744923815408 and parameters: {'alpha': 1.7952394377284285e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,395] Trial 1890 finished with value: 0.403744445085015 and parameters: {'alpha': 1.0170313066948121e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,423] Trial 1891 finished with value: 0.40374506028636525 and parameters: {'alpha': 2.738304753492549e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,450] Trial 1892 finished with value: 0.4037452913582577 and parameters: {'alpha': 7.157364187811991e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  38%|███▊      | 1900/5000 [00:47<01:33, 33.24it/s]

[I 2026-06-14 00:49:19,478] Trial 1893 finished with value: 0.40374455041799984 and parameters: {'alpha': 1.010356649644438e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,507] Trial 1894 finished with value: 0.4037450487899067 and parameters: {'alpha': 2.669208286666391e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,536] Trial 1895 finished with value: 0.4037448395882644 and parameters: {'alpha': 1.7314186151673166e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,564] Trial 1896 finished with value: 0.4037452672470731 and parameters: {'alpha': 4.53918906425831e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,591] Trial 1897 finished with value: 0.4037448107339576 and parameters: {'alpha': 1.6423019534113453e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,621] Trial 1898 finished with value: 0.4037450178824076 and parameters: {'alpha': 2.8116958221156454e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,648] Trial 1899 finished with value: 0.4037448464283808 and parameters: {'alpha': 1.6536146235121384e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,679] Trial 1900 finished with value: 0.40374436258312524 and parameters: {'alpha': 1.004180689571428e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  38%|███▊      | 1908/5000 [00:47<01:30, 34.10it/s]

[I 2026-06-14 00:49:19,708] Trial 1901 finished with value: 0.4037452513042446 and parameters: {'alpha': 4.728559770100134e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,738] Trial 1902 finished with value: 0.40374500232695565 and parameters: {'alpha': 2.6192523843680833e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,765] Trial 1903 finished with value: 0.4037449658457845 and parameters: {'alpha': 1.8842776142635703e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,793] Trial 1904 finished with value: 0.40374490437314076 and parameters: {'alpha': 1.7491881463750106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,822] Trial 1905 finished with value: 0.4037452364932554 and parameters: {'alpha': 3.7859489293543896e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,851] Trial 1906 finished with value: 0.40374495530370036 and parameters: {'alpha': 1.7214125041001392e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,878] Trial 1907 finished with value: 0.40374532404282804 and parameters: {'alpha': 1.025358595881341e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,907] Trial 1908 finished with value: 0.40374498873352854 and parameters: {'alpha': 1.7153385923379417e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  38%|███▊      | 1915/5000 [00:47<01:30, 33.93it/s]

[I 2026-06-14 00:49:19,936] Trial 1909 finished with value: 0.4037451754070552 and parameters: {'alpha': 3.574109954202103e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,968] Trial 1910 finished with value: 0.4037447615010295 and parameters: {'alpha': 1.6955404528278152e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:19,997] Trial 1911 finished with value: 0.4037452644419662 and parameters: {'alpha': 6.859716045271103e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,029] Trial 1912 finished with value: 0.40374441010687295 and parameters: {'alpha': 1.0194093002702009e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,056] Trial 1913 finished with value: 0.40374474708814534 and parameters: {'alpha': 1.017232137398782e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,085] Trial 1914 finished with value: 0.40374499114876666 and parameters: {'alpha': 2.7308365834379e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,114] Trial 1915 finished with value: 0.4037450372032017 and parameters: {'alpha': 2.744603726124674e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  38%|███▊      | 1923/5000 [00:47<01:28, 34.58it/s]

[I 2026-06-14 00:49:20,142] Trial 1916 finished with value: 0.403744838312502 and parameters: {'alpha': 1.630921628709091e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,171] Trial 1917 finished with value: 0.40374526212004314 and parameters: {'alpha': 4.291521379791285e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,200] Trial 1918 finished with value: 0.4037450948701264 and parameters: {'alpha': 2.7397201460944244e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,228] Trial 1919 finished with value: 0.40374460287208946 and parameters: {'alpha': 1.018113878009055e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,256] Trial 1920 finished with value: 0.4037447403612091 and parameters: {'alpha': 1.7124484772468485e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,285] Trial 1921 finished with value: 0.40374482319405486 and parameters: {'alpha': 1.6953105923679787e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,313] Trial 1922 finished with value: 0.40374471390834193 and parameters: {'alpha': 1.0201396256221716e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,343] Trial 1923 finished with value: 0.4037452509426987 and parameters: {'alpha': 6.117257136199275e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  39%|███▊      | 1930/5000 [00:47<01:30, 34.10it/s]

[I 2026-06-14 00:49:20,371] Trial 1924 finished with value: 0.4037449949456572 and parameters: {'alpha': 2.5679389635480896e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,402] Trial 1925 finished with value: 0.40374490470906355 and parameters: {'alpha': 1.796621753477486e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,436] Trial 1926 finished with value: 0.4037446721866886 and parameters: {'alpha': 1.0034793790056888e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,466] Trial 1927 finished with value: 0.4037452139277309 and parameters: {'alpha': 3.873401215460032e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,495] Trial 1928 finished with value: 0.40374445562846867 and parameters: {'alpha': 1.0050443087347839e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,522] Trial 1929 finished with value: 0.40374502994743183 and parameters: {'alpha': 2.724009503962651e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,551] Trial 1930 finished with value: 0.4037443857769316 and parameters: {'alpha': 1.0104923843536245e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  39%|███▉      | 1938/5000 [00:48<01:29, 34.04it/s]

[I 2026-06-14 00:49:20,582] Trial 1931 finished with value: 0.4037453389084594 and parameters: {'alpha': 1.397072914484507e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,610] Trial 1932 finished with value: 0.4037445169462385 and parameters: {'alpha': 1.0001121471667025e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,640] Trial 1933 finished with value: 0.4037452525821845 and parameters: {'alpha': 4.569543191084432e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,669] Trial 1934 finished with value: 0.4037448864688604 and parameters: {'alpha': 1.7494250994957777e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,700] Trial 1935 finished with value: 0.40374465335668897 and parameters: {'alpha': 1.0055730641043216e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,729] Trial 1936 finished with value: 0.4037450600843172 and parameters: {'alpha': 2.7037829539740808e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,758] Trial 1937 finished with value: 0.40374491899195475 and parameters: {'alpha': 1.827855188423719e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  39%|███▉      | 1944/5000 [00:48<01:29, 34.11it/s]

[I 2026-06-14 00:49:20,786] Trial 1938 finished with value: 0.4037445328280914 and parameters: {'alpha': 1.0003844712294688e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,815] Trial 1939 finished with value: 0.4037452698316475 and parameters: {'alpha': 7.083546793426662e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,845] Trial 1940 finished with value: 0.40374503081879115 and parameters: {'alpha': 2.549827352143886e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,874] Trial 1941 finished with value: 0.4037445134931809 and parameters: {'alpha': 1.0074967628963526e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,904] Trial 1942 finished with value: 0.4037452297110293 and parameters: {'alpha': 4.31342318763494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,934] Trial 1943 finished with value: 0.5589726301454341 and parameters: {'alpha': 51462.854313002346}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:20,961] Trial 1944 finished with value: 0.40374498119305796 and parameters: {'alpha': 2.47380554223444e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:49:20,990] Trial 1945 finished with value: 0.40374488154645144 and parameters: {'alpha': 1.719453259644057e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,022] Trial 1946 finished with value: 0.40374476929242353 and parameters: {'alpha': 1.761223936612267e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,052] Trial 1947 finished with value: 0.40374527827543916 and parameters: {'alpha': 5.0878290290510576e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,081] Trial 1948 finished with value: 0.4037449167924172 and parameters: {'alpha': 1.737262412907237e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,108] Trial 1949 finished with value: 0.4037447251329314 and parameters: {'alpha': 1.0048318188635537e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,142] Trial 1950 finished with value: 0.40374500605141994 and parameters: {'alpha': 2.9420503377305006e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,188] Trial 1951 finished with value: 0.4037449444097231 and parameters: {'alpha': 1.7201805095660802e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  39%|███▉      | 1958/5000 [00:48<01:39, 30.46it/s]

[I 2026-06-14 00:49:21,225] Trial 1952 finished with value: 0.4037452919154427 and parameters: {'alpha': 7.780538799933084e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,258] Trial 1953 finished with value: 0.4037454084718708 and parameters: {'alpha': 0.0029337745690709675}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,290] Trial 1954 finished with value: 0.4037450183172615 and parameters: {'alpha': 2.580700109679724e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,324] Trial 1955 finished with value: 0.40374517283671607 and parameters: {'alpha': 3.349127777877394e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,359] Trial 1956 finished with value: 0.40374493979207404 and parameters: {'alpha': 1.7117312640813982e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,397] Trial 1957 finished with value: 0.4037454462501751 and parameters: {'alpha': 0.05870401047695342}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  39%|███▉      | 1964/5000 [00:48<01:38, 30.94it/s]

[I 2026-06-14 00:49:21,432] Trial 1958 finished with value: 0.40374476138947835 and parameters: {'alpha': 1.6738690275018696e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,463] Trial 1959 finished with value: 0.4037452130076491 and parameters: {'alpha': 3.8832327568495766e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,494] Trial 1960 finished with value: 0.403744784175754 and parameters: {'alpha': 1.6911569210248428e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,523] Trial 1961 finished with value: 0.4037448252328521 and parameters: {'alpha': 1.7455668337892554e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,553] Trial 1962 finished with value: 0.40374638485206304 and parameters: {'alpha': 1.144936498629691}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,584] Trial 1963 finished with value: 0.4037451897399138 and parameters: {'alpha': 4.345761616101158e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,615] Trial 1964 finished with value: 0.4037448968695203 and parameters: {'alpha': 1.674576621575992e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  39%|███▉      | 1971/5000 [00:49<01:34, 31.98it/s]

[I 2026-06-14 00:49:21,646] Trial 1965 finished with value: 0.4037450492602954 and parameters: {'alpha': 2.9050323956638103e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,677] Trial 1966 finished with value: 0.4037453146552729 and parameters: {'alpha': 8.581694700135742e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,705] Trial 1967 finished with value: 0.40374431763667246 and parameters: {'alpha': 1.0325929275948615e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,737] Trial 1968 finished with value: 0.40374484414498135 and parameters: {'alpha': 1.7329329290068512e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,765] Trial 1969 finished with value: 0.4037445801830292 and parameters: {'alpha': 1.0208293498867845e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,795] Trial 1970 finished with value: 0.40374508309671564 and parameters: {'alpha': 2.8035371816315362e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,825] Trial 1971 finished with value: 0.40374528432932677 and parameters: {'alpha': 5.230893188175662e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  40%|███▉      | 1979/5000 [00:49<01:30, 33.30it/s]

[I 2026-06-14 00:49:21,852] Trial 1972 finished with value: 0.4037445503273937 and parameters: {'alpha': 1.0053299016808524e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,881] Trial 1973 finished with value: 0.40374501180333533 and parameters: {'alpha': 2.810973187039858e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,911] Trial 1974 finished with value: 0.40374540418266436 and parameters: {'alpha': 2.8593454847690065e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,940] Trial 1975 finished with value: 0.4037447663444719 and parameters: {'alpha': 1.7099784667862915e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,968] Trial 1976 finished with value: 0.40374472427727753 and parameters: {'alpha': 1.644311144824905e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:21,996] Trial 1977 finished with value: 0.40374522347999353 and parameters: {'alpha': 3.8630470104740905e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,026] Trial 1978 finished with value: 0.403744830770101 and parameters: {'alpha': 1.706544489749842e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,052] Trial 1979 finished with value: 0.40374533312749583 and parameters: {'alpha': 1.471169190193589e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  40%|███▉      | 1986/5000 [00:49<01:30, 33.14it/s]

[I 2026-06-14 00:49:22,080] Trial 1980 finished with value: 0.4037451024639004 and parameters: {'alpha': 2.8126851633645128e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,111] Trial 1981 finished with value: 0.40374474740867927 and parameters: {'alpha': 1.7423576718646977e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,144] Trial 1982 finished with value: 0.4037445320285186 and parameters: {'alpha': 1.006323168151942e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,174] Trial 1983 finished with value: 0.4037452667014053 and parameters: {'alpha': 7.160421144606566e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,207] Trial 1984 finished with value: 0.4037444070676033 and parameters: {'alpha': 1.0140560100810812e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,238] Trial 1985 finished with value: 0.4037444864367978 and parameters: {'alpha': 1.0065456758341212e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,272] Trial 1986 finished with value: 0.4037449600785465 and parameters: {'alpha': 2.522685105140408e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  40%|███▉      | 1994/5000 [00:49<01:33, 32.19it/s]

[I 2026-06-14 00:49:22,304] Trial 1987 finished with value: 0.4037452890855558 and parameters: {'alpha': 4.3677841433624874e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,337] Trial 1988 finished with value: 0.40374498536030795 and parameters: {'alpha': 1.775059988560548e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,372] Trial 1989 finished with value: 0.4037451107635911 and parameters: {'alpha': 2.7854590012384398e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,403] Trial 1990 finished with value: 0.4037445587670382 and parameters: {'alpha': 1.006684819426791e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,434] Trial 1991 finished with value: 0.40374493357728614 and parameters: {'alpha': 1.6869308392373017e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,463] Trial 1992 finished with value: 0.4037446832496022 and parameters: {'alpha': 1.0029885636398982e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,495] Trial 1993 finished with value: 0.4037452798126941 and parameters: {'alpha': 5.4364708969446285e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  40%|████      | 2000/5000 [00:50<01:32, 32.44it/s]

[I 2026-06-14 00:49:22,528] Trial 1994 finished with value: 0.40374501078483965 and parameters: {'alpha': 2.6834750309689958e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,559] Trial 1995 finished with value: 0.4037448001655917 and parameters: {'alpha': 1.794966547295328e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,588] Trial 1996 finished with value: 0.4037452440272112 and parameters: {'alpha': 3.97097771895449e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,617] Trial 1997 finished with value: 0.403744740739385 and parameters: {'alpha': 1.0048405863771071e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,646] Trial 1998 finished with value: 0.4037448108618191 and parameters: {'alpha': 1.69639189775037e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,673] Trial 1999 finished with value: 0.4037449791617641 and parameters: {'alpha': 2.716638947409212e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,702] Trial 2000 finished with value: 0.403744767521516 and parameters: {'alpha': 1.694581191858318e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  40%|████      | 2007/5000 [00:50<01:31, 32.75it/s]

[I 2026-06-14 00:49:22,732] Trial 2001 finished with value: 0.4037453066240657 and parameters: {'alpha': 8.137323770282067e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,763] Trial 2002 finished with value: 0.40374499305562733 and parameters: {'alpha': 2.8721048328971326e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,794] Trial 2003 finished with value: 0.4037447332011863 and parameters: {'alpha': 1.0279174198312588e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,825] Trial 2004 finished with value: 0.40374452207334155 and parameters: {'alpha': 1.0001325879050565e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,856] Trial 2005 finished with value: 0.40374528886093375 and parameters: {'alpha': 4.273542355343844e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,890] Trial 2006 finished with value: 0.40374489110598055 and parameters: {'alpha': 1.6814576679929982e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,922] Trial 2007 finished with value: 0.40374454592428954 and parameters: {'alpha': 1.000548942757711e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  40%|████      | 2014/5000 [00:50<01:31, 32.65it/s]

[I 2026-06-14 00:49:22,952] Trial 2008 finished with value: 0.4037444300669844 and parameters: {'alpha': 1.0096027833830582e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:22,983] Trial 2009 finished with value: 0.4037450594182034 and parameters: {'alpha': 2.53225574372481e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,018] Trial 2010 finished with value: 0.4037447295964937 and parameters: {'alpha': 1.0066706288003983e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,047] Trial 2011 finished with value: 0.4037449823034121 and parameters: {'alpha': 2.442496094305266e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,075] Trial 2012 finished with value: 0.4037453099566483 and parameters: {'alpha': 5.8256056049918716e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,104] Trial 2013 finished with value: 0.4037448046929065 and parameters: {'alpha': 1.7972143719362748e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,133] Trial 2014 finished with value: 0.40374518440715135 and parameters: {'alpha': 3.950669033290444e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  40%|████      | 2022/5000 [00:50<01:30, 32.84it/s]

[I 2026-06-14 00:49:23,163] Trial 2015 finished with value: 0.4037445076803677 and parameters: {'alpha': 1.0022302441224487e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,194] Trial 2016 finished with value: 0.403744975124434 and parameters: {'alpha': 1.755725239523256e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,223] Trial 2017 finished with value: 0.4037449941522228 and parameters: {'alpha': 2.423958582107688e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,254] Trial 2018 finished with value: 0.40374484408483624 and parameters: {'alpha': 1.6917637521375665e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,284] Trial 2019 finished with value: 0.40374531032426675 and parameters: {'alpha': 9.918926119527075e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,314] Trial 2020 finished with value: 0.4037446470561705 and parameters: {'alpha': 1.009716864432839e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,345] Trial 2021 finished with value: 0.4037452600090967 and parameters: {'alpha': 4.4460876257402265e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  41%|████      | 2028/5000 [00:50<01:31, 32.48it/s]

[I 2026-06-14 00:49:23,381] Trial 2022 finished with value: 0.4037449899557515 and parameters: {'alpha': 2.586981179874943e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,410] Trial 2023 finished with value: 0.4037447700753599 and parameters: {'alpha': 1.7356401312925495e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,442] Trial 2024 finished with value: 0.4037446667888645 and parameters: {'alpha': 1.0130919819291029e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,471] Trial 2025 finished with value: 0.40374505683039397 and parameters: {'alpha': 2.8572380333896296e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,504] Trial 2026 finished with value: 0.40374475494755546 and parameters: {'alpha': 1.716078721237206e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,535] Trial 2027 finished with value: 0.40374522832169796 and parameters: {'alpha': 4.435394241173352e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,567] Trial 2028 finished with value: 0.4037449576066228 and parameters: {'alpha': 1.7313457388956577e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  41%|████      | 2035/5000 [00:51<01:31, 32.45it/s]

[I 2026-06-14 00:49:23,598] Trial 2029 finished with value: 0.40374502007512175 and parameters: {'alpha': 2.8552186410460436e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,629] Trial 2030 finished with value: 0.403745275299491 and parameters: {'alpha': 7.474245392096123e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,656] Trial 2031 finished with value: 0.4037453605688166 and parameters: {'alpha': 2.0483087704586159e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,687] Trial 2032 finished with value: 0.4037449669025406 and parameters: {'alpha': 1.7893753657730194e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,718] Trial 2033 finished with value: 0.40374480843163096 and parameters: {'alpha': 1.7003127049864986e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,753] Trial 2034 finished with value: 0.4037446599826243 and parameters: {'alpha': 1.0149502391667568e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,782] Trial 2035 finished with value: 0.4037452114150073 and parameters: {'alpha': 2.9976985591622956e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  41%|████      | 2042/5000 [00:51<01:29, 33.01it/s]

[I 2026-06-14 00:49:23,811] Trial 2036 finished with value: 0.4037452439727243 and parameters: {'alpha': 5.023536872960704e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,841] Trial 2037 finished with value: 0.403744937972558 and parameters: {'alpha': 1.747216720255111e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,872] Trial 2038 finished with value: 0.4037444156144983 and parameters: {'alpha': 1.0178893112217087e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,901] Trial 2039 finished with value: 0.40374507273939075 and parameters: {'alpha': 2.7784631342684095e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,930] Trial 2040 finished with value: 0.40374482377478477 and parameters: {'alpha': 1.7001380219571537e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,959] Trial 2041 finished with value: 0.4037446191059032 and parameters: {'alpha': 1.0007505852697249e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:23,990] Trial 2042 finished with value: 0.4037452446653185 and parameters: {'alpha': 4.85507280334745e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  41%|████      | 2050/5000 [00:51<01:26, 34.04it/s]

[I 2026-06-14 00:49:24,017] Trial 2043 finished with value: 0.40374448602232615 and parameters: {'alpha': 1.0144274766200051e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,046] Trial 2044 finished with value: 0.4037451656925866 and parameters: {'alpha': 2.994326446403768e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,073] Trial 2045 finished with value: 0.4037445373415465 and parameters: {'alpha': 1.0021773939305794e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,102] Trial 2046 finished with value: 0.4037444828945722 and parameters: {'alpha': 1.0059461652611477e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,130] Trial 2047 finished with value: 0.40374429740324363 and parameters: {'alpha': 1.0016399227292196e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,157] Trial 2048 finished with value: 0.40374503312443516 and parameters: {'alpha': 2.5422159021535477e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,186] Trial 2049 finished with value: 0.4037452428973874 and parameters: {'alpha': 6.481011215653802e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,217] Trial 2050 finished with value: 0.40374479721583245 and parameters: {'alpha': 1.7880953736109504e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  41%|████      | 2056/5000 [00:51<01:28, 33.22it/s]

[I 2026-06-14 00:49:24,247] Trial 2051 finished with value: 0.4037443229076603 and parameters: {'alpha': 1.0037761072678868e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,278] Trial 2052 finished with value: 0.40374506578632785 and parameters: {'alpha': 2.9771945261605784e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,312] Trial 2053 finished with value: 0.40374533209432245 and parameters: {'alpha': 1.2199034524034325e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,349] Trial 2054 finished with value: 0.4037448560123843 and parameters: {'alpha': 1.750620732355776e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,384] Trial 2055 finished with value: 0.4202233579519435 and parameters: {'alpha': 2228.708686643171}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,424] Trial 2056 finished with value: 0.40374447327665103 and parameters: {'alpha': 1.0012620949009354e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  41%|████      | 2062/5000 [00:52<01:45, 27.78it/s]

[I 2026-06-14 00:49:24,465] Trial 2057 finished with value: 0.4037452702682958 and parameters: {'alpha': 4.1578845610882846e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,500] Trial 2058 finished with value: 0.40374501024264703 and parameters: {'alpha': 2.5784876794073015e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,536] Trial 2059 finished with value: 0.4037449605193222 and parameters: {'alpha': 1.8100992802154004e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,593] Trial 2060 finished with value: 0.40374487377638546 and parameters: {'alpha': 1.7576565900538562e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,641] Trial 2061 finished with value: 0.4037452154065728 and parameters: {'alpha': 3.788563659105873e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:49:24,687] Trial 2062 finished with value: 0.40374493101403935 and parameters: {'alpha': 1.7270806123412125e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,726] Trial 2063 finished with value: 0.403745028455863 and parameters: {'alpha': 2.721354449136705e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,760] Trial 2064 finished with value: 0.40374528846534696 and parameters: {'alpha': 5.925438382456578e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,793] Trial 2065 finished with value: 0.40374487621115296 and parameters: {'alpha': 1.914468874093934e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,824] Trial 2066 finished with value: 0.40374477163196953 and parameters: {'alpha': 1.8484066128499775e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,857] Trial 2067 finished with value: 0.40374522313056577 and parameters: {'alpha': 4.189294116251976e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,889] Trial 2068 finished with value: 0.4037448043743551 and parameters: {'alpha': 1.8223033961632996e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  42%|████▏     | 2075/5000 [00:52<01:38, 29.75it/s]

[I 2026-06-14 00:49:24,923] Trial 2069 finished with value: 0.4037453156196929 and parameters: {'alpha': 9.69321155906162e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,953] Trial 2070 finished with value: 0.40374476286732275 and parameters: {'alpha': 1.727371349226333e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:24,982] Trial 2071 finished with value: 0.40374432448686937 and parameters: {'alpha': 1.0052724086591484e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,009] Trial 2072 finished with value: 0.4037445521882372 and parameters: {'alpha': 1.002425532381668e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,039] Trial 2073 finished with value: 0.40374511929977325 and parameters: {'alpha': 3.256334407154511e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,070] Trial 2074 finished with value: 0.40374505815403117 and parameters: {'alpha': 2.815381628647222e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,100] Trial 2075 finished with value: 0.40374474998015175 and parameters: {'alpha': 1.6706801454462076e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:49:25,130] Trial 2076 finished with value: 0.40374540653420404 and parameters: {'alpha': 0.0001257926235870948}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,159] Trial 2077 finished with value: 0.40374527730756365 and parameters: {'alpha': 5.6138215242067486e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,186] Trial 2078 finished with value: 0.4037448708866971 and parameters: {'alpha': 1.682917512617962e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,213] Trial 2079 finished with value: 0.40374502036519716 and parameters: {'alpha': 2.8861485488800087e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,242] Trial 2080 finished with value: 0.4037449246770679 and parameters: {'alpha': 1.607962424469245e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,270] Trial 2081 finished with value: 0.40374445666997577 and parameters: {'alpha': 1.0061258619187437e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,301] Trial 2082 finished with value: 0.4037443563100343 and parameters: {'alpha': 1.0171264313938813e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  42%|████▏     | 2089/5000 [00:52<01:31, 31.83it/s]

[I 2026-06-14 00:49:25,332] Trial 2083 finished with value: 0.4037451950591062 and parameters: {'alpha': 4.224581462624223e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,366] Trial 2084 finished with value: 0.40374472532067873 and parameters: {'alpha': 1.0106356657088683e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,397] Trial 2085 finished with value: 0.40374510035139033 and parameters: {'alpha': 2.876534501130624e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,429] Trial 2086 finished with value: 0.4037449191431867 and parameters: {'alpha': 1.8280385077500086e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,463] Trial 2087 finished with value: 0.4037453163718621 and parameters: {'alpha': 7.834182828587795e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,495] Trial 2088 finished with value: 0.4037451091790964 and parameters: {'alpha': 2.8504098824098968e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,525] Trial 2089 finished with value: 0.4037449607554117 and parameters: {'alpha': 1.7543651318005103e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  42%|████▏     | 2097/5000 [00:53<01:29, 32.53it/s]

[I 2026-06-14 00:49:25,555] Trial 2090 finished with value: 0.4037449506474964 and parameters: {'alpha': 1.719355783967311e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,585] Trial 2091 finished with value: 0.40374526721855064 and parameters: {'alpha': 4.707771797159702e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,614] Trial 2092 finished with value: 0.40374461111881027 and parameters: {'alpha': 1.011591977799996e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,645] Trial 2093 finished with value: 0.40374508827418154 and parameters: {'alpha': 2.6520228250500844e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,675] Trial 2094 finished with value: 0.40374504138853445 and parameters: {'alpha': 2.740741328425583e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,706] Trial 2095 finished with value: 0.40374460952462077 and parameters: {'alpha': 1.0153466787155225e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,733] Trial 2096 finished with value: 0.40374477654841673 and parameters: {'alpha': 1.7459193336557275e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  42%|████▏     | 2103/5000 [00:53<01:27, 33.02it/s]

[I 2026-06-14 00:49:25,764] Trial 2097 finished with value: 0.4037443000264582 and parameters: {'alpha': 1.012588366295352e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,793] Trial 2098 finished with value: 0.4037452562999064 and parameters: {'alpha': 4.548153336826084e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,821] Trial 2099 finished with value: 0.40374494878507916 and parameters: {'alpha': 1.9099574645796245e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,850] Trial 2100 finished with value: 0.4037442804965014 and parameters: {'alpha': 1.0034866666985626e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,880] Trial 2101 finished with value: 0.40374433350324695 and parameters: {'alpha': 1.001942631935896e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,910] Trial 2102 finished with value: 0.40374541100917055 and parameters: {'alpha': 0.006728177281315282}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,938] Trial 2103 finished with value: 0.40374481450460825 and parameters: {'alpha': 1.7574988046428073e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  42%|████▏     | 2110/5000 [00:53<01:25, 33.61it/s]

[I 2026-06-14 00:49:25,967] Trial 2104 finished with value: 0.4037452771158749 and parameters: {'alpha': 7.23915113863225e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:25,998] Trial 2105 finished with value: 0.40374520536471525 and parameters: {'alpha': 3.545681551633193e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,028] Trial 2106 finished with value: 0.4037449281032279 and parameters: {'alpha': 1.774647380388083e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,056] Trial 2107 finished with value: 0.403744503336461 and parameters: {'alpha': 1.0118158199994282e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,085] Trial 2108 finished with value: 0.4037444034365099 and parameters: {'alpha': 1.0066914185841423e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,116] Trial 2109 finished with value: 0.40374509933318775 and parameters: {'alpha': 2.84394131145659e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,144] Trial 2110 finished with value: 0.40374541682491855 and parameters: {'alpha': 0.015399367987609906}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  42%|████▏     | 2117/5000 [00:53<01:25, 33.85it/s]

[I 2026-06-14 00:49:26,173] Trial 2111 finished with value: 0.4037448225020064 and parameters: {'alpha': 1.8168248474932446e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,202] Trial 2112 finished with value: 0.40374528053196046 and parameters: {'alpha': 4.5510177271554384e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,233] Trial 2113 finished with value: 0.4037442908527213 and parameters: {'alpha': 1.0011223172849725e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,263] Trial 2114 finished with value: 0.4037453421176047 and parameters: {'alpha': 1.6035119534099815e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,292] Trial 2115 finished with value: 0.4037450535673165 and parameters: {'alpha': 2.6775959576588874e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,321] Trial 2116 finished with value: 0.40374491172428195 and parameters: {'alpha': 1.8000925449761832e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,351] Trial 2117 finished with value: 0.40374473386907395 and parameters: {'alpha': 1.67152556574948e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  42%|████▎     | 2125/5000 [00:53<01:25, 33.44it/s]

[I 2026-06-14 00:49:26,382] Trial 2118 finished with value: 0.40374434593648445 and parameters: {'alpha': 1.0015901240100106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,412] Trial 2119 finished with value: 0.4037451875340734 and parameters: {'alpha': 4.119708611857847e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,445] Trial 2120 finished with value: 0.40374540583282065 and parameters: {'alpha': 1.1925442359101269e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,475] Trial 2121 finished with value: 0.403744562146858 and parameters: {'alpha': 1.0013247393362287e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,503] Trial 2122 finished with value: 0.40437428128187447 and parameters: {'alpha': 219.8977984158291}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,535] Trial 2123 finished with value: 0.40374513020861796 and parameters: {'alpha': 3.021404467712537e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,563] Trial 2124 finished with value: 0.403744931986419 and parameters: {'alpha': 1.7004188808021774e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  43%|████▎     | 2131/5000 [00:54<01:25, 33.38it/s]

[I 2026-06-14 00:49:26,593] Trial 2125 finished with value: 0.40374526592914384 and parameters: {'alpha': 8.20243906497292e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,622] Trial 2126 finished with value: 0.40374502055881245 and parameters: {'alpha': 2.8476367260248134e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,651] Trial 2127 finished with value: 0.4037449752848224 and parameters: {'alpha': 1.7361728550816906e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,681] Trial 2128 finished with value: 0.4037442542016391 and parameters: {'alpha': 1.001007658550553e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,713] Trial 2129 finished with value: 0.4037448188995547 and parameters: {'alpha': 1.7706228389945497e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,742] Trial 2130 finished with value: 0.4037443960332736 and parameters: {'alpha': 1.0120617573105408e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,771] Trial 2131 finished with value: 0.40374529232344153 and parameters: {'alpha': 5.9533689277159575e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  43%|████▎     | 2138/5000 [00:54<01:24, 33.80it/s]

[I 2026-06-14 00:49:26,800] Trial 2132 finished with value: 0.4037451697408916 and parameters: {'alpha': 3.049236788139824e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,831] Trial 2133 finished with value: 0.40374481971112336 and parameters: {'alpha': 1.781601726739365e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,860] Trial 2134 finished with value: 0.40374516804597277 and parameters: {'alpha': 2.990178508291708e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,888] Trial 2135 finished with value: 0.4037449496412713 and parameters: {'alpha': 1.771322819003529e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,917] Trial 2136 finished with value: 0.40374463450922077 and parameters: {'alpha': 1.0016326806773347e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,948] Trial 2137 finished with value: 0.4037452370727878 and parameters: {'alpha': 4.185666990781532e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:26,977] Trial 2138 finished with value: 0.4037449534873327 and parameters: {'alpha': 1.859934742987027e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  43%|████▎     | 2145/5000 [00:54<01:24, 33.82it/s]

[I 2026-06-14 00:49:27,008] Trial 2139 finished with value: 0.4037453155966301 and parameters: {'alpha': 1.0539679127959712e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,037] Trial 2140 finished with value: 0.4037450858008484 and parameters: {'alpha': 2.667784970463121e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,067] Trial 2141 finished with value: 0.40374473660491533 and parameters: {'alpha': 1.6296729329972448e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,097] Trial 2142 finished with value: 0.4037452540118008 and parameters: {'alpha': 4.5260018827854866e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,126] Trial 2143 finished with value: 0.40374498803828635 and parameters: {'alpha': 2.6702330968532788e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,154] Trial 2144 finished with value: 0.4037449155654137 and parameters: {'alpha': 1.7000328236188002e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,185] Trial 2145 finished with value: 0.4037447274595289 and parameters: {'alpha': 1.0125623297452644e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  43%|████▎     | 2153/5000 [00:54<01:25, 33.12it/s]

[I 2026-06-14 00:49:27,216] Trial 2146 finished with value: 0.40374530775720024 and parameters: {'alpha': 5.502330977369306e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,247] Trial 2147 finished with value: 0.4037448763880747 and parameters: {'alpha': 1.7083868776700116e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,279] Trial 2148 finished with value: 0.40374504513110854 and parameters: {'alpha': 2.7722733170078972e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,312] Trial 2149 finished with value: 0.40374467021740046 and parameters: {'alpha': 1.0154784786360964e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,340] Trial 2150 finished with value: 0.4037445947707177 and parameters: {'alpha': 1.0047296939989763e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,370] Trial 2151 finished with value: 0.4037442870765663 and parameters: {'alpha': 1.0061561475861489e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,401] Trial 2152 finished with value: 0.4037535989428641 and parameters: {'alpha': 5.62958262959896}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  43%|████▎     | 2159/5000 [00:54<01:27, 32.65it/s]

[I 2026-06-14 00:49:27,435] Trial 2153 finished with value: 0.4037449712243555 and parameters: {'alpha': 1.7520103166215102e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,467] Trial 2154 finished with value: 0.40374502287001457 and parameters: {'alpha': 2.7785861972209154e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,498] Trial 2155 finished with value: 0.40374523812734836 and parameters: {'alpha': 6.26413670231833e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,528] Trial 2156 finished with value: 0.4037448061163283 and parameters: {'alpha': 1.656157490589191e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,559] Trial 2157 finished with value: 0.4037452006936734 and parameters: {'alpha': 4.194035738558566e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,589] Trial 2158 finished with value: 0.4037446647950858 and parameters: {'alpha': 1.0116586464021089e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,619] Trial 2159 finished with value: 0.40374504794223914 and parameters: {'alpha': 2.7165135682662004e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  43%|████▎     | 2166/5000 [00:55<01:26, 32.73it/s]

[I 2026-06-14 00:49:27,649] Trial 2160 finished with value: 0.4037448386161101 and parameters: {'alpha': 1.7932186930585033e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,679] Trial 2161 finished with value: 0.40374492080413427 and parameters: {'alpha': 1.740758164470448e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,708] Trial 2162 finished with value: 0.4037444113314675 and parameters: {'alpha': 1.0058149081206936e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,741] Trial 2163 finished with value: 0.40374456975128686 and parameters: {'alpha': 1.0064258619957133e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,770] Trial 2164 finished with value: 0.40374519574569856 and parameters: {'alpha': 3.9745982566001e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,803] Trial 2165 finished with value: 0.4037450788629799 and parameters: {'alpha': 2.7277495843901135e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,833] Trial 2166 finished with value: 0.40374540704663525 and parameters: {'alpha': 0.0008158368241727105}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  43%|████▎     | 2173/5000 [00:55<01:27, 32.44it/s]

[I 2026-06-14 00:49:27,863] Trial 2167 finished with value: 0.4037453221773674 and parameters: {'alpha': 9.060809631504795e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,894] Trial 2168 finished with value: 0.40374488024673777 and parameters: {'alpha': 1.7370136330922782e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,927] Trial 2169 finished with value: 0.4037447700803008 and parameters: {'alpha': 1.7311433686823625e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,959] Trial 2170 finished with value: 0.40374452052908794 and parameters: {'alpha': 1.0019627913346693e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:27,989] Trial 2171 finished with value: 0.4037451151398159 and parameters: {'alpha': 2.98698883263674e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,019] Trial 2172 finished with value: 0.40374531092411575 and parameters: {'alpha': 5.574303140059403e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,050] Trial 2173 finished with value: 0.4037450915238809 and parameters: {'alpha': 2.7535786344705366e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  44%|████▎     | 2181/5000 [00:55<01:24, 33.28it/s]

[I 2026-06-14 00:49:28,081] Trial 2174 finished with value: 0.40374481035911247 and parameters: {'alpha': 1.7827599964600198e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,115] Trial 2175 finished with value: 0.4037449412415539 and parameters: {'alpha': 1.7084983796217705e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,143] Trial 2176 finished with value: 0.4037452305179828 and parameters: {'alpha': 4.127263385894474e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,172] Trial 2177 finished with value: 0.4037450036071901 and parameters: {'alpha': 2.6592308066329873e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,199] Trial 2178 finished with value: 0.4037448452107768 and parameters: {'alpha': 1.7023270688622483e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,228] Trial 2179 finished with value: 0.40374529960764394 and parameters: {'alpha': 6.664438347666095e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,257] Trial 2180 finished with value: 0.4037448282131405 and parameters: {'alpha': 1.82184746231475e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  44%|████▎     | 2187/5000 [00:55<01:23, 33.59it/s]

[I 2026-06-14 00:49:28,286] Trial 2181 finished with value: 0.4037452502970123 and parameters: {'alpha': 3.751609108573278e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,316] Trial 2182 finished with value: 0.40374540671792464 and parameters: {'alpha': 0.00034899466303908456}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,344] Trial 2183 finished with value: 0.40374450003529927 and parameters: {'alpha': 1.0100500441115307e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,373] Trial 2184 finished with value: 0.4037447969082005 and parameters: {'alpha': 1.7356529863261308e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,402] Trial 2185 finished with value: 0.4037454897391736 and parameters: {'alpha': 0.1210615215913283}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,431] Trial 2186 finished with value: 0.4037448178191346 and parameters: {'alpha': 1.6410223460758482e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,462] Trial 2187 finished with value: 0.40374510561015975 and parameters: {'alpha': 2.803505323401141e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  44%|████▍     | 2194/5000 [00:56<01:22, 33.85it/s]

[I 2026-06-14 00:49:28,490] Trial 2188 finished with value: 0.4037453648988768 and parameters: {'alpha': 2.5885427531137616e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,522] Trial 2189 finished with value: 0.40374425617257154 and parameters: {'alpha': 1.0024013619818177e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,550] Trial 2190 finished with value: 0.40374472223257285 and parameters: {'alpha': 1.6531967421876083e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,578] Trial 2191 finished with value: 0.40374458895858706 and parameters: {'alpha': 1.0101446164043095e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,608] Trial 2192 finished with value: 0.40374533328696216 and parameters: {'alpha': 1.0615786862444004e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,638] Trial 2193 finished with value: 0.4037445848651029 and parameters: {'alpha': 1.0080604988418455e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,666] Trial 2194 finished with value: 0.40374525271808775 and parameters: {'alpha': 4.143555251640978e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  44%|████▍     | 2201/5000 [00:56<01:22, 33.95it/s]

[I 2026-06-14 00:49:28,696] Trial 2195 finished with value: 0.40374500360812426 and parameters: {'alpha': 2.738675479942749e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,725] Trial 2196 finished with value: 0.40374478234027444 and parameters: {'alpha': 1.753525023042841e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,754] Trial 2197 finished with value: 0.4037446457729131 and parameters: {'alpha': 1.0100444335241109e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,784] Trial 2198 finished with value: 0.40374525238355174 and parameters: {'alpha': 6.349152595374931e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,814] Trial 2199 finished with value: 0.4037447326044152 and parameters: {'alpha': 1.0070863016378402e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,842] Trial 2200 finished with value: 0.4037446227891254 and parameters: {'alpha': 1.0113064758572557e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,873] Trial 2201 finished with value: 0.4037450627722468 and parameters: {'alpha': 2.673701931267376e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  44%|████▍     | 2209/5000 [00:56<01:23, 33.36it/s]

[I 2026-06-14 00:49:28,903] Trial 2202 finished with value: 0.403744992001809 and parameters: {'alpha': 2.7053872132909724e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,934] Trial 2203 finished with value: 0.40384710583440103 and parameters: {'alpha': 35.28381670449568}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,965] Trial 2204 finished with value: 0.4037452927076602 and parameters: {'alpha': 4.736689633394331e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:28,998] Trial 2205 finished with value: 0.4037446886152269 and parameters: {'alpha': 1.0082287889450625e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,027] Trial 2206 finished with value: 0.4037447932876814 and parameters: {'alpha': 1.7360330238839333e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,057] Trial 2207 finished with value: 0.4037445705091766 and parameters: {'alpha': 1.0004013829490702e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,087] Trial 2208 finished with value: 0.4037449825946965 and parameters: {'alpha': 2.7052115024879416e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  44%|████▍     | 2215/5000 [00:56<01:22, 33.63it/s]

[I 2026-06-14 00:49:29,117] Trial 2209 finished with value: 0.40374491456463735 and parameters: {'alpha': 1.727728260340851e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,146] Trial 2210 finished with value: 0.4037451975569894 and parameters: {'alpha': 4.267194761240209e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,175] Trial 2211 finished with value: 0.4037448449424634 and parameters: {'alpha': 1.7547393267017423e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,203] Trial 2212 finished with value: 0.40374500486060594 and parameters: {'alpha': 2.703846739236346e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,233] Trial 2213 finished with value: 0.4037453167609648 and parameters: {'alpha': 1.2295408162460411e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,261] Trial 2214 finished with value: 0.40374497887154037 and parameters: {'alpha': 1.7705569619183213e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,292] Trial 2215 finished with value: 0.4037452786106704 and parameters: {'alpha': 6.357030097819862e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  44%|████▍     | 2222/5000 [00:56<01:22, 33.68it/s]

[I 2026-06-14 00:49:29,321] Trial 2216 finished with value: 0.4037448857058115 and parameters: {'alpha': 1.74801228551953e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,352] Trial 2217 finished with value: 0.4037443368457724 and parameters: {'alpha': 1.008804721180155e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,381] Trial 2218 finished with value: 0.4037451903097118 and parameters: {'alpha': 3.8181405972079935e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,411] Trial 2219 finished with value: 0.40374441747290063 and parameters: {'alpha': 1.0067351870405145e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,439] Trial 2220 finished with value: 0.40374501487827297 and parameters: {'alpha': 2.5611027488959016e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,474] Trial 2221 finished with value: 0.403744860728075 and parameters: {'alpha': 1.640395101012247e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,505] Trial 2222 finished with value: 0.40374441263934846 and parameters: {'alpha': 1.0106111306432326e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  45%|████▍     | 2229/5000 [00:57<01:28, 31.47it/s]

[I 2026-06-14 00:49:29,562] Trial 2223 finished with value: 0.4037450878541949 and parameters: {'alpha': 2.7452667152163514e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,592] Trial 2224 finished with value: 0.4037443950220236 and parameters: {'alpha': 1.0080948881081214e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,626] Trial 2225 finished with value: 0.4037452764557111 and parameters: {'alpha': 4.5631829757446444e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,655] Trial 2226 finished with value: 0.4037448334696239 and parameters: {'alpha': 1.7981788788278325e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,683] Trial 2227 finished with value: 0.40374499867394126 and parameters: {'alpha': 2.7092795320729757e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,714] Trial 2228 finished with value: 0.4037448230605441 and parameters: {'alpha': 1.7093611859350787e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,747] Trial 2229 finished with value: 0.4037447148046125 and parameters: {'alpha': 1.0115170247435994e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:49:29,778] Trial 2230 finished with value: 0.40374532522733664 and parameters: {'alpha': 8.408788169185934e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,807] Trial 2231 finished with value: 0.4037452224069135 and parameters: {'alpha': 3.9233307519982184e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,834] Trial 2232 finished with value: 0.40374479743983993 and parameters: {'alpha': 1.820223979760302e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,864] Trial 2233 finished with value: 0.4037450494181424 and parameters: {'alpha': 2.6488742299321343e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,892] Trial 2234 finished with value: 0.4037447488041629 and parameters: {'alpha': 1.7148086739921197e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,921] Trial 2235 finished with value: 0.40374527312441244 and parameters: {'alpha': 5.88892415064892e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,949] Trial 2236 finished with value: 0.4037449865382107 and parameters: {'alpha': 1.7971868114081992e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:29,979] Trial 2237 finished with value: 0.4037447886853559 and parameters: {'alpha': 1.7342596549292077e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  45%|████▍     | 2245/5000 [00:57<01:23, 32.88it/s]

[I 2026-06-14 00:49:30,009] Trial 2238 finished with value: 0.40374520644906475 and parameters: {'alpha': 3.730977157782359e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,037] Trial 2239 finished with value: 0.4037448235663352 and parameters: {'alpha': 1.7128443551329112e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,067] Trial 2240 finished with value: 0.4037444267907415 and parameters: {'alpha': 1.0065002456157641e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,101] Trial 2241 finished with value: 0.40374501497833165 and parameters: {'alpha': 2.584284071885459e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,130] Trial 2242 finished with value: 0.40374521932551355 and parameters: {'alpha': 4.090298276283852e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,161] Trial 2243 finished with value: 0.40374486503392426 and parameters: {'alpha': 1.698336063077541e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,192] Trial 2244 finished with value: 0.4037449371766544 and parameters: {'alpha': 1.709925842601981e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  45%|████▌     | 2251/5000 [00:57<01:28, 30.91it/s]

[I 2026-06-14 00:49:30,236] Trial 2245 finished with value: 0.4037444440234835 and parameters: {'alpha': 1.0063935104408832e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,279] Trial 2246 finished with value: 0.4037452791985301 and parameters: {'alpha': 7.231218205561304e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,310] Trial 2247 finished with value: 0.40374511371790994 and parameters: {'alpha': 2.8585066649891487e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,339] Trial 2248 finished with value: 0.4037449215204767 and parameters: {'alpha': 1.6523257161190053e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,369] Trial 2249 finished with value: 0.403744444758442 and parameters: {'alpha': 1.0215753979453743e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,400] Trial 2250 finished with value: 0.4037451839099724 and parameters: {'alpha': 3.036835280694968e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,433] Trial 2251 finished with value: 0.40374461123057775 and parameters: {'alpha': 1.0093219096215725e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  45%|████▌     | 2258/5000 [00:58<01:27, 31.27it/s]

[I 2026-06-14 00:49:30,466] Trial 2252 finished with value: 0.40374534017022484 and parameters: {'alpha': 1.625992108798144e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,501] Trial 2253 finished with value: 0.4037445293436161 and parameters: {'alpha': 1.0128792479530366e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,531] Trial 2254 finished with value: 0.40374519784645574 and parameters: {'alpha': 4.1993419793183975e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,562] Trial 2255 finished with value: 0.40374505705375313 and parameters: {'alpha': 2.649102989177029e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,593] Trial 2256 finished with value: 0.4037448208966749 and parameters: {'alpha': 1.8142229672713843e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,624] Trial 2257 finished with value: 0.4037452429963927 and parameters: {'alpha': 6.295128022465901e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,655] Trial 2258 finished with value: 0.40374445185843955 and parameters: {'alpha': 1.0039050209057266e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  45%|████▌     | 2265/5000 [00:58<01:25, 32.04it/s]

[I 2026-06-14 00:49:30,686] Trial 2259 finished with value: 0.40374502825363057 and parameters: {'alpha': 2.688505168666881e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,716] Trial 2260 finished with value: 0.40374482949756346 and parameters: {'alpha': 1.6909353087471127e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,749] Trial 2261 finished with value: 0.40374483600815947 and parameters: {'alpha': 1.6668920773682845e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,779] Trial 2262 finished with value: 0.40374527839338376 and parameters: {'alpha': 4.5548773889744064e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,809] Trial 2263 finished with value: 0.40374508625012223 and parameters: {'alpha': 2.7190595235046086e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,838] Trial 2264 finished with value: 0.4037442752349331 and parameters: {'alpha': 1.0044620677659172e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,868] Trial 2265 finished with value: 0.4037449561539444 and parameters: {'alpha': 1.7389365759883383e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  45%|████▌     | 2273/5000 [00:58<01:22, 32.93it/s]

[I 2026-06-14 00:49:30,899] Trial 2266 finished with value: 0.4037447530923568 and parameters: {'alpha': 1.6983807986371564e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,930] Trial 2267 finished with value: 0.403744613450801 and parameters: {'alpha': 1.0117411898131468e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,959] Trial 2268 finished with value: 0.4037447462458855 and parameters: {'alpha': 1.010560539387884e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:30,991] Trial 2269 finished with value: 0.40374525275619144 and parameters: {'alpha': 4.340217177905913e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,019] Trial 2270 finished with value: 0.40374461194074196 and parameters: {'alpha': 1.0117588975489748e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,047] Trial 2271 finished with value: 0.4037453252845436 and parameters: {'alpha': 1.0065400052282687e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,076] Trial 2272 finished with value: 0.40374504086288737 and parameters: {'alpha': 2.6693336546577898e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  46%|████▌     | 2279/5000 [00:58<01:22, 32.92it/s]

[I 2026-06-14 00:49:31,106] Trial 2273 finished with value: 0.40374509444596485 and parameters: {'alpha': 2.70062493687986e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,136] Trial 2274 finished with value: 0.4037448725313648 and parameters: {'alpha': 1.7773356732834355e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,167] Trial 2275 finished with value: 0.403745303011466 and parameters: {'alpha': 5.8737729545571244e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,197] Trial 2276 finished with value: 0.4037448865595544 and parameters: {'alpha': 1.6856646209208e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,231] Trial 2277 finished with value: 0.4037442518248007 and parameters: {'alpha': 1.014282457697682e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,261] Trial 2278 finished with value: 0.40374538311146907 and parameters: {'alpha': 4.108559439867575e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,292] Trial 2279 finished with value: 0.4037451605996293 and parameters: {'alpha': 2.9862580551247036e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  46%|████▌     | 2286/5000 [00:58<01:23, 32.67it/s]

[I 2026-06-14 00:49:31,322] Trial 2280 finished with value: 0.4037448010784301 and parameters: {'alpha': 1.70581233419902e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,353] Trial 2281 finished with value: 0.4037443012930857 and parameters: {'alpha': 1.0144963474995838e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,383] Trial 2282 finished with value: 0.40374529616090854 and parameters: {'alpha': 4.162114424132094e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,414] Trial 2283 finished with value: 0.40374506107430774 and parameters: {'alpha': 2.8719989850629653e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,444] Trial 2284 finished with value: 0.403744831995149 and parameters: {'alpha': 1.716541604389003e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,478] Trial 2285 finished with value: 0.4037447915808037 and parameters: {'alpha': 1.7614324449210932e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,510] Trial 2286 finished with value: 0.40374523230954157 and parameters: {'alpha': 6.065373176235963e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  46%|████▌     | 2293/5000 [00:59<01:24, 32.00it/s]

[I 2026-06-14 00:49:31,541] Trial 2287 finished with value: 0.4037450411259842 and parameters: {'alpha': 2.86403189688581e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,571] Trial 2288 finished with value: 0.4037447345924054 and parameters: {'alpha': 1.615496032662779e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,603] Trial 2289 finished with value: 0.4037449910217705 and parameters: {'alpha': 2.635870914399943e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,637] Trial 2290 finished with value: 0.40374477331222675 and parameters: {'alpha': 1.71244958718274e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,667] Trial 2291 finished with value: 0.40374526122976934 and parameters: {'alpha': 3.973752887582372e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,699] Trial 2292 finished with value: 0.4037453063991874 and parameters: {'alpha': 7.020499418069376e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,730] Trial 2293 finished with value: 0.40374443789378417 and parameters: {'alpha': 1.0071124780592311e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  46%|████▌     | 2301/5000 [00:59<01:23, 32.15it/s]

[I 2026-06-14 00:49:31,763] Trial 2294 finished with value: 0.40374474271199023 and parameters: {'alpha': 1.733579115249104e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,793] Trial 2295 finished with value: 0.4037442870261949 and parameters: {'alpha': 1.009450159269694e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,823] Trial 2296 finished with value: 0.4037450616832675 and parameters: {'alpha': 2.6719142522060073e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,855] Trial 2297 finished with value: 0.4037446444818886 and parameters: {'alpha': 1.01010885390774e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,886] Trial 2298 finished with value: 0.4037444650812285 and parameters: {'alpha': 1.0001219354782233e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,917] Trial 2299 finished with value: 0.4464681482236775 and parameters: {'alpha': 4814.864715283989}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:31,946] Trial 2300 finished with value: 0.40374440468028316 and parameters: {'alpha': 1.0020780927888701e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  46%|████▌     | 2307/5000 [00:59<01:22, 32.62it/s]

[I 2026-06-14 00:49:31,979] Trial 2301 finished with value: 0.4037453125719104 and parameters: {'alpha': 1.1387814671661967e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,008] Trial 2302 finished with value: 0.4037452044073916 and parameters: {'alpha': 4.045578084989643e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,037] Trial 2303 finished with value: 0.4037454060876544 and parameters: {'alpha': 2.313365247181236e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,065] Trial 2304 finished with value: 0.4037450188761844 and parameters: {'alpha': 2.5418164802303026e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,096] Trial 2305 finished with value: 0.40374498218971416 and parameters: {'alpha': 2.549785434540869e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,124] Trial 2306 finished with value: 0.4037449235041382 and parameters: {'alpha': 1.7287169980573593e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,152] Trial 2307 finished with value: 0.40374559597073995 and parameters: {'alpha': 0.2661289412299576}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  46%|████▋     | 2314/5000 [00:59<01:21, 33.11it/s]

[I 2026-06-14 00:49:32,182] Trial 2308 finished with value: 0.40374489757594667 and parameters: {'alpha': 1.7382200989422432e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,213] Trial 2309 finished with value: 0.4037452850867695 and parameters: {'alpha': 6.171401256967204e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,242] Trial 2310 finished with value: 0.40374460345189667 and parameters: {'alpha': 1.008784035137283e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,273] Trial 2311 finished with value: 0.4037452513501614 and parameters: {'alpha': 3.507608309538971e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,302] Trial 2312 finished with value: 0.4037448124376298 and parameters: {'alpha': 1.7447275388989732e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,333] Trial 2313 finished with value: 0.4037442507781351 and parameters: {'alpha': 1.0027025749329198e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,365] Trial 2314 finished with value: 0.4037448363483639 and parameters: {'alpha': 1.7850157492553402e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  46%|████▋     | 2321/5000 [00:59<01:23, 32.24it/s]

[I 2026-06-14 00:49:32,395] Trial 2315 finished with value: 0.4037452460862889 and parameters: {'alpha': 4.487500042195263e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,428] Trial 2316 finished with value: 0.40374484529824123 and parameters: {'alpha': 1.7102811581716642e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,463] Trial 2317 finished with value: 0.4037450605764526 and parameters: {'alpha': 2.7320792968813534e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,495] Trial 2318 finished with value: 0.4037446458635915 and parameters: {'alpha': 1.0034101679172277e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,528] Trial 2319 finished with value: 0.4037446076297087 and parameters: {'alpha': 1.0004520241267487e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,558] Trial 2320 finished with value: 0.4037450674100645 and parameters: {'alpha': 2.7313608596689868e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,590] Trial 2321 finished with value: 0.4037447595404753 and parameters: {'alpha': 1.7197592772177342e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  47%|████▋     | 2329/5000 [01:00<01:24, 31.62it/s]

[I 2026-06-14 00:49:32,623] Trial 2322 finished with value: 0.4037446980839453 and parameters: {'alpha': 1.0003459413132355e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,654] Trial 2323 finished with value: 0.40374527481726613 and parameters: {'alpha': 4.286174537962736e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,686] Trial 2324 finished with value: 0.40374493952867374 and parameters: {'alpha': 1.688872521656672e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,719] Trial 2325 finished with value: 0.4037452934584294 and parameters: {'alpha': 6.930839796773617e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,753] Trial 2326 finished with value: 0.4037447122987487 and parameters: {'alpha': 1.009721007112878e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,784] Trial 2327 finished with value: 0.4037450988082554 and parameters: {'alpha': 2.8170927032502885e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,815] Trial 2328 finished with value: 0.40374447890917103 and parameters: {'alpha': 1.0079878030359202e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  47%|████▋     | 2335/5000 [01:00<01:22, 32.18it/s]

[I 2026-06-14 00:49:32,847] Trial 2329 finished with value: 0.4037449604311456 and parameters: {'alpha': 1.764156659818829e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,876] Trial 2330 finished with value: 0.4037445495559968 and parameters: {'alpha': 1.0054183494101834e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,904] Trial 2331 finished with value: 0.4037450699074729 and parameters: {'alpha': 2.863269245871227e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,934] Trial 2332 finished with value: 0.40374534250742405 and parameters: {'alpha': 1.6467857761614187e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,965] Trial 2333 finished with value: 0.4037452788624723 and parameters: {'alpha': 4.277166688477662e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:32,997] Trial 2334 finished with value: 0.4037447909720274 and parameters: {'alpha': 1.839208679226366e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,028] Trial 2335 finished with value: 0.40374484698806684 and parameters: {'alpha': 1.7913530501708226e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  47%|████▋     | 2342/5000 [01:00<01:22, 32.05it/s]

[I 2026-06-14 00:49:33,060] Trial 2336 finished with value: 0.40374498959247407 and parameters: {'alpha': 2.7400622230996086e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,092] Trial 2337 finished with value: 0.40374481201286816 and parameters: {'alpha': 1.7651385416456134e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,123] Trial 2338 finished with value: 0.40374529931667374 and parameters: {'alpha': 9.004572744839763e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,154] Trial 2339 finished with value: 0.40374530433423 and parameters: {'alpha': 5.390964793580728e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,185] Trial 2340 finished with value: 0.4037448119180559 and parameters: {'alpha': 1.8053935932301365e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,217] Trial 2341 finished with value: 0.4037452685621876 and parameters: {'alpha': 3.712460940699167e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,248] Trial 2342 finished with value: 0.4037442644382141 and parameters: {'alpha': 1.0152003970359348e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  47%|████▋     | 2349/5000 [01:00<01:23, 31.85it/s]

[I 2026-06-14 00:49:33,280] Trial 2343 finished with value: 0.40374459384948985 and parameters: {'alpha': 1.0011542483735662e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,312] Trial 2344 finished with value: 0.4037449594496234 and parameters: {'alpha': 2.515736239923974e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,344] Trial 2345 finished with value: 0.4037449858464187 and parameters: {'alpha': 1.7897200915230626e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,377] Trial 2346 finished with value: 0.403744267216661 and parameters: {'alpha': 1.0086032811945726e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,407] Trial 2347 finished with value: 0.403744557124191 and parameters: {'alpha': 1.0064600767402026e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,436] Trial 2348 finished with value: 0.4037452403732712 and parameters: {'alpha': 4.307995601253533e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,473] Trial 2349 finished with value: 0.40374503272094825 and parameters: {'alpha': 2.8368970264458914e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  47%|████▋     | 2357/5000 [01:01<01:24, 31.41it/s]

[I 2026-06-14 00:49:33,509] Trial 2350 finished with value: 0.4037445701732533 and parameters: {'alpha': 1.0021221635298545e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,542] Trial 2351 finished with value: 0.4037449056133257 and parameters: {'alpha': 1.7822704032193924e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,573] Trial 2352 finished with value: 0.40374506312528047 and parameters: {'alpha': 2.7924070077404066e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,607] Trial 2353 finished with value: 0.40374498386549207 and parameters: {'alpha': 1.837472193799749e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,636] Trial 2354 finished with value: 0.40374524562649045 and parameters: {'alpha': 4.412792246196695e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,666] Trial 2355 finished with value: 0.403744820151578 and parameters: {'alpha': 1.6198918885932345e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,698] Trial 2356 finished with value: 0.4037452587789271 and parameters: {'alpha': 7.53626943675558e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  47%|████▋     | 2362/5000 [01:01<01:23, 31.59it/s]

[I 2026-06-14 00:49:33,732] Trial 2357 finished with value: 0.40374465751772104 and parameters: {'alpha': 1.0076729487219333e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,764] Trial 2358 finished with value: 0.40374507343859145 and parameters: {'alpha': 2.6441182494973917e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,793] Trial 2359 finished with value: 0.4037449177635118 and parameters: {'alpha': 1.7188514032362664e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,823] Trial 2360 finished with value: 0.4037448513084366 and parameters: {'alpha': 1.7376586158834974e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,854] Trial 2361 finished with value: 0.40374540646615437 and parameters: {'alpha': 6.649287398308779e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,912] Trial 2362 finished with value: 0.40374523725020434 and parameters: {'alpha': 4.296139989273728e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  47%|████▋     | 2369/5000 [01:01<01:28, 29.81it/s]

[I 2026-06-14 00:49:33,956] Trial 2363 finished with value: 0.4037449956306628 and parameters: {'alpha': 2.797933291199219e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:33,992] Trial 2364 finished with value: 0.403745273147937 and parameters: {'alpha': 8.156936610516828e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,027] Trial 2365 finished with value: 0.4037448128200148 and parameters: {'alpha': 1.6608305406099835e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,057] Trial 2366 finished with value: 0.4037447766534762 and parameters: {'alpha': 1.6694441141648733e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,086] Trial 2367 finished with value: 0.4037451020152138 and parameters: {'alpha': 2.8322834963450067e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,114] Trial 2368 finished with value: 0.4037448414035528 and parameters: {'alpha': 1.6720609194135156e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,146] Trial 2369 finished with value: 0.4037452423731948 and parameters: {'alpha': 4.3413512485682026e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  48%|████▊     | 2377/5000 [01:01<01:23, 31.27it/s]

[I 2026-06-14 00:49:34,176] Trial 2370 finished with value: 0.40399797465486365 and parameters: {'alpha': 84.17284092081127}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,207] Trial 2371 finished with value: 0.4037449507275209 and parameters: {'alpha': 1.796959214911912e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,236] Trial 2372 finished with value: 0.4037450599677857 and parameters: {'alpha': 2.7811412038921732e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,268] Trial 2373 finished with value: 0.40374485662563436 and parameters: {'alpha': 1.689908365860095e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,299] Trial 2374 finished with value: 0.40374527737998006 and parameters: {'alpha': 5.5256019714143687e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,328] Trial 2375 finished with value: 0.4037451058572 and parameters: {'alpha': 2.8384380559601204e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,358] Trial 2376 finished with value: 0.4037448994668492 and parameters: {'alpha': 1.6056020435629e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  48%|████▊     | 2383/5000 [01:01<01:22, 31.58it/s]

[I 2026-06-14 00:49:34,390] Trial 2377 finished with value: 0.40374864818072786 and parameters: {'alpha': 2.9090190169063628}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,420] Trial 2378 finished with value: 0.40374499256113533 and parameters: {'alpha': 1.829834283185468e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,450] Trial 2379 finished with value: 0.40374533307256466 and parameters: {'alpha': 1.2531957292787014e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,483] Trial 2380 finished with value: 0.40374457551505527 and parameters: {'alpha': 1.0214447615056401e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,513] Trial 2381 finished with value: 0.40374447264646535 and parameters: {'alpha': 1.015095406817239e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,546] Trial 2382 finished with value: 0.4037452293081743 and parameters: {'alpha': 4.282867369732553e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,577] Trial 2383 finished with value: 0.40374443612940497 and parameters: {'alpha': 1.0120432086806517e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  48%|████▊     | 2390/5000 [01:02<01:22, 31.71it/s]

[I 2026-06-14 00:49:34,608] Trial 2384 finished with value: 0.4037445030099551 and parameters: {'alpha': 1.019526364954595e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,640] Trial 2385 finished with value: 0.40374498690795696 and parameters: {'alpha': 2.701224935485692e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,669] Trial 2386 finished with value: 0.40374434651002805 and parameters: {'alpha': 1.0133761795778049e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,702] Trial 2387 finished with value: 0.40374508770819534 and parameters: {'alpha': 2.8071518622323607e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,734] Trial 2388 finished with value: 0.4037462024820102 and parameters: {'alpha': 0.9638109998304887}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,766] Trial 2389 finished with value: 0.403745240795636 and parameters: {'alpha': 6.698004361079769e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,797] Trial 2390 finished with value: 0.40374498944654424 and parameters: {'alpha': 1.8045030244190533e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  48%|████▊     | 2397/5000 [01:02<01:21, 31.84it/s]

[I 2026-06-14 00:49:34,827] Trial 2391 finished with value: 0.40374469305577926 and parameters: {'alpha': 1.0131476049311768e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,858] Trial 2392 finished with value: 0.40374498936865677 and parameters: {'alpha': 2.6197617676781162e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,888] Trial 2393 finished with value: 0.40374474484989725 and parameters: {'alpha': 1.7453400407575736e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,918] Trial 2394 finished with value: 0.40374525216963875 and parameters: {'alpha': 4.3754919067209266e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,950] Trial 2395 finished with value: 0.4037445572430096 and parameters: {'alpha': 1.0125823771153907e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:34,982] Trial 2396 finished with value: 0.4037448477133908 and parameters: {'alpha': 1.7334839329385055e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,015] Trial 2397 finished with value: 0.40374502217140545 and parameters: {'alpha': 2.8142278291607507e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  48%|████▊     | 2405/5000 [01:02<01:21, 31.74it/s]

[I 2026-06-14 00:49:35,048] Trial 2398 finished with value: 0.40374438821138353 and parameters: {'alpha': 1.0082598466999602e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,081] Trial 2399 finished with value: 0.40374525552365587 and parameters: {'alpha': 3.9358652541425846e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,112] Trial 2400 finished with value: 0.4037446762637001 and parameters: {'alpha': 1.0099008808576367e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,144] Trial 2401 finished with value: 0.4037449716307951 and parameters: {'alpha': 1.773483123060212e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,174] Trial 2402 finished with value: 0.40374531098054783 and parameters: {'alpha': 9.97906815236304e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,204] Trial 2403 finished with value: 0.40374426988989515 and parameters: {'alpha': 1.0063764518712575e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,235] Trial 2404 finished with value: 0.40374502324413536 and parameters: {'alpha': 2.4756847537204368e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  48%|████▊     | 2411/5000 [01:02<01:20, 32.04it/s]

[I 2026-06-14 00:49:35,267] Trial 2405 finished with value: 0.40374540163658734 and parameters: {'alpha': 1.5648260397345111e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,297] Trial 2406 finished with value: 0.4037447611539324 and parameters: {'alpha': 1.7052821477029083e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,327] Trial 2407 finished with value: 0.4037453204115663 and parameters: {'alpha': 5.632437446607838e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,358] Trial 2408 finished with value: 0.40374508407690807 and parameters: {'alpha': 2.7152245971180342e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,390] Trial 2409 finished with value: 0.40374497482299676 and parameters: {'alpha': 1.7977001097315873e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,419] Trial 2410 finished with value: 0.40374522038991617 and parameters: {'alpha': 4.4882785575468976e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,454] Trial 2411 finished with value: 0.4037443305234178 and parameters: {'alpha': 1.0080747632095865e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  48%|████▊     | 2417/5000 [01:03<01:24, 30.65it/s]

[I 2026-06-14 00:49:35,486] Trial 2412 finished with value: 0.4037444489344882 and parameters: {'alpha': 1.002871662584126e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,519] Trial 2413 finished with value: 0.4037450776221791 and parameters: {'alpha': 2.641625219819581e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,554] Trial 2414 finished with value: 0.40374499258212015 and parameters: {'alpha': 1.7940107156401178e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,588] Trial 2415 finished with value: 0.40374494318839 and parameters: {'alpha': 1.750216398844122e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,625] Trial 2416 finished with value: 0.40374520160227784 and parameters: {'alpha': 3.996910914428581e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,664] Trial 2417 finished with value: 0.40374487192948094 and parameters: {'alpha': 1.688827713456552e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  48%|████▊     | 2425/5000 [01:03<01:24, 30.54it/s]

[I 2026-06-14 00:49:35,696] Trial 2418 finished with value: 0.4037450437577591 and parameters: {'alpha': 2.877239547848743e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,729] Trial 2419 finished with value: 0.40374525197907896 and parameters: {'alpha': 6.484078284732538e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,760] Trial 2420 finished with value: 0.4037442644976961 and parameters: {'alpha': 1.0011142730628902e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,794] Trial 2421 finished with value: 0.403744449698098 and parameters: {'alpha': 1.0025909888410722e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,826] Trial 2422 finished with value: 0.4037445058567105 and parameters: {'alpha': 1.009618510475571e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,858] Trial 2423 finished with value: 0.4037450083455097 and parameters: {'alpha': 2.698595462033924e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,890] Trial 2424 finished with value: 0.40374479527261276 and parameters: {'alpha': 1.7432841608297277e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  49%|████▊     | 2431/5000 [01:03<01:23, 30.70it/s]

[I 2026-06-14 00:49:35,923] Trial 2425 finished with value: 0.4037449869560516 and parameters: {'alpha': 2.637212153371745e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,956] Trial 2426 finished with value: 0.40374536185970294 and parameters: {'alpha': 1.8725290916593926e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:35,988] Trial 2427 finished with value: 0.4037447987703014 and parameters: {'alpha': 1.6488050818545103e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,020] Trial 2428 finished with value: 0.4037452877727886 and parameters: {'alpha': 4.6509917730671665e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,052] Trial 2429 finished with value: 0.4037448189839577 and parameters: {'alpha': 1.7810306127806277e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,083] Trial 2430 finished with value: 0.4037453182115118 and parameters: {'alpha': 9.188792243285937e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,114] Trial 2431 finished with value: 0.4037444300004638 and parameters: {'alpha': 1.0093609341494505e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  49%|████▉     | 2438/5000 [01:03<01:22, 31.18it/s]

[I 2026-06-14 00:49:36,145] Trial 2432 finished with value: 0.4037451758632678 and parameters: {'alpha': 3.779294254582068e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,177] Trial 2433 finished with value: 0.4037448525685212 and parameters: {'alpha': 1.8169946731688652e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,208] Trial 2434 finished with value: 0.4037444510216865 and parameters: {'alpha': 1.0098769786665788e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,239] Trial 2435 finished with value: 0.4037448909567562 and parameters: {'alpha': 1.705882204968253e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,272] Trial 2436 finished with value: 0.403745143210239 and parameters: {'alpha': 2.9903391930602464e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,302] Trial 2437 finished with value: 0.40374477837064215 and parameters: {'alpha': 1.6957717525172406e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,334] Trial 2438 finished with value: 0.40374526487266327 and parameters: {'alpha': 4.151480516048322e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  49%|████▉     | 2445/5000 [01:03<01:20, 31.82it/s]

[I 2026-06-14 00:49:36,366] Trial 2439 finished with value: 0.4037450107917636 and parameters: {'alpha': 2.852110785660561e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,397] Trial 2440 finished with value: 0.4037448916054161 and parameters: {'alpha': 1.7356964679127002e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,428] Trial 2441 finished with value: 0.4037443683520898 and parameters: {'alpha': 1.0148342648677816e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,459] Trial 2442 finished with value: 0.40374470962446474 and parameters: {'alpha': 1.6591746628143784e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,488] Trial 2443 finished with value: 0.40374528639174684 and parameters: {'alpha': 5.139602317087627e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,519] Trial 2444 finished with value: 0.4037450348457426 and parameters: {'alpha': 2.7350191459720066e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,550] Trial 2445 finished with value: 0.40374526487216494 and parameters: {'alpha': 7.91696090178683e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  49%|████▉     | 2453/5000 [01:04<01:20, 31.45it/s]

[I 2026-06-14 00:49:36,584] Trial 2446 finished with value: 0.4037447527198323 and parameters: {'alpha': 1.686960445425936e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,615] Trial 2447 finished with value: 0.4037445876199349 and parameters: {'alpha': 1.004183487965342e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,647] Trial 2448 finished with value: 0.40374508908259954 and parameters: {'alpha': 2.849933046557004e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,679] Trial 2449 finished with value: 0.40374495270227007 and parameters: {'alpha': 1.6974779597258628e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,711] Trial 2450 finished with value: 0.4037443516975514 and parameters: {'alpha': 1.0109756088966674e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,743] Trial 2451 finished with value: 0.40374518125503117 and parameters: {'alpha': 3.779432686478322e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,776] Trial 2452 finished with value: 0.40374472272630324 and parameters: {'alpha': 1.6571405123252638e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  49%|████▉     | 2459/5000 [01:04<01:19, 31.78it/s]

[I 2026-06-14 00:49:36,810] Trial 2453 finished with value: 0.40374497520781993 and parameters: {'alpha': 2.5882691567437693e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,840] Trial 2454 finished with value: 0.40374530167732947 and parameters: {'alpha': 5.870678914619942e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,869] Trial 2455 finished with value: 0.4037448863761945 and parameters: {'alpha': 1.700165074245072e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,899] Trial 2456 finished with value: 0.4037447203378286 and parameters: {'alpha': 1.014767443310179e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,931] Trial 2457 finished with value: 0.4037445037524449 and parameters: {'alpha': 1.0048111808443919e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,961] Trial 2458 finished with value: 0.4037450474255774 and parameters: {'alpha': 2.7826429763287433e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:36,991] Trial 2459 finished with value: 0.40374477933953024 and parameters: {'alpha': 1.818942744282626e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  49%|████▉     | 2466/5000 [01:04<01:19, 31.99it/s]

[I 2026-06-14 00:49:37,021] Trial 2460 finished with value: 0.403744514910992 and parameters: {'alpha': 1.0021533182416733e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,054] Trial 2461 finished with value: 0.40374523961662645 and parameters: {'alpha': 4.094954952129387e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,085] Trial 2462 finished with value: 0.40374507024940415 and parameters: {'alpha': 2.7452436048550215e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,116] Trial 2463 finished with value: 0.40374494345978273 and parameters: {'alpha': 1.7136329036740535e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,147] Trial 2464 finished with value: 0.4037452845312531 and parameters: {'alpha': 8.367284236536395e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,180] Trial 2465 finished with value: 0.4037448691443494 and parameters: {'alpha': 1.7076205357703363e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,211] Trial 2466 finished with value: 0.40374503294561637 and parameters: {'alpha': 2.8066799645690874e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  49%|████▉     | 2473/5000 [01:04<01:18, 32.02it/s]

[I 2026-06-14 00:49:37,245] Trial 2467 finished with value: 0.4037448844909154 and parameters: {'alpha': 1.7729134513963164e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,276] Trial 2468 finished with value: 0.4037452398833626 and parameters: {'alpha': 4.0809122831836446e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,307] Trial 2469 finished with value: 0.4037447045932143 and parameters: {'alpha': 1.5852319500674168e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,337] Trial 2470 finished with value: 0.40374526804905175 and parameters: {'alpha': 6.218241617421961e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,367] Trial 2471 finished with value: 0.40374490761061643 and parameters: {'alpha': 1.654674709337372e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,397] Trial 2472 finished with value: 0.403744462362836 and parameters: {'alpha': 1.0222650173099404e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,428] Trial 2473 finished with value: 0.4037450505457872 and parameters: {'alpha': 2.7973327213811968e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  50%|████▉     | 2479/5000 [01:05<01:19, 31.71it/s]

[I 2026-06-14 00:49:37,459] Trial 2474 finished with value: 0.40374532208207203 and parameters: {'alpha': 1.2916018747672347e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,491] Trial 2475 finished with value: 0.40374484870023164 and parameters: {'alpha': 1.7535174012751976e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,524] Trial 2476 finished with value: 0.40374526743663747 and parameters: {'alpha': 4.4682487021519424e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,561] Trial 2477 finished with value: 0.40374505713621317 and parameters: {'alpha': 2.645452079409512e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,604] Trial 2478 finished with value: 0.40374542764342114 and parameters: {'alpha': 0.03142990614457657}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,643] Trial 2479 finished with value: 0.4037447739311999 and parameters: {'alpha': 1.0291006604184925e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  50%|████▉     | 2485/5000 [01:05<01:26, 28.93it/s]

[I 2026-06-14 00:49:37,682] Trial 2480 finished with value: 0.4037447496595585 and parameters: {'alpha': 1.7057822466495017e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,729] Trial 2481 finished with value: 0.40378617786924803 and parameters: {'alpha': 17.28045721957977}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,762] Trial 2482 finished with value: 0.4037450040313954 and parameters: {'alpha': 2.7294143767853368e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,795] Trial 2483 finished with value: 0.40374469529721196 and parameters: {'alpha': 1.0037610652557784e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,827] Trial 2484 finished with value: 0.40374456311379076 and parameters: {'alpha': 1.0007249810304065e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,858] Trial 2485 finished with value: 0.4037447485118495 and parameters: {'alpha': 1.6759070504737643e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  50%|████▉     | 2492/5000 [01:05<01:24, 29.63it/s]

[I 2026-06-14 00:49:37,889] Trial 2486 finished with value: 0.4037452547018959 and parameters: {'alpha': 5.2631483947560864e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,921] Trial 2487 finished with value: 0.4037445995285201 and parameters: {'alpha': 1.0083478043797887e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,954] Trial 2488 finished with value: 0.40374504463592387 and parameters: {'alpha': 2.732640276525046e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:37,986] Trial 2489 finished with value: 0.40374507950194194 and parameters: {'alpha': 2.7872292999802486e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,019] Trial 2490 finished with value: 0.4037445495696807 and parameters: {'alpha': 1.0077094263056934e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,056] Trial 2491 finished with value: 0.4037448199469102 and parameters: {'alpha': 1.682755706847145e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  50%|████▉     | 2499/5000 [01:05<01:22, 30.28it/s]

[I 2026-06-14 00:49:38,095] Trial 2492 finished with value: 0.4037444851449101 and parameters: {'alpha': 1.0112098107053435e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,130] Trial 2493 finished with value: 0.40374462932604 and parameters: {'alpha': 1.010902880616482e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,164] Trial 2494 finished with value: 0.40374519037203443 and parameters: {'alpha': 4.211470873567969e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,195] Trial 2495 finished with value: 0.4037445282342892 and parameters: {'alpha': 1.0075766940951492e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,226] Trial 2496 finished with value: 0.4037444040840466 and parameters: {'alpha': 1.0005350021205238e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,256] Trial 2497 finished with value: 0.4037450535325333 and parameters: {'alpha': 2.6586445697484145e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,286] Trial 2498 finished with value: 0.40374527546759736 and parameters: {'alpha': 7.95911392613475e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  50%|█████     | 2505/5000 [01:05<01:20, 31.09it/s]

[I 2026-06-14 00:49:38,318] Trial 2499 finished with value: 0.40374503621556823 and parameters: {'alpha': 2.479128023363734e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,348] Trial 2500 finished with value: 0.40374491082447567 and parameters: {'alpha': 1.7220843702108683e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,377] Trial 2501 finished with value: 0.4037452671602995 and parameters: {'alpha': 4.576216241835913e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,408] Trial 2502 finished with value: 0.4037446543703307 and parameters: {'alpha': 1.0043629019440605e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,438] Trial 2503 finished with value: 0.40374480016704695 and parameters: {'alpha': 1.8049908540814076e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,468] Trial 2504 finished with value: 0.40374504067163874 and parameters: {'alpha': 2.6659940008638915e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,500] Trial 2505 finished with value: 0.40374429906087195 and parameters: {'alpha': 1.0016752130282684e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  50%|█████     | 2512/5000 [01:06<01:18, 31.70it/s]

[I 2026-06-14 00:49:38,530] Trial 2506 finished with value: 0.403745242354518 and parameters: {'alpha': 6.16626945672166e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,562] Trial 2507 finished with value: 0.40374540660131747 and parameters: {'alpha': 0.00020118463445843845}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,593] Trial 2508 finished with value: 0.4037449703849517 and parameters: {'alpha': 1.7738335701213877e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,626] Trial 2509 finished with value: 0.40374521667426994 and parameters: {'alpha': 4.045857812681644e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,655] Trial 2510 finished with value: 0.4037449279147411 and parameters: {'alpha': 1.759990975621758e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,688] Trial 2511 finished with value: 0.4037450360752531 and parameters: {'alpha': 2.6874696347110813e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,719] Trial 2512 finished with value: 0.40374480848934335 and parameters: {'alpha': 1.717268169125057e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  50%|█████     | 2519/5000 [01:06<01:18, 31.66it/s]

[I 2026-06-14 00:49:38,752] Trial 2513 finished with value: 0.40374535030962855 and parameters: {'alpha': 1.357555965178577e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,784] Trial 2514 finished with value: 0.40374482628546726 and parameters: {'alpha': 1.7161468464617335e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,817] Trial 2515 finished with value: 0.40860277593140554 and parameters: {'alpha': 986.2282119867808}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,849] Trial 2516 finished with value: 0.40374472269894585 and parameters: {'alpha': 1.0129269499474256e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,880] Trial 2517 finished with value: 0.40374519622436844 and parameters: {'alpha': 3.290619975230547e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,909] Trial 2518 finished with value: 0.40374486331712267 and parameters: {'alpha': 1.777388121362296e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:38,942] Trial 2519 finished with value: 0.4037452563712428 and parameters: {'alpha': 3.560413860837707e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  51%|█████     | 2527/5000 [01:06<01:17, 31.93it/s]

[I 2026-06-14 00:49:38,973] Trial 2520 finished with value: 0.40374523453827577 and parameters: {'alpha': 6.28973018282871e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,006] Trial 2521 finished with value: 0.40374492090026354 and parameters: {'alpha': 1.7795652483994825e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,036] Trial 2522 finished with value: 0.4037448844582289 and parameters: {'alpha': 1.7486748565953715e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,068] Trial 2523 finished with value: 0.4037452279940314 and parameters: {'alpha': 3.91222436477566e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,099] Trial 2524 finished with value: 0.40374492582115545 and parameters: {'alpha': 1.6930070853368753e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,129] Trial 2525 finished with value: 0.4037450236586418 and parameters: {'alpha': 2.690201637791801e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,159] Trial 2526 finished with value: 0.40374490784221306 and parameters: {'alpha': 1.7130078985912453e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  51%|█████     | 2533/5000 [01:06<01:17, 31.86it/s]

[I 2026-06-14 00:49:39,190] Trial 2527 finished with value: 0.4037453637249997 and parameters: {'alpha': 2.840108033153032e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,225] Trial 2528 finished with value: 0.40374526248037995 and parameters: {'alpha': 4.1640807370738066e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,254] Trial 2529 finished with value: 0.4037452883595039 and parameters: {'alpha': 7.693414296514987e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,285] Trial 2530 finished with value: 0.4037449575074629 and parameters: {'alpha': 1.6664056373327708e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,318] Trial 2531 finished with value: 0.5720790921594604 and parameters: {'alpha': 90671.2508918884}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,349] Trial 2532 finished with value: 0.4037450790297579 and parameters: {'alpha': 2.6177804709082844e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,381] Trial 2533 finished with value: 0.40374482392869715 and parameters: {'alpha': 1.6875807759888612e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  51%|█████     | 2540/5000 [01:06<01:16, 31.99it/s]

[I 2026-06-14 00:49:39,412] Trial 2534 finished with value: 0.40374474979535413 and parameters: {'alpha': 1.0096006261160112e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,443] Trial 2535 finished with value: 0.40374472366546593 and parameters: {'alpha': 1.0050003259152488e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,473] Trial 2536 finished with value: 0.403744990896847 and parameters: {'alpha': 2.8957388539797266e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,503] Trial 2537 finished with value: 0.40374453196369336 and parameters: {'alpha': 1.0082404487079995e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,534] Trial 2538 finished with value: 0.40374528290194317 and parameters: {'alpha': 4.598038404534106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,566] Trial 2539 finished with value: 0.40374498324320507 and parameters: {'alpha': 1.7525804124298787e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,597] Trial 2540 finished with value: 0.4037446682049096 and parameters: {'alpha': 1.0160212735024969e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  51%|█████     | 2547/5000 [01:07<01:17, 31.82it/s]

[I 2026-06-14 00:49:39,631] Trial 2541 finished with value: 0.5074277457462624 and parameters: {'alpha': 15064.230007604196}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,663] Trial 2542 finished with value: 0.4037449994794032 and parameters: {'alpha': 2.5278234087082592e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,696] Trial 2543 finished with value: 0.40374527436927465 and parameters: {'alpha': 8.655838200758872e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,726] Trial 2544 finished with value: 0.40374479676564284 and parameters: {'alpha': 1.685910561250132e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,757] Trial 2545 finished with value: 0.4037451344511436 and parameters: {'alpha': 3.0188387305869003e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,788] Trial 2546 finished with value: 0.4037448011331323 and parameters: {'alpha': 1.769338813768115e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,820] Trial 2547 finished with value: 0.403745280168706 and parameters: {'alpha': 4.469019395467974e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  51%|█████     | 2555/5000 [01:07<01:16, 31.89it/s]

[I 2026-06-14 00:49:39,851] Trial 2548 finished with value: 0.40374457307529527 and parameters: {'alpha': 1.0198714530656304e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,882] Trial 2549 finished with value: 0.40374512925571926 and parameters: {'alpha': 2.9246024107736195e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,914] Trial 2550 finished with value: 0.40374481546123364 and parameters: {'alpha': 1.6797288844853248e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,946] Trial 2551 finished with value: 0.40374468283442744 and parameters: {'alpha': 1.0078942978086201e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:39,978] Trial 2552 finished with value: 0.40374434030097156 and parameters: {'alpha': 1.0015358396350162e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,007] Trial 2553 finished with value: 0.4037449840423726 and parameters: {'alpha': 2.637231297925888e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,037] Trial 2554 finished with value: 0.40374523083520975 and parameters: {'alpha': 6.174263436654232e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  51%|█████     | 2560/5000 [01:07<01:19, 30.60it/s]

[I 2026-06-14 00:49:40,070] Trial 2555 finished with value: 0.4037449319190644 and parameters: {'alpha': 1.748712137066459e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,100] Trial 2556 finished with value: 0.40374464395366805 and parameters: {'alpha': 1.0107533498998351e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,130] Trial 2557 finished with value: 0.4037450871663157 and parameters: {'alpha': 2.7507116456597603e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,180] Trial 2558 finished with value: 0.40374477764282823 and parameters: {'alpha': 1.7779052431154772e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,222] Trial 2559 finished with value: 0.4037452334680432 and parameters: {'alpha': 4.283162698594627e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,257] Trial 2560 finished with value: 0.40374492677250173 and parameters: {'alpha': 1.6718347842259668e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  51%|█████▏    | 2567/5000 [01:07<01:20, 30.18it/s]

[I 2026-06-14 00:49:40,296] Trial 2561 finished with value: 0.40374447176178124 and parameters: {'alpha': 1.0172867365126233e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,328] Trial 2562 finished with value: 0.40374500319825607 and parameters: {'alpha': 2.7702299874973168e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,362] Trial 2563 finished with value: 0.4037452920696802 and parameters: {'alpha': 6.549114943397894e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,394] Trial 2564 finished with value: 0.40374487517902785 and parameters: {'alpha': 1.8105783219446292e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,424] Trial 2565 finished with value: 0.4037450385603808 and parameters: {'alpha': 2.8412028969379593e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,453] Trial 2566 finished with value: 0.4037448302550596 and parameters: {'alpha': 1.625537444645817e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,485] Trial 2567 finished with value: 0.4037453508756388 and parameters: {'alpha': 1.4385562343331137e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  52%|█████▏    | 2575/5000 [01:08<01:18, 30.90it/s]

[I 2026-06-14 00:49:40,517] Trial 2568 finished with value: 0.40374529726919073 and parameters: {'alpha': 4.1102118698742854e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,549] Trial 2569 finished with value: 0.40374498213801907 and parameters: {'alpha': 1.7210558191207397e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,580] Trial 2570 finished with value: 0.40374478242171086 and parameters: {'alpha': 1.6512639791032196e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,611] Trial 2571 finished with value: 0.4037443435425301 and parameters: {'alpha': 1.023651961069475e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,644] Trial 2572 finished with value: 0.4037450651187403 and parameters: {'alpha': 2.8959609229019376e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,676] Trial 2573 finished with value: 0.40374505129567256 and parameters: {'alpha': 2.645571990970552e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,707] Trial 2574 finished with value: 0.4037453128459724 and parameters: {'alpha': 5.288757795354501e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  52%|█████▏    | 2581/5000 [01:08<01:18, 30.82it/s]

[I 2026-06-14 00:49:40,741] Trial 2575 finished with value: 0.4037449597504882 and parameters: {'alpha': 1.6950710196313528e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,774] Trial 2576 finished with value: 0.403744711835561 and parameters: {'alpha': 1.0146320640713841e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,806] Trial 2577 finished with value: 0.40374476836857676 and parameters: {'alpha': 1.7651800148739413e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,837] Trial 2578 finished with value: 0.40374531052433205 and parameters: {'alpha': 1.0618329129331142e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,869] Trial 2579 finished with value: 0.40374523203839274 and parameters: {'alpha': 4.5562319551974076e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,900] Trial 2580 finished with value: 0.4037445708200623 and parameters: {'alpha': 1.017638880383658e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,932] Trial 2581 finished with value: 0.4037452088003628 and parameters: {'alpha': 3.083268197945702e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  52%|█████▏    | 2588/5000 [01:08<01:16, 31.56it/s]

[I 2026-06-14 00:49:40,963] Trial 2582 finished with value: 0.40374478258838514 and parameters: {'alpha': 1.7357224273799297e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:40,994] Trial 2583 finished with value: 0.403744739588971 and parameters: {'alpha': 1.6973540041115984e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,025] Trial 2584 finished with value: 0.40374427177959266 and parameters: {'alpha': 1.0028408754238168e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,055] Trial 2585 finished with value: 0.40374447429976207 and parameters: {'alpha': 1.0160401427187883e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,085] Trial 2586 finished with value: 0.4037449662382695 and parameters: {'alpha': 2.5971994915242695e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,117] Trial 2587 finished with value: 0.4037452947462629 and parameters: {'alpha': 5.134163149430039e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,149] Trial 2588 finished with value: 0.40374504858218574 and parameters: {'alpha': 2.742663570761655e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  52%|█████▏    | 2595/5000 [01:08<01:15, 32.05it/s]

[I 2026-06-14 00:49:41,180] Trial 2589 finished with value: 0.40374434649674135 and parameters: {'alpha': 1.0187635566975422e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,211] Trial 2590 finished with value: 0.4037443001600629 and parameters: {'alpha': 1.021686522337579e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,242] Trial 2591 finished with value: 0.4037447876449598 and parameters: {'alpha': 1.7200456408635638e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,273] Trial 2592 finished with value: 0.4037452793743261 and parameters: {'alpha': 7.66217324508418e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,303] Trial 2593 finished with value: 0.4037449858235435 and parameters: {'alpha': 2.5443319518606755e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,332] Trial 2594 finished with value: 0.40374520719843104 and parameters: {'alpha': 3.988234721760689e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,365] Trial 2595 finished with value: 0.4037447405618842 and parameters: {'alpha': 1.6759556001169226e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  52%|█████▏    | 2603/5000 [01:08<01:15, 31.67it/s]

[I 2026-06-14 00:49:41,397] Trial 2596 finished with value: 0.4037443975929107 and parameters: {'alpha': 1.0149428251624206e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,428] Trial 2597 finished with value: 0.4037450064542034 and parameters: {'alpha': 2.546624986534353e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,459] Trial 2598 finished with value: 0.40374491765539583 and parameters: {'alpha': 1.7861088654223673e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,491] Trial 2599 finished with value: 0.40374525370290165 and parameters: {'alpha': 3.8709974277512656e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,523] Trial 2600 finished with value: 0.40374499364926575 and parameters: {'alpha': 2.7048679199447165e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,555] Trial 2601 finished with value: 0.4037443482123133 and parameters: {'alpha': 1.0074818910385659e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,587] Trial 2602 finished with value: 0.403745408905508 and parameters: {'alpha': 0.0035833454396836132}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  52%|█████▏    | 2609/5000 [01:09<01:16, 31.08it/s]

[I 2026-06-14 00:49:41,620] Trial 2603 finished with value: 0.4037445986895591 and parameters: {'alpha': 1.004714916282563e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,655] Trial 2604 finished with value: 0.40374531005635 and parameters: {'alpha': 8.449294282790967e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,687] Trial 2605 finished with value: 0.403744818321613 and parameters: {'alpha': 1.6876485973562578e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,720] Trial 2606 finished with value: 0.4037448460400325 and parameters: {'alpha': 1.7184048283440427e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,754] Trial 2607 finished with value: 0.4037452102827157 and parameters: {'alpha': 4.045819097019643e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,785] Trial 2608 finished with value: 0.4037442511098815 and parameters: {'alpha': 1.0152260522271486e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,817] Trial 2609 finished with value: 0.40374448888098885 and parameters: {'alpha': 1.0135157106092258e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  52%|█████▏    | 2616/5000 [01:09<01:15, 31.45it/s]

[I 2026-06-14 00:49:41,849] Trial 2610 finished with value: 0.40374473377387576 and parameters: {'alpha': 1.0117094459929405e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,883] Trial 2611 finished with value: 0.4037449966449507 and parameters: {'alpha': 2.6312788836076653e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,915] Trial 2612 finished with value: 0.40374432841177127 and parameters: {'alpha': 1.0103359303411116e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,944] Trial 2613 finished with value: 0.4037452810119731 and parameters: {'alpha': 5.717274636843855e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:41,974] Trial 2614 finished with value: 0.40374490084080333 and parameters: {'alpha': 1.7771507355795813e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,006] Trial 2615 finished with value: 0.4037451090438938 and parameters: {'alpha': 2.9083508343773407e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,036] Trial 2616 finished with value: 0.4037448952435677 and parameters: {'alpha': 1.7348999258827174e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  52%|█████▏    | 2623/5000 [01:09<01:14, 31.73it/s]

[I 2026-06-14 00:49:42,067] Trial 2617 finished with value: 0.4037452849780011 and parameters: {'alpha': 4.3508398619626494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,098] Trial 2618 finished with value: 0.40374492597844497 and parameters: {'alpha': 2.329736297101775e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,131] Trial 2619 finished with value: 0.40374475538167415 and parameters: {'alpha': 1.7178109489064077e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,161] Trial 2620 finished with value: 0.40374482355006736 and parameters: {'alpha': 1.6820226045141463e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,191] Trial 2621 finished with value: 0.40374517221119555 and parameters: {'alpha': 3.7018969526726825e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,224] Trial 2622 finished with value: 0.4037453228155604 and parameters: {'alpha': 1.1662274245730761e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,256] Trial 2623 finished with value: 0.4037450408818988 and parameters: {'alpha': 2.838286185604168e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  53%|█████▎    | 2631/5000 [01:09<01:14, 32.01it/s]

[I 2026-06-14 00:49:42,286] Trial 2624 finished with value: 0.4037449383250011 and parameters: {'alpha': 1.6637634868363585e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,318] Trial 2625 finished with value: 0.4037446208566396 and parameters: {'alpha': 1.0080763655238872e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,349] Trial 2626 finished with value: 0.40374527544584976 and parameters: {'alpha': 7.444347283191048e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,381] Trial 2627 finished with value: 0.40374508794294195 and parameters: {'alpha': 2.849569254171332e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,412] Trial 2628 finished with value: 0.40374486641623414 and parameters: {'alpha': 1.7160852858673916e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,441] Trial 2629 finished with value: 0.4037449444835765 and parameters: {'alpha': 1.748531510838012e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,472] Trial 2630 finished with value: 0.40374527300659846 and parameters: {'alpha': 5.276284010158963e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  53%|█████▎    | 2637/5000 [01:10<01:13, 32.17it/s]

[I 2026-06-14 00:49:42,504] Trial 2631 finished with value: 0.403744269154608 and parameters: {'alpha': 1.0027378242486853e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,534] Trial 2632 finished with value: 0.4037444884213495 and parameters: {'alpha': 1.0132091762205284e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,565] Trial 2633 finished with value: 0.40374497757246003 and parameters: {'alpha': 2.6046132319612334e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,596] Trial 2634 finished with value: 0.40374433931802506 and parameters: {'alpha': 1.0159336238493384e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,627] Trial 2635 finished with value: 0.4037448348097914 and parameters: {'alpha': 1.742828446490121e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,656] Trial 2636 finished with value: 0.403745283851969 and parameters: {'alpha': 4.841552946760168e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,690] Trial 2637 finished with value: 0.4037449607733919 and parameters: {'alpha': 2.5824866305447332e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  53%|█████▎    | 2644/5000 [01:10<01:13, 32.12it/s]

[I 2026-06-14 00:49:42,722] Trial 2638 finished with value: 0.4037447411280327 and parameters: {'alpha': 1.7018787620281877e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,754] Trial 2639 finished with value: 0.4037448625425417 and parameters: {'alpha': 1.702366420526128e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,784] Trial 2640 finished with value: 0.4037451800299229 and parameters: {'alpha': 3.956514493267459e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,815] Trial 2641 finished with value: 0.40374440265988243 and parameters: {'alpha': 1.0152013006468105e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,845] Trial 2642 finished with value: 0.40374512598586815 and parameters: {'alpha': 3.02796400130699e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,877] Trial 2643 finished with value: 0.4037449659819983 and parameters: {'alpha': 1.779019808360344e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,907] Trial 2644 finished with value: 0.4037448416357334 and parameters: {'alpha': 1.7688340094981806e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  53%|█████▎    | 2651/5000 [01:10<01:12, 32.24it/s]

[I 2026-06-14 00:49:42,936] Trial 2645 finished with value: 0.4037445676742146 and parameters: {'alpha': 1.0119627794920639e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:42,969] Trial 2646 finished with value: 0.4052150845890305 and parameters: {'alpha': 442.79296774870244}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,000] Trial 2647 finished with value: 0.40374459470544366 and parameters: {'alpha': 1.0001255951402946e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,031] Trial 2648 finished with value: 0.40374453954798933 and parameters: {'alpha': 1.0041075631130566e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,062] Trial 2649 finished with value: 0.4037453600670853 and parameters: {'alpha': 2.0727691924803574e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,092] Trial 2650 finished with value: 0.40374528278146266 and parameters: {'alpha': 6.510442295969808e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,124] Trial 2651 finished with value: 0.4037451626777594 and parameters: {'alpha': 3.207613547878417e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  53%|█████▎    | 2659/5000 [01:10<01:12, 32.27it/s]

[I 2026-06-14 00:49:43,154] Trial 2652 finished with value: 0.403745052893009 and parameters: {'alpha': 2.6476151165178082e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,186] Trial 2653 finished with value: 0.40374481788333766 and parameters: {'alpha': 1.7513488166905347e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,217] Trial 2654 finished with value: 0.40374465752108435 and parameters: {'alpha': 1.0114566018437853e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,248] Trial 2655 finished with value: 0.4037452474339253 and parameters: {'alpha': 4.6847815986951455e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,279] Trial 2656 finished with value: 0.4037447912828439 and parameters: {'alpha': 1.7546890900550537e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,309] Trial 2657 finished with value: 0.4037450120260148 and parameters: {'alpha': 2.453504125852955e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,340] Trial 2658 finished with value: 0.4037448625152806 and parameters: {'alpha': 1.7306870167960716e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  53%|█████▎    | 2665/5000 [01:10<01:12, 32.18it/s]

[I 2026-06-14 00:49:43,372] Trial 2659 finished with value: 0.40374525409948175 and parameters: {'alpha': 3.568109995247351e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,403] Trial 2660 finished with value: 0.4037443178291565 and parameters: {'alpha': 1.0098284306502467e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,433] Trial 2661 finished with value: 0.40374530636599315 and parameters: {'alpha': 1.0148652296112574e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,464] Trial 2662 finished with value: 0.40374490394952595 and parameters: {'alpha': 1.73347678348236e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,496] Trial 2663 finished with value: 0.4037451722446475 and parameters: {'alpha': 4.197029104375224e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,526] Trial 2664 finished with value: 0.4037447732742635 and parameters: {'alpha': 1.7143814498484704e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,558] Trial 2665 finished with value: 0.40374504500573033 and parameters: {'alpha': 2.6585216519544614e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  53%|█████▎    | 2672/5000 [01:11<01:12, 32.01it/s]

[I 2026-06-14 00:49:43,589] Trial 2666 finished with value: 0.4037452927972521 and parameters: {'alpha': 6.790273882735515e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,621] Trial 2667 finished with value: 0.40374497676574417 and parameters: {'alpha': 1.7513008153124716e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,651] Trial 2668 finished with value: 0.40374505101000513 and parameters: {'alpha': 2.83127852926165e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,684] Trial 2669 finished with value: 0.40374498350359983 and parameters: {'alpha': 1.7759377732375644e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,716] Trial 2670 finished with value: 0.4037444885595775 and parameters: {'alpha': 1.013318658298874e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,748] Trial 2671 finished with value: 0.40374526869279176 and parameters: {'alpha': 4.3503637656021886e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,779] Trial 2672 finished with value: 0.4037442856470259 and parameters: {'alpha': 1.0082605441329866e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  54%|█████▎    | 2679/5000 [01:11<01:13, 31.63it/s]

[I 2026-06-14 00:49:43,811] Trial 2673 finished with value: 0.4037450163473289 and parameters: {'alpha': 2.7518298944913498e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,841] Trial 2674 finished with value: 0.4037446734229014 and parameters: {'alpha': 1.0110789197156869e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,874] Trial 2675 finished with value: 0.40374499854580986 and parameters: {'alpha': 2.7662753505755543e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,905] Trial 2676 finished with value: 0.4037445473117266 and parameters: {'alpha': 1.006227338311356e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,937] Trial 2677 finished with value: 0.4037449430614826 and parameters: {'alpha': 1.741550300150282e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:43,971] Trial 2678 finished with value: 0.4037452575743764 and parameters: {'alpha': 4.596647111550766e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,004] Trial 2679 finished with value: 0.4037447850596388 and parameters: {'alpha': 1.834364543336594e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  54%|█████▎    | 2687/5000 [01:11<01:13, 31.60it/s]

[I 2026-06-14 00:49:44,039] Trial 2680 finished with value: 0.40374476850038415 and parameters: {'alpha': 1.700727469576638e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,070] Trial 2681 finished with value: 0.4037452696802905 and parameters: {'alpha': 6.527123895199927e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,100] Trial 2682 finished with value: 0.40374493629142977 and parameters: {'alpha': 1.7099091480733224e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,132] Trial 2683 finished with value: 0.403745007053201 and parameters: {'alpha': 2.840923982732274e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,163] Trial 2684 finished with value: 0.4037447228015888 and parameters: {'alpha': 1.681421071464855e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,194] Trial 2685 finished with value: 0.40374427127883994 and parameters: {'alpha': 1.0117067810812889e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,225] Trial 2686 finished with value: 0.4037451470575631 and parameters: {'alpha': 3.531594016213991e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  54%|█████▍    | 2693/5000 [01:11<01:12, 31.89it/s]

[I 2026-06-14 00:49:44,257] Trial 2687 finished with value: 0.403745003960064 and parameters: {'alpha': 2.7603328186782386e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,287] Trial 2688 finished with value: 0.40374533132680096 and parameters: {'alpha': 1.0718427493051114e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,317] Trial 2689 finished with value: 0.40374445725429925 and parameters: {'alpha': 1.0235453171822699e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,348] Trial 2690 finished with value: 0.4037443124886951 and parameters: {'alpha': 1.0082034041195346e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,381] Trial 2691 finished with value: 0.4037442579543028 and parameters: {'alpha': 1.0098555089006175e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,412] Trial 2692 finished with value: 0.4037453249900339 and parameters: {'alpha': 5.7106486747180056e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,443] Trial 2693 finished with value: 0.4037448916205503 and parameters: {'alpha': 1.8423627360529096e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  54%|█████▍    | 2700/5000 [01:12<01:12, 31.64it/s]

[I 2026-06-14 00:49:44,474] Trial 2694 finished with value: 0.4037445579739324 and parameters: {'alpha': 1.0128822764600082e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,507] Trial 2695 finished with value: 0.4037450998964076 and parameters: {'alpha': 2.7257046355362745e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,538] Trial 2696 finished with value: 0.40374493296564656 and parameters: {'alpha': 1.7442011941997327e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,569] Trial 2697 finished with value: 0.403744523629314 and parameters: {'alpha': 1.013486223964169e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,601] Trial 2698 finished with value: 0.4037452587315208 and parameters: {'alpha': 4.229375394041371e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,635] Trial 2699 finished with value: 0.4037450183679551 and parameters: {'alpha': 2.66018530531912e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,667] Trial 2700 finished with value: 0.40374451771681696 and parameters: {'alpha': 1.0050244933679795e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  54%|█████▍    | 2707/5000 [01:12<01:13, 31.11it/s]

[I 2026-06-14 00:49:44,703] Trial 2701 finished with value: 0.4037449615311307 and parameters: {'alpha': 1.7483758870664818e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,737] Trial 2702 finished with value: 0.4037450824857822 and parameters: {'alpha': 2.6978216499250435e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,769] Trial 2703 finished with value: 0.40374529076841553 and parameters: {'alpha': 5.7778616387803395e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,803] Trial 2704 finished with value: 0.403745407463406 and parameters: {'alpha': 0.0014313105752343362}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,834] Trial 2705 finished with value: 0.4037444833197987 and parameters: {'alpha': 1.0081311078450115e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,865] Trial 2706 finished with value: 0.40374485568613366 and parameters: {'alpha': 1.8151703302772483e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,897] Trial 2707 finished with value: 0.4037443490020935 and parameters: {'alpha': 1.0075704637071926e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  54%|█████▍    | 2713/5000 [01:12<01:13, 31.26it/s]

[I 2026-06-14 00:49:44,928] Trial 2708 finished with value: 0.4037451882975938 and parameters: {'alpha': 3.6860024758671617e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,959] Trial 2709 finished with value: 0.40374439222363157 and parameters: {'alpha': 1.0065303188256299e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:44,991] Trial 2710 finished with value: 0.40374492651439237 and parameters: {'alpha': 1.7732763651449858e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,025] Trial 2711 finished with value: 0.4037449733246083 and parameters: {'alpha': 2.653088988073329e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,060] Trial 2712 finished with value: 0.4037452675495622 and parameters: {'alpha': 6.623359079249029e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,096] Trial 2713 finished with value: 0.40374496262147774 and parameters: {'alpha': 1.7832526607309176e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  54%|█████▍    | 2719/5000 [01:12<01:16, 29.76it/s]

[I 2026-06-14 00:49:45,130] Trial 2714 finished with value: 0.40374483820790336 and parameters: {'alpha': 1.7106949644306298e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,169] Trial 2715 finished with value: 0.40374517509689645 and parameters: {'alpha': 3.609346916502832e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,203] Trial 2716 finished with value: 0.40374531890962106 and parameters: {'alpha': 1.2376725198430073e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,236] Trial 2717 finished with value: 0.40374464767648094 and parameters: {'alpha': 1.0125531699784154e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,271] Trial 2718 finished with value: 0.4037450128487705 and parameters: {'alpha': 2.712057943390319e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,306] Trial 2719 finished with value: 0.4037449649876655 and parameters: {'alpha': 1.691978260571637e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  55%|█████▍    | 2727/5000 [01:12<01:13, 30.75it/s]

[I 2026-06-14 00:49:45,339] Trial 2720 finished with value: 0.4037452750417926 and parameters: {'alpha': 4.3473705976297525e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,370] Trial 2721 finished with value: 0.40374492343937274 and parameters: {'alpha': 1.7955846427420365e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,401] Trial 2722 finished with value: 0.4037450111075901 and parameters: {'alpha': 2.6685939217672024e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,432] Trial 2723 finished with value: 0.4037447643160793 and parameters: {'alpha': 1.7402372534616394e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,464] Trial 2724 finished with value: 0.4037452991361881 and parameters: {'alpha': 7.464238018726172e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,495] Trial 2725 finished with value: 0.40374528265247606 and parameters: {'alpha': 4.435287902800145e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,526] Trial 2726 finished with value: 0.40374494648221004 and parameters: {'alpha': 1.674955549875337e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  55%|█████▍    | 2732/5000 [01:13<01:15, 29.84it/s]

[I 2026-06-14 00:49:45,559] Trial 2727 finished with value: 0.40374457501174105 and parameters: {'alpha': 1.0050949379821136e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,594] Trial 2728 finished with value: 0.40374468233885535 and parameters: {'alpha': 1.0093144537365285e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,629] Trial 2729 finished with value: 0.4037449852787442 and parameters: {'alpha': 2.685773782861687e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,666] Trial 2730 finished with value: 0.40374477871164816 and parameters: {'alpha': 1.715100645199406e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,703] Trial 2731 finished with value: 0.4037451753518588 and parameters: {'alpha': 3.7250491847246645e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,743] Trial 2732 finished with value: 0.40415730219963086 and parameters: {'alpha': 143.02084687045772}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  55%|█████▍    | 2738/5000 [01:13<01:17, 29.29it/s]

[I 2026-06-14 00:49:45,776] Trial 2733 finished with value: 0.4037449161757155 and parameters: {'alpha': 1.7158699561506944e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,812] Trial 2734 finished with value: 0.40374469375457145 and parameters: {'alpha': 1.011690056731672e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,846] Trial 2735 finished with value: 0.40374497929969727 and parameters: {'alpha': 2.6039668208696425e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,878] Trial 2736 finished with value: 0.40374478039393 and parameters: {'alpha': 1.7078229620707824e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,914] Trial 2737 finished with value: 0.4037452922898354 and parameters: {'alpha': 5.517592821900781e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:45,951] Trial 2738 finished with value: 0.40374508045941754 and parameters: {'alpha': 2.788421610632103e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  55%|█████▍    | 2745/5000 [01:13<01:15, 29.79it/s]

[I 2026-06-14 00:49:45,986] Trial 2739 finished with value: 0.40374481653764194 and parameters: {'alpha': 1.628109771703244e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,022] Trial 2740 finished with value: 0.40374440638631776 and parameters: {'alpha': 1.0188804575755818e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,052] Trial 2741 finished with value: 0.40374497656109376 and parameters: {'alpha': 2.7247782055047613e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,083] Trial 2742 finished with value: 0.4037448801804346 and parameters: {'alpha': 1.7868338088594104e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,113] Trial 2743 finished with value: 0.40374529583373137 and parameters: {'alpha': 9.3609244474604e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,145] Trial 2744 finished with value: 0.40374461247925 and parameters: {'alpha': 1.0213684817912388e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,175] Trial 2745 finished with value: 0.40374521806432795 and parameters: {'alpha': 4.605390562016624e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  55%|█████▌    | 2752/5000 [01:13<01:12, 31.00it/s]

[I 2026-06-14 00:49:46,206] Trial 2746 finished with value: 0.403745043645678 and parameters: {'alpha': 2.635615488465364e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,238] Trial 2747 finished with value: 0.4037446208415748 and parameters: {'alpha': 1.01247983402629e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,268] Trial 2748 finished with value: 0.40374539035680995 and parameters: {'alpha': 5.245628399727186e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,300] Trial 2749 finished with value: 0.40374481153573777 and parameters: {'alpha': 1.7748975189400737e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,330] Trial 2750 finished with value: 0.4037453031952079 and parameters: {'alpha': 4.3607688741250816e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,361] Trial 2751 finished with value: 0.40374496388756587 and parameters: {'alpha': 1.7337375524198306e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,393] Trial 2752 finished with value: 0.4037445687657206 and parameters: {'alpha': 1.0101967533304984e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  55%|█████▌    | 2760/5000 [01:13<01:10, 31.58it/s]

[I 2026-06-14 00:49:46,424] Trial 2753 finished with value: 0.40374507698196066 and parameters: {'alpha': 2.8591659248580218e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,456] Trial 2754 finished with value: 0.4037447236874897 and parameters: {'alpha': 1.0182455427901304e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,486] Trial 2755 finished with value: 0.4037449643838899 and parameters: {'alpha': 1.7418563095673667e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,519] Trial 2756 finished with value: 0.4037452925318764 and parameters: {'alpha': 4.040237875184057e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,549] Trial 2757 finished with value: 0.4037445902339582 and parameters: {'alpha': 1.0125922456157579e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,581] Trial 2758 finished with value: 0.4037452374003916 and parameters: {'alpha': 6.55410709248664e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,611] Trial 2759 finished with value: 0.40374504656198973 and parameters: {'alpha': 2.457432279885269e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  55%|█████▌    | 2766/5000 [01:14<01:11, 31.42it/s]

[I 2026-06-14 00:49:46,644] Trial 2760 finished with value: 0.4037447693871769 and parameters: {'alpha': 1.7021343844787487e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,674] Trial 2761 finished with value: 0.4037453474288496 and parameters: {'alpha': 1.8236746740950494e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,706] Trial 2762 finished with value: 0.4037449870869296 and parameters: {'alpha': 2.6956065265868406e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,739] Trial 2763 finished with value: 0.40374435708842843 and parameters: {'alpha': 1.0100696192199935e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,771] Trial 2764 finished with value: 0.4037449974180379 and parameters: {'alpha': 1.8327986759129244e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,802] Trial 2765 finished with value: 0.403745187743317 and parameters: {'alpha': 4.124835656401608e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,832] Trial 2766 finished with value: 0.40374485920462555 and parameters: {'alpha': 1.8153747647715335e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  55%|█████▌    | 2773/5000 [01:14<01:09, 31.96it/s]

[I 2026-06-14 00:49:46,862] Trial 2767 finished with value: 0.4037445470230034 and parameters: {'alpha': 1.0009938981108687e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,895] Trial 2768 finished with value: 0.4037445393828169 and parameters: {'alpha': 1.0017323287590792e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,925] Trial 2769 finished with value: 0.40374527385844944 and parameters: {'alpha': 7.176687731816351e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,956] Trial 2770 finished with value: 0.40374439284666347 and parameters: {'alpha': 1.0074582640537202e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:46,986] Trial 2771 finished with value: 0.4037457080175542 and parameters: {'alpha': 0.4097417343956778}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,018] Trial 2772 finished with value: 0.40374506387702286 and parameters: {'alpha': 2.7850567666195734e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,049] Trial 2773 finished with value: 0.4037449614276552 and parameters: {'alpha': 1.810182359286274e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  56%|█████▌    | 2780/5000 [01:14<01:09, 31.93it/s]

[I 2026-06-14 00:49:47,080] Trial 2774 finished with value: 0.4037452767991094 and parameters: {'alpha': 4.114854197026729e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,113] Trial 2775 finished with value: 0.40374475126197584 and parameters: {'alpha': 1.7552591523619552e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,144] Trial 2776 finished with value: 0.4037450521405081 and parameters: {'alpha': 2.5327413296904492e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,175] Trial 2777 finished with value: 0.4037449733417146 and parameters: {'alpha': 1.74310815225074e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,206] Trial 2778 finished with value: 0.40374523767844034 and parameters: {'alpha': 3.895517491664379e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,237] Trial 2779 finished with value: 0.4037445521200962 and parameters: {'alpha': 1.016363649954961e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,269] Trial 2780 finished with value: 0.40374529345933596 and parameters: {'alpha': 7.873374475020241e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  56%|█████▌    | 2788/5000 [01:14<01:09, 31.94it/s]

[I 2026-06-14 00:49:47,300] Trial 2781 finished with value: 0.4037449510476326 and parameters: {'alpha': 1.726213250230106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,333] Trial 2782 finished with value: 0.4037444604091978 and parameters: {'alpha': 1.003606152450905e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,365] Trial 2783 finished with value: 0.40374503877846973 and parameters: {'alpha': 2.7071370607275014e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,397] Trial 2784 finished with value: 0.4037448888724469 and parameters: {'alpha': 1.7112496493936292e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,427] Trial 2785 finished with value: 0.40374463294585944 and parameters: {'alpha': 1.0029125313607591e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,457] Trial 2786 finished with value: 0.40374539835087725 and parameters: {'alpha': 1.01345339529275e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,488] Trial 2787 finished with value: 0.403745276727968 and parameters: {'alpha': 4.118052661630407e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  56%|█████▌    | 2794/5000 [01:15<01:09, 31.88it/s]

[I 2026-06-14 00:49:47,521] Trial 2788 finished with value: 0.4037450881579362 and parameters: {'alpha': 2.6980824288732408e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,553] Trial 2789 finished with value: 0.4037446360692832 and parameters: {'alpha': 1.0007913678790017e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,584] Trial 2790 finished with value: 0.40374479825053766 and parameters: {'alpha': 1.805139443994723e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,614] Trial 2791 finished with value: 0.40374522889175707 and parameters: {'alpha': 4.258878276919792e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,647] Trial 2792 finished with value: 0.40374461198567213 and parameters: {'alpha': 1.0087352186111794e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,678] Trial 2793 finished with value: 0.4037453186156561 and parameters: {'alpha': 1.1590085552152997e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,708] Trial 2794 finished with value: 0.40374501314004474 and parameters: {'alpha': 2.6408430957084866e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  56%|█████▌    | 2801/5000 [01:15<01:09, 31.85it/s]

[I 2026-06-14 00:49:47,742] Trial 2795 finished with value: 0.403744297474087 and parameters: {'alpha': 1.0034368176222795e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,775] Trial 2796 finished with value: 0.40374478161028066 and parameters: {'alpha': 1.8700720936503836e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,805] Trial 2797 finished with value: 0.40374456654772684 and parameters: {'alpha': 1.002176014251355e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,836] Trial 2798 finished with value: 0.4037452666827313 and parameters: {'alpha': 6.866663819902234e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,867] Trial 2799 finished with value: 0.40374500728486873 and parameters: {'alpha': 2.568783917455233e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,898] Trial 2800 finished with value: 0.4037448630331631 and parameters: {'alpha': 1.670830995706672e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,928] Trial 2801 finished with value: 0.4037452156870348 and parameters: {'alpha': 4.203867979462988e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  56%|█████▌    | 2808/5000 [01:15<01:09, 31.71it/s]

[I 2026-06-14 00:49:47,960] Trial 2802 finished with value: 0.4037447950602109 and parameters: {'alpha': 1.7525108105316124e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:47,992] Trial 2803 finished with value: 0.4037450273654005 and parameters: {'alpha': 2.9469083942146082e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,024] Trial 2804 finished with value: 0.4037448890218105 and parameters: {'alpha': 1.7756701363583965e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,055] Trial 2805 finished with value: 0.4037448763589047 and parameters: {'alpha': 1.7237518718303173e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,086] Trial 2806 finished with value: 0.4037452908925266 and parameters: {'alpha': 5.408490737510387e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,118] Trial 2807 finished with value: 0.4037449154638516 and parameters: {'alpha': 1.7434875380348866e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,150] Trial 2808 finished with value: 0.4037454628634535 and parameters: {'alpha': 0.08274890590452538}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  56%|█████▋    | 2816/5000 [01:15<01:08, 31.81it/s]

[I 2026-06-14 00:49:48,182] Trial 2809 finished with value: 0.4037450045015601 and parameters: {'alpha': 2.6983527254334722e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,214] Trial 2810 finished with value: 0.4037442567483236 and parameters: {'alpha': 1.0128288143064494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,245] Trial 2811 finished with value: 0.40374489657259105 and parameters: {'alpha': 1.723604432289471e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,277] Trial 2812 finished with value: 0.40374466250863333 and parameters: {'alpha': 1.0146160682185956e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,308] Trial 2813 finished with value: 0.4037452729964935 and parameters: {'alpha': 3.8462980236330827e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,339] Trial 2814 finished with value: 0.4037450774943657 and parameters: {'alpha': 2.785527786187611e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,370] Trial 2815 finished with value: 0.4037447327014298 and parameters: {'alpha': 1.7101348217804445e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  56%|█████▋    | 2822/5000 [01:15<01:08, 31.93it/s]

[I 2026-06-14 00:49:48,402] Trial 2816 finished with value: 0.4037452692774069 and parameters: {'alpha': 7.818316549075941e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,434] Trial 2817 finished with value: 0.40374511540665603 and parameters: {'alpha': 2.974984839475112e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,464] Trial 2818 finished with value: 0.4037448947160675 and parameters: {'alpha': 1.734938121896994e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,495] Trial 2819 finished with value: 0.40374540474822745 and parameters: {'alpha': 4.38817158734876e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,526] Trial 2820 finished with value: 0.4037449164839046 and parameters: {'alpha': 1.6878796739653257e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,557] Trial 2821 finished with value: 0.40374524376919607 and parameters: {'alpha': 4.9426457201186814e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,587] Trial 2822 finished with value: 0.4037446680788296 and parameters: {'alpha': 1.0118135468456207e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  57%|█████▋    | 2829/5000 [01:16<01:07, 31.98it/s]

[I 2026-06-14 00:49:48,619] Trial 2823 finished with value: 0.4037444652496293 and parameters: {'alpha': 1.0173526162330016e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,651] Trial 2824 finished with value: 0.40374504997198685 and parameters: {'alpha': 2.7105713632300092e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,682] Trial 2825 finished with value: 0.4037453248694358 and parameters: {'alpha': 1.4110744967980888e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,713] Trial 2826 finished with value: 0.40374482226777825 and parameters: {'alpha': 1.689034794242281e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,743] Trial 2827 finished with value: 0.40374516742827304 and parameters: {'alpha': 3.8221327999517245e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,778] Trial 2828 finished with value: 0.40374503545519663 and parameters: {'alpha': 2.848900678716463e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,809] Trial 2829 finished with value: 0.530096027605759 and parameters: {'alpha': 23661.498144653466}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  57%|█████▋    | 2836/5000 [01:16<01:08, 31.70it/s]

[I 2026-06-14 00:49:48,841] Trial 2830 finished with value: 0.4037447745393863 and parameters: {'alpha': 1.6893951809187465e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,872] Trial 2831 finished with value: 0.40374532133590374 and parameters: {'alpha': 5.576172720370293e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,904] Trial 2832 finished with value: 0.403744839446123 and parameters: {'alpha': 1.677493292045614e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,935] Trial 2833 finished with value: 0.4037446624439208 and parameters: {'alpha': 1.005664678852947e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,966] Trial 2834 finished with value: 0.4037444426633992 and parameters: {'alpha': 1.0155238881951242e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:48,998] Trial 2835 finished with value: 0.4037450897625189 and parameters: {'alpha': 2.8137260276110823e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,030] Trial 2836 finished with value: 0.40374463976764474 and parameters: {'alpha': 1.0099829975990145e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  57%|█████▋    | 2844/5000 [01:16<01:07, 31.81it/s]

[I 2026-06-14 00:49:49,062] Trial 2837 finished with value: 0.4037444672251256 and parameters: {'alpha': 1.0003467644650791e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,094] Trial 2838 finished with value: 0.40374509541265696 and parameters: {'alpha': 2.703768068311303e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,126] Trial 2839 finished with value: 0.4037449580859638 and parameters: {'alpha': 1.7113487859607402e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,157] Trial 2840 finished with value: 0.4037452434025458 and parameters: {'alpha': 4.9043213739368094e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,188] Trial 2841 finished with value: 0.4037449937576503 and parameters: {'alpha': 1.747567438050603e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,219] Trial 2842 finished with value: 0.40374502974545623 and parameters: {'alpha': 2.7342421454282374e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,249] Trial 2843 finished with value: 0.40374527480437694 and parameters: {'alpha': 6.186076544247444e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  57%|█████▋    | 2850/5000 [01:16<01:07, 31.92it/s]

[I 2026-06-14 00:49:49,281] Trial 2844 finished with value: 0.4037442735418428 and parameters: {'alpha': 1.0152176641057337e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,313] Trial 2845 finished with value: 0.4037450012786592 and parameters: {'alpha': 1.8287253270009624e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,344] Trial 2846 finished with value: 0.40374506475964433 and parameters: {'alpha': 2.670357352649203e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,374] Trial 2847 finished with value: 0.4037453306836836 and parameters: {'alpha': 1.0606648723606713e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,406] Trial 2848 finished with value: 0.4037447178589736 and parameters: {'alpha': 1.6862187435369207e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,438] Trial 2849 finished with value: 0.4037444070118661 and parameters: {'alpha': 1.0117742919522744e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,469] Trial 2850 finished with value: 0.40374522985592554 and parameters: {'alpha': 3.0831863219517846e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  57%|█████▋    | 2857/5000 [01:17<01:07, 31.86it/s]

[I 2026-06-14 00:49:49,501] Trial 2851 finished with value: 0.4037449461354528 and parameters: {'alpha': 1.704216820804224e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,534] Trial 2852 finished with value: 0.4037452532276994 and parameters: {'alpha': 4.28269785879552e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,565] Trial 2853 finished with value: 0.4037448455635009 and parameters: {'alpha': 1.6921145451152134e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,595] Trial 2854 finished with value: 0.40374497023741845 and parameters: {'alpha': 1.739472594311715e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,627] Trial 2855 finished with value: 0.4037445521707993 and parameters: {'alpha': 1.0027517713938338e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,658] Trial 2856 finished with value: 0.4037451860587214 and parameters: {'alpha': 3.9697139581338256e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,689] Trial 2857 finished with value: 0.40374500196349056 and parameters: {'alpha': 2.900826631526644e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  57%|█████▋    | 2864/5000 [01:17<01:07, 31.50it/s]

[I 2026-06-14 00:49:49,720] Trial 2858 finished with value: 0.40374427106208766 and parameters: {'alpha': 1.0068937529494717e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,751] Trial 2859 finished with value: 0.4037453090103636 and parameters: {'alpha': 8.485795737815053e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,788] Trial 2860 finished with value: 0.4037449479951251 and parameters: {'alpha': 1.7166950034401182e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,820] Trial 2861 finished with value: 0.4037442964107916 and parameters: {'alpha': 1.0036148318068274e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,852] Trial 2862 finished with value: 0.40374507857600533 and parameters: {'alpha': 2.6605665368023923e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,883] Trial 2863 finished with value: 0.4037446117549409 and parameters: {'alpha': 1.0040393693221658e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,915] Trial 2864 finished with value: 0.4037453113625636 and parameters: {'alpha': 5.8994478833891614e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  57%|█████▋    | 2872/5000 [01:17<01:07, 31.63it/s]

[I 2026-06-14 00:49:49,947] Trial 2865 finished with value: 0.40375876698721586 and parameters: {'alpha': 7.89361074762914}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:49,979] Trial 2866 finished with value: 0.40374502658958067 and parameters: {'alpha': 2.595945280900143e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,010] Trial 2867 finished with value: 0.4037448406154362 and parameters: {'alpha': 1.6957690325662386e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,042] Trial 2868 finished with value: 0.40374480302182647 and parameters: {'alpha': 1.7143264334993035e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,073] Trial 2869 finished with value: 0.40374523379621247 and parameters: {'alpha': 4.221429827713755e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,104] Trial 2870 finished with value: 0.40374500306763245 and parameters: {'alpha': 2.6369929375531377e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,135] Trial 2871 finished with value: 0.4037444534186621 and parameters: {'alpha': 1.008794494668304e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  58%|█████▊    | 2878/5000 [01:17<01:07, 31.37it/s]

[I 2026-06-14 00:49:50,169] Trial 2872 finished with value: 0.40374480388784156 and parameters: {'alpha': 1.6259030298864326e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,202] Trial 2873 finished with value: 0.40374537220136597 and parameters: {'alpha': 2.606301453036654e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,234] Trial 2874 finished with value: 0.40374487286229904 and parameters: {'alpha': 1.7337450892924768e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,265] Trial 2875 finished with value: 0.40374523908676485 and parameters: {'alpha': 6.575629290491073e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,297] Trial 2876 finished with value: 0.4037450810295732 and parameters: {'alpha': 2.8338535507623583e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,328] Trial 2877 finished with value: 0.40374474537188343 and parameters: {'alpha': 1.6689139060251074e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,359] Trial 2878 finished with value: 0.40374450833018294 and parameters: {'alpha': 1.015498261698021e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  58%|█████▊    | 2885/5000 [01:17<01:06, 31.59it/s]

[I 2026-06-14 00:49:50,390] Trial 2879 finished with value: 0.4037452774585533 and parameters: {'alpha': 4.180797733873567e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,423] Trial 2880 finished with value: 0.40374501836556337 and parameters: {'alpha': 2.8822858557996656e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,454] Trial 2881 finished with value: 0.4037447902460098 and parameters: {'alpha': 1.605428944024768e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,485] Trial 2882 finished with value: 0.4037450323254824 and parameters: {'alpha': 2.6645516972206683e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,516] Trial 2883 finished with value: 0.4037449029799801 and parameters: {'alpha': 1.7987223545435854e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,548] Trial 2884 finished with value: 0.4037443151580352 and parameters: {'alpha': 1.007392812653029e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,581] Trial 2885 finished with value: 0.4037452689563237 and parameters: {'alpha': 4.5885155080788504e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  58%|█████▊    | 2892/5000 [01:18<01:06, 31.65it/s]

[I 2026-06-14 00:49:50,612] Trial 2886 finished with value: 0.4037448814423868 and parameters: {'alpha': 1.7031255866851153e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,644] Trial 2887 finished with value: 0.4037449153534573 and parameters: {'alpha': 1.7036831115445e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,676] Trial 2888 finished with value: 0.40374465983146895 and parameters: {'alpha': 1.0094050104465523e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,707] Trial 2889 finished with value: 0.40374505846168557 and parameters: {'alpha': 2.921023226716632e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,738] Trial 2890 finished with value: 0.40374531338421393 and parameters: {'alpha': 9.53391750105809e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,769] Trial 2891 finished with value: 0.4037452874608217 and parameters: {'alpha': 4.6663271137457965e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,803] Trial 2892 finished with value: 0.4037449501760587 and parameters: {'alpha': 1.782923082826237e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  58%|█████▊    | 2900/5000 [01:18<01:06, 31.42it/s]

[I 2026-06-14 00:49:50,835] Trial 2893 finished with value: 0.4037450121384902 and parameters: {'alpha': 2.597253117056683e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,868] Trial 2894 finished with value: 0.40374481090299535 and parameters: {'alpha': 1.7219589174446005e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,899] Trial 2895 finished with value: 0.4037448381826372 and parameters: {'alpha': 1.695605679359958e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,932] Trial 2896 finished with value: 0.4037452347427808 and parameters: {'alpha': 3.976312888318501e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,963] Trial 2897 finished with value: 0.4037444878217289 and parameters: {'alpha': 1.0041366197657616e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:50,995] Trial 2898 finished with value: 0.4037450766441415 and parameters: {'alpha': 2.733362306639852e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,026] Trial 2899 finished with value: 0.4037452506571787 and parameters: {'alpha': 6.410974363465328e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  58%|█████▊    | 2906/5000 [01:18<01:06, 31.70it/s]

[I 2026-06-14 00:49:51,058] Trial 2900 finished with value: 0.40374486382956803 and parameters: {'alpha': 1.751231775493921e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,090] Trial 2901 finished with value: 0.40374445781181095 and parameters: {'alpha': 1.0201552696008153e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,120] Trial 2902 finished with value: 0.4037451138815218 and parameters: {'alpha': 2.881606887304226e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,150] Trial 2903 finished with value: 0.4037449134234236 and parameters: {'alpha': 1.703454790623746e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,183] Trial 2904 finished with value: 0.4037447948552403 and parameters: {'alpha': 1.7198574072950984e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,215] Trial 2905 finished with value: 0.4037451839611478 and parameters: {'alpha': 3.999104116523845e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,247] Trial 2906 finished with value: 0.40374446188757107 and parameters: {'alpha': 1.0122838690465667e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  58%|█████▊    | 2913/5000 [01:18<01:05, 31.62it/s]

[I 2026-06-14 00:49:51,279] Trial 2907 finished with value: 0.4037443346436219 and parameters: {'alpha': 1.0169007311384471e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,311] Trial 2908 finished with value: 0.4037453362997423 and parameters: {'alpha': 1.1063012961473657e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,343] Trial 2909 finished with value: 0.4037444105343914 and parameters: {'alpha': 1.0038137768265371e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,374] Trial 2910 finished with value: 0.40374452182125353 and parameters: {'alpha': 1.0067249114188111e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,405] Trial 2911 finished with value: 0.4037450992521987 and parameters: {'alpha': 2.9612882563168646e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,437] Trial 2912 finished with value: 0.40374529113006336 and parameters: {'alpha': 5.863802074886003e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,468] Trial 2913 finished with value: 0.40374505635036995 and parameters: {'alpha': 2.6941613588453545e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  58%|█████▊    | 2920/5000 [01:19<01:05, 31.76it/s]

[I 2026-06-14 00:49:51,501] Trial 2914 finished with value: 0.40374495901894414 and parameters: {'alpha': 1.7574987737219274e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,532] Trial 2915 finished with value: 0.40374488243816653 and parameters: {'alpha': 1.748480893863543e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,563] Trial 2916 finished with value: 0.4037452818764595 and parameters: {'alpha': 4.3887354496128196e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,593] Trial 2917 finished with value: 0.4037450261500025 and parameters: {'alpha': 2.6677832609393075e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,624] Trial 2918 finished with value: 0.4037445111052925 and parameters: {'alpha': 1.0105068984148593e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,655] Trial 2919 finished with value: 0.4037447154511507 and parameters: {'alpha': 1.0067012896306901e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,687] Trial 2920 finished with value: 0.40374476951205324 and parameters: {'alpha': 1.7234644381106676e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  58%|█████▊    | 2925/5000 [01:19<01:11, 29.10it/s]

[I 2026-06-14 00:49:51,719] Trial 2921 finished with value: 0.4037443055758629 and parameters: {'alpha': 1.0157615561574414e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,759] Trial 2922 finished with value: 0.4037449893128982 and parameters: {'alpha': 2.5450183800080602e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,818] Trial 2923 finished with value: 0.4037452386493345 and parameters: {'alpha': 4.472361912564945e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,859] Trial 2924 finished with value: 0.40374479094229415 and parameters: {'alpha': 1.6719614640313994e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,898] Trial 2925 finished with value: 0.40374437273865577 and parameters: {'alpha': 1.0123238481505243e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  59%|█████▊    | 2932/5000 [01:19<01:10, 29.47it/s]

[I 2026-06-14 00:49:51,930] Trial 2926 finished with value: 0.40374509505143524 and parameters: {'alpha': 2.96687158755757e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,963] Trial 2927 finished with value: 0.40374437509067856 and parameters: {'alpha': 1.0050226016099231e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:51,994] Trial 2928 finished with value: 0.43304001940758013 and parameters: {'alpha': 3456.4448122150616}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,025] Trial 2929 finished with value: 0.40374444207867366 and parameters: {'alpha': 1.0104786830232204e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,057] Trial 2930 finished with value: 0.40374444523172476 and parameters: {'alpha': 1.0021650311810116e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,090] Trial 2931 finished with value: 0.4037453290096137 and parameters: {'alpha': 8.596571702753264e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,121] Trial 2932 finished with value: 0.4037449606402444 and parameters: {'alpha': 2.5326716662159163e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  59%|█████▉    | 2939/5000 [01:19<01:07, 30.52it/s]

[I 2026-06-14 00:49:52,152] Trial 2933 finished with value: 0.40374530774625217 and parameters: {'alpha': 5.571277923057827e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,185] Trial 2934 finished with value: 0.4037449518979303 and parameters: {'alpha': 1.7746976979943162e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,217] Trial 2935 finished with value: 0.40374541425919 and parameters: {'alpha': 0.011578094236097866}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,249] Trial 2936 finished with value: 0.4037449925120571 and parameters: {'alpha': 2.6055165051064867e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,280] Trial 2937 finished with value: 0.4037449884620772 and parameters: {'alpha': 1.8288421420458003e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,311] Trial 2938 finished with value: 0.4037452321273803 and parameters: {'alpha': 4.406076498628416e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,343] Trial 2939 finished with value: 0.4037447536762383 and parameters: {'alpha': 1.7162923331337757e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  59%|█████▉    | 2947/5000 [01:19<01:05, 31.16it/s]

[I 2026-06-14 00:49:52,375] Trial 2940 finished with value: 0.4037447506817387 and parameters: {'alpha': 1.001615979649694e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,406] Trial 2941 finished with value: 0.4037451385333331 and parameters: {'alpha': 3.311418890708238e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,437] Trial 2942 finished with value: 0.4037448252412151 and parameters: {'alpha': 1.7550494714594e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,469] Trial 2943 finished with value: 0.4037453413701219 and parameters: {'alpha': 1.342555472061097e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,500] Trial 2944 finished with value: 0.40374432048396147 and parameters: {'alpha': 1.0088456363274607e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,531] Trial 2945 finished with value: 0.40374505314658005 and parameters: {'alpha': 2.70397796554108e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,563] Trial 2946 finished with value: 0.4037444533911892 and parameters: {'alpha': 1.0064556290025714e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  59%|█████▉    | 2953/5000 [01:20<01:05, 31.11it/s]

[I 2026-06-14 00:49:52,596] Trial 2947 finished with value: 0.40374528837158485 and parameters: {'alpha': 7.279283037146175e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,629] Trial 2948 finished with value: 0.40374488302577194 and parameters: {'alpha': 1.703640364592374e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,659] Trial 2949 finished with value: 0.40374521154305976 and parameters: {'alpha': 4.1909526896234885e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,690] Trial 2950 finished with value: 0.4037448555927352 and parameters: {'alpha': 1.7209563860248848e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,724] Trial 2951 finished with value: 0.4037449798145283 and parameters: {'alpha': 2.3894543149655614e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,756] Trial 2952 finished with value: 0.4037450550748862 and parameters: {'alpha': 2.7498422470274944e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,786] Trial 2953 finished with value: 0.40374523909193555 and parameters: {'alpha': 4.3534841458347783e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  59%|█████▉    | 2960/5000 [01:20<01:05, 30.92it/s]

[I 2026-06-14 00:49:52,822] Trial 2954 finished with value: 0.4037447299840532 and parameters: {'alpha': 1.7769676772290355e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,856] Trial 2955 finished with value: 0.4037446237193919 and parameters: {'alpha': 1.0106413772944101e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,889] Trial 2956 finished with value: 0.403744874896507 and parameters: {'alpha': 1.730968692435434e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,920] Trial 2957 finished with value: 0.4037450044460619 and parameters: {'alpha': 2.733916026143024e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,952] Trial 2958 finished with value: 0.4037446460843314 and parameters: {'alpha': 1.0012580463155842e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:52,985] Trial 2959 finished with value: 0.4037453022553908 and parameters: {'alpha': 6.890667371696777e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,017] Trial 2960 finished with value: 0.4037449600821854 and parameters: {'alpha': 1.6981608451344305e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  59%|█████▉    | 2967/5000 [01:20<01:05, 30.99it/s]

[I 2026-06-14 00:49:53,049] Trial 2961 finished with value: 0.40374529325201014 and parameters: {'alpha': 4.108405730208612e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,081] Trial 2962 finished with value: 0.4037449614505253 and parameters: {'alpha': 1.7199854012079436e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,115] Trial 2963 finished with value: 0.4037443412224553 and parameters: {'alpha': 1.0003989136921665e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,147] Trial 2964 finished with value: 0.40374462183033977 and parameters: {'alpha': 1.0097341559263175e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,178] Trial 2965 finished with value: 0.4037447021330916 and parameters: {'alpha': 1.0039691476755442e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,210] Trial 2966 finished with value: 0.403745038210531 and parameters: {'alpha': 2.6907822034347386e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,242] Trial 2967 finished with value: 0.40374536423695173 and parameters: {'alpha': 2.0157202083330455e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  60%|█████▉    | 2975/5000 [01:20<01:05, 31.14it/s]

[I 2026-06-14 00:49:53,275] Trial 2968 finished with value: 0.4037450841656084 and parameters: {'alpha': 2.685945384901605e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,307] Trial 2969 finished with value: 0.4037448920083697 and parameters: {'alpha': 1.704838254052583e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,339] Trial 2970 finished with value: 0.4037454281100085 and parameters: {'alpha': 0.03211842081954177}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,372] Trial 2971 finished with value: 0.4037452803219102 and parameters: {'alpha': 6.905003518446175e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,403] Trial 2972 finished with value: 0.40374516728937915 and parameters: {'alpha': 4.154035010551313e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,434] Trial 2973 finished with value: 0.40374488616842014 and parameters: {'alpha': 1.8048065662014573e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,466] Trial 2974 finished with value: 0.40374462993176524 and parameters: {'alpha': 1.0037793945401132e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  60%|█████▉    | 2981/5000 [01:21<01:04, 31.21it/s]

[I 2026-06-14 00:49:53,499] Trial 2975 finished with value: 0.4037450506435173 and parameters: {'alpha': 2.6640800061423884e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,531] Trial 2976 finished with value: 0.4037448129627377 and parameters: {'alpha': 1.7866895094102373e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,562] Trial 2977 finished with value: 0.40374477142140774 and parameters: {'alpha': 1.734224264872714e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,593] Trial 2978 finished with value: 0.40374521936432567 and parameters: {'alpha': 4.271890857126994e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,624] Trial 2979 finished with value: 0.40374464021230355 and parameters: {'alpha': 1.0000180800529726e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,656] Trial 2980 finished with value: 0.4037450937489557 and parameters: {'alpha': 2.8144602742987354e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,687] Trial 2981 finished with value: 0.4037449149155532 and parameters: {'alpha': 1.8083945561466937e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  60%|█████▉    | 2988/5000 [01:21<01:04, 31.03it/s]

[I 2026-06-14 00:49:53,719] Trial 2982 finished with value: 0.40374530568366396 and parameters: {'alpha': 7.809107388403777e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,753] Trial 2983 finished with value: 0.403744860049194 and parameters: {'alpha': 1.696704622065136e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,786] Trial 2984 finished with value: 0.403745238170191 and parameters: {'alpha': 3.861856738112586e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,817] Trial 2985 finished with value: 0.4037448608190793 and parameters: {'alpha': 1.7441270470023834e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,851] Trial 2986 finished with value: 0.4037454057238233 and parameters: {'alpha': 1.1196111053509444e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,885] Trial 2987 finished with value: 0.40374509328843095 and parameters: {'alpha': 2.681986667185848e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,917] Trial 2988 finished with value: 0.40374428750367497 and parameters: {'alpha': 1.0174041121815663e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  60%|█████▉    | 2995/5000 [01:21<01:04, 31.14it/s]

[I 2026-06-14 00:49:53,949] Trial 2989 finished with value: 0.4037448919929419 and parameters: {'alpha': 1.7326471342709233e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:53,982] Trial 2990 finished with value: 0.4037446522791194 and parameters: {'alpha': 1.008206131874556e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,014] Trial 2991 finished with value: 0.40374525428401764 and parameters: {'alpha': 4.540680406611682e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,046] Trial 2992 finished with value: 0.4037450293194017 and parameters: {'alpha': 2.805886454038785e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,077] Trial 2993 finished with value: 0.40374505088802476 and parameters: {'alpha': 2.8051932264929933e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,109] Trial 2994 finished with value: 0.403744952518267 and parameters: {'alpha': 1.6871090729577855e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,143] Trial 2995 finished with value: 0.40374483939393097 and parameters: {'alpha': 1.7127751603384115e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  60%|██████    | 3003/5000 [01:21<01:04, 30.84it/s]

[I 2026-06-14 00:49:54,176] Trial 2996 finished with value: 0.40374527785070913 and parameters: {'alpha': 5.064220783844818e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,207] Trial 2997 finished with value: 0.40374532676786234 and parameters: {'alpha': 1.1109281370586081e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,240] Trial 2998 finished with value: 0.4037450050311486 and parameters: {'alpha': 2.496473536630504e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,274] Trial 2999 finished with value: 0.4037448851153052 and parameters: {'alpha': 1.725920180506357e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,305] Trial 3000 finished with value: 0.4037449684804144 and parameters: {'alpha': 1.6786153069988094e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,337] Trial 3001 finished with value: 0.4037452505634358 and parameters: {'alpha': 3.8086974556234156e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,370] Trial 3002 finished with value: 0.40374489455099677 and parameters: {'alpha': 1.7569169823670056e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  60%|██████    | 3008/5000 [01:21<01:05, 30.57it/s]

[I 2026-06-14 00:49:54,405] Trial 3003 finished with value: 0.4037446490922726 and parameters: {'alpha': 1.01722682420766e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,437] Trial 3004 finished with value: 0.40374471099615467 and parameters: {'alpha': 1.0182896144437943e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,471] Trial 3005 finished with value: 0.40374525896845753 and parameters: {'alpha': 6.961433542599968e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,503] Trial 3006 finished with value: 0.40374498206851667 and parameters: {'alpha': 2.7046669304703034e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,539] Trial 3007 finished with value: 0.40374489630273236 and parameters: {'alpha': 1.7871392071100823e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,576] Trial 3008 finished with value: 0.40374520561258775 and parameters: {'alpha': 3.850803256928464e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  60%|██████    | 3014/5000 [01:22<01:08, 28.92it/s]

[I 2026-06-14 00:49:54,612] Trial 3009 finished with value: 0.40374430779351406 and parameters: {'alpha': 1.0190702037670183e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,649] Trial 3010 finished with value: 0.4037448263808291 and parameters: {'alpha': 1.785484144137323e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,685] Trial 3011 finished with value: 0.403745032144917 and parameters: {'alpha': 2.799365621800534e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,722] Trial 3012 finished with value: 0.4037452849035787 and parameters: {'alpha': 6.24830159421503e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,760] Trial 3013 finished with value: 0.4037444407762242 and parameters: {'alpha': 1.0054250205028154e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,795] Trial 3014 finished with value: 0.40374446450140594 and parameters: {'alpha': 1.0102408842448273e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  60%|██████    | 3020/5000 [01:22<01:09, 28.51it/s]

[I 2026-06-14 00:49:54,828] Trial 3015 finished with value: 0.40374480472458585 and parameters: {'alpha': 1.7744275877948404e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,866] Trial 3016 finished with value: 0.4037442501761458 and parameters: {'alpha': 1.0056723728300573e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,903] Trial 3017 finished with value: 0.40374526146773937 and parameters: {'alpha': 3.890979266226576e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,940] Trial 3018 finished with value: 0.4037449962333152 and parameters: {'alpha': 2.4931731854065883e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:54,974] Trial 3019 finished with value: 0.40374495023115153 and parameters: {'alpha': 1.7042664089476935e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,009] Trial 3020 finished with value: 0.40374481875675666 and parameters: {'alpha': 1.7237962065766176e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  61%|██████    | 3026/5000 [01:22<01:10, 28.19it/s]

[I 2026-06-14 00:49:55,046] Trial 3021 finished with value: 0.40374434502092843 and parameters: {'alpha': 1.0172614345771684e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,083] Trial 3022 finished with value: 0.40374526856414644 and parameters: {'alpha': 4.160047494258733e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,119] Trial 3023 finished with value: 0.40374455878089094 and parameters: {'alpha': 1.0090055746581191e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,153] Trial 3024 finished with value: 0.40374457150923626 and parameters: {'alpha': 1.005814443402479e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,189] Trial 3025 finished with value: 0.48006150811773624 and parameters: {'alpha': 9213.026970617399}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,228] Trial 3026 finished with value: 0.40374507255567266 and parameters: {'alpha': 2.649808252359737e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  61%|██████    | 3032/5000 [01:22<01:10, 27.86it/s]

[I 2026-06-14 00:49:55,265] Trial 3027 finished with value: 0.40374430517476634 and parameters: {'alpha': 1.009099717165585e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,302] Trial 3028 finished with value: 0.4037453172009663 and parameters: {'alpha': 1.0214772041727092e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,339] Trial 3029 finished with value: 0.40374507710975843 and parameters: {'alpha': 2.5968283634332746e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,373] Trial 3030 finished with value: 0.40374529346006627 and parameters: {'alpha': 5.2976444402160126e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,408] Trial 3031 finished with value: 0.4037448917536045 and parameters: {'alpha': 1.7098439215585154e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,444] Trial 3032 finished with value: 0.4037450738909025 and parameters: {'alpha': 2.7051379857687067e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  61%|██████    | 3038/5000 [01:23<01:09, 28.22it/s]

[I 2026-06-14 00:49:55,479] Trial 3033 finished with value: 0.40374477269498477 and parameters: {'alpha': 1.7622606289930443e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,515] Trial 3034 finished with value: 0.4037451486571048 and parameters: {'alpha': 3.6777309619722036e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,551] Trial 3035 finished with value: 0.40374524522853017 and parameters: {'alpha': 7.094805791201818e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,586] Trial 3036 finished with value: 0.4037447544152827 and parameters: {'alpha': 1.782289724892217e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,619] Trial 3037 finished with value: 0.40374492435629267 and parameters: {'alpha': 1.66705892910978e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,656] Trial 3038 finished with value: 0.40374509763372685 and parameters: {'alpha': 2.9238069901816384e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  61%|██████    | 3045/5000 [01:23<01:08, 28.38it/s]

[I 2026-06-14 00:49:55,692] Trial 3039 finished with value: 0.40374427508833516 and parameters: {'alpha': 1.0026849638432018e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,730] Trial 3040 finished with value: 0.4037446222493611 and parameters: {'alpha': 1.014696339100736e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,763] Trial 3041 finished with value: 0.4037444663604964 and parameters: {'alpha': 1.0110447507301938e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,797] Trial 3042 finished with value: 0.40374534818811997 and parameters: {'alpha': 1.6742942347851102e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,829] Trial 3043 finished with value: 0.4037450469511604 and parameters: {'alpha': 2.658328193763833e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,866] Trial 3044 finished with value: 0.40374530220672616 and parameters: {'alpha': 4.2395363771650406e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  61%|██████    | 3051/5000 [01:23<01:10, 27.72it/s]

[I 2026-06-14 00:49:55,908] Trial 3045 finished with value: 0.4037448793096455 and parameters: {'alpha': 1.630761931880922e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,942] Trial 3046 finished with value: 0.40374454852344255 and parameters: {'alpha': 1.0006392950222764e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:55,977] Trial 3047 finished with value: 0.4037444955209674 and parameters: {'alpha': 1.0008836865545452e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,014] Trial 3048 finished with value: 0.4037451542130061 and parameters: {'alpha': 3.044441139871379e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,051] Trial 3049 finished with value: 0.4037452904303871 and parameters: {'alpha': 6.378835051029275e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,088] Trial 3050 finished with value: 0.4037449509095045 and parameters: {'alpha': 2.6209184820643188e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  61%|██████    | 3057/5000 [01:23<01:09, 27.83it/s]

[I 2026-06-14 00:49:56,127] Trial 3051 finished with value: 0.403745406322148 and parameters: {'alpha': 3.5590385099828995e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,162] Trial 3052 finished with value: 0.40374487341792614 and parameters: {'alpha': 1.7485072265928062e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,197] Trial 3053 finished with value: 0.4037447672861825 and parameters: {'alpha': 1.700589725975121e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,233] Trial 3054 finished with value: 0.40374529617426613 and parameters: {'alpha': 4.356427446980831e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,269] Trial 3055 finished with value: 0.40374498308212386 and parameters: {'alpha': 1.7045248698650756e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,304] Trial 3056 finished with value: 0.4037448014896126 and parameters: {'alpha': 1.7343600724996574e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  61%|██████▏   | 3063/5000 [01:23<01:08, 28.09it/s]

[I 2026-06-14 00:49:56,338] Trial 3057 finished with value: 0.4037450101859883 and parameters: {'alpha': 2.6355325208442554e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,372] Trial 3058 finished with value: 0.40374474280922457 and parameters: {'alpha': 1.6786105837110154e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,407] Trial 3059 finished with value: 0.40374524499403536 and parameters: {'alpha': 4.059633420393344e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,442] Trial 3060 finished with value: 0.403744862469403 and parameters: {'alpha': 1.725252422972295e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,473] Trial 3061 finished with value: 0.4037452842299258 and parameters: {'alpha': 7.394389251513667e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,505] Trial 3062 finished with value: 0.4037450293175762 and parameters: {'alpha': 2.8419048252754827e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,537] Trial 3063 finished with value: 0.4037445071860443 and parameters: {'alpha': 1.0183957934618536e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  61%|██████▏   | 3071/5000 [01:24<01:04, 29.87it/s]

[I 2026-06-14 00:49:56,570] Trial 3064 finished with value: 0.4037449675118679 and parameters: {'alpha': 1.7065679437146057e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,606] Trial 3065 finished with value: 0.4037452895344415 and parameters: {'alpha': 4.1529204695762974e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,638] Trial 3066 finished with value: 0.40374497922178976 and parameters: {'alpha': 2.542278795749232e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,670] Trial 3067 finished with value: 0.40374449979811255 and parameters: {'alpha': 1.0084881230845217e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,702] Trial 3068 finished with value: 0.4037448520458734 and parameters: {'alpha': 1.8782288488428517e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,734] Trial 3069 finished with value: 0.40374477960612837 and parameters: {'alpha': 1.717768818117685e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,767] Trial 3070 finished with value: 0.4037443831899152 and parameters: {'alpha': 1.0016169076164347e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  62%|██████▏   | 3077/5000 [01:24<01:04, 29.93it/s]

[I 2026-06-14 00:49:56,800] Trial 3071 finished with value: 0.4037447045637506 and parameters: {'alpha': 1.01145409891982e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,833] Trial 3072 finished with value: 0.4037452509978586 and parameters: {'alpha': 5.987115256653011e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,864] Trial 3073 finished with value: 0.4037450018657997 and parameters: {'alpha': 2.8531638422087354e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,899] Trial 3074 finished with value: 0.4037442957539396 and parameters: {'alpha': 1.0095840045540083e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,933] Trial 3075 finished with value: 0.4037450042652747 and parameters: {'alpha': 2.75844538230351e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,965] Trial 3076 finished with value: 0.4037453496273934 and parameters: {'alpha': 1.308841418679412e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:56,998] Trial 3077 finished with value: 0.4037448908659778 and parameters: {'alpha': 1.7068782508435244e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  62%|██████▏   | 3084/5000 [01:24<01:02, 30.44it/s]

[I 2026-06-14 00:49:57,030] Trial 3078 finished with value: 0.4037451926895934 and parameters: {'alpha': 3.6749259055586094e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,064] Trial 3079 finished with value: 0.40374480227077514 and parameters: {'alpha': 1.7694876066879436e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,095] Trial 3080 finished with value: 0.40374525526571337 and parameters: {'alpha': 6.092328251080853e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,127] Trial 3081 finished with value: 0.40374503372509213 and parameters: {'alpha': 2.821571101133272e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,159] Trial 3082 finished with value: 0.40374495649442976 and parameters: {'alpha': 1.7671190134985818e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,192] Trial 3083 finished with value: 0.40374485009084393 and parameters: {'alpha': 1.7783887195876438e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,223] Trial 3084 finished with value: 0.4037452172394643 and parameters: {'alpha': 4.24180302890606e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  62%|██████▏   | 3091/5000 [01:24<01:02, 30.72it/s]

[I 2026-06-14 00:49:57,256] Trial 3085 finished with value: 0.4037449313002916 and parameters: {'alpha': 1.734338681326688e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,288] Trial 3086 finished with value: 0.403744299632581 and parameters: {'alpha': 1.0051930573144179e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,321] Trial 3087 finished with value: 0.40374434880918997 and parameters: {'alpha': 1.014830143859579e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,353] Trial 3088 finished with value: 0.4037450812387075 and parameters: {'alpha': 2.7695459225086474e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,385] Trial 3089 finished with value: 0.4037449651745985 and parameters: {'alpha': 1.709176318228227e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,418] Trial 3090 finished with value: 0.40374529009718774 and parameters: {'alpha': 4.832672477362288e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,451] Trial 3091 finished with value: 0.4037452697852565 and parameters: {'alpha': 8.502859976865425e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  62%|██████▏   | 3099/5000 [01:25<01:01, 30.75it/s]

[I 2026-06-14 00:49:57,483] Trial 3092 finished with value: 0.40374473698506497 and parameters: {'alpha': 1.742643069915208e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,516] Trial 3093 finished with value: 0.40374503039340665 and parameters: {'alpha': 2.9562436612608288e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,549] Trial 3094 finished with value: 0.4037448795692824 and parameters: {'alpha': 1.718230939878277e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,582] Trial 3095 finished with value: 0.40374475411203853 and parameters: {'alpha': 1.0211106010270657e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,615] Trial 3096 finished with value: 0.40380127178418507 and parameters: {'alpha': 21.841321549789253}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,646] Trial 3097 finished with value: 0.4037451426596944 and parameters: {'alpha': 2.989793632389784e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,678] Trial 3098 finished with value: 0.4037447111128087 and parameters: {'alpha': 1.0037720990818086e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  62%|██████▏   | 3105/5000 [01:25<01:01, 30.69it/s]

[I 2026-06-14 00:49:57,712] Trial 3099 finished with value: 0.40374483183429394 and parameters: {'alpha': 1.8087620386795396e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,745] Trial 3100 finished with value: 0.40374523943508905 and parameters: {'alpha': 4.486853775006009e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,777] Trial 3101 finished with value: 0.4037447653919442 and parameters: {'alpha': 1.0154636502761737e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,809] Trial 3102 finished with value: 0.40374498818647603 and parameters: {'alpha': 2.707627209953181e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,843] Trial 3103 finished with value: 0.40374477528863306 and parameters: {'alpha': 1.7628630476419336e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,875] Trial 3104 finished with value: 0.40374492109021054 and parameters: {'alpha': 1.6814138063830962e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,910] Trial 3105 finished with value: 0.4037452913179427 and parameters: {'alpha': 6.510717450818881e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  62%|██████▏   | 3112/5000 [01:25<01:01, 30.59it/s]

[I 2026-06-14 00:49:57,944] Trial 3106 finished with value: 0.4037450942257958 and parameters: {'alpha': 2.8810072719702168e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:57,976] Trial 3107 finished with value: 0.4037448801189984 and parameters: {'alpha': 1.7371884917356843e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,008] Trial 3108 finished with value: 0.40374517900009693 and parameters: {'alpha': 4.123717840663143e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,040] Trial 3109 finished with value: 0.40374473930950716 and parameters: {'alpha': 1.6596062736396626e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,072] Trial 3110 finished with value: 0.403744401596571 and parameters: {'alpha': 1.0156648023208102e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,105] Trial 3111 finished with value: 0.4037446609696272 and parameters: {'alpha': 1.003885415146786e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,136] Trial 3112 finished with value: 0.40374532457690526 and parameters: {'alpha': 1.249303507970478e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  62%|██████▏   | 3119/5000 [01:25<01:01, 30.61it/s]

[I 2026-06-14 00:49:58,170] Trial 3113 finished with value: 0.4037450965238017 and parameters: {'alpha': 2.7435510264266965e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,203] Trial 3114 finished with value: 0.403744944026263 and parameters: {'alpha': 1.6987655445514514e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,237] Trial 3115 finished with value: 0.4037443375202075 and parameters: {'alpha': 1.0022038173920743e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,270] Trial 3116 finished with value: 0.40374457850523426 and parameters: {'alpha': 1.0141469505146376e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,303] Trial 3117 finished with value: 0.40374523674166746 and parameters: {'alpha': 4.051386233059775e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,334] Trial 3118 finished with value: 0.40374500361448007 and parameters: {'alpha': 2.6844608211694217e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,367] Trial 3119 finished with value: 0.4037452985924769 and parameters: {'alpha': 6.691297647382408e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  63%|██████▎   | 3127/5000 [01:25<01:01, 30.53it/s]

[I 2026-06-14 00:49:58,400] Trial 3120 finished with value: 0.4037449036550537 and parameters: {'alpha': 1.7995899154242118e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,433] Trial 3121 finished with value: 0.4037447102383551 and parameters: {'alpha': 1.0150306329265167e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,465] Trial 3122 finished with value: 0.4037451889071873 and parameters: {'alpha': 2.987078668759572e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,498] Trial 3123 finished with value: 0.40374476927975866 and parameters: {'alpha': 1.7338398871207136e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,531] Trial 3124 finished with value: 0.40374502758880293 and parameters: {'alpha': 2.7431930739119555e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,564] Trial 3125 finished with value: 0.40374484489855117 and parameters: {'alpha': 1.7678222248475106e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,596] Trial 3126 finished with value: 0.40374525000922495 and parameters: {'alpha': 4.6380666757231894e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  63%|██████▎   | 3133/5000 [01:26<01:01, 30.60it/s]

[I 2026-06-14 00:49:58,630] Trial 3127 finished with value: 0.40374475802694826 and parameters: {'alpha': 1.7744085328629153e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,662] Trial 3128 finished with value: 0.40374442921159015 and parameters: {'alpha': 1.0089794232696635e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,695] Trial 3129 finished with value: 0.4037453004918942 and parameters: {'alpha': 9.629889116129086e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,727] Trial 3130 finished with value: 0.4037442887368569 and parameters: {'alpha': 1.0011524453099082e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,760] Trial 3131 finished with value: 0.4037449673663814 and parameters: {'alpha': 2.584998527051668e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,792] Trial 3132 finished with value: 0.4037452566722326 and parameters: {'alpha': 4.398033702359196e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,824] Trial 3133 finished with value: 0.412162151346643 and parameters: {'alpha': 1408.965686910978}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  63%|██████▎   | 3140/5000 [01:26<01:00, 30.52it/s]

[I 2026-06-14 00:49:58,857] Trial 3134 finished with value: 0.4037450004641194 and parameters: {'alpha': 2.6327365726610887e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,891] Trial 3135 finished with value: 0.40374468810777275 and parameters: {'alpha': 1.0050904120849423e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,924] Trial 3136 finished with value: 0.40374482185321026 and parameters: {'alpha': 1.6975464574286615e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,957] Trial 3137 finished with value: 0.4037447469783314 and parameters: {'alpha': 1.7044373499500024e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:58,989] Trial 3138 finished with value: 0.4037442685838086 and parameters: {'alpha': 1.0072648092523901e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,021] Trial 3139 finished with value: 0.4037443067805645 and parameters: {'alpha': 1.0015731542212715e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,054] Trial 3140 finished with value: 0.4037452111831692 and parameters: {'alpha': 4.2536743270690746e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  63%|██████▎   | 3147/5000 [01:26<01:00, 30.64it/s]

[I 2026-06-14 00:49:59,087] Trial 3141 finished with value: 0.4037453688894374 and parameters: {'alpha': 2.9494057884948283e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,120] Trial 3142 finished with value: 0.40374508704111867 and parameters: {'alpha': 2.709974234011293e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,153] Trial 3143 finished with value: 0.4037447975337288 and parameters: {'alpha': 1.6941929494032252e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,184] Trial 3144 finished with value: 0.40374531764215144 and parameters: {'alpha': 7.467423613589399e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,217] Trial 3145 finished with value: 0.4037449724493677 and parameters: {'alpha': 1.783172138516064e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,249] Trial 3146 finished with value: 0.4037450416084738 and parameters: {'alpha': 2.8320885474545658e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,282] Trial 3147 finished with value: 0.403744403793571 and parameters: {'alpha': 1.0143887661160388e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  63%|██████▎   | 3155/5000 [01:26<01:00, 30.61it/s]

[I 2026-06-14 00:49:59,315] Trial 3148 finished with value: 0.4037452413397742 and parameters: {'alpha': 4.317548881180186e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,348] Trial 3149 finished with value: 0.4037455356322651 and parameters: {'alpha': 0.18491724143027236}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,380] Trial 3150 finished with value: 0.4037449008188033 and parameters: {'alpha': 1.770810641434506e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,414] Trial 3151 finished with value: 0.40374449312704624 and parameters: {'alpha': 1.0018974967373383e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,446] Trial 3152 finished with value: 0.4037449858199474 and parameters: {'alpha': 2.804738507808992e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,479] Trial 3153 finished with value: 0.4037444899555522 and parameters: {'alpha': 1.0059365084327801e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,511] Trial 3154 finished with value: 0.40374427252609696 and parameters: {'alpha': 1.0012988334851767e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  63%|██████▎   | 3161/5000 [01:27<00:59, 30.68it/s]

[I 2026-06-14 00:49:59,545] Trial 3155 finished with value: 0.4037444593104461 and parameters: {'alpha': 1.0072092933868744e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,578] Trial 3156 finished with value: 0.40374508802710823 and parameters: {'alpha': 2.7018977892565195e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,609] Trial 3157 finished with value: 0.4037452378325163 and parameters: {'alpha': 6.354999424184179e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,641] Trial 3158 finished with value: 0.4037443583933842 and parameters: {'alpha': 1.0026903557078114e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,674] Trial 3159 finished with value: 0.40374482084951013 and parameters: {'alpha': 1.7310020416571598e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,707] Trial 3160 finished with value: 0.4037452744977611 and parameters: {'alpha': 3.93115608285387e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,739] Trial 3161 finished with value: 0.4037448521191792 and parameters: {'alpha': 1.7597421094489848e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  63%|██████▎   | 3168/5000 [01:27<00:59, 30.56it/s]

[I 2026-06-14 00:49:59,771] Trial 3162 finished with value: 0.4037450181079869 and parameters: {'alpha': 2.5403937222623486e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,804] Trial 3163 finished with value: 0.4037448364822091 and parameters: {'alpha': 1.7305018071378984e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,836] Trial 3164 finished with value: 0.4037452821893057 and parameters: {'alpha': 5.6700098076764144e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,868] Trial 3165 finished with value: 0.4037449211874018 and parameters: {'alpha': 1.728288173685109e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,901] Trial 3166 finished with value: 0.4037450119623587 and parameters: {'alpha': 2.6094278204861438e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,939] Trial 3167 finished with value: 0.40374526081924134 and parameters: {'alpha': 3.84909292103308e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:49:59,972] Trial 3168 finished with value: 0.40374493810562645 and parameters: {'alpha': 1.7357640834243537e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  64%|██████▎   | 3175/5000 [01:27<01:00, 30.27it/s]

[I 2026-06-14 00:50:00,005] Trial 3169 finished with value: 0.40374533652682465 and parameters: {'alpha': 1.1528530692756154e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,038] Trial 3170 finished with value: 0.4037447902547351 and parameters: {'alpha': 1.6749507940769772e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,073] Trial 3171 finished with value: 0.40374442642886427 and parameters: {'alpha': 1.015204248632668e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,104] Trial 3172 finished with value: 0.4037450209036201 and parameters: {'alpha': 2.9031512622210774e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,137] Trial 3173 finished with value: 0.40374451089696584 and parameters: {'alpha': 1.0142244744729288e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,169] Trial 3174 finished with value: 0.40374522553420894 and parameters: {'alpha': 4.490994265512467e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,203] Trial 3175 finished with value: 0.40374486804827653 and parameters: {'alpha': 1.8121613957335762e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  64%|██████▎   | 3183/5000 [01:27<00:59, 30.57it/s]

[I 2026-06-14 00:50:00,236] Trial 3176 finished with value: 0.4037450989564071 and parameters: {'alpha': 2.7878020768440442e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,269] Trial 3177 finished with value: 0.4037447923673586 and parameters: {'alpha': 1.7272245235316238e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,301] Trial 3178 finished with value: 0.40374526129523214 and parameters: {'alpha': 6.67669055744328e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,334] Trial 3179 finished with value: 0.4037447304748865 and parameters: {'alpha': 1.7301910573470362e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,365] Trial 3180 finished with value: 0.40374500522443824 and parameters: {'alpha': 2.8330645988188377e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,398] Trial 3181 finished with value: 0.40374479280976805 and parameters: {'alpha': 1.6809580766717807e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,430] Trial 3182 finished with value: 0.4037445642194923 and parameters: {'alpha': 1.0074709384374733e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  64%|██████▍   | 3189/5000 [01:28<00:59, 30.48it/s]

[I 2026-06-14 00:50:00,464] Trial 3183 finished with value: 0.4037452773043135 and parameters: {'alpha': 4.491904322056213e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,497] Trial 3184 finished with value: 0.403744421708988 and parameters: {'alpha': 1.0050437463757888e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,529] Trial 3185 finished with value: 0.40374508384169916 and parameters: {'alpha': 2.6944251071673337e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,561] Trial 3186 finished with value: 0.40374475599223597 and parameters: {'alpha': 1.7162667034166185e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,594] Trial 3187 finished with value: 0.40374523148417146 and parameters: {'alpha': 4.160023740899212e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,627] Trial 3188 finished with value: 0.40374455317146857 and parameters: {'alpha': 1.0120103316527069e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,660] Trial 3189 finished with value: 0.4037453182991903 and parameters: {'alpha': 9.104934499263429e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  64%|██████▍   | 3196/5000 [01:28<00:59, 30.45it/s]

[I 2026-06-14 00:50:00,692] Trial 3190 finished with value: 0.4037448067642748 and parameters: {'alpha': 1.7615063527104033e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,728] Trial 3191 finished with value: 0.403744989107239 and parameters: {'alpha': 2.7909172613185614e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,760] Trial 3192 finished with value: 0.40374476876547316 and parameters: {'alpha': 1.7621675810311514e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,792] Trial 3193 finished with value: 0.40374436675992265 and parameters: {'alpha': 1.0012328621604784e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,824] Trial 3194 finished with value: 0.40374453153884327 and parameters: {'alpha': 1.0019083914733753e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,858] Trial 3195 finished with value: 0.4037450161310531 and parameters: {'alpha': 2.9387869460466863e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,889] Trial 3196 finished with value: 0.40374524745515483 and parameters: {'alpha': 5.197950729198328e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  64%|██████▍   | 3202/5000 [01:28<01:05, 27.38it/s]

[I 2026-06-14 00:50:00,923] Trial 3197 finished with value: 0.40387263740623125 and parameters: {'alpha': 42.90682248571311}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:00,958] Trial 3198 finished with value: 0.40374477426369215 and parameters: {'alpha': 1.7039864727467654e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,014] Trial 3199 finished with value: 0.40374495422554674 and parameters: {'alpha': 1.7135549012043376e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,061] Trial 3200 finished with value: 0.40374472546889767 and parameters: {'alpha': 1.0000865520798967e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,103] Trial 3201 finished with value: 0.4037453405248427 and parameters: {'alpha': 1.5896356935520273e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  64%|██████▍   | 3209/5000 [01:28<01:02, 28.66it/s]

[I 2026-06-14 00:50:01,137] Trial 3202 finished with value: 0.4037450621035098 and parameters: {'alpha': 2.736280730011471e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,170] Trial 3203 finished with value: 0.40374528792959397 and parameters: {'alpha': 4.323891723705004e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,204] Trial 3204 finished with value: 0.4037442769895006 and parameters: {'alpha': 1.0074601100786322e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,238] Trial 3205 finished with value: 0.4037450478244686 and parameters: {'alpha': 2.554162589013122e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,271] Trial 3206 finished with value: 0.40374485114348874 and parameters: {'alpha': 1.7181635339812897e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,304] Trial 3207 finished with value: 0.4037452757407428 and parameters: {'alpha': 6.011168525951356e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,336] Trial 3208 finished with value: 0.40374436680971604 and parameters: {'alpha': 1.0030213168971226e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  64%|██████▍   | 3216/5000 [01:28<01:00, 29.41it/s]

[I 2026-06-14 00:50:01,371] Trial 3209 finished with value: 0.40374436030228156 and parameters: {'alpha': 1.0070747187901213e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,405] Trial 3210 finished with value: 0.403745005599802 and parameters: {'alpha': 2.6091365573003104e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,436] Trial 3211 finished with value: 0.4037449480876057 and parameters: {'alpha': 1.7266173523868334e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,470] Trial 3212 finished with value: 0.4037452059884996 and parameters: {'alpha': 3.9985804534550815e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,503] Trial 3213 finished with value: 0.4037454065063663 and parameters: {'alpha': 0.0001066081534925848}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,536] Trial 3214 finished with value: 0.40374494917017706 and parameters: {'alpha': 1.74568401191124e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,568] Trial 3215 finished with value: 0.403745318724968 and parameters: {'alpha': 8.149816424654528e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  64%|██████▍   | 3222/5000 [01:29<01:00, 29.55it/s]

[I 2026-06-14 00:50:01,604] Trial 3216 finished with value: 0.4037443549047155 and parameters: {'alpha': 1.0027012327894702e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,637] Trial 3217 finished with value: 0.40374507501470136 and parameters: {'alpha': 2.8486178831640024e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,670] Trial 3218 finished with value: 0.40374540671767695 and parameters: {'alpha': 0.0003420437612076871}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,705] Trial 3219 finished with value: 0.4037448589400933 and parameters: {'alpha': 1.7062884551052806e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,738] Trial 3220 finished with value: 0.4037447690665768 and parameters: {'alpha': 1.7678454418124017e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,770] Trial 3221 finished with value: 0.4037451816020846 and parameters: {'alpha': 3.94261065945326e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,804] Trial 3222 finished with value: 0.40374508305809315 and parameters: {'alpha': 2.6630732930829532e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  65%|██████▍   | 3229/5000 [01:29<00:59, 29.78it/s]

[I 2026-06-14 00:50:01,837] Trial 3223 finished with value: 0.4037447588593791 and parameters: {'alpha': 1.727326203361388e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,869] Trial 3224 finished with value: 0.4037443130920647 and parameters: {'alpha': 1.0140263029905097e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,902] Trial 3225 finished with value: 0.4037449829572861 and parameters: {'alpha': 2.641330503508935e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,938] Trial 3226 finished with value: 0.40374524411744867 and parameters: {'alpha': 6.20585264666804e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:01,970] Trial 3227 finished with value: 0.40374481306500726 and parameters: {'alpha': 1.8182709762149577e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,003] Trial 3228 finished with value: 0.4037449111429635 and parameters: {'alpha': 1.6545555622355683e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,036] Trial 3229 finished with value: 0.40374520704252176 and parameters: {'alpha': 4.166868576315319e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  65%|██████▍   | 3237/5000 [01:29<00:58, 30.05it/s]

[I 2026-06-14 00:50:02,069] Trial 3230 finished with value: 0.40374433852615704 and parameters: {'alpha': 1.013405252481033e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,103] Trial 3231 finished with value: 0.40374507746751076 and parameters: {'alpha': 2.7788165776197666e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,136] Trial 3232 finished with value: 0.40374489108431755 and parameters: {'alpha': 1.704558335332549e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,169] Trial 3233 finished with value: 0.40374460120065814 and parameters: {'alpha': 1.009765658530753e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,202] Trial 3234 finished with value: 0.40374521435631777 and parameters: {'alpha': 3.878361003507323e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,234] Trial 3235 finished with value: 0.4037443404412812 and parameters: {'alpha': 1.0055650177569623e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,267] Trial 3236 finished with value: 0.4037450071620455 and parameters: {'alpha': 2.6638771967089866e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  65%|██████▍   | 3243/5000 [01:29<00:58, 30.21it/s]

[I 2026-06-14 00:50:02,301] Trial 3237 finished with value: 0.40374494313948567 and parameters: {'alpha': 1.6630599931000296e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,334] Trial 3238 finished with value: 0.403744870858667 and parameters: {'alpha': 1.707094900991022e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,367] Trial 3239 finished with value: 0.40374434268558973 and parameters: {'alpha': 1.004632891055055e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,399] Trial 3240 finished with value: 0.4037445636415505 and parameters: {'alpha': 1.0042667265165347e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,433] Trial 3241 finished with value: 0.40375063254579757 and parameters: {'alpha': 4.106432583814681}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,465] Trial 3242 finished with value: 0.40374531438473854 and parameters: {'alpha': 9.04062019467867e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,498] Trial 3243 finished with value: 0.4037451880991413 and parameters: {'alpha': 4.3013484767918606e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  65%|██████▍   | 3249/5000 [01:30<00:57, 30.31it/s]

[I 2026-06-14 00:50:02,532] Trial 3244 finished with value: 0.40374435237302536 and parameters: {'alpha': 1.0038241746528391e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,567] Trial 3245 finished with value: 0.40374496600722504 and parameters: {'alpha': 2.589559418652323e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,599] Trial 3246 finished with value: 0.4037449578792627 and parameters: {'alpha': 1.7152740143534787e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,630] Trial 3247 finished with value: 0.40374523710218885 and parameters: {'alpha': 6.285847323916898e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,663] Trial 3248 finished with value: 0.4037450659416844 and parameters: {'alpha': 2.62642265482021e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,702] Trial 3249 finished with value: 0.40374476417307026 and parameters: {'alpha': 1.758025711137575e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  65%|██████▌   | 3256/5000 [01:30<01:01, 28.50it/s]

[I 2026-06-14 00:50:02,743] Trial 3250 finished with value: 0.40374504930942046 and parameters: {'alpha': 2.7123546840763387e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,782] Trial 3251 finished with value: 0.4037444441918747 and parameters: {'alpha': 1.0064038400082317e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,817] Trial 3252 finished with value: 0.4037447700701009 and parameters: {'alpha': 1.730649182458016e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,856] Trial 3253 finished with value: 0.4037453479808039 and parameters: {'alpha': 1.7693469054943187e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,892] Trial 3254 finished with value: 0.40374525404799616 and parameters: {'alpha': 4.5433987148310606e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:02,926] Trial 3255 finished with value: 0.403744778693722 and parameters: {'alpha': 1.7516526380678873e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  65%|██████▌   | 3262/5000 [01:30<01:03, 27.49it/s]

[I 2026-06-14 00:50:02,965] Trial 3256 finished with value: 0.40374703526234473 and parameters: {'alpha': 1.7257612359530259}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,008] Trial 3257 finished with value: 0.4037454032823102 and parameters: {'alpha': 2.6286567328744337e-06}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,042] Trial 3258 finished with value: 0.40374498926754815 and parameters: {'alpha': 2.7668348347719332e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,082] Trial 3259 finished with value: 0.40374459948010444 and parameters: {'alpha': 1.0105103203045264e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,120] Trial 3260 finished with value: 0.40374481714740346 and parameters: {'alpha': 1.7424617681192518e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,155] Trial 3261 finished with value: 0.4037452958574273 and parameters: {'alpha': 8.163606713310163e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  65%|██████▌   | 3268/5000 [01:30<01:00, 28.41it/s]

[I 2026-06-14 00:50:03,188] Trial 3262 finished with value: 0.4037444369314546 and parameters: {'alpha': 1.0032189489832151e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,222] Trial 3263 finished with value: 0.40374522477839564 and parameters: {'alpha': 3.948520197888648e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,253] Trial 3264 finished with value: 0.40374507752970307 and parameters: {'alpha': 2.6632090894865608e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,286] Trial 3265 finished with value: 0.4037447336478788 and parameters: {'alpha': 1.7726647168109405e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,320] Trial 3266 finished with value: 0.4037443328982025 and parameters: {'alpha': 1.004611196116866e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,353] Trial 3267 finished with value: 0.4037452887774373 and parameters: {'alpha': 4.1975375601952806e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,386] Trial 3268 finished with value: 0.4037443379195946 and parameters: {'alpha': 1.0062421535607428e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  66%|██████▌   | 3275/5000 [01:30<00:58, 29.29it/s]

[I 2026-06-14 00:50:03,421] Trial 3269 finished with value: 0.40374482706832027 and parameters: {'alpha': 1.7180331821277735e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,453] Trial 3270 finished with value: 0.4037450690462334 and parameters: {'alpha': 2.7480471989478008e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,486] Trial 3271 finished with value: 0.403745250203373 and parameters: {'alpha': 6.507236789482474e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,518] Trial 3272 finished with value: 0.5567026505859722 and parameters: {'alpha': 47634.42285612674}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,553] Trial 3273 finished with value: 0.40374489931408625 and parameters: {'alpha': 1.7569753621370653e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,585] Trial 3274 finished with value: 0.40374501896711296 and parameters: {'alpha': 2.6655201135743562e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,619] Trial 3275 finished with value: 0.40374486289542333 and parameters: {'alpha': 1.7285618487546282e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:50:03,653] Trial 3276 finished with value: 0.4037452550093203 and parameters: {'alpha': 3.838743392350701e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,687] Trial 3277 finished with value: 0.40374498811845033 and parameters: {'alpha': 2.620721924974372e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,722] Trial 3278 finished with value: 0.40374489065396013 and parameters: {'alpha': 1.8603605646275176e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,754] Trial 3279 finished with value: 0.4037449337433566 and parameters: {'alpha': 1.7451237146280494e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,787] Trial 3280 finished with value: 0.40374531089918747 and parameters: {'alpha': 5.7066534464539584e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,820] Trial 3281 finished with value: 0.4037448187265749 and parameters: {'alpha': 1.7782909854356942e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,854] Trial 3282 finished with value: 0.40374523391832323 and parameters: {'alpha': 3.906028913927064e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  66%|██████▌   | 3288/5000 [01:31<00:58, 29.47it/s]

[I 2026-06-14 00:50:03,887] Trial 3283 finished with value: 0.4037450586508365 and parameters: {'alpha': 2.7454760140212523e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,922] Trial 3284 finished with value: 0.4037444970593155 and parameters: {'alpha': 1.0142123701454761e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,956] Trial 3285 finished with value: 0.4037443678506757 and parameters: {'alpha': 1.0077882647321315e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:03,992] Trial 3286 finished with value: 0.4037453350067957 and parameters: {'alpha': 1.0561229427043029e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,025] Trial 3287 finished with value: 0.4037449224820856 and parameters: {'alpha': 1.6356740210222644e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,059] Trial 3288 finished with value: 0.40374470763502796 and parameters: {'alpha': 1.651994767702993e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  66%|██████▌   | 3295/5000 [01:31<00:57, 29.57it/s]

[I 2026-06-14 00:50:04,092] Trial 3289 finished with value: 0.40374517580103825 and parameters: {'alpha': 3.9823181927195073e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,127] Trial 3290 finished with value: 0.40374485594302006 and parameters: {'alpha': 1.7171448669830435e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,161] Trial 3291 finished with value: 0.4037450642849668 and parameters: {'alpha': 2.830457160819698e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,194] Trial 3292 finished with value: 0.4037449760245815 and parameters: {'alpha': 1.7312921727626692e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,227] Trial 3293 finished with value: 0.40374430454046095 and parameters: {'alpha': 1.0029617858386739e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,261] Trial 3294 finished with value: 0.4037452292768182 and parameters: {'alpha': 6.067912258663733e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,294] Trial 3295 finished with value: 0.40374492098974774 and parameters: {'alpha': 1.7288568573359452e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  66%|██████▌   | 3302/5000 [01:31<00:56, 30.11it/s]

[I 2026-06-14 00:50:04,328] Trial 3296 finished with value: 0.4037450632448239 and parameters: {'alpha': 2.8520045779959033e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,360] Trial 3297 finished with value: 0.4037444243650203 and parameters: {'alpha': 1.009431402241423e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,394] Trial 3298 finished with value: 0.40374460809361395 and parameters: {'alpha': 1.0144112173827712e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,425] Trial 3299 finished with value: 0.40374446435722927 and parameters: {'alpha': 1.0102603123178868e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,458] Trial 3300 finished with value: 0.4037452300112755 and parameters: {'alpha': 4.1166820667532606e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,491] Trial 3301 finished with value: 0.4037444862758738 and parameters: {'alpha': 1.0106266339231719e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,524] Trial 3302 finished with value: 0.40374516454228737 and parameters: {'alpha': 3.000422048728106e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  66%|██████▌   | 3310/5000 [01:32<00:56, 30.15it/s]

[I 2026-06-14 00:50:04,557] Trial 3303 finished with value: 0.40374497663576636 and parameters: {'alpha': 1.7271958514894508e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,591] Trial 3304 finished with value: 0.4037453083030251 and parameters: {'alpha': 9.593481973845538e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,623] Trial 3305 finished with value: 0.40374503847193166 and parameters: {'alpha': 2.610147731026774e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,657] Trial 3306 finished with value: 0.4037452894083858 and parameters: {'alpha': 5.509584806764184e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,690] Trial 3307 finished with value: 0.40374486944353993 and parameters: {'alpha': 1.7172844442208523e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,723] Trial 3308 finished with value: 0.4037447672028836 and parameters: {'alpha': 1.7873015198490977e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,755] Trial 3309 finished with value: 0.40374459587781836 and parameters: {'alpha': 1.0022932702621671e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  66%|██████▋   | 3315/5000 [01:32<00:56, 30.08it/s]

[I 2026-06-14 00:50:04,789] Trial 3310 finished with value: 0.403745102247597 and parameters: {'alpha': 2.7844259634368452e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,823] Trial 3311 finished with value: 0.4037448279605216 and parameters: {'alpha': 1.7229638712718205e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,855] Trial 3312 finished with value: 0.4037452682523861 and parameters: {'alpha': 4.1319655856216897e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,888] Trial 3313 finished with value: 0.403744759373619 and parameters: {'alpha': 1.673870408007133e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,924] Trial 3314 finished with value: 0.4037443381683862 and parameters: {'alpha': 1.0135633796398351e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:04,957] Trial 3315 finished with value: 0.4037451794000227 and parameters: {'alpha': 3.0480119843496466e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  66%|██████▋   | 3321/5000 [01:32<00:58, 28.64it/s]

[I 2026-06-14 00:50:04,995] Trial 3316 finished with value: 0.40374436652898515 and parameters: {'alpha': 1.0003859403958509e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,034] Trial 3317 finished with value: 0.40374527057274434 and parameters: {'alpha': 5.934038383161136e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,071] Trial 3318 finished with value: 0.40374482224949404 and parameters: {'alpha': 1.7216823502265558e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,110] Trial 3319 finished with value: 0.4037450521080868 and parameters: {'alpha': 2.6876411604132744e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,145] Trial 3320 finished with value: 0.4037450921041636 and parameters: {'alpha': 2.7526041665262986e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,180] Trial 3321 finished with value: 0.40374481709876664 and parameters: {'alpha': 1.7071021498858196e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  67%|██████▋   | 3328/5000 [01:32<00:56, 29.43it/s]

[I 2026-06-14 00:50:05,212] Trial 3322 finished with value: 0.40374473757615803 and parameters: {'alpha': 1.015068870405794e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,246] Trial 3323 finished with value: 0.40374427573763944 and parameters: {'alpha': 1.013180164007107e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,280] Trial 3324 finished with value: 0.40374524149997043 and parameters: {'alpha': 4.7150479205185704e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,313] Trial 3325 finished with value: 0.4037442911127729 and parameters: {'alpha': 1.0003348298346548e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,345] Trial 3326 finished with value: 0.4037450775212251 and parameters: {'alpha': 2.692160200688152e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,378] Trial 3327 finished with value: 0.4037445334355869 and parameters: {'alpha': 1.0042960375163723e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,413] Trial 3328 finished with value: 0.40374533065463025 and parameters: {'alpha': 1.0680993543391378e-07}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  67%|██████▋   | 3335/5000 [01:33<00:56, 29.68it/s]

[I 2026-06-14 00:50:05,447] Trial 3329 finished with value: 0.4037454107601173 and parameters: {'alpha': 0.006355505434752015}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,480] Trial 3330 finished with value: 0.4037449452150972 and parameters: {'alpha': 1.7065040730259086e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,513] Trial 3331 finished with value: 0.40374501881821345 and parameters: {'alpha': 2.6786732401911165e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,545] Trial 3332 finished with value: 0.4037448040837513 and parameters: {'alpha': 1.7833196746905346e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,579] Trial 3333 finished with value: 0.40374522768764376 and parameters: {'alpha': 4.385905751851707e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,611] Trial 3334 finished with value: 0.4037447929142998 and parameters: {'alpha': 1.7744901474221936e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,645] Trial 3335 finished with value: 0.4037446584663412 and parameters: {'alpha': 1.006602850703185e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  67%|██████▋   | 3342/5000 [01:33<00:55, 29.82it/s]

[I 2026-06-14 00:50:05,679] Trial 3336 finished with value: 0.40374530101831463 and parameters: {'alpha': 6.578994957148309e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,712] Trial 3337 finished with value: 0.4037450123746029 and parameters: {'alpha': 2.7870393928972708e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,745] Trial 3338 finished with value: 0.40374500703165883 and parameters: {'alpha': 2.8034467561763138e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,780] Trial 3339 finished with value: 0.4037448280203743 and parameters: {'alpha': 1.7554290394521523e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,813] Trial 3340 finished with value: 0.4037445168315705 and parameters: {'alpha': 1.0070434262183502e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,846] Trial 3341 finished with value: 0.4037449457368779 and parameters: {'alpha': 1.674796108295399e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,880] Trial 3342 finished with value: 0.4037447329443055 and parameters: {'alpha': 1.002685120040413e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  67%|██████▋   | 3349/5000 [01:33<00:55, 29.56it/s]

[I 2026-06-14 00:50:05,913] Trial 3343 finished with value: 0.4037451871218449 and parameters: {'alpha': 4.073568632872709e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,946] Trial 3344 finished with value: 0.40374494690591717 and parameters: {'alpha': 1.7390317842769957e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:05,979] Trial 3345 finished with value: 0.40374450321587446 and parameters: {'alpha': 1.000600215785631e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,015] Trial 3346 finished with value: 0.40374503426085473 and parameters: {'alpha': 2.768872814440319e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,049] Trial 3347 finished with value: 0.40374533936291335 and parameters: {'alpha': 1.4286749935140016e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,083] Trial 3348 finished with value: 0.403745276264084 and parameters: {'alpha': 6.70763555231503e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  67%|██████▋   | 3355/5000 [01:33<00:55, 29.62it/s]

[I 2026-06-14 00:50:06,117] Trial 3349 finished with value: 0.40374484404607974 and parameters: {'alpha': 1.7336273949309907e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,151] Trial 3350 finished with value: 0.4037452541447495 and parameters: {'alpha': 3.8871605033884205e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,184] Trial 3351 finished with value: 0.40374472144138684 and parameters: {'alpha': 1.7158084323183976e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,218] Trial 3352 finished with value: 0.4037450772293366 and parameters: {'alpha': 2.6765082074875246e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,252] Trial 3353 finished with value: 0.4037448510304522 and parameters: {'alpha': 1.734842291849226e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,286] Trial 3354 finished with value: 0.4037452337660698 and parameters: {'alpha': 4.404828882060081e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  67%|██████▋   | 3361/5000 [01:33<00:55, 29.70it/s]

[I 2026-06-14 00:50:06,321] Trial 3355 finished with value: 0.40374479026876425 and parameters: {'alpha': 1.7299490759018054e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,354] Trial 3356 finished with value: 0.4037446227404105 and parameters: {'alpha': 1.0073381125983405e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,387] Trial 3357 finished with value: 0.40374461706139636 and parameters: {'alpha': 1.0017936298758788e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,422] Trial 3358 finished with value: 0.4037450567204608 and parameters: {'alpha': 2.67144023597077e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,455] Trial 3359 finished with value: 0.4037443644790434 and parameters: {'alpha': 1.0080554787638232e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,487] Trial 3360 finished with value: 0.4037446136168964 and parameters: {'alpha': 1.0007222055004003e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,521] Trial 3361 finished with value: 0.4037452580914879 and parameters: {'alpha': 4.6253973243213626e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:50:06,554] Trial 3362 finished with value: 0.40374449707110877 and parameters: {'alpha': 1.0039955905079521e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,587] Trial 3363 finished with value: 0.4037443916981987 and parameters: {'alpha': 1.0008209118386686e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,622] Trial 3364 finished with value: 0.4037450260089959 and parameters: {'alpha': 2.7058606651591266e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,655] Trial 3365 finished with value: 0.403744828193408 and parameters: {'alpha': 1.7377671040729036e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,688] Trial 3366 finished with value: 0.40374530266108927 and parameters: {'alpha': 6.758089054372802e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,722] Trial 3367 finished with value: 0.40374497471250514 and parameters: {'alpha': 2.614363780008999e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  67%|██████▋   | 3373/5000 [01:34<00:54, 29.70it/s]

[I 2026-06-14 00:50:06,756] Trial 3368 finished with value: 0.40374489611845926 and parameters: {'alpha': 1.703959443793222e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,789] Trial 3369 finished with value: 0.4037450055843047 and parameters: {'alpha': 2.7423682251530943e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,824] Trial 3370 finished with value: 0.4037449158736101 and parameters: {'alpha': 1.7014623399030177e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,856] Trial 3371 finished with value: 0.40374532566921806 and parameters: {'alpha': 1.0262241229834354e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,889] Trial 3372 finished with value: 0.4037452037162369 and parameters: {'alpha': 3.750894141093994e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,925] Trial 3373 finished with value: 0.40374495532977966 and parameters: {'alpha': 1.8886453635555396e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  68%|██████▊   | 3379/5000 [01:34<00:55, 29.30it/s]

[I 2026-06-14 00:50:06,959] Trial 3374 finished with value: 0.4037453681902645 and parameters: {'alpha': 2.4079406086516304e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:06,993] Trial 3375 finished with value: 0.40374489235071803 and parameters: {'alpha': 1.7366846919397192e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,030] Trial 3376 finished with value: 0.40374527851229774 and parameters: {'alpha': 5.0471649022467226e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,065] Trial 3377 finished with value: 0.4037450952871992 and parameters: {'alpha': 2.7152828967130126e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,098] Trial 3378 finished with value: 0.4037446015069412 and parameters: {'alpha': 1.0064411799282203e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,131] Trial 3379 finished with value: 0.4037447508834476 and parameters: {'alpha': 1.657415308503354e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  68%|██████▊   | 3385/5000 [01:34<00:55, 28.95it/s]

[I 2026-06-14 00:50:07,165] Trial 3380 finished with value: 0.4037452504931455 and parameters: {'alpha': 3.96983980240945e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,199] Trial 3381 finished with value: 0.4037447496017761 and parameters: {'alpha': 1.7558953716531197e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,234] Trial 3382 finished with value: 0.4037453019875335 and parameters: {'alpha': 7.191557879763355e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,270] Trial 3383 finished with value: 0.4037450339559662 and parameters: {'alpha': 2.8738563824773646e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,305] Trial 3384 finished with value: 0.4037459466258677 and parameters: {'alpha': 0.6907252855435656}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,339] Trial 3385 finished with value: 0.4037449076082786 and parameters: {'alpha': 1.841713748497935e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:50:07,372] Trial 3386 finished with value: 0.4037448089578645 and parameters: {'alpha': 1.716814845267551e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,407] Trial 3387 finished with value: 0.4037448997822737 and parameters: {'alpha': 1.695986023865228e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,442] Trial 3388 finished with value: 0.40374459649633127 and parameters: {'alpha': 1.0092713284178403e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,475] Trial 3389 finished with value: 0.40374524854537863 and parameters: {'alpha': 4.1201434018908123e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,507] Trial 3390 finished with value: 0.40374500756233817 and parameters: {'alpha': 2.866171880422742e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,540] Trial 3391 finished with value: 0.40374497377371993 and parameters: {'alpha': 1.731771044635309e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,574] Trial 3392 finished with value: 0.403745257281006 and parameters: {'alpha': 6.622364002705323e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  68%|██████▊   | 3398/5000 [01:35<00:54, 29.51it/s]

[I 2026-06-14 00:50:07,607] Trial 3393 finished with value: 0.40374475336082116 and parameters: {'alpha': 1.7787000986019112e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,642] Trial 3394 finished with value: 0.4037450659861996 and parameters: {'alpha': 2.8764002408153238e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,676] Trial 3395 finished with value: 0.4037448000725187 and parameters: {'alpha': 1.7081086760539902e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,710] Trial 3396 finished with value: 0.4037448954180626 and parameters: {'alpha': 1.6922321583592248e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,743] Trial 3397 finished with value: 0.40374525372921616 and parameters: {'alpha': 3.7518554571063356e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,779] Trial 3398 finished with value: 0.4037448466896014 and parameters: {'alpha': 1.687030465765621e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  68%|██████▊   | 3405/5000 [01:35<00:53, 29.70it/s]

[I 2026-06-14 00:50:07,811] Trial 3399 finished with value: 0.4037447211234372 and parameters: {'alpha': 1.0223964902275685e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,845] Trial 3400 finished with value: 0.4037452073443681 and parameters: {'alpha': 4.0445763717533624e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,879] Trial 3401 finished with value: 0.4037451058758588 and parameters: {'alpha': 2.7516938678468525e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,912] Trial 3402 finished with value: 0.4037453091270296 and parameters: {'alpha': 9.970629714317672e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,945] Trial 3403 finished with value: 0.40374503605683887 and parameters: {'alpha': 2.635096642936094e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:07,978] Trial 3404 finished with value: 0.40374498825498756 and parameters: {'alpha': 1.8273487210875404e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  68%|██████▊   | 3411/5000 [01:35<00:54, 29.32it/s]

[I 2026-06-14 00:50:08,014] Trial 3405 finished with value: 0.4037454059717185 and parameters: {'alpha': 1.9195559296873445e-05}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,050] Trial 3406 finished with value: 0.40374486524611336 and parameters: {'alpha': 1.697804232124371e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,084] Trial 3407 finished with value: 0.40374440970926156 and parameters: {'alpha': 1.0103665466085982e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,119] Trial 3408 finished with value: 0.40374526255137144 and parameters: {'alpha': 5.417098627372332e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,153] Trial 3409 finished with value: 0.4037449356849292 and parameters: {'alpha': 1.6992015985314767e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,186] Trial 3410 finished with value: 0.4037450267434641 and parameters: {'alpha': 2.7361441766191164e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  68%|██████▊   | 3417/5000 [01:35<00:53, 29.57it/s]

[I 2026-06-14 00:50:08,220] Trial 3411 finished with value: 0.4037443391874271 and parameters: {'alpha': 1.0139564755420951e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,255] Trial 3412 finished with value: 0.40374438809681634 and parameters: {'alpha': 1.0133152633391163e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,288] Trial 3413 finished with value: 0.4037452633096849 and parameters: {'alpha': 4.7631314352520064e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,321] Trial 3414 finished with value: 0.40374500425305876 and parameters: {'alpha': 2.6684638582587783e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,355] Trial 3415 finished with value: 0.40374490573532196 and parameters: {'alpha': 1.6822060472083072e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,387] Trial 3416 finished with value: 0.4037448025756082 and parameters: {'alpha': 1.7065493116671922e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,422] Trial 3417 finished with value: 0.40374440946053497 and parameters: {'alpha': 1.0239161334874593e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:50:08,456] Trial 3418 finished with value: 0.40374455431071543 and parameters: {'alpha': 1.0167374813007158e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,489] Trial 3419 finished with value: 0.4037445375797531 and parameters: {'alpha': 1.0077574001753728e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,524] Trial 3420 finished with value: 0.40452848042256395 and parameters: {'alpha': 268.6327804288296}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,557] Trial 3421 finished with value: 0.40374512573567617 and parameters: {'alpha': 2.9524018653129053e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,591] Trial 3422 finished with value: 0.4037452513301897 and parameters: {'alpha': 6.020459742854174e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,625] Trial 3423 finished with value: 0.4037450284593867 and parameters: {'alpha': 2.7533654704858546e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  69%|██████▊   | 3429/5000 [01:36<00:53, 29.39it/s]

[I 2026-06-14 00:50:08,658] Trial 3424 finished with value: 0.40374486974550633 and parameters: {'alpha': 1.6925571496384764e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,692] Trial 3425 finished with value: 0.40374525561627617 and parameters: {'alpha': 4.6746189683433984e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,727] Trial 3426 finished with value: 0.4037453236927762 and parameters: {'alpha': 1.3029696141578387e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,760] Trial 3427 finished with value: 0.4037445601836479 and parameters: {'alpha': 1.0002662654720206e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,795] Trial 3428 finished with value: 0.4037450077862818 and parameters: {'alpha': 2.573344924926335e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,831] Trial 3429 finished with value: 0.40374487149739063 and parameters: {'alpha': 1.6961518315332117e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  69%|██████▊   | 3435/5000 [01:36<00:53, 29.42it/s]

[I 2026-06-14 00:50:08,864] Trial 3430 finished with value: 0.4037445273705918 and parameters: {'alpha': 1.0046607971354596e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,898] Trial 3431 finished with value: 0.4037452120526247 and parameters: {'alpha': 4.037825899730123e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,934] Trial 3432 finished with value: 0.40374540712136164 and parameters: {'alpha': 0.0009221332591932859}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:08,967] Trial 3433 finished with value: 0.4037450339166568 and parameters: {'alpha': 2.6454080330043048e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,000] Trial 3434 finished with value: 0.4037449210281009 and parameters: {'alpha': 1.7739216250514398e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,037] Trial 3435 finished with value: 0.4037453028292669 and parameters: {'alpha': 7.82906603339915e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:50:09,071] Trial 3436 finished with value: 0.4037450706632746 and parameters: {'alpha': 2.714109885733351e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,106] Trial 3437 finished with value: 0.4037447385760157 and parameters: {'alpha': 1.662734443668258e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,139] Trial 3438 finished with value: 0.4037452534229902 and parameters: {'alpha': 4.2193060910031e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,173] Trial 3439 finished with value: 0.4037448926912475 and parameters: {'alpha': 1.7285775355536277e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,205] Trial 3440 finished with value: 0.40374459417296804 and parameters: {'alpha': 1.0079074131130822e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,240] Trial 3441 finished with value: 0.40374440239911946 and parameters: {'alpha': 1.0053481180220319e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  69%|██████▉   | 3447/5000 [01:36<00:52, 29.43it/s]

[I 2026-06-14 00:50:09,273] Trial 3442 finished with value: 0.40374463475914857 and parameters: {'alpha': 1.0139269853178559e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,307] Trial 3443 finished with value: 0.4037443919731826 and parameters: {'alpha': 1.0132657347666659e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,343] Trial 3444 finished with value: 0.4037450124435124 and parameters: {'alpha': 2.6171697641606914e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,376] Trial 3445 finished with value: 0.4037447580989477 and parameters: {'alpha': 1.767749391802338e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,410] Trial 3446 finished with value: 0.4037450770635913 and parameters: {'alpha': 2.8355142418441992e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,444] Trial 3447 finished with value: 0.4037452414384715 and parameters: {'alpha': 4.294811014627462e-08}. Best is trial 346 with value: 0.4037442459980544.

[I 2026-06-14 00:50:09,478] Trial 3448 finished with value: 0.4037445462311611 and parameters: {'alpha': 1.0098381419744179e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,514] Trial 3449 finished with value: 0.40374478304926514 and parameters: {'alpha': 1.732522020948827e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,547] Trial 3450 finished with value: 0.4037452988192274 and parameters: {'alpha': 6.571480231347321e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,580] Trial 3451 finished with value: 0.4037449719469512 and parameters: {'alpha': 2.4770117140800497e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,613] Trial 3452 finished with value: 0.4037445083694752 and parameters: {'alpha': 1.0021711614773708e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,646] Trial 3453 finished with value: 0.40374458250281037 and parameters: {'alpha': 1.0045779757772903e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  69%|██████▉   | 3460/5000 [01:37<00:51, 29.71it/s]

[I 2026-06-14 00:50:09,681] Trial 3454 finished with value: 0.4037453775355173 and parameters: {'alpha': 4.063892310045241e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,716] Trial 3455 finished with value: 0.4037448614660955 and parameters: {'alpha': 1.7000332476553498e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,747] Trial 3456 finished with value: 0.40374524040080256 and parameters: {'alpha': 4.4675274134429075e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,781] Trial 3457 finished with value: 0.4037450306560427 and parameters: {'alpha': 2.6420673817857483e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,815] Trial 3458 finished with value: 0.4037446586651408 and parameters: {'alpha': 1.0029214291814837e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,848] Trial 3459 finished with value: 0.4037442865807568 and parameters: {'alpha': 1.0038464392201399e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,882] Trial 3460 finished with value: 0.4037446584037953 and parameters: {'alpha': 1.0044094377613282e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  69%|██████▉   | 3466/5000 [01:37<00:52, 29.43it/s]

[I 2026-06-14 00:50:09,916] Trial 3461 finished with value: 0.4037453092296815 and parameters: {'alpha': 8.284100828151252e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,951] Trial 3462 finished with value: 0.4037448218592167 and parameters: {'alpha': 1.7273034370399358e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:09,984] Trial 3463 finished with value: 0.40374525234685293 and parameters: {'alpha': 4.1538913967792166e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,017] Trial 3464 finished with value: 0.4037444386333328 and parameters: {'alpha': 1.0061903027848637e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,053] Trial 3465 finished with value: 0.40374502722859945 and parameters: {'alpha': 2.7251005256135668e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,089] Trial 3466 finished with value: 0.4037447604458159 and parameters: {'alpha': 1.7571945783264597e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  69%|██████▉   | 3472/5000 [01:37<00:52, 28.98it/s]

[I 2026-06-14 00:50:10,125] Trial 3467 finished with value: 0.4037449541365779 and parameters: {'alpha': 2.6230285685695672e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,160] Trial 3468 finished with value: 0.4037449595413279 and parameters: {'alpha': 1.7390003152049402e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,196] Trial 3469 finished with value: 0.40374534264505957 and parameters: {'alpha': 1.5422836998258991e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,229] Trial 3470 finished with value: 0.4037452435136587 and parameters: {'alpha': 4.325200044674596e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,264] Trial 3471 finished with value: 0.40374486084742633 and parameters: {'alpha': 1.7133967750180268e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,298] Trial 3472 finished with value: 0.40374484330286897 and parameters: {'alpha': 1.7521949195163412e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  70%|██████▉   | 3478/5000 [01:37<00:52, 28.99it/s]

[I 2026-06-14 00:50:10,333] Trial 3473 finished with value: 0.40374516571287883 and parameters: {'alpha': 3.912922681639916e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,368] Trial 3474 finished with value: 0.40374507764196343 and parameters: {'alpha': 2.7427914760149378e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,404] Trial 3475 finished with value: 0.4037453064950459 and parameters: {'alpha': 7.218358031105826e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,437] Trial 3476 finished with value: 0.4037447561364123 and parameters: {'alpha': 1.7268891362997583e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,472] Trial 3477 finished with value: 0.4037449130891764 and parameters: {'alpha': 1.844402519569703e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,506] Trial 3478 finished with value: 0.40374494342753925 and parameters: {'alpha': 1.6821468202693604e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  70%|██████▉   | 3484/5000 [01:38<00:52, 29.10it/s]

[I 2026-06-14 00:50:10,539] Trial 3479 finished with value: 0.4037450672858629 and parameters: {'alpha': 2.8279452721773205e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,573] Trial 3480 finished with value: 0.40374486420490713 and parameters: {'alpha': 1.710084865788127e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,609] Trial 3481 finished with value: 0.40374521609017644 and parameters: {'alpha': 4.060947693889942e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,643] Trial 3482 finished with value: 0.40374482919881277 and parameters: {'alpha': 1.6912592829288017e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,677] Trial 3483 finished with value: 0.40374473228309044 and parameters: {'alpha': 1.0056875198492756e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,712] Trial 3484 finished with value: 0.4037443271521533 and parameters: {'alpha': 1.0130663889376702e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  70%|██████▉   | 3490/5000 [01:38<00:51, 29.22it/s]

[I 2026-06-14 00:50:10,746] Trial 3485 finished with value: 0.4037452380131728 and parameters: {'alpha': 6.533336963223308e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,780] Trial 3486 finished with value: 0.40374501928269924 and parameters: {'alpha': 2.9444492306568415e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,814] Trial 3487 finished with value: 0.40374469239866856 and parameters: {'alpha': 1.014101505179773e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,847] Trial 3488 finished with value: 0.40374508893316713 and parameters: {'alpha': 2.6964783010365666e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,881] Trial 3489 finished with value: 0.40374488903570566 and parameters: {'alpha': 1.6627795384257895e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,916] Trial 3490 finished with value: 0.40374431407265216 and parameters: {'alpha': 1.0148359360919565e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  70%|██████▉   | 3496/5000 [01:38<00:52, 28.80it/s]

[I 2026-06-14 00:50:10,950] Trial 3491 finished with value: 0.40374528771145546 and parameters: {'alpha': 4.7926327027971467e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:10,986] Trial 3492 finished with value: 0.403745002738614 and parameters: {'alpha': 2.7506168794219783e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,021] Trial 3493 finished with value: 0.40374445188290176 and parameters: {'alpha': 1.006474609085567e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,057] Trial 3494 finished with value: 0.4037453241450621 and parameters: {'alpha': 1.0037315834976156e-07}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,093] Trial 3495 finished with value: 0.40374494692046076 and parameters: {'alpha': 1.7166880633609635e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,127] Trial 3496 finished with value: 0.4037450625579128 and parameters: {'alpha': 2.672946872061816e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 346. Best value: 0.403744:  70%|███████   | 3502/5000 [01:38<00:56, 26.31it/s]

[I 2026-06-14 00:50:11,166] Trial 3497 finished with value: 0.4037452000311146 and parameters: {'alpha': 4.1660138504332934e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,227] Trial 3498 finished with value: 0.40374455038177803 and parameters: {'alpha': 1.0066164631492028e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,271] Trial 3499 finished with value: 0.4037447483028072 and parameters: {'alpha': 1.6534743677441324e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,311] Trial 3500 finished with value: 0.4037450971700671 and parameters: {'alpha': 2.716371455998687e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,344] Trial 3501 finished with value: 0.40374461795982974 and parameters: {'alpha': 1.00269280126027e-08}. Best is trial 346 with value: 0.4037442459980544.

Best trial: 3504. Best value: 0.403744:  70%|███████   | 3508/5000 [01:38<00:54, 27.62it/s]

[I 2026-06-14 00:50:11,379] Trial 3502 finished with value: 0.40374490572232163 and parameters: {'alpha': 1.6378833849702163e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,414] Trial 3503 finished with value: 0.40374527405565175 and parameters: {'alpha': 6.251826970158732e-08}. Best is trial 346 with value: 0.4037442459980544.
[I 2026-06-14 00:50:11,446] Trial 3504 finished with value: 0.40374423498439005 and parameters: {'alpha': 1.0089586116094582e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,481] Trial 3505 finished with value: 0.40374490825776954 and parameters: {'alpha': 1.7079359712697683e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,516] Trial 3506 finished with value: 0.4037444896651129 and parameters: {'alpha': 1.0026597634735779e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,550] Trial 3507 finished with value: 0.40374521596097496 and parameters: {'alpha': 3.090216507259435e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  70%|███████   | 3514/5000 [01:39<00:52, 28.33it/s]

[I 2026-06-14 00:50:11,587] Trial 3508 finished with value: 0.40374473913854625 and parameters: {'alpha': 1.00976577300363e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,621] Trial 3509 finished with value: 0.4037450039255626 and parameters: {'alpha': 2.6853843662131382e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,656] Trial 3510 finished with value: 0.4037452982118916 and parameters: {'alpha': 4.779066297866676e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,690] Trial 3511 finished with value: 0.40374494189510096 and parameters: {'alpha': 1.7059714797555662e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,722] Trial 3512 finished with value: 0.4037448826627599 and parameters: {'alpha': 1.7302259656163884e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,756] Trial 3513 finished with value: 0.4037450071555167 and parameters: {'alpha': 2.553226251949802e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  70%|███████   | 3520/5000 [01:39<00:51, 28.78it/s]

[I 2026-06-14 00:50:11,792] Trial 3514 finished with value: 0.40374445662016495 and parameters: {'alpha': 1.0115389638370773e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,825] Trial 3515 finished with value: 0.4037452475755268 and parameters: {'alpha': 3.998957177260737e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,860] Trial 3516 finished with value: 0.4037446688072613 and parameters: {'alpha': 1.0056221503827095e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,895] Trial 3517 finished with value: 0.40374495190047505 and parameters: {'alpha': 1.827878034252611e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,929] Trial 3518 finished with value: 0.403745291152904 and parameters: {'alpha': 8.310258959749217e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:11,962] Trial 3519 finished with value: 0.40374502342277424 and parameters: {'alpha': 2.6406147475304292e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████   | 3526/5000 [01:39<00:51, 28.68it/s]

[I 2026-06-14 00:50:11,997] Trial 3520 finished with value: 0.4037447452767031 and parameters: {'alpha': 1.7400524415188047e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,031] Trial 3521 finished with value: 0.4037452422385222 and parameters: {'alpha': 4.804053978423483e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,065] Trial 3522 finished with value: 0.40374540636209255 and parameters: {'alpha': 5.764981748074505e-05}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,103] Trial 3523 finished with value: 0.4037447559540485 and parameters: {'alpha': 1.7460340931872692e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,137] Trial 3524 finished with value: 0.4037447893844566 and parameters: {'alpha': 1.7018029320016085e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,171] Trial 3525 finished with value: 0.40374499926281243 and parameters: {'alpha': 2.7830111326692436e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████   | 3532/5000 [01:39<00:50, 28.91it/s]

[I 2026-06-14 00:50:12,206] Trial 3526 finished with value: 0.4037448970145467 and parameters: {'alpha': 1.7893467876642576e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,241] Trial 3527 finished with value: 0.4037451784335931 and parameters: {'alpha': 4.1241954062065e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,276] Trial 3528 finished with value: 0.4037447453050482 and parameters: {'alpha': 1.6834715805404745e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,311] Trial 3529 finished with value: 0.4037443648687541 and parameters: {'alpha': 1.0069800548470573e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,345] Trial 3530 finished with value: 0.4037453389105483 and parameters: {'alpha': 1.6006960405195906e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,379] Trial 3531 finished with value: 0.40374509741210945 and parameters: {'alpha': 2.8072106476103484e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████   | 3538/5000 [01:39<00:50, 28.93it/s]

[I 2026-06-14 00:50:12,413] Trial 3532 finished with value: 0.4037452679957902 and parameters: {'alpha': 6.730333745473768e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,447] Trial 3533 finished with value: 0.4037449745321397 and parameters: {'alpha': 2.6838843755779043e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,481] Trial 3534 finished with value: 0.4037450515901758 and parameters: {'alpha': 2.6447911215207624e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,516] Trial 3535 finished with value: 0.4037448168105435 and parameters: {'alpha': 1.7750368788218343e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,549] Trial 3536 finished with value: 0.4037449606080458 and parameters: {'alpha': 1.6664902530779064e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,584] Trial 3537 finished with value: 0.4037454051524917 and parameters: {'alpha': 6.085840313160157e-06}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████   | 3544/5000 [01:40<00:49, 29.23it/s]

[I 2026-06-14 00:50:12,621] Trial 3538 finished with value: 0.4037452667423646 and parameters: {'alpha': 4.868778265868121e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,654] Trial 3539 finished with value: 0.40374483703999875 and parameters: {'alpha': 1.59510902287347e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,688] Trial 3540 finished with value: 0.4037451388682348 and parameters: {'alpha': 3.433251038453322e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,722] Trial 3541 finished with value: 0.40374435803088854 and parameters: {'alpha': 1.011128982692057e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,755] Trial 3542 finished with value: 0.403744701773897 and parameters: {'alpha': 1.016108965522294e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,789] Trial 3543 finished with value: 0.40374483327817395 and parameters: {'alpha': 1.7709334063874378e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████   | 3550/5000 [01:40<00:49, 29.14it/s]

[I 2026-06-14 00:50:12,824] Trial 3544 finished with value: 0.40374530341968606 and parameters: {'alpha': 8.481540090171547e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,857] Trial 3545 finished with value: 0.40374501869012946 and parameters: {'alpha': 2.7919305290719152e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,892] Trial 3546 finished with value: 0.403744877475197 and parameters: {'alpha': 1.6283336033189046e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,927] Trial 3547 finished with value: 0.4037444054372189 and parameters: {'alpha': 1.0127829136620316e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,960] Trial 3548 finished with value: 0.4037445139206879 and parameters: {'alpha': 1.0093518207161661e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:12,995] Trial 3549 finished with value: 0.40374443068043653 and parameters: {'alpha': 1.0079169827014369e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████   | 3556/5000 [01:40<00:50, 28.78it/s]

[I 2026-06-14 00:50:13,030] Trial 3550 finished with value: 0.403745181762239 and parameters: {'alpha': 4.276254799176132e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,064] Trial 3551 finished with value: 0.40374499929603264 and parameters: {'alpha': 2.677486844895383e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,101] Trial 3552 finished with value: 0.4037448590077479 and parameters: {'alpha': 1.7697694327007306e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,137] Trial 3553 finished with value: 0.4037447217235125 and parameters: {'alpha': 1.0078577920526502e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,171] Trial 3554 finished with value: 0.40374519537732434 and parameters: {'alpha': 4.0801808602100535e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,206] Trial 3555 finished with value: 0.40374470252692923 and parameters: {'alpha': 1.0025277311096045e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████   | 3562/5000 [01:40<00:49, 28.85it/s]

[I 2026-06-14 00:50:13,241] Trial 3556 finished with value: 0.4037450161284349 and parameters: {'alpha': 2.732421475449703e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,276] Trial 3557 finished with value: 0.4037448160596055 and parameters: {'alpha': 1.7080833516360793e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,311] Trial 3558 finished with value: 0.4037452810125279 and parameters: {'alpha': 6.911271336477672e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,346] Trial 3559 finished with value: 0.40585940941453885 and parameters: {'alpha': 571.4911261587104}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,380] Trial 3560 finished with value: 0.4037449616541782 and parameters: {'alpha': 2.505647087815258e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,414] Trial 3561 finished with value: 0.4037444411923925 and parameters: {'alpha': 1.0087258010529193e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████▏  | 3568/5000 [01:40<00:49, 28.85it/s]

[I 2026-06-14 00:50:13,449] Trial 3562 finished with value: 0.403745408450008 and parameters: {'alpha': 0.0029012608343548935}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,484] Trial 3563 finished with value: 0.403744846391839 and parameters: {'alpha': 1.815526679430183e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,519] Trial 3564 finished with value: 0.4037452903808316 and parameters: {'alpha': 4.695040705230525e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,554] Trial 3565 finished with value: 0.4037449906255759 and parameters: {'alpha': 2.6197229226413664e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,588] Trial 3566 finished with value: 0.40374454071120564 and parameters: {'alpha': 1.0118168229294415e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,622] Trial 3567 finished with value: 0.4037448678765949 and parameters: {'alpha': 1.7639028563565334e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  71%|███████▏  | 3574/5000 [01:41<00:48, 29.12it/s]

[I 2026-06-14 00:50:13,657] Trial 3568 finished with value: 0.40374532656314854 and parameters: {'alpha': 1.0833680246499784e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,691] Trial 3569 finished with value: 0.4037447779862605 and parameters: {'alpha': 1.8412764196050578e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,725] Trial 3570 finished with value: 0.40398394446286584 and parameters: {'alpha': 79.23020517382213}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,760] Trial 3571 finished with value: 0.4037446125010658 and parameters: {'alpha': 1.0025365331633203e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,794] Trial 3572 finished with value: 0.4037443004723943 and parameters: {'alpha': 1.007175921178703e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,828] Trial 3573 finished with value: 0.4037452433127051 and parameters: {'alpha': 3.640821882243097e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  72%|███████▏  | 3580/5000 [01:41<00:48, 29.01it/s]

[I 2026-06-14 00:50:13,863] Trial 3574 finished with value: 0.40374509308396045 and parameters: {'alpha': 2.7057283745201696e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,897] Trial 3575 finished with value: 0.403744896625924 and parameters: {'alpha': 1.728365512802824e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,932] Trial 3576 finished with value: 0.4037452866602366 and parameters: {'alpha': 4.969744569840348e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:13,968] Trial 3577 finished with value: 0.4037449567739637 and parameters: {'alpha': 1.6773763401125865e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,002] Trial 3578 finished with value: 0.40374508471725146 and parameters: {'alpha': 2.7794650543252627e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,035] Trial 3579 finished with value: 0.4037452375824557 and parameters: {'alpha': 6.105427184199408e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  72%|███████▏  | 3586/5000 [01:41<00:49, 28.75it/s]

[I 2026-06-14 00:50:14,071] Trial 3580 finished with value: 0.4037447981937567 and parameters: {'alpha': 1.7362614397280962e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,108] Trial 3581 finished with value: 0.4037449570642721 and parameters: {'alpha': 1.7121410982387327e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,143] Trial 3582 finished with value: 0.40374516646859304 and parameters: {'alpha': 3.98462696052629e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,179] Trial 3583 finished with value: 0.4037447969968714 and parameters: {'alpha': 1.6989823871060498e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,212] Trial 3584 finished with value: 0.4037450325786124 and parameters: {'alpha': 2.645773654477299e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,247] Trial 3585 finished with value: 0.40374507776171964 and parameters: {'alpha': 2.7403959820496565e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  72%|███████▏  | 3592/5000 [01:41<00:48, 28.84it/s]

[I 2026-06-14 00:50:14,282] Trial 3586 finished with value: 0.4037449539461115 and parameters: {'alpha': 1.718287312263709e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,317] Trial 3587 finished with value: 0.40374529231472256 and parameters: {'alpha': 8.898578338203527e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,352] Trial 3588 finished with value: 0.40374432216705763 and parameters: {'alpha': 1.0141297388441987e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,386] Trial 3589 finished with value: 0.40374539333842935 and parameters: {'alpha': 7.286394362688584e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,419] Trial 3590 finished with value: 0.4037452170538294 and parameters: {'alpha': 4.142532163210157e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,453] Trial 3591 finished with value: 0.4037449406502454 and parameters: {'alpha': 1.706164823337462e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  72%|███████▏  | 3598/5000 [01:42<00:49, 28.60it/s]

[I 2026-06-14 00:50:14,492] Trial 3592 finished with value: 0.40374479663219354 and parameters: {'alpha': 1.767035964884691e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,526] Trial 3593 finished with value: 0.40374462503969866 and parameters: {'alpha': 1.009350217636043e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,560] Trial 3594 finished with value: 0.4037453617290296 and parameters: {'alpha': 1.931384564655821e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,596] Trial 3595 finished with value: 0.4037452793748753 and parameters: {'alpha': 3.9365441106321535e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,632] Trial 3596 finished with value: 0.40374435935295205 and parameters: {'alpha': 1.0014656936388825e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,666] Trial 3597 finished with value: 0.4037445510439112 and parameters: {'alpha': 1.0036277107113563e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  72%|███████▏  | 3604/5000 [01:42<00:49, 28.10it/s]

[I 2026-06-14 00:50:14,701] Trial 3598 finished with value: 0.4037450469414895 and parameters: {'alpha': 2.7784885831333685e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,736] Trial 3599 finished with value: 0.4037448576445086 and parameters: {'alpha': 1.8569521289026865e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,772] Trial 3600 finished with value: 0.4037442964083287 and parameters: {'alpha': 1.0077432555797164e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,807] Trial 3601 finished with value: 0.4037453062759856 and parameters: {'alpha': 5.8047683154191416e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,846] Trial 3602 finished with value: 0.40374436959980364 and parameters: {'alpha': 1.0006989495840183e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,881] Trial 3603 finished with value: 0.4037450124052813 and parameters: {'alpha': 2.679958190774284e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  72%|███████▏  | 3610/5000 [01:42<00:49, 28.27it/s]

[I 2026-06-14 00:50:14,918] Trial 3604 finished with value: 0.40374479065726754 and parameters: {'alpha': 1.7055294484238076e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,953] Trial 3605 finished with value: 0.40374501614265434 and parameters: {'alpha': 2.7792062908410597e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:14,989] Trial 3606 finished with value: 0.4037448648661605 and parameters: {'alpha': 1.7169768072734696e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,026] Trial 3607 finished with value: 0.4037452931040336 and parameters: {'alpha': 6.531216149249234e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,060] Trial 3608 finished with value: 0.40374463385858894 and parameters: {'alpha': 1.014626985793854e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,094] Trial 3609 finished with value: 0.40374425025556293 and parameters: {'alpha': 1.0001341131642066e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  72%|███████▏  | 3616/5000 [01:42<00:49, 28.23it/s]

[I 2026-06-14 00:50:15,132] Trial 3610 finished with value: 0.40374495831117524 and parameters: {'alpha': 1.722129595513898e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,167] Trial 3611 finished with value: 0.4037451706635897 and parameters: {'alpha': 3.9068285170688763e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,201] Trial 3612 finished with value: 0.403744960643599 and parameters: {'alpha': 1.73777848407328e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,238] Trial 3613 finished with value: 0.40374511869653656 and parameters: {'alpha': 2.9317589329468767e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,272] Trial 3614 finished with value: 0.4037447433905221 and parameters: {'alpha': 1.0081691930575529e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,306] Trial 3615 finished with value: 0.40374486111274815 and parameters: {'alpha': 1.761164489432621e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  72%|███████▏  | 3622/5000 [01:42<00:48, 28.58it/s]

[I 2026-06-14 00:50:15,341] Trial 3616 finished with value: 0.40374503844010196 and parameters: {'alpha': 2.7832287259036846e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,375] Trial 3617 finished with value: 0.40374527436065927 and parameters: {'alpha': 4.3828181757478035e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,411] Trial 3618 finished with value: 0.40374530751033694 and parameters: {'alpha': 1.0371301056451929e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,446] Trial 3619 finished with value: 0.4037448740257 and parameters: {'alpha': 1.752074566506212e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,481] Trial 3620 finished with value: 0.40374432698755863 and parameters: {'alpha': 1.0011348099623664e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,515] Trial 3621 finished with value: 0.403745092425184 and parameters: {'alpha': 2.8150304404050483e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  73%|███████▎  | 3628/5000 [01:43<00:48, 28.51it/s]

[I 2026-06-14 00:50:15,551] Trial 3622 finished with value: 0.403744534095948 and parameters: {'alpha': 1.0075672537632329e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,585] Trial 3623 finished with value: 0.40374428061951706 and parameters: {'alpha': 1.007481670309385e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,619] Trial 3624 finished with value: 0.40374503490685865 and parameters: {'alpha': 2.761298762732976e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,654] Trial 3625 finished with value: 0.4037453050109504 and parameters: {'alpha': 5.088022391437034e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,689] Trial 3626 finished with value: 0.4037448278144773 and parameters: {'alpha': 1.8033007290796743e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,724] Trial 3627 finished with value: 0.403744639495423 and parameters: {'alpha': 1.0064893858860737e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  73%|███████▎  | 3634/5000 [01:43<00:47, 28.51it/s]

[I 2026-06-14 00:50:15,759] Trial 3628 finished with value: 0.4037450284008659 and parameters: {'alpha': 2.6391424461362413e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,795] Trial 3629 finished with value: 0.4037449569299191 and parameters: {'alpha': 1.8217055166914117e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,830] Trial 3630 finished with value: 0.40374526787117376 and parameters: {'alpha': 6.236738920537439e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,865] Trial 3631 finished with value: 0.4037448697331732 and parameters: {'alpha': 1.665660732543248e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,900] Trial 3632 finished with value: 0.4037452263193796 and parameters: {'alpha': 3.933954163255303e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:15,935] Trial 3633 finished with value: 0.40374479584600265 and parameters: {'alpha': 1.649075757892833e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  73%|███████▎  | 3640/5000 [01:43<00:47, 28.43it/s]

[I 2026-06-14 00:50:15,970] Trial 3634 finished with value: 0.40374505868111715 and parameters: {'alpha': 2.809243917328816e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,006] Trial 3635 finished with value: 0.40374478066024855 and parameters: {'alpha': 1.8241462906427807e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,040] Trial 3636 finished with value: 0.4037448766528643 and parameters: {'alpha': 1.6952816940359306e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,075] Trial 3637 finished with value: 0.4037452594531058 and parameters: {'alpha': 6.653894838978772e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,109] Trial 3638 finished with value: 0.4037443039386502 and parameters: {'alpha': 1.0109333919213714e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,147] Trial 3639 finished with value: 0.40374541898197847 and parameters: {'alpha': 0.01860591798573602}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  73%|███████▎  | 3646/5000 [01:43<00:48, 28.06it/s]

[I 2026-06-14 00:50:16,182] Trial 3640 finished with value: 0.4037450509205567 and parameters: {'alpha': 2.8136560789338815e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,218] Trial 3641 finished with value: 0.403744923933368 and parameters: {'alpha': 1.725570575898669e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,254] Trial 3642 finished with value: 0.4037451604778467 and parameters: {'alpha': 3.4003060282240076e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,290] Trial 3643 finished with value: 0.4037453354871261 and parameters: {'alpha': 1.1501441647600231e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,324] Trial 3644 finished with value: 0.40374485934550686 and parameters: {'alpha': 1.669251873984029e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,360] Trial 3645 finished with value: 0.40374436798080354 and parameters: {'alpha': 1.011209592616002e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  73%|███████▎  | 3652/5000 [01:43<00:47, 28.19it/s]

[I 2026-06-14 00:50:16,399] Trial 3646 finished with value: 0.4037452652430811 and parameters: {'alpha': 4.129452874427993e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,434] Trial 3647 finished with value: 0.4037448960634976 and parameters: {'alpha': 1.7210710704829537e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,467] Trial 3648 finished with value: 0.4037450483791139 and parameters: {'alpha': 2.6884386449655224e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,505] Trial 3649 finished with value: 0.4037448706456991 and parameters: {'alpha': 1.7596805607007033e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,540] Trial 3650 finished with value: 0.4037445708057025 and parameters: {'alpha': 1.0103286949518724e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,575] Trial 3651 finished with value: 0.40374532279131853 and parameters: {'alpha': 5.799236025221355e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  73%|███████▎  | 3658/5000 [01:44<00:47, 28.50it/s]

[I 2026-06-14 00:50:16,609] Trial 3652 finished with value: 0.40374540660836655 and parameters: {'alpha': 0.00019040712137031093}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,644] Trial 3653 finished with value: 0.4037450315448869 and parameters: {'alpha': 2.6079182302356877e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,679] Trial 3654 finished with value: 0.403744704586549 and parameters: {'alpha': 1.6585121302775432e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,714] Trial 3655 finished with value: 0.40374441424203983 and parameters: {'alpha': 1.0161954994458893e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,748] Trial 3656 finished with value: 0.4037452725691555 and parameters: {'alpha': 4.647184173966302e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,782] Trial 3657 finished with value: 0.4037449005051674 and parameters: {'alpha': 1.7655843719063043e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  73%|███████▎  | 3664/5000 [01:44<00:47, 28.38it/s]

[I 2026-06-14 00:50:16,820] Trial 3658 finished with value: 0.4037447108982568 and parameters: {'alpha': 1.0079940256785195e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,855] Trial 3659 finished with value: 0.40374508100486495 and parameters: {'alpha': 2.8316950368395085e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,889] Trial 3660 finished with value: 0.4037447813212277 and parameters: {'alpha': 1.7231383302197473e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,927] Trial 3661 finished with value: 0.4037452161465407 and parameters: {'alpha': 3.85023189788016e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,961] Trial 3662 finished with value: 0.4037449294591372 and parameters: {'alpha': 1.7223475993720214e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:16,995] Trial 3663 finished with value: 0.40374458221967247 and parameters: {'alpha': 1.0006038604989682e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  73%|███████▎  | 3670/5000 [01:44<00:47, 28.12it/s]

[I 2026-06-14 00:50:17,030] Trial 3664 finished with value: 0.4037453245860538 and parameters: {'alpha': 1.0430625498622624e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,065] Trial 3665 finished with value: 0.4037445631915626 and parameters: {'alpha': 1.0048995057252381e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,101] Trial 3666 finished with value: 0.4037449917391967 and parameters: {'alpha': 2.6303637453385425e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,136] Trial 3667 finished with value: 0.4037450205971789 and parameters: {'alpha': 2.7694055911734205e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,173] Trial 3668 finished with value: 0.40374529851594426 and parameters: {'alpha': 6.543774256577747e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,209] Trial 3669 finished with value: 0.4037449611058998 and parameters: {'alpha': 2.6705826519992545e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▎  | 3676/5000 [01:44<00:46, 28.28it/s]

[I 2026-06-14 00:50:17,246] Trial 3670 finished with value: 0.4037449445102846 and parameters: {'alpha': 1.728665730216756e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,281] Trial 3671 finished with value: 0.4037443942760854 and parameters: {'alpha': 1.0066691300966375e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,315] Trial 3672 finished with value: 0.40374528785069075 and parameters: {'alpha': 4.67985059617058e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,350] Trial 3673 finished with value: 0.4037449121049804 and parameters: {'alpha': 1.742497630493543e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,385] Trial 3674 finished with value: 0.4037445554882515 and parameters: {'alpha': 1.0137351364377797e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,420] Trial 3675 finished with value: 0.40374478915529605 and parameters: {'alpha': 1.7778580980847614e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▎  | 3682/5000 [01:44<00:46, 28.22it/s]

[I 2026-06-14 00:50:17,457] Trial 3676 finished with value: 0.4037442966344727 and parameters: {'alpha': 1.0047584710668026e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,494] Trial 3677 finished with value: 0.40374523064540485 and parameters: {'alpha': 3.513908182220487e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,528] Trial 3678 finished with value: 0.4037449640225095 and parameters: {'alpha': 1.718543546681549e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,564] Trial 3679 finished with value: 0.40374516506712527 and parameters: {'alpha': 3.8547315571046246e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,600] Trial 3680 finished with value: 0.40374495137169547 and parameters: {'alpha': 1.7397236210302263e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,635] Trial 3681 finished with value: 0.40374510389381285 and parameters: {'alpha': 2.7410347991970502e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▍  | 3688/5000 [01:45<00:46, 28.13it/s]

[I 2026-06-14 00:50:17,671] Trial 3682 finished with value: 0.4037453608270673 and parameters: {'alpha': 2.1966322728862616e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,709] Trial 3683 finished with value: 0.40374524402994244 and parameters: {'alpha': 5.188782177891834e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,743] Trial 3684 finished with value: 0.4037448640520827 and parameters: {'alpha': 1.771586555634008e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,780] Trial 3685 finished with value: 0.40374466832290823 and parameters: {'alpha': 1.0028944978147363e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,815] Trial 3686 finished with value: 0.40374502354929165 and parameters: {'alpha': 2.7633805231235483e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,848] Trial 3687 finished with value: 0.40374434185358665 and parameters: {'alpha': 1.0001404952400226e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▍  | 3694/5000 [01:45<00:46, 28.34it/s]

[I 2026-06-14 00:50:17,885] Trial 3688 finished with value: 0.4037449074477281 and parameters: {'alpha': 1.739452684893426e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,920] Trial 3689 finished with value: 0.40374526802891675 and parameters: {'alpha': 7.330743698350481e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,955] Trial 3690 finished with value: 0.40374488969599154 and parameters: {'alpha': 1.7038252666891344e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:17,991] Trial 3691 finished with value: 0.4037452364822821 and parameters: {'alpha': 4.103928122535982e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,025] Trial 3692 finished with value: 0.40374454025195505 and parameters: {'alpha': 1.0029289903759943e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,059] Trial 3693 finished with value: 0.4037450419267727 and parameters: {'alpha': 2.7736418413661502e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▍  | 3700/5000 [01:45<00:46, 28.13it/s]

[I 2026-06-14 00:50:18,095] Trial 3694 finished with value: 0.4037449506478137 and parameters: {'alpha': 1.709593573430575e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,130] Trial 3695 finished with value: 0.40374484600546123 and parameters: {'alpha': 1.6939417412314715e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,166] Trial 3696 finished with value: 0.40374448179902217 and parameters: {'alpha': 1.0034068872882946e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,204] Trial 3697 finished with value: 0.40374499294054234 and parameters: {'alpha': 2.7174770564692497e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,239] Trial 3698 finished with value: 0.40374526079189677 and parameters: {'alpha': 8.02045306689313e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,275] Trial 3699 finished with value: 0.4037454699312303 and parameters: {'alpha': 0.09289318785233179}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▍  | 3706/5000 [01:45<00:45, 28.21it/s]

[I 2026-06-14 00:50:18,311] Trial 3700 finished with value: 0.40374516139463906 and parameters: {'alpha': 3.892570423019307e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,347] Trial 3701 finished with value: 0.4037447890259146 and parameters: {'alpha': 1.7544162563838526e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,382] Trial 3702 finished with value: 0.4037447548163088 and parameters: {'alpha': 1.769807619280654e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,418] Trial 3703 finished with value: 0.40374524528205946 and parameters: {'alpha': 4.0731349382972465e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,453] Trial 3704 finished with value: 0.40374504777429143 and parameters: {'alpha': 2.643303718071757e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,487] Trial 3705 finished with value: 0.40374475682140337 and parameters: {'alpha': 1.7462995739083244e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▍  | 3712/5000 [01:46<00:45, 28.19it/s]

[I 2026-06-14 00:50:18,524] Trial 3706 finished with value: 0.4037447653068881 and parameters: {'alpha': 1.701602094598337e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,560] Trial 3707 finished with value: 0.4037453232879464 and parameters: {'alpha': 1.3056863718828528e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,594] Trial 3708 finished with value: 0.403745310226653 and parameters: {'alpha': 5.800705283863108e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,628] Trial 3709 finished with value: 0.4037450850776293 and parameters: {'alpha': 2.7977553222158872e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,664] Trial 3710 finished with value: 0.4037454377567473 and parameters: {'alpha': 0.046300268083325595}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,699] Trial 3711 finished with value: 0.40374498695914407 and parameters: {'alpha': 2.6164546411454215e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▍  | 3718/5000 [01:46<00:45, 28.06it/s]

[I 2026-06-14 00:50:18,735] Trial 3712 finished with value: 0.4037449322248108 and parameters: {'alpha': 1.6974958342305345e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,774] Trial 3713 finished with value: 0.4037448535236218 and parameters: {'alpha': 1.7264589232367032e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,811] Trial 3714 finished with value: 0.40374526985662024 and parameters: {'alpha': 4.455736890151806e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,848] Trial 3715 finished with value: 0.40374457318325696 and parameters: {'alpha': 1.0212048060736591e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,881] Trial 3716 finished with value: 0.40374509094406513 and parameters: {'alpha': 2.7216468439147164e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,915] Trial 3717 finished with value: 0.40374476060925896 and parameters: {'alpha': 1.708967267555951e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  74%|███████▍  | 3724/5000 [01:46<00:44, 28.43it/s]

[I 2026-06-14 00:50:18,952] Trial 3718 finished with value: 0.40374433993174774 and parameters: {'alpha': 1.0202481156913759e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:18,989] Trial 3719 finished with value: 0.4037442986194205 and parameters: {'alpha': 1.0127691790635104e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,023] Trial 3720 finished with value: 0.4037452722384134 and parameters: {'alpha': 6.462029226026463e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,058] Trial 3721 finished with value: 0.4037450907657178 and parameters: {'alpha': 2.7835828289342637e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,091] Trial 3722 finished with value: 0.4037448149371547 and parameters: {'alpha': 1.642479869071308e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,124] Trial 3723 finished with value: 0.40374488196140573 and parameters: {'alpha': 1.724002074147055e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  75%|███████▍  | 3730/5000 [01:46<00:45, 28.12it/s]

[I 2026-06-14 00:50:19,160] Trial 3724 finished with value: 0.4037452177202754 and parameters: {'alpha': 3.739090016945008e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,199] Trial 3725 finished with value: 0.40374472194776345 and parameters: {'alpha': 1.015422456142726e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,234] Trial 3726 finished with value: 0.4037449471027678 and parameters: {'alpha': 1.6712753870436904e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,271] Trial 3727 finished with value: 0.4037444150588114 and parameters: {'alpha': 1.0043952277653886e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,306] Trial 3728 finished with value: 0.4037450275920139 and parameters: {'alpha': 2.70318225683558e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,340] Trial 3729 finished with value: 0.4037452608912893 and parameters: {'alpha': 6.886030248737081e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  75%|███████▍  | 3736/5000 [01:46<00:45, 28.06it/s]

[I 2026-06-14 00:50:19,377] Trial 3730 finished with value: 0.40374499284259985 and parameters: {'alpha': 2.8290258196492463e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,412] Trial 3731 finished with value: 0.4037448629261307 and parameters: {'alpha': 1.6166719133856347e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,447] Trial 3732 finished with value: 0.40374526699964136 and parameters: {'alpha': 4.6985628210526064e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,483] Trial 3733 finished with value: 0.40374471651563815 and parameters: {'alpha': 1.6836426686245235e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,519] Trial 3734 finished with value: 0.4037449489777257 and parameters: {'alpha': 1.672304658462666e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,554] Trial 3735 finished with value: 0.40374460537384527 and parameters: {'alpha': 1.0034154653674485e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  75%|███████▍  | 3742/5000 [01:47<00:44, 28.19it/s]

[I 2026-06-14 00:50:19,591] Trial 3736 finished with value: 0.4037451090219263 and parameters: {'alpha': 2.91180535311676e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,626] Trial 3737 finished with value: 0.4037452679890605 and parameters: {'alpha': 4.1854011987244275e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,660] Trial 3738 finished with value: 0.40374480797886864 and parameters: {'alpha': 1.7990567338502225e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,696] Trial 3739 finished with value: 0.40374471806969753 and parameters: {'alpha': 1.6945052091765386e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,730] Trial 3740 finished with value: 0.40374531584983847 and parameters: {'alpha': 1.1985552057271793e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,765] Trial 3741 finished with value: 0.40374448751235215 and parameters: {'alpha': 1.0057524448220628e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  75%|███████▍  | 3748/5000 [01:47<00:44, 28.42it/s]

[I 2026-06-14 00:50:19,802] Trial 3742 finished with value: 0.40374510629539934 and parameters: {'alpha': 2.8022148157253108e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,836] Trial 3743 finished with value: 0.40374468269186164 and parameters: {'alpha': 1.0213661836088482e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,870] Trial 3744 finished with value: 0.4037450646051239 and parameters: {'alpha': 2.742822554689236e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,906] Trial 3745 finished with value: 0.40374523885720914 and parameters: {'alpha': 6.70969173929898e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,941] Trial 3746 finished with value: 0.40374500073394926 and parameters: {'alpha': 1.834192750202125e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:19,975] Trial 3747 finished with value: 0.4037448453533337 and parameters: {'alpha': 1.7336441840377285e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  75%|███████▌  | 3754/5000 [01:47<00:43, 28.35it/s]

[I 2026-06-14 00:50:20,012] Trial 3748 finished with value: 0.4037445954828664 and parameters: {'alpha': 1.0103888289020762e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,047] Trial 3749 finished with value: 0.4037445498154473 and parameters: {'alpha': 1.0206192379422432e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,081] Trial 3750 finished with value: 0.40374540140286547 and parameters: {'alpha': 1.5089273580328371e-06}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,117] Trial 3751 finished with value: 0.4037443453520584 and parameters: {'alpha': 1.0012029119896306e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,153] Trial 3752 finished with value: 0.40374525972675895 and parameters: {'alpha': 3.800852086761006e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,186] Trial 3753 finished with value: 0.4217628154875597 and parameters: {'alpha': 2377.1062293619834}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  75%|███████▌  | 3760/5000 [01:47<00:43, 28.19it/s]

[I 2026-06-14 00:50:20,227] Trial 3754 finished with value: 0.403745055457955 and parameters: {'alpha': 2.800308300410073e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,263] Trial 3755 finished with value: 0.40374455254387875 and parameters: {'alpha': 1.0146164807994846e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,297] Trial 3756 finished with value: 0.40374427649084554 and parameters: {'alpha': 1.0079646863243763e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,333] Trial 3757 finished with value: 0.4037452139251531 and parameters: {'alpha': 4.271560269521986e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,367] Trial 3758 finished with value: 0.40374496343549143 and parameters: {'alpha': 1.710377285663945e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,402] Trial 3759 finished with value: 0.4037450600721242 and parameters: {'alpha': 2.7041722396910506e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  75%|███████▌  | 3766/5000 [01:47<00:43, 28.18it/s]

[I 2026-06-14 00:50:20,437] Trial 3760 finished with value: 0.4037453235281348 and parameters: {'alpha': 9.437093649382403e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,474] Trial 3761 finished with value: 0.40374479273904895 and parameters: {'alpha': 1.7292581268060636e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,509] Trial 3762 finished with value: 0.40374526348610273 and parameters: {'alpha': 4.203666063077403e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,544] Trial 3763 finished with value: 0.40374493343761647 and parameters: {'alpha': 1.760803810039988e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,579] Trial 3764 finished with value: 0.40374504548466134 and parameters: {'alpha': 2.7532406628855453e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,615] Trial 3765 finished with value: 0.4037445837413486 and parameters: {'alpha': 1.0206698632687961e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  75%|███████▌  | 3772/5000 [01:48<00:43, 28.17it/s]

[I 2026-06-14 00:50:20,652] Trial 3766 finished with value: 0.40374531714656675 and parameters: {'alpha': 5.7051024885780456e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,687] Trial 3767 finished with value: 0.4037450766755533 and parameters: {'alpha': 2.8447886187833107e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,723] Trial 3768 finished with value: 0.40374452801838273 and parameters: {'alpha': 1.0122945646306667e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,759] Trial 3769 finished with value: 0.40374489454860524 and parameters: {'alpha': 1.7256149485637202e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,794] Trial 3770 finished with value: 0.40374471448898425 and parameters: {'alpha': 1.0124475788063919e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,829] Trial 3771 finished with value: 0.40374499530206276 and parameters: {'alpha': 2.6092579046700588e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▌  | 3778/5000 [01:48<00:43, 28.41it/s]

[I 2026-06-14 00:50:20,866] Trial 3772 finished with value: 0.4037449483492207 and parameters: {'alpha': 1.728886527146361e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,901] Trial 3773 finished with value: 0.40374527025562285 and parameters: {'alpha': 4.563527084037962e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,935] Trial 3774 finished with value: 0.40374482438078896 and parameters: {'alpha': 1.689932645136304e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:20,971] Trial 3775 finished with value: 0.40374503054116123 and parameters: {'alpha': 2.7235033005170864e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,006] Trial 3776 finished with value: 0.4037449264210741 and parameters: {'alpha': 1.659199573428108e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,039] Trial 3777 finished with value: 0.4037445142364179 and parameters: {'alpha': 1.0032252481882984e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▌  | 3782/5000 [01:48<00:47, 25.88it/s]

[I 2026-06-14 00:50:21,075] Trial 3778 finished with value: 0.40374523960159453 and parameters: {'alpha': 6.398302324448354e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,118] Trial 3779 finished with value: 0.4037450859731989 and parameters: {'alpha': 2.736297648531935e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,177] Trial 3780 finished with value: 0.403744880644563 and parameters: {'alpha': 1.7369057105000302e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,222] Trial 3781 finished with value: 0.40374430969363956 and parameters: {'alpha': 1.007140256508819e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,263] Trial 3782 finished with value: 0.4037451900291375 and parameters: {'alpha': 4.10856567149276e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▌  | 3788/5000 [01:48<00:46, 26.33it/s]

[I 2026-06-14 00:50:21,298] Trial 3783 finished with value: 0.4037447380471792 and parameters: {'alpha': 1.6996373532406105e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,334] Trial 3784 finished with value: 0.40374504770577324 and parameters: {'alpha': 2.604612254227042e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,369] Trial 3785 finished with value: 0.4037453333523322 and parameters: {'alpha': 1.0419381853557907e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,404] Trial 3786 finished with value: 0.40374487953258875 and parameters: {'alpha': 1.7438896055120184e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,441] Trial 3787 finished with value: 0.4037452274982221 and parameters: {'alpha': 4.2353618778156305e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,478] Trial 3788 finished with value: 0.4037447509807386 and parameters: {'alpha': 1.7352348511523475e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▌  | 3794/5000 [01:49<00:44, 26.92it/s]

[I 2026-06-14 00:50:21,514] Trial 3789 finished with value: 0.4037450693349819 and parameters: {'alpha': 2.7209300745746645e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,550] Trial 3790 finished with value: 0.4037448908419131 and parameters: {'alpha': 1.7101359889233946e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,586] Trial 3791 finished with value: 0.40374486429415957 and parameters: {'alpha': 1.6830105618322193e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,622] Trial 3792 finished with value: 0.40374457954728543 and parameters: {'alpha': 1.0257615648133446e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,659] Trial 3793 finished with value: 0.4037454068317903 and parameters: {'alpha': 0.0004970306530468724}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,694] Trial 3794 finished with value: 0.403745278306588 and parameters: {'alpha': 6.204000464417857e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▌  | 3800/5000 [01:49<00:43, 27.31it/s]

[I 2026-06-14 00:50:21,730] Trial 3795 finished with value: 0.4037450857092062 and parameters: {'alpha': 2.7746681881168932e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,768] Trial 3796 finished with value: 0.4037448055704237 and parameters: {'alpha': 1.719325509904494e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,804] Trial 3797 finished with value: 0.4037452732784486 and parameters: {'alpha': 3.891690014090355e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,838] Trial 3798 finished with value: 0.4037453545991661 and parameters: {'alpha': 1.8393604451386343e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,875] Trial 3799 finished with value: 0.4037445715410222 and parameters: {'alpha': 1.006954559140019e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,910] Trial 3800 finished with value: 0.4037450338483194 and parameters: {'alpha': 2.571062081722543e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▌  | 3806/5000 [01:49<00:42, 27.79it/s]

[I 2026-06-14 00:50:21,945] Trial 3801 finished with value: 0.40374472298784175 and parameters: {'alpha': 1.660879545067786e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:21,982] Trial 3802 finished with value: 0.4037452870371838 and parameters: {'alpha': 6.2196731133115e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,016] Trial 3803 finished with value: 0.4037443322959471 and parameters: {'alpha': 1.0034415923363206e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,052] Trial 3804 finished with value: 0.4037447838611698 and parameters: {'alpha': 1.6778938689778472e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,090] Trial 3805 finished with value: 0.40374526158377844 and parameters: {'alpha': 3.862545812776813e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,127] Trial 3806 finished with value: 0.40374457560129534 and parameters: {'alpha': 1.0127701659734794e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▌  | 3812/5000 [01:49<00:43, 27.52it/s]

[I 2026-06-14 00:50:22,161] Trial 3807 finished with value: 0.4037444075139408 and parameters: {'alpha': 1.0181569986350595e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,198] Trial 3808 finished with value: 0.40374437552868103 and parameters: {'alpha': 1.0034465264096384e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,235] Trial 3809 finished with value: 0.40374505398638766 and parameters: {'alpha': 2.6319658032899475e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,272] Trial 3810 finished with value: 0.40374501529093626 and parameters: {'alpha': 2.5354075594904744e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,310] Trial 3811 finished with value: 0.4037444177640005 and parameters: {'alpha': 1.001983193626384e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,345] Trial 3812 finished with value: 0.40374526585324017 and parameters: {'alpha': 4.3118447883034636e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▋  | 3818/5000 [01:49<00:42, 27.61it/s]

[I 2026-06-14 00:50:22,380] Trial 3813 finished with value: 0.4037452990998266 and parameters: {'alpha': 9.375134204496048e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,418] Trial 3814 finished with value: 0.4037449876934382 and parameters: {'alpha': 1.770487371708816e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,453] Trial 3815 finished with value: 0.40374500712441075 and parameters: {'alpha': 2.8310432314789904e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,488] Trial 3816 finished with value: 0.4037447638874122 and parameters: {'alpha': 1.734273488396092e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,525] Trial 3817 finished with value: 0.40376165831824923 and parameters: {'alpha': 9.035572379312262}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,560] Trial 3818 finished with value: 0.40374430816216167 and parameters: {'alpha': 1.0023894069117793e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  76%|███████▋  | 3824/5000 [01:50<00:42, 27.87it/s]

[I 2026-06-14 00:50:22,596] Trial 3819 finished with value: 0.4037452974880781 and parameters: {'alpha': 4.1239905892758966e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,632] Trial 3820 finished with value: 0.4037448226345433 and parameters: {'alpha': 1.709895583161902e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,667] Trial 3821 finished with value: 0.4037450505705902 and parameters: {'alpha': 2.60910828162179e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,701] Trial 3822 finished with value: 0.40374501901701554 and parameters: {'alpha': 2.7049694038171132e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,739] Trial 3823 finished with value: 0.4037446164492233 and parameters: {'alpha': 1.016644951239336e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,774] Trial 3824 finished with value: 0.4037443542153832 and parameters: {'alpha': 1.0117663734454217e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  77%|███████▋  | 3830/5000 [01:50<00:41, 27.86it/s]

[I 2026-06-14 00:50:22,810] Trial 3825 finished with value: 0.4037452670246115 and parameters: {'alpha': 6.457405293614984e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,846] Trial 3826 finished with value: 0.40374485961329953 and parameters: {'alpha': 1.848346241756636e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,882] Trial 3827 finished with value: 0.403744880293841 and parameters: {'alpha': 1.714890832761681e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,918] Trial 3828 finished with value: 0.4037452283748489 and parameters: {'alpha': 4.646505367732312e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,953] Trial 3829 finished with value: 0.4037447562153562 and parameters: {'alpha': 1.695569081277037e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:22,989] Trial 3830 finished with value: 0.4037450591671415 and parameters: {'alpha': 2.7151791868850958e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  77%|███████▋  | 3836/5000 [01:50<00:41, 27.88it/s]

[I 2026-06-14 00:50:23,023] Trial 3831 finished with value: 0.40374471281331814 and parameters: {'alpha': 1.0088044630580849e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,061] Trial 3832 finished with value: 0.40374497560940265 and parameters: {'alpha': 1.7472577866219747e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,097] Trial 3833 finished with value: 0.40374523347706687 and parameters: {'alpha': 3.882081658332555e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,132] Trial 3834 finished with value: 0.4037448914056146 and parameters: {'alpha': 1.7338281697065393e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,168] Trial 3835 finished with value: 0.4037443010586284 and parameters: {'alpha': 1.0002282457116039e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,203] Trial 3836 finished with value: 0.40374526859016374 and parameters: {'alpha': 7.308227520802897e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  77%|███████▋  | 3842/5000 [01:50<00:41, 27.61it/s]

[I 2026-06-14 00:50:23,242] Trial 3837 finished with value: 0.4037442794472723 and parameters: {'alpha': 1.0030878451814352e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,280] Trial 3838 finished with value: 0.4037450446020091 and parameters: {'alpha': 2.5496419505521747e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,315] Trial 3839 finished with value: 0.403745093156486 and parameters: {'alpha': 2.848230014366382e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,351] Trial 3840 finished with value: 0.40374482387703103 and parameters: {'alpha': 1.7076124931854436e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,388] Trial 3841 finished with value: 0.40374527042811537 and parameters: {'alpha': 4.519188898935938e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,422] Trial 3842 finished with value: 0.4037449151106486 and parameters: {'alpha': 1.7216716969089968e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  77%|███████▋  | 3848/5000 [01:50<00:41, 27.76it/s]

[I 2026-06-14 00:50:23,458] Trial 3843 finished with value: 0.4037450694340284 and parameters: {'alpha': 2.7183348974033813e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,495] Trial 3844 finished with value: 0.40374486487440314 and parameters: {'alpha': 1.7439989315892093e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,531] Trial 3845 finished with value: 0.4037452694743559 and parameters: {'alpha': 3.9201640497138765e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,566] Trial 3846 finished with value: 0.40374495220534273 and parameters: {'alpha': 1.7892996093038793e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,602] Trial 3847 finished with value: 0.4037453183357096 and parameters: {'alpha': 9.881072593522901e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,638] Trial 3848 finished with value: 0.40374506941978966 and parameters: {'alpha': 2.6364044653632288e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  77%|███████▋  | 3854/5000 [01:51<00:41, 27.86it/s]

[I 2026-06-14 00:50:23,673] Trial 3849 finished with value: 0.4037448447932079 and parameters: {'alpha': 1.691177408208955e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,711] Trial 3850 finished with value: 0.40374481138882923 and parameters: {'alpha': 1.63487532736355e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,747] Trial 3851 finished with value: 0.40374450986326094 and parameters: {'alpha': 1.0152044859606347e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,781] Trial 3852 finished with value: 0.40374529516453533 and parameters: {'alpha': 5.3009229368829914e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,817] Trial 3853 finished with value: 0.40374519039677176 and parameters: {'alpha': 3.7657719129953984e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,852] Trial 3854 finished with value: 0.40374485096362744 and parameters: {'alpha': 1.686288218289897e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  77%|███████▋  | 3860/5000 [01:51<00:40, 28.05it/s]

[I 2026-06-14 00:50:23,887] Trial 3855 finished with value: 0.40374504875884426 and parameters: {'alpha': 2.7025489446914974e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,924] Trial 3856 finished with value: 0.4037447769169341 and parameters: {'alpha': 1.6850611311523844e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,958] Trial 3857 finished with value: 0.40374427553142067 and parameters: {'alpha': 1.0037241713584645e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:23,993] Trial 3858 finished with value: 0.4037453217813425 and parameters: {'alpha': 5.915980939781508e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,030] Trial 3859 finished with value: 0.4037448838202534 and parameters: {'alpha': 1.714906049377068e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,065] Trial 3860 finished with value: 0.4037442853489928 and parameters: {'alpha': 1.002922101332826e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  77%|███████▋  | 3866/5000 [01:51<00:40, 28.00it/s]

[I 2026-06-14 00:50:24,102] Trial 3861 finished with value: 0.4037453820319629 and parameters: {'alpha': 3.469494797041629e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,139] Trial 3862 finished with value: 0.4037450684802889 and parameters: {'alpha': 2.7567885802011067e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,174] Trial 3863 finished with value: 0.40374532573895083 and parameters: {'alpha': 1.4215010932810733e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,209] Trial 3864 finished with value: 0.4037442953613506 and parameters: {'alpha': 1.0224267681976982e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,245] Trial 3865 finished with value: 0.4037449991566703 and parameters: {'alpha': 2.7281980464967678e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,284] Trial 3866 finished with value: 0.4037444874758755 and parameters: {'alpha': 1.0250394997410644e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  77%|███████▋  | 3872/5000 [01:51<00:40, 27.76it/s]

[I 2026-06-14 00:50:24,321] Trial 3867 finished with value: 0.40374476558097777 and parameters: {'alpha': 1.678284163786669e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,358] Trial 3868 finished with value: 0.40374432448242864 and parameters: {'alpha': 1.0085439844915123e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,392] Trial 3869 finished with value: 0.40374437263548874 and parameters: {'alpha': 1.0117802760723175e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,427] Trial 3870 finished with value: 0.40374529619045946 and parameters: {'alpha': 4.2130367239383504e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,464] Trial 3871 finished with value: 0.40374527151286926 and parameters: {'alpha': 7.667429283326787e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,499] Trial 3872 finished with value: 0.4037444967580968 and parameters: {'alpha': 1.006398730166342e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  78%|███████▊  | 3878/5000 [01:52<00:40, 27.95it/s]

[I 2026-06-14 00:50:24,536] Trial 3873 finished with value: 0.40374503111972926 and parameters: {'alpha': 2.891170499915491e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,572] Trial 3874 finished with value: 0.4037450055595652 and parameters: {'alpha': 2.502054252497336e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,607] Trial 3875 finished with value: 0.40374483365261554 and parameters: {'alpha': 1.8513575375750343e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,642] Trial 3876 finished with value: 0.40374521426000437 and parameters: {'alpha': 4.0472854439401704e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,679] Trial 3877 finished with value: 0.4037446692936766 and parameters: {'alpha': 1.0042135808400196e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,715] Trial 3878 finished with value: 0.4037448993658126 and parameters: {'alpha': 1.7998380396534923e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  78%|███████▊  | 3884/5000 [01:52<00:40, 27.82it/s]

[I 2026-06-14 00:50:24,751] Trial 3879 finished with value: 0.40374450942882695 and parameters: {'alpha': 1.0142567801403641e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,788] Trial 3880 finished with value: 0.4037448394572054 and parameters: {'alpha': 1.723987411504559e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,824] Trial 3881 finished with value: 0.4037452044263661 and parameters: {'alpha': 3.874612884629409e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,859] Trial 3882 finished with value: 0.4037450381856758 and parameters: {'alpha': 2.6643536976601398e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,895] Trial 3883 finished with value: 0.4037453093555352 and parameters: {'alpha': 8.508817377144842e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:24,931] Trial 3884 finished with value: 0.40413695943424793 and parameters: {'alpha': 135.43160808216427}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  78%|███████▊  | 3890/5000 [01:52<00:39, 27.82it/s]

[I 2026-06-14 00:50:24,966] Trial 3885 finished with value: 0.4037449310185089 and parameters: {'alpha': 1.855672476510279e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,004] Trial 3886 finished with value: 0.40374525438578923 and parameters: {'alpha': 4.478990481103408e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,039] Trial 3887 finished with value: 0.4037444019172311 and parameters: {'alpha': 1.0076864982375572e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,075] Trial 3888 finished with value: 0.4037449128469105 and parameters: {'alpha': 1.758575633547976e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,111] Trial 3889 finished with value: 0.4037450276949091 and parameters: {'alpha': 2.6925294471783222e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,146] Trial 3890 finished with value: 0.40374496154261685 and parameters: {'alpha': 2.524886235977734e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  78%|███████▊  | 3896/5000 [01:52<00:39, 27.69it/s]

[I 2026-06-14 00:50:25,181] Trial 3891 finished with value: 0.40374447606589736 and parameters: {'alpha': 1.0110870986683304e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,218] Trial 3892 finished with value: 0.40374473475234446 and parameters: {'alpha': 1.689842614843556e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,254] Trial 3893 finished with value: 0.40374484029667834 and parameters: {'alpha': 1.6951339581380075e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,292] Trial 3894 finished with value: 0.40374436069355063 and parameters: {'alpha': 1.0043171524418239e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,329] Trial 3895 finished with value: 0.4037442731550675 and parameters: {'alpha': 1.0071759043962937e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,365] Trial 3896 finished with value: 0.40374436690740007 and parameters: {'alpha': 1.0064005458151164e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  78%|███████▊  | 3902/5000 [01:52<00:39, 27.52it/s]

[I 2026-06-14 00:50:25,402] Trial 3897 finished with value: 0.40374524784207877 and parameters: {'alpha': 4.2016859546335566e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,440] Trial 3898 finished with value: 0.4037452619294147 and parameters: {'alpha': 5.5997271416100375e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,476] Trial 3899 finished with value: 0.44939044846236553 and parameters: {'alpha': 5130.758611784966}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,511] Trial 3900 finished with value: 0.4037449633867174 and parameters: {'alpha': 2.552099666110949e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,549] Trial 3901 finished with value: 0.40374483561637137 and parameters: {'alpha': 1.7317935479753657e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,585] Trial 3902 finished with value: 0.4037446731285479 and parameters: {'alpha': 1.0139515091963768e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  78%|███████▊  | 3908/5000 [01:53<00:39, 27.35it/s]

[I 2026-06-14 00:50:25,623] Trial 3903 finished with value: 0.40374504074645984 and parameters: {'alpha': 2.8711031081833807e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,661] Trial 3904 finished with value: 0.4037447817871748 and parameters: {'alpha': 1.7337034708030036e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,697] Trial 3905 finished with value: 0.4037452632439069 and parameters: {'alpha': 6.71011751227912e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,734] Trial 3906 finished with value: 0.40374503642182274 and parameters: {'alpha': 2.754629779673126e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,769] Trial 3907 finished with value: 0.40374520020944143 and parameters: {'alpha': 4.2547915695512174e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,803] Trial 3908 finished with value: 0.40374490939173063 and parameters: {'alpha': 1.730321952215549e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  78%|███████▊  | 3914/5000 [01:53<00:38, 27.87it/s]

[I 2026-06-14 00:50:25,838] Trial 3909 finished with value: 0.4037447746666471 and parameters: {'alpha': 1.744110025765808e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,875] Trial 3910 finished with value: 0.4037453157666512 and parameters: {'alpha': 1.1533473200017019e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,910] Trial 3911 finished with value: 0.40374506195000925 and parameters: {'alpha': 2.7987187225687546e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,945] Trial 3912 finished with value: 0.4037449459502163 and parameters: {'alpha': 1.696647656635776e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:25,981] Trial 3913 finished with value: 0.4037447976041335 and parameters: {'alpha': 1.7131692988491726e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,016] Trial 3914 finished with value: 0.40374519814231197 and parameters: {'alpha': 4.3016337719648395e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  78%|███████▊  | 3920/5000 [01:53<00:39, 27.54it/s]

[I 2026-06-14 00:50:26,053] Trial 3915 finished with value: 0.40374476713269086 and parameters: {'alpha': 1.706889694918934e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,091] Trial 3916 finished with value: 0.4037450689983357 and parameters: {'alpha': 2.7978789697672442e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,126] Trial 3917 finished with value: 0.40374529107077345 and parameters: {'alpha': 6.266580347817968e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,162] Trial 3918 finished with value: 0.4037449233377046 and parameters: {'alpha': 1.7763776305952487e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,200] Trial 3919 finished with value: 0.4037445848029951 and parameters: {'alpha': 1.0189938896775744e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,235] Trial 3920 finished with value: 0.4037452319996036 and parameters: {'alpha': 3.97541034405245e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▊  | 3926/5000 [01:53<00:39, 27.32it/s]

[I 2026-06-14 00:50:26,271] Trial 3921 finished with value: 0.40374472393460314 and parameters: {'alpha': 1.6597820861388683e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,313] Trial 3922 finished with value: 0.4037447639738102 and parameters: {'alpha': 1.0177431407210976e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,348] Trial 3923 finished with value: 0.4037450671019764 and parameters: {'alpha': 2.708098068218006e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,384] Trial 3924 finished with value: 0.4037446622366181 and parameters: {'alpha': 1.013861334463016e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,421] Trial 3925 finished with value: 0.40374502039476023 and parameters: {'alpha': 2.6793100329787308e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,456] Trial 3926 finished with value: 0.4037444587291958 and parameters: {'alpha': 1.0117261749840485e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▊  | 3932/5000 [01:54<00:38, 27.49it/s]

[I 2026-06-14 00:50:26,492] Trial 3927 finished with value: 0.40374528083952976 and parameters: {'alpha': 6.298210948461775e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,530] Trial 3928 finished with value: 0.4037449229055705 and parameters: {'alpha': 1.8005505455020753e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,565] Trial 3929 finished with value: 0.4037450025745721 and parameters: {'alpha': 2.6620083259230042e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,601] Trial 3930 finished with value: 0.40374525214289003 and parameters: {'alpha': 3.7437358963588064e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,638] Trial 3931 finished with value: 0.40374450644041077 and parameters: {'alpha': 1.0050398846864571e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,673] Trial 3932 finished with value: 0.40374466098421746 and parameters: {'alpha': 1.005865166085943e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▉  | 3938/5000 [01:54<00:38, 27.47it/s]

[I 2026-06-14 00:50:26,711] Trial 3933 finished with value: 0.4037453351729897 and parameters: {'alpha': 1.5976054854673274e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,748] Trial 3934 finished with value: 0.4037449549470505 and parameters: {'alpha': 1.856172306985692e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,783] Trial 3935 finished with value: 0.40374487451983887 and parameters: {'alpha': 1.7222176268992882e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,820] Trial 3936 finished with value: 0.4037446045786406 and parameters: {'alpha': 1.0138371580686061e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,856] Trial 3937 finished with value: 0.40374522194532914 and parameters: {'alpha': 3.7711163077420256e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,892] Trial 3938 finished with value: 0.4037452826514422 and parameters: {'alpha': 8.013509490073631e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▉  | 3944/5000 [01:54<00:38, 27.67it/s]

[I 2026-06-14 00:50:26,927] Trial 3939 finished with value: 0.4037449452657011 and parameters: {'alpha': 1.6867945379761165e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:26,964] Trial 3940 finished with value: 0.40374449310243377 and parameters: {'alpha': 1.0094793943771586e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,001] Trial 3941 finished with value: 0.4037450566762665 and parameters: {'alpha': 2.8008882136743664e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,035] Trial 3942 finished with value: 0.4037448945641233 and parameters: {'alpha': 1.7286090360877556e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,072] Trial 3943 finished with value: 0.5333851823491157 and parameters: {'alpha': 25451.800864510227}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,108] Trial 3944 finished with value: 0.40374526627941715 and parameters: {'alpha': 4.525475980064686e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▉  | 3950/5000 [01:54<00:37, 27.67it/s]

[I 2026-06-14 00:50:27,145] Trial 3945 finished with value: 0.4037455963840663 and parameters: {'alpha': 0.2666752307554343}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,182] Trial 3946 finished with value: 0.40374498710823203 and parameters: {'alpha': 2.6735628795652275e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,217] Trial 3947 finished with value: 0.4037446073525618 and parameters: {'alpha': 1.016786005546097e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,252] Trial 3948 finished with value: 0.4037448248839903 and parameters: {'alpha': 1.740759193817681e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,290] Trial 3949 finished with value: 0.4037449796873215 and parameters: {'alpha': 2.674339086195281e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,327] Trial 3950 finished with value: 0.40374525544975504 and parameters: {'alpha': 6.620921591515944e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▉  | 3956/5000 [01:54<00:37, 27.61it/s]

[I 2026-06-14 00:50:27,362] Trial 3951 finished with value: 0.4037447899899967 and parameters: {'alpha': 1.6383872223257125e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,399] Trial 3952 finished with value: 0.40374474054885795 and parameters: {'alpha': 1.7489468346804586e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,435] Trial 3953 finished with value: 0.4037452720505365 and parameters: {'alpha': 3.817417005106157e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,470] Trial 3954 finished with value: 0.40374491289129183 and parameters: {'alpha': 1.714343768390408e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,508] Trial 3955 finished with value: 0.4037449772314913 and parameters: {'alpha': 2.653795855870988e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,545] Trial 3956 finished with value: 0.4037449062613845 and parameters: {'alpha': 1.7233569622607196e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▉  | 3962/5000 [01:55<00:37, 27.55it/s]

[I 2026-06-14 00:50:27,581] Trial 3957 finished with value: 0.40374465352217875 and parameters: {'alpha': 1.0161941315717537e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,618] Trial 3958 finished with value: 0.4037452424317618 and parameters: {'alpha': 4.4935834899015736e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,655] Trial 3959 finished with value: 0.4037449814338173 and parameters: {'alpha': 2.6242684390217194e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,689] Trial 3960 finished with value: 0.4037444304318901 and parameters: {'alpha': 1.0043436115890902e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,727] Trial 3961 finished with value: 0.40374529480602295 and parameters: {'alpha': 9.502416860166346e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,763] Trial 3962 finished with value: 0.4037443806660262 and parameters: {'alpha': 1.0159767122996418e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▉  | 3968/5000 [01:55<00:37, 27.58it/s]

[I 2026-06-14 00:50:27,799] Trial 3963 finished with value: 0.4037454077615012 and parameters: {'alpha': 0.0018724034313875916}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,835] Trial 3964 finished with value: 0.40374473973610153 and parameters: {'alpha': 1.6916478740104224e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,871] Trial 3965 finished with value: 0.40374498481027343 and parameters: {'alpha': 2.7317018477656614e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,906] Trial 3966 finished with value: 0.4037451892153085 and parameters: {'alpha': 4.299430311909556e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,943] Trial 3967 finished with value: 0.40374476756333466 and parameters: {'alpha': 1.7333519821494868e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:27,978] Trial 3968 finished with value: 0.4037447338987252 and parameters: {'alpha': 1.707221527276339e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  79%|███████▉  | 3974/5000 [01:55<00:37, 27.62it/s]

[I 2026-06-14 00:50:28,014] Trial 3969 finished with value: 0.40374473175662995 and parameters: {'alpha': 1.0130369587965664e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,051] Trial 3970 finished with value: 0.4037442654488951 and parameters: {'alpha': 1.0009255268330938e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,087] Trial 3971 finished with value: 0.403745059654742 and parameters: {'alpha': 2.6672749203806658e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,123] Trial 3972 finished with value: 0.40374528565884715 and parameters: {'alpha': 5.817434780085139e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,159] Trial 3973 finished with value: 0.40374480014974157 and parameters: {'alpha': 1.701137427748224e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,195] Trial 3974 finished with value: 0.4037449852073953 and parameters: {'alpha': 2.7140240383975163e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  80%|███████▉  | 3980/5000 [01:55<00:37, 27.24it/s]

[I 2026-06-14 00:50:28,231] Trial 3975 finished with value: 0.403744888771601 and parameters: {'alpha': 1.7723591928021016e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,270] Trial 3976 finished with value: 0.4037443030457121 and parameters: {'alpha': 1.013614982817125e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,310] Trial 3977 finished with value: 0.40374525169167613 and parameters: {'alpha': 4.2164465728363213e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,346] Trial 3978 finished with value: 0.4037450252339831 and parameters: {'alpha': 2.813536508381932e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,384] Trial 3979 finished with value: 0.40374460087346836 and parameters: {'alpha': 1.0030894160606225e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,419] Trial 3980 finished with value: 0.4037444672143027 and parameters: {'alpha': 1.0208967616444182e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  80%|███████▉  | 3986/5000 [01:55<00:37, 27.35it/s]

[I 2026-06-14 00:50:28,455] Trial 3981 finished with value: 0.40374449131659323 and parameters: {'alpha': 1.0073182792941998e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,493] Trial 3982 finished with value: 0.40374529740501464 and parameters: {'alpha': 6.667172364855178e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,529] Trial 3983 finished with value: 0.40374496026447 and parameters: {'alpha': 2.5627276886628833e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,564] Trial 3984 finished with value: 0.40374520538679287 and parameters: {'alpha': 4.2469514823586294e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,602] Trial 3985 finished with value: 0.40374490622628906 and parameters: {'alpha': 1.708199949450414e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,637] Trial 3986 finished with value: 0.40374477613967363 and parameters: {'alpha': 1.7206060553801958e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  80%|███████▉  | 3992/5000 [01:56<00:36, 27.31it/s]

[I 2026-06-14 00:50:28,673] Trial 3987 finished with value: 0.4037449583646288 and parameters: {'alpha': 1.713903744170468e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,711] Trial 3988 finished with value: 0.40374498780762896 and parameters: {'alpha': 2.680434671836603e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,748] Trial 3989 finished with value: 0.40374435378926876 and parameters: {'alpha': 1.0126885130499509e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,783] Trial 3990 finished with value: 0.40374531781823053 and parameters: {'alpha': 1.1478390224615278e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,820] Trial 3991 finished with value: 0.40374433378188734 and parameters: {'alpha': 1.0011939041274485e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,855] Trial 3992 finished with value: 0.40374526285602663 and parameters: {'alpha': 4.327316015746075e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  80%|███████▉  | 3998/5000 [01:56<00:36, 27.28it/s]

[I 2026-06-14 00:50:28,892] Trial 3993 finished with value: 0.40374801077610717 and parameters: {'alpha': 2.472773372690413}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,931] Trial 3994 finished with value: 0.4037447736038395 and parameters: {'alpha': 1.7168343970781247e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:28,966] Trial 3995 finished with value: 0.40374502135514084 and parameters: {'alpha': 2.868048321592429e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,003] Trial 3996 finished with value: 0.4037449269506972 and parameters: {'alpha': 1.756399819481596e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,039] Trial 3997 finished with value: 0.4037448475607257 and parameters: {'alpha': 1.7411458789553642e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,075] Trial 3998 finished with value: 0.5729338252836456 and parameters: {'alpha': 95107.95063061909}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  80%|████████  | 4003/5000 [01:56<00:40, 24.53it/s]

[I 2026-06-14 00:50:29,112] Trial 3999 finished with value: 0.403745302110473 and parameters: {'alpha': 4.220718495239224e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,152] Trial 4000 finished with value: 0.40374433567589935 and parameters: {'alpha': 1.0014889678963325e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,219] Trial 4001 finished with value: 0.4037442913606274 and parameters: {'alpha': 1.0004604631671171e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,263] Trial 4002 finished with value: 0.4037446562667641 and parameters: {'alpha': 1.0047017016234744e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,308] Trial 4003 finished with value: 0.40374509324089985 and parameters: {'alpha': 2.7200487729535506e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  80%|████████  | 4009/5000 [01:56<00:38, 25.46it/s]

[I 2026-06-14 00:50:29,346] Trial 4004 finished with value: 0.4037444671376531 and parameters: {'alpha': 1.0035017098335674e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,383] Trial 4005 finished with value: 0.40374528987969904 and parameters: {'alpha': 7.721198058673032e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,421] Trial 4006 finished with value: 0.4037449704259465 and parameters: {'alpha': 2.615454245943397e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,457] Trial 4007 finished with value: 0.4037451945662782 and parameters: {'alpha': 4.242949234792947e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,493] Trial 4008 finished with value: 0.4037449677529651 and parameters: {'alpha': 1.7003305147422314e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,530] Trial 4009 finished with value: 0.4037450557412363 and parameters: {'alpha': 2.6958429236366377e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  80%|████████  | 4015/5000 [01:57<00:37, 26.24it/s]

[I 2026-06-14 00:50:29,567] Trial 4010 finished with value: 0.4037453653589778 and parameters: {'alpha': 2.1684608280350018e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,604] Trial 4011 finished with value: 0.4037449234724039 and parameters: {'alpha': 1.704355956409768e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,642] Trial 4012 finished with value: 0.40374493097493397 and parameters: {'alpha': 1.7197192190753544e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,678] Trial 4013 finished with value: 0.4037446458549619 and parameters: {'alpha': 1.007984615947376e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,715] Trial 4014 finished with value: 0.4037452619696242 and parameters: {'alpha': 5.993577253269483e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,751] Trial 4015 finished with value: 0.4037450857976944 and parameters: {'alpha': 2.7360785543829775e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  80%|████████  | 4021/5000 [01:57<00:36, 26.84it/s]

[I 2026-06-14 00:50:29,787] Trial 4016 finished with value: 0.4037447852983679 and parameters: {'alpha': 1.7857166178663765e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,824] Trial 4017 finished with value: 0.4037445574499623 and parameters: {'alpha': 1.00381524897672e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,862] Trial 4018 finished with value: 0.403744427485351 and parameters: {'alpha': 1.0002616472371027e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,898] Trial 4019 finished with value: 0.4037452260830809 and parameters: {'alpha': 3.873329497331643e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,934] Trial 4020 finished with value: 0.40374440350379054 and parameters: {'alpha': 1.0084722542773218e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:29,971] Trial 4021 finished with value: 0.4037449808164065 and parameters: {'alpha': 2.6670691771870577e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  81%|████████  | 4027/5000 [01:57<00:35, 27.14it/s]

[I 2026-06-14 00:50:30,008] Trial 4022 finished with value: 0.4037447643770889 and parameters: {'alpha': 1.716371857150241e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,043] Trial 4023 finished with value: 0.40374459599599954 and parameters: {'alpha': 1.0027671810097936e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,081] Trial 4024 finished with value: 0.40374530577770934 and parameters: {'alpha': 8.811423842274647e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,117] Trial 4025 finished with value: 0.40374428190499184 and parameters: {'alpha': 1.0029715500546763e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,153] Trial 4026 finished with value: 0.40374506582023684 and parameters: {'alpha': 2.867338308477492e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,190] Trial 4027 finished with value: 0.4037452583960524 and parameters: {'alpha': 4.807541803237287e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  81%|████████  | 4033/5000 [01:57<00:35, 26.97it/s]

[I 2026-06-14 00:50:30,225] Trial 4028 finished with value: 0.4037447850353403 and parameters: {'alpha': 1.7475855738077905e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,261] Trial 4029 finished with value: 0.403744748777128 and parameters: {'alpha': 1.7882758389903276e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,299] Trial 4030 finished with value: 0.40374459088327325 and parameters: {'alpha': 1.0060487853496634e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,340] Trial 4031 finished with value: 0.4037450429164938 and parameters: {'alpha': 2.7331180343890598e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,376] Trial 4032 finished with value: 0.40374520298289923 and parameters: {'alpha': 4.3229807557673435e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,412] Trial 4033 finished with value: 0.40374491140813246 and parameters: {'alpha': 1.7857495008370507e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  81%|████████  | 4039/5000 [01:57<00:35, 27.23it/s]

[I 2026-06-14 00:50:30,449] Trial 4034 finished with value: 0.4037452805845396 and parameters: {'alpha': 6.904925459452534e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,485] Trial 4035 finished with value: 0.40374431981674647 and parameters: {'alpha': 1.0088260117053074e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,522] Trial 4036 finished with value: 0.40374433653285546 and parameters: {'alpha': 1.0040459237780005e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,558] Trial 4037 finished with value: 0.40374495578943437 and parameters: {'alpha': 2.4885768554428093e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,594] Trial 4038 finished with value: 0.40374487124455677 and parameters: {'alpha': 1.7560065460879587e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,632] Trial 4039 finished with value: 0.4037443964933721 and parameters: {'alpha': 1.0078794970817963e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  81%|████████  | 4045/5000 [01:58<00:35, 27.22it/s]

[I 2026-06-14 00:50:30,669] Trial 4040 finished with value: 0.4037450033365451 and parameters: {'alpha': 2.6858244133222344e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,708] Trial 4041 finished with value: 0.4037452656810598 and parameters: {'alpha': 4.1192880516364075e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,745] Trial 4042 finished with value: 0.4037448089019941 and parameters: {'alpha': 1.7497474792331444e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,781] Trial 4043 finished with value: 0.40374505830441687 and parameters: {'alpha': 2.633317230356463e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,816] Trial 4044 finished with value: 0.40374440922393146 and parameters: {'alpha': 1.0096232541206477e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,853] Trial 4045 finished with value: 0.4037453234152265 and parameters: {'alpha': 1.2626006041257188e-07}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  81%|████████  | 4051/5000 [01:58<00:34, 27.30it/s]

[I 2026-06-14 00:50:30,889] Trial 4046 finished with value: 0.4037444748580115 and parameters: {'alpha': 1.005203681442907e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,926] Trial 4047 finished with value: 0.4037448608281789 and parameters: {'alpha': 1.749019413565238e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,962] Trial 4048 finished with value: 0.40374431573055064 and parameters: {'alpha': 1.0024965770856299e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:30,999] Trial 4049 finished with value: 0.40374525634881386 and parameters: {'alpha': 4.500680311618277e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,035] Trial 4050 finished with value: 0.40374506021124773 and parameters: {'alpha': 2.7908017909579067e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,072] Trial 4051 finished with value: 0.4037448493870456 and parameters: {'alpha': 1.8266580821835923e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  81%|████████  | 4057/5000 [01:58<00:34, 27.21it/s]

[I 2026-06-14 00:50:31,108] Trial 4052 finished with value: 0.4037452497234602 and parameters: {'alpha': 6.400908940242499e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,146] Trial 4053 finished with value: 0.4037450425943451 and parameters: {'alpha': 2.7057137183123735e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,183] Trial 4054 finished with value: 0.40374489611239794 and parameters: {'alpha': 1.655286235196235e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,220] Trial 4055 finished with value: 0.4037447318605736 and parameters: {'alpha': 1.7369572286837145e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,256] Trial 4056 finished with value: 0.4037452374577541 and parameters: {'alpha': 3.950674069285427e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,293] Trial 4057 finished with value: 0.4037447958119481 and parameters: {'alpha': 1.7780104161472188e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  81%|████████▏ | 4063/5000 [01:58<00:34, 26.87it/s]

[I 2026-06-14 00:50:31,330] Trial 4058 finished with value: 0.4037450641127981 and parameters: {'alpha': 2.8371710118906195e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,369] Trial 4059 finished with value: 0.4037445739696868 and parameters: {'alpha': 1.0081702586877188e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,407] Trial 4060 finished with value: 0.4037452851314282 and parameters: {'alpha': 5.7156263960613164e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,443] Trial 4061 finished with value: 0.40374489339873193 and parameters: {'alpha': 1.6956666099515936e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,482] Trial 4062 finished with value: 0.40374502928041955 and parameters: {'alpha': 2.695563516549206e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,519] Trial 4063 finished with value: 0.4037452513747609 and parameters: {'alpha': 4.0514236337811196e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  81%|████████▏ | 4069/5000 [01:59<00:34, 27.02it/s]

[I 2026-06-14 00:50:31,556] Trial 4064 finished with value: 0.4037450740549472 and parameters: {'alpha': 2.641330354643718e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,593] Trial 4065 finished with value: 0.4037447856319199 and parameters: {'alpha': 1.8344296476002675e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,629] Trial 4066 finished with value: 0.40374489388987655 and parameters: {'alpha': 1.714688224484482e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,666] Trial 4067 finished with value: 0.40374528998308884 and parameters: {'alpha': 8.957705695337523e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,703] Trial 4068 finished with value: 0.4037448836493558 and parameters: {'alpha': 1.682221072418609e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,740] Trial 4069 finished with value: 0.40374474286610784 and parameters: {'alpha': 1.0025567623748203e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4075/5000 [01:59<00:34, 27.05it/s]

[I 2026-06-14 00:50:31,777] Trial 4070 finished with value: 0.403745213466883 and parameters: {'alpha': 3.990258586870634e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,813] Trial 4071 finished with value: 0.40374441644823533 and parameters: {'alpha': 1.0124166280975397e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,851] Trial 4072 finished with value: 0.4037448398042389 and parameters: {'alpha': 1.6981081481330907e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,888] Trial 4073 finished with value: 0.40374506131069204 and parameters: {'alpha': 2.7764510166530797e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,924] Trial 4074 finished with value: 0.40374484190739857 and parameters: {'alpha': 1.7010127432235836e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:31,961] Trial 4075 finished with value: 0.4037452386853723 and parameters: {'alpha': 6.491319630389527e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4081/5000 [01:59<00:33, 27.19it/s]

[I 2026-06-14 00:50:31,997] Trial 4076 finished with value: 0.40378762577731236 and parameters: {'alpha': 17.726952215416553}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,034] Trial 4077 finished with value: 0.4037448340040148 and parameters: {'alpha': 1.750389488963721e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,071] Trial 4078 finished with value: 0.40374525624547386 and parameters: {'alpha': 3.782924476396074e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,108] Trial 4079 finished with value: 0.40374481304560805 and parameters: {'alpha': 1.7363605448016682e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,143] Trial 4080 finished with value: 0.4037449850695591 and parameters: {'alpha': 1.7492287090276104e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,180] Trial 4081 finished with value: 0.4037450872661753 and parameters: {'alpha': 2.7997299971677963e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4087/5000 [01:59<00:33, 26.99it/s]

[I 2026-06-14 00:50:32,217] Trial 4082 finished with value: 0.4037448498336756 and parameters: {'alpha': 1.725973121651322e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,255] Trial 4083 finished with value: 0.403745225827417 and parameters: {'alpha': 4.47801845022816e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,293] Trial 4084 finished with value: 0.40374510820641657 and parameters: {'alpha': 2.7701177404963813e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,329] Trial 4085 finished with value: 0.40374437711534733 and parameters: {'alpha': 1.0073809570528558e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,368] Trial 4086 finished with value: 0.4824989404388238 and parameters: {'alpha': 9622.166444847218}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,407] Trial 4087 finished with value: 0.40374533256249284 and parameters: {'alpha': 1.3394874962541707e-07}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4093/5000 [01:59<00:33, 27.05it/s]

[I 2026-06-14 00:50:32,444] Trial 4088 finished with value: 0.40374487985584073 and parameters: {'alpha': 1.622498353104676e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,480] Trial 4089 finished with value: 0.40374507058036235 and parameters: {'alpha': 2.812003141087129e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,517] Trial 4090 finished with value: 0.4037443634030788 and parameters: {'alpha': 1.0095824477091531e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,553] Trial 4091 finished with value: 0.40374526345727724 and parameters: {'alpha': 5.5329256160383664e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,590] Trial 4092 finished with value: 0.4037447438095303 and parameters: {'alpha': 1.6558541840966754e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,628] Trial 4093 finished with value: 0.40374489093893046 and parameters: {'alpha': 1.663508279079572e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4099/5000 [02:00<00:33, 27.09it/s]

[I 2026-06-14 00:50:32,664] Trial 4094 finished with value: 0.40374507255994574 and parameters: {'alpha': 2.9452325869020813e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,701] Trial 4095 finished with value: 0.40374465549262484 and parameters: {'alpha': 1.0149578267173984e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,738] Trial 4096 finished with value: 0.4037452978989059 and parameters: {'alpha': 7.324239592051949e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,775] Trial 4097 finished with value: 0.4037443057702686 and parameters: {'alpha': 1.0160329430308624e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,812] Trial 4098 finished with value: 0.4037449727691172 and parameters: {'alpha': 2.712413183319989e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,849] Trial 4099 finished with value: 0.4037451716093006 and parameters: {'alpha': 3.92193811515723e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4105/5000 [02:00<00:32, 27.16it/s]

[I 2026-06-14 00:50:32,886] Trial 4100 finished with value: 0.40374485302274465 and parameters: {'alpha': 1.7118442186630333e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,923] Trial 4101 finished with value: 0.4037448419202951 and parameters: {'alpha': 1.748028990576823e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,960] Trial 4102 finished with value: 0.4037448963241126 and parameters: {'alpha': 1.716886390701448e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:32,996] Trial 4103 finished with value: 0.4037460894866288 and parameters: {'alpha': 0.8462459210552903}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,032] Trial 4104 finished with value: 0.403745185190794 and parameters: {'alpha': 4.0898372265647505e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,069] Trial 4105 finished with value: 0.4037450796212195 and parameters: {'alpha': 2.836458889122834e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4111/5000 [02:00<00:32, 27.22it/s]

[I 2026-06-14 00:50:33,107] Trial 4106 finished with value: 0.4037448608243779 and parameters: {'alpha': 1.7494455517693174e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,144] Trial 4107 finished with value: 0.4037446111824686 and parameters: {'alpha': 1.0005351821712957e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,181] Trial 4108 finished with value: 0.403745015308835 and parameters: {'alpha': 2.66977437352708e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,217] Trial 4109 finished with value: 0.403745268567605 and parameters: {'alpha': 5.078755858547993e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,253] Trial 4110 finished with value: 0.40374465998583253 and parameters: {'alpha': 1.0138785575692039e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,289] Trial 4111 finished with value: 0.40374468784723755 and parameters: {'alpha': 1.0031634473919099e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4117/5000 [02:00<00:32, 27.07it/s]

[I 2026-06-14 00:50:33,326] Trial 4112 finished with value: 0.40374530732626757 and parameters: {'alpha': 9.176594369360149e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,364] Trial 4113 finished with value: 0.4037448703586153 and parameters: {'alpha': 1.70159122331269e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,403] Trial 4114 finished with value: 0.4037448466039638 and parameters: {'alpha': 1.7209723686351334e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,439] Trial 4115 finished with value: 0.40374505909290753 and parameters: {'alpha': 2.702673486698823e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,476] Trial 4116 finished with value: 0.40374520710834133 and parameters: {'alpha': 4.335002714360385e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,513] Trial 4117 finished with value: 0.40374479906080146 and parameters: {'alpha': 1.7448539712654762e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  82%|████████▏ | 4123/5000 [02:01<00:32, 26.91it/s]

[I 2026-06-14 00:50:33,549] Trial 4118 finished with value: 0.40374489278403314 and parameters: {'alpha': 1.7738488908478262e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,590] Trial 4119 finished with value: 0.4037447109864375 and parameters: {'alpha': 1.0121570383278359e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,628] Trial 4120 finished with value: 0.4037451006884313 and parameters: {'alpha': 2.8193117179399147e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,664] Trial 4121 finished with value: 0.4037445500868258 and parameters: {'alpha': 1.0103213705122544e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,700] Trial 4122 finished with value: 0.4037452801349523 and parameters: {'alpha': 6.267581028429329e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,738] Trial 4123 finished with value: 0.40374425186353197 and parameters: {'alpha': 1.0009981387506991e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  83%|████████▎ | 4129/5000 [02:01<00:32, 27.19it/s]

[I 2026-06-14 00:50:33,774] Trial 4124 finished with value: 0.4037448313347484 and parameters: {'alpha': 1.7221965620297046e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,811] Trial 4125 finished with value: 0.40374498871346104 and parameters: {'alpha': 2.811558983467846e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,848] Trial 4126 finished with value: 0.40374496563497314 and parameters: {'alpha': 1.757160949368129e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,884] Trial 4127 finished with value: 0.40374523583953825 and parameters: {'alpha': 4.3005675575791504e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,920] Trial 4128 finished with value: 0.40374540544807525 and parameters: {'alpha': 8.90725554322992e-06}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:33,957] Trial 4129 finished with value: 0.40374428361924297 and parameters: {'alpha': 1.0026009937048422e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  83%|████████▎ | 4135/5000 [02:01<00:31, 27.15it/s]

[I 2026-06-14 00:50:33,994] Trial 4130 finished with value: 0.4037450455555935 and parameters: {'alpha': 2.816734187119549e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,031] Trial 4131 finished with value: 0.4037444265858235 and parameters: {'alpha': 1.0033148642746268e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,068] Trial 4132 finished with value: 0.4090759018023696 and parameters: {'alpha': 1047.1080805993354}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,103] Trial 4133 finished with value: 0.4037453517055502 and parameters: {'alpha': 1.5875198097147513e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,140] Trial 4134 finished with value: 0.40374433729164516 and parameters: {'alpha': 1.006204794567804e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,179] Trial 4135 finished with value: 0.40374451108214227 and parameters: {'alpha': 1.0115804453680157e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  83%|████████▎ | 4141/5000 [02:01<00:31, 27.25it/s]

[I 2026-06-14 00:50:34,216] Trial 4136 finished with value: 0.4037449800117553 and parameters: {'alpha': 2.7286503960376535e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,253] Trial 4137 finished with value: 0.40374471583358107 and parameters: {'alpha': 1.0018865966345464e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,290] Trial 4138 finished with value: 0.4037452925408531 and parameters: {'alpha': 5.747096682421913e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,325] Trial 4139 finished with value: 0.4037445344749339 and parameters: {'alpha': 1.0100414880938198e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,361] Trial 4140 finished with value: 0.4037449744059951 and parameters: {'alpha': 2.6208420425837956e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,402] Trial 4141 finished with value: 0.40374477200886033 and parameters: {'alpha': 1.715614590427859e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  83%|████████▎ | 4147/5000 [02:01<00:31, 26.97it/s]

[I 2026-06-14 00:50:34,439] Trial 4142 finished with value: 0.40374488928247365 and parameters: {'alpha': 1.773139606976388e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,477] Trial 4143 finished with value: 0.4037451890210214 and parameters: {'alpha': 4.214042106515158e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,514] Trial 4144 finished with value: 0.4037453172057161 and parameters: {'alpha': 9.102239793093418e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,551] Trial 4145 finished with value: 0.40374488232666744 and parameters: {'alpha': 1.7359769644306233e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,587] Trial 4146 finished with value: 0.40374503271953804 and parameters: {'alpha': 2.9249501577192222e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,624] Trial 4147 finished with value: 0.4037445234614653 and parameters: {'alpha': 1.004092936916435e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  83%|████████▎ | 4153/5000 [02:02<00:31, 27.00it/s]

[I 2026-06-14 00:50:34,660] Trial 4148 finished with value: 0.4037449947867013 and parameters: {'alpha': 2.6979670297734518e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,697] Trial 4149 finished with value: 0.4037454118291821 and parameters: {'alpha': 0.00795287510731318}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,735] Trial 4150 finished with value: 0.4037447483026836 and parameters: {'alpha': 1.7661442466345127e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,771] Trial 4151 finished with value: 0.4037444307156996 and parameters: {'alpha': 1.0032354491611863e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,809] Trial 4152 finished with value: 0.4037443519099628 and parameters: {'alpha': 1.005577333814138e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,846] Trial 4153 finished with value: 0.40374523788617456 and parameters: {'alpha': 4.7758988274488267e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  83%|████████▎ | 4159/5000 [02:02<00:30, 27.15it/s]

[I 2026-06-14 00:50:34,882] Trial 4154 finished with value: 0.4037447915163364 and parameters: {'alpha': 1.756706602119344e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,920] Trial 4155 finished with value: 0.4037449595060245 and parameters: {'alpha': 1.6991872895902457e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,957] Trial 4156 finished with value: 0.40374503902264425 and parameters: {'alpha': 2.7835618006825593e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:34,992] Trial 4157 finished with value: 0.4037442738545933 and parameters: {'alpha': 1.0034919888886714e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,029] Trial 4158 finished with value: 0.4037452242265057 and parameters: {'alpha': 4.610084278567789e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,067] Trial 4159 finished with value: 0.40374504138489736 and parameters: {'alpha': 2.7231216601914335e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  83%|████████▎ | 4165/5000 [02:02<00:31, 26.92it/s]

[I 2026-06-14 00:50:35,104] Trial 4160 finished with value: 0.4037448995729193 and parameters: {'alpha': 1.6734043409954133e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,141] Trial 4161 finished with value: 0.40374485363482354 and parameters: {'alpha': 1.751452749549463e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,179] Trial 4162 finished with value: 0.40374523918098354 and parameters: {'alpha': 4.00022987257824e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,216] Trial 4163 finished with value: 0.40374530308383033 and parameters: {'alpha': 8.153742482384735e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,253] Trial 4164 finished with value: 0.4037443823740936 and parameters: {'alpha': 1.0078801886332248e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,291] Trial 4165 finished with value: 0.4037450634422366 and parameters: {'alpha': 2.6345093186697786e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  83%|████████▎ | 4171/5000 [02:02<00:30, 26.99it/s]

[I 2026-06-14 00:50:35,327] Trial 4166 finished with value: 0.4037448100373985 and parameters: {'alpha': 1.8776911574659578e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,364] Trial 4167 finished with value: 0.4037448682688639 and parameters: {'alpha': 1.6460928392998867e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,404] Trial 4168 finished with value: 0.4037451625986146 and parameters: {'alpha': 3.947911263892538e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,440] Trial 4169 finished with value: 0.40374482989950394 and parameters: {'alpha': 1.7117689620567834e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,475] Trial 4170 finished with value: 0.40374526902665325 and parameters: {'alpha': 7.252849451925097e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,513] Trial 4171 finished with value: 0.40374509588170937 and parameters: {'alpha': 2.7541630865982342e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▎ | 4177/5000 [02:03<00:30, 26.99it/s]

[I 2026-06-14 00:50:35,550] Trial 4172 finished with value: 0.40374494466372873 and parameters: {'alpha': 1.7678158354272124e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,588] Trial 4173 finished with value: 0.4037452844341514 and parameters: {'alpha': 4.2887547397967536e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,626] Trial 4174 finished with value: 0.4037446856692616 and parameters: {'alpha': 1.0071224712363708e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,662] Trial 4175 finished with value: 0.4037450311357814 and parameters: {'alpha': 2.5905203297462236e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,698] Trial 4176 finished with value: 0.40374490825804177 and parameters: {'alpha': 1.6473991698518174e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,735] Trial 4177 finished with value: 0.4037449587531335 and parameters: {'alpha': 1.8362092229833277e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▎ | 4183/5000 [02:03<00:30, 27.10it/s]

[I 2026-06-14 00:50:35,772] Trial 4178 finished with value: 0.4037453780008561 and parameters: {'alpha': 3.0299191598763756e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,809] Trial 4179 finished with value: 0.4037446813134894 and parameters: {'alpha': 1.004606216102073e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,845] Trial 4180 finished with value: 0.40374523443920707 and parameters: {'alpha': 3.99496954052159e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,882] Trial 4181 finished with value: 0.4037449731989614 and parameters: {'alpha': 2.6324033609509803e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,919] Trial 4182 finished with value: 0.40374484490874774 and parameters: {'alpha': 1.7283796968159392e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:35,956] Trial 4183 finished with value: 0.4037443493493066 and parameters: {'alpha': 1.0105771948306277e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▍ | 4189/5000 [02:03<00:29, 27.15it/s]

[I 2026-06-14 00:50:35,993] Trial 4184 finished with value: 0.4037453106253862 and parameters: {'alpha': 1.1160408439157208e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,029] Trial 4185 finished with value: 0.4037454063620518 and parameters: {'alpha': 3.620740671589739e-05}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,067] Trial 4186 finished with value: 0.40374522453807793 and parameters: {'alpha': 6.080548260062598e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,103] Trial 4187 finished with value: 0.4037444216404808 and parameters: {'alpha': 1.0075813365760042e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,140] Trial 4188 finished with value: 0.40374492856398136 and parameters: {'alpha': 1.731587083271952e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,177] Trial 4189 finished with value: 0.403744991676039 and parameters: {'alpha': 2.8581810903611575e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▍ | 4195/5000 [02:03<00:29, 27.31it/s]

[I 2026-06-14 00:50:36,214] Trial 4190 finished with value: 0.40374472195861866 and parameters: {'alpha': 1.732038243431305e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,250] Trial 4191 finished with value: 0.4037447646615029 and parameters: {'alpha': 1.7212021665880554e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,287] Trial 4192 finished with value: 0.4037447008182848 and parameters: {'alpha': 1.0045449538323383e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,323] Trial 4193 finished with value: 0.40374527196503973 and parameters: {'alpha': 4.023628591848753e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,358] Trial 4194 finished with value: 0.40374502201446183 and parameters: {'alpha': 2.6354698848516075e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,396] Trial 4195 finished with value: 0.40374527839071617 and parameters: {'alpha': 6.866399246648462e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▍ | 4201/5000 [02:03<00:29, 26.78it/s]

[I 2026-06-14 00:50:36,436] Trial 4196 finished with value: 0.4037448444127155 and parameters: {'alpha': 1.7998442779132995e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,473] Trial 4197 finished with value: 0.4037450229465684 and parameters: {'alpha': 2.663805787348591e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,512] Trial 4198 finished with value: 0.4037449158412386 and parameters: {'alpha': 1.7566157483942256e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,549] Trial 4199 finished with value: 0.4037447464330385 and parameters: {'alpha': 1.0108446493710779e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,586] Trial 4200 finished with value: 0.4037452698628062 and parameters: {'alpha': 4.184483563437945e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,624] Trial 4201 finished with value: 0.40374496428167017 and parameters: {'alpha': 1.7570253659373892e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▍ | 4207/5000 [02:04<00:29, 26.86it/s]

[I 2026-06-14 00:50:36,661] Trial 4202 finished with value: 0.40374438189935696 and parameters: {'alpha': 1.0124537783722246e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,699] Trial 4203 finished with value: 0.40374502037450827 and parameters: {'alpha': 2.9003255463608446e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,735] Trial 4204 finished with value: 0.4037448628914667 and parameters: {'alpha': 1.7144053339423375e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,772] Trial 4205 finished with value: 0.4037452870224745 and parameters: {'alpha': 4.035250742401381e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,808] Trial 4206 finished with value: 0.4037445226778118 and parameters: {'alpha': 1.0094356727515297e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,848] Trial 4207 finished with value: 0.4037449232635044 and parameters: {'alpha': 1.7323869066587157e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▍ | 4213/5000 [02:04<00:29, 26.92it/s]

[I 2026-06-14 00:50:36,885] Trial 4208 finished with value: 0.4037443664283382 and parameters: {'alpha': 1.0046765603938265e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,922] Trial 4209 finished with value: 0.40374530942567805 and parameters: {'alpha': 5.6133820392189047e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,959] Trial 4210 finished with value: 0.40374499815515985 and parameters: {'alpha': 2.7719895000780884e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:36,995] Trial 4211 finished with value: 0.40374501031638227 and parameters: {'alpha': 2.743091480225759e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,032] Trial 4212 finished with value: 0.4037453102995152 and parameters: {'alpha': 1.139637914187962e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,069] Trial 4213 finished with value: 0.4037449706109861 and parameters: {'alpha': 1.738923045240382e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▍ | 4219/5000 [02:04<00:28, 27.06it/s]

[I 2026-06-14 00:50:37,105] Trial 4214 finished with value: 0.40374443863658477 and parameters: {'alpha': 1.018749083188944e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,142] Trial 4215 finished with value: 0.4037449707974292 and parameters: {'alpha': 2.717122042835876e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,178] Trial 4216 finished with value: 0.4037452793590524 and parameters: {'alpha': 6.247051692437254e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,216] Trial 4217 finished with value: 0.40374476395871567 and parameters: {'alpha': 1.8071758904785325e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,252] Trial 4218 finished with value: 0.40374495632127616 and parameters: {'alpha': 1.73607251799122e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,289] Trial 4219 finished with value: 0.4037451806450327 and parameters: {'alpha': 3.793209723131987e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  84%|████████▍ | 4225/5000 [02:04<00:28, 26.91it/s]

[I 2026-06-14 00:50:37,326] Trial 4220 finished with value: 0.4037449008974267 and parameters: {'alpha': 1.7188678659959615e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,363] Trial 4221 finished with value: 0.40374478365704913 and parameters: {'alpha': 1.7398600483038267e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,401] Trial 4222 finished with value: 0.40374521207151265 and parameters: {'alpha': 3.072708790595186e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,441] Trial 4223 finished with value: 0.40374478606878145 and parameters: {'alpha': 1.683493000040058e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,477] Trial 4224 finished with value: 0.4037443096445262 and parameters: {'alpha': 1.0022160117079576e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,515] Trial 4225 finished with value: 0.40374531741819086 and parameters: {'alpha': 5.724116617818415e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  85%|████████▍ | 4231/5000 [02:05<00:28, 26.82it/s]

[I 2026-06-14 00:50:37,551] Trial 4226 finished with value: 0.4037447143918618 and parameters: {'alpha': 1.009805925195025e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,588] Trial 4227 finished with value: 0.4037452436903987 and parameters: {'alpha': 3.401673764865726e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,627] Trial 4228 finished with value: 0.4037449608489274 and parameters: {'alpha': 1.7503869025397807e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,663] Trial 4229 finished with value: 0.4037450873437165 and parameters: {'alpha': 2.6544535989136476e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,700] Trial 4230 finished with value: 0.4037453448836172 and parameters: {'alpha': 1.67019780883329e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,738] Trial 4231 finished with value: 0.4037446348102786 and parameters: {'alpha': 1.0014723348083887e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  85%|████████▍ | 4237/5000 [02:05<00:28, 27.01it/s]

[I 2026-06-14 00:50:37,775] Trial 4232 finished with value: 0.4037449074354229 and parameters: {'alpha': 1.7056038766503357e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,812] Trial 4233 finished with value: 0.40374438266772406 and parameters: {'alpha': 1.011942343936593e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,849] Trial 4234 finished with value: 0.40374526219980655 and parameters: {'alpha': 4.2798149926798e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,885] Trial 4235 finished with value: 0.40374457318351825 and parameters: {'alpha': 1.0138983788481694e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,922] Trial 4236 finished with value: 0.40374508681876325 and parameters: {'alpha': 2.7192295956322383e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:37,959] Trial 4237 finished with value: 0.4037452994957737 and parameters: {'alpha': 6.913493870749487e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  85%|████████▍ | 4243/5000 [02:05<00:27, 27.12it/s]

[I 2026-06-14 00:50:37,997] Trial 4238 finished with value: 0.4037449869650906 and parameters: {'alpha': 2.763035218702217e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,033] Trial 4239 finished with value: 0.4037448660304936 and parameters: {'alpha': 1.7105013974380474e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,071] Trial 4240 finished with value: 0.40374496464426957 and parameters: {'alpha': 1.6965343532730937e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,107] Trial 4241 finished with value: 0.4037447627111764 and parameters: {'alpha': 1.69005676780462e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,143] Trial 4242 finished with value: 0.4037452559141649 and parameters: {'alpha': 3.908417796157968e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,180] Trial 4243 finished with value: 0.4037449336996936 and parameters: {'alpha': 1.6785833403648524e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  85%|████████▍ | 4249/5000 [02:05<00:27, 27.05it/s]

[I 2026-06-14 00:50:38,218] Trial 4244 finished with value: 0.40374437261320534 and parameters: {'alpha': 1.014217431561398e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,254] Trial 4245 finished with value: 0.4037449880499702 and parameters: {'alpha': 2.8304172422260134e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,292] Trial 4246 finished with value: 0.40374530617140086 and parameters: {'alpha': 9.084103766772771e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,329] Trial 4247 finished with value: 0.40374496923371145 and parameters: {'alpha': 1.711741117458113e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,366] Trial 4248 finished with value: 0.4037442758930477 and parameters: {'alpha': 1.013508788339271e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,403] Trial 4249 finished with value: 0.40374522839818555 and parameters: {'alpha': 4.174076237677164e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  85%|████████▌ | 4255/5000 [02:05<00:27, 26.74it/s]

[I 2026-06-14 00:50:38,441] Trial 4250 finished with value: 0.4037450535597746 and parameters: {'alpha': 2.7505947733105138e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,482] Trial 4251 finished with value: 0.4037447626387416 and parameters: {'alpha': 1.7692962311985147e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,520] Trial 4252 finished with value: 0.40374444869104964 and parameters: {'alpha': 1.0170821856324075e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,557] Trial 4253 finished with value: 0.40374524376397003 and parameters: {'alpha': 5.064322619502623e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,593] Trial 4254 finished with value: 0.4037449840624097 and parameters: {'alpha': 2.6940335502865044e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,631] Trial 4255 finished with value: 0.4037448811978037 and parameters: {'alpha': 1.8340131263239436e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  85%|████████▌ | 4261/5000 [02:06<00:27, 26.62it/s]

[I 2026-06-14 00:50:38,670] Trial 4256 finished with value: 0.4037443531686159 and parameters: {'alpha': 1.0162330515563749e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,709] Trial 4257 finished with value: 0.40374460967278736 and parameters: {'alpha': 1.0077926910190216e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,747] Trial 4258 finished with value: 0.4037449825897655 and parameters: {'alpha': 2.731456396164563e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,783] Trial 4259 finished with value: 0.40374443213778505 and parameters: {'alpha': 1.0071962752028898e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,820] Trial 4260 finished with value: 0.4037452850583925 and parameters: {'alpha': 6.552053175291366e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,858] Trial 4261 finished with value: 0.4037448963502505 and parameters: {'alpha': 1.709302478889717e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  85%|████████▌ | 4267/5000 [02:06<00:27, 26.88it/s]

[I 2026-06-14 00:50:38,895] Trial 4262 finished with value: 0.4037450660683196 and parameters: {'alpha': 2.740830008326722e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,931] Trial 4263 finished with value: 0.4037443045433114 and parameters: {'alpha': 1.015080503566932e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:38,969] Trial 4264 finished with value: 0.4037446137792824 and parameters: {'alpha': 1.0030353628078636e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,007] Trial 4265 finished with value: 0.4037452327040446 and parameters: {'alpha': 4.665739059263406e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,042] Trial 4266 finished with value: 0.4037446673022394 and parameters: {'alpha': 1.0016500097484095e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,079] Trial 4267 finished with value: 0.4037450211593347 and parameters: {'alpha': 2.694718572264783e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  85%|████████▌ | 4273/5000 [02:06<00:26, 26.99it/s]

[I 2026-06-14 00:50:39,115] Trial 4268 finished with value: 0.4037449061585978 and parameters: {'alpha': 1.6439166516462867e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,151] Trial 4269 finished with value: 0.40374487722669405 and parameters: {'alpha': 1.694748660387407e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,189] Trial 4270 finished with value: 0.40374520205986514 and parameters: {'alpha': 4.125703014545139e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,226] Trial 4271 finished with value: 0.40374507452852054 and parameters: {'alpha': 2.709594713187496e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,263] Trial 4272 finished with value: 0.40374532374281946 and parameters: {'alpha': 1.1934560965473055e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,299] Trial 4273 finished with value: 0.4037449192289249 and parameters: {'alpha': 1.7386000795170663e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  86%|████████▌ | 4279/5000 [02:06<00:26, 26.83it/s]

[I 2026-06-14 00:50:39,337] Trial 4274 finished with value: 0.4037452530767702 and parameters: {'alpha': 6.724858271687211e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,374] Trial 4275 finished with value: 0.4037443519397792 and parameters: {'alpha': 1.0166325377791356e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,411] Trial 4276 finished with value: 0.4037450083283727 and parameters: {'alpha': 2.670665450772118e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,447] Trial 4277 finished with value: 0.4037447565327691 and parameters: {'alpha': 1.7169544518366423e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,486] Trial 4278 finished with value: 0.40374434247464 and parameters: {'alpha': 1.0045556026279816e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,525] Trial 4279 finished with value: 0.4037452713651618 and parameters: {'alpha': 3.9824508079977555e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  86%|████████▌ | 4285/5000 [02:07<00:29, 23.95it/s]

[I 2026-06-14 00:50:39,563] Trial 4280 finished with value: 0.4037449024377641 and parameters: {'alpha': 1.806610994986279e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,601] Trial 4281 finished with value: 0.4037449012709803 and parameters: {'alpha': 1.7178006622865528e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,664] Trial 4282 finished with value: 0.4037450617232942 and parameters: {'alpha': 2.569162602233257e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,710] Trial 4283 finished with value: 0.4037447025298725 and parameters: {'alpha': 1.010991500616424e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,758] Trial 4284 finished with value: 0.40374519862536234 and parameters: {'alpha': 4.057997883549941e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  86%|████████▌ | 4291/5000 [02:07<00:27, 25.36it/s]

[I 2026-06-14 00:50:39,797] Trial 4285 finished with value: 0.4037447432018072 and parameters: {'alpha': 1.0085987293476808e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,834] Trial 4286 finished with value: 0.40374443408551325 and parameters: {'alpha': 1.014425826686204e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,871] Trial 4287 finished with value: 0.40374498973659556 and parameters: {'alpha': 2.6688168504047944e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,909] Trial 4288 finished with value: 0.4037452689828716 and parameters: {'alpha': 8.147081721588849e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,945] Trial 4289 finished with value: 0.40374491104439014 and parameters: {'alpha': 1.706958174301062e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:39,981] Trial 4290 finished with value: 0.40374479263744767 and parameters: {'alpha': 1.7208922934493106e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  86%|████████▌ | 4297/5000 [02:07<00:26, 26.18it/s]

[I 2026-06-14 00:50:40,020] Trial 4291 finished with value: 0.4037452702264997 and parameters: {'alpha': 4.417706709016918e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,057] Trial 4292 finished with value: 0.40374503163571324 and parameters: {'alpha': 2.9143858501911898e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,094] Trial 4293 finished with value: 0.40374482130227274 and parameters: {'alpha': 1.7025787918486064e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,131] Trial 4294 finished with value: 0.40374498678799997 and parameters: {'alpha': 2.7647621596234253e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,167] Trial 4295 finished with value: 0.403744961112874 and parameters: {'alpha': 1.74469399918639e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,204] Trial 4296 finished with value: 0.40374466219932564 and parameters: {'alpha': 1.0035366556822277e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  86%|████████▌ | 4303/5000 [02:07<00:26, 26.66it/s]

[I 2026-06-14 00:50:40,242] Trial 4297 finished with value: 0.40374484680311834 and parameters: {'alpha': 1.7018286446144763e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,278] Trial 4298 finished with value: 0.4037452857604148 and parameters: {'alpha': 6.209262678387603e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,315] Trial 4299 finished with value: 0.40374518882756344 and parameters: {'alpha': 4.273905998707298e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,352] Trial 4300 finished with value: 0.40390647236674787 and parameters: {'alpha': 53.37906921179923}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,388] Trial 4301 finished with value: 0.40374540424986455 and parameters: {'alpha': 3.088692051286365e-06}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,425] Trial 4302 finished with value: 0.4037447147475437 and parameters: {'alpha': 1.0161706600814661e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  86%|████████▌ | 4309/5000 [02:08<00:26, 26.54it/s]

[I 2026-06-14 00:50:40,463] Trial 4303 finished with value: 0.40374507842535334 and parameters: {'alpha': 2.747497493077671e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,504] Trial 4304 finished with value: 0.40374484912743386 and parameters: {'alpha': 1.7143224405808028e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,542] Trial 4305 finished with value: 0.4037455048567336 and parameters: {'alpha': 0.14230788195753363}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,580] Trial 4306 finished with value: 0.4037443084273413 and parameters: {'alpha': 1.0156995850584978e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,616] Trial 4307 finished with value: 0.40374540649001306 and parameters: {'alpha': 9.383714428312768e-05}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,653] Trial 4308 finished with value: 0.4037449750011977 and parameters: {'alpha': 2.556753715738082e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  86%|████████▋ | 4315/5000 [02:08<00:25, 26.66it/s]

[I 2026-06-14 00:50:40,692] Trial 4309 finished with value: 0.4037448325600302 and parameters: {'alpha': 1.806461817540766e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,729] Trial 4310 finished with value: 0.4037453617894468 and parameters: {'alpha': 1.9340970858403534e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,766] Trial 4311 finished with value: 0.40374521578722616 and parameters: {'alpha': 4.259708462146206e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,804] Trial 4312 finished with value: 0.40374442170074937 and parameters: {'alpha': 1.0081399135078047e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,841] Trial 4313 finished with value: 0.40374464898375073 and parameters: {'alpha': 1.0124492012039928e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,878] Trial 4314 finished with value: 0.40374531591673374 and parameters: {'alpha': 8.12901043821965e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  86%|████████▋ | 4321/5000 [02:08<00:25, 26.57it/s]

[I 2026-06-14 00:50:40,917] Trial 4315 finished with value: 0.4037450173816257 and parameters: {'alpha': 2.7444141575890524e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,955] Trial 4316 finished with value: 0.4037450002629621 and parameters: {'alpha': 2.4879293381180372e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:40,994] Trial 4317 finished with value: 0.40374483687136514 and parameters: {'alpha': 1.6984380312838924e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,032] Trial 4318 finished with value: 0.40374475796678705 and parameters: {'alpha': 1.71409265621083e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,068] Trial 4319 finished with value: 0.403745233030149 and parameters: {'alpha': 4.536669677999056e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,105] Trial 4320 finished with value: 0.4037444323057163 and parameters: {'alpha': 1.0163721824345293e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  87%|████████▋ | 4327/5000 [02:08<00:25, 26.57it/s]

[I 2026-06-14 00:50:41,143] Trial 4321 finished with value: 0.40374498879404563 and parameters: {'alpha': 1.7788784572320256e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,180] Trial 4322 finished with value: 0.4037450509400241 and parameters: {'alpha': 2.7017407004778818e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,218] Trial 4323 finished with value: 0.4037452667439189 and parameters: {'alpha': 4.646354526008756e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,256] Trial 4324 finished with value: 0.40374506004359445 and parameters: {'alpha': 2.8439195975127444e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,292] Trial 4325 finished with value: 0.40374452672204497 and parameters: {'alpha': 1.0197104795327565e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,331] Trial 4326 finished with value: 0.403744413121148 and parameters: {'alpha': 1.011721338854508e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  87%|████████▋ | 4333/5000 [02:08<00:25, 26.47it/s]

[I 2026-06-14 00:50:41,368] Trial 4327 finished with value: 0.4037444212940574 and parameters: {'alpha': 1.0075875147200476e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,406] Trial 4328 finished with value: 0.40374531243326084 and parameters: {'alpha': 9.81714859384928e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,442] Trial 4329 finished with value: 0.4037449136447037 and parameters: {'alpha': 1.769627598024987e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,480] Trial 4330 finished with value: 0.40374490586504125 and parameters: {'alpha': 1.834498024968242e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,520] Trial 4331 finished with value: 0.4037452540663938 and parameters: {'alpha': 4.4661319085102675e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,558] Trial 4332 finished with value: 0.40374485157559425 and parameters: {'alpha': 1.7885777049536205e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  87%|████████▋ | 4339/5000 [02:09<00:24, 26.54it/s]

[I 2026-06-14 00:50:41,596] Trial 4333 finished with value: 0.4037444840063313 and parameters: {'alpha': 1.0151505119777354e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,635] Trial 4334 finished with value: 0.40374506109499714 and parameters: {'alpha': 2.7322672921737703e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,672] Trial 4335 finished with value: 0.4037449591225136 and parameters: {'alpha': 1.7054935576680222e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,711] Trial 4336 finished with value: 0.4037452818878111 and parameters: {'alpha': 6.242576227154572e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,747] Trial 4337 finished with value: 0.40374452365143754 and parameters: {'alpha': 1.0061720509444632e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,784] Trial 4338 finished with value: 0.4037451012685438 and parameters: {'alpha': 2.8524833723420475e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  87%|████████▋ | 4345/5000 [02:09<00:24, 26.52it/s]

[I 2026-06-14 00:50:41,823] Trial 4339 finished with value: 0.40374452614346673 and parameters: {'alpha': 1.0096095625600281e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,861] Trial 4340 finished with value: 0.4037450242014115 and parameters: {'alpha': 2.7001282428170716e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,898] Trial 4341 finished with value: 0.4037448822405082 and parameters: {'alpha': 1.7274611489563192e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,936] Trial 4342 finished with value: 0.4037448312005305 and parameters: {'alpha': 1.743555753508516e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:41,974] Trial 4343 finished with value: 0.40374527698291174 and parameters: {'alpha': 5.226237964037927e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,011] Trial 4344 finished with value: 0.4037443691462781 and parameters: {'alpha': 1.0110554795646318e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  87%|████████▋ | 4351/5000 [02:09<00:24, 26.48it/s]

[I 2026-06-14 00:50:42,049] Trial 4345 finished with value: 0.40374454278326577 and parameters: {'alpha': 1.0002624278512135e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,085] Trial 4346 finished with value: 0.40374571575906654 and parameters: {'alpha': 0.41935435065698645}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,123] Trial 4347 finished with value: 0.4037450854357077 and parameters: {'alpha': 2.985306749574302e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,162] Trial 4348 finished with value: 0.40374489281005405 and parameters: {'alpha': 1.7153828250514673e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,199] Trial 4349 finished with value: 0.4037452102116373 and parameters: {'alpha': 4.2683389203200584e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,236] Trial 4350 finished with value: 0.4037450418481388 and parameters: {'alpha': 2.8571869146541836e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  87%|████████▋ | 4357/5000 [02:09<00:24, 26.64it/s]

[I 2026-06-14 00:50:42,276] Trial 4351 finished with value: 0.40374494156374635 and parameters: {'alpha': 1.6514544381610514e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,313] Trial 4352 finished with value: 0.4037453046424075 and parameters: {'alpha': 1.0331802157321246e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,350] Trial 4353 finished with value: 0.403744810345905 and parameters: {'alpha': 1.709161807968066e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,389] Trial 4354 finished with value: 0.40374492309750964 and parameters: {'alpha': 1.7060624127789113e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,425] Trial 4355 finished with value: 0.40374527269416965 and parameters: {'alpha': 4.265325937989562e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,462] Trial 4356 finished with value: 0.4037450505446382 and parameters: {'alpha': 2.7320332024291898e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  87%|████████▋ | 4363/5000 [02:10<00:24, 26.26it/s]

[I 2026-06-14 00:50:42,503] Trial 4357 finished with value: 0.40374482259410704 and parameters: {'alpha': 1.7875150166664682e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,542] Trial 4358 finished with value: 0.404913058559918 and parameters: {'alpha': 372.818552840131}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,581] Trial 4359 finished with value: 0.40374447019996235 and parameters: {'alpha': 1.0162211872353721e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,619] Trial 4360 finished with value: 0.40374526879868755 and parameters: {'alpha': 5.60955353246724e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,656] Trial 4361 finished with value: 0.4037450089599432 and parameters: {'alpha': 2.7011108277386552e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,693] Trial 4362 finished with value: 0.40374486076744737 and parameters: {'alpha': 1.72748852447393e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  87%|████████▋ | 4369/5000 [02:10<00:24, 26.17it/s]

[I 2026-06-14 00:50:42,732] Trial 4363 finished with value: 0.4037447757596571 and parameters: {'alpha': 1.7347663124461432e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,770] Trial 4364 finished with value: 0.403745188465828 and parameters: {'alpha': 3.830324926983255e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,808] Trial 4365 finished with value: 0.4037448375229308 and parameters: {'alpha': 1.69181769491976e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,850] Trial 4366 finished with value: 0.40374528957555744 and parameters: {'alpha': 8.11421415180926e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,887] Trial 4367 finished with value: 0.40374501688660663 and parameters: {'alpha': 2.7240855178322222e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:42,924] Trial 4368 finished with value: 0.403744908700012 and parameters: {'alpha': 1.7700795696832415e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4375/5000 [02:10<00:23, 26.26it/s]

[I 2026-06-14 00:50:42,963] Trial 4369 finished with value: 0.4037446005525568 and parameters: {'alpha': 1.0167562902478804e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,002] Trial 4370 finished with value: 0.40374527518703573 and parameters: {'alpha': 3.703342416325739e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,040] Trial 4371 finished with value: 0.4037447981734857 and parameters: {'alpha': 1.82144686525183e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,077] Trial 4372 finished with value: 0.40374462955536417 and parameters: {'alpha': 1.0126593069383522e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,115] Trial 4373 finished with value: 0.4037454071938715 and parameters: {'alpha': 0.0010288707333531448}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,153] Trial 4374 finished with value: 0.4037449974186468 and parameters: {'alpha': 2.729186679677249e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4381/5000 [02:10<00:23, 26.28it/s]

[I 2026-06-14 00:50:43,192] Trial 4375 finished with value: 0.40374528093179973 and parameters: {'alpha': 6.287686836077464e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,230] Trial 4376 finished with value: 0.40375077868701453 and parameters: {'alpha': 4.187573680494102}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,267] Trial 4377 finished with value: 0.40374487323210306 and parameters: {'alpha': 1.7746514132007865e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,305] Trial 4378 finished with value: 0.4037448291584422 and parameters: {'alpha': 1.7082221429393924e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,343] Trial 4379 finished with value: 0.403745247837369 and parameters: {'alpha': 3.692728266398226e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,380] Trial 4380 finished with value: 0.40374473062322963 and parameters: {'alpha': 1.6368561657002186e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4387/5000 [02:10<00:23, 26.09it/s]

[I 2026-06-14 00:50:43,419] Trial 4381 finished with value: 0.403744813185066 and parameters: {'alpha': 1.6724413428308557e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,457] Trial 4382 finished with value: 0.40374506466207555 and parameters: {'alpha': 2.8506886677252428e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,494] Trial 4383 finished with value: 0.4037444608471887 and parameters: {'alpha': 1.007159866203095e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,535] Trial 4384 finished with value: 0.4037445186975728 and parameters: {'alpha': 1.0127212833855978e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,574] Trial 4385 finished with value: 0.40374528740201077 and parameters: {'alpha': 6.533232048473249e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,612] Trial 4386 finished with value: 0.4037453302499299 and parameters: {'alpha': 1.4829362444209728e-07}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4393/5000 [02:11<00:23, 26.21it/s]

[I 2026-06-14 00:50:43,652] Trial 4387 finished with value: 0.40374507989334263 and parameters: {'alpha': 2.7499150060152698e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,690] Trial 4388 finished with value: 0.40374474909451796 and parameters: {'alpha': 1.0137336100439797e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,728] Trial 4389 finished with value: 0.4037453916110519 and parameters: {'alpha': 6.840694179655621e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,766] Trial 4390 finished with value: 0.40374472184057936 and parameters: {'alpha': 1.7069260212920464e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,803] Trial 4391 finished with value: 0.4037452511165595 and parameters: {'alpha': 4.153627944217027e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,840] Trial 4392 finished with value: 0.40374497401870796 and parameters: {'alpha': 2.683490937211359e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4399/5000 [02:11<00:22, 26.27it/s]

[I 2026-06-14 00:50:43,878] Trial 4393 finished with value: 0.4037449082879309 and parameters: {'alpha': 1.8160443033505914e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,916] Trial 4394 finished with value: 0.40374440690588004 and parameters: {'alpha': 1.0182116282987642e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,954] Trial 4395 finished with value: 0.4037449441347813 and parameters: {'alpha': 1.7215807031230758e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:43,993] Trial 4396 finished with value: 0.40374522164784865 and parameters: {'alpha': 4.111628978186414e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,030] Trial 4397 finished with value: 0.403744984026928 and parameters: {'alpha': 2.6897971302008434e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,067] Trial 4398 finished with value: 0.4037448267867498 and parameters: {'alpha': 1.7371694547524218e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4405/5000 [02:11<00:22, 26.63it/s]

[I 2026-06-14 00:50:44,106] Trial 4399 finished with value: 0.40374529651073454 and parameters: {'alpha': 6.750175118920837e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,143] Trial 4400 finished with value: 0.4037442474343914 and parameters: {'alpha': 1.0198699317247423e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,179] Trial 4401 finished with value: 0.40374505058730026 and parameters: {'alpha': 2.8506969652929748e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,217] Trial 4402 finished with value: 0.4037449696296119 and parameters: {'alpha': 1.7411915958532794e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,253] Trial 4403 finished with value: 0.4037452306477713 and parameters: {'alpha': 4.373466939776475e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,291] Trial 4404 finished with value: 0.40374491209386815 and parameters: {'alpha': 1.686354131269024e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4411/5000 [02:11<00:22, 26.43it/s]

[I 2026-06-14 00:50:44,329] Trial 4405 finished with value: 0.40374485290955997 and parameters: {'alpha': 1.7313266076779526e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,367] Trial 4406 finished with value: 0.4037451933721225 and parameters: {'alpha': 3.3794308070439965e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,405] Trial 4407 finished with value: 0.4037443012511242 and parameters: {'alpha': 1.0006130115241578e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,443] Trial 4408 finished with value: 0.4037453127046028 and parameters: {'alpha': 8.636412965217234e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,480] Trial 4409 finished with value: 0.4037450351184771 and parameters: {'alpha': 2.7001814453130843e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,519] Trial 4410 finished with value: 0.4037444951319604 and parameters: {'alpha': 1.008983579514201e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4417/5000 [02:12<00:22, 26.27it/s]

[I 2026-06-14 00:50:44,561] Trial 4411 finished with value: 0.4037442593366223 and parameters: {'alpha': 1.001680574386755e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,599] Trial 4412 finished with value: 0.4037447613969299 and parameters: {'alpha': 1.7152810187493678e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,637] Trial 4413 finished with value: 0.4037452567350385 and parameters: {'alpha': 4.479538667647906e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,674] Trial 4414 finished with value: 0.4037450147634644 and parameters: {'alpha': 2.6336220819819978e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,712] Trial 4415 finished with value: 0.40374542420544934 and parameters: {'alpha': 0.02634962564336057}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,749] Trial 4416 finished with value: 0.40374477670480585 and parameters: {'alpha': 1.7531039324738415e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  88%|████████▊ | 4423/5000 [02:12<00:21, 26.37it/s]

[I 2026-06-14 00:50:44,788] Trial 4417 finished with value: 0.40374434067560205 and parameters: {'alpha': 1.0104305016978971e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,826] Trial 4418 finished with value: 0.40374529129226877 and parameters: {'alpha': 6.382822271399858e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,864] Trial 4419 finished with value: 0.40374502237938303 and parameters: {'alpha': 2.6300547563765942e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,901] Trial 4420 finished with value: 0.40374476477503785 and parameters: {'alpha': 1.6590726583125818e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,938] Trial 4421 finished with value: 0.4037447692866516 and parameters: {'alpha': 1.6684603228660557e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:44,976] Trial 4422 finished with value: 0.40374524359480757 and parameters: {'alpha': 4.578891204927015e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:50:45,017] Trial 4423 finished with value: 0.40374481781439925 and parameters: {'alpha': 1.697944386663573e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,061] Trial 4424 finished with value: 0.40374470580649924 and parameters: {'alpha': 1.0050125391200535e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,100] Trial 4425 finished with value: 0.40374430031438197 and parameters: {'alpha': 1.0016059963759577e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,142] Trial 4426 finished with value: 0.4037450765195517 and parameters: {'alpha': 2.9049550662445143e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,180] Trial 4427 finished with value: 0.4037446968360784 and parameters: {'alpha': 1.018258474624258e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  89%|████████▊ | 4433/5000 [02:12<00:22, 25.65it/s]

[I 2026-06-14 00:50:45,219] Trial 4428 finished with value: 0.40374503721405364 and parameters: {'alpha': 2.6855717011890445e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,262] Trial 4429 finished with value: 0.403745316953869 and parameters: {'alpha': 1.0593478936465223e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,299] Trial 4430 finished with value: 0.4037452384777083 and parameters: {'alpha': 4.0766253193041714e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,336] Trial 4431 finished with value: 0.4037447650767107 and parameters: {'alpha': 1.7830209957496e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,374] Trial 4432 finished with value: 0.40374495560592105 and parameters: {'alpha': 1.6928987517400538e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,410] Trial 4433 finished with value: 0.40374507389821096 and parameters: {'alpha': 2.664495907721455e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  89%|████████▉ | 4439/5000 [02:13<00:21, 25.84it/s]

[I 2026-06-14 00:50:45,449] Trial 4434 finished with value: 0.40374467889187343 and parameters: {'alpha': 1.0168720964683928e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,488] Trial 4435 finished with value: 0.403745270678335 and parameters: {'alpha': 6.242893708567081e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,526] Trial 4436 finished with value: 0.40374478726140467 and parameters: {'alpha': 1.672190758105713e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,566] Trial 4437 finished with value: 0.4037450514348281 and parameters: {'alpha': 2.8641567385421124e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,604] Trial 4438 finished with value: 0.4037448186468217 and parameters: {'alpha': 1.6631048714594413e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,642] Trial 4439 finished with value: 0.40374517821711065 and parameters: {'alpha': 3.956680017144089e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  89%|████████▉ | 4445/5000 [02:13<00:21, 25.98it/s]

[I 2026-06-14 00:50:45,681] Trial 4440 finished with value: 0.4037453589811651 and parameters: {'alpha': 2.3423814396657553e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,721] Trial 4441 finished with value: 0.4037448481654629 and parameters: {'alpha': 1.755816371950956e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,758] Trial 4442 finished with value: 0.4037447529616361 and parameters: {'alpha': 1.7145258264003482e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,796] Trial 4443 finished with value: 0.4037453007617827 and parameters: {'alpha': 4.311182806091431e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,835] Trial 4444 finished with value: 0.40374508439502466 and parameters: {'alpha': 2.7537487092345157e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,873] Trial 4445 finished with value: 0.4037443590900418 and parameters: {'alpha': 1.0078221438746535e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  89%|████████▉ | 4451/5000 [02:13<00:21, 25.92it/s]

[I 2026-06-14 00:50:45,911] Trial 4446 finished with value: 0.40374490373997146 and parameters: {'alpha': 1.722172901235689e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,952] Trial 4447 finished with value: 0.4037447762017379 and parameters: {'alpha': 1.7091104593757874e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:45,989] Trial 4448 finished with value: 0.4037452644855955 and parameters: {'alpha': 6.016035903824417e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,026] Trial 4449 finished with value: 0.40374445467351355 and parameters: {'alpha': 1.0009441730719869e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,065] Trial 4450 finished with value: 0.40374426455596096 and parameters: {'alpha': 1.0028808875703262e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,103] Trial 4451 finished with value: 0.40374497667483866 and parameters: {'alpha': 2.6111976410332824e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  89%|████████▉ | 4457/5000 [02:13<00:20, 26.15it/s]

[I 2026-06-14 00:50:46,141] Trial 4452 finished with value: 0.4037443654397391 and parameters: {'alpha': 1.0161247521274897e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,179] Trial 4453 finished with value: 0.4037447313466415 and parameters: {'alpha': 1.6913179310213358e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,217] Trial 4454 finished with value: 0.5547566842661006 and parameters: {'alpha': 44723.92353112073}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,254] Trial 4455 finished with value: 0.40374511823303283 and parameters: {'alpha': 3.061714397683482e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,293] Trial 4456 finished with value: 0.4037447593976557 and parameters: {'alpha': 1.701617958863595e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,330] Trial 4457 finished with value: 0.403744716454171 and parameters: {'alpha': 1.0264062161096844e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  89%|████████▉ | 4463/5000 [02:13<00:20, 26.22it/s]

[I 2026-06-14 00:50:46,368] Trial 4458 finished with value: 0.40374506041552694 and parameters: {'alpha': 2.7915522430047428e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,408] Trial 4459 finished with value: 0.40374523889529956 and parameters: {'alpha': 6.165492992964223e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,445] Trial 4460 finished with value: 0.4037453481473079 and parameters: {'alpha': 1.4199453413405419e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,482] Trial 4461 finished with value: 0.4037445140464127 and parameters: {'alpha': 1.0056946782519943e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,521] Trial 4462 finished with value: 0.4037450847497376 and parameters: {'alpha': 2.664013736315279e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,561] Trial 4463 finished with value: 0.4037449590160202 and parameters: {'alpha': 1.6695653994677697e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  89%|████████▉ | 4469/5000 [02:14<00:20, 26.00it/s]

[I 2026-06-14 00:50:46,599] Trial 4464 finished with value: 0.403745226775443 and parameters: {'alpha': 3.8027752803628876e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,638] Trial 4465 finished with value: 0.40374461101450076 and parameters: {'alpha': 1.0035634456181871e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,677] Trial 4466 finished with value: 0.4037448830700177 and parameters: {'alpha': 1.7380971987592906e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,715] Trial 4467 finished with value: 0.4037446325789666 and parameters: {'alpha': 1.0207963193954336e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,754] Trial 4468 finished with value: 0.4037449758619065 and parameters: {'alpha': 2.7155877220391182e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,791] Trial 4469 finished with value: 0.4037452512193815 and parameters: {'alpha': 6.118531804582425e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|████████▉ | 4475/5000 [02:14<00:20, 25.85it/s]

[I 2026-06-14 00:50:46,828] Trial 4470 finished with value: 0.4037445691986359 and parameters: {'alpha': 1.0190171383037441e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,871] Trial 4471 finished with value: 0.4037447524780365 and parameters: {'alpha': 1.7682032688851704e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,910] Trial 4472 finished with value: 0.40374441683459356 and parameters: {'alpha': 1.0178139124757547e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,947] Trial 4473 finished with value: 0.4037445428727659 and parameters: {'alpha': 1.0049898354206254e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:46,987] Trial 4474 finished with value: 0.4037445678428458 and parameters: {'alpha': 1.0149317638670966e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,023] Trial 4475 finished with value: 0.40374658712710715 and parameters: {'alpha': 1.3352720668822502}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|████████▉ | 4481/5000 [02:14<00:19, 26.04it/s]

[I 2026-06-14 00:50:47,063] Trial 4476 finished with value: 0.4037451720340533 and parameters: {'alpha': 3.973071601899455e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,102] Trial 4477 finished with value: 0.4037450706982924 and parameters: {'alpha': 2.7244595333978126e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,140] Trial 4478 finished with value: 0.4037445543902553 and parameters: {'alpha': 1.0183662132978216e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,177] Trial 4479 finished with value: 0.40374448938454466 and parameters: {'alpha': 1.0102385468919367e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,217] Trial 4480 finished with value: 0.40374531525019475 and parameters: {'alpha': 9.64613647766937e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,255] Trial 4481 finished with value: 0.40374502743481716 and parameters: {'alpha': 2.6308512384850426e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|████████▉ | 4487/5000 [02:14<00:19, 26.20it/s]

[I 2026-06-14 00:50:47,292] Trial 4482 finished with value: 0.40374487067163284 and parameters: {'alpha': 1.7578021148845914e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,330] Trial 4483 finished with value: 0.40374503054880023 and parameters: {'alpha': 2.6568434094669447e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,368] Trial 4484 finished with value: 0.4037446575988329 and parameters: {'alpha': 1.0159814657597657e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,405] Trial 4485 finished with value: 0.40374447759612864 and parameters: {'alpha': 1.0108399030471554e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,444] Trial 4486 finished with value: 0.4037443542709126 and parameters: {'alpha': 1.0023717516650436e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,481] Trial 4487 finished with value: 0.4037452284136212 and parameters: {'alpha': 4.419460649144434e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|████████▉ | 4492/5000 [02:15<00:19, 25.77it/s]

[I 2026-06-14 00:50:47,520] Trial 4488 finished with value: 0.4037450448346348 and parameters: {'alpha': 2.7785393660531185e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,561] Trial 4489 finished with value: 0.40374495426006385 and parameters: {'alpha': 1.678327182156307e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,601] Trial 4490 finished with value: 0.4037444224913893 and parameters: {'alpha': 1.0013915429647591e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:47,640] Trial 4491 finished with value: 0.40374527700785895 and parameters: {'alpha': 4.607486277455902e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|████████▉ | 4496/5000 [02:15<00:45, 11.03it/s]

[I 2026-06-14 00:50:48,177] Trial 4492 finished with value: 0.40374453201475685 and parameters: {'alpha': 1.0040126881789685e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,225] Trial 4493 finished with value: 0.40374501818863084 and parameters: {'alpha': 2.6582217211734304e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,274] Trial 4494 finished with value: 0.403744861951621 and parameters: {'alpha': 1.7292292250070957e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,325] Trial 4495 finished with value: 0.40374525368238273 and parameters: {'alpha': 6.774477092143026e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,376] Trial 4496 finished with value: 0.40374501920475825 and parameters: {'alpha': 2.6532287063881598e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|█████████ | 4502/5000 [02:15<00:32, 15.46it/s]

[I 2026-06-14 00:50:48,430] Trial 4497 finished with value: 0.40374499126126984 and parameters: {'alpha': 1.777871174647792e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,478] Trial 4498 finished with value: 0.4037446583398875 and parameters: {'alpha': 1.01012889474834e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,528] Trial 4499 finished with value: 0.4037449084948229 and parameters: {'alpha': 1.7949031036069317e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,576] Trial 4500 finished with value: 0.40374524883978036 and parameters: {'alpha': 3.704480113252491e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,617] Trial 4501 finished with value: 0.4037449192956756 and parameters: {'alpha': 1.819916800688741e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|█████████ | 4508/5000 [02:16<00:24, 19.80it/s]

[I 2026-06-14 00:50:48,656] Trial 4502 finished with value: 0.4037452641454089 and parameters: {'alpha': 4.41967818307873e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,695] Trial 4503 finished with value: 0.40374488548876586 and parameters: {'alpha': 1.741683538952784e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,734] Trial 4504 finished with value: 0.4037453211980067 and parameters: {'alpha': 9.87337281908086e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,773] Trial 4505 finished with value: 0.40374506906229385 and parameters: {'alpha': 2.599563514321918e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,811] Trial 4506 finished with value: 0.403825089806976 and parameters: {'alpha': 28.831371363665717}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,848] Trial 4507 finished with value: 0.40374476974284745 and parameters: {'alpha': 1.0115207867972002e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|█████████ | 4514/5000 [02:16<00:21, 22.68it/s]

[I 2026-06-14 00:50:48,888] Trial 4508 finished with value: 0.4037447778776908 and parameters: {'alpha': 1.7137470100140494e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,926] Trial 4509 finished with value: 0.4037452312298043 and parameters: {'alpha': 4.619277369054731e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:48,964] Trial 4510 finished with value: 0.4037447962427611 and parameters: {'alpha': 1.8006786582062034e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,002] Trial 4511 finished with value: 0.4037454066655709 and parameters: {'alpha': 0.0002737860292660825}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,039] Trial 4512 finished with value: 0.40374503195818107 and parameters: {'alpha': 2.8638647427841744e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,078] Trial 4513 finished with value: 0.4037448241769999 and parameters: {'alpha': 1.6985379214590127e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|█████████ | 4520/5000 [02:16<00:19, 24.34it/s]

[I 2026-06-14 00:50:49,118] Trial 4514 finished with value: 0.4037452778682056 and parameters: {'alpha': 4.416898527831783e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,157] Trial 4515 finished with value: 0.40374492575971455 and parameters: {'alpha': 1.7594833900997065e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,195] Trial 4516 finished with value: 0.4037449727952036 and parameters: {'alpha': 2.7026204069967657e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,234] Trial 4517 finished with value: 0.40374528974871055 and parameters: {'alpha': 7.54305868515672e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,272] Trial 4518 finished with value: 0.4037447779124043 and parameters: {'alpha': 1.805088911557608e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,309] Trial 4519 finished with value: 0.40374490458526674 and parameters: {'alpha': 1.702737797692878e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  90%|█████████ | 4524/5000 [02:16<00:20, 23.14it/s]

[I 2026-06-14 00:50:49,347] Trial 4520 finished with value: 0.4037452885374885 and parameters: {'alpha': 3.913279321589948e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,388] Trial 4521 finished with value: 0.40374473132328437 and parameters: {'alpha': 1.7139228091940184e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,452] Trial 4522 finished with value: 0.40374473858153187 and parameters: {'alpha': 1.6841998003732023e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,493] Trial 4523 finished with value: 0.4037450427271948 and parameters: {'alpha': 2.7968794175692756e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,538] Trial 4524 finished with value: 0.4037446651528953 and parameters: {'alpha': 1.0049260692912336e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████ | 4529/5000 [02:17<00:20, 23.22it/s]

[I 2026-06-14 00:50:49,579] Trial 4525 finished with value: 0.4037445696187238 and parameters: {'alpha': 1.0010378392563502e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,633] Trial 4526 finished with value: 0.40374466475791015 and parameters: {'alpha': 1.0167588977962079e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,671] Trial 4527 finished with value: 0.40374432661467424 and parameters: {'alpha': 1.0106745326731879e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,710] Trial 4528 finished with value: 0.4037450448966846 and parameters: {'alpha': 2.6899014649460497e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,751] Trial 4529 finished with value: 0.40374523460037925 and parameters: {'alpha': 6.131680870964497e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████ | 4535/5000 [02:17<00:19, 24.20it/s]

[I 2026-06-14 00:50:49,790] Trial 4530 finished with value: 0.40374511182087125 and parameters: {'alpha': 3.060165991978174e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,829] Trial 4531 finished with value: 0.4037443883553545 and parameters: {'alpha': 1.00449981631989e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,870] Trial 4532 finished with value: 0.4037453455516085 and parameters: {'alpha': 1.4497355438068152e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,909] Trial 4533 finished with value: 0.4037449026769796 and parameters: {'alpha': 1.756947041099918e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,947] Trial 4534 finished with value: 0.4037452567487534 and parameters: {'alpha': 4.426661787803321e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:49,987] Trial 4535 finished with value: 0.4037449872726839 and parameters: {'alpha': 2.5526145537963704e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████ | 4541/5000 [02:17<00:18, 24.62it/s]

[I 2026-06-14 00:50:50,030] Trial 4536 finished with value: 0.4037449353834404 and parameters: {'alpha': 1.7114218053306894e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,070] Trial 4537 finished with value: 0.40374540604340026 and parameters: {'alpha': 1.969403660726982e-05}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,112] Trial 4538 finished with value: 0.40374481052796374 and parameters: {'alpha': 1.7689982134455842e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,150] Trial 4539 finished with value: 0.40374436297321464 and parameters: {'alpha': 1.0017481462230286e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,189] Trial 4540 finished with value: 0.4037452743187575 and parameters: {'alpha': 5.988166180256248e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,227] Trial 4541 finished with value: 0.4037450476257524 and parameters: {'alpha': 2.6050921698079885e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████ | 4547/5000 [02:17<00:19, 23.07it/s]

[I 2026-06-14 00:50:50,266] Trial 4542 finished with value: 0.4037451685608422 and parameters: {'alpha': 3.869410071193427e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,322] Trial 4543 finished with value: 0.4037447835299256 and parameters: {'alpha': 1.7276131440328424e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,378] Trial 4544 finished with value: 0.4037442476894709 and parameters: {'alpha': 1.0073801677220817e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,426] Trial 4545 finished with value: 0.403744957321291 and parameters: {'alpha': 2.590957922584619e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,464] Trial 4546 finished with value: 0.4037453101089909 and parameters: {'alpha': 8.745879880933209e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████ | 4551/5000 [02:18<00:19, 23.45it/s]

[I 2026-06-14 00:50:50,506] Trial 4547 finished with value: 0.40374485828005874 and parameters: {'alpha': 1.624593574912768e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,547] Trial 4548 finished with value: 0.4037449760369501 and parameters: {'alpha': 1.7237809656240328e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,586] Trial 4549 finished with value: 0.40374499775942846 and parameters: {'alpha': 2.8133639723664478e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,629] Trial 4550 finished with value: 0.40374474653213843 and parameters: {'alpha': 1.690366604848517e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,670] Trial 4551 finished with value: 0.403744869781122 and parameters: {'alpha': 1.716942640179564e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████ | 4557/5000 [02:18<00:18, 24.44it/s]

[I 2026-06-14 00:50:50,709] Trial 4552 finished with value: 0.40374429948237744 and parameters: {'alpha': 1.0033304926961538e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,749] Trial 4553 finished with value: 0.40374525578993414 and parameters: {'alpha': 4.078595136249171e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,786] Trial 4554 finished with value: 0.4037451909595571 and parameters: {'alpha': 3.946412288861596e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,824] Trial 4555 finished with value: 0.4037448837846766 and parameters: {'alpha': 1.691940062122894e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,864] Trial 4556 finished with value: 0.4037449795793007 and parameters: {'alpha': 2.807675818720292e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,903] Trial 4557 finished with value: 0.4037452814800133 and parameters: {'alpha': 7.841351786903436e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████▏| 4563/5000 [02:18<00:17, 25.04it/s]

[I 2026-06-14 00:50:50,942] Trial 4558 finished with value: 0.4037450612631924 and parameters: {'alpha': 2.6965226063757026e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:50,982] Trial 4559 finished with value: 0.40374482563410896 and parameters: {'alpha': 1.7238051200309033e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,019] Trial 4560 finished with value: 0.40374482900842873 and parameters: {'alpha': 1.6861735371543866e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,059] Trial 4561 finished with value: 0.40374443771899127 and parameters: {'alpha': 1.001920759023085e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,099] Trial 4562 finished with value: 0.40374524706357356 and parameters: {'alpha': 4.5246394683679097e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,139] Trial 4563 finished with value: 0.40374484104292074 and parameters: {'alpha': 1.701343862375416e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████▏| 4569/5000 [02:18<00:17, 25.07it/s]

[I 2026-06-14 00:50:51,179] Trial 4564 finished with value: 0.4037450079669581 and parameters: {'alpha': 2.794662989039216e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,219] Trial 4565 finished with value: 0.4037445312394553 and parameters: {'alpha': 1.0060808915216926e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,258] Trial 4566 finished with value: 0.40374529263096903 and parameters: {'alpha': 5.09956908943299e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,297] Trial 4567 finished with value: 0.40374446163194005 and parameters: {'alpha': 1.014622303251651e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,337] Trial 4568 finished with value: 0.4037447386019322 and parameters: {'alpha': 1.7152512895100434e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,376] Trial 4569 finished with value: 0.40374511093072857 and parameters: {'alpha': 2.9215851227005227e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  91%|█████████▏| 4574/5000 [02:18<00:16, 25.30it/s]

[I 2026-06-14 00:50:51,415] Trial 4570 finished with value: 0.4037454088148074 and parameters: {'alpha': 0.0034473239165795206}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,456] Trial 4571 finished with value: 0.40374497381021096 and parameters: {'alpha': 2.7046383821346083e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,495] Trial 4572 finished with value: 0.4037452862424157 and parameters: {'alpha': 6.460580418448376e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,533] Trial 4573 finished with value: 0.40374475008303284 and parameters: {'alpha': 1.689224768990383e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,575] Trial 4574 finished with value: 0.40374490571945876 and parameters: {'alpha': 1.6256997810281674e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:50:51,619] Trial 4575 finished with value: 0.40374471187261957 and parameters: {'alpha': 1.6492271153078e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,665] Trial 4576 finished with value: 0.40374431810394373 and parameters: {'alpha': 1.0080669573846365e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,705] Trial 4577 finished with value: 0.40374518145193944 and parameters: {'alpha': 3.964361931935905e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,743] Trial 4578 finished with value: 0.40374534063187373 and parameters: {'alpha': 1.2583059025597866e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,781] Trial 4579 finished with value: 0.4037449784991276 and parameters: {'alpha': 2.6689476888211707e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,820] Trial 4580 finished with value: 0.40374472205003875 and parameters: {'alpha': 1.6744379365724973e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  92%|█████████▏| 4586/5000 [02:19<00:16, 24.97it/s]

[I 2026-06-14 00:50:51,863] Trial 4581 finished with value: 0.4037449173801067 and parameters: {'alpha': 1.7064323211147487e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,904] Trial 4582 finished with value: 0.40374524140837775 and parameters: {'alpha': 4.0758912333156216e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,944] Trial 4583 finished with value: 0.40374508446757573 and parameters: {'alpha': 2.640988217140082e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:51,984] Trial 4584 finished with value: 0.4037443167884433 and parameters: {'alpha': 1.0063734414729079e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,022] Trial 4585 finished with value: 0.4037449309657489 and parameters: {'alpha': 1.7008922931004024e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,060] Trial 4586 finished with value: 0.4037450122377038 and parameters: {'alpha': 2.7471993626322575e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  92%|█████████▏| 4592/5000 [02:19<00:16, 25.19it/s]

[I 2026-06-14 00:50:52,099] Trial 4587 finished with value: 0.4037453041303402 and parameters: {'alpha': 5.638486433383705e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,139] Trial 4588 finished with value: 0.40374432588458764 and parameters: {'alpha': 1.0129921509038446e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,180] Trial 4589 finished with value: 0.4037449499538465 and parameters: {'alpha': 1.71967692518434e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,218] Trial 4590 finished with value: 0.403744938749353 and parameters: {'alpha': 1.7331919127642366e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,258] Trial 4591 finished with value: 0.40374526415507545 and parameters: {'alpha': 4.023900738756654e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,298] Trial 4592 finished with value: 0.40374441892968516 and parameters: {'alpha': 1.0037075501555811e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  92%|█████████▏| 4598/5000 [02:19<00:15, 25.25it/s]

[I 2026-06-14 00:50:52,337] Trial 4593 finished with value: 0.4037445567578512 and parameters: {'alpha': 1.000811037179409e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,378] Trial 4594 finished with value: 0.40374505211460776 and parameters: {'alpha': 2.5416775835067875e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,417] Trial 4595 finished with value: 0.4037445248423684 and parameters: {'alpha': 1.001584346311224e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,457] Trial 4596 finished with value: 0.4037445683781938 and parameters: {'alpha': 1.0075144334346447e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,495] Trial 4597 finished with value: 0.4037444410041022 and parameters: {'alpha': 1.0046071461351863e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,536] Trial 4598 finished with value: 0.4037452711809645 and parameters: {'alpha': 5.713624418576017e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:50:52,575] Trial 4599 finished with value: 0.4037445828274388 and parameters: {'alpha': 1.0153712222399631e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,614] Trial 4600 finished with value: 0.4037450210109096 and parameters: {'alpha': 2.5689845891816103e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,656] Trial 4601 finished with value: 0.403745026449029 and parameters: {'alpha': 2.584667846473168e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,697] Trial 4602 finished with value: 0.4037452600857156 and parameters: {'alpha': 7.99022058008404e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,736] Trial 4603 finished with value: 0.40374480288151016 and parameters: {'alpha': 1.723369402774433e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,776] Trial 4604 finished with value: 0.403745033483059 and parameters: {'alpha': 2.7324092484191114e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  92%|█████████▏| 4610/5000 [02:20<00:15, 25.29it/s]

[I 2026-06-14 00:50:52,815] Trial 4605 finished with value: 0.4037448285812393 and parameters: {'alpha': 1.7725400932005718e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,852] Trial 4606 finished with value: 0.40374438216501285 and parameters: {'alpha': 1.0168200123333504e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,893] Trial 4607 finished with value: 0.40374528574456026 and parameters: {'alpha': 4.2400730215682465e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,931] Trial 4608 finished with value: 0.4037448917501574 and parameters: {'alpha': 1.716554164946055e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:52,970] Trial 4609 finished with value: 0.40374536325219273 and parameters: {'alpha': 2.4233184594902693e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,011] Trial 4610 finished with value: 0.4037450981538543 and parameters: {'alpha': 2.7770869410344842e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  92%|█████████▏| 4616/5000 [02:20<00:15, 25.21it/s]

[I 2026-06-14 00:50:53,050] Trial 4611 finished with value: 0.4037443203024062 and parameters: {'alpha': 1.005313751826654e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,091] Trial 4612 finished with value: 0.4037442713905412 and parameters: {'alpha': 1.012923179979667e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,131] Trial 4613 finished with value: 0.4037452436523191 and parameters: {'alpha': 4.573781602158287e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,170] Trial 4614 finished with value: 0.4037453187987867 and parameters: {'alpha': 1.1393693224947782e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,210] Trial 4615 finished with value: 0.40374507485538463 and parameters: {'alpha': 2.6762368540589612e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,249] Trial 4616 finished with value: 0.4037447057949949 and parameters: {'alpha': 1.0110619315096284e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  92%|█████████▏| 4622/5000 [02:20<00:15, 24.89it/s]

[I 2026-06-14 00:50:53,289] Trial 4617 finished with value: 0.40374478164612654 and parameters: {'alpha': 1.7496211951084547e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,330] Trial 4618 finished with value: 0.40374494330224314 and parameters: {'alpha': 1.766818150812572e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,369] Trial 4619 finished with value: 0.40374520156195176 and parameters: {'alpha': 4.146242632598487e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,408] Trial 4620 finished with value: 0.4037448911426898 and parameters: {'alpha': 1.8013597295012813e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,452] Trial 4621 finished with value: 0.4037450734144481 and parameters: {'alpha': 2.7822429358339105e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  93%|█████████▎| 4626/5000 [02:21<00:15, 24.55it/s]

[I 2026-06-14 00:50:53,499] Trial 4622 finished with value: 0.4037452826455603 and parameters: {'alpha': 7.569925762424902e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,539] Trial 4623 finished with value: 0.40374480258275397 and parameters: {'alpha': 1.7431554547779152e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,580] Trial 4624 finished with value: 0.40374456729486297 and parameters: {'alpha': 1.015972379741035e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,620] Trial 4625 finished with value: 0.403745087935243 and parameters: {'alpha': 2.7019342404621834e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,662] Trial 4626 finished with value: 0.4037444902316791 and parameters: {'alpha': 1.0172442877281796e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:50:53,706] Trial 4627 finished with value: 0.4037444273566438 and parameters: {'alpha': 1.0101705628863919e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,749] Trial 4628 finished with value: 0.40374526073501754 and parameters: {'alpha': 4.11298572501184e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,790] Trial 4629 finished with value: 0.4037447574489175 and parameters: {'alpha': 1.7621448920441647e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,829] Trial 4630 finished with value: 0.40374502596751927 and parameters: {'alpha': 2.6842970024882514e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,868] Trial 4631 finished with value: 0.4037448557852856 and parameters: {'alpha': 1.7169294396741432e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  93%|█████████▎| 4637/5000 [02:21<00:14, 24.81it/s]

[I 2026-06-14 00:50:53,909] Trial 4632 finished with value: 0.4037452845176927 and parameters: {'alpha': 6.211656114429268e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,950] Trial 4633 finished with value: 0.4037448288608027 and parameters: {'alpha': 1.729097560392967e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:53,989] Trial 4634 finished with value: 0.4037452495496304 and parameters: {'alpha': 3.7374911293081404e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,028] Trial 4635 finished with value: 0.40374451321909705 and parameters: {'alpha': 1.0185441301620579e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,067] Trial 4636 finished with value: 0.40374445289855027 and parameters: {'alpha': 1.0047207083393934e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,107] Trial 4637 finished with value: 0.4037450029322559 and parameters: {'alpha': 2.8012120283066157e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  93%|█████████▎| 4643/5000 [02:21<00:14, 25.20it/s]

[I 2026-06-14 00:50:54,146] Trial 4638 finished with value: 0.40374486215970556 and parameters: {'alpha': 1.7749003036018842e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,185] Trial 4639 finished with value: 0.40374442170081304 and parameters: {'alpha': 1.0141361748571494e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,225] Trial 4640 finished with value: 0.4037452646342102 and parameters: {'alpha': 4.17840520787587e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,263] Trial 4641 finished with value: 0.40374502789848604 and parameters: {'alpha': 2.6297158181165387e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,302] Trial 4642 finished with value: 0.4037449153069378 and parameters: {'alpha': 1.714855890878493e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,342] Trial 4643 finished with value: 0.40374528969754203 and parameters: {'alpha': 7.38011233569458e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  93%|█████████▎| 4649/5000 [02:21<00:13, 25.39it/s]

[I 2026-06-14 00:50:54,380] Trial 4644 finished with value: 0.40374490150129394 and parameters: {'alpha': 1.7958157620858807e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,419] Trial 4645 finished with value: 0.40374477234304706 and parameters: {'alpha': 1.7020704371998446e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,459] Trial 4646 finished with value: 0.4037451595652442 and parameters: {'alpha': 3.9260686824503686e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,497] Trial 4647 finished with value: 0.4037449860477676 and parameters: {'alpha': 2.6917163386715937e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,536] Trial 4648 finished with value: 0.4037445580270826 and parameters: {'alpha': 1.0080125925419026e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,575] Trial 4649 finished with value: 0.4037449264108014 and parameters: {'alpha': 1.659741973980471e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  93%|█████████▎| 4655/5000 [02:22<00:13, 25.11it/s]

[I 2026-06-14 00:50:54,613] Trial 4650 finished with value: 0.4037449236972944 and parameters: {'alpha': 1.718082589393568e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,653] Trial 4651 finished with value: 0.40374533008739094 and parameters: {'alpha': 1.1801092477804025e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,696] Trial 4652 finished with value: 0.40374525973836684 and parameters: {'alpha': 4.50729399562541e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,736] Trial 4653 finished with value: 0.40374478794030483 and parameters: {'alpha': 1.7201837444221375e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,777] Trial 4654 finished with value: 0.4037449896638643 and parameters: {'alpha': 2.7104924424610826e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  93%|█████████▎| 4661/5000 [02:22<00:13, 25.27it/s]

[I 2026-06-14 00:50:54,818] Trial 4655 finished with value: 0.40374489694783183 and parameters: {'alpha': 1.7848963609996625e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,859] Trial 4656 finished with value: 0.4037452355673242 and parameters: {'alpha': 6.183917969588472e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,897] Trial 4657 finished with value: 0.40374425415295545 and parameters: {'alpha': 1.0243876193396115e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,938] Trial 4658 finished with value: 0.40374501955603226 and parameters: {'alpha': 2.8534770246624876e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:54,977] Trial 4659 finished with value: 0.40374490614922076 and parameters: {'alpha': 1.6832996941239172e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,014] Trial 4660 finished with value: 0.40374524601612594 and parameters: {'alpha': 4.513781017127895e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  93%|█████████▎| 4665/5000 [02:22<00:13, 25.24it/s]

[I 2026-06-14 00:50:55,055] Trial 4661 finished with value: 0.40374472457368416 and parameters: {'alpha': 1.6919026262399557e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,095] Trial 4662 finished with value: 0.4037445530072494 and parameters: {'alpha': 1.0222014645962112e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,134] Trial 4663 finished with value: 0.4037450336836497 and parameters: {'alpha': 2.6310264152151777e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,176] Trial 4664 finished with value: 0.4037450450591596 and parameters: {'alpha': 2.7035018706658206e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,217] Trial 4665 finished with value: 0.403744862719625 and parameters: {'alpha': 1.6652651870409142e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  93%|█████████▎| 4670/5000 [02:22<00:13, 24.83it/s]

[I 2026-06-14 00:50:55,259] Trial 4666 finished with value: 0.40374518748040944 and parameters: {'alpha': 3.7036715471051646e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,300] Trial 4667 finished with value: 0.40374490317900025 and parameters: {'alpha': 1.7255370809983134e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,339] Trial 4668 finished with value: 0.40374530864637753 and parameters: {'alpha': 7.741344568686902e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,379] Trial 4669 finished with value: 0.4037444231754127 and parameters: {'alpha': 1.007444372190863e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,426] Trial 4670 finished with value: 0.40374482023957076 and parameters: {'alpha': 1.7042660507187738e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▎| 4676/5000 [02:22<00:13, 24.44it/s]

[I 2026-06-14 00:50:55,467] Trial 4671 finished with value: 0.40374524480053675 and parameters: {'alpha': 3.8777754447219e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,508] Trial 4672 finished with value: 0.40374475547165667 and parameters: {'alpha': 1.6661587822823718e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,548] Trial 4673 finished with value: 0.4037451234769584 and parameters: {'alpha': 2.996555960897406e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,587] Trial 4674 finished with value: 0.4037448595199355 and parameters: {'alpha': 1.6786686976301566e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,629] Trial 4675 finished with value: 0.4037452400894243 and parameters: {'alpha': 6.491526101338818e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▎| 4680/5000 [02:23<00:13, 23.47it/s]

[I 2026-06-14 00:50:55,672] Trial 4676 finished with value: 0.4037450189141793 and parameters: {'alpha': 2.6659532601008054e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,729] Trial 4677 finished with value: 0.4037449037728225 and parameters: {'alpha': 1.626606711165325e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,770] Trial 4678 finished with value: 0.40374473374708375 and parameters: {'alpha': 1.017980596434425e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,813] Trial 4679 finished with value: 0.40374438040838817 and parameters: {'alpha': 1.006879143271739e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,855] Trial 4680 finished with value: 0.4037446222573577 and parameters: {'alpha': 1.0254151249585508e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▎| 4685/5000 [02:23<00:13, 23.67it/s]

[I 2026-06-14 00:50:55,898] Trial 4681 finished with value: 0.40376780485056973 and parameters: {'alpha': 11.286443985986763}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,940] Trial 4682 finished with value: 0.4037443141575609 and parameters: {'alpha': 1.0016775562922293e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:55,981] Trial 4683 finished with value: 0.4037443572297096 and parameters: {'alpha': 1.0021886946297612e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,021] Trial 4684 finished with value: 0.40374433047611824 and parameters: {'alpha': 1.0119647996727631e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,064] Trial 4685 finished with value: 0.4037450208702649 and parameters: {'alpha': 2.88541377383587e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▍| 4691/5000 [02:23<00:13, 23.65it/s]

[I 2026-06-14 00:50:56,105] Trial 4686 finished with value: 0.403745251961729 and parameters: {'alpha': 5.227082892124439e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,150] Trial 4687 finished with value: 0.40374541491044447 and parameters: {'alpha': 0.012548936399845908}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,193] Trial 4688 finished with value: 0.40374534071471785 and parameters: {'alpha': 1.3427301111111422e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,234] Trial 4689 finished with value: 0.40374425296532235 and parameters: {'alpha': 1.0020252786826824e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,275] Trial 4690 finished with value: 0.40374450824890734 and parameters: {'alpha': 1.0010044039450507e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▍| 4696/5000 [02:23<00:12, 23.82it/s]

[I 2026-06-14 00:50:56,318] Trial 4691 finished with value: 0.4037450742853243 and parameters: {'alpha': 2.873577901901127e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,358] Trial 4692 finished with value: 0.4037453771214419 and parameters: {'alpha': 4.534111510385822e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,401] Trial 4693 finished with value: 0.40374505690336276 and parameters: {'alpha': 2.736076049405284e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,442] Trial 4694 finished with value: 0.40428491765286 and parameters: {'alpha': 189.35657731359666}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,480] Trial 4695 finished with value: 0.40374527501805674 and parameters: {'alpha': 4.4084229692602876e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,519] Trial 4696 finished with value: 0.4037448549449972 and parameters: {'alpha': 1.741317307566341e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▍| 4701/5000 [02:24<00:12, 24.44it/s]

[I 2026-06-14 00:50:56,560] Trial 4697 finished with value: 0.40374476360069517 and parameters: {'alpha': 1.7326035888233345e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,599] Trial 4698 finished with value: 0.40374503202356743 and parameters: {'alpha': 2.5804581110702217e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,638] Trial 4699 finished with value: 0.4037453092184707 and parameters: {'alpha': 5.9069560393075914e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,680] Trial 4700 finished with value: 0.40374451439146175 and parameters: {'alpha': 1.0092889247814951e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,723] Trial 4701 finished with value: 0.40374505167757024 and parameters: {'alpha': 2.6754775555674513e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▍| 4707/5000 [02:24<00:11, 24.57it/s]

[I 2026-06-14 00:50:56,765] Trial 4702 finished with value: 0.4037449607698135 and parameters: {'alpha': 1.745161585545724e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,806] Trial 4703 finished with value: 0.40374491117932065 and parameters: {'alpha': 1.733602430188259e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,846] Trial 4704 finished with value: 0.4037445034000211 and parameters: {'alpha': 1.0036285830522776e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,883] Trial 4705 finished with value: 0.40374523451042493 and parameters: {'alpha': 3.823297499507579e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,925] Trial 4706 finished with value: 0.4037446322588009 and parameters: {'alpha': 1.0178090154095735e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:56,964] Trial 4707 finished with value: 0.4037449685732537 and parameters: {'alpha': 1.7490135618304038e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▍| 4712/5000 [02:24<00:11, 24.37it/s]

[I 2026-06-14 00:50:57,004] Trial 4708 finished with value: 0.40374529985028224 and parameters: {'alpha': 9.711400654999223e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,046] Trial 4709 finished with value: 0.40374499930905533 and parameters: {'alpha': 2.663108954885387e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,086] Trial 4710 finished with value: 0.4037448133588089 and parameters: {'alpha': 1.703783879498508e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,129] Trial 4711 finished with value: 0.403745243732117 and parameters: {'alpha': 4.2800960911770485e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,174] Trial 4712 finished with value: 0.4037446298915923 and parameters: {'alpha': 1.0204021292136037e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▍| 4718/5000 [02:24<00:11, 24.17it/s]

[I 2026-06-14 00:50:57,217] Trial 4713 finished with value: 0.4037448956678183 and parameters: {'alpha': 1.743770600397983e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,260] Trial 4714 finished with value: 0.4037445023163518 and parameters: {'alpha': 1.0059496091448045e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,303] Trial 4715 finished with value: 0.40374505091412277 and parameters: {'alpha': 2.7061490987735593e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,343] Trial 4716 finished with value: 0.4037452586369662 and parameters: {'alpha': 6.173761229154751e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,382] Trial 4717 finished with value: 0.4037448676000117 and parameters: {'alpha': 1.6690766450806534e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  94%|█████████▍| 4723/5000 [02:24<00:11, 24.38it/s]

[I 2026-06-14 00:50:57,424] Trial 4718 finished with value: 0.40374506114635544 and parameters: {'alpha': 2.717823156863139e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,463] Trial 4719 finished with value: 0.40374527438826485 and parameters: {'alpha': 3.97681588136204e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,501] Trial 4720 finished with value: 0.4037448976523917 and parameters: {'alpha': 1.840905969751886e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,546] Trial 4721 finished with value: 0.4037445034926642 and parameters: {'alpha': 1.0205095492228888e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,586] Trial 4722 finished with value: 0.40374479579495837 and parameters: {'alpha': 1.724012158151398e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,624] Trial 4723 finished with value: 0.4037450569932076 and parameters: {'alpha': 2.5624137542501874e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▍| 4728/5000 [02:25<00:11, 24.38it/s]

[I 2026-06-14 00:50:57,667] Trial 4724 finished with value: 0.40374446680834136 and parameters: {'alpha': 1.0065676022116169e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,706] Trial 4725 finished with value: 0.40374527260727977 and parameters: {'alpha': 6.240946622433146e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,749] Trial 4726 finished with value: 0.4037452132943634 and parameters: {'alpha': 4.0770347832252105e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,789] Trial 4727 finished with value: 0.4037450379972764 and parameters: {'alpha': 2.624156093516091e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,833] Trial 4728 finished with value: 0.4037446152559375 and parameters: {'alpha': 1.0034040353011035e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▍| 4733/5000 [02:25<00:11, 23.70it/s]

[I 2026-06-14 00:50:57,877] Trial 4729 finished with value: 0.403744807578724 and parameters: {'alpha': 1.722203821654484e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,922] Trial 4730 finished with value: 0.40374531389586066 and parameters: {'alpha': 1.0767961333809288e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:57,964] Trial 4731 finished with value: 0.40374486698327167 and parameters: {'alpha': 1.8513624051909966e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,007] Trial 4732 finished with value: 0.4037444367534094 and parameters: {'alpha': 1.017968677719315e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,051] Trial 4733 finished with value: 0.40374434923059405 and parameters: {'alpha': 1.0088957741121903e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▍| 4739/5000 [02:25<00:10, 24.06it/s]

[I 2026-06-14 00:50:58,092] Trial 4734 finished with value: 0.40374523139383595 and parameters: {'alpha': 3.7189322511977484e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,134] Trial 4735 finished with value: 0.4037451043527253 and parameters: {'alpha': 2.746609930119333e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,175] Trial 4736 finished with value: 0.4037448780118723 and parameters: {'alpha': 1.6882117421978093e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,213] Trial 4737 finished with value: 0.4037448394207566 and parameters: {'alpha': 1.7469258874211805e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,255] Trial 4738 finished with value: 0.4037453048416061 and parameters: {'alpha': 5.871436560264917e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▍| 4744/5000 [02:25<00:10, 24.37it/s]

[I 2026-06-14 00:50:58,296] Trial 4739 finished with value: 0.403744584605976 and parameters: {'alpha': 1.0175756585466805e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,336] Trial 4740 finished with value: 0.4037449945672556 and parameters: {'alpha': 2.6230185257802395e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,374] Trial 4741 finished with value: 0.4037443227638992 and parameters: {'alpha': 1.0120678308746227e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,414] Trial 4742 finished with value: 0.40374525794386645 and parameters: {'alpha': 4.183989385338561e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,453] Trial 4743 finished with value: 0.40374481286574854 and parameters: {'alpha': 1.771962268816936e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,496] Trial 4744 finished with value: 0.40374494222279544 and parameters: {'alpha': 1.7618875096727123e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▌| 4750/5000 [02:26<00:10, 24.68it/s]

[I 2026-06-14 00:50:58,537] Trial 4745 finished with value: 0.4037453560211568 and parameters: {'alpha': 1.7908786115505327e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,577] Trial 4746 finished with value: 0.40374434694459493 and parameters: {'alpha': 1.014914734441761e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,615] Trial 4747 finished with value: 0.4037450383597793 and parameters: {'alpha': 2.7759961681031635e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,655] Trial 4748 finished with value: 0.40374445246591983 and parameters: {'alpha': 1.0014372181729841e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,694] Trial 4749 finished with value: 0.4037443273117451 and parameters: {'alpha': 1.0102950497680771e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,737] Trial 4750 finished with value: 0.4037452117264898 and parameters: {'alpha': 4.243204087831291e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▌| 4757/5000 [02:26<00:09, 24.85it/s]

[I 2026-06-14 00:50:58,779] Trial 4751 finished with value: 0.40374499301925726 and parameters: {'alpha': 2.6184526486606254e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,817] Trial 4752 finished with value: 0.4037448108405717 and parameters: {'alpha': 1.7128881131114386e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,855] Trial 4753 finished with value: 0.4037449665866709 and parameters: {'alpha': 2.6612147680651957e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,897] Trial 4754 finished with value: 0.4037453137760155 and parameters: {'alpha': 8.565824977445289e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,937] Trial 4755 finished with value: 0.40374473824169727 and parameters: {'alpha': 1.7314533787918753e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:58,977] Trial 4756 finished with value: 0.4037452753575611 and parameters: {'alpha': 4.664878186526299e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▌| 4761/5000 [02:26<00:09, 24.77it/s]

[I 2026-06-14 00:50:59,019] Trial 4757 finished with value: 0.40374484242125375 and parameters: {'alpha': 1.6679585623375583e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,060] Trial 4758 finished with value: 0.4037449649540362 and parameters: {'alpha': 1.7440662644735448e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,098] Trial 4759 finished with value: 0.4037446832558965 and parameters: {'alpha': 1.0115620923857005e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,155] Trial 4760 finished with value: 0.4037450240410879 and parameters: {'alpha': 2.644527610549395e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,213] Trial 4761 finished with value: 0.40374430682585927 and parameters: {'alpha': 1.0001071212283886e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▌| 4767/5000 [02:26<00:10, 23.23it/s]

[I 2026-06-14 00:50:59,260] Trial 4762 finished with value: 0.40374524670530026 and parameters: {'alpha': 4.4103090877627165e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,305] Trial 4763 finished with value: 0.40374484375915226 and parameters: {'alpha': 1.718905383496175e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,342] Trial 4764 finished with value: 0.4037452630992997 and parameters: {'alpha': 7.196276063948747e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,380] Trial 4765 finished with value: 0.4037446550351335 and parameters: {'alpha': 1.0122380658230973e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,419] Trial 4766 finished with value: 0.4037450956979645 and parameters: {'alpha': 2.6379357345379963e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,458] Trial 4767 finished with value: 0.4037452750173181 and parameters: {'alpha': 4.1570738461103175e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  95%|█████████▌| 4773/5000 [02:27<00:09, 24.32it/s]

[I 2026-06-14 00:50:59,498] Trial 4768 finished with value: 0.4037450318177686 and parameters: {'alpha': 2.8117960253051193e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,538] Trial 4769 finished with value: 0.4037447748900605 and parameters: {'alpha': 1.7325170544948483e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,578] Trial 4770 finished with value: 0.40374466885536725 and parameters: {'alpha': 1.0054977105194205e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,616] Trial 4771 finished with value: 0.4037447838129849 and parameters: {'alpha': 1.8438460828613204e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,656] Trial 4772 finished with value: 0.4037448387933304 and parameters: {'alpha': 1.7778317090905383e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,694] Trial 4773 finished with value: 0.40374523886104596 and parameters: {'alpha': 4.084372437797127e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  96%|█████████▌| 4778/5000 [02:27<00:09, 24.17it/s]

[I 2026-06-14 00:50:59,734] Trial 4774 finished with value: 0.4037447961369381 and parameters: {'alpha': 1.7414647673197256e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,779] Trial 4775 finished with value: 0.4037450567657197 and parameters: {'alpha': 2.6631967578925482e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,819] Trial 4776 finished with value: 0.4037454413630798 and parameters: {'alpha': 0.05157625894857608}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,861] Trial 4777 finished with value: 0.4037454001211763 and parameters: {'alpha': 1.4537166033773042e-06}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,905] Trial 4778 finished with value: 0.40374528014031497 and parameters: {'alpha': 7.876465496931524e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  96%|█████████▌| 4784/5000 [02:27<00:09, 23.98it/s]

[I 2026-06-14 00:50:59,948] Trial 4779 finished with value: 0.40374508066387244 and parameters: {'alpha': 2.5788451175323635e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:50:59,992] Trial 4780 finished with value: 0.40374474754777906 and parameters: {'alpha': 1.6259875620998673e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,035] Trial 4781 finished with value: 0.4037448679705546 and parameters: {'alpha': 1.7586553356420708e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,079] Trial 4782 finished with value: 0.4037452517188805 and parameters: {'alpha': 3.914718982113735e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,117] Trial 4783 finished with value: 0.4037442837172465 and parameters: {'alpha': 1.0193595286495137e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:00,156] Trial 4784 finished with value: 0.4037444954344236 and parameters: {'alpha': 1.0046461003520809e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,197] Trial 4785 finished with value: 0.40374506872175087 and parameters: {'alpha': 2.6690565472609095e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,236] Trial 4786 finished with value: 0.4037448754887539 and parameters: {'alpha': 1.734671792796605e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,277] Trial 4787 finished with value: 0.40374517775965946 and parameters: {'alpha': 4.085807237239447e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,318] Trial 4788 finished with value: 0.40374476837905554 and parameters: {'alpha': 1.7288709961522017e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  96%|█████████▌| 4793/5000 [02:27<00:08, 24.35it/s]

[I 2026-06-14 00:51:00,358] Trial 4789 finished with value: 0.40374524210881824 and parameters: {'alpha': 6.564590164429868e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,402] Trial 4790 finished with value: 0.4037446395763891 and parameters: {'alpha': 1.0035626468663786e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,442] Trial 4791 finished with value: 0.403745022500687 and parameters: {'alpha': 2.76938766476463e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,482] Trial 4792 finished with value: 0.40374432797776194 and parameters: {'alpha': 1.0000021270836338e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,524] Trial 4793 finished with value: 0.4037443024895031 and parameters: {'alpha': 1.0052558904058046e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  96%|█████████▌| 4799/5000 [02:28<00:08, 24.47it/s]

[I 2026-06-14 00:51:00,564] Trial 4794 finished with value: 0.40374533578945193 and parameters: {'alpha': 1.1841926486509342e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,607] Trial 4795 finished with value: 0.4037448144308532 and parameters: {'alpha': 1.736190546327271e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,648] Trial 4796 finished with value: 0.4037450520339192 and parameters: {'alpha': 2.6571478121426246e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,687] Trial 4797 finished with value: 0.40374479263136914 and parameters: {'alpha': 1.7290746352271068e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,728] Trial 4798 finished with value: 0.4037452796306742 and parameters: {'alpha': 5.041857737220465e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  96%|█████████▌| 4803/5000 [02:28<00:08, 24.08it/s]

[I 2026-06-14 00:51:00,771] Trial 4799 finished with value: 0.40374436302000605 and parameters: {'alpha': 1.0045460373409597e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,812] Trial 4800 finished with value: 0.40374435308503864 and parameters: {'alpha': 1.0120745446544323e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,854] Trial 4801 finished with value: 0.40374499986839996 and parameters: {'alpha': 2.6733938329979366e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,896] Trial 4802 finished with value: 0.40374518202850435 and parameters: {'alpha': 3.61930497603716e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:00,938] Trial 4803 finished with value: 0.4037447335138333 and parameters: {'alpha': 1.6546225037538267e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:00,980] Trial 4804 finished with value: 0.40374496559353185 and parameters: {'alpha': 1.7716789916829052e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,022] Trial 4805 finished with value: 0.40671577488146704 and parameters: {'alpha': 717.033891601824}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,062] Trial 4806 finished with value: 0.4037443809716375 and parameters: {'alpha': 1.011219709787278e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,101] Trial 4807 finished with value: 0.40374528260663095 and parameters: {'alpha': 6.065937809336357e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,142] Trial 4808 finished with value: 0.40374506671210525 and parameters: {'alpha': 2.627458717891041e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,182] Trial 4809 finished with value: 0.4037449179287441 and parameters: {'alpha': 1.656258873147787e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  96%|█████████▋| 4814/5000 [02:28<00:07, 24.44it/s]

[I 2026-06-14 00:51:01,225] Trial 4810 finished with value: 0.40374524694706554 and parameters: {'alpha': 4.424719851267573e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,269] Trial 4811 finished with value: 0.40374493070787554 and parameters: {'alpha': 1.71385854340953e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,308] Trial 4812 finished with value: 0.40374473743074213 and parameters: {'alpha': 1.0065784587926295e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,348] Trial 4813 finished with value: 0.4037450540109739 and parameters: {'alpha': 2.874648153448143e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,388] Trial 4814 finished with value: 0.40374484462770516 and parameters: {'alpha': 1.7543305843398383e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:01,429] Trial 4815 finished with value: 0.4037452701880331 and parameters: {'alpha': 8.744944894897986e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,468] Trial 4816 finished with value: 0.4037449723405831 and parameters: {'alpha': 2.6241561784117603e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,511] Trial 4817 finished with value: 0.4037449152262955 and parameters: {'alpha': 1.7422103053452866e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,550] Trial 4818 finished with value: 0.4037452494771914 and parameters: {'alpha': 3.851305775503429e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,589] Trial 4819 finished with value: 0.403745406885338 and parameters: {'alpha': 0.0005732870611186458}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  96%|█████████▋| 4825/5000 [02:29<00:07, 24.75it/s]

[I 2026-06-14 00:51:01,630] Trial 4820 finished with value: 0.40374483836503006 and parameters: {'alpha': 1.7020410857344377e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,670] Trial 4821 finished with value: 0.4037444454198372 and parameters: {'alpha': 1.0156570701979643e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,709] Trial 4822 finished with value: 0.4037452316355374 and parameters: {'alpha': 4.159706691848901e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,749] Trial 4823 finished with value: 0.5066772085998779 and parameters: {'alpha': 14856.117089122872}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,793] Trial 4824 finished with value: 0.403744791724483 and parameters: {'alpha': 1.7637826855756612e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,832] Trial 4825 finished with value: 0.40374502882072894 and parameters: {'alpha': 2.7677142204704202e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  97%|█████████▋| 4832/5000 [02:29<00:06, 24.86it/s]

[I 2026-06-14 00:51:01,874] Trial 4826 finished with value: 0.40374494942081524 and parameters: {'alpha': 1.737888146092171e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,913] Trial 4827 finished with value: 0.40374528567100304 and parameters: {'alpha': 5.8620062878545615e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,953] Trial 4828 finished with value: 0.4037450577435064 and parameters: {'alpha': 2.7248704207244113e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:01,994] Trial 4829 finished with value: 0.40374480203983387 and parameters: {'alpha': 1.7033539287083316e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,033] Trial 4830 finished with value: 0.40374442411262185 and parameters: {'alpha': 1.0116805075887276e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,072] Trial 4831 finished with value: 0.4037445338548329 and parameters: {'alpha': 1.0055257382621335e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  97%|█████████▋| 4838/5000 [02:29<00:06, 25.02it/s]

[I 2026-06-14 00:51:02,114] Trial 4832 finished with value: 0.4037446833637328 and parameters: {'alpha': 1.0076126855714712e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,154] Trial 4833 finished with value: 0.40374507898225814 and parameters: {'alpha': 2.727756028062258e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,193] Trial 4834 finished with value: 0.4037443325682028 and parameters: {'alpha': 1.005967214361807e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,234] Trial 4835 finished with value: 0.4037453705702283 and parameters: {'alpha': 2.430674576602407e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,272] Trial 4836 finished with value: 0.40374453089163337 and parameters: {'alpha': 1.0121463488467214e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,310] Trial 4837 finished with value: 0.4037446264023254 and parameters: {'alpha': 1.0121893208998786e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  97%|█████████▋| 4844/5000 [02:29<00:06, 25.14it/s]

[I 2026-06-14 00:51:02,351] Trial 4838 finished with value: 0.40374526358353774 and parameters: {'alpha': 4.3067716424150254e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,392] Trial 4839 finished with value: 0.42826005324511374 and parameters: {'alpha': 2997.169216555179}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,431] Trial 4840 finished with value: 0.4037452565549591 and parameters: {'alpha': 7.443657458024186e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,471] Trial 4841 finished with value: 0.4037450387842583 and parameters: {'alpha': 2.5679589809314792e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,510] Trial 4842 finished with value: 0.40374491609643787 and parameters: {'alpha': 1.805909160348112e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,549] Trial 4843 finished with value: 0.4037444894847343 and parameters: {'alpha': 1.0141316177679816e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:02,591] Trial 4844 finished with value: 0.40374500433527655 and parameters: {'alpha': 2.8568078525800817e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,632] Trial 4845 finished with value: 0.4037448025423736 and parameters: {'alpha': 1.759172688988971e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,672] Trial 4846 finished with value: 0.403744602791284 and parameters: {'alpha': 1.0035730776617429e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,711] Trial 4847 finished with value: 0.40374533803481055 and parameters: {'alpha': 1.388707576933402e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,749] Trial 4848 finished with value: 0.403744680360499 and parameters: {'alpha': 1.0021330923581987e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  97%|█████████▋| 4853/5000 [02:30<00:05, 24.73it/s]

[I 2026-06-14 00:51:02,794] Trial 4849 finished with value: 0.4037452959655458 and parameters: {'alpha': 4.566441079593898e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,836] Trial 4850 finished with value: 0.40374502867704193 and parameters: {'alpha': 2.680034673641936e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,877] Trial 4851 finished with value: 0.4037448753395583 and parameters: {'alpha': 1.7234450400896537e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,917] Trial 4852 finished with value: 0.40374430057964394 and parameters: {'alpha': 1.0021546272453103e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:02,958] Trial 4853 finished with value: 0.4037452440190156 and parameters: {'alpha': 4.262005976934718e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  97%|█████████▋| 4859/5000 [02:30<00:05, 24.68it/s]

[I 2026-06-14 00:51:02,998] Trial 4854 finished with value: 0.40374450966790076 and parameters: {'alpha': 1.0000361568825796e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,038] Trial 4855 finished with value: 0.4037443322136625 and parameters: {'alpha': 1.007177601749145e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,079] Trial 4856 finished with value: 0.4037450515592686 and parameters: {'alpha': 2.7174135196193264e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,119] Trial 4857 finished with value: 0.40374492221401925 and parameters: {'alpha': 1.7494332864929183e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,161] Trial 4858 finished with value: 0.4037444922259661 and parameters: {'alpha': 1.0078063633743382e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  97%|█████████▋| 4865/5000 [02:30<00:05, 24.94it/s]

[I 2026-06-14 00:51:03,201] Trial 4859 finished with value: 0.40374506117537473 and parameters: {'alpha': 2.6398904332008728e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,242] Trial 4860 finished with value: 0.4037452743671042 and parameters: {'alpha': 8.223327132649193e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,281] Trial 4861 finished with value: 0.403744957245511 and parameters: {'alpha': 1.8085164654303678e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,321] Trial 4862 finished with value: 0.40374526921799136 and parameters: {'alpha': 4.433234241954735e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,361] Trial 4863 finished with value: 0.40374479767566884 and parameters: {'alpha': 1.7561079005760697e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,399] Trial 4864 finished with value: 0.40374452216322165 and parameters: {'alpha': 1.0062361388793673e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  97%|█████████▋| 4870/5000 [02:30<00:05, 24.73it/s]

[I 2026-06-14 00:51:03,442] Trial 4865 finished with value: 0.4037449939464926 and parameters: {'alpha': 2.8281625849990668e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,482] Trial 4866 finished with value: 0.4037448415200957 and parameters: {'alpha': 1.7826036437426907e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,521] Trial 4867 finished with value: 0.4037447265603437 and parameters: {'alpha': 1.0030157594989428e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,562] Trial 4868 finished with value: 0.40374527205469857 and parameters: {'alpha': 6.454842613525058e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,601] Trial 4869 finished with value: 0.4037448958623539 and parameters: {'alpha': 1.7536203862761083e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,640] Trial 4870 finished with value: 0.4037452732343114 and parameters: {'alpha': 4.2452529190986675e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  98%|█████████▊| 4875/5000 [02:31<00:05, 24.71it/s]

[I 2026-06-14 00:51:03,682] Trial 4871 finished with value: 0.4037449988306863 and parameters: {'alpha': 2.5961779947327958e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,723] Trial 4872 finished with value: 0.40374477893907895 and parameters: {'alpha': 1.7506313077783286e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,764] Trial 4873 finished with value: 0.40374485273936084 and parameters: {'alpha': 1.7313942894606308e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,808] Trial 4874 finished with value: 0.403745052662859 and parameters: {'alpha': 2.7659258265789442e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,848] Trial 4875 finished with value: 0.4037452787707466 and parameters: {'alpha': 3.9261066460959715e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  98%|█████████▊| 4880/5000 [02:31<00:04, 24.57it/s]

[I 2026-06-14 00:51:03,888] Trial 4876 finished with value: 0.40374496011952704 and parameters: {'alpha': 1.7145733410232e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,932] Trial 4877 finished with value: 0.4037452831660183 and parameters: {'alpha': 6.65374686407196e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:03,971] Trial 4878 finished with value: 0.40374441398634775 and parameters: {'alpha': 1.0018436074462237e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,011] Trial 4879 finished with value: 0.4037450047741837 and parameters: {'alpha': 2.8088890627600148e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,052] Trial 4880 finished with value: 0.40374498687933824 and parameters: {'alpha': 1.7507918652965017e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:04,092] Trial 4881 finished with value: 0.4037444224931915 and parameters: {'alpha': 1.0106134504538313e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,132] Trial 4882 finished with value: 0.40374522413741615 and parameters: {'alpha': 4.009261020035325e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,173] Trial 4883 finished with value: 0.40374511107981914 and parameters: {'alpha': 2.8770235293806207e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,213] Trial 4884 finished with value: 0.403744867128212 and parameters: {'alpha': 1.7872680786454472e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,252] Trial 4885 finished with value: 0.40374531330635843 and parameters: {'alpha': 1.0526234612390728e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,293] Trial 4886 finished with value: 0.4037449250381341 and parameters: {'alpha': 1.8822328394567445e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  98%|█████████▊| 4892/5000 [02:31<00:04, 24.82it/s]

[I 2026-06-14 00:51:04,333] Trial 4887 finished with value: 0.40374490079185527 and parameters: {'alpha': 1.653458635236839e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,373] Trial 4888 finished with value: 0.40374525900515085 and parameters: {'alpha': 5.1670295695837245e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,415] Trial 4889 finished with value: 0.4037449396766709 and parameters: {'alpha': 1.6808532974694214e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,454] Trial 4890 finished with value: 0.4037450731078944 and parameters: {'alpha': 2.6663611002568414e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,493] Trial 4891 finished with value: 0.40374465460259057 and parameters: {'alpha': 1.0068966826327554e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,534] Trial 4892 finished with value: 0.40374433934325793 and parameters: {'alpha': 1.0071405126252499e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:04,575] Trial 4893 finished with value: 0.403745194809535 and parameters: {'alpha': 3.012494785222077e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,615] Trial 4894 finished with value: 0.4037452706887442 and parameters: {'alpha': 5.377564676672647e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,654] Trial 4895 finished with value: 0.4037449679478323 and parameters: {'alpha': 2.4727049844745855e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,694] Trial 4896 finished with value: 0.403744891358302 and parameters: {'alpha': 1.7715798872070103e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,735] Trial 4897 finished with value: 0.4037444679480347 and parameters: {'alpha': 1.004669508935835e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  98%|█████████▊| 4902/5000 [02:32<00:04, 24.44it/s]

[I 2026-06-14 00:51:04,775] Trial 4898 finished with value: 0.4037448737894757 and parameters: {'alpha': 1.76662465378566e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,821] Trial 4899 finished with value: 0.4037448694240004 and parameters: {'alpha': 1.7074783401748266e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,862] Trial 4900 finished with value: 0.403745209571159 and parameters: {'alpha': 3.18395125113767e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,903] Trial 4901 finished with value: 0.4037452874936874 and parameters: {'alpha': 6.399240854709297e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:04,943] Trial 4902 finished with value: 0.403744895403194 and parameters: {'alpha': 1.7959030699260845e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:04,982] Trial 4903 finished with value: 0.4037452529812531 and parameters: {'alpha': 4.187137460160555e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,022] Trial 4904 finished with value: 0.40374490356374876 and parameters: {'alpha': 1.715010289869692e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,062] Trial 4905 finished with value: 0.4037447429002191 and parameters: {'alpha': 1.0146680783466478e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,101] Trial 4906 finished with value: 0.4037448658794887 and parameters: {'alpha': 1.6901176661897105e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,143] Trial 4907 finished with value: 0.40374497883744304 and parameters: {'alpha': 2.7932635246726975e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:05,183] Trial 4908 finished with value: 0.40374535053413624 and parameters: {'alpha': 1.3522182419578586e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,222] Trial 4909 finished with value: 0.4037444039417666 and parameters: {'alpha': 1.0088534879931388e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,264] Trial 4910 finished with value: 0.40374517080812145 and parameters: {'alpha': 3.8107746759466864e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,303] Trial 4911 finished with value: 0.40374497032177237 and parameters: {'alpha': 1.74287340632678e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,342] Trial 4912 finished with value: 0.4037450620061337 and parameters: {'alpha': 2.907259184190192e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  98%|█████████▊| 4918/5000 [02:32<00:03, 24.71it/s]

[I 2026-06-14 00:51:05,384] Trial 4913 finished with value: 0.40374479741275526 and parameters: {'alpha': 1.7566611531057268e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,425] Trial 4914 finished with value: 0.40374452231206054 and parameters: {'alpha': 1.0110445398350313e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,465] Trial 4915 finished with value: 0.4037453186732616 and parameters: {'alpha': 8.353552167657601e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,505] Trial 4916 finished with value: 0.4037452555924485 and parameters: {'alpha': 4.096414486802499e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,544] Trial 4917 finished with value: 0.40374436568103766 and parameters: {'alpha': 1.0078765133944538e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,583] Trial 4918 finished with value: 0.4037450274688852 and parameters: {'alpha': 2.6963142909609505e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  98%|█████████▊| 4923/5000 [02:33<00:03, 24.73it/s]

[I 2026-06-14 00:51:05,625] Trial 4919 finished with value: 0.40374482152349267 and parameters: {'alpha': 1.7596527812861713e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,664] Trial 4920 finished with value: 0.4037449256547723 and parameters: {'alpha': 1.672760087823496e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,706] Trial 4921 finished with value: 0.4037452959078895 and parameters: {'alpha': 5.313062920394862e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,747] Trial 4922 finished with value: 0.40374471362786823 and parameters: {'alpha': 1.009827754373851e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,788] Trial 4923 finished with value: 0.4037450897850031 and parameters: {'alpha': 2.6839998878829118e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▊| 4928/5000 [02:33<00:02, 24.55it/s]

[I 2026-06-14 00:51:05,830] Trial 4924 finished with value: 0.40374469640684674 and parameters: {'alpha': 1.01304103730997e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,872] Trial 4925 finished with value: 0.4037448440521431 and parameters: {'alpha': 1.776993983357287e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,912] Trial 4926 finished with value: 0.40374508745968085 and parameters: {'alpha': 2.678400313038796e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,953] Trial 4927 finished with value: 0.4037452765085768 and parameters: {'alpha': 4.703645027064774e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:05,994] Trial 4928 finished with value: 0.40374457215547377 and parameters: {'alpha': 1.014169428938224e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▊| 4934/5000 [02:33<00:02, 24.79it/s]

[I 2026-06-14 00:51:06,034] Trial 4929 finished with value: 0.4037444047426971 and parameters: {'alpha': 1.0067083678109701e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,074] Trial 4930 finished with value: 0.40374484586813036 and parameters: {'alpha': 1.733327833878021e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,115] Trial 4931 finished with value: 0.4037450892768129 and parameters: {'alpha': 2.748487573112847e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,155] Trial 4932 finished with value: 0.4037449646259202 and parameters: {'alpha': 1.798831544110522e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,195] Trial 4933 finished with value: 0.4037453075141889 and parameters: {'alpha': 8.561510182316305e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,235] Trial 4934 finished with value: 0.4037452289860547 and parameters: {'alpha': 4.065703590248785e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▉| 4940/5000 [02:33<00:02, 24.63it/s]

[I 2026-06-14 00:51:06,276] Trial 4935 finished with value: 0.4037449796938916 and parameters: {'alpha': 2.6901481670709472e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,316] Trial 4936 finished with value: 0.40374473424396473 and parameters: {'alpha': 1.6429335045781355e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,356] Trial 4937 finished with value: 0.40374497114450314 and parameters: {'alpha': 1.867351716381375e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,396] Trial 4938 finished with value: 0.40374468206610015 and parameters: {'alpha': 1.017442000354744e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,437] Trial 4939 finished with value: 0.4037454065624482 and parameters: {'alpha': 0.00015636712583028117}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▉| 4945/5000 [02:34<00:02, 24.76it/s]

[I 2026-06-14 00:51:06,478] Trial 4940 finished with value: 0.40374442527416676 and parameters: {'alpha': 1.0050181997628653e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,518] Trial 4941 finished with value: 0.40374524822968777 and parameters: {'alpha': 4.447632233110293e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,558] Trial 4942 finished with value: 0.40374498541714915 and parameters: {'alpha': 2.7052043440005687e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,600] Trial 4943 finished with value: 0.40374478706165834 and parameters: {'alpha': 1.7265146560478147e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,639] Trial 4944 finished with value: 0.4037448209174633 and parameters: {'alpha': 1.728125920417147e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,679] Trial 4945 finished with value: 0.40374540451102586 and parameters: {'alpha': 4.690592123412051e-06}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▉| 4950/5000 [02:34<00:02, 24.91it/s]

[I 2026-06-14 00:51:06,720] Trial 4946 finished with value: 0.4037453067324075 and parameters: {'alpha': 5.761004494624153e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,760] Trial 4947 finished with value: 0.4037450274364508 and parameters: {'alpha': 2.5589772515938673e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,798] Trial 4948 finished with value: 0.4037445488346067 and parameters: {'alpha': 1.0111173431886551e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,843] Trial 4949 finished with value: 0.40374476177532936 and parameters: {'alpha': 1.6833865902825717e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,883] Trial 4950 finished with value: 0.403744614358089 and parameters: {'alpha': 1.0042193956989484e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▉| 4955/5000 [02:34<00:01, 24.60it/s]

[I 2026-06-14 00:51:06,925] Trial 4951 finished with value: 0.4037452316237261 and parameters: {'alpha': 3.588873508515911e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:06,967] Trial 4952 finished with value: 0.4037453199775459 and parameters: {'alpha': 1.213639785363297e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,007] Trial 4953 finished with value: 0.40374482326161465 and parameters: {'alpha': 1.7527224941984716e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,046] Trial 4954 finished with value: 0.40374444743854143 and parameters: {'alpha': 1.0073800915802034e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,087] Trial 4955 finished with value: 0.4037450361738814 and parameters: {'alpha': 2.9318398285582495e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:07,128] Trial 4956 finished with value: 0.4037443588323278 and parameters: {'alpha': 1.0034189557720915e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,170] Trial 4957 finished with value: 0.4037444723043416 and parameters: {'alpha': 1.0105381169349118e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,210] Trial 4958 finished with value: 0.40374531522581075 and parameters: {'alpha': 5.939857600042114e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,250] Trial 4959 finished with value: 0.4037449866060778 and parameters: {'alpha': 2.6643321392023298e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,290] Trial 4960 finished with value: 0.4037447667026284 and parameters: {'alpha': 1.682633313054091e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▉| 4964/5000 [02:34<00:01, 22.66it/s]

[I 2026-06-14 00:51:07,330] Trial 4961 finished with value: 0.40374450981876436 and parameters: {'alpha': 1.0031739636202133e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,376] Trial 4962 finished with value: 0.40374507150379924 and parameters: {'alpha': 2.9415043492114578e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,446] Trial 4963 finished with value: 0.40374530275755927 and parameters: {'alpha': 7.03817336632622e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,501] Trial 4964 finished with value: 0.4037450023663844 and parameters: {'alpha': 2.6789407868055474e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▉| 4970/5000 [02:35<00:01, 22.91it/s]

[I 2026-06-14 00:51:07,546] Trial 4965 finished with value: 0.40374496414280925 and parameters: {'alpha': 1.7962944834965493e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,586] Trial 4966 finished with value: 0.40374520178851003 and parameters: {'alpha': 3.96267766375364e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,626] Trial 4967 finished with value: 0.40374488855270113 and parameters: {'alpha': 1.7481754597352948e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,666] Trial 4968 finished with value: 0.4037447536969279 and parameters: {'alpha': 1.7623891464673386e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,707] Trial 4969 finished with value: 0.4037451856084806 and parameters: {'alpha': 3.873203740554765e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744:  99%|█████████▉| 4974/5000 [02:35<00:01, 23.50it/s]

[I 2026-06-14 00:51:07,749] Trial 4970 finished with value: 0.40374438075521407 and parameters: {'alpha': 1.0089920925800006e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,789] Trial 4971 finished with value: 0.40374482357516384 and parameters: {'alpha': 1.752742797659035e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,829] Trial 4972 finished with value: 0.40374471146362995 and parameters: {'alpha': 1.7173096473292846e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,874] Trial 4973 finished with value: 0.4037452434194511 and parameters: {'alpha': 4.394842758721162e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,914] Trial 4974 finished with value: 0.40374500593362406 and parameters: {'alpha': 2.728236402633087e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744: 100%|█████████▉| 4979/5000 [02:35<00:00, 23.94it/s]

[I 2026-06-14 00:51:07,953] Trial 4975 finished with value: 0.40374528636969415 and parameters: {'alpha': 8.078541573529816e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:07,996] Trial 4976 finished with value: 0.40374489597171703 and parameters: {'alpha': 1.7449699754048775e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,036] Trial 4977 finished with value: 0.4037448760833055 and parameters: {'alpha': 1.7865424737854623e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,076] Trial 4978 finished with value: 0.40374506169263524 and parameters: {'alpha': 2.7631759891853773e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,116] Trial 4979 finished with value: 0.4037452645127345 and parameters: {'alpha': 5.464934903395224e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744: 100%|█████████▉| 4985/5000 [02:35<00:00, 24.34it/s]

[I 2026-06-14 00:51:08,156] Trial 4980 finished with value: 0.4037446047443165 and parameters: {'alpha': 1.0080262299658281e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,197] Trial 4981 finished with value: 0.4037447441999902 and parameters: {'alpha': 1.700206719942874e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,239] Trial 4982 finished with value: 0.4040037627956452 and parameters: {'alpha': 86.23163386940959}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,279] Trial 4983 finished with value: 0.40374469163472376 and parameters: {'alpha': 1.007318726711118e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,318] Trial 4984 finished with value: 0.4037450417038609 and parameters: {'alpha': 2.8181245546334466e-08}. Best is trial 3504 with value: 0.40374423498439005.

[I 2026-06-14 00:51:08,360] Trial 4985 finished with value: 0.4037449469154358 and parameters: {'alpha': 1.8364630900990267e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,400] Trial 4986 finished with value: 0.40374541025191457 and parameters: {'alpha': 0.005595765812319877}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,440] Trial 4987 finished with value: 0.4037452467403643 and parameters: {'alpha': 4.3073947215060916e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,481] Trial 4988 finished with value: 0.40374498499895584 and parameters: {'alpha': 2.7873052114348e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,520] Trial 4989 finished with value: 0.4037449331622818 and parameters: {'alpha': 1.8611280253540917e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,561] Trial 4990 finished with value: 0.4037448007952344 and parameters: {'alpha': 1.7089533712032667e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744: 100%|█████████▉| 4996/5000 [02:36<00:00, 24.62it/s]

[I 2026-06-14 00:51:08,604] Trial 4991 finished with value: 0.4037453251897098 and parameters: {'alpha': 1.2040593085313694e-07}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,643] Trial 4992 finished with value: 0.4037448639784133 and parameters: {'alpha': 1.73065760227202e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,682] Trial 4993 finished with value: 0.40374442820482603 and parameters: {'alpha': 1.0040225112377954e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,722] Trial 4994 finished with value: 0.4037451968002723 and parameters: {'alpha': 4.137108999987917e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,761] Trial 4995 finished with value: 0.40374481739496443 and parameters: {'alpha': 1.7204609116203476e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,803] Trial 4996 finished with value: 0.4037451085981063 and parameters: {'alpha': 2.88505502702214e-08}. Best is trial 3504 with value: 0.40374423498439005.

Best trial: 3504. Best value: 0.403744: 100%|██████████| 5000/5000 [02:36<00:00, 31.99it/s]

[I 2026-06-14 00:51:08,847] Trial 4997 finished with value: 0.4037446719036564 and parameters: {'alpha': 1.0086968613113156e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,889] Trial 4998 finished with value: 0.4037452674415013 and parameters: {'alpha': 6.362520853178215e-08}. Best is trial 3504 with value: 0.40374423498439005.
[I 2026-06-14 00:51:08,931] Trial 4999 finished with value: 0.40374494808616157 and parameters: {'alpha': 1.748029274651109e-08}. Best is trial 3504 with value: 0.40374423498439005.

In [58]:
study_ridge.best_value

0.40374423498439005

In [59]:
study_ridge.best_params

{'alpha': 1.0089586116094582e-08}

In [71]:
with open("../data/best_params/cat_params.json", "w") as f:
    json.dump(best_params_cat, f, indent=4)

with open("../data/best_params/lgb_params.json", "w") as f:
    json.dump(best_params_lgb, f, indent=4)

with open("../data/best_params/xgb_params.json", "w") as f:
    json.dump(best_params_xgb, f, indent=4)

with open("../data/best_params/alpha_staking.json", "w") as f:
    json.dump(study_ridge.best_params, f, indent=4)

In [68]:
holdout_stack

,y_true,catboost_100_tuned_pred,xgboost_100_tuned_pred,lightgbm_100_tuned_pred
id,,,,
25445,15.894952,15.773402,15.923815,15.798406
25446,15.789712,15.711569,15.736780,15.689281
25447,15.424949,15.404342,15.296574,15.337484
25448,13.815512,15.659978,15.603654,15.578457
25449,15.894952,15.766640,15.794141,15.824709
...,...,...,...,...
30466,15.725135,15.530609,15.550094,15.567313
30467,15.816991,15.742132,15.785863,15.728267
30468,17.034386,16.606112,16.697931,16.492907
30469,15.757264,15.504860,15.488005,15.478578
30470,15.538277,15.427690,15.348730,15.408597

In [70]:
final_stack_df = pd.concat([np.log1p(stack_df), holdout_stack])
final_stack_df.to_csv('../data/journals/oof_stacking.csv')